### PR TITLE
Add TLD BSA enroll start date to schema

### PR DESCRIPTION
**Pull request by weiminyu**
Also adds a placeholder getter in the Tld class, so that it can be mocked/spied in tests. This way more BSA related code can be submitted before the schema is deployed to prod.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2215)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2215)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 1104 at r1](https://reviewable.io/reviews/google/nomulus/2215#gh-1387469078:-NiorQGTAT4CyXnhe8G8:b2nhb2c) ([raw file](https://github.com/google/nomulus/blob/0666f8ae8836da8c55050128bba2d7b20f88a5d3/core/src/main/java/google/registry/model/tld/Tld.java#L1104)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Useless parameter

The parameter 'enrollTime' is never used.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1605)
</blockquote></details>

Ack

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2215)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot], @sarahcaseybot, and @weiminyu)

___
*[`core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java` line 108 at r1](https://reviewable.io/reviews/google/nomulus/2215#-Nioueej9sGt08g6o30f:-Nioueej9sGt08g6o30g:b2fqou4) ([raw file](https://github.com/google/nomulus/blob/0666f8ae8836da8c55050128bba2d7b20f88a5d3/core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java#L108)):*
> ```Java
> 
>   @Test
>   void testSuccess_updateTld_bsaTimeUnaffected() throws Exception {
> ```

Why does this need to be tested separately? If you dump the class to a file and then re-apply the same file, shouldn't ALL fields remain unchanged?

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2215)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot], @jianglai, and @sarahcaseybot)

___
*[`core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java` line 108 at r1](https://reviewable.io/reviews/google/nomulus/2215#-Nioueej9sGt08g6o30f:-Niovx875XC4Rxf0HfYx:bmc8me2) ([raw file](https://github.com/google/nomulus/blob/0666f8ae8836da8c55050128bba2d7b20f88a5d3/core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java#L108)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Why does this need to be tested separately? If you dump the class to a file and then re-apply the same file, shouldn't ALL fields remain unchanged?
</blockquote></details>

Like the breakglassMode field, this one is not configured from the files in repo. (There is a JsonIgnore annotation).
Eventually we will have a dedicated BSA command that manages this field, since there are required setup/cleanup work to be done
when a tld joins/leaves BSA

**Review by jianglai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2215)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot], @sarahcaseybot, and @weiminyu)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 555 at r1](https://reviewable.io/reviews/google/nomulus/2215#-Nip13-h2iF9T1pC58h6:-Nip13-h2iF9T1pC58h7:b-tf88vc) ([raw file](https://github.com/google/nomulus/blob/0666f8ae8836da8c55050128bba2d7b20f88a5d3/core/src/main/java/google/registry/model/tld/Tld.java#L555)):*
> ```Java
>   // TODO(11/30/2023): uncomment below two lines
>   // /** The start time of this TLD's enrollment in the BSA program, if applicable. */
>   // @JsonIgnore @Nullable DateTime bsaEnrollStartTime;
> ```

I think this comment is in the wrong place?
___
*[`core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java` line 108 at r1](https://reviewable.io/reviews/google/nomulus/2215#-Nioueej9sGt08g6o30f:-Nip18JN7fo-QdNfPBHM:b-i3injz) ([raw file](https://github.com/google/nomulus/blob/0666f8ae8836da8c55050128bba2d7b20f88a5d3/core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java#L108)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Like the breakglassMode field, this one is not configured from the files in repo. (There is a JsonIgnore annotation).
Eventually we will have a dedicated BSA command that manages this field, since there are required setup/cleanup work to be done
when a tld joins/leaves BSA
</blockquote></details>

The comment to the `@JsonIgnore` says "Annotation can be removed once we add the field and annotate it.". So does it mean eventually it will be configured from the files?

**Review by jianglai — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2215)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot] and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/model/tld/Tld.java` line 555 at r1](https://reviewable.io/reviews/google/nomulus/2215#-Nip13-h2iF9T1pC58h6:-NipG1akB0UrfXTUtRj0:b-dyns98) ([raw file](https://github.com/google/nomulus/blob/0666f8ae8836da8c55050128bba2d7b20f88a5d3/core/src/main/java/google/registry/model/tld/Tld.java#L555)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This is a reminder to add this field when the schema is deployed to production. 
We cannot add it now because Hibernate will try to read it and fail the compatibility test.
</blockquote></details>

Oh, sorry I thought it was commenting the method below (getTldStr())...
___
*[`core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java` line 108 at r1](https://reviewable.io/reviews/google/nomulus/2215#-Nioueej9sGt08g6o30f:-NipGbdu3fCgvB-pBsNI:b-6ujdsf) ([raw file](https://github.com/google/nomulus/blob/0666f8ae8836da8c55050128bba2d7b20f88a5d3/core/src/test/java/google/registry/tools/ConfigureTldCommandTest.java#L108)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

In the Tld class, after we uncomment the line: `@JsonIgnore @Nullable DateTime bsaEnrollStartTime;`, we can remove the
JsonIgnore annotation from the getter method.

Without the annotated field jackson treats the getter as a bean method, so we have to annotate the getter for now.
</blockquote></details>

Ah, of course it some under-the-hood annotation magic at play.

**Pull request merged**
