### PR TITLE
Explain why log4j is excluded

### PR DESCRIPTION
**Pull request by weiminyu**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1463)

### CODE REVIEW

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1463#-:-MqecuR40RwKAlMuw7W_:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1463)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[java_common.gradle, line 70 at r1](https://reviewable.io/reviews/google/nomulus/1463#-MqecxVxCqvrufrzq6vd:-MqecxVxCqvrufrzq6ve:b-iyibqh) ([raw file](https://github.com/google/nomulus/blob/4ad3da97338c028310fcb5e846cfd24f946ebcf7/java_common.gradle#L70)):*
> ```Gradle
>     // (FluentLogger) does not depend on it. Its exclusion is not expected to
>     // impact our monitoring and troubleshooting.
>     it.exclude group: 'org.apache.logging.log4j'
> ```

I think we need to add this exclusion to more places than just `java_common.gradle`.  Most of our subprojects don't include `java_common` (including e.g. the proxy).

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1463)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[java_common.gradle, line 70 at r1](https://reviewable.io/reviews/google/nomulus/1463#-MqecxVxCqvrufrzq6vd:-MqpYTlM2n9FQndAiUdg:b-6bmezh) ([raw file](https://github.com/google/nomulus/blob/4ad3da97338c028310fcb5e846cfd24f946ebcf7/java_common.gradle#L70)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think we need to add this exclusion to more places than just `java_common.gradle`.  Most of our subprojects don't include `java_common` (including e.g. the proxy).
</blockquote></details>

java_common is added in the root project config: https://github.com/google/nomulus/blob/6a419eaeb608d10036f10d6ec9df6d8cbd4c0e81/build.gradle#L325

Same change is added in another PR. Reverting this one.

**Comment by weiminyu** [comment]
Same change added by another PR.

**Pull request closed without merging**
