### PR TITLE
Include GracePeriod statuses in RDAP results

### PR DESCRIPTION
**Pull request by gbrodman**
We do this for WHOIS results so we should do it for RDAP results as well (especially since they're mostly already included in the response profile).

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2606)

### CODE REVIEW

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2606)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])

___
*[`core/src/test/java/google/registry/rdap/RdapDomainActionTest.java` line 509 at r1](https://reviewable.io/reviews/google/nomulus/2606#gh-1831774449:-OB2YB-TBe5_xGvLrlyf:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e5619645724f4432ef3d67823e18ec4c8a72e2c9/core/src/test/java/google/registry/rdap/RdapDomainActionTest.java#L509)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unread local variable

Variable 'Domain domain' is never read.

[Show more details](https://github.com/google/nomulus/security/code-scanning/16002)
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/rdap/RdapDomainActionTest.java` line 522 at r1](https://reviewable.io/reviews/google/nomulus/2606#gh-1831774452:-OB2YBNi7K06JzcFTyqM:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e5619645724f4432ef3d67823e18ec4c8a72e2c9/core/src/test/java/google/registry/rdap/RdapDomainActionTest.java#L522)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unread local variable

Variable 'Domain domain' is never read.

[Show more details](https://github.com/google/nomulus/security/code-scanning/16003)
</blockquote></details>

Done.

**Review by gbrodman — COMMENTED** [review]
friendly ping

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2606#-:-OBfso7k6C-s6FvBf7_2:b-50swta)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

**Review by gbrodman — COMMENTED** [review]
friendly ping

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2606#-:-ODDP2TM3OgCvNlpm6Cm:b-50swta)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

**Review by CydeWeys — CHANGES_REQUESTED** [review]
And I assume this passes the RDAP conformance tool?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2606#-:-ODRv2LR1K-5ZpoLK5Sx:b-ss5vuu)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @gbrodman, @github-advanced-security[bot], and @jianglai)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 358 at r2](https://reviewable.io/reviews/google/nomulus/2606#-ODRu7ob9ZeglxuqABbQ:-ODRu7ob9ZeglxuqABbR:b-91ui89) ([raw file](https://github.com/google/nomulus/blob/adb5a9deb7e8c28e0a7f835efb8d1c40f450c1e7/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L358)):*
> ```Java
>     ImmutableSet<EnumToAttributeAdapter.EppEnum> allStatusValues =
>         new ImmutableSet.Builder<EnumToAttributeAdapter.EppEnum>()
>             .addAll(domain.getStatusValues())
> ```

It's minor, but `Sets.union()` might be able to accomplish this with fewer lines of code (and thus be more readable).
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 1058 at r2](https://reviewable.io/reviews/google/nomulus/2606#-ODRuKKhBTBs1tkLhwnQ:-ODRuKKhBTBs1tkLhwnR:b-dzs3ld) ([raw file](https://github.com/google/nomulus/blob/adb5a9deb7e8c28e0a7f835efb8d1c40f450c1e7/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L1058)):*
> ```Java
>    */
>   private static ImmutableSet<RdapStatus> makeStatusValueList(
>       ImmutableSet<? extends EnumToAttributeAdapter.EppEnum> statusValues,
> ```

Might be worth directly importing `EppEnum` into this file?



_Code quote:_
```Java
EppEnum
```
___
*[`core/src/test/java/google/registry/testing/DatabaseHelper.java` line 610 at r2](https://reviewable.io/reviews/google/nomulus/2606#-ODRu_x040zMHuxzO78c:-ODRu_x040zMHuxzO78d:brlm19m) ([raw file](https://github.com/google/nomulus/blob/adb5a9deb7e8c28e0a7f835efb8d1c40f450c1e7/core/src/test/java/google/registry/testing/DatabaseHelper.java#L610)):*
> ```Java
>                     DesignatedContact.create(Type.TECH, contact.createVKey())))
>             .setAuthInfo(DomainAuthInfo.create(PasswordAuth.create("fooBAR")));
>     if (creationTime.plusDays(5).isAfter(now)) {
> ```

Probably not wise to hard-code the domain lifecycle considering that it is configure and has different values on some tests.  See https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/tld/Tld.java;l=418-425;drc=fa377733be7dc097e218cf59b0e9d875e7ab2f26 which I think should be used instead.
___
*[`core/src/test/java/google/registry/testing/DatabaseHelper.java` line 613 at r2](https://reviewable.io/reviews/google/nomulus/2606#-ODRuqblD4DFeimQKYn7:-ODRuqblD4DFeimQKYn8:brhumzt) ([raw file](https://github.com/google/nomulus/blob/adb5a9deb7e8c28e0a7f835efb8d1c40f450c1e7/core/src/test/java/google/registry/testing/DatabaseHelper.java#L613)):*
> ```Java
>       domainBuilder.addGracePeriod(
>           GracePeriod.create(
>               GracePeriodStatus.ADD, repoId, creationTime.plusDays(5), "TheRegistrar", null));
> ```

Same here.

**Review by gbrodman — COMMENTED** [review]
yeah, though it's not really possible to create domains on alpha at the moment (DB is kinda broken and I'm hitting https://github.com/flyway/flyway/issues/2970 when trying to update the DB schema) 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2606#-:-ODSlrI2EIF65LZ376X7:bi12rd2)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @github-advanced-security[bot], and @jianglai)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 358 at r2](https://reviewable.io/reviews/google/nomulus/2606#-ODRu7ob9ZeglxuqABbQ:-ODSfMRG7UMMWSAlqo1P:b8l9g3a) ([raw file](https://github.com/google/nomulus/blob/adb5a9deb7e8c28e0a7f835efb8d1c40f450c1e7/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L358)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It's minor, but `Sets.union()` might be able to accomplish this with fewer lines of code (and thus be more readable).
</blockquote></details>

sure, I used this before because it gives an ImmutableSet explicitly 
___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 1058 at r2](https://reviewable.io/reviews/google/nomulus/2606#-ODRuKKhBTBs1tkLhwnQ:-ODSfHGbEAXOJvscFC5P:b7igvgk) ([raw file](https://github.com/google/nomulus/blob/adb5a9deb7e8c28e0a7f835efb8d1c40f450c1e7/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L1058)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Might be worth directly importing `EppEnum` into this file?
</blockquote></details>

eh sure, this before is what IDEA did by default 
___
*[`core/src/test/java/google/registry/testing/DatabaseHelper.java` line 610 at r2](https://reviewable.io/reviews/google/nomulus/2606#-ODRu_x040zMHuxzO78c:-ODSh6CZ-nm9KNTYR523:b-896fix) ([raw file](https://github.com/google/nomulus/blob/adb5a9deb7e8c28e0a7f835efb8d1c40f450c1e7/core/src/test/java/google/registry/testing/DatabaseHelper.java#L610)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Probably not wise to hard-code the domain lifecycle considering that it is configure and has different values on some tests.  See https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/tld/Tld.java;l=418-425;drc=fa377733be7dc097e218cf59b0e9d875e7ab2f26 which I think should be used instead.
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/testing/DatabaseHelper.java` line 613 at r2](https://reviewable.io/reviews/google/nomulus/2606#-ODRuqblD4DFeimQKYn7:-ODSh6TJ2syykGDlB2Du:b-896fix) ([raw file](https://github.com/google/nomulus/blob/adb5a9deb7e8c28e0a7f835efb8d1c40f450c1e7/core/src/test/java/google/registry/testing/DatabaseHelper.java#L613)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Review by gbrodman — COMMENTED** [review]
jk that's the wrong issue, but there's a flyway versioning issue that i'm fixing separately 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2606#-:-ODgMsUA8UP6je8uxknu:b9prj48)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @github-advanced-security[bot], and @jianglai)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2606)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

___
*[`core/src/main/java/google/registry/rdap/RdapJsonFormatter.java` line 358 at r2](https://reviewable.io/reviews/google/nomulus/2606#-ODRu7ob9ZeglxuqABbQ:-ODgljum58Qx6GnoTaId:bb85ydy) ([raw file](https://github.com/google/nomulus/blob/adb5a9deb7e8c28e0a7f835efb8d1c40f450c1e7/core/src/main/java/google/registry/rdap/RdapJsonFormatter.java#L358)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

sure, I used this before because it gives an ImmutableSet explicitly
</blockquote></details>

Note that it's actually returning a `SetView`, which is itself immutable.

**Review by CydeWeys — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 4 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2606)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

**Pull request merged**
