### PR TITLE
Add sanity checks to history entry construction

### PR DESCRIPTION
**Pull request by CydeWeys**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1156)

### CODE REVIEW

**Review by gbrodman — APPROVED** [review]
:lgtm:, most of these should be caught by the DB anyway but no harm in checking in build

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1156#-:-M_X1OYH4-WzkBgveG5t:bc9fuhj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by CydeWeys — COMMENTED** [review]
Best not to rely on the DB constraints though.  They aren't as tight as we might want for compatibility with all historic data, whereas we can make these `build()` method stricters to get stronger protections on future data.  Note that th registrar id is nullable in the DB schema.

Also it's cleaner to throw an exception immediately when the invalid entity is constructed at the site of construction, rather than much later when a wrapping transaction is executed.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1156#-:-M_X5m4i7QGjdsnmgHbq:b1b7esl)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1156)* status: 2 of 21 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/DedupeRecurringBillingEventIdsCommand.java, line 0 at r2](https://reviewable.io/reviews/google/nomulus/1156#-M_abgE570M4ZoLVDR3q:-M_abgE570M4ZoLVDR3r:bvaa631) ([raw file](https://github.com/google/nomulus/blob/c466edf39e002d3d2ee500a1bd25f97b5b74aba2/core/src/main/java/google/registry/tools/DedupeRecurringBillingEventIdsCommand.java#L0)):*
Do you know if we've actually run this command?

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1156)* status: 1 of 31 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/DedupeRecurringBillingEventIdsCommand.java, line  at r2](https://reviewable.io/reviews/google/nomulus/1156#-M_abgE570M4ZoLVDR3q:-M_gmOuj3lcFRY7AUfa-:bk43vow) ([raw file](https://github.com/google/nomulus/blob/c466edf39e002d3d2ee500a1bd25f97b5b74aba2/core/src/main/java/google/registry/tools/DedupeRecurringBillingEventIdsCommand.java#L)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Do you know if we've actually run this command? 
</blockquote></details>

Yes, this was Shicong's scrap command from last year.  We probably should've deleted it well before now; we've wasted some time migrating stuff in it.

**Review by gbrodman — APPROVED** [review]
> Reviewed 11 of 19 files at r2, 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
