### PR TITLE
Fix console EPP password form, minor adjustments

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2445)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2445)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 62 at r1](https://reviewable.io/reviews/google/nomulus/2445#-Ny0y0Ne5rQkV_D1ZQlR:-Ny0y0Ne5rQkV_D1ZQlS:bhtltf1) ([raw file](https://github.com/google/nomulus/blob/2b0fe771badd285358dbcdc6dc0d56c42b271d02/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L62)):*
> ```Java
>   private final GmailClient gmailClient;
> 
>   private final Optional<PasswordChangeRequest> eppPasswordChangeRequest;
> ```

What happens if we don't use an Optional, and the user doesn't pass in the correct input? I'm hoping it'd be a nice enough error; ideally we don't need an Optional because this is not a GET action. 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 86 at r1](https://reviewable.io/reviews/google/nomulus/2445#-Ny0xnwO4t14GtJPHsYB:-Ny0xnwO4t14GtJPHsYC:b-lr6lw6) ([raw file](https://github.com/google/nomulus/blob/2b0fe771badd285358dbcdc6dc0d56c42b271d02/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L86)):*
> ```Java
>     var errorMsg = "Missing param(s): %s";
>     try {
>       checkArgument(!Strings.isNullOrEmpty(eppRequestBody.registrarId()), errorMsg, "registrarId");
> ```

I think this should be a lot easier after my other PR. After that, we can just let the IllegalArgumentException fall through 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 146 at r1](https://reviewable.io/reviews/google/nomulus/2445#-Ny0xeOC0tI7ZlnziB_o:-Ny0xeOC0tI7ZlnziB_p:b-uy57un) ([raw file](https://github.com/google/nomulus/blob/2b0fe771badd285358dbcdc6dc0d56c42b271d02/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L146)):*
> ```Java
> 
>   @AutoValue
>   public abstract static class PasswordChangeRequest {
> ```

Can we use a record instead of an AutoValue?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2445)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 62 at r1](https://reviewable.io/reviews/google/nomulus/2445#-Ny0y0Ne5rQkV_D1ZQlR:-Ny1aLHO49GSQ88tfHiO:bks79t4) ([raw file](https://github.com/google/nomulus/blob/2b0fe771badd285358dbcdc6dc0d56c42b271d02/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L62)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What happens if we don't use an Optional, and the user doesn't pass in the correct input? I'm hoping it'd be a nice enough error; ideally we don't need an Optional because this is not a GET action.
</blockquote></details>

The last time I checked it throws internal error in the runtime, which doesn't translate well into a response status or message,  that's why we used the same approach with optional for contacts and registrar. 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 86 at r1](https://reviewable.io/reviews/google/nomulus/2445#-Ny0xnwO4t14GtJPHsYB:-Ny1azOY-TqmOkxh-A2t:bb6un1j) ([raw file](https://github.com/google/nomulus/blob/2b0fe771badd285358dbcdc6dc0d56c42b271d02/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L86)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think this should be a lot easier after my other PR. After that, we can just let the IllegalArgumentException fall through
</blockquote></details>

Done
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 146 at r1](https://reviewable.io/reviews/google/nomulus/2445#-Ny0xeOC0tI7ZlnziB_o:-Ny1v8we54TpyaPVCzkr:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2b0fe771badd285358dbcdc6dc0d56c42b271d02/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L146)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Can we use a record instead of an AutoValue?
</blockquote></details>

Done.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2445)* status: all files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 62 at r1](https://reviewable.io/reviews/google/nomulus/2445#-Ny0y0Ne5rQkV_D1ZQlR:-Ny2-HMy1UgIlrLvAFKp:bbm314) ([raw file](https://github.com/google/nomulus/blob/2b0fe771badd285358dbcdc6dc0d56c42b271d02/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L62)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

The last time I checked it throws internal error in the runtime, which doesn't translate well into a response status or message,  that's why we used the same approach with optional for contacts and registrar.
</blockquote></details>

oh that's lame, but oh well not our problem here 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 73 at r2](https://reviewable.io/reviews/google/nomulus/2445#-Ny2-2lp5bJIuB6iJVJs:-Ny2-2lp5bJIuB6iJVJt:biwd34h) ([raw file](https://github.com/google/nomulus/blob/770f58c8672d31a01a112fb5c7bbae90c92eb2b3/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L73)):*
> ```Java
>   }
> 
>   private boolean confirmParamsAvailable() {
> ```

don't think this needs to return anything 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 75 at r2](https://reviewable.io/reviews/google/nomulus/2445#-Ny1ztCj2LldYIzQjiWU:-Ny1ztCj2LldYIzQjiWV:b-rk2s40) ([raw file](https://github.com/google/nomulus/blob/770f58c8672d31a01a112fb5c7bbae90c92eb2b3/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L75)):*
> ```Java
>   private boolean confirmParamsAvailable() {
>     if (!this.eppPasswordChangeRequest.isPresent()) {
>       throw new BadRequestException("Epp Password update body is invalid");
> ```

we could just use checkArgument as well here rather than a separate exception 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 92 at r2](https://reviewable.io/reviews/google/nomulus/2445#-Ny2-6FK5mydHrGkdVhb:-Ny2-6FK5mydHrGkdVhc:b-2d8raw) ([raw file](https://github.com/google/nomulus/blob/770f58c8672d31a01a112fb5c7bbae90c92eb2b3/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L92)):*
> ```Java
>     if (!this.confirmParamsAvailable()) return;
>     var eppRequestBody = this.eppPasswordChangeRequest.get();
>     if (!eppRequestBody.newPassword().equals(eppRequestBody.newPasswordRepeat())) {
> ```

We can still just use `checkArgument` here as well, since it'll also give 401

**Review by gbrodman — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2445)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2445)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 73 at r2](https://reviewable.io/reviews/google/nomulus/2445#-Ny2-2lp5bJIuB6iJVJs:-Ny6bGjb1pZ33AcsIF8M:b-896fix) ([raw file](https://github.com/google/nomulus/blob/770f58c8672d31a01a112fb5c7bbae90c92eb2b3/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L73)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

don't think this needs to return anything
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 75 at r2](https://reviewable.io/reviews/google/nomulus/2445#-Ny1ztCj2LldYIzQjiWU:-Ny6er317by-eUu8VYSL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/770f58c8672d31a01a112fb5c7bbae90c92eb2b3/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L75)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we could just use checkArgument as well here rather than a separate exception
</blockquote></details>

Done.

**Pull request merged**
