### PR TITLE
Remove dual-write of registrar from tool commands

### PR DESCRIPTION
**Pull request by mindhog**
As discussed, we're keeping registrar in the "replicated" category.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/952)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
Could you close b/161237240 after merge?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/952#-:-MSczRJr-QDWlr8B5cXR:blz3xlt)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by mindhog — COMMENTED** [review]
Will do!

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/952#-:-MSd8vNn0Ho9IUrBpV34:bhy9ost)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @CydeWeys and @weiminyu)

**Review by weiminyu — COMMENTED** [review]
-weiminyu

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/952#-:-MSd9lwiC9uSxTqDgvHM:b-if3745)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by weiminyu — COMMENTED** [review]
-reviewer:@weiminyu

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/952#-:-MSdA-DX3GZLjPp01NEY:b-h8n64a)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by CydeWeys — COMMENTED** [review]
There's no dual read / dual write to remove from the registrar settings endpoint used by the registrar console?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/952#-:-MSiyIg9CMmlQljCTsHI:bvv41wb)* status: 0 of 5 files reviewed, all discussions resolved

**Review by mindhog — COMMENTED** [review]
No, there's only a single write there.  Unfortunately it's also an ofy() save, but I think Gus has been working through converting those.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/952#-:-MSm_0kb2dIwLENIRb8G:b-4iod0u)* status: 0 of 5 files reviewed, all discussions resolved

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/952#-:-MSmv5oT39T2mLAYIJkd:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved

**Pull request merged**
