### PR TITLE
Drop DatabaseMigrationStateSchedule table

### PR DESCRIPTION
**Pull request by jianglai**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2002)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2002)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by gbrodman — CHANGES_REQUESTED** [review]
wait, shouldn't this be failing tests? 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2002#-:-NUww2m00inXZ4GZ8kaT:b-c1qr8b)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
Hmm, weird. I guess the test is ran against deployed SQL schema, so if we are adding something, the schema needs to be deployed for the Java tests to pass, but when we are deleting something, there is no such thing as "deployed ORM view of the schema" to run test against?

@weiminyu Is it expected that when dropping a table, the SQL change does NOT have to wait for the Java change to be deployed to pass presubmit tests?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2002#-:-NUwwJG-B0Zv8L6vky4I:b8ra0ss)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
Talked with Weimin, it turned out that this class opted out of the SQL integration tests:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java;drc=b8b1dce40af41248d2e0c0e346d2e7a233423185;l=48

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2002#-:-NV53ZvM58aP7kuEHghr:b-wa9al3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by gbrodman — COMMENTED** [review]
Ah so I guess that counts even though we deleted that line in the previous PR? Weird. In any case I suppose we probably still want to keep this from merging until next week's deployment goes through, which I assume is why you have the "do not merge" tag on. Cool. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2002#-:-NVFfYVO-Qk7JbF6vTp3:b-5at5p7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
Deployment completed.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2002#-:-NVfq-XtEPsM0emr3--P:b-odnvk7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2002)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
