### PR TITLE
Update NPM plugin and hardcode versions of Node / NPM to use

### PR DESCRIPTION
**Pull request by gbrodman**
The plugin we were using before was a bit old (last updated in March
2019) and this one is newer, updated, and updates the package-lock file
with the new dependency upgrades

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/971)

### CODE REVIEW

**Review by mindhog — COMMENTED** [review]
The lockfile does appear to be generated in the build in some cases.  I can do a "./nom_build build" on a clean repository right now and get a different lockfile.

That said, pinning the node version like this seems worthwhile.  How can we verify that it works? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/971#-:-MTvUjAd3qvPsQlpgaUt:b-ii6rbt)* status: 0 of 1 files reviewed, all discussions resolved

**Review by mindhog — COMMENTED** [review]
FWIW, this appears to generate the same diffs I see currently without it.  I'm not sure what that means, I'd like to try changing my npm to see if that makes a difference.

```
diff --git a/package-lock.json b/package-lock.json
index 43c7fd818..2bc5140ec 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -5,6 +5,7 @@
   "requires": true,
   "packages": {
     "": {
+      "name": "nomulus",
       "version": "1.0.0",
       "license": "Apache-2.0",
       "dependencies": {
@@ -225,7 +226,6 @@
       "dependencies": {
         "anymatch": "~3.1.1",
         "braces": "~3.0.2",
-        "fsevents": "~2.3.1",
         "glob-parent": "~5.1.0",
         "is-binary-path": "~2.1.0",
         "is-glob": "~4.0.1",
```

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/971#-:-MTvYZKA2G0gD1vspmq-:blnhwcz)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by gbrodman — COMMENTED** [review]
What command are you running that re-generates the lockfile, then?  I don't know how your Python build script works; I'm just running the Gradle commands. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/971#-:-MTvapTG0ypAd67w3WKE:b-7qf1j6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mindhog — COMMENTED** [review]
It is the equivalent of "./gradlew build"

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/971#-:-MTvcCEQ0aqVhlvVvKgk:bvn629r)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by gbrodman** [comment]
Cool, we got the dependencies updated and the build works now. PTAL?

**Review by mindhog — APPROVED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/971)* status: 3 of 4 files reviewed, all discussions resolved

**Review by mindhog — COMMENTED** [review]
LG.  And building this branch locally leaves my package.json file unsullied, so I think we've nailed it! 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/971#-:-MUAxzhl9V-bxJdGy5zK:bqhrraw)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
sweet!

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/971#-:-MUEhqys39W2LdE6R1oB:b-kfub9m)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
thanks for the help!

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/971#-:-MUEhsYWCz3DL4zp5_-q:b1qtmjs)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
