### PR TITLE
Add discount price to AllocationToken

### PR DESCRIPTION
**Pull request by jicelhay**
Add discountPrice to AllocationToken model and modifies DiscountPriceTokenLogic to calculate domain's cost in create/renew flow considering this discount.

See b/358151081 and go/dreg-allocationtoken-discount for more details.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2559)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2559)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @CydeWeys and @jicelhay)

___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 332 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O70JGsa7eM-MLKtas91:-O70JGsa7eM-MLKtas92:b-cfgef8) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L332)):*
> ```Java
>       if (allocationToken.get().getDiscountPrice() != null) {
>         if (!tld.getCurrency().equals(allocationToken.get().getDiscountPrice().getCurrencyUnit()))
>           throw new AllocationTokenInvalidForCurrencyException();
> ```

Does the formatter not enforce the use of curly braces 100% of the time? I would have assumed that it did! 
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 252 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O70HHm17_SPCj8F7l5M:-O70HHm17_SPCj8F7l5N:bjsz882) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L252)):*
> ```Java
> 
>   /**
>    * A discount that allows to set promotional prices. This field is different from {@code
> ```

nit: "allows one to set" or "allows the setting of" 
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 256 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O70GarO5nkgEZGSlqDv:-O70GarO5nkgEZGSlqDw:b-waw9ky) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L256)):*
> ```Java
>    * discountFraction} that applies a fraction discount to the domain base price.
>    *
>    * <p>Prefer this method of discount when attempting to set a promotional price across domains
> ```

this is kinda nitty, but it's probably better wording to say "...promotional price across TLDs with different base prices" (since any tokens where we're using discounts will be generic across some set of TLDs (or all of them) rather than being associated with one particular domain) 
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 262 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O70BJLv2I9DNIxpvqha:-O70Egq64TopaY_PJDBc:b-khtb4k) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L262)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Hrm, it's annoying that this is necessary.  I wonder if there's a better way to do this projectwide.  (Not in scope for this PR.)
</blockquote></details>

i think this was added with the recent hibernate update unfortunately, not sure if Weimin looked into overriding the project defaults; I don't see any way to do that but I haven't looked in much depth.
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 318 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O708iN-40vdMz07GH-C:-O70HXIzAKPEUmtskWeM:bq0j8bz) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L318)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should return `Optional<Money>` to really flag it at the call sites that this will frequently be empty.  Also this makes nullness checking at the callsites nicer.

Also, not relevant here, but in general, if you do have a method that can return null, it needs to be annotated with `@Nullable`.  Since this will be returning an Optional though, it won't be able to be null, so then that wouldn't be appropriate after that change is made.
</blockquote></details>

adding on, I think the reason why getDiscountFraction doesn't return an Optional is because the operation of "reduce a price by 0%" works even in the 0 case, in a way that a null Money object does not

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2559)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 332 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O70JGsa7eM-MLKtas91:-O7345dZBIH1dsXRhZZv:bobgchn) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L332)):*
<details><summary><i>Previously, jicelhay (Juan Celhay) wrote…</i></summary><blockquote>

No corrections from formatter, adding braces because throw is in new line.
</blockquote></details>

This might be something we silently lost in the Piper -> GitHub transition without realizing (because the rest of us are religious about doing it on our own anyway).  Wonder if we can configure things here to always require it.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2559)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @jicelhay)

___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 159 at r2](https://reviewable.io/reviews/google/nomulus/2559#-O735Jt200DltQPS_VXh:-O735Jt200DltQPS_VXi:bszh8rm) ([raw file](https://github.com/google/nomulus/blob/cddb96f4f37328a213b98b2cf59bdce6f484786d/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L159)):*
> ```Java
>       throws AllocationTokenInvalidForPremiumNameException {
>     if (token.isPresent()
>         && (token.get().getDiscountFraction() != 0.0 || token.get().getDiscountPrice() != null)
> ```

This is now an error (IntelliJ should be warning you of such?).  It should be token.get().getDiscountPrice().isPresent().  Make sure to use IntelliJ to see all callsites of `getDiscountPrice()` and verify that they're all now using Optional correctly rather than the previous nullable value.

Also I think this may be exposing the fact that there is a test for this case missing?  Seems like there should be a test case somewhere that has a configured token with no discounted price on it that throws `AllocationTokenInvalidForPremiumNameException`.  Basically, the case where `Optional<Money>` is empty because it's wrapping a null value, but an empty Optional is itself not null and will incorrectly go into this conditional.
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 318 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O708iN-40vdMz07GH-C:-O734P081q3aUcHiB9DI:b-wvpp2o) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L318)):*
<details><summary><i>Previously, jicelhay (Juan Celhay) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@Gus That's true, but also, the default value of a double is 0.0 (it cannot be null unless it's a `Double`, which it's not here), whereas the default value of a `Money` is `null`.  So that's two reasons there needs to be different handling.
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 319 at r2](https://reviewable.io/reviews/google/nomulus/2559#-O734eEu8q_W8dVkBX4X:-O734eEu8q_W8dVkBX4Y:b-ul4tp6) ([raw file](https://github.com/google/nomulus/blob/cddb96f4f37328a213b98b2cf59bdce6f484786d/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L319)):*
> ```Java
> 
>   public Optional<Money> getDiscountPrice() {
>     return Optional.of(discountPrice);
> ```

This needs to be `Optional.ofNullable(discountPrice)`, otherwise it will throw an exception when `discountPrice` is null per the API docs: https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#of-T-

**Review by jicelhay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2559)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 332 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O70JGsa7eM-MLKtas91:-O79ll_t9r6oBHl4JKdG:b-6h8mxu) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L332)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This might be something we silently lost in the Piper -> GitHub transition without realizing (because the rest of us are religious about doing it on our own anyway).  Wonder if we can configure things here to always require it.
</blockquote></details>

Created b/368306591 and assigned it to me.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2559)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @jicelhay)

___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 332 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O70JGsa7eM-MLKtas91:-O7AGfGF0MGpvzTTyolj:bq0hulb) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L332)):*
<details><summary><i>Previously, jicelhay (Juan Celhay) wrote…</i></summary><blockquote>

Created b/368306591 and assigned it to me.
</blockquote></details>

we already have a Checkstyle check for that (look for NeedBraces in config/checkstyle/checkstyle.xml, but it's currently set at warning. I guess we could also change that (and probably others too) to "error" severity. 
___
*[`core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java` line 774 at r3](https://reviewable.io/reviews/google/nomulus/2559#-O7AIFh4608xzWr-Oen_:-O7AIFh4608xzWr-Oena:bmfskmt) ([raw file](https://github.com/google/nomulus/blob/c47f82175460058156a08b4d91c2002f44748b31/core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java#L774)):*
> ```Java
> 
>   @Test
>   void testGetDomainTransferPrice_premiumDomain_default_premiumRenewalPrice() throws EppException {
> ```

why are we deleting these tests here? I'm not sure if they're related

**Review by jicelhay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2559)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java` line 774 at r3](https://reviewable.io/reviews/google/nomulus/2559#-O7AIFh4608xzWr-Oen_:-O7AVGSt4zWUFMIj0Wkm:b-snsisu) ([raw file](https://github.com/google/nomulus/blob/c47f82175460058156a08b4d91c2002f44748b31/core/src/test/java/google/registry/flows/domain/DomainPricingLogicTest.java#L774)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

why are we deleting these tests here? I'm not sure if they're related
</blockquote></details>

This wasn't intentional, re-added them.

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2559)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2559)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jicelhay)

___
*[`core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java` line 332 at r1](https://reviewable.io/reviews/google/nomulus/2559#-O70JGsa7eM-MLKtas91:-O7UR2hgC18B7yTmQtCF:bcg296n) ([raw file](https://github.com/google/nomulus/blob/1a2f8ceeaa3bbde97c72a7c001656aaef58d2975/core/src/main/java/google/registry/flows/domain/DomainPricingLogic.java#L332)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we already have a Checkstyle check for that (look for NeedBraces in config/checkstyle/checkstyle.xml, but it's currently set at warning. I guess we could also change that (and probably others too) to "error" severity.
</blockquote></details>

Yeah I think we can safely change that one to error, if you want to go ahead and do that Gus.

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2559)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jicelhay)

**Pull request merged**
