### PR TITLE
Sometimes include deletion times in domain-list exports

### PR DESCRIPTION
**Pull request by gbrodman**
We only include the deletion time if the domain is in the 5-day PENDING_DELETE period after the 30 day REDEMPTION period. For all other domains, we just have an empty string as that field.

This is behind a feature flag so that we can control when it is enabled

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2602)

### CODE REVIEW

**Comment by gbrodman** [comment]
thoughts on this approach? the SQL is a bit messier but we don't have to lead everything and we can just put it behind a feature flag until we're ready to enable it

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 177 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsKd2tA3B-ntcjnSU9:-OAsKd2tA3B-ntcjnSUA:bjwb9no) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L177)):*
> ```Java
>       return FeatureFlag.isActiveNow(
>           FeatureFlag.FeatureName.INCLUDE_PENDING_DELETE_DATE_FOR_DOMAINS);
>     } catch (FeatureFlag.FeatureFlagNotFoundException e) {
> ```

A bit of a code smell here ... perhaps we want a method on `FeatureFlag` that returns if the flag is active and exists, and otherwise, returns false rather than an exception?

Or something like this?

`boolean isActiveNowOrElse(FeatureName featureFlagName, boolean defaultValue) { ... }`

```
Optional<Boolean> isActiveNow(FeatureName featureFlagName) { ... }

//from callsite:
return isActiveNow(INCLUDE_PENDING_DELETE_DATE_FOR_DOMAINS).orElse(false);
```

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsM9nrEr3v3XMqOlU1:-OAsM9nrEr3v3XMqOlU2:b-f04rr0) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L69)):*
> ```Java
>       "SELECT domainName FROM Domain WHERE tld = :tld AND deletionTime > :now ORDER by domainName";
>   private static final String SELECT_DOMAINS_AND_DELETION_TIMES_STATEMENT =
>       "SELECT d.domain_name, d.deletion_time, d.statuses, gp.type FROM \"Domain\" d LEFT JOIN"
> ```

Use multi-line Java string syntax here, it'll be clearer.

Also line-wrapping should be based on keeping clauses together, rather than just at arbitrary line limits.
___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsMVGg44J_P8fEsKfI:-OAsMVGg44J_P8fEsKfJ:bi023s6) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L70)):*
> ```Java
>   private static final String SELECT_DOMAINS_AND_DELETION_TIMES_STATEMENT =
>       "SELECT d.domain_name, d.deletion_time, d.statuses, gp.type FROM \"Domain\" d LEFT JOIN"
>           + " (SELECT * FROM \"GracePeriod\" WHERE type = 'REDEMPTION') AS gp ON d.repo_id ="
> ```

Feels like this shouldn't be a `SELECT *` here -- just get the fields you need.

Also, there are nearly 20k REDEMPTION grace period rows in this table in production right now.  That seems inefficient to repeatedly load all of them for each TLD's query, especially the small TLDs that have almost no domains.  It seems like the more performant way to write this query would be to directly JOIN the Domain table to this table on `domain_repo_id` rather than joining to all rows selected by a sub-query and then filtering afterwards.

Also I think you want to filter to just `GracePeriod`s that have an `expiration_time` greater than NOW, just in case there is an orphaned expired grace period row somehow.
___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 134 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsLdnZ33_QSIJ0MqU9:-OAsLdn_7mZsefVSuE6z:bvb2ib7) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L134)):*
> ```Java
>     verifyNotNull(driveConnection, "Expecting non-null driveConnection");
>     String filename =
>         includeDeletionTimes ? REGISTERED_DOMAINS_CSV_FILENAME : REGISTERED_DOMAINS_TXT_FILENAME;
> ```

I don't think we should be changing the file name here.  Registrars likely depend on the name being the same, and leaving orphaned old copies of the list indefinitely once the feature flag date comes isn't a good idea.

**Review by CydeWeys — COMMENTED** [review]
The feature flag is a good idea btw, as we'll need to let registrars know ahead of time that we're adding a column to the file as it might break their existing uses of it (unless we want to keep writing the existing file in the existing format and then also write a new file with the new field, but that's probably unnecessary).

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602#-:-OAsPa7U6yepVOhfYatq:bta6bjy)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsM9nrEr3v3XMqOlU1:-OAscqid7uB7WTHMYQIp:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L69)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use multi-line Java string syntax here, it'll be clearer.

Also line-wrapping should be based on keeping clauses together, rather than just at arbitrary line limits.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsMVGg44J_P8fEsKfI:-OAsZpLNAUww6u-OkwMV:bg6ni4h) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L70)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Feels like this shouldn't be a `SELECT *` here -- just get the fields you need.

Also, there are nearly 20k REDEMPTION grace period rows in this table in production right now.  That seems inefficient to repeatedly load all of them for each TLD's query, especially the small TLDs that have almost no domains.  It seems like the more performant way to write this query would be to directly JOIN the Domain table to this table on `domain_repo_id` rather than joining to all rows selected by a sub-query and then filtering afterwards.

Also I think you want to filter to just `GracePeriod`s that have an `expiration_time` greater than NOW, just in case there is an orphaned expired grace period row somehow.
</blockquote></details>

the reason not to join it directly on the Domain table is that there can be potentially multiple grace periods per domain and doing the join directly would result in duplicate rows for those domains for which there are multiple grace periods. Filtering to only REDEMPTION grace periods before doing the join fixes this. 

can do the rest though. Fortunately the expiration_time addition doesn't change anything with our existing DB. 
___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 177 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsKd2tA3B-ntcjnSU9:-OAsgtCh5MWiK9-wzDYJ:b-1c71n1) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L177)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

A bit of a code smell here ... perhaps we want a method on `FeatureFlag` that returns if the flag is active and exists, and otherwise, returns false rather than an exception?

Or something like this?

`boolean isActiveNowOrElse(FeatureName featureFlagName, boolean defaultValue) { ... }`

```
Optional<Boolean> isActiveNow(FeatureName featureFlagName) { ... }

//from callsite:
return isActiveNow(INCLUDE_PENDING_DELETE_DATE_FOR_DOMAINS).orElse(false);
```
</blockquote></details>

Yeah that works, basically.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 134 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsLdnZ33_QSIJ0MqU9:-OAxXEDw9uR_j7evoA_H:b804u6x) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L134)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Wouldn't it be weird to have a CSV with an extension of .txt? idk
</blockquote></details>

Then you'll have to go through and delete all the old .txt files that aren't being update anymore once we do the change-over.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsMVGg44J_P8fEsKfI:-OAxXYcS8JxAKfzpjkNv:b-6taf92) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L70)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

the reason not to join it directly on the Domain table is that there can be potentially multiple grace periods per domain and doing the join directly would result in duplicate rows for those domains for which there are multiple grace periods. Filtering to only REDEMPTION grace periods before doing the join fixes this. 

can do the rest though. Fortunately the expiration_time addition doesn't change anything with our existing DB.
</blockquote></details>

Why doesn't a filter after the JOIN work?

`SELECT _____ FROM Domain JOIN GracePeriod ON _______ WHERE gp.type IS NULL OR gp.type = 'REDEMPTION' AND gp.expiration_time > ______ AND _______`

That'll prevent loading up all the 20k redemptions that aren't applicable for this TLD, plus won't have any duplicate rows, as there will either be a single row with type is null if there wasn't a GracePeriod to match, or a single row with type is redemption if there were GracePeriods to match (as there can't be dupes).

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsMVGg44J_P8fEsKfI:-OAxc1yH2y6CFb9g7SDr:bt7briq) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L70)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why doesn't a filter after the JOIN work?

`SELECT _____ FROM Domain JOIN GracePeriod ON _______ WHERE gp.type IS NULL OR gp.type = 'REDEMPTION' AND gp.expiration_time > ______ AND _______`

That'll prevent loading up all the 20k redemptions that aren't applicable for this TLD, plus won't have any duplicate rows, as there will either be a single row with type is null if there wasn't a GracePeriod to match, or a single row with type is redemption if there were GracePeriods to match (as there can't be dupes).
</blockquote></details>

I tried that before, too. It then doesn't include domains for which there *are* valid grace periods that are something other than REDEMPTION.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsMVGg44J_P8fEsKfI:-OAxcpkV-u6fLgNjt28R:btdprwp) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L70)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I tried that before, too. It then doesn't include domains for which there *are* valid grace periods that are something other than REDEMPTION.
</blockquote></details>

with more data:

```
postgres=> select count(distinct d.repo_id) FROM "Domain" d LEFT JOIN "GracePeriod"  gp ON d.repo_id = gp.domain_repo_id WHERE (gp.type IS NULL or gp.type = 'REDEMPTION') AND d.tld = 'dev' AND deletion_time > CAST('2024-11-04T12:00:00.000Z' AS timestamptz);
 count  
--------
 427055
(1 row)

postgres=> select count(distinct d.repo_id) FROM "Domain" d LEFT JOIN (SELECT type, domain_repo_id FROM "GracePeriod" WHERE type = 'REDEMPTION' AND expiration_time > CAST('2024-11-04T12:00:00.000Z' AS timestamptz)) AS gp ON d.repo_id = gp.domain_repo_id WHERE d.tld = 'dev' AND d.deletion_time > CAST('2024-11-04T12:00:00.000Z' AS timestamptz);
 count  
--------
 447075
(1 row)

postgres=> select count(distinct d.repo_id) FROM "Domain" d WHERE d.tld = 'dev' AND d.deletion_time > CAST('2024-11-04T12:00:00.000Z' AS timestamptz);
 count  
--------
 447075
(1 row)

```

(note that you get the same results with count(*) versus count(distinct repo_id) 
___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 134 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsLdnZ33_QSIJ0MqU9:-OAxchmXACrvmuzQZeSS:bgvalpo) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L134)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Then you'll have to go through and delete all the old .txt files that aren't being update anymore once we do the change-over.
</blockquote></details>

yeah i don't massively care since I can see the arguments either way. I'll just do the txt file

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`core/src/main/java/google/registry/export/ExportDomainListsAction.java` line 70 at r1](https://reviewable.io/reviews/google/nomulus/2602#-OAsMVGg44J_P8fEsKfI:-OB1by6SAQqu_ihRQTGs:bf4j0uu) ([raw file](https://github.com/google/nomulus/blob/ea62366f6c670ee9e958900bba167bb34074890e/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L70)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

with more data:

```
postgres=> select count(distinct d.repo_id) FROM "Domain" d LEFT JOIN "GracePeriod"  gp ON d.repo_id = gp.domain_repo_id WHERE (gp.type IS NULL or gp.type = 'REDEMPTION') AND d.tld = 'dev' AND deletion_time > CAST('2024-11-04T12:00:00.000Z' AS timestamptz);
 count  
--------
 427055
(1 row)

postgres=> select count(distinct d.repo_id) FROM "Domain" d LEFT JOIN (SELECT type, domain_repo_id FROM "GracePeriod" WHERE type = 'REDEMPTION' AND expiration_time > CAST('2024-11-04T12:00:00.000Z' AS timestamptz)) AS gp ON d.repo_id = gp.domain_repo_id WHERE d.tld = 'dev' AND d.deletion_time > CAST('2024-11-04T12:00:00.000Z' AS timestamptz);
 count  
--------
 447075
(1 row)

postgres=> select count(distinct d.repo_id) FROM "Domain" d WHERE d.tld = 'dev' AND d.deletion_time > CAST('2024-11-04T12:00:00.000Z' AS timestamptz);
 count  
--------
 447075
(1 row)

```

(note that you get the same results with count(*) versus count(distinct repo_id)
</blockquote></details>

After mutual in-person investigation, the sub-query just isn't that slow (<200ms on prod).  Running it 46 times per day on replica is just not a big deal.

**Review by CydeWeys — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2602)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
