### PR TITLE
Add REGISTER_BSA allocation type

### PR DESCRIPTION
**Pull request by weiminyu**
Add a new type to allow creation of domains blocked by BSA.

Except for the BSA semantics, the new type behaves exactly like SINGLE_USE.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2319)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2319)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @weiminyu)

___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 143 at r1](https://reviewable.io/reviews/google/nomulus/2319#-Nq-C3jI8QjY90lnq8BI:-Nq-C3jI8QjY90lnq8BJ:b-lks0qd) ([raw file](https://github.com/google/nomulus/blob/68d5baec34a197630bbe1d532a650f79a0e55319/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L143)):*
> ```Java
> 
>     /** Returns true if token should be invalidated after use. */
>     public boolean isOneTimeUse() {
> ```

Add a private field to the `TokenType` enum instead, with a constructor, and do `SINGLE_USE(true), ALLOW_BSA(true)` and `....(false)` for everything else.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2319)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 140 at r1](https://reviewable.io/reviews/google/nomulus/2319#-Nq-F4B8DB6TyBBdhuqV:-Nq-F4B8DB6TyBBdhuqW:b-xoea0g) ([raw file](https://github.com/google/nomulus/blob/68d5baec34a197630bbe1d532a650f79a0e55319/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L140)):*
> ```Java
>      * {@link #SINGLE_USE}.
>      */
>     ALLOW_BSA;
> ```

I think a better name for this would be `REGISTER_BSA` or `BSA_REGISTRATION` or `BSA_CREATE` or something like that.  "Allow BSA" sounds a little bit too much like a token behavior rather than a token type (I can't explain why but that's how it reads to me).

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2319)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 140 at r1](https://reviewable.io/reviews/google/nomulus/2319#-Nq-F4B8DB6TyBBdhuqV:-Nq3_HuxEMFSJaOI-tXL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/68d5baec34a197630bbe1d532a650f79a0e55319/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L140)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think a better name for this would be `REGISTER_BSA` or `BSA_REGISTRATION` or `BSA_CREATE` or something like that.  "Allow BSA" sounds a little bit too much like a token behavior rather than a token type (I can't explain why but that's how it reads to me).
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/domain/token/AllocationToken.java` line 143 at r1](https://reviewable.io/reviews/google/nomulus/2319#-Nq-C3jI8QjY90lnq8BI:-Nq3_Ksw5dhHQaSFeoQK:b-896fix) ([raw file](https://github.com/google/nomulus/blob/68d5baec34a197630bbe1d532a650f79a0e55319/core/src/main/java/google/registry/model/domain/token/AllocationToken.java#L143)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Add a private field to the `TokenType` enum instead, with a constructor, and do `SINGLE_USE(true), ALLOW_BSA(true)` and `....(false)` for everything else.
</blockquote></details>

Done.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2319)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @weiminyu)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 335 at r2](https://reviewable.io/reviews/google/nomulus/2319#-Nq97dxs5L30I39_Bly7:-Nq97dxtAMaFs0pZhapf:bq59cyc) ([raw file](https://github.com/google/nomulus/blob/94608d91138a95705b29e5cc8328b3b6a3c22774/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L335)):*
> ```Java
>     }
>     if (!isRegisterBsaCreate(domainName, allocationToken)) {
>       verifyNotBlockedByBsa(domainLabel, tld, now);
> ```

This might be clearer if you changed the method signature of `verifyNotBlockedByBsa()` to add an `Optional<AllocationToken>` parameter.  Then it would be clear in there and at callsites that a valid allocation token being present means that the BSA block can be overridden.  Then you don't need the conditional here or in the check flow.

See `boolean isValidReservedCreate(InternetDomainName domainName, Optional<AllocationToken> token)` and `boolean isAnchorTenant(InternetDomainName domainName, Optional<AllocationToken> token, Optional<MetadataExtension> metadataExtension)` for close analogues implementing the kind of scheme I'm suggesting here.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2319)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @weiminyu)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 335 at r2](https://reviewable.io/reviews/google/nomulus/2319#-Nq97dxs5L30I39_Bly7:-Nq98LCv2JjDR74yA7VE:bnjor4p) ([raw file](https://github.com/google/nomulus/blob/94608d91138a95705b29e5cc8328b3b6a3c22774/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L335)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This might be clearer if you changed the method signature of `verifyNotBlockedByBsa()` to add an `Optional<AllocationToken>` parameter.  Then it would be clear in there and at callsites that a valid allocation token being present means that the BSA block can be overridden.  Then you don't need the conditional here or in the check flow.

See `boolean isValidReservedCreate(InternetDomainName domainName, Optional<AllocationToken> token)` and `boolean isAnchorTenant(InternetDomainName domainName, Optional<AllocationToken> token, Optional<MetadataExtension> metadataExtension)` for close analogues implementing the kind of scheme I'm suggesting here.
</blockquote></details>

(I suppose the check flow logic works a little bit differently; it's not actually calling `verifyNotBlockedByBsa()`)

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2319)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 335 at r2](https://reviewable.io/reviews/google/nomulus/2319#-Nq97dxs5L30I39_Bly7:-Nq9LB0_B1FwKJrI2f1X:b-896fix) ([raw file](https://github.com/google/nomulus/blob/94608d91138a95705b29e5cc8328b3b6a3c22774/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L335)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

(I suppose the check flow logic works a little bit differently; it's not actually calling `verifyNotBlockedByBsa()`)
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2319#-:-Nq9NaVh7XIET6ZK-5eK:bnfp4nl)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
