### PR TITLE
Convert 3 classes from ofy -> tm

### PR DESCRIPTION
**Pull request by mindhog**
Convert SyncGroupMembersAction, SyncRegistrarsSheet and
IcannReportingUploadAction and their test cases to use TransactionManager and
dual-test them so we know they work in jpa.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1034)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1034)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java, line 65 at r1](https://reviewable.io/reviews/google/nomulus/1034#-MWahOLy7JdFMia4pGJj:-MWahOLy7JdFMia4pGJk:b-8kbvx2) ([raw file](https://github.com/google/nomulus/blob/b3a761ab27f8263a195eeb7717914fae51810343/core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java#L65)):*
> ```Java
>   boolean wereRegistrarsModified() {
>     Optional<Cursor> cursor =
>         tm().transact(() -> tm().loadByKeyIfPresent(Cursor.createGlobalVKey(SYNC_REGISTRAR_SHEET)));
> ```

slight nit, we may wish to use `transactIfJpaTm()` here since i don't think we technically need a transaction in ofy-land 

Same comment for all the other instances like this across all the other production and test files, I believe 
___
*[core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/1034#-MWahjvl9em-2moaYzDP:-MWahjvl9em-2moaYzDQ:b4sumiz) ([raw file](https://github.com/google/nomulus/blob/b3a761ab27f8263a195eeb7717914fae51810343/core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java#L84)):*
> ```Java
>     createTld("example");
>     // Remove Registrar entities created by AppEngineRule (and RegistrarContact's, for jpa)
>     if (!tm().isOfy()) {
> ```

Out of curiosity, what happens if this code were to run in ofy-land?

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1034)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java, line 65 at r1](https://reviewable.io/reviews/google/nomulus/1034#-MWahOLy7JdFMia4pGJj:-MWdaWht9CZqpJChEGtw:b-dvla44) ([raw file](https://github.com/google/nomulus/blob/b3a761ab27f8263a195eeb7717914fae51810343/core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java#L65)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

slight nit, we may wish to use `transactIfJpaTm()` here since i don't think we technically need a transaction in ofy-land 

Same comment for all the other instances like this across all the other production and test files, I believe 
</blockquote></details>

If we can run the "load" methods non-transactionally in datastore, it seems like we should make this work in JPA as well by making those methods transaction in JpaTransactionManagerImpl.  Do you agree?  
___
*[core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/1034#-MWahjvl9em-2moaYzDP:-MWdcB_OAn-Q6eRGFuHf:bkom47e) ([raw file](https://github.com/google/nomulus/blob/b3a761ab27f8263a195eeb7717914fae51810343/core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java#L84)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Out of curiosity, what happens if this code were to run in ofy-land? 
</blockquote></details>

"Only ancestor queries are allowed inside transactions."  Another ugly behavioral discrepancy.  I vaguely prefer the `isOfy()` check here to `transactIfJpaTm()`, as this code doesn't need to run at all in ofy without foreign-key enforcement.

But once again, I think we'd be better off if we made the transaction internal to `JTMI.loadAllOf()`.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1034)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

___
*[core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java, line 65 at r1](https://reviewable.io/reviews/google/nomulus/1034#-MWahOLy7JdFMia4pGJj:-MWe4ArDDlBp-0AuFNPV:bozcf1i) ([raw file](https://github.com/google/nomulus/blob/b3a761ab27f8263a195eeb7717914fae51810343/core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java#L65)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

If we can run the "load" methods non-transactionally in datastore, it seems like we should make this work in JPA as well by making those methods transaction in JpaTransactionManagerImpl.  Do you agree?  
</blockquote></details>

OK after discussion, let's add DatabaseHelper methods whenever
___
*[core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/1034#-MWahjvl9em-2moaYzDP:-MWe4F225yDhxM_ancpo:b91loq0) ([raw file](https://github.com/google/nomulus/blob/b3a761ab27f8263a195eeb7717914fae51810343/core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java#L84)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

"Only ancestor queries are allowed inside transactions."  Another ugly behavioral discrepancy.  I vaguely prefer the `isOfy()` check here to `transactIfJpaTm()`, as this code doesn't need to run at all in ofy without foreign-key enforcement.

But once again, I think we'd be better off if we made the transaction internal to `JTMI.loadAllOf()`.
</blockquote></details>

ugh yeah that's annoying, and yeah the isOfy check would be required here

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1034)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java, line 65 at r1](https://reviewable.io/reviews/google/nomulus/1034#-MWahOLy7JdFMia4pGJj:-MWejdttCPoS86bKq0xv:b-2gjicj) ([raw file](https://github.com/google/nomulus/blob/b3a761ab27f8263a195eeb7717914fae51810343/core/src/main/java/google/registry/export/sheet/SyncRegistrarsSheet.java#L65)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

OK after discussion, let's add DatabaseHelper methods whenever
</blockquote></details>

Converted to transactIfJpaTm. Also fixed a transaction issue in the ICANN reporting.

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1034)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/1034#-MWahjvl9em-2moaYzDP:-MWeomVW9aFt9cU1-pdv:bb6sh2i) ([raw file](https://github.com/google/nomulus/blob/b3a761ab27f8263a195eeb7717914fae51810343/core/src/test/java/google/registry/export/sheet/SyncRegistrarsSheetTest.java#L84)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ugh yeah that's annoying, and yeah the isOfy check would be required here 
</blockquote></details>

Ack.

**Review by gbrodman — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1034)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1034)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Review by mindhog — COMMENTED** [review]
PTAL?  I've  restructured IcannReportingUploadAction to run the entire action in its own transaction instead of having nested transactions for each item.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1034#-:-MWyieBCD7wB1Ro7eoFG:b-pfbeia)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Review by gbrodman — APPROVED** [review]
Yeah, I think it looks good to me 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1034#-:-MWytnCu269lPPwAxNgC:b-o0grnu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Pull request merged**
