### PR TITLE
Remove SQL credentials from Keyring

### PR DESCRIPTION
**Pull request by weiminyu**
Remove SQL credentials from Keyring. SQL credentials will be managed by
an automated system (go/dr-sql-security) and the keyring is no longer a
suitable place to hold them.

Also stopped loading SQL credentials from they keyring for comparison
with those from the secret manager.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1059)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
nice, glad to see that we can remove these, that the secret manager is all good

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1059#-:-MXdmFU92EXlK9nCfpXY:bnwb083)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @weiminyu)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 345 at r1](https://reviewable.io/reviews/google/nomulus/1059#-MXdmhUq6XJ0THsR5ZnO:-MXdmhUr-PUtruXLiiEC:b3npbgk) ([raw file](https://github.com/google/nomulus/blob/102808f0040dddad4539aaf5471658f3803a4e69/core/src/main/java/google/registry/persistence/PersistenceModule.java#L345)):*
> ```Java
>       overrides.put(Environment.PASS, credential.password());
>     } catch (Throwable e) {
>       // TODO(b/184631990): after SQL becomes primary, throw an exception to fail fast
> ```

What about using a `DatabaseMigrationUtils.isDatastore(REPLAYED_ENTITIES)`check here to determine if we should fail fast (SQL) or log (Datastore)?

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1059)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 345 at r1](https://reviewable.io/reviews/google/nomulus/1059#-MXdmhUq6XJ0THsR5ZnO:-MXe7QyoCsvJSmigppb3:b-bgj32h) ([raw file](https://github.com/google/nomulus/blob/102808f0040dddad4539aaf5471658f3803a4e69/core/src/main/java/google/registry/persistence/PersistenceModule.java#L345)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What about using a `DatabaseMigrationUtils.isDatastore(REPLAYED_ENTITIES)`check here to determine if we should fail fast (SQL) or log (Datastore)? 
</blockquote></details>

I'm not sure if we want the behavior to change so seamlessly. It is probably better to announce it to the team beforehand and then roll it out.
Whether we throw or log, there isn't externally visible differences anyway.

**Review by gbrodman — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1059#-:-MXek12w5ThVxQum-5Lw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai and @mindhog)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 345 at r1](https://reviewable.io/reviews/google/nomulus/1059#-MXdmhUq6XJ0THsR5ZnO:-MXek-8u5n4vhkIxfaWz:b-1ua90q) ([raw file](https://github.com/google/nomulus/blob/102808f0040dddad4539aaf5471658f3803a4e69/core/src/main/java/google/registry/persistence/PersistenceModule.java#L345)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

I'm not sure if we want the behavior to change so seamlessly. It is probably better to announce it to the team beforehand and then roll it out.
Whether we throw or log, there isn't externally visible differences anyway.
</blockquote></details>

All right fair enough.

**Review by mindhog — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1059)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
