### PR TITLE
Rename ContactResource -> Contact

### PR DESCRIPTION
**Pull request by CydeWeys**
This is a follow-up to PR #1725 and #1733. Now all EPP resource entity class
names have been rationalized to match with their SQL table names.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1763)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 116 of 116 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1763)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/model/eppcommon/StatusValue.java` line 134 at r1](https://reviewable.io/reviews/google/nomulus/1763#-NAebY67DMDdWdDFc5E5:-NAebY67DMDdWdDFc5E6:b-cntc7h) ([raw file](https://github.com/google/nomulus/blob/c0e7310337ef497fb777768593cab1e69fd642e8/core/src/main/java/google/registry/model/eppcommon/StatusValue.java#L134)):*
> ```Java
>     ALL(
>         ContactBase.class,
>         Contact.class,
> ```

should move this above ContactBase
___
*[`core/src/main/java/google/registry/model/contact/Contact.java` line 37 at r1](https://reviewable.io/reviews/google/nomulus/1763#-NAebCYbC93-JZYr6H1i:-NAebCYc6DrAja3SMNC-:bnk1qvn) ([raw file](https://github.com/google/nomulus/blob/c0e7310337ef497fb777768593cab1e69fd642e8/core/src/main/java/google/registry/model/contact/Contact.java#L37)):*
> ```Java
>  */
> @ReportedOn
> @Entity(name = "Contact")
> ```

somewhat nitty, don't need to specify the name

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1763)* status: 115 of 116 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/main/java/google/registry/model/contact/Contact.java` line 37 at r1](https://reviewable.io/reviews/google/nomulus/1763#-NAebCYbC93-JZYr6H1i:-NAeewUyBL1Bqm-SqtBO:b-xvbwa0) ([raw file](https://github.com/google/nomulus/blob/c0e7310337ef497fb777768593cab1e69fd642e8/core/src/main/java/google/registry/model/contact/Contact.java#L37)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

somewhat nitty, don't need to specify the name
</blockquote></details>

Don't have to, but we do specify it on most of the tables, even when the Java class matches the table name.  It kind of makes sense to not tie the two together so tightly.

**Review by gbrodman — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1763)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1763)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/model/eppcommon/StatusValue.java` line 134 at r1](https://reviewable.io/reviews/google/nomulus/1763#-NAebY67DMDdWdDFc5E5:-NAefCLG32EtBBQmtONW:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c0e7310337ef497fb777768593cab1e69fd642e8/core/src/main/java/google/registry/model/eppcommon/StatusValue.java#L134)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

should move this above ContactBase
</blockquote></details>

Done.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1763)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/model/contact/Contact.java` line 37 at r1](https://reviewable.io/reviews/google/nomulus/1763#-NAebCYbC93-JZYr6H1i:-NAeiNaf7OhHyc1W0GvV:bq51f26) ([raw file](https://github.com/google/nomulus/blob/c0e7310337ef497fb777768593cab1e69fd642e8/core/src/main/java/google/registry/model/contact/Contact.java#L37)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Don't have to, but we do specify it on most of the tables, even when the Java class matches the table name.  It kind of makes sense to not tie the two together so tightly.
</blockquote></details>

nah, we don't specify it on most tables except in situations where they're different

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
