### PR TITLE
Enforce consistency in non-cached FKI loads

### PR DESCRIPTION
**Pull request by gbrodman**
For the cached code path, we do not require consistency but we do
require the ability to load / operate on large numbers of entities (so,
we must do so without a Datastore transaction). For the non-cached code
path, we require consistency but do not care about large numbers of
entities, so we must remain in the transaction that we're already in.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1075)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1075)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 212 at r1](https://reviewable.io/reviews/google/nomulus/1075#-MYBDl3y6d7HL7kwmymM:-MYBDl3y6d7HL7kwmymN:b5u54es) ([raw file](https://github.com/google/nomulus/blob/c4d522e1ce6d06a52848c371da2337e6a8a828a9/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L212)):*
> ```Java
>   private static <E extends EppResource>
>       ImmutableMap<String, ForeignKeyIndex<E>> loadIndexesFromStore(
>           Class<E> clazz, Collection<String> foreignKeys, boolean forceConsistency) {
> ```

`forceConsistency` doesn't mean much to me as "consistency" as such is not a concept we use generally throughout our codebase by that name.  Just name it what it is: `isTransactional`.

Also, the Javadoc should be explaining what this parameter is, not just an inline comment.
___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 214 at r1](https://reviewable.io/reviews/google/nomulus/1075#-MYBECZJC0v2MLBtTUkK:-MYBECZJC0v2MLBtTUkL:b-iv98q) ([raw file](https://github.com/google/nomulus/blob/c4d522e1ce6d06a52848c371da2337e6a8a828a9/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L214)):*
> ```Java
>           Class<E> clazz, Collection<String> foreignKeys, boolean forceConsistency) {
>     if (tm().isOfy()) {
>       // If loading from the cache, we may need to load more entities than the Datastore transaction
> ```

Be more specific.  "Datastore transaction size limit" (which is 10 MB) is not what we're actually hitting here -- what we're hitting here is the Datastore limit on number of enrolled entity groups in a transaction, which is 25.
___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 219 at r1](https://reviewable.io/reviews/google/nomulus/1075#-MYBEbi77ylxQnc_N8Ko:-MYBEbi77ylxQnc_N8Kp:bdvpv2i) ([raw file](https://github.com/google/nomulus/blob/c4d522e1ce6d06a52848c371da2337e6a8a828a9/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L219)):*
> ```Java
>       return ImmutableMap.copyOf(
>           forceConsistency
>               ? ofy().load().type(mapToFkiClass(clazz)).ids(foreignKeys)
> ```

Why is this an `ofy()` call and not `ofyTm()`?  Does it matter?

**Comment by mindhog** [comment]
___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 219 at r1](https://reviewable.io/reviews/google/nomulus/1075#-MYBEbi77ylxQnc_N8Ko:-MYBFiSo9u2dEnNrXVSu:b-p10o5c) ([raw file](https://github.com/google/nomulus/blob/c4d522e1ce6d06a52848c371da2337e6a8a828a9/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L219)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why is this an `ofy()` call and not `ofyTm()`?  Does it matter?
</blockquote></details>

ofyTm() doeesn't currently support arbitrary ofy queries (IMO, we should make it do so just so even if it's the very same API, just so we can rule out stuff that has already been converted)

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1075)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @gbrodman)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1075)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 212 at r1](https://reviewable.io/reviews/google/nomulus/1075#-MYBDl3y6d7HL7kwmymM:-MYBRROWDYE64YGXmUMk:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c4d522e1ce6d06a52848c371da2337e6a8a828a9/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L212)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`forceConsistency` doesn't mean much to me as "consistency" as such is not a concept we use generally throughout our codebase by that name.  Just name it what it is: `isTransactional`.

Also, the Javadoc should be explaining what this parameter is, not just an inline comment.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 214 at r1](https://reviewable.io/reviews/google/nomulus/1075#-MYBECZJC0v2MLBtTUkK:-MYBRWUT90m6zi9Zdr0q:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c4d522e1ce6d06a52848c371da2337e6a8a828a9/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L214)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Be more specific.  "Datastore transaction size limit" (which is 10 MB) is not what we're actually hitting here -- what we're hitting here is the Datastore limit on number of enrolled entity groups in a transaction, which is 25.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 219 at r1](https://reviewable.io/reviews/google/nomulus/1075#-MYBEbi77ylxQnc_N8Ko:-MYBRYoW1HFpQmRjCEzM:bayrnc6) ([raw file](https://github.com/google/nomulus/blob/c4d522e1ce6d06a52848c371da2337e6a8a828a9/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L219)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

ofyTm() doeesn't currently support arbitrary ofy queries (IMO, we should make it do so just so even if it's the very same API, just so we can rule out stuff that has already been converted) 
</blockquote></details>

we actually could use ofyTm here but it would require converting the collection of Strings to VKeys then converting the resulting map's keys from VKeys back into Strings.

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1075)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 228 at r2](https://reviewable.io/reviews/google/nomulus/1075#-MYBSR8mDlmva4Km9myH:-MYBSR8nBu54fnfECx-2:b-hn16vg) ([raw file](https://github.com/google/nomulus/blob/5467f95f7f4c5781d523c1b71cc93579deb3ae93/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L228)):*
> ```Java
>       String property = RESOURCE_CLASS_TO_FKI_PROPERTY.get(clazz);
>       ImmutableList<ForeignKeyIndex<E>> indexes =
>           tm().transact(
> ```

It occurs to me that this explicit call to `transact()` shouldn't be necessary, right?  We're always in a wrapping transaction?  This could be replaced by an `assertInTransaction()` call.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1075)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/index/ForeignKeyIndex.java, line 228 at r2](https://reviewable.io/reviews/google/nomulus/1075#-MYBSR8mDlmva4Km9myH:-MYBdl9y2H3vNdMMB5ld:b-kk81bq) ([raw file](https://github.com/google/nomulus/blob/5467f95f7f4c5781d523c1b71cc93579deb3ae93/core/src/main/java/google/registry/model/index/ForeignKeyIndex.java#L228)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It occurs to me that this explicit call to `transact()` shouldn't be necessary, right?  We're always in a wrapping transaction?  This could be replaced by an `assertInTransaction()` call.
</blockquote></details>

I'm not sure. Either way, we can check that later and not have it block this commit (the transact call is a no-op if we're already in one)

**Pull request merged**
