### PR TITLE
Stage the init_sql_pipeline in CloudBuild

### PR DESCRIPTION
**Pull request by weiminyu**
Defined metadata file and added Gradle uberJar task for the pipeline,
which are needed for staging.

Updated cloud build script to stage this pipeline during the build
processs.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1004)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
Tested in alpha

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1004#-:-MVWk4H85Erlmf5eAiuN:b-97m2s3)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @gbrodman, @jianglai, and @mindhog)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1004)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @jianglai and @mindhog)

___
*[core/build.gradle, line 786 at r1](https://reviewable.io/reviews/google/nomulus/1004#-MVXXZSWBD7Iamu_6zDl:-MVXXZSWBD7Iamu_6zDm:bivmtta) ([raw file](https://github.com/google/nomulus/blob/af92b52b4e8cced95beda56e6269751c0b2190bb/core/build.gradle#L786)):*
> ```Gradle
> 
> createUberJar(
>     'init_sql_pipeline',
> ```

Out of curiosity, why is this duplicated? I see it's the case with the previous command as well 

Separately, are we going to need to have one of these tasks for every single BEAM pipeline? Just curious. 
___
*[core/src/main/resources/google/registry/beam/init_sql_pipeline_metadata.json, line 20 at r1](https://reviewable.io/reviews/google/nomulus/1004#-MVXXotbEVGbhivicOUK:-MVXXotbEVGbhivicOUL:b-ts4uaf) ([raw file](https://github.com/google/nomulus/blob/af92b52b4e8cced95beda56e6269751c0b2190bb/core/src/main/resources/google/registry/beam/init_sql_pipeline_metadata.json#L20)):*
> ```JSON
>       "is_optional": true,
>       "regexes": [
>         "^[0-9A-Z_]+$"
> ```

Is the only reason why this isn't `^[A-Z_]+$` so that, if the user wants, they can specify the level from  `java.sql.Connection`? 
___
*[release/cloudbuild-nomulus.yaml, line 85 at r1](https://reviewable.io/reviews/google/nomulus/1004#-MVXYhR03DrclDa2Ue7f:-MVXYhR03DrclDa2Ue7g:bb7l8rz) ([raw file](https://github.com/google/nomulus/blob/af92b52b4e8cced95beda56e6269751c0b2190bb/release/cloudbuild-nomulus.yaml#L85)):*
> ```YAML
>   - -c
>   - |
>     ./release/stage_beam_pipeline.sh \
> ```

neat

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1004)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @jianglai and @mindhog)

___
*[core/build.gradle, line 786 at r1](https://reviewable.io/reviews/google/nomulus/1004#-MVXXZSWBD7Iamu_6zDl:-MVXimaZ6r1HK8c6ZTEz:b-vxxbch) ([raw file](https://github.com/google/nomulus/blob/af92b52b4e8cced95beda56e6269751c0b2190bb/core/build.gradle#L786)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Out of curiosity, why is this duplicated? I see it's the case with the previous command as well 

Separately, are we going to need to have one of these tasks for every single BEAM pipeline? Just curious. 
</blockquote></details>

The first param is Gradle task name, the second param is the jar name. I would propose to require them to be the same when the output jar is for beam.

And yes, we will need one such task for each pipeline. 
___
*[core/src/main/resources/google/registry/beam/init_sql_pipeline_metadata.json, line 20 at r1](https://reviewable.io/reviews/google/nomulus/1004#-MVXXotbEVGbhivicOUK:-MVXjXgH9EWMx02oqfUS:b9b0szl) ([raw file](https://github.com/google/nomulus/blob/af92b52b4e8cced95beda56e6269751c0b2190bb/core/src/main/resources/google/registry/beam/init_sql_pipeline_metadata.json#L20)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Is the only reason why this isn't `^[A-Z_]+$` so that, if the user wants, they can specify the level from  `java.sql.Connection`? 
</blockquote></details>

I just copied the generic pattern for enum names, without considering the actual names.

No real harm though, since the option class will check if the parameter can be translated to a proper enum.
___
*[release/cloudbuild-nomulus.yaml, line 85 at r1](https://reviewable.io/reviews/google/nomulus/1004#-MVXYhR03DrclDa2Ue7f:-MVXkfn0-Z-vs6npCguV:buexv7c) ([raw file](https://github.com/google/nomulus/blob/af92b52b4e8cced95beda56e6269751c0b2190bb/release/cloudbuild-nomulus.yaml#L85)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

neat
</blockquote></details>

Yeah. Thanks to the JvmInitializer that allows injection on worker vm.

**Review by gbrodman — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai and @mindhog)

**Review by jianglai — APPROVED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

___
*[core/src/main/resources/google/registry/beam/init_sql_pipeline_metadata.json, line 20 at r1](https://reviewable.io/reviews/google/nomulus/1004#-MVXXotbEVGbhivicOUK:-MVZdt5JCaydyWzlpxd5:b-8u1ned) ([raw file](https://github.com/google/nomulus/blob/af92b52b4e8cced95beda56e6269751c0b2190bb/core/src/main/resources/google/registry/beam/init_sql_pipeline_metadata.json#L20)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

I just copied the generic pattern for enum names, without considering the actual names.

No real harm though, since the option class will check if the parameter can be translated to a proper enum.
</blockquote></details>

Does this have to be this way? With the old templates we only need to build one Uber jar and the nomulus command can invoke different functions to stage different pipelines. Now we call a bash script to build a uber jar for a specific pipeline, and then call gcloud build the image and upload it (and the metadata file).

Is it possible to still create one jar and call the gcloud java client to do staging within the Nomulus tool? We don't have to change this PR, but I do want to know if this is an option that we can explore.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

___
*[core/src/main/resources/google/registry/beam/init_sql_pipeline_metadata.json, line 20 at r1](https://reviewable.io/reviews/google/nomulus/1004#-MVXXotbEVGbhivicOUK:-MVb2csF6gc6kzQ2Qzt-:b-1lpif3) ([raw file](https://github.com/google/nomulus/blob/af92b52b4e8cced95beda56e6269751c0b2190bb/core/src/main/resources/google/registry/beam/init_sql_pipeline_metadata.json#L20)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Does this have to be this way? With the old templates we only need to build one Uber jar and the nomulus command can invoke different functions to stage different pipelines. Now we call a bash script to build a uber jar for a specific pipeline, and then call gcloud build the image and upload it (and the metadata file).

Is it possible to still create one jar and call the gcloud java client to do staging within the Nomulus tool? We don't have to change this PR, but I do want to know if this is an option that we can explore.
</blockquote></details>

That's a good question. It depends on an unpublished detail of the docker image created by gcloud: whether it invokes the uber jar using java -jar  or java mainClass -cp $uberJarPath. If dataflow team publicly chooses the latter, we can reuse jars for multiple pipelines. I'm going to reach out to them about this.

**Pull request merged**
