### PR TITLE
Add a command to compare two escrow  deposits

### PR DESCRIPTION
**Pull request by jianglai**
We already have ValidateEscrowDepositCommand to check for internal
reference consistency of two deposits, i. e. making sure that all
contacts and hosts referenced by domains exist in the same deposit.
Therefore to compare whether two deposits are equal we only need to make
sure that they contain the same domains and registrars, assuming they
both pass the validation. We don't compare their contents directly
because the MapReduce deposit contains all contacts and domains whereas
the Beam deposit only contains referenced ones, making a direct
comparison impossible.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1476)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1476)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 45 at r2](https://reviewable.io/reviews/google/nomulus/1476#-MsaBXJ5EicQEuXHGA4k:-MsaBXJ5EicQEuXHGA4l:b-f81f12) ([raw file](https://github.com/google/nomulus/blob/a55273cab77836ba12913de016ab0cc7cb9f3c46/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L45)):*
> ```Java
> /** Command to view and schema validate an XML RDE escrow deposit. */
> @Parameters(separators = " =", commandDescription = "Compare two XML escrow deposits.")
> public final class CompareEscrowDepositsCommand implements Command {
> ```

We should probably label this class '@'DeleteAfterMigration  



_Code quote:_
```Java
CompareEscrowDepositsCommand
```
___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 115 at r2](https://reviewable.io/reviews/google/nomulus/1476#-MsaBnAV0vst9KPmrOaz:-MsaBnAV0vst9KPmrOb-:b4q7qck) ([raw file](https://github.com/google/nomulus/blob/a55273cab77836ba12913de016ab0cc7cb9f3c46/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L115)):*
> ```Java
>       System.out.println(
>           "The two deposits contain the same domains and registrars. "
>               + "You still need to run ValidateEscrowDepositCommand for reference consistency.");
> ```

We may want to add this sentence in class javadoc.



_Code quote:_
```Java
You still need to run ValidateEscrowDepositCommand for reference consistency.
```

**Review by jianglai — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1476)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 45 at r2](https://reviewable.io/reviews/google/nomulus/1476#-MsaBXJ5EicQEuXHGA4k:-MshB59I7a1uRHkqnv5U:b-896fix) ([raw file](https://github.com/google/nomulus/blob/a55273cab77836ba12913de016ab0cc7cb9f3c46/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L45)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

We should probably label this class '@'DeleteAfterMigration  
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 115 at r2](https://reviewable.io/reviews/google/nomulus/1476#-MsaBnAV0vst9KPmrOaz:-MshBs0FB9JvbBpfkV-J:b-896fix) ([raw file](https://github.com/google/nomulus/blob/a55273cab77836ba12913de016ab0cc7cb9f3c46/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L115)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

We may want to add this sentence in class javadoc.
</blockquote></details>

Done.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1476)* status: all files reviewed, 6 unresolved discussions (waiting on @jianglai and @weiminyu)

___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 1 at r5](https://reviewable.io/reviews/google/nomulus/1476#-MspVUgD-eZhtK49npDH:-MspVUgD-eZhtK49npDI:b-gzs748) ([raw file](https://github.com/google/nomulus/blob/78cc57ed480cac146ef92cde75c0e609c0188309/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L1)):*
> ```Java
> // Copyright 2017 The Nomulus Authors. All Rights Reserved.
> ```

Incorrect copyright year.
___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 58 at r5](https://reviewable.io/reviews/google/nomulus/1476#-MspVbDo8ezJwuhms228:-MspVbDo8ezJwuhms229:b-dqrai2) ([raw file](https://github.com/google/nomulus/blob/78cc57ed480cac146ef92cde75c0e609c0188309/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L58)):*
> ```Java
> 
>   @Parameter(
>       names = {"-i1", "--input1"},
> ```

`-i1` and `-i2` are strange parameter names. Both are required, right?  Just use main parameters then so it works like `diff` or any other command line comparison tool.  `compare_escrow_deposits file1 file2` is a lot cleaner than `compare_escrow_deposits -i1 file1 -i2 file2`
___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 69 at r5](https://reviewable.io/reviews/google/nomulus/1476#-MspWEeC4KBh9KwwYk9u:-MspWEeD6ltbPtWLookr:btc7lci) ([raw file](https://github.com/google/nomulus/blob/78cc57ed480cac146ef92cde75c0e609c0188309/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L69)):*
> ```Java
>   private Path input2 = null;
> 
>   @Inject Provider<Keyring> keyring;
> ```

I believe constructor injection is preferred, so we should be doing it that way on new code.
___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 99 at r5](https://reviewable.io/reviews/google/nomulus/1476#-MspWVTX9R_btguFDRVN:-MspWVTX9R_btguFDRVO:brets90) ([raw file](https://github.com/google/nomulus/blob/78cc57ed480cac146ef92cde75c0e609c0188309/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L99)):*
> ```Java
>   }
> 
>   private static boolean printUniqueElements(
> ```

Nothing in `DiffUtils` is suitable for this?  Maybe move this there if it seems generally usable?

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1476)* status: all files reviewed, 4 unresolved discussions (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1476)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 1 at r5](https://reviewable.io/reviews/google/nomulus/1476#-MspVUgD-eZhtK49npDH:-Mt3pJpTDtLPKZ2rlOt0:b-896fix) ([raw file](https://github.com/google/nomulus/blob/78cc57ed480cac146ef92cde75c0e609c0188309/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L1)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Incorrect copyright year.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 58 at r5](https://reviewable.io/reviews/google/nomulus/1476#-MspVbDo8ezJwuhms228:-Mt6EMPH0ChnUEhB-Smz:b-896fix) ([raw file](https://github.com/google/nomulus/blob/78cc57ed480cac146ef92cde75c0e609c0188309/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L58)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`-i1` and `-i2` are strange parameter names. Both are required, right?  Just use main parameters then so it works like `diff` or any other command line comparison tool.  `compare_escrow_deposits file1 file2` is a lot cleaner than `compare_escrow_deposits -i1 file1 -i2 file2`
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 69 at r5](https://reviewable.io/reviews/google/nomulus/1476#-MspWEeC4KBh9KwwYk9u:-Mt6F7a9-JHvghegEd5P:bubkgx1) ([raw file](https://github.com/google/nomulus/blob/78cc57ed480cac146ef92cde75c0e609c0188309/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L69)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I believe constructor injection is preferred, so we should be doing it that way on new code.
</blockquote></details>

Constructor injection is perferred. But in this case this is a scrap tool that will be deleted soon, so I don't think it matters that much. More importantly, I believe most command test cases use the `CommandTestCase` base class which uses reflection to call a no-arg constructor. So we'd need to create such a constructor just for testing purposes, do you think it is still worth doing?

If so we may want to do a refactoring to all command classes to use constructor injection. As it stands now any member-injected field that is touched will be reformatted automatically with the annotation on a separate line, resulting in a non-uniform style. 
___
*[core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java, line 99 at r5](https://reviewable.io/reviews/google/nomulus/1476#-MspWVTX9R_btguFDRVN:-Mt6GZKGBITCMit7yiMr:bp8tzod) ([raw file](https://github.com/google/nomulus/blob/78cc57ed480cac146ef92cde75c0e609c0188309/core/src/main/java/google/registry/tools/javascrap/CompareEscrowDepositsCommand.java#L99)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Nothing in `DiffUtils` is suitable for this?  Maybe move this there if it seems generally usable?
</blockquote></details>

Err, this is mostly lifted from `ValidateEscrowDepositCommand`. As it mostly just calls Guava's `Sets.difference`, I don't think it needs to be put in a util function. `DiffUtils` seems to exclusively deal with maps and uses recursion.

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1476)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys)

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1476#-:-Mt91BcBElV618AIKRP_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
