### PR TITLE
Fix timestamp inversion bug

### PR DESCRIPTION
**Pull request by weiminyu**
Set the number of commitLog buckets to 1 in CommitLog replay tests to
expose all timestamp inversion problem.

Fixed PollAckFlowTest.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1144)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1144)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/test/java/google/registry/flows/poll/PollAckFlowTest.java, line 62 at r1](https://reviewable.io/reviews/google/nomulus/1144#-M_QO4KW6rP-VQpAxyY6:-M_Qn2BgEbXXHyr2YsXV:b-1imf6y) ([raw file](https://github.com/google/nomulus/blob/f1c75601e9de920c4d4eca097b58607d65911d9b/core/src/test/java/google/registry/flows/poll/PollAckFlowTest.java#L62)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

You might want to take a look at [SetClockExtension](https://github.com/google/nomulus/blob/master/core/src/test/java/google/registry/testing/SetClockExtension.java#L26) which I think will work here.  You will need to set ordering explicitly, though.
</blockquote></details>

AppEngineExtension is in parent class. To use SetClockExtension, it has to be in parent class too, right?

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1144)* status: 2 of 15 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/test/java/google/registry/flows/poll/PollAckFlowTest.java, line 62 at r1](https://reviewable.io/reviews/google/nomulus/1144#-M_QO4KW6rP-VQpAxyY6:-M_ROdZT7vJItEtsLwPJ:b-cc45ip) ([raw file](https://github.com/google/nomulus/blob/f1c75601e9de920c4d4eca097b58607d65911d9b/core/src/test/java/google/registry/flows/poll/PollAckFlowTest.java#L62)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

AppEngineExtension is in parent class. To use SetClockExtension, it has to be in parent class too, right?
</blockquote></details>

Nope, see e.g. DomainCheckFlowTest, DomainInfoFlowTest, DomainRenewFlowTest.

**Review by gbrodman — APPROVED** [review]
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1144)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @weiminyu)

**Review by mindhog — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1144)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @weiminyu)

**Pull request merged**
