### PR TITLE
Update a few plugins for Java 11 compatibility

### PR DESCRIPTION
**Pull request by jianglai**
Guice 5.0.0-BETA-1 is now compatible with Java 11. However we don't
directly depend on Guice. Rather Soy depends on Guice. So I added a
direct dependency on Guice 5.0 in the soy configuration in order to frontload
Soy's transitive dependency and pull in the newer version. Similarly Soy
depends on an old version of protobuf that is incompatible with Java 11, 
whereas the protobuf version that we use ourselves are OK. So an explicit
dependency for protobuf was added in the soy configuration as well.

Mockito 3.7.7 is now compatible with Java 11. The complication is that
we need to use the inline version of Mockito, which among other things
also allows mocking for final classes (hooray!). It will eventually
become the default Mockito mock maker but for now it needs to be
manually activated.

Note that the inline version now introduces another warning:

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
```

Which I think is WAI due to how the inline mock maker works. Waiting on
the author to confirm.

After these to changes the only illegal reflective access is caused by
App Engine SDK tools, which we will rid ourselves of when we migrate off
of GAE.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/966)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTl7RVIBFbNXUdwCQPC:blhleyz) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
> ```JSON
>   "name": "nomulus",
>   "version": "1.0.0",
>   "lockfileVersion": 1,
> ```

You're reverting this to an older lockfile, I think you can remove this change.

If you do "nvm install-latest-npm" I think it will fix this (we should maybe consider adding a test for the npm version to the build)

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTn-ghWCeX6gtLIhyi3:bp8lo9y) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

You're reverting this to an older lockfile, I think you can remove this change.

If you do "nvm install-latest-npm" I think it will fix this (we should maybe consider adding a test for the npm version to the build)
</blockquote></details>

Hmm, actually it looks like the format was updated by me in a previous PR (#958) just last week. I am not entirely sure what happened. I suspect that i may have generated that PR on my crostini VM instead of on my gLinux workstation. They do have the same npm version though (7.5.4), which according to the [official doc](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion) should both use `lockfileVersion: 2`.

@gbrodman any idea how npm is used by Gradle? Does it use the system provided npm/node or does it use it's own packaged version?

In any case it seems reasonable that we revert to version 1 because that's what most of us would wind up getting if running the build on gLinux.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTrGGrjA7iK-_OBlLAI:b-tqpg0t) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Hmm, actually it looks like the format was updated by me in a previous PR (#958) just last week. I am not entirely sure what happened. I suspect that i may have generated that PR on my crostini VM instead of on my gLinux workstation. They do have the same npm version though (7.5.4), which according to the [official doc](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion) should both use `lockfileVersion: 2`.

@gbrodman any idea how npm is used by Gradle? Does it use the system provided npm/node or does it use it's own packaged version?

In any case it seems reasonable that we revert to version 1 because that's what most of us would wind up getting if running the build on gLinux.
</blockquote></details>

It's part of the plugin, configurable (though I think we use the default). See https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/usage.md#configuring-the-plugin

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTv4Y7x9uluU1Ekdim4:b-9cda86) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It's part of the plugin, configurable (though I think we use the default). See https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/usage.md#configuring-the-plugin 
</blockquote></details>

How do we want to deal with this?  Ideally the build should be hermetic and it shouldn't matter what weird stuff we have on our workstations.
In the meantime, I do think you should take this out of the PR, AFAICT it's unrelated to the rest of the change and we should deal with whatever we choose to do WRT npm separately.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTv6PRI7zYI8ZMVm6oQ:b-yr5vw6) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

How do we want to deal with this?  Ideally the build should be hermetic and it shouldn't matter what weird stuff we have on our workstations.
In the meantime, I do think you should take this out of the PR, AFAICT it's unrelated to the rest of the change and we should deal with whatever we choose to do WRT npm separately. 
</blockquote></details>

I think you may have misread the comment -- the version of node / npm is locked to the version of the node plugin unless we configure it (then it's locked to whatever the configuration is)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTv6XBu6kUa-N4XSjgR:b-hlgm1l) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think you may have misread the comment -- the version of node / npm is locked to the version of the node plugin unless we configure it (then it's locked to whatever the configuration is) 
</blockquote></details>

Unless you were responding to only Lai, then my bad

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTv6zX44ZDwkEae9ZMA:b9bnqh3) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Unless you were responding to only Lai, then my bad 
</blockquote></details>

No, I was responding to both of you, and I don't think I misunderstood your comment. But if the version of node/npm is locked to the version of the node plugin then we shouldn't see changes in this file unless we upgrade the node plugin, right?  I don't think we've done that explicitly.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTv9EHn5Fiq5na1NX9O:b9kicvt) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

No, I was responding to both of you, and I don't think I misunderstood your comment. But if the version of node/npm is locked to the version of the node plugin then we shouldn't see changes in this file unless we upgrade the node plugin, right?  I don't think we've done that explicitly.
</blockquote></details>

It depends on how Lai was generating the lockfile

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTvBLhkERLR63wj5-Zg:b2nz6sz) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It depends on how Lai was generating the lockfile
</blockquote></details>

I'm guessing he didn't explicitly generate the lockfile.  It gets regenerated in the course of a build (I've just verified this).

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTvBw7F4UDEifl-0tKg:bd17zj6) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I'm guessing he didn't explicitly generate the lockfile.  It gets regenerated in the course of a build (I've just verified this).
</blockquote></details>

hm yeah i'm seeing some changes as well if I nuke it and re-generate it using ./gradlew npmInstall 

I'll check that in as a separate PR, thanks for the heads-up -- hopefully that fixes this

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTvChhL0wmpuymrzzzE:b-3ulzzl) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

hm yeah i'm seeing some changes as well if I nuke it and re-generate it using ./gradlew npmInstall 

I'll check that in as a separate PR, thanks for the heads-up -- hopefully that fixes this 
</blockquote></details>

hm actually that didn't work quite as expected, i'll need to take a further look

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTvCp8PAv2xI_tsj5Sm:b-bd2uox) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

hm actually that didn't work quite as expected, i'll need to take a further look 
</blockquote></details>

Yeah, running a `gw assemble` gives the same lockfile that's already in the repo

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTvDHlX5-llmEmjsTHb:bxw2jj8) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah, running a `gw assemble` gives the same lockfile that's already in the repo 
</blockquote></details>

yeah let's just manually specify everything to be explicitly clear

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MTvFClT2i7pmvETkLJQ:b468c3o) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah let's just manually specify everything to be explicitly clear 
</blockquote></details>

https://github.com/google/nomulus/pull/971

note that Gradle apparently explicitly does not regenerate the lockfile, but Node always uses it if available. We should probably standardize on these versions.

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUL5cD28hmqPaWqVhpM:b7851kf) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

https://github.com/google/nomulus/pull/971

note that Gradle apparently explicitly does not regenerate the lockfile, but Node always uses it if available. We should probably standardize on these versions. 
</blockquote></details>

Note that #971 has been merged, does your build produce a lockfile identical to the one in master?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: 7 of 35 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUiK3Tf6l_k_wjRWgAh:b-eswda0) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Note that #971 has been merged, does your build produce a lockfile identical to the one in master? 
</blockquote></details>

Sorry just had time to get to this. I rebased on master and ran `./gradlew build`. This file still gets downgraded to version 1. Given that #971 locks to npm v6, shouldn't it be version 1 per https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion?

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 1 of 28 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: 8 of 35 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @jianglai, and @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUib6gi5EHHepBnA5TK:b7bjkej) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Sorry just had time to get to this. I rebased on master and ran `./gradlew build`. This file still gets downgraded to version 1. Given that #971 locks to npm v6, shouldn't it be version 1 per https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion?
</blockquote></details>

It should be version 1, that's correct (and also what's currently checked in).  What I'm not clear on is why it still seems to be downgrading some of the dependencies?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: 8 of 35 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUic3qJ-MEKIfvGuH9i:b635iit) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

It should be version 1, that's correct (and also what's currently checked in).  What I'm not clear on is why it still seems to be downgrading some of the dependencies?
</blockquote></details>

Hmm, you are right. I was looking at the wrong diff. Supposedly all the packages are controlled by the `package.json` file, right? It's indeed strange.

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: 8 of 35 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @jianglai, and @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUieIZS24Ord9z_Ipqd:b-31vhfq) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Hmm, you are right. I was looking at the wrong diff. Supposedly all the packages are controlled by the `package.json` file, right? It's indeed strange. 
</blockquote></details>

I honestly know very little about how the npm stuff is supposed to work, @gbrodman is probably the best person to comment on this.

My only thoughts on this are:
- if this is controlled internally by gradle-node-plugin and config files in the build, you should not be seeing diffs after regenerating unless one of your changes affects node dependencies (i.e. the build is hermetic with respect to node dependencies)
- if this is _not_ controlled purely internally, we should figure out what everyone needs to do to ensure that they have the right versions of node/npm/whatever installed so that we're all generating the same file.

Once again, I encourage you to simply take this file out of the PR.  We don't need to block this PR on figuring the node issue out.

**Comment by jianglai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/966)_ status: 8 of 35 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @jianglai, and @mindhog)
> 
> _[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUieIZS24Ord9z_Ipqd:b-31vhfq) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):_
> 
> Previously, jianglai (Lai Jiang) wrote…
> I honestly know very little about how the npm stuff is supposed to work, @gbrodman is probably the best person to comment on this.
> 
> My only thoughts on this are:
> 
> * if this is controlled internally by gradle-node-plugin and config files in the build, you should not be seeing diffs after regenerating unless one of your changes affects node dependencies (i.e. the build is hermetic with respect to node dependencies)
> * if this is _not_ controlled purely internally, we should figure out what everyone needs to do to ensure that they have the right versions of node/npm/whatever installed so that we're all generating the same file.
> 
> Once again, I encourage you to simply take this file out of the PR. We don't need to block this PR on figuring the node issue out.

I could certainly take it out, my concern is that this change is somehow a side effect of the other changes to dependencies that I'm making, because I was about to reproduce the same result on two different machines. This means that if I take the file out and check in the rest of the code, the next PR will include it. Let me try taking it out and run the presubmit to see what happens.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: 8 of 35 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUj_4ls0pWGTlLIl9yd:bqa847x) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I could certainly take it out, my concern is that this change is somehow a side effect of the other changes to dependencies that I'm making, because I was about to reproduce the same result on two different machines. This means that if I take the file out and check in the rest of the code, the next PR will include it. Let me try taking it out and run the presubmit to see what happens. 
</blockquote></details>

OK Mike and I did some investigation. It looks like `package-lock.json` is generated by `gradle npmInstall` when the `node_modules` folder is absent (or presumably when `package.json` is modified). It will grab the latest packages from npm repo. So as long as we don't touch these it should be OK to remove the lockfile from this PR, which I did. PLAL.

**Review by mindhog — APPROVED** [review]
FYI, summary of dependency version changes (courtesy of my awesome new tool) are:
```
b'com.google.code.findbugs:jsr305': {b'3.0.2\n', b'3.0.1\n', b'2.0.3\n'} -> {b'3.0.2\n', b'3.0.1\n'}
b'com.google.guava:guava': {b'27.0.1-jre\n', b'27.1-jre\n', b'27.0-jre\n', b'29.0-jre\n', b'25.1-jre\n', b'30.1-jre\n', b'21.0\n', b'19.0\n', b'28.2-android\n', b'20.0\n'} -> {b'27.0.1-jre\n', b'27.1-jre\n', b'27.0-jre\n', b'29.0-jre\n', b'25.1-jre\n', b'30.1-jre\n', b'19.0\n', b'28.2-android\n', b'20.0\n'}
b'com.google.inject:guice': {b'4.1.0\n'} -> {b'5.0.0-BETA-1\n', b'4.1.0\n'}
b'com.google.protobuf:protobuf-java': {b'3.0.2\n', b'3.6.1\n', b'3.14.0\n', b'3.4.0\n', b'2.5.0\n', b'3.3.0\n'} -> {b'3.0.2\n', b'3.13.0\n', b'3.14.0\n', b'3.4.0\n', b'2.5.0\n'}
b'net.bytebuddy:byte-buddy-agent': {b'1.10.5\n'} -> {b'1.10.19\n'}
b'net.bytebuddy:byte-buddy': {b'1.10.17\n', b'1.10.5\n'} -> {b'1.10.17\n', b'1.10.19\n'}
b'org.mockito:mockito-core': {b'3.3.3\n', b'1.10.19\n'} -> {b'3.7.7\n', b'1.10.19\n'}
b'org.objenesis:objenesis': {b'2.6\n', b'2.1\n', b'1.2\n'} -> {b'3.1\n', b'2.1\n', b'1.2\n'}
b'org.mockito:mockito-junit-jupiter': {b'3.3.3\n'} -> {b'3.7.7\n'}
```

> Reviewed 26 of 28 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966#-:-MUjn3Vw8BZndprBTw5c:b-2p8ay1)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by jianglai — COMMENTED** [review]
Which tool is that?! Can you share?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966#-:-MUkh5ig3ADlU_Gkla8N:b-719ozy)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by mindhog — COMMENTED** [review]
Yeah, I'm cleaning it up right now.  Will send a PR shortly.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966#-:-MUnZeGu8IBVk2ktnMmN:b53i5d0)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUnoOAYEPLcEs_LrMaT:b-va34q3) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

OK Mike and I did some investigation. It looks like `package-lock.json` is generated by `gradle npmInstall` when the `node_modules` folder is absent (or presumably when `package.json` is modified). It will grab the latest packages from npm repo. So as long as we don't touch these it should be OK to remove the lockfile from this PR, which I did. PLAL.
</blockquote></details>

Did this file sneak back in?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUoSblg54dUZGCUZVSw:b-3iyi87) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Did this file sneak back in?
</blockquote></details>

Guice released the official 5.0.1 version during the review of this PR so I upgrade from the beta version and rerun everything. Somehow this file got regenerated again. I've since removed it. It is however still leaves the question unanswered: why? The only thing that's changed is the guice version.

**Review by mindhog — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUoV8Q8EwmkgkU4ZF7P:b-yc73h5) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Guice released the official 5.0.1 version during the review of this PR so I upgrade from the beta version and rerun everything. Somehow this file got regenerated again. I've since removed it. It is however still leaves the question unanswered: why? The only thing that's changed is the guice version.
</blockquote></details>

Did you maybe remove the file locally?  If so, I can understand it getting regenerated.  If you reverted to the original version of the file, then we have a new mystery.

**Review by mindhog — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUof3aA0fMDw5RnqSa8:bstrx8v) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Did you maybe remove the file locally?  If so, I can understand it getting regenerated.  If you reverted to the original version of the file, then we have a new mystery.
</blockquote></details>

I didn't. I only changed one line in the dependencies.gradle file and rerun your update-dependency script...

**Review by mindhog — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/966)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[package-lock.json, line 4 at r1](https://reviewable.io/reviews/google/nomulus/966#-MTl7RVIBFbNXUdwCQPB:-MUofgw9EKVxkDVE8zEj:b-31kdgp) ([raw file](https://github.com/google/nomulus/blob/51bff097fe00f572fba69998b67c9060697f488c/package-lock.json#L4)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I didn't. I only changed one line in the dependencies.gradle file and rerun your update-dependency script...
</blockquote></details>

update-dependency does some unusual stuff, I'll see if I can repro that in that context (without  actually updating GoB and the repo).  But I still think you're good to merge, worst case we can add any changes to this file after-the-fact.
[By way of full disclosure, update-dependency was mostly Shicong's work, though I've certainly messed with it quite a bit]

**Pull request merged**
