### PR TITLE
Add commands to set and check the database migration state

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1174)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[.gitignore, line 108 at r1](https://reviewable.io/reviews/google/nomulus/1174#-MaUIe7e6lp90rixhios:-MaUIe7f833bCPDVY8S4:b-1q1t0a) ([raw file](https://github.com/google/nomulus/blob/12c2ca994d09bff914dc36f61f038617bc1f6e31/.gitignore#L108)):*
> ```ignore
> node_modules/**
> /repos/
> gjf.out
> ```

I've been noticing this, do you know what it is?
___
*[core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java, line 22 at r1](https://reviewable.io/reviews/google/nomulus/1174#-MaUJ4a56Bj9OmgFimCl:-MaUJ4a56Bj9OmgFimCm:bfo0ob6) ([raw file](https://github.com/google/nomulus/blob/12c2ca994d09bff914dc36f61f038617bc1f6e31/core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java#L22)):*
> ```Java
> 
> /** A command to check the current Registry 3.0 migration state of the database. */
> @Parameters(separators = " =", commandDescription = "Check domain availability")
> ```

I think the description needs an update.
___
*[core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java, line 47 at r1](https://reviewable.io/reviews/google/nomulus/1174#-MaUJygI9WWMXpoJzojy:-MaUJygI9WWMXpoJzojz:b-l8cj2c) ([raw file](https://github.com/google/nomulus/blob/12c2ca994d09bff914dc36f61f038617bc1f6e31/core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java#L47)):*
> ```Java
>     MigrationState currentState = DatabaseMigrationStateWrapper.get();
>     MigrationState newState = MigrationState.valueOf(Iterables.getOnlyElement(mainParameters));
>     DatabaseMigrationStateWrapper.set(newState);
> ```

Though it's unlikely to be a problem, we should probably wrap the get...update sequence in a transaction (unless ConfirmingCommand already does that?)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[.gitignore, line 108 at r1](https://reviewable.io/reviews/google/nomulus/1174#-MaUIe7e6lp90rixhios:-MaUT54EDoxCDINyiVtN:b-eznwjs) ([raw file](https://github.com/google/nomulus/blob/12c2ca994d09bff914dc36f61f038617bc1f6e31/.gitignore#L108)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I've been noticing this, do you know what it is?
</blockquote></details>

I assume it's the output of google-java-format
___
*[core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java, line 22 at r1](https://reviewable.io/reviews/google/nomulus/1174#-MaUJ4a56Bj9OmgFimCl:-MaUTAFOBj6F_yk3l9Kf:b-23phzi) ([raw file](https://github.com/google/nomulus/blob/12c2ca994d09bff914dc36f61f038617bc1f6e31/core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java#L22)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I think the description needs an update.
</blockquote></details>

ugh oops
___
*[core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java, line 47 at r1](https://reviewable.io/reviews/google/nomulus/1174#-MaUJygI9WWMXpoJzojy:-MaUTFZQ9x2yd-Hm_NPj:bh97sdc) ([raw file](https://github.com/google/nomulus/blob/12c2ca994d09bff914dc36f61f038617bc1f6e31/core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java#L47)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Though it's unlikely to be a problem, we should probably wrap the get...update sequence in a transaction (unless ConfirmingCommand already does that?)
</blockquote></details>

nah, I don't think it does. We should probably do that though. Done.

**Review by mindhog — APPROVED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @CydeWeys and @mindhog)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java, line 29 at r2](https://reviewable.io/reviews/google/nomulus/1174#-Mad4p67-Ap6kNXboi1x:-Mad4p682-3s9UBlF_aF:b-8z1vu) ([raw file](https://github.com/google/nomulus/blob/6dbbd94407c41121f946ba9e11506fdce431f122/core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java#L29)):*
> ```Java
> /** Command to set the current Registry 3.0 migration state of the database. */
> @Parameters(separators = " =", commandDescription = "Set the current database migration state.")
> public class SetDatabaseMigrationStateCommand extends ConfirmingCommand
> ```

These changes need to be schedulable as per my comments on the design doc.  See Sarah's implement of the primary database setting which uses a `TimedTransitionMap`.

**Review by CydeWeys — COMMENTED** [review]
For the record, I think it was a mistake to not simply adapt the existing `DatabaseTransitionSchedule` entity to serve this new use case.  It already had all the associated tooling, which you ended up re-implementing, plus it would have killed two birds with one stone by also accomplishing the cleanup of that entity (which is no longer used and which still needs to happen).  A lot of extra duplicated work was done here.  I thought we were on the same page on this before I went out for vacation last week.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174#-:-MaiUdd9D0QlkepR4VAs:bg9c50i)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

**Review by CydeWeys — COMMENTED** [review]
It's not too late to merge all of this in with that.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174#-:-MaiWC-ZAgfSw5kPGdE1:b70rvls)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

**Review by gbrodman — COMMENTED** [review]
It doesn't end up being that much wasted work; a lot of this (valid transitions, etc) are still necessary and we can't reuse the existing DatabaseTransitionSchedule as-is anyway. It requires a functionally new object. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174#-:-MaiWDc55IrULHtOv3TW:b-h1bcn6)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

**Review by CydeWeys — COMMENTED** [review]
The existing `DatabaseTransitionSchedule` object is no longer used per Sarah, so feel free to carve that up as necessary.  The first three transition IDs are now complete and need to be removed, and the final one, `REPLAYED_ENTITIES`, is actively duplicative of what you're adding here and needs to be merged in.

This PR shouldn't be adding any duplicative functionality; it all needs to be merged.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174#-:-MaiZ5Yk3H2evr2vK4Tj:b-o65tq7)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

**Review by gbrodman — COMMENTED** [review]
Yeah I mean we can definitely delete that, but my point is that while we can retain styles of code, the objects themselves are completely different so we'll want a new Datastore entity. I'll delete the old one in my new PR though. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174#-:-Maj6Jg30Q9f644i4RNH:blq2ayk)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java, line 25 at r3](https://reviewable.io/reviews/google/nomulus/1174#-MbDG_604QiMfMNqYyFf:-MbDG_604QiMfMNqYyFg:b-3g77g6) ([raw file](https://github.com/google/nomulus/blob/e96d9a216ad8a170d3a5a98b9d9fdff902a6731c/core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java#L25)):*
> ```Java
> /** A command to check the current Registry 3.0 migration state of the database. */
> @Parameters(separators = " =", commandDescription = "Check current Registry 3.0 migration state")
> public class CheckDatabaseMigrationStateCommand implements CommandWithRemoteApi {
> ```

I get `Get` is a better verb here than `Check`.  `Check` implies that verification is happening, but there is no verification happening; this is just a `Get`, same as the other similarly named nomulus tool commands also prefixed with `Get`.
___
*[core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java, line 29 at r2](https://reviewable.io/reviews/google/nomulus/1174#-Mad4p67-Ap6kNXboi1x:-MbDGnU2BjErGP11qZ0m:b-jsj6qu) ([raw file](https://github.com/google/nomulus/blob/6dbbd94407c41121f946ba9e11506fdce431f122/core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java#L29)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These changes need to be schedulable as per my comments on the design doc.  See Sarah's implement of the primary database setting which uses a `TimedTransitionMap`.
</blockquote></details>

Resolved, looks like.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java, line 36 at r3](https://reviewable.io/reviews/google/nomulus/1174#-MbDH5gE9D4g21evUju3:-MbDH5gE9D4g21evUju4:bhh9n0p) ([raw file](https://github.com/google/nomulus/blob/e96d9a216ad8a170d3a5a98b9d9fdff902a6731c/core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java#L36)):*
> ```Java
>   private static final String WARNING_MESSAGE =
>       "Attempting to change the schedule with an effect that would take place within the next 10 "
>           + "minutes. The schedule cache is refreshed every 5 minutes so this MAY BE DANGEROUS.\n";
> ```

s/is refreshed every/duration interval is/

Your phrasing is not how cache duration intervals work; there is no periodic refreshing on a set schedule like that.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java, line 25 at r3](https://reviewable.io/reviews/google/nomulus/1174#-MbDG_604QiMfMNqYyFf:-MbDHnm0EMsU_opBxKDi:bl6kolz) ([raw file](https://github.com/google/nomulus/blob/e96d9a216ad8a170d3a5a98b9d9fdff902a6731c/core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java#L25)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I get `Get` is a better verb here than `Check`.  `Check` implies that verification is happening, but there is no verification happening; this is just a `Get`, same as the other similarly named nomulus tool commands also prefixed with `Get`.
</blockquote></details>

Well I can't edit that first sentence but you can figure out what I meant.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java, line 36 at r3](https://reviewable.io/reviews/google/nomulus/1174#-MbDH5gE9D4g21evUju3:-MbHxqWLEBJKaeHGjfFm:bwx72vk) ([raw file](https://github.com/google/nomulus/blob/e96d9a216ad8a170d3a5a98b9d9fdff902a6731c/core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java#L36)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

s/is refreshed every/duration interval is/

Your phrasing is not how cache duration intervals work; there is no periodic refreshing on a set schedule like that.
</blockquote></details>

I mean, it will be refreshed any time someone calls `tm()` so it'll probably be very close to periodic refreshing. But point taken.
___
*[core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java, line 25 at r3](https://reviewable.io/reviews/google/nomulus/1174#-MbDG_604QiMfMNqYyFf:-MbHwPLK6fpkS3pzF-kG:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e96d9a216ad8a170d3a5a98b9d9fdff902a6731c/core/src/main/java/google/registry/tools/CheckDatabaseMigrationStateCommand.java#L25)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Well I can't edit that first sentence but you can figure out what I meant.
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1174)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java, line 36 at r3](https://reviewable.io/reviews/google/nomulus/1174#-MbDH5gE9D4g21evUju3:-MbIl1i67ceWql_g2Ppt:bf62uvr) ([raw file](https://github.com/google/nomulus/blob/e96d9a216ad8a170d3a5a98b9d9fdff902a6731c/core/src/main/java/google/registry/tools/SetDatabaseMigrationStateCommand.java#L36)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I mean, it will be refreshed any time someone calls `tm()` so it'll probably be very close to periodic refreshing. But point taken.
</blockquote></details>

Not on, e.g., `tools` or `backend` instances.

Also the wording here still isn't quite correct.

"The duration interval of the cache is every 5 minutes"

It's not *every* 5 minutes, it is 5 minutes period.  Should be something like "The cache duration interval is 5 minutes ..."

**Pull request merged**
