### PR TITLE
Convert remaining Contact flows to tm()

### PR DESCRIPTION
**Pull request by hstonec**
Converted the remaining Contact flows, i.e. `ContactCreateFlow`, `ContactUpdateFlow` and `ContactCheckFlow` to use `tm()`.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/924)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/924)* status: all files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/main/java/google/registry/model/eppcommon/Address.java, line 206 at r1](https://reviewable.io/reviews/google/nomulus/924#-MQYHdbN96L_h18AAsxT:-MQYHdbN96L_h18AAsxU:bwxix5w) ([raw file](https://github.com/google/nomulus/blob/5a419e081d99d4ae046a4a061d5b85b934d86145/core/src/main/java/google/registry/model/eppcommon/Address.java#L206)):*
> ```Java
>    * reconstructed from XML message.
>    *
>    * <p>This is a callback function that JAXB invokes after unmarshalling the XML message.
> ```

Is there really no annotation or anything for this? That's lame on the part of JAXB. Why is this change necessary here, out of curiosity?

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/924)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/eppcommon/Address.java, line 206 at r1](https://reviewable.io/reviews/google/nomulus/924#-MQYHdbN96L_h18AAsxT:-MQYdPg39e5Alq-oSGfY:bd6pkd) ([raw file](https://github.com/google/nomulus/blob/5a419e081d99d4ae046a4a061d5b85b934d86145/core/src/main/java/google/registry/model/eppcommon/Address.java#L206)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Is there really no annotation or anything for this? That's lame on the part of JAXB. Why is this change necessary here, out of curiosity? 
</blockquote></details>

I couldn't find any annotation for this specific use case. So, in `ContactUpdateFlow`, the update XML request with address change will be unmarshalled to `Address` instance then set to the `ContactResource` if there is any difference. (See [here](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/flows/contact/ContactUpdateFlow.java;l=120-133?q=contactupdateflow&ss=nomulus%2Fnomulus)). 

Right now, we need to keep both `List<String> street`(used in Datastore) and `streetLine1, streetLine2, streetLine3` (used in Cloud SQL) for backwards compatibility. So, when the `Address` instance is unmarshalled from the XML request, we also need to make sure all these street fields are set correctly, otherwise the street information will be lost when it is stored to Cloud SQL(because it uses streetLine1, streetLine2 and streetLine3 but only the List<String> street is set).

It would be nice if JAXB provides annotation for readonly elements like JPA does but I cannot find any, also I am not sure if there is a way to map multiple `<contact:street>` tags to `streetLine1, streetLine2, streetLine3` in a correct order. Below is part of the update XML request for your reference:

```xml
<contact:postalInfo type="int">
    <contact:org/>
    <contact:addr>
        <contact:street>124 Example Dr.</contact:street>
        <contact:street>Suite 200</contact:street>
        <contact:city>Dulles</contact:city>
        <contact:sp>VA</contact:sp>
        <contact:pc>20166-6503</contact:pc>
        <contact:cc>US</contact:cc>
    </contact:addr>
</contact:postalInfo>
```

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/924)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[core/src/main/java/google/registry/model/eppcommon/Address.java, line 206 at r1](https://reviewable.io/reviews/google/nomulus/924#-MQYHdbN96L_h18AAsxT:-MQsUzSx7VCrQnpx5Jgk:bv8c6gd) ([raw file](https://github.com/google/nomulus/blob/5a419e081d99d4ae046a4a061d5b85b934d86145/core/src/main/java/google/registry/model/eppcommon/Address.java#L206)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

I couldn't find any annotation for this specific use case. So, in `ContactUpdateFlow`, the update XML request with address change will be unmarshalled to `Address` instance then set to the `ContactResource` if there is any difference. (See [here](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/flows/contact/ContactUpdateFlow.java;l=120-133?q=contactupdateflow&ss=nomulus%2Fnomulus)). 

Right now, we need to keep both `List<String> street`(used in Datastore) and `streetLine1, streetLine2, streetLine3` (used in Cloud SQL) for backwards compatibility. So, when the `Address` instance is unmarshalled from the XML request, we also need to make sure all these street fields are set correctly, otherwise the street information will be lost when it is stored to Cloud SQL(because it uses streetLine1, streetLine2 and streetLine3 but only the List<String> street is set).

It would be nice if JAXB provides annotation for readonly elements like JPA does but I cannot find any, also I am not sure if there is a way to map multiple `<contact:street>` tags to `streetLine1, streetLine2, streetLine3` in a correct order. Below is part of the update XML request for your reference:

```xml
<contact:postalInfo type="int">
    <contact:org/>
    <contact:addr>
        <contact:street>124 Example Dr.</contact:street>
        <contact:street>Suite 200</contact:street>
        <contact:city>Dulles</contact:city>
        <contact:sp>VA</contact:sp>
        <contact:pc>20166-6503</contact:pc>
        <contact:cc>US</contact:cc>
    </contact:addr>
</contact:postalInfo>
```
</blockquote></details>

OK cool, so this is basically to make sure that the SQL fields get populated correctly from XML requests. So this isn't directly related to the tm() conversions themselves -- the objects that were being created from XML weren't populated correctly anyway before this. 

Out of curiosity do you know if we have any tests that make sure that all the fields are populated correctly from the XML request? If so (and they include the `streetLine1` etc fields), they should have failed before this right?

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/924)* status: 6 of 7 files reviewed, all discussions resolved

___
*[core/src/main/java/google/registry/model/eppcommon/Address.java, line 206 at r1](https://reviewable.io/reviews/google/nomulus/924#-MQYHdbN96L_h18AAsxT:-MQsbVpiDT3SAJwOgsPs:bk5ehxk) ([raw file](https://github.com/google/nomulus/blob/5a419e081d99d4ae046a4a061d5b85b934d86145/core/src/main/java/google/registry/model/eppcommon/Address.java#L206)):*
>OK cool, so this is basically to make sure that the SQL fields get populated correctly from XML requests. So this isn't directly related to the tm() conversions themselves -- the objects that were being created from XML weren't populated correctly anyway before this.

Correct, more accurately, the `Address` instance from XML was not created correctly to be used for Cloud SQL, because we set `@Transient` to `Address.street` because we don't want to deal with `List` in this case, instead we added three individual `Address.streetLine${num}` fields as the table columns to store the street information, and these `Address.streetLine${num}` fields are not populated from XML until this PR.

>Out of curiosity do you know if we have any tests that make sure that all the fields are populated correctly from the XML request? If so (and they include the streetLine1 etc fields), they should have failed before this right?

It seems that we just don't have such test so I added one. See `ContactCommandTest`.

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/924)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[core/src/main/java/google/registry/model/eppcommon/Address.java, line 206 at r1](https://reviewable.io/reviews/google/nomulus/924#-MQYHdbN96L_h18AAsxT:-MQwfNY-B6OeKeCfZmly:b-hkagas) ([raw file](https://github.com/google/nomulus/blob/5a419e081d99d4ae046a4a061d5b85b934d86145/core/src/main/java/google/registry/model/eppcommon/Address.java#L206)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

>OK cool, so this is basically to make sure that the SQL fields get populated correctly from XML requests. So this isn't directly related to the tm() conversions themselves -- the objects that were being created from XML weren't populated correctly anyway before this.

Correct, more accurately, the `Address` instance from XML was not created correctly to be used for Cloud SQL, because we set `@Transient` to `Address.street` because we don't want to deal with `List` in this case, instead we added three individual `Address.streetLine${num}` fields as the table columns to store the street information, and these `Address.streetLine${num}` fields are not populated from XML until this PR.

>Out of curiosity do you know if we have any tests that make sure that all the fields are populated correctly from the XML request? If so (and they include the streetLine1 etc fields), they should have failed before this right?

It seems that we just don't have such test so I added one. See `ContactCommandTest`.
</blockquote></details>

great, thank you very much

**Pull request merged**
