### PR TITLE
Add a no-async actions DB migration phase

### PR DESCRIPTION
**Pull request by CydeWeys**
This needs to be set several hours prior to entering the READONLY stage. This is
not a read-only stage; all synchronous actions under Datastore (such as domain
creates) will continue to succeed. The only thing that will fail is host
deletes, host renames, and contact deletes, as these three actions require a
mapreduce to run before they are complete, and we don't want mapreduces hanging
around and executing during what is supposed to be a short duration READONLY
period.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1579)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
lgtm modulo one small comment and we probably want some tests 

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579#-:-MzVsQ-HDaWor_V1Z02s:b-jibfq2)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java, line 169 at r1](https://reviewable.io/reviews/google/nomulus/1579#-MzVrnx10dVQ_qqi1sPS:-MzVrnx10dVQ_qqi1sPT:bqcwa5c) ([raw file](https://github.com/google/nomulus/blob/43d9fcae0d7ad14bd9cdd9f8c1f487e06cf8aeaa/core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java#L169)):*
> ```Java
>                 MigrationState.DATASTORE_PRIMARY_NO_ASYNC)
>             .putAll(
>                 MigrationState.DATASTORE_PRIMARY_NO_ASYNC,
> ```

small, but technically we can go from NO_ASYNC to ONLY as well

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java, line 169 at r1](https://reviewable.io/reviews/google/nomulus/1579#-MzVrnx10dVQ_qqi1sPS:-Mz_l-hSBdBjVqfLz4U0:b-896fix) ([raw file](https://github.com/google/nomulus/blob/43d9fcae0d7ad14bd9cdd9f8c1f487e06cf8aeaa/core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java#L169)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

small, but technically we can go from NO_ASYNC to ONLY as well 
</blockquote></details>

Done.

**Review by CydeWeys — COMMENTED** [review]
Now with all tests.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579#-:-Mz_l4H4CMpGRuuGt5D1:b-y9a0ew)* status: 7 of 15 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java, line 263 at r3](https://reviewable.io/reviews/google/nomulus/1579#-Mz_wIVQB6_GPwTUC46t:-Mz_wIVQB6_GPwTUC46u:b-9u9plk) ([raw file](https://github.com/google/nomulus/blob/e5a183b63caeddb21055ab54130e60b8885813f9/core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java#L263)):*
> ```Java
>     EppException thrown = assertThrows(ReadOnlyModeEppException.class, this::runFlow);
>     assertAboutEppExceptions().that(thrown).marshalsToXml();
>     DatabaseHelper.removeDatabaseMigrationSchedule();
> ```

can we put this in an AfterEach method and remove it from any other places we call it? 
___
*[core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java, line 845 at r3](https://reviewable.io/reviews/google/nomulus/1579#-Mz_wQngDW7SqvfZlrwo:-Mz_wQngDW7SqvfZlrwp:b-rmkdi9) ([raw file](https://github.com/google/nomulus/blob/e5a183b63caeddb21055ab54130e60b8885813f9/core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java#L845)):*
> ```Java
>   @TestOfyOnly
>   void testSuccess_inNoAsyncPhase() throws Exception {
>     DatabaseHelper.setMigrationScheduleToDatastorePrimaryNoAsync(clock);
> ```

same thing as the other test, we should probably remove this in an AfterEach. Maybe putting it in an AfterEach in the FlowTestCase?

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java, line 263 at r3](https://reviewable.io/reviews/google/nomulus/1579#-Mz_wIVQB6_GPwTUC46t:-MzabIAU9E2UAChikv5K:b-lp4qzt) ([raw file](https://github.com/google/nomulus/blob/e5a183b63caeddb21055ab54130e60b8885813f9/core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java#L263)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can we put this in an AfterEach method and remove it from any other places we call it? 
</blockquote></details>

It doesn't make sense to put it in an `@AfterEach` as it's not in the `@BeforeEach` and it's not relevant to the vast majority of tests in this class anyway.  How about putting it in a `finally` block?

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java, line 845 at r3](https://reviewable.io/reviews/google/nomulus/1579#-Mz_wQngDW7SqvfZlrwo:-MzabbCaB0It_6OInoLh:b-89a4l7) ([raw file](https://github.com/google/nomulus/blob/e5a183b63caeddb21055ab54130e60b8885813f9/core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java#L845)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

same thing as the other test, we should probably remove this in an AfterEach. Maybe putting it in an AfterEach in the FlowTestCase?
</blockquote></details>

Ditto

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java, line 263 at r3](https://reviewable.io/reviews/google/nomulus/1579#-Mz_wIVQB6_GPwTUC46t:-MzaczTZ3R-Klx705pOC:b9mko7n) ([raw file](https://github.com/google/nomulus/blob/e5a183b63caeddb21055ab54130e60b8885813f9/core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java#L263)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It doesn't make sense to put it in an `@AfterEach` as it's not in the `@BeforeEach` and it's not relevant to the vast majority of tests in this class anyway.  How about putting it in a `finally` block?
</blockquote></details>

And that would move the cleanup a lot farther away from the setup that necessitates it, which makes it harder to reason about the reasons for things overall (and makes it more error-prone if you're trying to duplicate this kind of testing elsewhere -- you'll see the setup in the unit test but most likely miss the cleanup).

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java, line 263 at r3](https://reviewable.io/reviews/google/nomulus/1579#-Mz_wIVQB6_GPwTUC46t:-MzaesEZ3vGH-BBzeh7v:b-gz3rcj) ([raw file](https://github.com/google/nomulus/blob/e5a183b63caeddb21055ab54130e60b8885813f9/core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java#L263)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

And that would move the cleanup a lot farther away from the setup that necessitates it, which makes it harder to reason about the reasons for things overall (and makes it more error-prone if you're trying to duplicate this kind of testing elsewhere -- you'll see the setup in the unit test but most likely miss the cleanup).
</blockquote></details>

I'm thinking of something similar in concept to the TmOverrideExtension, where the AfterEach statement there makes sure to clean up after any tests that may have changed the schedule. The reason for doing that in an extension or an AfterEach method is that if a test fails to clean up after itself, it will still succeed but only (maybe!) cause other tests elsewhere to fail, obscuring what's actually going on and delaying test failures one runs everything at once (and even then maybe it's just a flake)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java, line 263 at r3](https://reviewable.io/reviews/google/nomulus/1579#-Mz_wIVQB6_GPwTUC46t:-MzafcAI2gJ2Rzt6GKIZ:b-njafn5) ([raw file](https://github.com/google/nomulus/blob/e5a183b63caeddb21055ab54130e60b8885813f9/core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java#L263)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I'm thinking of something similar in concept to the TmOverrideExtension, where the AfterEach statement there makes sure to clean up after any tests that may have changed the schedule. The reason for doing that in an extension or an AfterEach method is that if a test fails to clean up after itself, it will still succeed but only (maybe!) cause other tests elsewhere to fail, obscuring what's actually going on and delaying test failures one runs everything at once (and even then maybe it's just a flake) 
</blockquote></details>

It's not worth it to go to those lengths though.  These are a small number of tests that are all going away in a month once the migration is complete.  The "it might affect other tests" concern can be solved through the use of a `finally` clause, but as currently written, so long as the test is passing (and it is), it won't affect anything else.

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1579)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java, line 263 at r3](https://reviewable.io/reviews/google/nomulus/1579#-Mz_wIVQB6_GPwTUC46t:-MzagiEu6O4DMQbI22Bd:b-ppgadq) ([raw file](https://github.com/google/nomulus/blob/e5a183b63caeddb21055ab54130e60b8885813f9/core/src/test/java/google/registry/flows/contact/ContactDeleteFlowTest.java#L263)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It's not worth it to go to those lengths though.  These are a small number of tests that are all going away in a month once the migration is complete.  The "it might affect other tests" concern can be solved through the use of a `finally` clause, but as currently written, so long as the test is passing (and it is), it won't affect anything else.
</blockquote></details>

yeah a `finally` clause definitely isn't the solution. 

meh yeah it's a good point that we're getting rid of this before long (hopefully)

**Pull request merged**
