### PR TITLE
Add Console Settings -> Security front-end

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2079)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2079)* status: all files reviewed, 9 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/dev-proxy.config.json` line 4 at r2](https://reviewable.io/reviews/google/nomulus/2079#-N_eFPuj6rUV9lk3SrwY:-N_eFPuj6rUV9lk3SrwZ:b-gmbsda) ([raw file](https://github.com/google/nomulus/blob/ec41c6d1fd475ccae7ecb1caf8350a6dd0a5c51d/console-webapp/dev-proxy.config.json#L4)):*
> ```JSON
>   "/console-api":
>   {
>     "target": "https://domain-registry-alpha.appspot.com",
> ```

hm i'm not sure we want to push this if we're usually developing everything against the local dev server? 

also, technically this won't work for other open-source users 
___
*[`console-webapp/src/app/settings/contact/contact.component.ts` line 107 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_ipx1-5t7OzA0UiGjn:-N_ipx100Cue8Y-7kdHK:btacek) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/contact/contact.component.ts#L107)):*
> ```XML
>   }
> 
>   onClose(e: any) {
> ```

this (and the other event methods) should probably have an actual type of the event -- I'm not sure what that is, but it seems like there are some kinda-generic Event types in the Typescript spec that correspond to DOM events. Have you tried to figure out exactly what type this should be? 
___
*[`console-webapp/src/app/settings/security/security.component.html` line 7 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_j8Ge06C86M28WLAYJ:-N_j8Ge06C86M28WLAYK:b8c4502) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.component.html#L7)):*
> ```HTML
>   <div class="settings-security__section">
>     <div class="settings-security__section-description">
>       <h2>IP Allow Whitelist</h2>
> ```

technically we'll want to use the term `IP Allowlist`, even if it's a bit awkward 
___
*[`console-webapp/src/app/settings/security/security.component.html` line 16 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jAsbw8W22pPxlsg7M:-N_jAsbw8W22pPxlsg7N:bci911e) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.component.html#L16)):*
> ```HTML
>       <div
>         *ngIf="
>           dataSource.ipAddressAllowList &&
> ```

Do we need to check for both null/undefined and an empty list? What happens if the list is empty? and we don't have this check? 
___
*[`console-webapp/src/app/settings/security/security.component.html` line 18 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jAQq6Bw50qQAwspJZ:-N_jAQq6Bw50qQAwspJ_:b-91z1iz) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.component.html#L18)):*
> ```HTML
>           dataSource.ipAddressAllowList &&
>           dataSource.ipAddressAllowList.length > 0
>         "
> ```

out of curiosity, does the formatter add these newlines? 
___
*[`console-webapp/src/app/settings/security/security.component.html` line 33 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jBIw20gjD3tJ3aXx-:-N_jBIw37Tw6RSj4w5aS:b-7t9g4q) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.component.html#L33)):*
> ```HTML
>               mat-icon-button
>               aria-label="Remove"
>               (click)="removeIpEntry(index)"
> ```

out of curiosity did you give any thought to removal of the IP address by index (what you're doing here) vs by value? I assume that there's some way of saying "remove this element from this list" 
___
*[`console-webapp/src/app/settings/security/security.service.ts` line 50 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jE_tw11Tn8kSSI70Y:-N_jEKGwCZcVvekIqu4d:b-e25y6y) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.service.ts#L50)):*
> ```XML
>         tap((securitySettings: SecuritySettingsBackendModel) => {
>           if(securitySettings) {
>             this.securitySettings = Object.assign({}, securitySettings, {
> ```

What does the `Object.assign` bit do? It seems to me like this is converting the response from the API into the form we want, is that right / why is that necessary? 
___
*[`console-webapp/src/app/settings/security/security.service.ts` line 72 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jF-S14SU_BgsZT-7s:-N_jF-S14SU_BgsZT-7t:blke4a0) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.service.ts#L72)):*
> ```XML
>     )
>     .pipe(
>       tap((_) => {
> ```

why are we using `tap` if we're not using the value? I thought that `tap` was essentially for doing something with a value as we pass it through
___
*[`console-webapp/src/app/settings/security/security.service.spec.ts` line 14 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jCT7o2PtM-EQzl4eW:-N_jCT7o2PtM-EQzl4eX:bqlkgzn) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.service.spec.ts#L14)):*
> ```XML
> // See the License for the specific language governing permissions and
> // limitations under the License.
> ```

Did you mention wanting to write tests for this, or are you thinking of saving that for the future?
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 67 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jCpfJ4sRc1UylMW4D:-N_jCpfJ4sRc1UylMW4E:bkswj5f) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/shared/services/backend.service.ts#L67)):*
> ```XML
>       .pipe(catchError((err) => this.errorCatcher<string[]>(err)));
>   }
> ```

at some point should we consider retrieving the entire registrar object once when the user selects it, then just passing around the required bits of data? I think I remember you mentioning it, but to be honest if it doesn't create problems to retrieve bits at a time it's probably safer to do it this way.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2079)* status: 8 of 19 files reviewed, 9 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/dev-proxy.config.json` line 4 at r2](https://reviewable.io/reviews/google/nomulus/2079#-N_eFPuj6rUV9lk3SrwY:-N_ncs9RCrEY8IyEm1tb:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ec41c6d1fd475ccae7ecb1caf8350a6dd0a5c51d/console-webapp/dev-proxy.config.json#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

hm i'm not sure we want to push this if we're usually developing everything against the local dev server? 

also, technically this won't work for other open-source users 
</blockquote></details>

Done.
___
*[`console-webapp/src/app/settings/contact/contact.component.ts` line 107 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_ipx1-5t7OzA0UiGjn:-N_nctDJ7p2GWaQ2dNyJ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/contact/contact.component.ts#L107)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this (and the other event methods) should probably have an actual type of the event -- I'm not sure what that is, but it seems like there are some kinda-generic Event types in the Typescript spec that correspond to DOM events. Have you tried to figure out exactly what type this should be? 
</blockquote></details>

Done.
___
*[`console-webapp/src/app/settings/security/security.component.html` line 7 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_j8Ge06C86M28WLAYJ:-N_ncuCb0aZqcbo-M8py:b-896fix) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.component.html#L7)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

technically we'll want to use the term `IP Allowlist`, even if it's a bit awkward 
</blockquote></details>

Done.
___
*[`console-webapp/src/app/settings/security/security.component.html` line 16 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jAsbw8W22pPxlsg7M:-N_nY_NyEqcC9LObOYnG:b1w0qdm) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.component.html#L16)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Do we need to check for both null/undefined and an empty list? What happens if the list is empty? and we don't have this check? 
</blockquote></details>

I wasn't going to check for empty list, but typescript just won't let it compile without this check, so I had to add it. 
___
*[`console-webapp/src/app/settings/security/security.component.html` line 18 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jAQq6Bw50qQAwspJZ:-N_p4Td50WiTVeluSuK6:b2nhswy) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.component.html#L18)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

out of curiosity, does the formatter add these newlines? 
</blockquote></details>

Yes
___
*[`console-webapp/src/app/settings/security/security.component.html` line 33 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jBIw20gjD3tJ3aXx-:-N_nZ6Mn7WUcJJun2yW5:b7h6nhi) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.component.html#L33)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

out of curiosity did you give any thought to removal of the IP address by index (what you're doing here) vs by value? I assume that there's some way of saying "remove this element from this list" 
</blockquote></details>

There's no such method in javascript to remove element from the list, `splice` does it by index and it's mutable. Generally `filter` is considered to be a way around it, which you can use with either index or reference. To me index seems more intuitive. 
___
*[`console-webapp/src/app/settings/security/security.service.ts` line 50 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jE_tw11Tn8kSSI70Y:-N_n_67B25Ql3QxbwFWB:b-vpj3vi) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.service.ts#L50)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What does the `Object.assign` bit do? It seems to me like this is converting the response from the API into the form we want, is that right / why is that necessary? 
</blockquote></details>

Correct .`Object.assign` converts list of strings (API) to list of objects (Frontend) and back. It's necessary because from Java side the `ipAddressAllowList` is naturally and historically a list of strings, however Angular binding doesn't work well with list of strings, causing rerenders and focus being constantly lost on the field. Making a simple conversion seemed like the easiest solution. 
___
*[`console-webapp/src/app/settings/security/security.service.ts` line 72 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jF-S14SU_BgsZT-7s:-N_naCac3nM1cED07t2k:b-k5gh6u) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.service.ts#L72)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

why are we using `tap` if we're not using the value? I thought that `tap` was essentially for doing something with a value as we pass it through
</blockquote></details>

We're "doing something with a value" - we're saving it. `tap` is used for any side effect in observable, which is exactly our case here. 
___
*[`console-webapp/src/app/settings/security/security.service.spec.ts` line 14 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jCT7o2PtM-EQzl4eW:-N_p441L5sSMZ0rLKzQH:b-1yzgki) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.service.spec.ts#L14)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Did you mention wanting to write tests for this, or are you thinking of saving that for the future?
</blockquote></details>

I'm working on tests in parallel, but I have a feeling that at some point, probably as soon as old console is reimplemented, we will revisit the tests topic
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 67 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jCpfJ4sRc1UylMW4D:-N_nbz3J1yIVMgRVC_-H:b-wo4otd) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/shared/services/backend.service.ts#L67)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

at some point should we consider retrieving the entire registrar object once when the user selects it, then just passing around the required bits of data? I think I remember you mentioning it, but to be honest if it doesn't create problems to retrieve bits at a time it's probably safer to do it this way.
</blockquote></details>

That's absolutely correct, my initial idea was to retrieve registrar info entirely and work with it on frontend, however the more I thought about it during both frontend and backend implementations I realized we'd be better off dealing with parts of the object instead.

**Comment by ptkach** [comment]
@gbrodman  Please let me know if you have any suggestions here, as I believe it's in a good shape now and I'd like to get it merged. Thanks!

**Comment by 1proprogrammerchant** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/2079)_ status: 7 of 19 files reviewed, 13 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])
> 
> _[`console-webapp/src/app/settings/security/security.component.spec.ts` line 30 at r5](https://reviewable.io/reviews/google/nomulus/2079#gh-1270884364:-Na84Xt17RrM6svivt29:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f6b63f38b046328fe8658c5efc8b14470dfe2c1/console-webapp/src/app/settings/security/security.component.spec.ts#L30)):_
> 
> Previously, github-code-scanning[bot] wrote…
> Done.
> 
> _[`console-webapp/src/app/settings/security/security.service.spec.ts` line 19 at r5](https://reviewable.io/reviews/google/nomulus/2079#gh-1270884366:-Na84fntEaEsOagG42av:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f6b63f38b046328fe8658c5efc8b14470dfe2c1/console-webapp/src/app/settings/security/security.service.spec.ts#L19)):_
> 
> Previously, github-code-scanning[bot] wrote…
> Done.
> 
> _[`console-webapp/src/app/settings/security/security.service.spec.ts` line 20 at r5](https://reviewable.io/reviews/google/nomulus/2079#gh-1270884372:-Na84gGdDy8QIO8mFfCd:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f6b63f38b046328fe8658c5efc8b14470dfe2c1/console-webapp/src/app/settings/security/security.service.spec.ts#L20)):_
> 
> Previously, github-code-scanning[bot] wrote…
> Done.
> 
> _[`console-webapp/src/app/settings/security/security.service.spec.ts` line 21 at r5](https://reviewable.io/reviews/google/nomulus/2079#gh-1270884375:-Na84gjk1HbNGTAz6Q3V:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0f6b63f38b046328fe8658c5efc8b14470dfe2c1/console-webapp/src/app/settings/security/security.service.spec.ts#L21)):_
> 
> Previously, github-code-scanning[bot] wrote…
> Done. 
this is a nice change

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r4, 4 of 4 files at r6, all commit messages.
> Dismissed @gbrodman from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2079)* status: all files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`console-webapp/src/app/settings/security/security.component.spec.ts` line 151 at r6](https://reviewable.io/reviews/google/nomulus/2079#-NaDkcu8AO59uoXbOIEl:-NaDkcu8AO59uoXbOIEm:b-7m9pri) ([raw file](https://github.com/google/nomulus/blob/4dc55341a707eaf892b05ef73980acd61b6debe8/console-webapp/src/app/settings/security/security.component.spec.ts#L151)):*
> ```XML
>       .querySelector('.settings-security__actions-save')
>       .click();
>     expect(saveSpy).toHaveBeenCalledOnceWith({
> ```

neat!
___
*[`console-webapp/src/app/settings/security/security.service.ts` line 72 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jF-S14SU_BgsZT-7s:-NaDf4Ao24J7hvNFAAdC:bo8jrhz) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.service.ts#L72)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

We're "doing something with a value" - we're saving it. `tap` is used for any side effect in observable, which is exactly our case here. 
</blockquote></details>

Maybe I'm missing something but why would we do this instead of just calling subscribe? 
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 67 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jCpfJ4sRc1UylMW4D:-NaDgLr48N-RFUUJkhty:b-4u9l00) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/shared/services/backend.service.ts#L67)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

That's absolutely correct, my initial idea was to retrieve registrar info entirely and work with it on frontend, however the more I thought about it during both frontend and backend implementations I realized we'd be better off dealing with parts of the object instead. 
</blockquote></details>

yeah that's fair, just noting what we talked about where if we get to the point where there's more than a couple different little bits we're dealing with we might want to end up just using the whole registrar

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2079)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot])

___
*[`console-webapp/src/app/settings/security/security.service.ts` line 72 at r3](https://reviewable.io/reviews/google/nomulus/2079#-N_jF-S14SU_BgsZT-7s:-NaI3LC95paXS8vzMX_c:buj1z7n) ([raw file](https://github.com/google/nomulus/blob/739207431855e0f5d0127e1794c79c541098f99d/console-webapp/src/app/settings/security/security.service.ts#L72)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Because we have 2 separate things we need to do based on the completion of the the observer:
1) Stop loading indicator - that's a view responsibility to deal with view-related logic
2) Save data - that's a service responsibility to deal with the data

Given that there's only a single subscriber allowed on a observer I don't think we have a better way to deal with this logic. 

</blockquote></details>

got it, yeah i didn't realize that we were returning an observable that someone else subscribed to -- in that case, this makes complete sense

**Pull request merged**
