### PR TITLE
Convert more classes to using SQL / TM

### PR DESCRIPTION
**Pull request by gbrodman**
Nothing much particularly crazy here

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1067)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1067)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/tools/UnrenewDomainCommand.java, line 90 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrQSsP3yW0YJKM3UgH:-MXrQSsP3yW0YJKM3UgI:b4p63a8) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/UnrenewDomainCommand.java#L90)):*
> ```Java
> 
>     for (String domainName : mainParameters) {
>       if (ForeignKeyIndex.load(DomainBase.class, domainName, START_OF_TIME) == null) {
> ```

This is definitely one of those things that will require substantial clean-up post-migration to get rid of the `ForeignKeyIndex` concept entirely.  What this should really be is a `SELECT` query to which domain names don't have existing `Domain` rows.
___
*[core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java, line 151 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrQeT64kbjzKMIXMM1:-MXrQeT64kbjzKMIXMM2:b-vpbqul) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java#L151)):*
> ```Java
>   /** Loads in all {@link DomainBase} objects for a given FQDN. */
>   private List<DomainBase> loadDomainsForFqdn(String fullyQualifiedDomainName) {
>     if (tm().isOfy()) {
> ```

This query is actually really simple and would be a good candidate for the API Mike is working on.
___
*[core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java, line 162 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrJy_94PLG8zgOX6lF:-MXrJCul3vTbdq0dj9Vi:b-xf04xx) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java#L162)):*
> ```Java
>               () ->
>                   jpaTm()
>                       .query("FROM Domain WHERE fullyQualifiedDomainName = :fqdn", DomainBase.class)
> ```

I can't wait till we're off Datastore entirely and can rename these fields so we don't have to keep using the overly-lengthy `fullyQualifiedDomainName`.
___
*[core/src/main/java/google/registry/tools/javascrap/RemoveIpAddressCommand.java, line 63 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrIoSsBawf5tf_UYvV:-MXrIoSsBawf5tf_UYvW:b-8p2ssc) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/javascrap/RemoveIpAddressCommand.java#L63)):*
> ```Java
>       HostResource host =
>           transactIfJpaTm(
>               () -> tm().loadByKeyIfPresent(VKey.create(HostResource.class, roid)).orElse(null));
> ```

`loadByKeyIfPresent()` returns `Optional`.  Why are you coercing that to null then checking nullness below?!  Just use Optional correctly as god intended.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1067)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/tools/UnrenewDomainCommand.java, line 90 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrQSsP3yW0YJKM3UgH:-MXruRGH-U6sBs7Rlp_X:byjav7g) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/UnrenewDomainCommand.java#L90)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is definitely one of those things that will require substantial clean-up post-migration to get rid of the `ForeignKeyIndex` concept entirely.  What this should really be is a `SELECT` query to which domain names don't have existing `Domain` rows.
</blockquote></details>

Yes, we will likely be able to write a better API for retrieving `EppResource`s with particular indexed characteristics. 
___
*[core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java, line 151 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrQeT64kbjzKMIXMM1:-MXruOIl4QUDW7zqvMTf:b-9o43eb) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java#L151)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This query is actually really simple and would be a good candidate for the API Mike is working on.
</blockquote></details>

yeah, super easy 
___
*[core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java, line 162 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrJy_94PLG8zgOX6lF:-MXruMw2BjELJyV08_xw:bceuwbh) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java#L162)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I can't wait till we're off Datastore entirely and can rename these fields so we don't have to keep using the overly-lengthy `fullyQualifiedDomainName`.
</blockquote></details>

For sure.
___
*[core/src/main/java/google/registry/tools/javascrap/RemoveIpAddressCommand.java, line 63 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrIoSsBawf5tf_UYvV:-MXruGAc2weJt5euwynv:ba7au3o) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/javascrap/RemoveIpAddressCommand.java#L63)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`loadByKeyIfPresent()` returns `Optional`.  Why are you coercing that to null then checking nullness below?!  Just use Optional correctly as god intended.
</blockquote></details>

tbh not sure, i might have just tried to make as few changes to the javascrap files as possible

**Review by mindhog — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1067)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java, line 151 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrQeT64kbjzKMIXMM1:-MY56OYT7OVSmNR2OyfJ:bf1sqr8) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/javascrap/BackfillSpec11ThreatMatchesCommand.java#L151)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah, super easy 
</blockquote></details>

Agreed, but don't feel it necessary to block on that, I'll do a pass through the code to clean up any cases like that.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1067)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/javascrap/RemoveIpAddressCommand.java, line 63 at r1](https://reviewable.io/reviews/google/nomulus/1067#-MXrIoSsBawf5tf_UYvV:-MY5rMia7W35ywqODuuD:b4epdsf) ([raw file](https://github.com/google/nomulus/blob/0ba0f6990690d65a4f196ec8548ad17bfd1e81bb/core/src/main/java/google/registry/tools/javascrap/RemoveIpAddressCommand.java#L63)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

tbh not sure, i might have just tried to make as few changes to the javascrap files as possible
</blockquote></details>

either way, done

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1067)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
