### PR TITLE
Update bigdataoss:util dependency

### PR DESCRIPTION
**Pull request by gbrodman**
We're running into issues pulling 2.1.3 from maven, possibly due to
vulnerabilities in dependencies, so this updates it to the most recent
version of 2.2.6.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1654)

### CODE REVIEW

**Comment by mindhog** [comment]
Note that you'll need to run upgrade_dependency.sh to fix the presubmits.  Changes per show_upgrade_diffs:

```
updated com.fasterxml.jackson.core:jackson-core: {2.13.2} -> {2.13.3}                                                                                                                                                                                                           
updated com.fasterxml.jackson:jackson-bom: {2.13.2} -> {2.13.3}                                                                                                                                                                                                                  
updated com.google.api-client:google-api-client: {1.33.4, 1.34.0} -> {1.35.0, 1.34.0, 1.34.1}                                                                                                                                                                                    
updated com.google.api.grpc:proto-google-iam-v1: {1.3.1} -> {1.3.4}                                                                                                                                                                                                              
updated com.google.api:api-common: {2.1.5} -> {2.2.0}                                                                                                                                                                                                                            
updated com.google.api:gax-httpjson: {0.101.0} -> {0.103.1}                                                                                                                                                                                                                      
updated com.google.api:gax: {2.16.0} -> {2.18.1, 2.16.0}                                                                                                                                                                                                                         
updated com.google.apis:google-api-services-storage: {v1-rev20220401-1.32.1} -> {v1-rev20220509-1.32.1}                                                                                                                                                                          
updated com.google.auth:google-auth-library-credentials: {1.6.0} -> {1.7.0, 1.6.0}                                                                                                                                                                                               
updated com.google.auth:google-auth-library-oauth2-http: {1.6.0} -> {1.7.0, 1.6.0}                                                                                                                                                                                               
updated com.google.cloud:google-cloud-core-http: {2.6.0} -> {2.7.1}                                                                                                                                                                                                              
updated com.google.cloud:google-cloud-core: {2.6.0} -> {2.7.1}                                                                                                                                                                                                                   
updated com.google.cloud:google-cloud-storage: {2.6.1} -> {2.7.2}                                                                                                                                                                                                                
updated com.google.errorprone:error_prone_annotations: {2.7.1, 2.11.0, 2.13.0, 2.3.4} -> {2.7.1, 2.11.0, 2.13.1, 2.3.4}                                                                                                                                                          
updated com.google.http-client:google-http-client-apache-v2: {1.41.7, 1.41.5} -> {1.41.7, 1.41.8}                                                                                                                                                                                
updated com.google.http-client:google-http-client-appengine: {1.41.7} -> {1.41.8}                                                                                                                                                                                                
updated com.google.http-client:google-http-client-gson: {1.41.7, 1.41.5} -> {1.41.7, 1.41.8}                                                                                                                                                                                     
updated com.google.http-client:google-http-client-jackson2: {1.41.7} -> {1.41.8}                                                                                                                                                                                                 
updated com.google.http-client:google-http-client: {1.41.7, 1.41.5} -> {1.41.7, 1.41.8}                                                                                                                                                                                          
updated com.google.oauth-client:google-oauth-client: {1.33.2, 1.33.3, 1.33.1} -> {1.33.2, 1.34.0, 1.33.3}                                                                                                                                                                        
updated com.google.protobuf:protobuf-java-util: {3.19.4, 4.0.0-rc-2} -> {3.20.1, 4.0.0-rc-2}                                                                                                                                                                                     
updated com.google.protobuf:protobuf-java: {3.4.0, 2.5.0, 3.19.4, 4.0.0-rc-2} -> {3.20.1, 3.4.0, 2.5.0, 4.0.0-rc-2}                                                                                                                                                              
updated io.grpc:grpc-context: {1.45.1, 1.27.2} -> {1.27.2, 1.46.0}                                                                                                                                                                                                               
updated io.opencensus:opencensus-api: {0.31.0} -> {0.31.0, 0.31.1}                                                                                                                                                                                                               
updated io.opencensus:opencensus-contrib-http-util: {0.31.0} -> {0.31.0, 0.31.1}                                                                                                                                                                                                 
updated net.bytebuddy:byte-buddy-agent: {1.12.9} -> {1.12.10}                                                                                                                                                                                                                    
updated net.bytebuddy:byte-buddy: {1.12.9} -> {1.12.10, 1.12.9}                                                                                                                                                                                                                  
updated org.checkerframework:checker-qual: {3.21.4, 3.13.0, 2.10.0, 3.12.0, 2.11.1, 3.5.0, 3.0.0, 3.19.0} -> {3.13.0, 2.10.0, 3.12.0, 3.22.0, 2.11.1, 3.5.0, 3.0.0                                                                                                               , 3.19.0}                                                                                                                                                                                               
updated org.junit.jupiter:junit-jupiter-api: {5.8.2} -> {5.9.0-M1}                                                                                                                                                                                                               
updated org.junit.jupiter:junit-jupiter-engine: {5.8.2} -> {5.9.0-M1}                                                                                                                                                                                                            
updated org.junit.platform:junit-platform-commons: {1.8.2} -> {1.9.0-M1}                                                                                                                                                                                                         
updated org.junit.platform:junit-platform-engine: {1.8.2} -> {1.9.0-M1}                                                                                                                                                                                                          
updated org.junit:junit-bom: {5.8.2} -> {5.9.0-M1}                                                                                                                                                                                                                               
updated org.mockito:mockito-core: {1.10.19, 4.5.1} -> {4.6.1, 1.10.19}                                                                                                                                                                                                           
updated org.ow2.asm:asm-analysis: {7.1, 8.0.1, 9.2, 7.0} -> {7.1, 8.0.1, 9.3, 7.0}                                                                                                                                                                                               
updated org.ow2.asm:asm-tree: {7.1, 8.0.1, 9.2, 7.0} -> {7.1, 8.0.1, 9.3, 7.0}                                                                                                                                                                                                   
updated org.ow2.asm:asm-util: {9.2, 7.0} -> {9.3, 7.0}                                                                                                                                                                                                                           
updated org.ow2.asm:asm: {7.1, 8.0.1, 9.1, 9.2, 7.0} -> {7.1, 8.0.1, 9.1, 9.3, 7.0}                                                                                                                                                                                              
updated org.jetbrains.kotlin:kotlin-stdlib-common: {1.3.50, 1.5.32} -> {1.3.50, 1.6.10}                                                                                                                                                                                          
updated org.jetbrains.kotlin:kotlin-stdlib: {1.3.50, 1.5.32} -> {1.3.50, 1.6.10}                                                                                                                                                                                                 
updated com.fasterxml.jackson.core:jackson-annotations: {2.10.3, 2.13.2} -> {2.10.3, 2.13.3}                                                                                                                                                                                     
updated com.google.api.grpc:proto-google-cloud-tasks-v2: {2.1.11} -> {2.2.0}                                                                                                                                                                                                     
updated com.google.api.grpc:proto-google-cloud-tasks-v2beta2: {0.91.11} -> {0.92.0}                                                                                                                                                                                              
updated com.google.api.grpc:proto-google-cloud-tasks-v2beta3: {0.91.11} -> {0.92.0}                                                                                                                                                                                              
updated com.google.api:gax-grpc: {2.16.0} -> {2.18.1}                                                                                                                                                                                                                            
updated com.google.appengine:appengine-api-1.0-sdk: {1.9.86} -> {1.9.86, 2.0.5}                                                                                                                                                                                                  
updated com.google.cloud:google-cloud-tasks: {2.1.11} -> {2.2.0}                                                                                                                                                                                                                 
updated com.google.dagger:dagger: {2.41} -> {2.42}                                                                                                                                                                                                                               
updated io.grpc:grpc-api: {1.45.1} -> {1.46.0}                                                                                                                                                                                                                                  
updated io.grpc:grpc-protobuf-lite: {1.45.1} -> {1.46.0}                                                                                                                                                                                                                         
updated io.grpc:grpc-protobuf: {1.45.1} -> {1.46.0}                                                                                                                                                                                                                              
updated io.grpc:grpc-stub: {1.45.1} -> {1.46.0}                                                                                                                                                                                                                                  
updated io.netty:netty-tcnative-boringssl-static: {2.0.51.Final, 2.0.46.Final} -> {2.0.52.Final, 2.0.46.Final}                                                                                                                                                                   
updated io.netty:netty-tcnative-classes: {2.0.51.Final, 2.0.46.Final} -> {2.0.52.Final, 2.0.46.Final}                                                                                                                                                                            
updated org.junit.jupiter:junit-jupiter-params: {5.8.2} -> {5.9.0-M1}                                                                                                                                                                                                            
updated org.junit.platform:junit-platform-launcher: {1.8.2} -> {1.9.0-M1}                                                                                                                                                                                                        
updated org.junit.platform:junit-platform-runner: {1.8.2} -> {1.9.0-M1}                                                                                                                                                                                                          
updated org.junit.platform:junit-platform-suite-api: {1.8.2} -> {1.9.0-M1}                                                                                                                                                                                                       
updated org.testcontainers:junit-jupiter: {1.17.1} -> {1.17.2}                                                                                                                                                                                                                   
updated org.testcontainers:testcontainers: {1.17.1} -> {1.17.2}                                                                                                                                                                                                                  
updated io.grpc:grpc-alts: {1.45.1, 1.44.0} -> {1.44.0, 1.46.0}                                                                                                                                                                                                                  
updated io.grpc:grpc-auth: {1.45.1, 1.44.0} -> {1.44.0, 1.46.0}                                                                                                                                                                                                                  
updated io.grpc:grpc-core: {1.45.1, 1.44.1} -> {1.44.1, 1.46.0}                                                                                                                                                                                                                  
updated io.grpc:grpc-googleapis: {1.45.1} -> {1.46.0}                                                                                                                                                                                                                            
updated io.grpc:grpc-grpclb: {1.45.1, 1.44.0} -> {1.44.0, 1.46.0}                                                                                                                                                                                                                
updated io.grpc:grpc-netty-shaded: {1.45.1, 1.44.0} -> {1.44.0, 1.46.0}                                                                                                                                                                                                          
updated io.grpc:grpc-services: {1.45.1} -> {1.44.0, 1.46.0}                                                                                                                                                                                                                      
updated io.grpc:grpc-xds: {1.45.1} -> {1.44.0, 1.46.0}                                                                                                                                                                                                                          
updated io.perfmark:perfmark-api: {0.23.0} -> {0.25.0}
updated com.google.dagger:dagger-compiler: {2.41} -> {2.42}
updated com.google.dagger:dagger-producers: {2.41} -> {2.42}
updated com.google.dagger:dagger-spi: {2.41} -> {2.42}
updated org.jetbrains.kotlinx:kotlinx-metadata-jvm: {0.3.0} -> {0.4.2}
updated org.junit.platform:junit-platform-suite-commons: {1.8.2} -> {1.9.0-M1}
updated com.fasterxml.jackson.core:jackson-databind: {2.13.2} -> {2.13.3}
updated com.fasterxml.jackson.dataformat:jackson-dataformat-yaml: {2.13.2} -> {2.13.3}
added com.fasterxml.jackson.datatype:jackson-datatype-joda: {2.13.3}
added com.fasterxml.jackson.datatype:jackson-datatype-jsr310: {2.13.3}
updated com.google.api-client:google-api-client-appengine: {1.34.0} -> {1.35.0}
updated com.google.api-client:google-api-client-java6: {1.34.0} -> {1.35.0}
updated com.google.api-client:google-api-client-servlet: {1.34.0} -> {1.35.0}
updated com.google.api.grpc:grpc-google-cloud-bigtable-v2: {1.27.1} -> {2.5.3}
updated com.google.api.grpc:grpc-google-cloud-storage-v2: {2.0.1-alpha} -> {2.2.2-alpha}
added com.google.api.grpc:proto-google-cloud-monitoring-v3: {1.64.0}
updated com.google.api.grpc:proto-google-cloud-secretmanager-v1: {2.1.7} -> {2.2.0}
updated com.google.api.grpc:proto-google-cloud-secretmanager-v1beta1: {2.1.7} -> {2.2.0}
updated com.google.api.grpc:proto-google-cloud-storage-v2: {2.0.1-alpha} -> {2.2.2-alpha}
updated com.google.apis:google-api-services-appengine: {v1-rev20220326-1.32.1} -> {v1-rev20220509-1.32.1}
updated com.google.apis:google-api-services-cloudkms: {v1-rev20220415-1.32.1} -> {v1-rev20220513-1.32.1}
updated com.google.apis:google-api-services-monitoring: {v3-rev20220322-1.32.1} -> {v3-rev20220525-1.32.1}
updated com.google.apis:google-api-services-sqladmin: {v1beta4-rev20220310-1.32.1} -> {v1beta4-rev20220323-1.32.1}
updated com.google.appengine:appengine-remote-api: {2.0.4} -> {2.0.5}
updated com.google.cloud.bigdataoss:gcsio: {2.2.4} -> {2.2.6}
updated com.google.cloud.bigdataoss:util: {2.2.4} -> {2.2.6}
updated com.google.cloud.bigtable:bigtable-client-core: {1.25.1} -> {1.26.3}
updated com.google.cloud.bigtable:bigtable-metrics-api: {1.25.1} -> {1.26.3}
updated com.google.cloud.sql:jdbc-socket-factory-core: {1.5.0} -> {1.6.0}
updated com.google.cloud:google-cloud-bigtable: {1.27.1} -> {2.5.3}
added com.google.cloud:google-cloud-monitoring: {1.82.0}
updated com.google.cloud:google-cloud-secretmanager: {2.1.7} -> {2.2.0}
updated com.google.oauth-client:google-oauth-client-appengine: {1.33.3} -> {1.34.0}
updated com.google.oauth-client:google-oauth-client-java6: {1.33.3} -> {1.34.0}
updated com.google.oauth-client:google-oauth-client-jetty: {1.33.3} -> {1.34.0}
updated com.google.oauth-client:google-oauth-client-servlet: {1.33.3} -> {1.34.0}
added com.lmax:disruptor: {3.4.2}
updated dnsjava:dnsjava: {3.5.0} -> {3.5.1}
added io.grpc:grpc-census: {1.44.0}
added io.opencensus:opencensus-contrib-exemplar-util: {0.31.0}
added io.opencensus:opencensus-contrib-grpc-metrics: {0.31.0}
added io.opencensus:opencensus-contrib-resource-util: {0.31.0}
added io.opencensus:opencensus-exporter-metrics-util: {0.31.0}
added io.opencensus:opencensus-exporter-stats-stackdriver: {0.31.0}
added io.opencensus:opencensus-impl-core: {0.31.0}
added io.opencensus:opencensus-impl: {0.31.0}
updated org.apache.beam:beam-model-fn-execution: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-model-job-management: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-model-pipeline: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-runners-core-construction-java: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-runners-core-java: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-runners-google-cloud-dataflow-java: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-runners-java-fn-execution: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-sdks-java-core: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-sdks-java-expansion-service: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-sdks-java-extensions-arrow: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-sdks-java-extensions-protobuf: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-sdks-java-fn-execution: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-sdks-java-io-google-cloud-platform: {2.38.0} -> {2.39.0}
updated org.apache.beam:beam-sdks-java-io-kafka: {2.38.0} -> {2.39.0}
updated org.flywaydb:flyway-core: {6.0.1, 8.5.10} -> {6.0.1, 8.5.12}
updated org.hibernate:hibernate-core: {5.6.8.Final} -> {5.6.9.Final}
updated org.hibernate:hibernate-hikaricp: {5.6.8.Final} -> {5.6.9.Final}
updated org.jsoup:jsoup: {1.14.3} -> {1.15.1}
updated org.postgresql:postgresql: {42.3.4} -> {42.3.6}
updated org.springframework:spring-core: {4.3.18.RELEASE} -> {5.3.18}
updated org.springframework:spring-expression: {4.3.18.RELEASE} -> {5.3.18}
added org.springframework:spring-jcl: {5.3.18}
updated org.testcontainers:database-commons: {1.17.1} -> {1.17.2}
updated org.testcontainers:jdbc: {1.17.1} -> {1.17.2}
updated org.testcontainers:postgresql: {1.17.1} -> {1.17.2}
updated com.google.appengine:appengine-api-stubs: {2.0.4} -> {2.0.5}
updated com.google.cloud:google-cloud-nio: {0.123.28} -> {0.124.2}
updated org.apache.beam:beam-runners-direct-java: {2.38.0} -> {2.39.0}
updated org.apache.tomcat:tomcat-annotations-api: {10.1.0-M14} -> {10.1.0-M15}
updated org.junit-pioneer:junit-pioneer: {1.7.0} -> {1.7.1}
updated org.junit.jupiter:junit-jupiter-migrationsupport: {5.8.2} -> {5.9.0-M1}
updated org.mockito:mockito-junit-jupiter: {4.5.1} -> {4.6.1}
updated org.testcontainers:selenium: {1.17.1} -> {1.17.2}
updated com.google.cloud.sql:postgres-socket-factory: {1.5.0} -> {1.6.0}
```

**Review by mindhog — COMMENTED** [review]
LGTM, but it looks like the FOSS presubmits are failing because we can't get 2.2.6, either :-/  Please ignore my comment about `upgrade_dependency.sh`, my mistake based on a misread of the presubmit failure.  The internal tests passed so I'm assuming you've done that.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1654#-:-N3suHYwAxtkaVRc7fkd:b-6xaerp)* status: 0 of 135 files reviewed, all discussions resolved

**Review by mindhog — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1654#-:-N3sv1as5oqf3YIOH410:bnfp4nl)* status: 0 of 135 files reviewed, all discussions resolved

**Comment by gbrodman** [comment]
Ugh. Yeah I already updated the dependencies but no luck, it looks like.

**Pull request merged**
