### PR TITLE
Properly handle Joda Money in JPA

### PR DESCRIPTION
**Pull request by weiminyu**
Joda Money has BigDecimal as amount, which is mapped to a numeric(19,2)
column in the database. As a result, the Money amount load from DB has
scale 2. This becomes a problem with currencies such as JPY, which
requires scale to be 0. To properly load a currency, we must adjust the
scale post-load.

The current approach, which uses Hibernate component mapping,  puts the
burden of post-load cleanup on each entity type that uses Money. It is
easy to forget this, as we just discovered.

This PR uses a CompositeUserType to map Money. It adjusts the scale
properly when loading Money instances. Although CompositeUserType appear
to be deprecated in Hibernate 6, it is the only proper solution right
now for mapping non-owned classes.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1447)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
This is fixed, as shown on github page.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1447#-:-Mq0-MU_8LlDhjbEQwNp:blp1y51)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @mindhog)

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1447)* status: all files reviewed, 2 unresolved discussions (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/persistence/converter/JodaMoneyType.java, line 93 at r1](https://reviewable.io/reviews/google/nomulus/1447#-Mq0F8ZzE3nn_gP8U1Vw:-Mq0F8ZzE3nn_gP8U1Vx:b-e7thci) ([raw file](https://github.com/google/nomulus/blob/f444b65f3bb0cee6275c7816aab2b1fed29274d3/core/src/main/java/google/registry/persistence/converter/JodaMoneyType.java#L93)):*
> ```
> nail down some details with my team
> ```

Pasted into the wrong window?
___
*[core/src/test/java/google/registry/persistence/converter/JodaMoneyConverterTest.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/1447#-Mq0Hi8S3rr4OBnl6P2P:-Mq0Hi8T9IdiN-D8F1Zk:b-jxvk0r) ([raw file](https://github.com/google/nomulus/blob/f444b65f3bb0cee6275c7816aab2b1fed29274d3/core/src/test/java/google/registry/persistence/converter/JodaMoneyConverterTest.java#L55)):*
> ```Java
>   @Test
>   void roundTripConversion() {
>     Money money = Money.of(CurrencyUnit.USD, 100);
> ```

Do we have a test that verifies that we don't lose precision on USD? (e.g. $1.23?)  Can we add one if not? (or just modify this test)

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1447)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/persistence/converter/JodaMoneyType.java, line 93 at r1](https://reviewable.io/reviews/google/nomulus/1447#-Mq0F8ZzE3nn_gP8U1Vw:-Mq0L1cV7Im1I-1UXdMN:b-guczyo) ([raw file](https://github.com/google/nomulus/blob/f444b65f3bb0cee6275c7816aab2b1fed29274d3/core/src/main/java/google/registry/persistence/converter/JodaMoneyType.java#L93)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

> ```
> nail down some details with my team
> ```

Pasted into the wrong window?
</blockquote></details>

Yeah, happening a lot to me lately. Maybe time to replace the mouse.
___
*[core/src/test/java/google/registry/persistence/converter/JodaMoneyConverterTest.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/1447#-Mq0Hi8S3rr4OBnl6P2P:-Mq0LkUo-bHTwAtSXgTy:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f444b65f3bb0cee6275c7816aab2b1fed29274d3/core/src/test/java/google/registry/persistence/converter/JodaMoneyConverterTest.java#L55)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Do we have a test that verifies that we don't lose precision on USD? (e.g. $1.23?)  Can we add one if not? (or just modify this test)
</blockquote></details>

Done.

**Review by mindhog — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1447)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @weiminyu)

**Pull request merged**
