### PR TITLE
Create separate BSA service

### PR DESCRIPTION
**Pull request by ptkach**
Deployed to QA, disabled static IP on backend, enabled on bsa service. I think I've updated all the places, but please let me know if I missed anything, as we have a lot places where services are hardcoded.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2221)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2221)* status: 0 of 31 files reviewed, 3 unresolved discussions (waiting on @jianglai and @ptkach)

___
*[`build.gradle` line 350 at r2](https://reviewable.io/reviews/google/nomulus/2221#-NjIYItf47qUcyeLh2ZO:-NjIYItf47qUcyeLh2ZP:bikj93l) ([raw file](https://github.com/google/nomulus/blob/ff065541482efc960761387f7607d28bb44a8992/build.gradle#L350)):*
> ```Gradle
>   def services = [':services:default',
>                   ':services:backend',
>                   ':services:bsa',
> ```

Will we find more use to this service? If so a more general name would be better.



_Code quote:_
```Gradle
bsa
```
___
*[`core/src/main/java/google/registry/bsa/BsaAction.java` line 31 at r2](https://reviewable.io/reviews/google/nomulus/2221#-NjIYiP_6pdfxL316lmj:-NjIYiP_6pdfxL316lmk:b-27ovv) ([raw file](https://github.com/google/nomulus/blob/ff065541482efc960761387f7607d28bb44a8992/core/src/main/java/google/registry/bsa/BsaAction.java#L31)):*
> ```Java
>     method = Action.Method.GET,
>     auth = Auth.AUTH_API_ADMIN)
> public class BsaAction implements Runnable {
> ```

Please rename this class, maybe DummyAction or PlaceholderAction.
That'll make my life easier. Otherwise I'll have a chain of PRs to resolve.



_Code quote:_
```Java
BsaAction
```

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2221)* status: 2 of 31 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot], @ptkach, and @weiminyu)

___
*[`build.gradle` line 350 at r2](https://reviewable.io/reviews/google/nomulus/2221#-NjIYItf47qUcyeLh2ZO:-NjIs5GcEk2fUdG1X3wc:b-xs48dm) ([raw file](https://github.com/google/nomulus/blob/ff065541482efc960761387f7607d28bb44a8992/build.gradle#L350)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Will we find more use to this service? If so a more general name would be better.
</blockquote></details>

The idea is to have an isolated service that would have a new static egress IP so as to not interfere with existing services that also depends on egress IP whitelists, like ICANN reporting, MarksDB download, and such.

Ultimately we would want to update all these whitelists (they are too wide as is because GAE's egress IP pool is so big), so we can turn on static IP for all services without interruption. At that time this service can be removed.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2221)* status: 2 of 31 files reviewed, 3 unresolved discussions (waiting on @weiminyu)

___
*[`build.gradle` line 350 at r2](https://reviewable.io/reviews/google/nomulus/2221#-NjIYItf47qUcyeLh2ZO:-NjJ3Jj14sHK4vdADCW6:b-fmjr4p) ([raw file](https://github.com/google/nomulus/blob/ff065541482efc960761387f7607d28bb44a8992/build.gradle#L350)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The idea is to have an isolated service that would have a new static egress IP so as to not interfere with existing services that also depends on egress IP whitelists, like ICANN reporting, MarksDB download, and such.

Ultimately we would want to update all these whitelists (they are too wide as is because GAE's egress IP pool is so big), so we can turn on static IP for all services without interruption. At that time this service can be removed.
</blockquote></details>

Although that's a valid plan, I don't necessary agree that we should do that. There's no particular reason to try to limit our usage of separate services, especially for such use-cases, that don't necessary inline with nomulus as an open source registry service. We actually get more granularity in analytical and logging tools in GCP as we use separate services. It produces some boilerplate code, but by no means it makes our project noticeably larger.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2221)* status: 2 of 31 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/test/java/google/registry/module/bsa/BsaServletTest.java` line 26 at r1](https://reviewable.io/reviews/google/nomulus/2221#gh-1393212922:-NjJlv0K547ectz0V9QL:b6ujch) ([raw file](https://github.com/google/nomulus/blob/9adf4af7588f89dfb8edea20dfb5600de9cd6b0e/core/src/test/java/google/registry/module/bsa/BsaServletTest.java#L26)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: BsaServletTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1610)
</blockquote></details>

Not applicable
___
*[`core/src/main/java/google/registry/bsa/BsaAction.java` line 31 at r2](https://reviewable.io/reviews/google/nomulus/2221#-NjIYiP_6pdfxL316lmj:-NjJlwUr-r4XbgEznZrZ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ff065541482efc960761387f7607d28bb44a8992/core/src/main/java/google/registry/bsa/BsaAction.java#L31)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Please rename this class, maybe DummyAction or PlaceholderAction.
That'll make my life easier. Otherwise I'll have a chain of PRs to resolve.
</blockquote></details>

Done.

**Review by weiminyu — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2221#-:-NjJmGua5Urxjve2fRT7:bg7igkv)* status: 2 of 31 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot] and @jianglai)

**Review by weiminyu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2221#-:-NjJq8tJ0iVnCM_NZMAg:bnfp4nl)* status: 2 of 31 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot] and @jianglai)

**Pull request merged**
