### PR TITLE
Filter console registrars per user role

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2501)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2501)* status: all files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W-m3ACmhwVr_eKBlS:-O2W-m3B1Vel8a7eAgJg:b-utvbkj) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L90)):*
> ```Java
>       consoleApiParams.response().setPayload(gson.toJson(registrars));
>       consoleApiParams.response().setStatus(SC_OK);
>     } else if (user.getUserRoles().getRegistrarRoles().values().stream()
> ```

tbh VIEW_REGISTRAR_DETAILS is the most very basic of permissions on a registrar, anyone that has any permissions on a registrar has this permission. 

I don't know if it would be any cleaner, but another reasonable way of doing this would be simply to use the key set of `registrarRoles` as the query param `accessibleRegistrarIds`, maybe doing a final permission check afterward? 

Just thinking of ways to make this look neater 
___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W0ZP3-ry6ZGzE6u0Y:-O2W0ZP3-ry6ZGzE6u0Z:b275v7v) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L95)):*
> ```Java
>           user.getUserRoles().getRegistrarRoles().entrySet().stream()
>               .filter(e -> e.getValue().hasPermission(ConsolePermission.VIEW_REGISTRAR_DETAILS))
>               .map(e -> e.getKey())
> ```

Can just be Map.Entry::getKey
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 169 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W0tdf5RGg1eyWhxxs:-O2W0tdf5RGg1eyWhxxt:b169s1j) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L169)):*
> ```Java
>     String payload = ((FakeResponse) consoleApiParams.response()).getPayload();
>     assertThat(
>             ImmutableList.of("\"registrarId\":\"registrarId\"").stream()
> ```

do we need the stream and allMatch?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2501)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W-m3ACmhwVr_eKBlS:-O2WJ2zX6aLtNrbe-IPa:baw2zm4) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L90)):*
> tbh VIEW\_REGISTRAR\_DETAILS is the most very basic of permissions on a registrar, anyone that has any permissions on a registrar has this permission.

Not sure what do you mean by this. Are you trying to say that it's incorrect to check that permission and I should check a different one?
___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W0ZP3-ry6ZGzE6u0Y:-O2WJDuM-Itz0w_2_z0H:b-166ndf) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L95)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Can just be Map.Entry::getKey
</blockquote></details>

What's the benefit? This is a very basic line, easy to understand and `Map.Entry::getKey` is 2 chars longer, so I'm not sure

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2501)* status: all files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W-m3ACmhwVr_eKBlS:-O2WMjC58rlecM3-AIzd:ba73quf) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L90)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

> tbh VIEW\_REGISTRAR\_DETAILS is the most very basic of permissions on a registrar, anyone that has any permissions on a registrar has this permission.

Not sure what do you mean by this. Are you trying to say that it's incorrect to check that permission and I should check a different one?
</blockquote></details>

What you wrote is definitely not correct. I was just suggesting a simplification. 

Basically, right now you're asking "is there any registrar for which this user has the VIEW_REGISTRAR_DETAILS permission?" and I'm saying that because that permission is so basic, we could simplify this by asking "is there any registrar for which this user has any role?" 
___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W0ZP3-ry6ZGzE6u0Y:-O2WMcoI09WQwYtqPxJl:b4xsjqd) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L95)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

What's the benefit? This is a very basic line, easy to understand and `Map.Entry::getKey` is 2 chars longer, so I'm not sure
</blockquote></details>

generally the formatters suggest using the direct method reference when possible

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2501)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W-m3ACmhwVr_eKBlS:-O2_4BYqDJByL0vQPz4i:b8gf9i3) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L90)):*
> What you wrote is definitely not correct.

Why is definitely NOT correct?

> is there any registrar for which this user has any role?

I agree it'd make things simpler now, as like you said VIEW_REGISTRAR_DETAILS is the very basic permission, but it's not necessary will be the same in the future. I don't think the simplification worth maintainability risks. VIEW_REGISTRAR_DETAILS is the role design for this specific purpose, so why not use it?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2501)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 90 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W-m3ACmhwVr_eKBlS:-O2_IIbr1ltZGxggSH_A:b-wd552p) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L90)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

> What you wrote is definitely not correct.

Why is definitely NOT correct?

> is there any registrar for which this user has any role?

I agree it'd make things simpler now, as like you said VIEW_REGISTRAR_DETAILS is the very basic permission, but it's not necessary will be the same in the future. I don't think the simplification worth maintainability risks. VIEW_REGISTRAR_DETAILS is the role design for this specific purpose, so why not use it?
</blockquote></details>

ughhhh I meant "not INCORRECT" my bad it means the absolute opposite 

fair enough!

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2501)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W0ZP3-ry6ZGzE6u0Y:-O2_mjlkAWy7xP0d1vti:b-t37vfg) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L95)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

generally the formatters suggest using the direct method reference when possible
</blockquote></details>

I really don't see how this particular case gets any better or worse either way. My understanding is that it's a matter of how readable the code is, for instance when lambda gets too long or naming a method would shade more light on it's contents etc, but this case is perfectly readable either way and we have bunch of places with lambdas in our project, so that's not a strict convention either.
What I'm trying to say is that I wouldn't expect this to be a blocker for merging a PR 
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 169 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W0tdf5RGg1eyWhxxs:-O2_nlaH0CKP1yqbBOB9:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L169)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

do we need the stream and allMatch?
</blockquote></details>

Updated

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2501)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2501#-O2W0ZP3-ry6ZGzE6u0Y:-O2_vq-q3qrVsMfllGUN:b-p896i1) ([raw file](https://github.com/google/nomulus/blob/e87ebc4c3310f9ef16e1c9bfd32062704d4a7a38/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L95)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I really don't see how this particular case gets any better or worse either way. My understanding is that it's a matter of how readable the code is, for instance when lambda gets too long or naming a method would shade more light on it's contents etc, but this case is perfectly readable either way and we have bunch of places with lambdas in our project, so that's not a strict convention either.
What I'm trying to say is that I wouldn't expect this to be a blocker for merging a PR
</blockquote></details>

by itself no it definitely wouldn't be a blocker, but i figured i was commenting on other things so I might as well

**Pull request merged**
