### PR TITLE
Add indexes on contacts in the Domain table

### PR DESCRIPTION
**Pull request by jianglai**
These indexes are used to find if a contact is linked to a domain in
during a contact delete.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1145)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1145)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 371 at r1](https://reviewable.io/reviews/google/nomulus/1145#-M_R4RrX4ZhYyFIT9pux:-M_R4RrX4ZhYyFIT9puy:b-ucdbks) ([raw file](https://github.com/google/nomulus/blob/d8077038b74146c06bd48d7d67bca7f69cc0dd69/core/src/main/java/google/registry/model/EppResourceUtils.java#L371)):*
> ```Java
>    * @param limit the maximum number of returned keys
>    */
>   @SuppressWarnings("unchecked")
> ```

Can you fix this instead?  This is pretty broad `SuppressWarnings`.
___
*[core/src/main/java/google/registry/model/domain/DomainBase.java, line 58 at r1](https://reviewable.io/reviews/google/nomulus/1145#-M_R4jbHAlZBMu2Zi62h:-M_R4jbHAlZBMu2Zi62i:bioh6pz) ([raw file](https://github.com/google/nomulus/blob/d8077038b74146c06bd48d7d67bca7f69cc0dd69/core/src/main/java/google/registry/model/domain/DomainBase.java#L58)):*
> ```Java
>     indexes = {
>       @Index(columnList = "adminContact"),
>       @Index(columnList = "autorenewEndTime"),
> ```

I'm not disputing that this index isn't necessary (it is), but why isn't it in the Flyway script below?

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1145)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 371 at r1](https://reviewable.io/reviews/google/nomulus/1145#-M_R4RrX4ZhYyFIT9pux:-M_X6wkdDjFDMIn7Irg3:b-lghs3j) ([raw file](https://github.com/google/nomulus/blob/d8077038b74146c06bd48d7d67bca7f69cc0dd69/core/src/main/java/google/registry/model/EppResourceUtils.java#L371)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Apparently `Query.getResultStream()` returns a raw `Stream` (because the type of the query is not known at compile time) so this is not really fixable... See a similar discussion here: https://stackoverflow.com/questions/15913150/what-is-the-proper-way-to-cast-hibernate-query-list-to-listtype
</blockquote></details>

Can you suppress it just on the one line though instead of on the whole method?
___
*[core/src/main/java/google/registry/model/domain/DomainBase.java, line 58 at r1](https://reviewable.io/reviews/google/nomulus/1145#-M_R4jbHAlZBMu2Zi62h:-M_X78s6CEQK9OPNsqi4:b-yf4phl) ([raw file](https://github.com/google/nomulus/blob/d8077038b74146c06bd48d7d67bca7f69cc0dd69/core/src/main/java/google/registry/model/domain/DomainBase.java#L58)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It's moved, not new. I reordered the indexes alphabetically (unless this is going to cause problem)?
</blockquote></details>

Oh, I see.  I don't think it will cause a problem.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1145)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/model/EppResourceUtils.java, line 371 at r1](https://reviewable.io/reviews/google/nomulus/1145#-M_R4RrX4ZhYyFIT9pux:-M_YH89U4Uj5Gbi4MvJK:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d8077038b74146c06bd48d7d67bca7f69cc0dd69/core/src/main/java/google/registry/model/EppResourceUtils.java#L371)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Can you suppress it just on the one line though instead of on the whole method?
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1145#-:-M_aB6yv3o8ZmI0oKo97:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
