### PR TITLE
Add a console action to retrieve a paged list of domains

### PR DESCRIPTION
**Pull request by gbrodman**
In the future we'll want to add searching capability but for now we can go with straightforward pagination. 

Note: we will need to add a GSON VKey converter in the future to parse domains, but for now we're not using the domains anywhere

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2193)

### CODE REVIEW

**Review by ptkach — COMMENTED** [review]
That looks great, is it deployed somewhere? 

> Reviewed 2 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193#-:-Nhc9QRN5kNvRkMuiXtM:b-jxl4ue)* status: 2 of 7 files reviewed, all discussions resolved

**Review by gbrodman — COMMENTED** [review]
nah, I didn't deploy it anywhere because it doesn't have a front end component 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193#-:-NhcMeJt6WFbRu6N4C2O:b-jm56rn)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @ptkach)

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java` line 98 at r1](https://reviewable.io/reviews/google/nomulus/2193#-NhhQavO2wWUB_FuMUPP:-NhhQavO2wWUB_FuMUPQ:b-837oi1) ([raw file](https://github.com/google/nomulus/blob/1492964fab8b0c0e2e900dc8121ac5c5530e2005/core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java#L98)):*
> ```Java
>     // We have to use a constant created-before time in order to have stable pagination, since new
>     // domains can be constantly created
>     CreateAutoTimestamp createdBeforeTime;
> ```

To keep track, as discussed, we probably want to reset this if it comes older than an hour as someone might get stuck with older results if the same url reused

**Review by gbrodman — COMMENTED** [review]
Discussed offline: I shifted this to be a list of individual parameters because we cannot use the body of GET requests. 

Deploying to crash now 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193#-:-NhhQnIr9-11MkRObgNZ:bxe4dit)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
some sample curl commands on crash take about 2.5-3.5 seconds which is not great but not terrible 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193#-:-Nhlnl0o9hP8lqgIDBlJ:boflke6)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java` line 98 at r1](https://reviewable.io/reviews/google/nomulus/2193#-NhhQavO2wWUB_FuMUPP:-NhmM-QKErUP-OpUJspt:bg5cmfo) ([raw file](https://github.com/google/nomulus/blob/1492964fab8b0c0e2e900dc8121ac5c5530e2005/core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java#L98)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

To keep track, as discussed, we probably want to reset this if it comes older than an hour as someone might get stuck with older results if the same url reused
</blockquote></details>

i was thinking about this for a while and I think it makes more sense to handle that on the front end 

1. it's quicker to display to the user what's going on that way 
2. it means that the back end is giving back to the front end exactly what it requested every time 
3. in the case where we'd want to reset it, we don't have a great way of communicating to the front end what we're doing. Whereas if the front end does it, we can have a check there that says basically "if the time is old, reload the thing without a time" 
___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 214 at r2](https://reviewable.io/reviews/google/nomulus/2193#gh-1373731513:-Nhhrf_Y5AEkNM0rBZfx:b-nbuf10) ([raw file](https://github.com/google/nomulus/blob/d2abfde74edc4a589005ff4c818878de16d9e8ac/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L214)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Missing catch of NumberFormatException

Potential uncaught 'java.lang.NumberFormatException'.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1578)
</blockquote></details>

this exception shouldn't be relevant

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java` line 98 at r1](https://reviewable.io/reviews/google/nomulus/2193#-NhhQavO2wWUB_FuMUPP:-Ni0DBM6B4A2OnY5JW9H:bln0swv) ([raw file](https://github.com/google/nomulus/blob/1492964fab8b0c0e2e900dc8121ac5c5530e2005/core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java#L98)):*
I think we need to think it through a little more. 
I agree with you that handing it on front-end side makes more sense and will provide a better transparency to the user. However from user's perspective there's still inconsistency in this implementation:

> it means that the back end is giving back to the front end exactly what it requested every time

Not exactly, as after the first visit user gets the "limited" list of `createdBeforeNow` domains. User doesn't get to request this value, but gets to be responsible for resetting it, which in turn will provide a new `createdBeforeNow` for the user

Another point is that this implementation takes care of new domains created after user's request, but it doesn't take into account the domains deleted during user session. That enables a possibility with providing the user with N domains and P pages on the first load and then during navigation that can switch to N - D domains and potentially less pages.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java` line 98 at r1](https://reviewable.io/reviews/google/nomulus/2193#-NhhQavO2wWUB_FuMUPP:-Ni0NV2LC-AHnkdCY8MO:b-nkshv3) ([raw file](https://github.com/google/nomulus/blob/1492964fab8b0c0e2e900dc8121ac5c5530e2005/core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java#L98)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I think we need to think it through a little more. 
I agree with you that handing it on front-end side makes more sense and will provide a better transparency to the user. However from user's perspective there's still inconsistency in this implementation:

> it means that the back end is giving back to the front end exactly what it requested every time

Not exactly, as after the first visit user gets the "limited" list of `createdBeforeNow` domains. User doesn't get to request this value, but gets to be responsible for resetting it, which in turn will provide a new `createdBeforeNow` for the user

Another point is that this implementation takes care of new domains created after user's request, but it doesn't take into account the domains deleted during user session. That enables a possibility with providing the user with N domains and P pages on the first load and then during navigation that can switch to N - D domains and potentially less pages.
</blockquote></details>

yeah there can be inconsistency, but after thinking about it this is pretty straightforward I think because we can also use deletion time (created before or at creationTime, deletion after deletionTime, both of which default to the time at the first request) 

the front end can check whether or not the creationTime that it's about to request is reasonable and remove it if not -- my goal is to make the backend API do exactly what the front end requests, and it's the front end's responsibility to request non-silly things. Things get very complex quickly if the backend returns things that don't match what the frontend requested.

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java` line 98 at r1](https://reviewable.io/reviews/google/nomulus/2193#-NhhQavO2wWUB_FuMUPP:-Ni0blH6E35xmPkoRBJO:b-l4djva) ([raw file](https://github.com/google/nomulus/blob/1492964fab8b0c0e2e900dc8121ac5c5530e2005/core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java#L98)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah there can be inconsistency, but after thinking about it this is pretty straightforward I think because we can also use deletion time (created before or at creationTime, deletion after deletionTime, both of which default to the time at the first request) 

the front end can check whether or not the creationTime that it's about to request is reasonable and remove it if not -- my goal is to make the backend API do exactly what the front end requests, and it's the front end's responsibility to request non-silly things. Things get very complex quickly if the backend returns things that don't match what the frontend requested.
</blockquote></details>

As discussed offline, please rename the variable to be something like 'snapshotTime' and update the query to account for the deleted after that said time. The rest should be taken care by front-end

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java` line 98 at r1](https://reviewable.io/reviews/google/nomulus/2193#-NhhQavO2wWUB_FuMUPP:-Ni1-z31AG3xdm4Geki_:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1492964fab8b0c0e2e900dc8121ac5c5530e2005/core/src/main/java/google/registry/ui/server/console/ConsoleDomainListAction.java#L98)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

As discussed offline, please rename the variable to be something like 'snapshotTime' and update the query to account for the deleted after that said time. The rest should be taken care by front-end
</blockquote></details>

Done.

**Review by ptkach — APPROVED** [review]
> Reviewed 2 of 7 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 194 at r3](https://reviewable.io/reviews/google/nomulus/2193#-Ni15zPP7t5JJDZBUL57:-Ni15zPP7t5JJDZBUL58:b-k5ia1e) ([raw file](https://github.com/google/nomulus/blob/bb95a939d2059435cebcc305e8b3100573519be7/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L194)):*
> ```Java
> 
>   @Provides
>   @Parameter("checkpointTime")
> ```

Not major, but since this is global to a request namespace in order to avoid collision in the future, we might want to have have it named after a request, like `domains-checkointTime` unless it's in fact expected to be used across different screens. Thoughts?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2193)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 194 at r3](https://reviewable.io/reviews/google/nomulus/2193#-Ni15zPP7t5JJDZBUL57:-Ni1AUGKB1qQIVhLyj4M:bh6gq84) ([raw file](https://github.com/google/nomulus/blob/bb95a939d2059435cebcc305e8b3100573519be7/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L194)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Not major, but since this is global to a request namespace in order to avoid collision in the future, we might want to have have it named after a request, like `domains-checkointTime` unless it's in fact expected to be used across different screens. Thoughts?
</blockquote></details>

I don't think that particularly matters. This way we can reuse the injection if we, for some reason, want to have a checkpoint time somewhere else. Even if the usage is entirely different, the "inject an optional DateTime object" can be the same.

**Pull request merged**
