### PR TITLE
Correctly restore composite VKeys in DomainContent 

### PR DESCRIPTION
**Pull request by mindhog**
The PollEvent and BillingEvent VKeys in DomainContent weren't getting restored as symmetric keys, they were missing their ofy components.  Restore these keys from material in the DomainContent record, introducing history entry identifiers for each of the key fields.

This depends on #821.  It also includes a hacky work-around for the auto-generated identifier in PollMessage, which should be properly replaced prior to the merge of this PR (with the hacky work-around removed).

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/825)

### CODE REVIEW

**Review by hstonec — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/825)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 261 at r1](https://reviewable.io/reviews/google/nomulus/825#-MIdivRG2mikMh9HP5E0:-MIdivRG2mikMh9HP5E1:b94csdk) ([raw file](https://github.com/google/nomulus/blob/6122983fc168e18274c9ffcaeb9c1685cf7916ae/core/src/main/java/google/registry/model/domain/DomainContent.java#L261)):*
> ```
> @Column(name = "autorenew_poll_message_history_id")
>   @Ignore
>   Long autorenewPollMessageHistoryId;
> ```
nit: we may not need `@Column` here as the name of the field should be converted to the same column name as you annotated.
___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 380 at r1](https://reviewable.io/reviews/google/nomulus/825#-MIdoj0s8KsshGR_xxxV:-MIdoj0s8KsshGR_xxxW:bwzh392) ([raw file](https://github.com/google/nomulus/blob/6122983fc168e18274c9ffcaeb9c1685cf7916ae/core/src/main/java/google/registry/model/domain/DomainContent.java#L380)):*
> ```
> public 
> ```
Does package level access work here? `DomainContent`, `DomainBase` and `DomainHistory` are all in the same package right?
___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 911 at r2](https://reviewable.io/reviews/google/nomulus/825#-MIsynGV46dNz6wCnyLk:-MIsynGV46dNz6wCnyLl:bg88h1t) ([raw file](https://github.com/google/nomulus/blob/92ddc7e52ec1dbc91a266cb061aa241f22cc9161/core/src/main/java/google/registry/model/domain/DomainContent.java#L911)):*
> ```
> getInstance().deletePollMessageHistoryId =
>           deletePollMessage != null ? deletePollMessage.getOfyKey().getParent().getId() : null;
> ```

Did you remember which type of entity having legacy key(Registry 1.0 key) in Datastore? The legacy key 's parent has different structure. Maybe we should check if any of the VKey accessed here have valid `parent` key in production.

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/825)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @hstonec)

___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 261 at r1](https://reviewable.io/reviews/google/nomulus/825#-MIdivRG2mikMh9HP5E0:-MIt0wdD1oinV5weGvFE:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6122983fc168e18274c9ffcaeb9c1685cf7916ae/core/src/main/java/google/registry/model/domain/DomainContent.java#L261)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> @Column(name = "autorenew_poll_message_history_id")
>   @Ignore
>   Long autorenewPollMessageHistoryId;
> ```
nit: we may not need `@Column` here as the name of the field should be converted to the same column name as you annotated.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 380 at r1](https://reviewable.io/reviews/google/nomulus/825#-MIdoj0s8KsshGR_xxxV:-MIt1f9MBGlwe6WC6cmT:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6122983fc168e18274c9ffcaeb9c1685cf7916ae/core/src/main/java/google/registry/model/domain/DomainContent.java#L380)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> public 
> ```
Does package level access work here? `DomainContent`, `DomainBase` and `DomainHistory` are all in the same package right?
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 911 at r2](https://reviewable.io/reviews/google/nomulus/825#-MIsynGV46dNz6wCnyLk:-MItNFrqDxkVC4tAhU0S:b397tsl) ([raw file](https://github.com/google/nomulus/blob/92ddc7e52ec1dbc91a266cb061aa241f22cc9161/core/src/main/java/google/registry/model/domain/DomainContent.java#L911)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
> getInstance().deletePollMessageHistoryId =
>           deletePollMessage != null ? deletePollMessage.getOfyKey().getParent().getId() : null;
> ```

Did you remember which type of entity having legacy key(Registry 1.0 key) in Datastore? The legacy key 's parent has different structure. Maybe we should check if any of the VKey accessed here have valid `parent` key in production.
</blockquote></details>

Thanks! For some reason I was thinking we had fixed those.

Fortunately, the legacy keys are fairly easy to deal with, added code to do that.

**Review by hstonec — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/825)* status: 1 of 10 files reviewed, all discussions resolved (waiting on @gbrodman and @hstonec)

**Review by hstonec — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/825)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java, line 463 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzDdGy9HW4JsQ8kCgd:-MIzDdGy9HW4JsQ8kCge:bqs8c3g) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java#L463)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> historyEntry = historyEntry.asBuilder().setDomainContent(domain).build();
>               jpaTm().insert(historyEntry);
>               jpaTm().insert(autorenewPollMessage);
>               jpaTm().insert(billEvent);
>               jpaTm().insert(deletePollMessage);
>               jpaTm().insert(domain);
> ```
</details>

The change looks good, I am just worried we may run into more similar issues when we start using `tm().insertAll()` in the application code(or unit test), which will probably make us defer more foreign key checks.

**Comment by mindhog** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/825)_ status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman, @hstonec, and @mindhog)
> 
> _[core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java, line 463 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzDdGy9HW4JsQ8kCgd:-MIzDdGy9HW4JsQ8kCge:bqs8c3g) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/test/java/google/registry/model/domain/DomainBaseSqlTest.java#L463)):_
> 
> Quoted 6 lines of code…
> The change looks good, I am just worried we may run into more similar issues when we start using `tm().insertAll()` in the application code(or unit test), which will probably make us defer more foreign key checks.

Yes.  Composing an e-mail on that very subject.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/825)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @hstonec, and @mindhog)

___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 218 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzFhrC2ME5IIMhJKvt:-MIzFhrC2ME5IIMhJKvu:b-jqfx12) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/main/java/google/registry/model/domain/DomainContent.java#L218)):*
> ```Java
>    * History record for the delete poll message.
>    *
>    * <p>Here so we can restore the original ofy key from sql.
> ```

Worth bundling these into a single (embedded object)? I'm worried about decoupling that could potentially occur with two separate variables. 
___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 374 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzIVYcBsK3J66Y0TpI:-MIzIVYcBsK3J66Y0TpJ:b3rrrje) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/main/java/google/registry/model/domain/DomainContent.java#L374)):*
> ```Java
>    * </ul>
>    */
>   void restoreOfyKeys(String repoId) {
> ```

do we ever need to pass in the repo ID? it should always be the same right? 
___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 174 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzI2_DB0BZk9jfnT6g:-MIzI2_DB0BZk9jfnT6h:b-baidmo) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/main/java/google/registry/model/domain/DomainHistory.java#L174)):*
> ```Java
>         domainContent = null;
>       } else {
>         domainContent.restoreOfyKeys(domainRepoId);
> ```

Why not just put this in the @PostLoad method of the DomainContent?

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/825)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @hstonec)

___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 218 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzFhrC2ME5IIMhJKvt:-MIzKQ8L9HHPIlmfsFPK:b-vcqt7y) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/main/java/google/registry/model/domain/DomainContent.java#L218)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Worth bundling these into a single (embedded object)? I'm worried about decoupling that could potentially occur with two separate variables. 
</blockquote></details>

Meh.  It's short-term code and fairly well contained, though it would be nice to not have to repeat the pattern three times.  I'll play with that approach for the next one of these that I do.
___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 374 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzIVYcBsK3J66Y0TpI:-MIzKlwm5J1Tl-jiVGzZ:b-98v78m) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/main/java/google/registry/model/domain/DomainContent.java#L374)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

do we ever need to pass in the repo ID? it should always be the same right? 
</blockquote></details>

Yes, because of when it's restored from the history record.  Unless I'm missing something?  It looked you had moved the concrete repo id out into DomainBase.
___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 174 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzI2_DB0BZk9jfnT6g:-MIzMuh99d2IcKLgdh1z:btxup6i) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/main/java/google/registry/model/domain/DomainHistory.java#L174)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Why not just put this in the @PostLoad method of the DomainContent? 
</blockquote></details>

Because we need the domainRepoId from this object.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/825)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 374 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzIVYcBsK3J66Y0TpI:-MIzXBkn-NSbuLcNZnpX:b-bzhv2n) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/main/java/google/registry/model/domain/DomainContent.java#L374)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Yes, because of when it's restored from the history record.  Unless I'm missing something?  It looked you had moved the concrete repo id out into DomainBase.
</blockquote></details>

right, annoying that we have that limitation 

i'm starting to think this history migration may, overall, just not be worth it 
___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 174 at r3](https://reviewable.io/reviews/google/nomulus/825#-MIzI2_DB0BZk9jfnT6g:-MIzXTxGCmOCkgobty4-:b-usvdyl) ([raw file](https://github.com/google/nomulus/blob/7d8d5ed98870f194e54e33e817b0e6e64065bf87/core/src/main/java/google/registry/model/domain/DomainHistory.java#L174)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Because we need the domainRepoId from this object.
</blockquote></details>

ugh right

**Review by gbrodman — APPROVED** [review]
:lgtm:

Discussed offline, my concerns can be alleviated by a refactoring of the repo ID which I will do after this PR 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/825#-:-MJ2m6Zs-N89AwjCKvCE:bjgaqls)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @hstonec)

**Pull request merged**
