### PR TITLE
Upgrade to Gradle 7.0

### PR DESCRIPTION
**Pull request by mindhog**
Upgrade gradle version and convert `buildSrc/build.gradle` to Kotlin.   Fix all observed breakage.

Performed the following tests:

- verified all lockfiles (`gradle.lockfile` and `buildscript-gradle.lockfile`) are
  recreated when we do --write-locks
- verified pluginsUrl is used to load buildSrc plugins (specifying a bad value 
  causes buildSrc to fail when loading its plugins)
- `./nom_build :nom:generate_golden_file`
- integration tests:
  ```
  integration/run_compatibility_tests.sh -s sql -p domain-registry-dev
  integration/run_compatibility_tests.sh -s nomulus -p domain-registry-dev
  ```
- deploy to alpha
- schema publishing.  (`:db:publish`)

This change affects the lockfiles, so we also do a dependency update.  Dependency diffs are as follows:
 
```
Package version change report:
change package-name: {old versions} -> {new versions}
=====================================================

updated com.google.api-client:google-api-client: {1.35.2, 1.35.0, 1.35.1} -> {1.35.2, 1.35.1}
updated com.google.api:gax: {2.18.2, 2.18.1} -> {2.18.2, 2.18.3}
updated com.google.apis:google-api-services-storage: {v1-rev20220608-1.32.1} -> {v1-rev20220705-1.32.1}
updated com.google.auth:google-auth-library-credentials: {1.8.0, 1.7.0} -> {1.8.0, 1.8.1, 1.7.0}
updated com.google.auth:google-auth-library-oauth2-http: {1.8.0, 1.7.0} -> {1.8.0, 1.8.1, 1.7.0}
updated com.google.cloud:google-cloud-storage: {2.9.0, 2.9.2} -> {2.10.0}
updated com.google.guava:guava: {31.1-jre, 30.1-jre, 31.0.1-jre, 29.0-jre, 19.0, 20.0, 27.0.1-jre, 28.2-jre} -> {31.1-jre, 30.1-jre, 31.0.1-jre, 29.0-jre, 20.0, 27.0.1-jre, 28.2-jre}
updated com.google.http-client:google-http-client-apache-v2: {1.42.0, 1.41.8} -> {1.42.0}
updated com.google.http-client:google-http-client-gson: {1.42.0, 1.41.8} -> {1.42.0, 1.42.1}
updated com.google.http-client:google-http-client: {1.42.0, 1.41.8} -> {1.42.0, 1.42.1}
updated com.google.oauth-client:google-oauth-client: {1.34.0, 1.34.1} -> {1.34.1}
updated io.opencensus:opencensus-api: {0.31.1, 0.31.0} -> {0.31.1}
updated io.opencensus:opencensus-contrib-http-util: {0.31.1, 0.31.0} -> {0.31.1}
added : {empty}
updated net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin: {0.6.1} -> {2.0.2}
updated net.ltgt.gradle:gradle-errorprone-plugin: {0.6.1} -> {2.0.2}
updated org.slf4j:slf4j-api: {1.7.2, 1.7.36, 2.0.0-alpha7} -> {1.7.2, 2.0.0-alpha7, 1.7.30, 1.7.36}
updated com.google.api.grpc:proto-google-cloud-tasks-v2: {2.3.0} -> {2.3.1}
updated com.google.api.grpc:proto-google-cloud-tasks-v2beta2: {0.93.0} -> {0.93.1}
updated com.google.api.grpc:proto-google-cloud-tasks-v2beta3: {0.93.0} -> {0.93.1}
updated com.google.cloud:google-cloud-tasks: {2.3.0} -> {2.3.1}
updated com.google.dagger:dagger-compiler: {2.42} -> {2.43}
updated com.google.dagger:dagger-producers: {2.42} -> {2.43}
updated com.google.dagger:dagger-spi: {2.42} -> {2.43}
updated com.google.dagger:dagger: {2.42} -> {2.43}
updated com.google.devtools.ksp:symbol-processing-api: {1.5.30-1.0.0} -> {1.7.0-1.0.6}
updated com.google.re2j:re2j: {1.7} -> {1.7, 1.1}
updated io.github.java-diff-utils:java-diff-utils: {4.11} -> {4.12}
updated io.netty:netty-tcnative-boringssl-static: {2.0.53.Final, 2.0.46.Final} -> {2.0.54.Final, 2.0.46.Final}
updated io.netty:netty-tcnative-classes: {2.0.53.Final, 2.0.46.Final} -> {2.0.54.Final, 2.0.46.Final}
updated org.jetbrains.kotlin:kotlin-stdlib-common: {1.6.10, 1.3.50} -> {1.3.50, 1.7.0}
updated org.jetbrains.kotlin:kotlin-stdlib-jdk7: {1.5.32, 1.3.50} -> {1.3.50, 1.7.0}
updated org.jetbrains.kotlin:kotlin-stdlib-jdk8: {1.5.32, 1.3.50} -> {1.3.50, 1.7.0}
updated org.jetbrains.kotlin:kotlin-stdlib: {1.6.10, 1.3.50} -> {1.3.50, 1.7.0}
updated com.google.apis:google-api-services-cloudkms: {v1-rev20220617-1.32.1} -> {v1-rev20220701-1.32.1}
updated com.google.apis:google-api-services-monitoring: {v3-rev20220626-1.32.1} -> {v3-rev20220715-1.32.1}
updated com.google.apis:google-api-services-sqladmin: {v1beta4-rev20220513-1.32.1} -> {v1beta4-rev20220623-1.32.1}
updated com.google.cloud.sql:jdbc-socket-factory-core: {1.6.1} -> {1.6.2}
updated com.google.cloud.sql:postgres-socket-factory: {1.6.1} -> {1.6.2}
updated com.google.cloud:google-cloud-nio: {0.124.7} -> {0.124.10}
updated com.sun.istack:istack-commons-runtime: {3.0.7} -> {4.1.1, 3.0.7}
updated org.apache.tomcat:tomcat-annotations-api: {10.1.0-M16} -> {10.1.0-M17}
added org.eclipse.angus:angus-activation: {1.0.0}
updated org.flywaydb:flyway-core: {8.5.13, 6.0.1} -> {6.0.1, 9.0.1}
added org.glassfish.jaxb:jaxb-core: {4.0.0}
updated org.glassfish.jaxb:jaxb-runtime: {2.3.1} -> {2.3.1, 4.0.0}
updated org.glassfish.jaxb:txw2: {2.3.1} -> {2.3.1, 4.0.0}
```

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1712)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
Now that we have gradle.lock, do we still need the per-config lockfiles?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1712#-:-N7qcx3bAXt_kCmjOImU:bhs3mr7)* status: 0 of 339 files reviewed, all discussions resolved

**Review by mindhog — COMMENTED** [review]
Those should all be removed.  However, note that we still have _per-project_ lockfiles.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1712#-:-N7qe7J8C5Sc5eO9oWFI:bpqrle9)* status: 0 of 339 files reviewed, all discussions resolved

**Review by weiminyu — CHANGES_REQUESTED** [review]
> Reviewed 9 of 339 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1712)* status: 9 of 339 files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)

___
*[`build.gradle` line 329 at r1](https://reviewable.io/reviews/google/nomulus/1712#-N7qegyQ82AlCKIhPxid:-N7qegyR3WgCuXnKbiMO:b-dr5zvj) ([raw file](https://github.com/google/nomulus/blob/0ff5d15270a09d6e090b629f5afcf4aead0458ff/build.gradle#L329)):*
> ```Gradle
>       configurations.each {
>         if (it.name != 'dependencyLicenseReport' && it.name != 'integration') {
>           it.resolutionStrategy.activateDependencyLocking()
> ```

Is this still necessary after adding lockAllConfiguration above?



_Code quote:_
```Gradle
it.resolutionStrategy.activateDependencyLocking()
```

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1712)* status: 9 of 339 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`build.gradle` line 329 at r1](https://reviewable.io/reviews/google/nomulus/1712#-N7qegyQ82AlCKIhPxid:-N7uSIItBgBT3UhDi282:b-ifn75c) ([raw file](https://github.com/google/nomulus/blob/0ff5d15270a09d6e090b629f5afcf4aead0458ff/build.gradle#L329)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Is this still necessary after adding lockAllConfiguration above?
</blockquote></details>

Unfortunately, yes (after removing it lockfiles were not generated for subprojects).

It looks like lockAllConfiguration does not affect subprojects, as I had initially believed.  We can still use the more granular dependency locking strategy here, though, which seems to still be what we want.

**Review by weiminyu — APPROVED** [review]
Ah, didn't realize they were deleted.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1712#-:-N7r2k4A0x9kslhB1kPP:baqzyh6)* status: 9 of 339 files reviewed, all discussions resolved (waiting on @weiminyu)

**Pull request merged**
