### PR TITLE
Update renew flow to accept and process REMOVEPACKAGE token

### PR DESCRIPTION
**Pull request by ptkach**
Removes domain from package and update renewal price when __REMOVEPACKAGE__ token sent with domain renewal command

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1768)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
First line of the commit message should fit within the space :) 

If you want to include more detail (usually a good call), better to put it on lines below

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1768#-:-NAudzod57Aabysm5amI:bxd0ahd)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @gbrodman and @ptkach)

___
*[`core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java` line 185 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv5AHw7YexhT7NxL8E:-NAv5AHw7YexhT7NxL8F:b8lclal) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java#L185)):*
> ```Java
>     verifyRenewAllowed(authInfo, existingDomain, command, allocationToken);
> 
>     // If static token is applicable this should update the domain
> ```

"should" is a bit awkward here -- it does or it doesn't. Also, it's less `if [a] static token is applicable` and more `if the client passed in a static token`, right? 
___
*[`core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java` line 261 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv62AC4P4Cdb08XZO7:-NAv62AC4P4Cdb08XZO8:b-n4kdax) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java#L261)):*
> ```Java
>         newDomain, domainHistory, explicitRenewEvent, newAutorenewEvent, newAutorenewPollMessage);
>     if (allocationToken.isPresent()
>         && AllocationToken.TokenBehavior.DEFAULT.equals(allocationToken.get().getTokenBehavior())
> ```

I don't think this line is necessary since we already have the `SINGLE_USE` check below (REMOVEPACKAGE, and really all possible static tokens, are UNLIMITED_USE) 
___
*[`core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java` line 356 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv21zw7p3AUbb6mTvC:-NAv21zw7p3AUbb6mTvD:b8os11n) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java#L356)):*
> ```Java
>             allocationToken
>                 .filter(t -> AllocationToken.TokenBehavior.DEFAULT.equals(t.getTokenBehavior()))
>                 .map(AllocationToken::createVKey)
> ```

this isn't super related to this PR, but perhaps we should have `AllocationToken::createVKey` throw an exception if the token is one of the types of tokens that isn't stored in the database. 
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 225 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAuqOh2B1OuaqpNvJrL:-NAuqOh2B1OuaqpNvJrM:b-yg04f3) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L225)):*
> ```Java
>   }
> 
>   public static Domain applyToken(Domain domain, Optional<AllocationToken> allocationToken) {
> ```

probably want to rename this to something more specific. Tokens can be used in a ton of different ways, so `applyToken` isn't descriptive enough I think
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 226 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv4Pm78Hi87qAZI2fX:-NAv4Pm78Hi87qAZI2fY:b-aqjewe) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L226)):*
> ```Java
> 
>   public static Domain applyToken(Domain domain, Optional<AllocationToken> allocationToken) {
>     if (allocationToken.isPresent()
> ```

kinda nitty, but we can do the same short-circuiting that we discussed earlier 

```
if (!allocationToken.isPresent()) {
  return domain;
}
```
to avoid nesting
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 229 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv4gue1PvNwMHhswyD:-NAv4gue1PvNwMHhswyE:b-w5g89y) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L229)):*
> ```Java
>         && TokenBehavior.REMOVE_PACKAGE.equals(allocationToken.get().getTokenBehavior())) {
>       // Reset renewal price behavior to Default and null out renewal price, to force next charge be
>       // solely on Domain/TLD...
> ```

the grammar here is a bit wonky, can you clarify please? Also the ellipses are unnecessary



_Suggestion:_
```Java
      // to force next charge be
      // solely on Domain/TLD...
```
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 240 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAuk95OEd42wYzcEg3H:-NAuk95OEd42wYzcEg3I:bwloyoi) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L240)):*
> ```Java
>       // logic that relies on fetching the event from the store to succeed
>       tm().transact(
>               () -> {
> ```

nit, don't need braces
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 243 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAujw4u6UKCk-RxVMKY:-NAujw4u6UKCk-RxVMKZ:b-pfgb83) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L243)):*
> ```Java
>                 tm().put(newRecurringBillingEvent);
>               });
>       jpaTm().getEntityManager().flush();
> ```

What happens without these lines? Generally, SQL reflects changes and additions immediately. 
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 320 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv3Hkk9bMvpTMFkcJX:-NAv3Hkk9bMvpTMFkcJY:bk5yfkd) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L320)):*
> ```Java
>   }
> 
>   /** The __REMOVEPACKAGE__ token requires at least a year period of renewal */
> ```

Given that this is part of the renew flow, we already check that the number of years is greater than 0, right? 

Also, either way, we should probably have a test for that case. with the __REMOVEPACKAGE__ token 
___
*[`core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java` line 1263 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv6SBZErn9rEn2ZtXl:-NAv6SB_3uytwjgOz_K-:b-dihdqt) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L1263)):*
> ```Java
>         assertThrows(RemovePackageTokenOnNonPackageDomainException.class, this::runFlow);
>     assertAboutEppExceptions().that(thrown).marshalsToXml();
>   }
> ```

what happens if we use the REMOVEPACKAGE token on a domain that doesn't have a package associated with it? I'm not sure we handle that, and regardless we'll want a test for that. 
___
*[`core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java` line 1294 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv2m1q-wpywzwkNdcV:-NAv2m1q-wpywzwkNdcW:b-1mg0bh) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L1294)):*
> ```Java
>     // doSuccessfulTest
>     Domain domain = reloadResourceByForeignKey();
>     assertThat(domain.getCurrentPackageToken().isPresent()).isFalse();
> ```

can do Truth8.assertThat(domain.getCurrentPackageToken()).isEmpty();

**Review by ptkach — COMMENTED** [review]
Updated

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1768#-:-NAyw-c02Qu8BO7O4D5Y:b-bu91xm)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java` line 185 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv5AHw7YexhT7NxL8E:-NAyw27N51CQp2vQkrmf:b-n4d156) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java#L185)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

"should" is a bit awkward here -- it does or it doesn't. Also, it's less `if [a] static token is applicable` and more `if the client passed in a static token`, right? 
</blockquote></details>

Makes sense, however the point of "applicable" was to make it clear that even if token is passed it doesn't necessary make any updates to a domain. Updated accordingly. 
___
*[`core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java` line 261 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv62AC4P4Cdb08XZO7:-NAywOSz0eZl6Wizl7y4:b-bw8e14) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java#L261)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think this line is necessary since we already have the `SINGLE_USE` check below (REMOVEPACKAGE, and really all possible static tokens, are UNLIMITED_USE) 
</blockquote></details>

Updated.
___
*[`core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java` line 356 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv21zw7p3AUbb6mTvC:-NAywWgJEjvt1K0vs--E:b-bw8e14) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java#L356)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this isn't super related to this PR, but perhaps we should have `AllocationToken::createVKey` throw an exception if the token is one of the types of tokens that isn't stored in the database. 
</blockquote></details>

Updated.
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 225 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAuqOh2B1OuaqpNvJrL:-NAywZQf9ckGyA3TA0sb:b-bw8e14) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L225)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

probably want to rename this to something more specific. Tokens can be used in a ton of different ways, so `applyToken` isn't descriptive enough I think
</blockquote></details>

Updated.
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 226 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv4Pm78Hi87qAZI2fX:-NAywa620HAEV7H9UMz5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L226)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

kinda nitty, but we can do the same short-circuiting that we discussed earlier 

```
if (!allocationToken.isPresent()) {
  return domain;
}
```
to avoid nesting
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 229 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv4gue1PvNwMHhswyD:-NAywao06pWYcv6VK7B1:b-xlt3rw) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L229)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

the grammar here is a bit wonky, can you clarify please? Also the ellipses are unnecessary
</blockquote></details>

Removed this part, code is self-explanatory enough here, I believe 
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 240 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAuk95OEd42wYzcEg3H:-NAywvOz3lXpM7eQHche:bb6un1j) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L240)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit, don't need braces
</blockquote></details>

Done
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 243 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAujw4u6UKCk-RxVMKY:-NAywx3k1plO9hLD-fB8:byjqov2) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L243)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What happens without these lines? Generally, SQL reflects changes and additions immediately. 
</blockquote></details>

Between SQL and this code there's entity manager that while being in transaction (it's in transaction at this moment to be clear) saves updates to the cache (I believe it's done to optimize read and writes) . Without these lines I was getting the following error https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java;drc=74e22089fe0c893364a8eb6a247ea8481c4fb827;l=673 caused by the code in run loading BillingEvent (from cache as it's in transaction state still)
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 320 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv3Hkk9bMvpTMFkcJX:-NAyyqYD2jMDnTGdMNKR:blc95ra) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L320)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Given that this is part of the renew flow, we already check that the number of years is greater than 0, right? 

Also, either way, we should probably have a test for that case. with the __REMOVEPACKAGE__ token 
</blockquote></details>

Just double checked and you are correct - line above covers only non null and format, however turns "> 0" is covered during unmarshalling step, so I've missed that. Added a test case anyway, which I believe can be redundant as it's not a new functionality. 
___
*[`core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java` line 1263 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv6SBZErn9rEn2ZtXl:-NAyzidW2LYFecJZRV3r:b-uyupvz) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L1263)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what happens if we use the REMOVEPACKAGE token on a domain that doesn't have a package associated with it? I'm not sure we handle that, and regardless we'll want a test for that. 
</blockquote></details>

This test covers that specifically (no package token on domain but REMOVEPACKAGE token in command)- https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java;drc=f623da9948de55492f313783debbdd5d2a5b15ac;l=1253 
___
*[`core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java` line 1294 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv2m1q-wpywzwkNdcV:-NAz-SSZ7QdnI7uO6V8M:b-896fix) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L1294)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can do Truth8.assertThat(domain.getCurrentPackageToken()).isEmpty();
</blockquote></details>

Done.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1768)* status: all files reviewed, 4 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java` line 356 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv21zw7p3AUbb6mTvC:-NAzFx4D8w0J5ZjFjG17:b-bnshm5) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java#L356)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

i think it's definitely better to do what we were doing before with checking for DEFAULT tokens rather than handling an exception (this isn't python, haha) 
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 243 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAujw4u6UKCk-RxVMKY:-NAzNpIF907kE50msX8V:b-5nwquy) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L243)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Between SQL and this code there's entity manager that while being in transaction (it's in transaction at this moment to be clear) saves updates to the cache (I believe it's done to optimize read and writes) . Without these lines I was getting the following error https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java;drc=74e22089fe0c893364a8eb6a247ea8481c4fb827;l=673 caused by the code in run loading BillingEvent (from cache as it's in transaction state still)
</blockquote></details>

ah yeah, the old "saving and reloading the same object is disallowed" thing. 

this is kind of an unfortunate side effect of only storing the `VKey<Recurring>` rather than the `Recurring` itself on the domain item, I suppose. Let's put a comment here explaining this, something along the lines of "the Recurring billing event is reloaded later in the renew flow" 
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 237 at r2](https://reviewable.io/reviews/google/nomulus/1768#-NAzOn5hAjKIhwrKtKUs:-NAzOn5hAjKIhwrKtKUt:b2wbv04) ([raw file](https://github.com/google/nomulus/blob/ef0f05a9927da6f22a2191c65add82721c08408c/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L237)):*
> ```Java
>     // Synchronize changed RecurringBillingEvent with storage,
>     // prevents entities conflicts while in the transaction
>     tm().transact(() -> tm().put(newRecurringBillingEvent));
> ```

 actually, it's unnecessary to have a transaction here -- we're already in one, but if we weren't, the `loadByKey` just above would fail anyway 
___
*[`core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java` line 1307 at r2](https://reviewable.io/reviews/google/nomulus/1768#-NAzJrQE0_enRc5MlCGZ:-NAzJrQE0_enRc5MlCG_:bxvcalc) ([raw file](https://github.com/google/nomulus/blob/ef0f05a9927da6f22a2191c65add82721c08408c/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L1307)):*
> ```Java
>         ImmutableMap.of("DOMAIN", "example.tld", "YEARS", "0", "TOKEN", "__REMOVEPACKAGE__"));
> 
>     assertThrows(GenericXmlSyntaxErrorException.class, this::runFlow);
> ```

is this exception the one thrown? I'd expect IllegalArgumentException, not a syntax error

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1768)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java` line 356 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAv21zw7p3AUbb6mTvC:-NAzgREK3Zg42ki6toMS:b-ed9acc) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/DomainRenewFlow.java#L356)):*
> the Recurring billing event is reloaded later in the renew flow
Agree, updated
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 243 at r1](https://reviewable.io/reviews/google/nomulus/1768#-NAujw4u6UKCk-RxVMKY:-NAzgYYr1MK4FTgaquAu:b-896fix) ([raw file](https://github.com/google/nomulus/blob/43f41ad1cac9bb6a9415758c652b8bdb25a16611/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L243)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ah yeah, the old "saving and reloading the same object is disallowed" thing. 

this is kind of an unfortunate side effect of only storing the `VKey<Recurring>` rather than the `Recurring` itself on the domain item, I suppose. Let's put a comment here explaining this, something along the lines of "the Recurring billing event is reloaded later in the renew flow" 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 237 at r2](https://reviewable.io/reviews/google/nomulus/1768#-NAzOn5hAjKIhwrKtKUs:-NAzgXzB0lOZ_wn-JAiz:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ef0f05a9927da6f22a2191c65add82721c08408c/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L237)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

 actually, it's unnecessary to have a transaction here -- we're already in one, but if we weren't, the `loadByKey` just above would fail anyway 
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java` line 1307 at r2](https://reviewable.io/reviews/google/nomulus/1768#-NAzJrQE0_enRc5MlCGZ:-NAzgZBk5ot8pPntXGiH:b862f36) ([raw file](https://github.com/google/nomulus/blob/ef0f05a9927da6f22a2191c65add82721c08408c/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L1307)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

is this exception the one thrown? I'd expect IllegalArgumentException, not a syntax error 
</blockquote></details>

yeah, I'd expect so too, but thats what it throws

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1768)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java` line 1307 at r2](https://reviewable.io/reviews/google/nomulus/1768#-NAzJrQE0_enRc5MlCGZ:-NAzjINUDBBFrm1zNSlw:b-rf7p6a) ([raw file](https://github.com/google/nomulus/blob/ef0f05a9927da6f22a2191c65add82721c08408c/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L1307)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

yeah, I'd expect so too, but thats what it throws 
</blockquote></details>

oh, it's XML-parsing-verified, we can probably just remove this test then

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1768)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 207 at r4](https://reviewable.io/reviews/google/nomulus/1768#-NAzl99y7JdpCbhgJCZQ:-NAzl99y7JdpCbhgJCZR:b-2ybyvy) ([raw file](https://github.com/google/nomulus/blob/761ac031404c42b0481958432f8f86050ee20725/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L207)):*
> ```Java
> 
>   public static void verifyTokenAllowedOnDomain(
>       Domain domain, Renew command, Optional<AllocationToken> allocationToken) throws EppException {
> ```

unused var
___
*[`core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java` line 221 at r4](https://reviewable.io/reviews/google/nomulus/1768#-NAzlCS877X5yV1pAexZ:-NAzlCS877X5yV1pAex_:b-gevvxm) ([raw file](https://github.com/google/nomulus/blob/761ac031404c42b0481958432f8f86050ee20725/core/src/main/java/google/registry/flows/domain/token/AllocationTokenFlowUtils.java#L221)):*
> ```Java
>   }
> 
>   public static Domain adjustDomainBasedOnAllocationToken(
> ```

while we're changing methods, i think we may still want to be more specific here, `maybeApplyPackageRemovalToken`?

**Review by gbrodman — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1768)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
