### PR TITLE
Delete DatastoreTM and most other references to Datastore

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1681)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 227 of 339 files at r1, 1 of 2 files at r2, 15 of 24 files at r3, 15 of 22 files at r4, 21 of 25 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1681)* status: 259 of 340 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[`core/src/test/java/google/registry/testing/AppEngineExtension.java` line 414 at r5](https://reviewable.io/reviews/google/nomulus/1681#-N5q2F3g83czyf-_-Ea1:-N5q2F3g83czyf-_-Ea2:bytuou3) ([raw file](https://github.com/google/nomulus/blob/61725821b9244a69f99a8c60b61e8f13268b1126/core/src/test/java/google/registry/testing/AppEngineExtension.java#L414)):*
> ```Java
>             .setNoIndexAutoGen(false));
>     // This forces App Engine to write the generated indexes to a usable location.
>     System.setProperty("appengine.generated.dir", tmpDir.getAbsolutePath());
> ```

Hmm, don't we want to remove this entirely?
___
*[`core/src/test/java/google/registry/testing/AppEngineExtension.java` line 455 at r5](https://reviewable.io/reviews/google/nomulus/1681#-N5q2ZycAiL12Xw55bNa:-N5q2ZycAiL12Xw55bNb:bvlrzm5) ([raw file](https://github.com/google/nomulus/blob/61725821b9244a69f99a8c60b61e8f13268b1126/core/src/test/java/google/registry/testing/AppEngineExtension.java#L455)):*
> ```Java
>     // Reset id allocation in ObjectifyService so that ids are deterministic in tests.
>     IdService.resetSelfAllocatedId();
>     this.ofyTestEntities.forEach(AppEngineExtension::register);
> ```

... and this too?

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 65 of 339 files at r1, 6 of 24 files at r3, 6 of 22 files at r4, 4 of 25 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1681)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[`core/src/test/java/google/registry/testing/AppEngineExtension.java` line 455 at r5](https://reviewable.io/reviews/google/nomulus/1681#-N5q2ZycAiL12Xw55bNa:-N5q6SEaBStNL9fVs3E2:b-nv2w5m) ([raw file](https://github.com/google/nomulus/blob/61725821b9244a69f99a8c60b61e8f13268b1126/core/src/test/java/google/registry/testing/AppEngineExtension.java#L455)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This we definitely need to keep, for ID generation 
</blockquote></details>

But we were only previously doing it when "withDatastore" was true.  Wouldn't it never be true now?

**Review by mindhog — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1681)* status: 339 of 340 files reviewed, all discussions resolved (waiting on @mindhog)

**Comment by gbrodman** [comment]
this push only fixed merge conflicts in ExpandRecurringBillingEventsAction*

**Pull request merged**
