### PR TITLE
Use custom whois message for bsa-blocked domain

### PR DESCRIPTION
**Pull request by weiminyu**
If a domain does not exist and is blocked by BSA, return BSA's custom message in whois response.
If a domain exists and would be blocked by BSA if deregistered, do not mention BSA at all.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2241)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2241)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 76 at r2](https://reviewable.io/reviews/google/nomulus/2241#-NldC3rbDujUpxtq1Z5v:-NldC3rbDujUpxtq1Z5w:bdnrwdi) ([raw file](https://github.com/google/nomulus/blob/31e33e17a6499237b95c86ccd9fa16ccd0d658a0/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L76)):*
> ```Java
> 
>   private boolean isBlockedByBsa(InternetDomainName domainName, String tld, DateTime now) {
>     return tm().transact(
> ```

Move this transaction out to `executeQuery()` inside the `if` statement for when the TLD is in-bailiwick, as `getResponse()` also creates a transaction to interact with the DB (inside the load by foreign key methods).  We don't want to run two separate round-trips to the DB here, one to see if the domain exists and then one to see if the label exists in the BSA table.
___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 81 at r2](https://reviewable.io/reviews/google/nomulus/2241#-NldCbCv1w6sc4OAmbd1:-NldCbCv1w6sc4OAmbd2:bzbzknt) ([raw file](https://github.com/google/nomulus/blob/31e33e17a6499237b95c86ccd9fa16ccd0d658a0/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L81)):*
> ```Java
>                 verifyNotBlockedByBsa(domainName.parts().get(0), Tld.get(tld), now);
>                 return false;
>               } catch (DomainLabelBlockedByBsaException e) {
> ```

Using exceptions for normal code flow like this is an antipattern and not generally recommended (it's also way more expensive to handle an exception with its stack trace than just a boolean).  Would be better to refactor most of the logic inside `verifyNotBlockedByBsa()` into a check method that returns a boolean, and then use that here, and then also use it inside of the newly refactored `verifyNotBlockedByBsa()` method and have that do the exception only on the create flow.

Remember, we get millions of WHOIS queries in a short amount of time every Monday night so we do want these to be as performant as possible.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2241)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 67 at r1](https://reviewable.io/reviews/google/nomulus/2241#gh-1412567097:-NldJzEB2Wi9sNM4WzY3:b-8yl62q) ([raw file](https://github.com/google/nomulus/blob/6125e242dfd27eda7fd2cda55d01f888d3b98776/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L67)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unread local variable

Variable 'Tld tldEntity' is never read.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1625)
</blockquote></details>

Outdated comment.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2241)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 76 at r2](https://reviewable.io/reviews/google/nomulus/2241#-NldC3rbDujUpxtq1Z5v:-Nly9zoH8SV7fO8qGhTf:b-896fix) ([raw file](https://github.com/google/nomulus/blob/31e33e17a6499237b95c86ccd9fa16ccd0d658a0/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L76)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Move this transaction out to `executeQuery()` inside the `if` statement for when the TLD is in-bailiwick, as `getResponse()` also creates a transaction to interact with the DB (inside the load by foreign key methods).  We don't want to run two separate round-trips to the DB here, one to see if the domain exists and then one to see if the label exists in the BSA table.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 81 at r2](https://reviewable.io/reviews/google/nomulus/2241#-NldCbCv1w6sc4OAmbd1:-NlyA-_EDfInVoDtj9y8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/31e33e17a6499237b95c86ccd9fa16ccd0d658a0/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L81)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Using exceptions for normal code flow like this is an antipattern and not generally recommended (it's also way more expensive to handle an exception with its stack trace than just a boolean).  Would be better to refactor most of the logic inside `verifyNotBlockedByBsa()` into a check method that returns a boolean, and then use that here, and then also use it inside of the newly refactored `verifyNotBlockedByBsa()` method and have that do the exception only on the create flow.

Remember, we get millions of WHOIS queries in a short amount of time every Monday night so we do want these to be as performant as possible.
</blockquote></details>

Done.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2241)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 63 at r4](https://reviewable.io/reviews/google/nomulus/2241#-NlywEyb6phVeKkG0dwc:-NlywEyb6phVeKkG0dwd:b-o58pg4) ([raw file](https://github.com/google/nomulus/blob/1edee04588cc8de0b841c4babbddc20d08b45a68/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L63)):*
> ```Java
>     // Google Registry Policy: Do not return records under TLDs for which we're not authoritative.
>     if (tld.isPresent() && getTlds().contains(tld.get().toString())) {
>       final Optional<WhoisResponse> response = getResponse(domainName, now);
> ```

This needs to be inside the transaction as well.  This is what's loading the resource from the DB.

The code should look like:

```
if (tld.isPresent() && getTlds().contains(tld.get().toString())) {
  tm().transact(() -> {
    final Optional<WhoisResponse> response = getResponse(domainName, now);
    // ...
    if (isBlockedByBsa(label, Tld.get(tldStr), now)) {
      // Throw exception.
    }
    // ...
  });
}
```
___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 70 at r4](https://reviewable.io/reviews/google/nomulus/2241#-NlywYKk-HGPh_xBpi5e:-NlywYKl1KfUFyh-11EO:b-aubthu) ([raw file](https://github.com/google/nomulus/blob/1edee04588cc8de0b841c4babbddc20d08b45a68/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L70)):*
> ```Java
>       String label = domainName.parts().get(0);
>       String tldStr = tld.get().toString();
>       if (tm().transact(() -> isBlockedByBsa(label, Tld.get(tldStr), now))) {
> ```

This should not be a separate transaction.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2241)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 63 at r4](https://reviewable.io/reviews/google/nomulus/2241#-NlywEyb6phVeKkG0dwc:-Nm23_88-qa2LYpuJWow:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1edee04588cc8de0b841c4babbddc20d08b45a68/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L63)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This needs to be inside the transaction as well.  This is what's loading the resource from the DB.

The code should look like:

```
if (tld.isPresent() && getTlds().contains(tld.get().toString())) {
  tm().transact(() -> {
    final Optional<WhoisResponse> response = getResponse(domainName, now);
    // ...
    if (isBlockedByBsa(label, Tld.get(tldStr), now)) {
      // Throw exception.
    }
    // ...
  });
}
```
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 70 at r4](https://reviewable.io/reviews/google/nomulus/2241#-NlywYKk-HGPh_xBpi5e:-Nm1rnEx7hBgp8uJ5JAC:b-rm3o1) ([raw file](https://github.com/google/nomulus/blob/1edee04588cc8de0b841c4babbddc20d08b45a68/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L70)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should not be a separate transaction.
</blockquote></details>

Yeah, I realized on my way out I didn't address the original problem.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2241)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 63 at r4](https://reviewable.io/reviews/google/nomulus/2241#-NlywEyb6phVeKkG0dwc:-Nm2Vj2A7Oq6Ntn28jd3:b-6j97iz) ([raw file](https://github.com/google/nomulus/blob/1edee04588cc8de0b841c4babbddc20d08b45a68/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L63)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The transaction should be inside the `if` statement as per my code suggestion.

The reason is that the `if (tld.isPresent() && getTlds().contains(tld.get().toString())) {` check itself does not usually need to hit the DB (only one time out of many when the TLDs cache is stale).  So when we get a domain lookup for an out-of-bailiwick domain, or just something that isn't formatted as a domain at all, the TLD won't exist in our system and it doesn't need to hit the DB at all (except in the rare case that the TLDs cache needs to be refreshed).  So, better to only start the transaction once we know with good likelihood that we're going to need to hit the DB (to attempt to load the domain).

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2241)* status: 0 of 26 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/whois/DomainLookupCommand.java` line 63 at r4](https://reviewable.io/reviews/google/nomulus/2241#-NlywEyb6phVeKkG0dwc:-NnAME7s7EAHzpQidf32:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1edee04588cc8de0b841c4babbddc20d08b45a68/core/src/main/java/google/registry/whois/DomainLookupCommand.java#L63)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The transaction should be inside the `if` statement as per my code suggestion.

The reason is that the `if (tld.isPresent() && getTlds().contains(tld.get().toString())) {` check itself does not usually need to hit the DB (only one time out of many when the TLDs cache is stale).  So when we get a domain lookup for an out-of-bailiwick domain, or just something that isn't formatted as a domain at all, the TLD won't exist in our system and it doesn't need to hit the DB at all (except in the rare case that the TLDs cache needs to be refreshed).  So, better to only start the transaction once we know with good likelihood that we're going to need to hit the DB (to attempt to load the domain).
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2241#-:-NnAchT35uWnj-OqiBSk:bnfp4nl)* status: 0 of 26 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])

**Pull request merged**
