### PR TITLE
Remove InjectExtension

### PR DESCRIPTION
**Pull request by jianglai**
It is only used to set the clock used by Ofy, and it admits itself being
an ugly hack...

Also applied IntelliJ suggestions on touched files.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1739)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 46 of 47 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1739)* status: all files reviewed, 1 unresolved discussion

___
*[`core/src/test/java/google/registry/flows/EppTestCase.java` line 151 at r2](https://reviewable.io/reviews/google/nomulus/1739#-N9EfEtB7PMajHIVePZ6:-N9EfEtB7PMajHIVePZ7:b-jlpkxd) ([raw file](https://github.com/google/nomulus/blob/e4132db8ed5795ec3a230c6eb3287b1566e41c33/core/src/test/java/google/registry/flows/EppTestCase.java#L151)):*
> ```Java
>   }
> 
>   private String assertLoginCommandAndResponse(
> ```

Note that I moved a few methods inside the CommandAsserter class per IntelliJ's suggestions because they are only  used inside that class.



_Code quote:_
```Java
assertLoginCommandAndResponse
```

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 46 of 47 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1739)* status: all files reviewed, 5 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 134 at r3](https://reviewable.io/reviews/google/nomulus/1739#-N9HKr0OBIZzcmBMPAa5:-N9HKr0OBIZzcmBMPAa6:bvj0kwg) ([raw file](https://github.com/google/nomulus/blob/4ea7b237b51b1409bb1d458477cb91f76e514256/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L134)):*
> ```Java
>     // Currently we do not do anything with this allocation token, but just want it loaded and
>     // available in this flow in case we use it in the future.
>     @SuppressWarnings("unused")
> ```

we can just remove the variable assignment instead of adding the annotation i think 
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java` line 174 at r4](https://reviewable.io/reviews/google/nomulus/1739#-N9Hsish6LiyEt3317rt:-N9Hsish6LiyEt3317ru:bvj0kwg) ([raw file](https://github.com/google/nomulus/blob/311d2a5739ce6b09676fd454b12f7a5a3631cc05/core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java#L174)):*
> ```Java
>     // Currently we do not do anything with this allocation token, but just want it loaded and
>     // available in this flow in case we use it in the future.
>     @SuppressWarnings("unused")
> ```

we can just remove the variable assignment instead of adding the annotation i think 



_Code quote:_
```Java
    // available in this flow in case we use it in the future.
    @SuppressWarnings("unused")
```
___
*[`core/src/main/java/google/registry/model/console/User.java` line 32 at r3](https://reviewable.io/reviews/google/nomulus/1739#-N9HL2f0CgYIo2Aprtc6:-N9HL2f0CgYIo2Aprtc7:b6y0vua) ([raw file](https://github.com/google/nomulus/blob/4ea7b237b51b1409bb1d458477cb91f76e514256/core/src/main/java/google/registry/model/console/User.java#L32)):*
> ```Java
> 
>   /** Autogenerated unique ID of this user. */
>   @SuppressWarnings("unused")
> ```

let's remove this, I've added a `getId` method in another PR 
___
*[`core/src/test/java/google/registry/export/SyncGroupMembersActionTest.java` line 184 at r4](https://reviewable.io/reviews/google/nomulus/1739#-N9Hrtfa5SWMar7FsjZM:-N9Hrtfb5hkrQThN0aFl:bnj7d2n) ([raw file](https://github.com/google/nomulus/blob/311d2a5739ce6b09676fd454b12f7a5a3631cc05/core/src/test/java/google/registry/export/SyncGroupMembersActionTest.java#L184)):*
> ```Java
>         Role.MEMBER);
>     verify(response).setStatus(SC_OK);
>     assertThat(
> ```

This new code seems more verbose / less clear to me, why was it added?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1739)* status: 44 of 47 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @jianglai, and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 134 at r3](https://reviewable.io/reviews/google/nomulus/1739#-N9HKr0OBIZzcmBMPAa5:-N9I5dp60YYfabDVXnGm:bac4pnj) ([raw file](https://github.com/google/nomulus/blob/4ea7b237b51b1409bb1d458477cb91f76e514256/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L134)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we can just remove the variable assignment instead of adding the annotation i think 
</blockquote></details>

See the comment below.
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java` line 174 at r4](https://reviewable.io/reviews/google/nomulus/1739#-N9Hsish6LiyEt3317rt:-N9I5SAR-Q17T86w-ER3:bar3m) ([raw file](https://github.com/google/nomulus/blob/311d2a5739ce6b09676fd454b12f7a5a3631cc05/core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java#L174)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we can just remove the variable assignment instead of adding the annotation i think 
</blockquote></details>

Based on the comment we do want to leave it available for future use. I don't specifically understand why it was necessary, though. @sarahcaseybot, is there a reason to load this if it's not used currently?
___
*[`core/src/main/java/google/registry/model/console/User.java` line 32 at r3](https://reviewable.io/reviews/google/nomulus/1739#-N9HL2f0CgYIo2Aprtc6:-N9I5kbY5v3MkqVeC-o2:b-lco7iv) ([raw file](https://github.com/google/nomulus/blob/4ea7b237b51b1409bb1d458477cb91f76e514256/core/src/main/java/google/registry/model/console/User.java#L32)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

let's remove this, I've added a `getId` method in another PR 
</blockquote></details>

OK, but that PR needs to go in first, otherwise I get a presubmit test failure due to unused fields.
___
*[`core/src/test/java/google/registry/export/SyncGroupMembersActionTest.java` line 184 at r4](https://reviewable.io/reviews/google/nomulus/1739#-N9Hrtfa5SWMar7FsjZM:-N9I6-jP9prfo_pfvFKV:b-go92w5) ([raw file](https://github.com/google/nomulus/blob/311d2a5739ce6b09676fd454b12f7a5a3631cc05/core/src/test/java/google/registry/export/SyncGroupMembersActionTest.java#L184)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This new code seems more verbose / less clear to me, why was it added? 
</blockquote></details>

I believe IntelliJ prefers using Java native stream functions instead of using the ones from Guava. I do agree that the Guava version is much more succinct, though.

Reverted.

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1739)* status: 46 of 47 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1739)* status: all files reviewed, 3 unresolved discussions (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 134 at r3](https://reviewable.io/reviews/google/nomulus/1739#-N9HKr0OBIZzcmBMPAa5:-N9I8ZJsAbgfxtwHyyFI:b-tgjd6u) ([raw file](https://github.com/google/nomulus/blob/4ea7b237b51b1409bb1d458477cb91f76e514256/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L134)):*
> I'm pretty confident we need to keep the call to `allocationTokenFlowUtils.verifyAllocationTokenIfPresent` (same with the approve flow) but we just don't need to store the result. 
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java` line 174 at r4](https://reviewable.io/reviews/google/nomulus/1739#-N9Hsish6LiyEt3317rt:-N9I8LSG6Zhsei1CB4KS:bbxmbse) ([raw file](https://github.com/google/nomulus/blob/311d2a5739ce6b09676fd454b12f7a5a3631cc05/core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java#L174)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Based on the comment we do want to leave it available for future use. I don't specifically understand why it was necessary, though. @sarahcaseybot, is there a reason to load this if it's not used currently?
</blockquote></details>

I'm pretty confident we need to keep the call to `allocationTokenFlowUtils.verifyAllocationTokenIfPresent` (same with the approve flow) but we just don't need to store the result. 
___
*[`core/src/main/java/google/registry/model/console/User.java` line 32 at r3](https://reviewable.io/reviews/google/nomulus/1739#-N9HL2f0CgYIo2Aprtc6:-N9I80qKBjJqaDFOrkif:b-q3axd3) ([raw file](https://github.com/google/nomulus/blob/4ea7b237b51b1409bb1d458477cb91f76e514256/core/src/main/java/google/registry/model/console/User.java#L32)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

OK, but that PR needs to go in first, otherwise I get a presubmit test failure due to unused fields.
</blockquote></details>

It's weird that the presubmits would only start failing now, but anyway it has already been merged https://github.com/google/nomulus/blob/master/core/src/main/java/google/registry/model/console/User.java#L52 

same with the override on the build method

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1739)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @sarahcaseybot)

___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java` line 134 at r3](https://reviewable.io/reviews/google/nomulus/1739#-N9HKr0OBIZzcmBMPAa5:-N9IEsNp7tCiDrAhrb5n:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4ea7b237b51b1409bb1d458477cb91f76e514256/core/src/main/java/google/registry/flows/domain/DomainTransferApproveFlow.java#L134)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

> I'm pretty confident we need to keep the call to `allocationTokenFlowUtils.verifyAllocationTokenIfPresent` (same with the approve flow) but we just don't need to store the result. 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java` line 174 at r4](https://reviewable.io/reviews/google/nomulus/1739#-N9Hsish6LiyEt3317rt:-N9IErfm7AO58Z6Mey_t:b-896fix) ([raw file](https://github.com/google/nomulus/blob/311d2a5739ce6b09676fd454b12f7a5a3631cc05/core/src/main/java/google/registry/flows/domain/DomainTransferRequestFlow.java#L174)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I'm pretty confident we need to keep the call to `allocationTokenFlowUtils.verifyAllocationTokenIfPresent` (same with the approve flow) but we just don't need to store the result. 
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/model/console/User.java` line 32 at r3](https://reviewable.io/reviews/google/nomulus/1739#-N9HL2f0CgYIo2Aprtc6:-N9IDgG521m0mLaK5sAj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4ea7b237b51b1409bb1d458477cb91f76e514256/core/src/main/java/google/registry/model/console/User.java#L32)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It's weird that the presubmits would only start failing now, but anyway it has already been merged https://github.com/google/nomulus/blob/master/core/src/main/java/google/registry/model/console/User.java#L52 

same with the override on the build method 
</blockquote></details>

Done.

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1739)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1739)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)

**Pull request merged**
