### PR TITLE
Remove GAE Users service API usage

### PR DESCRIPTION
**Pull request by jianglai**
This is the last remaining GAE API that we depend on. By removing it, we are able to remove all common GAE dependencies as well.

To merge this PR, we need to create console `User` objects that have the same email address as the `RegistrarPoc` objects' `login_email_address` and copy over the existing registry lock hashes and salts.

We are also able to simply the code base by removing some redundant logic like `AuthMethod` (API is now the only supported one) and `UserAuthInfo` (console user is now the only supported one)

There are several behavioral changes that are worth noting:

1. The `XsrfTokenManager` now uses the console user's email address to mint and verify the token. Previously, only email addresses returned by the GAE Users service are used, whereas a blank email address will be used if the user is logged in as a console user. I believe this was an oversight that is now corrected.
2. The legacy console will return 401 when no user is logged in, instead of redirecting to the Users service login flow.
3. The logout URL in the legacy console is changed to use the IAP logout flow. It will clear the cookie and redirect the users to IAP login page (tested on QA).
4. The screenshot changes are mostly due to the console users lacking a display name and therefore showing the email address instead. Some changes are due to using the console user's email address as the registry lock email address, which is being fixed in #2413 and its follow-up RPs.
 

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2414)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 201 of 201 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param)

___
*[`core/src/main/java/google/registry/request/auth/AuthResult.java` line 30 at r1](https://reviewable.io/reviews/google/nomulus/2414#gh-1579483283:-NwKVjWv7wwwLwET_Mr8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/32b8f231e1ca425ac465aa7e955f4fe3db9df6dc/core/src/main/java/google/registry/request/auth/AuthResult.java#L30)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "authLevel" does not match any actual type parameter of type "AuthResult".

[Show more details](https://github.com/google/nomulus/security/code-scanning/7613)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/request/auth/AuthResult.java` line 31 at r1](https://reviewable.io/reviews/google/nomulus/2414#gh-1579483285:-NwKVjmlAMqxT7Maan2o:b-896fix) ([raw file](https://github.com/google/nomulus/blob/32b8f231e1ca425ac465aa7e955f4fe3db9df6dc/core/src/main/java/google/registry/request/auth/AuthResult.java#L31)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "user" does not match any actual type parameter of type "AuthResult".

[Show more details](https://github.com/google/nomulus/security/code-scanning/7614)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/request/auth/AuthResult.java` line 32 at r1](https://reviewable.io/reviews/google/nomulus/2414#gh-1579483289:-NwKVk1eCGBBiryXirt8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/32b8f231e1ca425ac465aa7e955f4fe3db9df6dc/core/src/main/java/google/registry/request/auth/AuthResult.java#L32)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "serviceAccountEmail" does not match any actual type parameter of type "AuthResult".

[Show more details](https://github.com/google/nomulus/security/code-scanning/7615)
</blockquote></details>

Done.

**Review by jianglai — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman, @param, and @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman, @param, and @ptkach)

**Comment by jianglai** [comment]
Gentle ping. I think we should start reviewing this PR as it is pretty extensive, even though it cannot be submitted due to other dependencies still in flux.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 170 of 201 files at r1, 11 of 13 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 17 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 14 unresolved discussions (waiting on @jianglai, @param, and @ptkach)

___
*[`core/src/main/java/google/registry/request/auth/AuthResult.java` line 59 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv5z_cBpV6it1Jqg7h:-Nwv5z_cBpV6it1Jqg7i:bunh7q1) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/request/auth/AuthResult.java#L59)):*
> ```Java
> 
>   private static AuthResult create(
>       AuthLevel authLevel, @Nullable User user, @Nullable String email) {
> ```

can we rename this to serviceAccountEmail or something to make it clear that this should *not* be the user's email? 
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java` line 56 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv71f42hZ79GlBbWmF:-Nwv71f42hZ79GlBbWmG:b-f3xi59) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java#L56)):*
> ```Java
>     path = ConsoleOteSetupAction.PATH,
>     method = {Method.POST, Method.GET},
>     auth = Auth.AUTH_PUBLIC)
> ```

I think we want this to be PUBLIC_LOGGIED_IN
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java` line 66 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv74GO76YmNoNlbrG7:-Nwv74GO76YmNoNlbrG8:b-f3xi59) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java#L66)):*
> ```Java
>     path = ConsoleRegistrarCreatorAction.PATH,
>     method = {Method.POST, Method.GET},
>     auth = Auth.AUTH_PUBLIC)
> ```

I think we want this to be PUBLIC_LOGGIED_IN
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleUiAction.java` line 43 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv75gu3mWD-qzyoO_D:-Nwv75gu3mWD-qzyoO_E:b-f3xi59) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/ConsoleUiAction.java#L43)):*
> ```Java
> 
> /** Action that serves Registrar Console single HTML page (SPA). */
> @Action(service = Action.Service.DEFAULT, path = ConsoleUiAction.PATH, auth = Auth.AUTH_PUBLIC)
> ```

I think we want this to be PUBLIC_LOGGIED_IN
___
*[`core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java` line 79 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7BO3D7R4PkJbQff6:-Nwv7BO3D7R4PkJbQff7:b-czdu19) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java#L79)):*
> ```Java
>     data.put("productName", productName);
>     data.put("username", user.getEmailAddress());
>     data.put("logoutUrl", "/registrar?gcp-iap-mode=CLEAR_LOGIN_COOKIE");
> ```

sadly this does not work as well as you might expect, but it's probably still better than nothing 
___
*[`core/src/test/java/google/registry/request/auth/AuthenticatedRegistrarAccessorTest.java` line 84 at r5](https://reviewable.io/reviews/google/nomulus/2414#-NwvAHzx0zFQWaKO_XPG:-NwvAHzx0zFQWaKO_XPH:bm07fgo) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/request/auth/AuthenticatedRegistrarAccessorTest.java#L84)):*
> ```Java
>   private static final String REGISTRAR_ID_WITH_ACCESS = "TheRegistrar";
> 
>   /** Registrar ID of a REAL registrar with the {@link USER} has no access to. */
> ```

nit: "which", not "with"
___
*[`core/src/test/java/google/registry/request/auth/RequestAuthenticatorTest.java` line 51 at r5](https://reviewable.io/reviews/google/nomulus/2414#-NwvAUjQ3LFFxlFtdKsU:-NwvAUjQ3LFFxlFtdKsV:b8z5pcw) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/request/auth/RequestAuthenticatorTest.java#L51)):*
> ```Java
>               .setEmailAddress("user@registry.example")
>               .setUserRoles(
>                   new UserRoles.Builder().setIsAdmin(false).setGlobalRole(GlobalRole.NONE).build())
> ```

fwiw "false" is the default for admin, no need to set it 
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleEppPasswordActionTest.java` line 199 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7pgd8yHsWBY-30VQ:-Nwv7pgd8yHsWBY-30VR:bfx5sp7) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/ui/server/console/ConsoleEppPasswordActionTest.java#L199)):*
> ```Java
>         AuthenticatedRegistrarAccessor.createForTesting(
>             ImmutableSetMultimap.of("registrarId", OWNER));
>     Cookie cookie =
> ```

I think we can remove this cookie-setting code, since the fake params class does it for us? (This comment may apply multiple places in the PR) 
___
*[`core/src/test/java/google/registry/ui/server/registrar/ConsoleUiActionTest.java` line 157 at r5](https://reviewable.io/reviews/google/nomulus/2414#-NwvAyOW3EBTazvr5OrO:-NwvAyOW3EBTazvr5OrP:b-b9esd) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/ui/server/registrar/ConsoleUiActionTest.java#L157)):*
> ```Java
> 
>   @Test
>   void testNoUser_redirect() {
> ```

nit, but it's no longer a "redirect" 
___
*[`core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java` line 402 at r5](https://reviewable.io/reviews/google/nomulus/2414#-NwvBEIXEm6IiGngB-Cz:-NwvBEIXEm6IiGngB-D-:bcwvmwb) ([raw file](https://github.com/google/nomulus/blob/03b358726a0dfc336f7262e6e132d9c0cdcca870/core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java#L402)):*
> ```Java
>     clock.setTo(previousLock.getLockRequestTime().plusHours(2));
>     Map<String, ?> response = action.handleJsonRequest(lockRequest());
>     assertSuccess(response, "lock", "Marla.Singer.RegistryLock@crr.com");
> ```

we'll need to change this, but you already noted that in the commit description 
___
*[`core/src/test/java/google/registry/webdriver/RegistrarCreateConsoleScreenshotTest.java` line 42 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv8BCc8AF9sDZibE5W:-Nwv8BCc8AF9sDZibE5X:bx5uq2d) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/webdriver/RegistrarCreateConsoleScreenshotTest.java#L42)):*
> ```Java
> 
>   @BeforeEach
>   void beforeEach() {
> ```

can we just put this in WebDriverTestCase so we don't need to repeat it? 
___
*[`core/src/test/java/google/registry/testing/ConsoleApiParamsUtil.java` line 27 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7W3R2Pbx4HCb-w5V:-Nwv7W3R2Pbx4HCb-w5W:b-6bti5v) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/testing/ConsoleApiParamsUtil.java#L27)):*
> ```Java
> import org.joda.time.DateTime;
> 
> public final class ConsoleApiParamsUtil {
> ```

By convention, I think we'd want this to be ConsoleApiParamsUtil*s. But why do we need to change this at all?

**Review by jianglai — COMMENTED** [review]
> Reviewed 35 of 35 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 12 unresolved discussions (waiting on @gbrodman, @param, and @ptkach)

___
*[`core/src/main/java/google/registry/request/auth/AuthResult.java` line 59 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv5z_cBpV6it1Jqg7h:-NwykaDm8cd5rfdXYRvD:b-ooearx) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/request/auth/AuthResult.java#L59)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can we rename this to serviceAccountEmail or something to make it clear that this should *not* be the user's email?
</blockquote></details>

It was only a private method so I don't think there would be any confusion to the users. But sure.
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java` line 56 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv71f42hZ79GlBbWmF:-NwykmR1E3-0DuFM0R6T:b-9nv1ps) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java#L56)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we want this to be PUBLIC_LOGGIED_IN
</blockquote></details>

I think all actions that extends `HtmlAction` can now be `AUTH_PUBLIC_LOGGED_IN`, as they are now behind IAP and there is no way for an unauthenticated request to reach them. I left them as `AUTH_PUBLIC` so that they behave absolutely the same as before (sans the support for legacy auth, of course) and there is one fewer variable to worry about. In the grand scheme of things this probably doesn't matter because we will stop supporting the legacy console soon.

If you feel strongly, I'm OK with changing them to `AUTH_PUBLIC_LOGGED_IN`, though I don't think it will affect anything in practice.
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java` line 66 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv74GO76YmNoNlbrG7:-Nwym2XeDc8qAwkFCKXr:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/ConsoleRegistrarCreatorAction.java#L66)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we want this to be PUBLIC_LOGGIED_IN
</blockquote></details>

Ditto.
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleUiAction.java` line 43 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv75gu3mWD-qzyoO_D:-Nwym3IN1N6Bl5a02FeA:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/ConsoleUiAction.java#L43)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we want this to be PUBLIC_LOGGIED_IN
</blockquote></details>

Ditto.
___
*[`core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java` line 79 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7BO3D7R4PkJbQff6:-Nwym65337e7R3eg0UtR:b-5ftecq) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java#L79)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

sadly this does not work as well as you might expect, but it's probably still better than nothing
</blockquote></details>

I tried and it seems to work fine. If you click on the button, it will log you out and take you back to the IAP login screen. I think that is as much as one can do with the endpoints behind IAP. It is also the same behavior as what the logout button does in the new console.

Can you clarify what you meant by "this does not work as well as you might expect"?
___
*[`core/src/test/java/google/registry/request/auth/RequestAuthenticatorTest.java` line 51 at r5](https://reviewable.io/reviews/google/nomulus/2414#-NwvAUjQ3LFFxlFtdKsU:-Nwymp9cEBB3ZcUBY-gD:b-tx9tx9) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/request/auth/RequestAuthenticatorTest.java#L51)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

fwiw "false" is the default for admin, no need to set it
</blockquote></details>

Correct. I think in a lot of places we set it to `false` unnecessary.
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleEppPasswordActionTest.java` line 199 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7pgd8yHsWBY-30VQ:-Nwyo3ML9rV3dysODOpV:b464sbf) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/ui/server/console/ConsoleEppPasswordActionTest.java#L199)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we can remove this cookie-setting code, since the fake params class does it for us? (This comment may apply multiple places in the PR)
</blockquote></details>

Correct. It turned out after rebasing it is gone already :P
___
*[`core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java` line 402 at r5](https://reviewable.io/reviews/google/nomulus/2414#-NwvBEIXEm6IiGngB-Cz:-NwyoHDq1EpugfQA2bx6:b-51at5r) ([raw file](https://github.com/google/nomulus/blob/03b358726a0dfc336f7262e6e132d9c0cdcca870/core/src/test/java/google/registry/ui/server/registrar/RegistryLockPostActionTest.java#L402)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

we'll need to change this, but you already noted that in the commit description
</blockquote></details>

Yes, just waiting for your PR to get merged and deployed.
___
*[`core/src/test/java/google/registry/webdriver/RegistrarCreateConsoleScreenshotTest.java` line 42 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv8BCc8AF9sDZibE5W:-NwyoetcCqbPkrN41DN1:binux3j) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/webdriver/RegistrarCreateConsoleScreenshotTest.java#L42)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can we just put this in WebDriverTestCase so we don't need to repeat it?
</blockquote></details>

That's a good pint, but unfortunately no. It needs access to the `server` field, which is set by each child test class (as the route is different in each class).
___
*[`core/src/test/java/google/registry/testing/ConsoleApiParamsUtil.java` line 27 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7W3R2Pbx4HCb-w5V:-Nwyn-UhDOaxNDBJEVJ2:b-lb9b8p) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/testing/ConsoleApiParamsUtil.java#L27)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

By convention, I think we'd want this to be ConsoleApiParamsUtil*s. But why do we need to change this at all?
</blockquote></details>

Because `FakeConsoleApiParams` suggests that the class is a fake implementation of `ConsoleApiParams`, but in reality it just provides a helper function that returns a real `ConsoleApiParams`, which some fake/mocked parameters.

And yes, it should have been `*Utils`.

**Review by jianglai — COMMENTED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 9 unresolved discussions (waiting on @gbrodman, @param, and @ptkach)

___
*[`core/src/main/java/google/registry/request/auth/AuthResult.java` line 59 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv5z_cBpV6it1Jqg7h:-NwzM3uZ8yxMi2jAK5Wf:becbz7q) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/request/auth/AuthResult.java#L59)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think the order of the words in the variable got mixed up :|
</blockquote></details>

oops...
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java` line 56 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv71f42hZ79GlBbWmF:-NwzM5Ob4VGokrQaL-sB:b1d9lbw) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java#L56)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What do you mean by "they behave absolutely the same as before"? I think it's probably best to have them be AUTH_PUBLIC_LOGGED_IN just in case we accidentally mess up something with the IAP configuration at some point. There's no downside to setting them to that; it's the more correct option and we're changing this file anyway.
</blockquote></details>

What I meant is that these endpoints used to allow unlogged-in users because they would redirect them to the login page. Now they would just return 401, but it should be a condition that is never true because the endpoints are behind IAP.

**Review by gbrodman — COMMENTED** [review]
Looks good to me, waiting to approve until we can get all the dependencies through. 

> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414#-:-Nwzm2U57F8Jk0G5HUYn:b-fbrrse)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java` line 79 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7BO3D7R4PkJbQff6:-Nwzkh247YlGSYr0TWUx:b-syhydd) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java#L79)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I tried and it seems to work fine. If you click on the button, it will log you out and take you back to the IAP login screen. I think that is as much as one can do with the endpoints behind IAP. It is also the same behavior as what the logout button does in the new console.

Can you clarify what you meant by "this does not work as well as you might expect"?
</blockquote></details>

I don't remember exactly but if you try reloading / refreshing it might not actually fully log you out, if you have IAP sessions open on other sites (like gmail). It's not a huge deal. 
___
*[`core/src/test/java/google/registry/webdriver/RegistrarCreateConsoleScreenshotTest.java` line 42 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv8BCc8AF9sDZibE5W:-Nwzlvvk65QjjPrt2dl8:byg9ocy) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/test/java/google/registry/webdriver/RegistrarCreateConsoleScreenshotTest.java#L42)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

That's a good pint, but unfortunately no. It needs access to the `server` field, which is set by each child test class (as the route is different in each class).
</blockquote></details>

womp :(

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java` line 79 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7BO3D7R4PkJbQff6:-NwzzLID2_QxdUU-G5xL:b-gt49j2) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java#L79)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't remember exactly but if you try reloading / refreshing it might not actually fully log you out, if you have IAP sessions open on other sites (like gmail). It's not a huge deal.
</blockquote></details>

Is it specific to the old console? I copy & pasted the URL from the new console, so I would expect it to behave the same?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java` line 79 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7BO3D7R4PkJbQff6:-Nx-K0596A8VcTZ6kIcT:b-atu0bl) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java#L79)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is it specific to the old console? I copy & pasted the URL from the new console, so I would expect it to behave the same?
</blockquote></details>

No, this was in the new console. Pavlo and I had a few discussions a while back where we decided it was fine.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java` line 79 at r5](https://reviewable.io/reviews/google/nomulus/2414#-Nwv7BO3D7R4PkJbQff6:-Nx-t2BL9Tw5qESkMpam:b-z4mrwp) ([raw file](https://github.com/google/nomulus/blob/c619c86d6efa72d86988c1f0edba57b7a64b1b67/core/src/main/java/google/registry/ui/server/registrar/HtmlAction.java#L79)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

No, this was in the new console. Pavlo and I had a few discussions a while back where we decided it was fine.
</blockquote></details>

OK, make sense. I think it is fine too.

**Review by gbrodman — COMMENTED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

**Review by gbrodman — COMMENTED** [review]
> Reviewed 20 of 20 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed 14 of 14 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

**Review by gbrodman — APPROVED** [review]
> Reviewed 14 of 14 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: all files reviewed, 3 unresolved discussions (waiting on @param and @ptkach)

**Review by jianglai — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> Reviewed 22 of 23 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed 23 of 23 files at r12, 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 5 files at r14, 1 of 2 files at r15, 16 of 16 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 20 files at r9, 1 of 16 files at r16, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2414)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
