### PR TITLE
Create reusable dialog / bottom sheet component

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2237)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2237)* status: all files reviewed, 4 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/registrar/registrarDetails.component.ts` line 30 at r1](https://reviewable.io/reviews/google/nomulus/2237#-Nkq8gyL5G4YAoYIT5_p:-Nkq8gyL5G4YAoYIT5_q:bw74ngt) ([raw file](https://github.com/google/nomulus/blob/41958715411455cb4d18140dc49672543f6622d4/console-webapp/src/app/registrar/registrarDetails.component.ts#L30)):*
> ```XML
> import { MatChipInputEvent } from '@angular/material/chips';
> 
> const MOBILE_LAYOUT_BREAKPOINT = '(max-width: 599px)';
> ```

i think we can remove this line?
___
*[`console-webapp/src/app/settings/contact/contact.component.ts` line 115 at r1](https://reviewable.io/reviews/google/nomulus/2237#-Nkq9tkZ79y9M-e1DeJq:-Nkq9tkZ79y9M-e1DeJr:by6tx7p) ([raw file](https://github.com/google/nomulus/blob/cf27a08aa212bc48bbe25cdfe473dcc9236b7628/console-webapp/src/app/settings/contact/contact.component.ts#L115)):*
> ```XML
>   }
> 
>   onClose(e?: MouseEvent) {
> ```

I'm not sure how the injector works / how these are getting closed, how is this changing from the previous behavior? 
___
*[`console-webapp/src/app/shared/components/dialogBottomSheet.component.ts` line 1 at r1](https://reviewable.io/reviews/google/nomulus/2237#-Nkq8Y8w5mrTXfUt3EYX:-Nkq8Y8w5mrTXfUt3EYY:b7rsyyr) ([raw file](https://github.com/google/nomulus/blob/cf27a08aa212bc48bbe25cdfe473dcc9236b7628/console-webapp/src/app/shared/components/dialogBottomSheet.component.ts#L1)):*
> ```XML
> import { BreakpointObserver } from '@angular/cdk/layout';
> ```

need a license 
___
*[`console-webapp/src/app/shared/components/dialogBottomSheet.component.ts` line 13 at r1](https://reviewable.io/reviews/google/nomulus/2237#-NkqABe13Isi-8Fo2dy3:-NkqABe13Isi-8Fo2dy4:bm22rka) ([raw file](https://github.com/google/nomulus/blob/cf27a08aa212bc48bbe25cdfe473dcc9236b7628/console-webapp/src/app/shared/components/dialogBottomSheet.component.ts#L13)):*
> ```XML
>   template: '',
> })
> export class DialogBottomSheetWrapper {
> ```

Can we have a small javadoc-type doc for this since it's kind of a library that can be used later by other components?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2237)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/registrar/registrarDetails.component.ts` line 30 at r1](https://reviewable.io/reviews/google/nomulus/2237#-Nkq8gyL5G4YAoYIT5_p:-NkqSOrFEDqgmPB2fJhx:b-t66avr) ([raw file](https://github.com/google/nomulus/blob/41958715411455cb4d18140dc49672543f6622d4/console-webapp/src/app/registrar/registrarDetails.component.ts#L30)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think we can remove this line?
</blockquote></details>

Yes yes
___
*[`console-webapp/src/app/settings/contact/contact.component.ts` line 115 at r1](https://reviewable.io/reviews/google/nomulus/2237#-Nkq9tkZ79y9M-e1DeJq:-Nkvb-eqE2um2rLaGlxi:b9qqqt3) ([raw file](https://github.com/google/nomulus/blob/cf27a08aa212bc48bbe25cdfe473dcc9236b7628/console-webapp/src/app/settings/contact/contact.component.ts#L115)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I'm not sure how the injector works / how these are getting closed, how is this changing from the previous behavior?
</blockquote></details>

I actually realized I can do better and encapsulate this entire logic withing a wrapper component. This way child components do not need to know about the details, like what kind of a component do they get injected in - MatBottomSheetRef or MatDialogRef, or how to close or where get the parameters. 

However to answer your question injector allows us to handle injection at runtime, so we can decide on a token we want to inject. See more details - https://medium.com/@gurunadhpukkalla/injectors-in-angular-a-comprehensive-guide-with-example-d9b7f57a1408
___
*[`console-webapp/src/app/shared/components/dialogBottomSheet.component.ts` line 1 at r1](https://reviewable.io/reviews/google/nomulus/2237#-Nkq8Y8w5mrTXfUt3EYX:-Nkvc3s38nKSQeVY_yHo:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cf27a08aa212bc48bbe25cdfe473dcc9236b7628/console-webapp/src/app/shared/components/dialogBottomSheet.component.ts#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

need a license
</blockquote></details>

Done.
___
*[`console-webapp/src/app/shared/components/dialogBottomSheet.component.ts` line 13 at r1](https://reviewable.io/reviews/google/nomulus/2237#-NkqABe13Isi-8Fo2dy3:-Nkvc4T82PkjrTipm9SQ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cf27a08aa212bc48bbe25cdfe473dcc9236b7628/console-webapp/src/app/shared/components/dialogBottomSheet.component.ts#L13)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Can we have a small javadoc-type doc for this since it's kind of a library that can be used later by other components?
</blockquote></details>

Done.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2237)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/contact/contact-details.component.html` line 1 at r3](https://reviewable.io/reviews/google/nomulus/2237#-Nkvu1ib94ZL_oYW7lw3:-Nkvu1ib94ZL_oYW7lw4:b49otdt) ([raw file](https://github.com/google/nomulus/blob/ac7f29f1e3704679f75df939f1851bb9c57ffe4f/console-webapp/src/app/settings/contact/contact-details.component.html#L1)):*
> ```HTML
> <h3 mat-dialog-title>Contact details</h3>
> ```

i think we should rename this file to camelCase? 
___
*[`console-webapp/src/app/settings/contact/contact.component.ts` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2237#-Nkvz37j6x7RFl2DQ2sU:-Nkvz37j6x7RFl2DQ2sV:bwu1ivm) ([raw file](https://github.com/google/nomulus/blob/ac7f29f1e3704679f75df939f1851bb9c57ffe4f/console-webapp/src/app/settings/contact/contact.component.ts#L48)):*
> ```XML
> 
> type ContactDetailsParams = {
>   onClose: Function;
> ```

actually i wonder if `close` is a better term for these than `onClose` since it's instructing the wrapper to close, not something that happens after the wrapper has already closed 

thoughts? 
___
*[`console-webapp/src/app/shared/components/dialogBottomSheet.component.ts` line 26 at r3](https://reviewable.io/reviews/google/nomulus/2237#-NkvxIbT-77rYefqJ7qc:-NkvxIbT-77rYefqJ7qd:b4fbpa) ([raw file](https://github.com/google/nomulus/blob/ac7f29f1e3704679f75df939f1851bb9c57ffe4f/console-webapp/src/app/shared/components/dialogBottomSheet.component.ts#L26)):*
> ```XML
> const MOBILE_LAYOUT_BREAKPOINT = '(max-width: 599px)';
> 
> export interface DialogBottomSheetContent {
> ```

Why not make this an abstract class and include the `onClose` method here? That way we could still refer to `onClose` methods in the HTML files but the subclasses e.g. RegistrarDetailsComponent wouldn't need to actually implement it. 

Then we wouldn't need to have the wrapper *Params classes 

I'm not sure exactly what that would look like, but it seems like we should be able to pass DialogBottomSheetWrapper's `onClose` method in to the DialogBottomSheetContent so that it gets called whenever the DialogBottomSheetContent's onClose method is called. 
___
*[`console-webapp/src/app/shared/components/dialogBottomSheet.component.ts` line 53 at r3](https://reviewable.io/reviews/google/nomulus/2237#-NkvvOqC7rwb0EtGqCon:-NkvvOqD0Vj84iiBxXZK:bu663h2) ([raw file](https://github.com/google/nomulus/blob/ac7f29f1e3704679f75df939f1851bb9c57ffe4f/console-webapp/src/app/shared/components/dialogBottomSheet.component.ts#L53)):*
> ```XML
>   ) {
>     const config = { data, onClose: () => this.onClose() };
>     if (this.breakpointObserver.isMatched(MOBILE_LAYOUT_BREAKPOINT)) {
> ```

Does this trigger if the user is on a non-mobile device but changes the width of the window to be smaller than 599 pixels?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2237)* status: 3 of 11 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`console-webapp/src/app/settings/contact/contact.component.ts` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2237#-Nkvz37j6x7RFl2DQ2sU:-Nl9__sE9fqqQq1RKiUD:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/ac7f29f1e3704679f75df939f1851bb9c57ffe4f/console-webapp/src/app/settings/contact/contact.component.ts#L48)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

actually i wonder if `close` is a better term for these than `onClose` since it's instructing the wrapper to close, not something that happens after the wrapper has already closed 

thoughts?
</blockquote></details>

Updated
___
*[`console-webapp/src/app/shared/components/dialogBottomSheet.component.ts` line 26 at r3](https://reviewable.io/reviews/google/nomulus/2237#-NkvxIbT-77rYefqJ7qc:-Nl9_cJC3jpE-X2SVwah:b-pnsyif) ([raw file](https://github.com/google/nomulus/blob/ac7f29f1e3704679f75df939f1851bb9c57ffe4f/console-webapp/src/app/shared/components/dialogBottomSheet.component.ts#L26)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Why not make this an abstract class and include the `onClose` method here? That way we could still refer to `onClose` methods in the HTML files but the subclasses e.g. RegistrarDetailsComponent wouldn't need to actually implement it. 

Then we wouldn't need to have the wrapper *Params classes 

I'm not sure exactly what that would look like, but it seems like we should be able to pass DialogBottomSheetWrapper's `onClose` method in to the DialogBottomSheetContent so that it gets called whenever the DialogBottomSheetContent's onClose method is called.
</blockquote></details>

What you're suggesting is more like a Java-way to do it, however sending a callback as a parameter is a common way to do that in front-end and I think it'd be expected this way for anyone looking into this coming from Reach/Vue/Angular background. Also we'd need to set a reference to Wrapper component to a details Content component first, so that it'd be able to close it, for that we'd need to import necessary dependencies and spill implementation details there, which I'm trying to avoid by keeping each part to only strictly necessary implementation details.
___
*[`console-webapp/src/app/shared/components/dialogBottomSheet.component.ts` line 53 at r3](https://reviewable.io/reviews/google/nomulus/2237#-NkvvOqC7rwb0EtGqCon:-Nkw1-164P2fvU32S-4a:b2nhswy) ([raw file](https://github.com/google/nomulus/blob/ac7f29f1e3704679f75df939f1851bb9c57ffe4f/console-webapp/src/app/shared/components/dialogBottomSheet.component.ts#L53)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Does this trigger if the user is on a non-mobile device but changes the width of the window to be smaller than 599 pixels?
</blockquote></details>

Yes
___
*[`console-webapp/src/app/settings/contact/contact-details.component.html` line 1 at r3](https://reviewable.io/reviews/google/nomulus/2237#-Nkvu1ib94ZL_oYW7lw3:-Nl9YlZZ669MauZ2br_5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ac7f29f1e3704679f75df939f1851bb9c57ffe4f/console-webapp/src/app/settings/contact/contact-details.component.html#L1)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think we should rename this file to camelCase?
</blockquote></details>

Done.

**Pull request merged**
