### PR TITLE
Change TaskQueueUtils to CloudTaskUtils in CommitLogFanoutAction

### PR DESCRIPTION
**Pull request by rachelguan**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1408)

### CODE REVIEW

**Review by jianglai — CHANGES_REQUESTED** [review]
The PR name should be consistent with the others, i. e. "Change TaskQueueUtils to CloudTasksUtils ...".

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408#-:-Mns3B_s0q7MiZKfHhJ9:b-2zjunj)* status: all files reviewed, 1 unresolved discussion (waiting on @rachelguan)

___
*[core/src/main/java/google/registry/cron/CommitLogFanoutAction.java, line 69 at r1](https://reviewable.io/reviews/google/nomulus/1408#-Mns5ZSD5KIzkAl8M7Xm:-Mns5ZSD5KIzkAl8M7Xn:b8n5ubi) ([raw file](https://github.com/google/nomulus/blob/39aaa0f53000a09b9cc0c7cda8c4561578893047/core/src/main/java/google/registry/cron/CommitLogFanoutAction.java#L69)):*
It looks like this pattern is used more than once (in `TldFanoutAction` as well at least). Let's extract it to a common method so it's easier to use:

`CloudTasksUtils.createTask(path, method, service, params, clock, jitterSecond)`.
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>     Instant scheduleTime =
>         Instant.ofEpochMilli(
>             clock
>                 .nowUtc()
>                 .plusMillis(
>                     jitterSeconds
>                         .map(seconds -> random.nextInt((int) SECONDS.toMillis(seconds)))
>                         .orElse(0))
>                 .getMillis());
> ```
</details>

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/main/java/google/registry/cron/CommitLogFanoutAction.java, line 69 at r1](https://reviewable.io/reviews/google/nomulus/1408#-Mns5ZSD5KIzkAl8M7Xm:-Mo-CMD_8G8myqgg7KUF:b-z7wxp0) ([raw file](https://github.com/google/nomulus/blob/39aaa0f53000a09b9cc0c7cda8c4561578893047/core/src/main/java/google/registry/cron/CommitLogFanoutAction.java#L69)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It looks like this pattern is used more than once (in `TldFanoutAction` as well at least). Let's extract it to a common method so it's easier to use:

`CloudTasksUtils.createTask(path, method, service, params, clock, jitterSecond)`.

> ```
>     Instant scheduleTime =
>         Instant.ofEpochMilli(
>             clock
>                 .nowUtc()
>                 .plusMillis(
>                     jitterSeconds
>                         .map(seconds -> random.nextInt((int) SECONDS.toMillis(seconds)))
>                         .orElse(0))
>                 .getMillis());
> ```

</blockquote></details>

I noticed that as well.. And it seems like I would have to add some other common methods as well in CloudTasksUtils. For now, I will add a createTask() that takes jitterSecond and clock and I'm going to add a variation that takes different headers in the upcoming PRs.

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @jianglai and @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 138 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5ia0h4g3nuPXge7z6:-Mo5ia0h4g3nuPXge7z7:byuvcn) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L138)):*
> ```
> private static Task createTask
> ```
This warrants a javadoc. What jitterSeconds does is not obvious from the function signature alone.
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 144 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5j8x4CJeByMBYoqpu:-Mo5j8x4CJeByMBYoqpv:b-iaj62j) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L144)):*
> ```
> Optional<Integer> jitterSeconds
> ```
What's the point of passing an optional here? We should call this method when jitterSeconds is non-zero, right?
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 145 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5iYXwBuSRU1Y5aG_5:-Mo5iYXwBuSRU1Y5aG_6:b-615vt0) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L145)):*
> ```Java
>       Clock clock,
>       Optional<Integer> jitterSeconds) {
> ```

Extra whitespace.
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5jVAH2UcoiXfyn2PQ:-Mo5jVAH2UcoiXfyn2PR:b-nnvlts) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L91)):*
> ```
>     // epoch time 1636347600 is equivalent to the current clock up to seconds.
>     // no assertion for nano seconds because getNanos() only accesses the underlying
>     // nanosecond-adjustment of the instant.
> ```
I don't quite understand the comment here, the scheduled time is a random number, isn't it? So we can only assert that is is not zero (i. e. it is explicitly set). If you want to be precise you can assert that the scheduled time is within the current time + jitterSeconds.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jianglai and @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 145 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5iYXwBuSRU1Y5aG_5:-Mo61SHs427mUgbPlBgS:brpmqc3) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L145)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Extra whitespace.
</blockquote></details>

removed.
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5jVAH2UcoiXfyn2PQ:-Mo61TZW5x5BpW-rXyX7:b-kzvkhu) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L91)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>     // epoch time 1636347600 is equivalent to the current clock up to seconds.
>     // no assertion for nano seconds because getNanos() only accesses the underlying
>     // nanosecond-adjustment of the instant.
> ```
I don't quite understand the comment here, the scheduled time is a random number, isn't it? So we can only assert that is is not zero (i. e. it is explicitly set). If you want to be precise you can assert that the scheduled time is within the current time + jitterSeconds.
</blockquote></details>

removed. originally i was going to see if i could have an assertion for getNanos() as well but ran into an error. Right now im just going to check if the seconds() is not equal to zero.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jianglai and @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 144 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5j8x4CJeByMBYoqpu:-Mo61myFELifbZvjtEdX:b8mmyby) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L144)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> Optional<Integer> jitterSeconds
> ```
What's the point of passing an optional here? We should call this method when jitterSeconds is non-zero, right?
</blockquote></details>

Based on what I noticed, jitterSeconds is injected and Optional<Integer> is the original type. 

If the non zero check is done outside of this method, the same check will be written in multiple places. Even though it's just a one line check, I think it makes more sense to keep it here to avoid writing the same check in multiple places

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jianglai)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 138 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5ia0h4g3nuPXge7z6:-Mo66P9m5rS81Ljl6vwc:b-896fix) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L138)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> private static Task createTask
> ```
This warrants a javadoc. What jitterSeconds does is not obvious from the function signature alone.
</blockquote></details>

Done.

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: all files reviewed, 3 unresolved discussions (waiting on @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 138 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5ia0h4g3nuPXge7z6:-MoFg5yE1_4Fe2G1mFFU:b2o7wkb) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L138)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I meant was to write a javadoc for this function. Even though this is a private function, it is still where the jitter seconds is actually used, so we should explain what it does here.
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 144 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5j8x4CJeByMBYoqpu:-MoFjCZm4fruGYlIZOIQ:b-ccyzbg) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L144)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Based on what I noticed, jitterSeconds is injected and Optional<Integer> is the original type. 

If the non zero check is done outside of this method, the same check will be written in multiple places. Even though it's just a one line check, I think it makes more sense to keep it here to avoid writing the same check in multiple places 
</blockquote></details>

I still think it probably makes more sense to check it outside this function, because `CloudTasksUtils` should not care about how the jitter seconds variable is injected, but I get it that this way we make the call sites cleaner.

If we do what to do the check here, you can simply return `createTask(path, method, service, params)` when the optional is empty. There is no need to set the time on the task when no jitter seconds variable is provided.
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5jVAH2UcoiXfyn2PQ:-MoFk4K-CfhmjCMVoCC1:b-2z5vv) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L91)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

removed. originally i was going to see if i could have an assertion for getNanos() as well but ran into an error. Right now im just going to check if the seconds() is not equal to zero. 
</blockquote></details>

have you tried checking if seconds + nano seconds falls within current time and current time + jitterSeconds?

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @jianglai)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 138 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5ia0h4g3nuPXge7z6:-MoGcpyz5b4_2DSrBJcw:bnbhww0) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L138)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

What I meant was to write a javadoc for this function. Even though this is a private function, it is still where the jitter seconds is actually used, so we should explain what it does here.
</blockquote></details>

I included that for the createPostTask and createGetTask variation since those two are public. 
Included javadoc here as well, which was based off the existing createTask javadoc. 
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 144 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5j8x4CJeByMBYoqpu:-MoGugboBsWTRAHMWEKC:be6nl10) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/main/java/google/registry/util/CloudTasksUtils.java#L144)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I still think it probably makes more sense to check it outside this function, because `CloudTasksUtils` should not care about how the jitter seconds variable is injected, but I get it that this way we make the call sites cleaner.

If we do what to do the check here, you can simply return `createTask(path, method, service, params)` when the optional is empty. There is no need to set the time on the task when no jitter seconds variable is provided.
</blockquote></details>

went with the latter approach by calling ```createTask(path, method, service, params)``` when jitterseconds is empty or below or equal to zero. 
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/1408#-Mo5jVAH2UcoiXfyn2PQ:-MoH1eYC9wIH7Ad_CVvx:be9f3tr) ([raw file](https://github.com/google/nomulus/blob/697286eb7c11d2975e9f57e0b51e80ce8fc639b1/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L91)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

have you tried checking if seconds + nano seconds falls within current time and current time + jitterSeconds?
</blockquote></details>

now I changed the way to do time comparison; it's a good idea to check both upper bound and lower bound. Thanks!

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: all files reviewed, 5 unresolved discussions (waiting on @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 139 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKuuNQ1Vekl918S7hQ:-MoKuuNQ1Vekl918S7hR:b-5560hg) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/main/java/google/registry/util/CloudTasksUtils.java#L139)):*
> ```
> Create a {@link Task} to be enqueued.
> ```
Create a Task to be enqueue with a random delay.
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 149 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKv1kGBH0g7ED_ZtNC:-MoKv1kGBH0g7ED_ZtND:blft1p8) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/main/java/google/registry/util/CloudTasksUtils.java#L149)):*
> ```
> @param clock a source of time.
> ```
This is cute :). Though we have not been very strict about requiring every parameter to be explained. You could have skipped this one.
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 163 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKuT_E6Hh3OTsFWrUc:-MoKuT_F2U4vLuOeu6G1:b540ib5) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/main/java/google/registry/util/CloudTasksUtils.java#L163)):*
> ```
> (jitterSeconds.isPresent() && jitterSeconds.get() <= 0) || jitterSeconds.isEmpty()
> ```
This can just be `(jitterSeconds.isEmpty() || jitterSeconds.get() <= 0)` because of short circuiting.
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 96 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKwSGf-UhPXmFQ4qt0:-MoKwSGf-UhPXmFQ4qt1:b-4l98w6) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L96)):*
> ```
> plusMillis
> ```
Shouldn't this be `plusSeconds`?
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 98 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKx2zk4FFi8Axw1O3D:-MoKx2zk4FFi8Axw1O3E:bj0r6j9) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L98)):*
> ```
>     assertThat(scheduleTime.getEpochSecond() + scheduleTime.getNano())
>         .isAtLeast(lowerBoundTime.getEpochSecond() + lowerBoundTime.getNano());
> ```
This can be just `assertThat(scheduleTime).isAfter(lowerBoundTime)`, right?

Same below.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @jianglai and @rachelguan)

___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 139 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKuuNQ1Vekl918S7hQ:-MoLCnD838I4chbcGe8n:b-nkvj82) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/main/java/google/registry/util/CloudTasksUtils.java#L139)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> Create a {@link Task} to be enqueued.
> ```
Create a Task to be enqueue with a random delay.
</blockquote></details>

Done../gra
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 149 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKv1kGBH0g7ED_ZtNC:-MoLAccv75xBrA_EARr3:b52wly1) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/main/java/google/registry/util/CloudTasksUtils.java#L149)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> @param clock a source of time.
> ```
This is cute :). Though we have not been very strict about requiring every parameter to be explained. You could have skipped this one.
</blockquote></details>

I thought  there's explanation for every single parameter of the existing createTask(), i might as well just add that here for the createTask() variation. This was actually found in our repo :)  
___
*[util/src/main/java/google/registry/util/CloudTasksUtils.java, line 163 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKuT_E6Hh3OTsFWrUc:-MoLA_6M9my98zYSj8aA:b-9ci8mb) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/main/java/google/registry/util/CloudTasksUtils.java#L163)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> (jitterSeconds.isPresent() && jitterSeconds.get() <= 0) || jitterSeconds.isEmpty()
> ```
This can just be `(jitterSeconds.isEmpty() || jitterSeconds.get() <= 0)` because of short circuiting.
</blockquote></details>

right. fixed. 
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 98 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKx2zk4FFi8Axw1O3D:-MoLGje_9I9iLNKpX_uQ:b-ccxicb) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L98)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
>     assertThat(scheduleTime.getEpochSecond() + scheduleTime.getNano())
>         .isAtLeast(lowerBoundTime.getEpochSecond() + lowerBoundTime.getNano());
> ```
This can be just `assertThat(scheduleTime).isAfter(lowerBoundTime)`, right?

Same below.
</blockquote></details>

there's randomness involved with jitterSeconds.
 ```random.nextInt(bound)``` returns a pseudorandom, uniformly distributed int value between 0 (inclusive) and the specified value (exclusive). 

I think it's safe to say that schedule time is less than the upper bound time, so I don't need to use ```isAtmost```..
However, there's a really low chance that the number ends up being zero and that will break the test case.

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: all files reviewed, 2 unresolved discussions (waiting on @rachelguan)

___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 96 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKwSGf-UhPXmFQ4qt0:-MoOofgj0zlEb57a7zq9:b308ek3) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L96)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> plusMillis
> ```
Shouldn't this be `plusSeconds`?
</blockquote></details>

There's no need to do this, you can just use `plusSeconds(100)`.

https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#plusSeconds-long-
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 98 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKx2zk4FFi8Axw1O3D:-MoOpErC8oDjIQpH1HiN:bd1vs6h) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L98)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

there's randomness involved with jitterSeconds.
 ```random.nextInt(bound)``` returns a pseudorandom, uniformly distributed int value between 0 (inclusive) and the specified value (exclusive). 

I think it's safe to say that schedule time is less than the upper bound time, so I don't need to use ```isAtmost```..
However, there's a really low chance that the number ends up being zero and that will break the test case.  
</blockquote></details>

Good point about the inclusive lower bound.

However you cannot just add the value of second with the value of nanosecond, can you? You have to convert them to the same unit (nanoseconds).

Plus, you can still use `Instant` to compare the lower bound, just do:

`assertThat(scheduleTime).isBefore(lowerBoundTime).isFalse()`.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 96 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKwSGf-UhPXmFQ4qt0:-MoLICf_C_P5CTzFkzE8:b-gfj8z5) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L96)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

There's no need to do this, you can just use `plusSeconds(100)`.

https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#plusSeconds-long-
</blockquote></details>

it was a typo, I meant to convert that to milliseconds in the code. 

 I tried to keep it similar to how schedule time was originally written: 
```
    Instant scheduleTime =
        Instant.ofEpochMilli(
            clock
                .nowUtc()
                .plusMillis(
                    jitterSeconds
                        .map(seconds -> random.nextInt((int) SECONDS.toMillis(seconds)))
                        .orElse(0))
                .getMillis());
```
And I really like the idea of adding more randomness by converting seconds to milliseconds. 
So for test cases, I tried to create times the same way it is in ```CloudTasksUtils.java'
___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 98 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKx2zk4FFi8Axw1O3D:-MoZQp0o5fxbbMVMOXJ4:bjtlibx) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L98)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Good point about the inclusive lower bound.

However you cannot just add the value of second with the value of nanosecond, can you? You have to convert them to the same unit (nanoseconds).

Plus, you can still use `Instant` to compare the lower bound, just do:

`assertThat(scheduleTime).isBefore(lowerBoundTime).isFalse()`.
</blockquote></details>

I tried to show explicitly the math but didn't think of converting the values. Comparing Instant object using the APIs it comes with definitely would work better. Thanks for the suggestion!

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: all files reviewed, 1 unresolved discussion (waiting on @rachelguan)

___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 96 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKwSGf-UhPXmFQ4qt0:-MocYeXW-Bp15lgajhSj:b-rjqpr2) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L96)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

it was a typo, I meant to convert that to milliseconds in the code. 

 I tried to keep it similar to how schedule time was originally written: 
```
    Instant scheduleTime =
        Instant.ofEpochMilli(
            clock
                .nowUtc()
                .plusMillis(
                    jitterSeconds
                        .map(seconds -> random.nextInt((int) SECONDS.toMillis(seconds)))
                        .orElse(0))
                .getMillis());
```
And I really like the idea of adding more randomness by converting seconds to milliseconds. 
So for test cases, I tried to create times the same way it is in ```CloudTasksUtils.java'
</blockquote></details>

It is correct that by using millisecond in generating the random number you get more "randomness", but here you are just creating a fix instant, what is the point of doing the unit conversion here? The instant is the same regardless of what unit you use.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[util/src/test/java/google/registry/util/CloudTasksUtilsTest.java, line 96 at r5](https://reviewable.io/reviews/google/nomulus/1408#-MoKwSGf-UhPXmFQ4qt0:-Mod_fXD8Vjx18EucWlI:b-oc2jde) ([raw file](https://github.com/google/nomulus/blob/eca93017b0f8bf7868ae70d21e16326652d53b03/util/src/test/java/google/registry/util/CloudTasksUtilsTest.java#L96)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It is correct that by using millisecond in generating the random number you get more "randomness", but here you are just creating a fix instant, what is the point of doing the unit conversion here? The instant is the same regardless of what unit you use.
</blockquote></details>

you got a point and i changed that.

**Review by jianglai — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1408)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachelguan)

**Pull request merged**
