### PR TITLE
Verify schema using Cloud Build

### PR DESCRIPTION
**Pull request by weiminyu**
Verifies that the actual schema is the same as the golden schema in currently deployed release.

This catches out-of-band schema changes, e.g., tables and indexes added for troubleshooting etc.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1627)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
Tested in alpha

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1627#-:-N1yn5ih8HN21taz2nwJ:b-97m2s3)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @jianglai and @mindhog)

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1627)* status: all files reviewed, 8 unresolved discussions (waiting on @mindhog and @weiminyu)

___
*[`release/cloudbuild-release.yaml` line 158 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24HTDR6k_H1Tm1RzJA:-N24HTDS37sL6tbMt6uJ:bpbi16) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/cloudbuild-release.yaml#L158)):*
> ```YAML
>         > release/cloudbuild-schema-deploy-${environment}.yaml
>     done
>     for environment in alpha crash sandbox production; do
> ```

Is there a reason why this cannot be done in the same loop above?



_Code quote:_
```YAML
 for environment in alpha crash sandbox production; do
```
___
*[`release/schema-verifier/Dockerfile` line 1 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24I6xK1gCO6j928b-L:-N24I6xK1gCO6j928b-M:b9npb00) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/schema-verifier/Dockerfile#L1)):*
> ```Dockerfile
> # Copyright 2019 The Nomulus Authors. All Rights Reserved.
> ```

I know this file is copied from `release/schema-deployer`, but since its content has changed meaningfully, we should update the date to 2022.



_Code quote:_
```Dockerfile
2019
```
___
*[`release/schema-verifier/verify_deployed_sql_schema.sh` line 2 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24II58-d7Q0QN78Yts:-N24II58-d7Q0QN78Ytt:brhumzt) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/schema-verifier/verify_deployed_sql_schema.sh#L2)):*
> ```Shell
> #!/bin/bash
> # Copyright 2019 The Nomulus Authors. All Rights Reserved.
> ```

Same here.



_Code quote:_
```Shell
2019
```
___
*[`release/schema-verifier/verify_deployed_sql_schema.sh` line 28 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24_7tx-PYkJ6E5VU4E:-N24_7tx-PYkJ6E5VU4F:b-ok8rd0) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/schema-verifier/verify_deployed_sql_schema.sh#L28)):*
> ```Shell
> 
> set -e
> if [ ! -f /secrets/schema_deployer_credential.dec ]; then
> ```

If all three files are necessary, why not test for all of their existence?



_Code quote:_
```Shell
if [ ! -f /secrets/schema_deployer_credential.dec ]; then
```
___
*[`release/schema-verifier/verify_deployed_sql_schema.sh` line 33 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24Y126A-j2xSId5KA3:-N24Y126A-j2xSId5KA4:bkm2666) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/schema-verifier/verify_deployed_sql_schema.sh#L33)):*
> ```Shell
> fi
> cloud_sql_instance=$(cut -d' ' -f1 /secrets/schema_deployer_credential.dec)
> db_user=$(cut -d' ' -f2 /secrets/schema_deployer_credential.dec)
> ```

read -r cloud_sql_instance db_user db_password <(cat /secrets/schema_deployer_credential.dec | awk '{print $1, $2, $3}') 



_Code quote:_
```Shell
cloud_sql_instance=$(cut -d' ' -f1 /secrets/schema_deployer_credential.dec)
db_user=$(cut -d' ' -f2 /secrets/schema_deployer_credential.dec)
db_password=$(cut -d' ' -f3 /secrets/schema_deployer_credential.dec)
```
___
*[`release/schema-verifier/verify_deployed_sql_schema.sh` line 77 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24a9NH-k1ERFC3Pxfy:-N24a9NH-k1ERFC3Pxfz:b-rn704s) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/schema-verifier/verify_deployed_sql_schema.sh#L77)):*
> ```Shell
> 
> raw_diff=$(diff /schema/nomulus.golden.sql /schema/nomulus.actual.sql)
> effective_diff=$(echo "${raw_diff}" \
> ```

There should be some comments on exactly what lines are being removed.



_Code quote:_
```Shell
effective_diff=$(echo "${raw_diff}" \
```
___
*[`release/schema-verifier/verify_deployed_sql_schema.sh` line 79 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24a4Bv6WgPa1-C5TgS:-N24a4Bv6WgPa1-C5TgT:b-aode3h) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/schema-verifier/verify_deployed_sql_schema.sh#L79)):*
> ```Shell
> effective_diff=$(echo "${raw_diff}" \
>                    | grep "^[<>]" | sed -e "s/^[<>]\s//g" \
>                    | grep -v "^--" | grep -v "^$"  \
> ```

`grep -v "^--|^$"`?



_Code quote:_
```Shell
grep -v "^--" | grep -v "^$" 
```
___
*[`release/schema-verifier/verify_deployed_sql_schema.sh` line 93 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24a_-cAS-EKkUEUBNe:-N24a_-cAS-EKkUEUBNf:b88o77z) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/schema-verifier/verify_deployed_sql_schema.sh#L93)):*
> ```Shell
> 
> # Stop Cloud SQL Proxy
> pkill cloud_sql_proxy
> ```

Maybe we should use a trap to kill the background proxy process so you don't have to do `set +-e` and can directly do `exit 0|1`.



_Code quote:_
```Shell
pkill cloud_sql_proxy
```

**Review by jianglai — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1627)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)

___
*[`release/schema-verifier/verify_deployed_sql_schema.sh` line 28 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24_7tx-PYkJ6E5VU4E:-N2DPeA2AjTMn85wnwD0:borqcho) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/schema-verifier/verify_deployed_sql_schema.sh#L28)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Actually no need to check. Removed.
</blockquote></details>

Why is there no need to check?

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1627)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @mindhog)

___
*[`release/schema-verifier/verify_deployed_sql_schema.sh` line 28 at r1](https://reviewable.io/reviews/google/nomulus/1627#-N24_7tx-PYkJ6E5VU4E:-N2DTseF1TQWiiQGn2OW:b-aak72q) ([raw file](https://github.com/google/nomulus/blob/27f3cee490549f024b91f322eab41de80ef19ae1/release/schema-verifier/verify_deployed_sql_schema.sh#L28)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Why is there no need to check?
</blockquote></details>

The correct error message from 'cat' will surface, and script will aborted, if the file does not exist.

**Pull request merged**
