### PR TITLE
Use ReplaySpecializer to fix DomainBase replays

### PR DESCRIPTION
**Pull request by mindhog**
DomainBase currently has a number of ancillary objects that require a
cascading delete that doesn't get propagated.  Implement beforeSqlDelete() in
DomainContent to delete these child entities.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/991)

### CODE REVIEW

**Comment by mindhog** [comment]
Note that this change depends on  #989

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/991)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 390 at r1](https://reviewable.io/reviews/google/nomulus/991#-MVI22MWBbXy9FfM-Oev:-MVI22MWBbXy9FfM-Oew:biio5i1) ([raw file](https://github.com/google/nomulus/blob/24647585b48cbd9334a385c8f559c62b455a71a1/core/src/main/java/google/registry/model/domain/DomainContent.java#L390)):*
> ```Java
>   public static void beforeSqlDelete(VKey<DomainBase> key) {
>     // Delete all grace periods associated with the domain.
>     Query query =
> ```

don't need to save the query object here, can just do 

```
jpaTm().getEntityManager().createQuery(...).setParameter(..).executeUpdate();
```
twice
___
*[core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java, line 531 at r1](https://reviewable.io/reviews/google/nomulus/991#-MVI2Sc286557IHF61cs:-MVI2Sc286557IHF61ct:b-jbedlf) ([raw file](https://github.com/google/nomulus/blob/24647585b48cbd9334a385c8f559c62b455a71a1/core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java#L531)):*
> ```Java
> 
>   @Test
>   void testFailure_nonexistentDomain() throws Exception {
> ```

Unfortunate that we have to make all these deletion calls. Maybe worth making a helper method in DatabaseHelper that deletes all resources that are based on the provided domain, thoughts?

**Review by gbrodman — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/991)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/991)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/domain/DomainContent.java, line 390 at r1](https://reviewable.io/reviews/google/nomulus/991#-MVI22MWBbXy9FfM-Oev:-MVI8-SK7gzL-2vntNJ1:b-3nkx7v) ([raw file](https://github.com/google/nomulus/blob/24647585b48cbd9334a385c8f559c62b455a71a1/core/src/main/java/google/registry/model/domain/DomainContent.java#L390)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

don't need to save the query object here, can just do 

```
jpaTm().getEntityManager().createQuery(...).setParameter(..).executeUpdate();
```
twice
</blockquote></details>

Done.  Fluent FTW!
___
*[core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java, line 531 at r1](https://reviewable.io/reviews/google/nomulus/991#-MVI2Sc286557IHF61cs:-MVI6HoR5bwh0-8uadZB:b-9i4daf) ([raw file](https://github.com/google/nomulus/blob/24647585b48cbd9334a385c8f559c62b455a71a1/core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java#L531)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Unfortunate that we have to make all these deletion calls. Maybe worth making a helper method in DatabaseHelper that deletes all resources that are based on the provided domain, thoughts? 
</blockquote></details>

Yeah, if we're doing it more than once.  A lot of what I'm deleting here is specific to DomainTransferFlowTestCase derivatives.  Do you know of any other locations where we're deleting a bunch of objects offhand?

I'll be adding replay to the rest of the transfer flow tests, so I'll likely be the first to run into the opportunity to refactor it.

**Review by gbrodman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/991#-:-MVRzmjo1bHeYz9MEoaN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

___
*[core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java, line 531 at r1](https://reviewable.io/reviews/google/nomulus/991#-MVI2Sc286557IHF61cs:-MVRzGdd5-zF8cz35gvs:b-7resco) ([raw file](https://github.com/google/nomulus/blob/24647585b48cbd9334a385c8f559c62b455a71a1/core/src/test/java/google/registry/flows/domain/DomainTransferApproveFlowTest.java#L531)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Yeah, if we're doing it more than once.  A lot of what I'm deleting here is specific to DomainTransferFlowTestCase derivatives.  Do you know of any other locations where we're deleting a bunch of objects offhand?

I'll be adding replay to the rest of the transfer flow tests, so I'll likely be the first to run into the opportunity to refactor it.
</blockquote></details>

Yeah, I think the only other situation I've seen might have been this case (when I was converting DomainTransfer*Flow calls to tm()).

**Pull request merged**
