### PR TITLE
Add OTE registrars to console /registrars response

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2440)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2440)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 80 at r1](https://reviewable.io/reviews/google/nomulus/2440#-NxnIlr03pyk3sbC3y5c:-NxnIlr03pyk3sbC3y5d:b-dcs7i6) ([raw file](https://github.com/google/nomulus/blob/7055210478bf8bfde09a929296d3693fd06ff840/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L80)):*
> ```Java
>             .filter(
>                 r ->
>                     ImmutableList.of(Registrar.Type.REAL, RegistrarBase.Type.OTE)
> ```

this is nitty but let's make this a constant so we don't need to recreate it / can give it a nice lil name
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 130 at r1](https://reviewable.io/reviews/google/nomulus/2440#-NxnJ2VWCH4KFUNeQEi_:-NxnJ2VWCH4KFUNeQEia:b-qdv5k7) ([raw file](https://github.com/google/nomulus/blob/7055210478bf8bfde09a929296d3693fd06ff840/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L130)):*
> ```Java
>     var expectedRegistrarIds = ImmutableList.of("NewRegistrar", "TheRegistrar", "registrarId2");
> 
>     assertThat(actualRegistrarIds).containsExactlyElementsIn(expectedRegistrarIds);
> ```

very small thing, but you don't need to make a new list, can just do something like `containsExactly("NewRegistrar"......)`

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2440)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 80 at r1](https://reviewable.io/reviews/google/nomulus/2440#-NxnIlr03pyk3sbC3y5c:-Nxs1G7D-j8uGOi5QAWX:bdxynu9) ([raw file](https://github.com/google/nomulus/blob/7055210478bf8bfde09a929296d3693fd06ff840/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L80)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this is nitty but let's make this a constant so we don't need to recreate it / can give it a nice lil name
</blockquote></details>

why not make it a constant?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2440)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 80 at r1](https://reviewable.io/reviews/google/nomulus/2440#-NxnIlr03pyk3sbC3y5c:-NxxtE2r8NNPZOTCZHCD:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/7055210478bf8bfde09a929296d3693fd06ff840/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L80)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

why not make it a constant?
</blockquote></details>

Updated

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2440)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
