### PR TITLE
Add autorenews to URS

### PR DESCRIPTION
**Pull request by rachelguan**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1343)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @rachelguan)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 103 at r1](https://reviewable.io/reviews/google/nomulus/1343#-Mkhs-IK0P7gx5zUTXeA:-Mkhs-IL3BC-ZYyOuxXA:b-irxm9n) ([raw file](https://github.com/google/nomulus/blob/f1841f75002c3293fb0155adcae5e6e74cf240c5/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L103)):*
> ```Java
>       names = {"--autorenews"},
>       description = "Flag determining whether or not the domain will be renewed for a year.")
>   private Boolean autorenews = false;
> ```

There's no need to add a command-line `@Parameter` here, as this shouldn't be independently set from the basic mode of operation of the URS tool itself, which is: "Normal -- lock domain, disable autorenew,  Undo -- Unlock domain, re-enable autorenew".

What you will need to add an `@Parameter` for though is the one year renewal option.  We might even make that a required parameter, which seems more foolproof.
___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 145 at r1](https://reviewable.io/reviews/google/nomulus/1343#-MkhsHnl27HKUu2vvWe9:-MkhsHnl27HKUu2vvWeA:byl9w9z) ([raw file](https://github.com/google/nomulus/blob/f1841f75002c3293fb0155adcae5e6e74cf240c5/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L145)):*
> ```Java
> 
>       // when run in --undo mode, it will always set {@link #autorenews} to true
>       autorenews = true;
> ```

Yeah, see, you definitely don't want an `@Parameter` above, as it doesn't make sense to override a user-set command line parameter.
___
*[core/src/main/java/google/registry/tools/UpdateDomainCommand.java, line 322 at r1](https://reviewable.io/reviews/google/nomulus/1343#-MkhshP4AA4YRFg4eTXU:-MkhshP4AA4YRFg4eTXV:b-6tmalg) ([raw file](https://github.com/google/nomulus/blob/f1841f75002c3293fb0155adcae5e6e74cf240c5/core/src/main/java/google/registry/tools/UpdateDomainCommand.java#L322)):*
> ```Java
>       if (autorenews != null) {
>         soyMapData.put("autorenews", autorenews.toString());
>         // we want to use metadata extension to set requestedByRegistrar to false and leave an
> ```

You shouldn't need to modify the `UpdateDomainCommand` at all in this PR.

Also this is incorrect, as you're overriding `requestedByRegistrar` which is coming from the user's command line invocation.  The correct thing to do would be to throw an error if the user has passed in incompatible arguments, not just silently ignore what they've requested and do something else.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @rachelguan)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 103 at r1](https://reviewable.io/reviews/google/nomulus/1343#-Mkhs-IK0P7gx5zUTXeA:-Mki1BLV-JBu1RKr-Fdw:bicsyu8) ([raw file](https://github.com/google/nomulus/blob/f1841f75002c3293fb0155adcae5e6e74cf240c5/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L103)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There's no need to add a command-line `@Parameter` here, as this shouldn't be independently set from the basic mode of operation of the URS tool itself, which is: "Normal -- lock domain, disable autorenew,  Undo -- Unlock domain, re-enable autorenew".

What you will need to add an `@Parameter` for though is the one year renewal option.  We might even make that a required parameter, which seems more foolproof.
</blockquote></details>

removed names and set required = true. 
___
*[core/src/main/java/google/registry/tools/UpdateDomainCommand.java, line 322 at r1](https://reviewable.io/reviews/google/nomulus/1343#-MkhshP4AA4YRFg4eTXU:-Mki3xOEDoxS8HpMPBaN:b-hfpv0l) ([raw file](https://github.com/google/nomulus/blob/f1841f75002c3293fb0155adcae5e6e74cf240c5/core/src/main/java/google/registry/tools/UpdateDomainCommand.java#L322)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You shouldn't need to modify the `UpdateDomainCommand` at all in this PR.

Also this is incorrect, as you're overriding `requestedByRegistrar` which is coming from the user's command line invocation.  The correct thing to do would be to throw an error if the user has passed in incompatible arguments, not just silently ignore what they've requested and do something else.
</blockquote></details>

removed

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @parameter)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 103 at r1](https://reviewable.io/reviews/google/nomulus/1343#-Mkhs-IK0P7gx5zUTXeA:-Mki9J7-CSfGTWP1fBuh:bsx8x5n) ([raw file](https://github.com/google/nomulus/blob/f1841f75002c3293fb0155adcae5e6e74cf240c5/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L103)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

removed names and set required = true. 
</blockquote></details>

** now there are two newly added variables: 1) renewOneYear which is a @Parameter and 2) autorenews 
___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 145 at r1](https://reviewable.io/reviews/google/nomulus/1343#-MkhsHnl27HKUu2vvWe9:-Mki9hzF64oJr1l8BZKN:b2nign3) ([raw file](https://github.com/google/nomulus/blob/f1841f75002c3293fb0155adcae5e6e74cf240c5/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L145)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yeah, see, you definitely don't want an `@Parameter` above, as it doesn't make sense to override a user-set command line parameter.
</blockquote></details>

yep

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @parameter)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 103 at r1](https://reviewable.io/reviews/google/nomulus/1343#-Mkhs-IK0P7gx5zUTXeA:-MknYrSe3qFYPRTvyjo5:b9nodp8) ([raw file](https://github.com/google/nomulus/blob/f1841f75002c3293fb0155adcae5e6e74cf240c5/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L103)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

** now there are two newly added variables: 1) renewOneYear which is a @Parameter and 2) autorenews 
</blockquote></details>

renewOneYear and related code will be in a separate PR

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @parameter, and @rachelguan)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 168 at r4](https://reviewable.io/reviews/google/nomulus/1343#-Mks6HW80fY9oClXPoqh:-Mks6HW80fY9oClXPoqi:b-gl67i5) ([raw file](https://github.com/google/nomulus/blob/d746c151afdeb23cf3f09698bb79f8ec93e19160/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L168)):*
> ```Java
>             (undo ? "Undo " : "") + "Uniform Rapid Suspension",
>             "autorenews",
>             Boolean.toString(autorenews)));
> ```

Do you even need a separate `autorenews` boolean here at all, or can it simply be `!undo`?

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @parameter)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 168 at r4](https://reviewable.io/reviews/google/nomulus/1343#-Mks6HW80fY9oClXPoqh:-MksAnXo1aMMbPHvFZzA:b-lux61f) ([raw file](https://github.com/google/nomulus/blob/d746c151afdeb23cf3f09698bb79f8ec93e19160/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L168)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Do you even need a separate `autorenews` boolean here at all, or can it simply be `!undo`?
</blockquote></details>

currently, autorenews is always false but set to true only when undo is true. Will there be other cases in future to use autorenews ? 
if not, then declaring autorenews and setting it to true if (undo) can be removed

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @parameter)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 168 at r4](https://reviewable.io/reviews/google/nomulus/1343#-Mks6HW80fY9oClXPoqh:-MksG6ps5_eIbQf-4r3S:bdpwmx3) ([raw file](https://github.com/google/nomulus/blob/d746c151afdeb23cf3f09698bb79f8ec93e19160/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L168)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

currently, autorenews is always false but set to true only when undo is true. Will there be other cases in future to use autorenews ? 
if not, then declaring autorenews and setting it to true if (undo) can be removed 
</blockquote></details>

autorenews should be same as undo since if (undo) autorenews = true; else, autorenews remains false.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @rachelguan)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 162 at r5](https://reviewable.io/reviews/google/nomulus/1343#-MkwcLeL3uEO-O0-DYmC:-MkwcLeL3uEO-O0-DYmD:b-z6tpgk) ([raw file](https://github.com/google/nomulus/blob/ab91b70a32ada6a140557304d7caecc3e719e832/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L162)):*
> ```Java
>             (undo ? "Undo " : "") + "Uniform Rapid Suspension",
>             "autorenews",
>             Boolean.toString(undo)));
> ```

Add a code comment here explaining what's going on (this might be non-obvious, or appear to be a mistake).

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 162 at r5](https://reviewable.io/reviews/google/nomulus/1343#-MkwcLeL3uEO-O0-DYmC:-MkwqHML2_ZY4IOZILzt:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ab91b70a32ada6a140557304d7caecc3e719e832/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L162)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Add a code comment here explaining what's going on (this might be non-obvious, or appear to be a mistake).
</blockquote></details>

Done.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @rachelguan)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 162 at r5](https://reviewable.io/reviews/google/nomulus/1343#-MkwcLeL3uEO-O0-DYmC:-MkxKvS91cyoHGMrXIK9:b-8jha6x) ([raw file](https://github.com/google/nomulus/blob/ab91b70a32ada6a140557304d7caecc3e719e832/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L162)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Rather than talking about true/false, talk about the _why_ of things.  Something like "Domain autorenewal is disabled as part of URS, and also re-enabled when URS is undone."

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343#-:-MkxLKRQD-nKSVXl3-vJ:bnfp4nl)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @rachelguan)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @rachelguan)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 162 at r5](https://reviewable.io/reviews/google/nomulus/1343#-MkwcLeL3uEO-O0-DYmC:-MkxLNtZ2jydtCbemkzX:brfyjye) ([raw file](https://github.com/google/nomulus/blob/ab91b70a32ada6a140557304d7caecc3e719e832/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L162)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Rather than talking about true/false, talk about the _why_ of things.  Something like "Domain autorenewal is disabled as part of URS, and also re-enabled when URS is undone."
</blockquote></details>

Make that:  "Domain autorenewal is disabled as part of URS, and also re-enabled if URS is undone."

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java, line 162 at r5](https://reviewable.io/reviews/google/nomulus/1343#-MkwcLeL3uEO-O0-DYmC:-MkxTECt6QNmKmHNLnnL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ab91b70a32ada6a140557304d7caecc3e719e832/core/src/main/java/google/registry/tools/UniformRapidSuspensionCommand.java#L162)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Make that:  "Domain autorenewal is disabled as part of URS, and also re-enabled if URS is undone."
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1343#-:-MkxW6Lb3NQhu9ZJdlby:bnfp4nl)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
