### PR TITLE
Implement DatastoreEntity/SqlEntity for many more classes

### PR DESCRIPTION
**Pull request by gbrodman**
We still have many more classes to go, but this gets us closer to
guaranteeing that we can convert from Datastore to SQL objects and back
again.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/788)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 13 of 18 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/788)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 85 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn3E4Y-UmPluu1mN0v:-MGn3E4Y-UmPluu1mN0w:b-b1ypkd) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/main/java/google/registry/model/contact/ContactHistory.java#L85)):*
> ```Java
>   @Override
>   public ImmutableList<DatastoreEntity> toDatastoreEntities() {
>     return ImmutableList.of(asHistoryEntry());
> ```

Can we make HistoryEntry implement DatastoreAndSqlEntity and move these methods there?
___
*[core/src/test/java/google/registry/model/ofy/OfyTest.java, line 333 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn4ebsDQb5wyR6a5bb:-MGn4ebsDQb5wyR6a5bc:b-zgiigg) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/test/java/google/registry/model/ofy/OfyTest.java#L333)):*
> ```Java
>             return null;
>           }
>         };
> ```

what's up with all of these formatting changes?
___
*[core/src/test/java/google/registry/schema/replay/EntityTest.java, line 47 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn5KbJ5brXl2NaU2Sf:-MGn5KbJ5brXl2NaU2Sg:bj5n061) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/test/java/google/registry/schema/replay/EntityTest.java#L47)):*
> ```
> containsExactlyElementsIn
> ```

Is there a reason to use containsExactlyElementsIn as opposed to isEqualTo?  I think you only need the former for comparing against a different type of iterable, right?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/788)* status: all files reviewed, 3 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 85 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn3E4Y-UmPluu1mN0v:-MGnCN9D6cInmMSZRbGY:b-wswf4l) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/main/java/google/registry/model/contact/ContactHistory.java#L85)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can we make HistoryEntry implement DatastoreAndSqlEntity and move these methods there?
</blockquote></details>

I don't believe we want to do that. Conceptually, when we're re-ingesting commit logs from Datastore -> SQL, we will be reading HistoryEntry objects from Datastore and writing DomainHistory (et al) objects to SQL. This is one of the only cases where we want these differences, that I'm aware of. 
___
*[core/src/test/java/google/registry/model/ofy/OfyTest.java, line 333 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn4ebsDQb5wyR6a5bb:-MGnC1JVEkC5garnln6B:b12v8vf) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/test/java/google/registry/model/ofy/OfyTest.java#L333)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

what's up with all of these formatting changes?
</blockquote></details>

autoformatting :( 
___
*[core/src/test/java/google/registry/schema/replay/EntityTest.java, line 47 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn5KbJ5brXl2NaU2Sf:-MGnBeBC0JA9ur3sx1EF:bc0zmje) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/test/java/google/registry/schema/replay/EntityTest.java#L47)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

> ```
> containsExactlyElementsIn
> ```

Is there a reason to use containsExactlyElementsIn as opposed to isEqualTo?  I think you only need the former for comparing against a different type of iterable, right? 
</blockquote></details>

`containsExactlyElementsIn` gives more information about what is missing / unexpected if the two iterables aren't exactly equal. For iterables, it seems to be objectively better

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/788)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 85 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn3E4Y-UmPluu1mN0v:-MGnDZo_5qLnGyDx0htY:b-7mpbcm) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/main/java/google/registry/model/contact/ContactHistory.java#L85)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't believe we want to do that. Conceptually, when we're re-ingesting commit logs from Datastore -> SQL, we will be reading HistoryEntry objects from Datastore and writing DomainHistory (et al) objects to SQL. This is one of the only cases where we want these differences, that I'm aware of. 
</blockquote></details>

I don't understand what that has to do with it :-) My point is simply that we could have a single toDatastoreEntities() method in HistoryEntry as opposed to implementing that interface in all of the derived classes.  asHistoryEntry() should already provide the necessary polymorphism.  Am I missing something?

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/788)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/model/ofy/OfyTest.java, line 333 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn4ebsDQb5wyR6a5bb:-MGnEeoH9z47-vtUhzzR:bvlq98x) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/test/java/google/registry/model/ofy/OfyTest.java#L333)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

autoformatting :( 
</blockquote></details>

But why is it happening here?  The format checks (and auto-formatting) should only be applied to spans of the code that have changed.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/788)* status: all files reviewed, 2 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 85 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn3E4Y-UmPluu1mN0v:-MGnF29C8hzEKvZQrhhy:b-mgh1vy) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/main/java/google/registry/model/contact/ContactHistory.java#L85)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I don't understand what that has to do with it :-) My point is simply that we could have a single toDatastoreEntities() method in HistoryEntry as opposed to implementing that interface in all of the derived classes.  asHistoryEntry() should already provide the necessary polymorphism.  Am I missing something?
</blockquote></details>

Oh, you're referring to implementing DatastoreEntity and SqlEntity (separately), not implementing DatastoreAndSqlEntity (which just returns `ImmutableList.of(this)`). 

Yes, we could do this. However, I kept it separate because it seemed clearer to me to say "HistoryEntry objects are Datastore entities, and DomainHistory objects are SQL entities".  Even though it's a bit of duplicated code, it seemed conceptually clearer. Thoughts? 
___
*[core/src/test/java/google/registry/model/ofy/OfyTest.java, line 333 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn4ebsDQb5wyR6a5bb:-MGnFR7g0xYY04NTkGoQ:b9eyzvt) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/test/java/google/registry/model/ofy/OfyTest.java#L333)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

But why is it happening here?  The format checks (and auto-formatting) should only be applied to spans of the code that have changed. 
</blockquote></details>

Most likely I just autoformatted the entire file. If we care I can revert it, though it might get changed at some point anyway.

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/788)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 85 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn3E4Y-UmPluu1mN0v:-MGnIiHl5WMY_hoU5mu6:b-sx263d) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/main/java/google/registry/model/contact/ContactHistory.java#L85)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Oh, you're referring to implementing DatastoreEntity and SqlEntity (separately), not implementing DatastoreAndSqlEntity (which just returns `ImmutableList.of(this)`). 

Yes, we could do this. However, I kept it separate because it seemed clearer to me to say "HistoryEntry objects are Datastore entities, and DomainHistory objects are SQL entities".  Even though it's a bit of duplicated code, it seemed conceptually clearer. Thoughts? 
</blockquote></details>

I see your point.  That's basically making use of the implementation as a form of documentation.  I agree that this is generally useful, but I think simplifying the code is a higher priority.  For documentation of which are datastore entities and which are SQL entities, the ofy.Entity and sql.Entity annotations are the correct documentational indicators. 
___
*[core/src/test/java/google/registry/model/ofy/OfyTest.java, line 333 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn4ebsDQb5wyR6a5bb:-MGnH_tqDG8R1Ygy9vrD:br9k0r8) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/test/java/google/registry/model/ofy/OfyTest.java#L333)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Most likely I just autoformatted the entire file. If we care I can revert it, though it might get changed at some point anyway. 
</blockquote></details>

We don't need to revert it.  But in general, please use "javaIncrementalFormatApply" or "java-format/google-java-format-git-diff.sh format" for reformatting as the unnecessary formatting changes distract from the salient change and break "git blame" history.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/788)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 85 at r2](https://reviewable.io/reviews/google/nomulus/788#-MGn3E4Y-UmPluu1mN0v:-MGnP_zM32mXKzCMRW_f:b-hda3n5) ([raw file](https://github.com/google/nomulus/blob/723767309d5ed9b8a2b0a36b80559120b0835f73/core/src/main/java/google/registry/model/contact/ContactHistory.java#L85)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I see your point.  That's basically making use of the implementation as a form of documentation.  I agree that this is generally useful, but I think simplifying the code is a higher priority.  For documentation of which are datastore entities and which are SQL entities, the ofy.Entity and sql.Entity annotations are the correct documentational indicators. 
</blockquote></details>

Yeah, makes sense. A plus: it gets rid of a forced cast . Done.

**Review by mindhog — APPROVED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/788)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Pull request merged**
