### PR TITLE
Add console /registrars GET endpoint

### PR DESCRIPTION
**Pull request by ptkach**
Deployed and tested on alpha

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2050)

### CODE REVIEW

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2050)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 37 at r1](https://reviewable.io/reviews/google/nomulus/2050#-NXMZ0UoBpy3YEsMfNfW:-NXMZ0UoBpy3YEsMfNfX:bnv93u0) ([raw file](https://github.com/google/nomulus/blob/2c35d9efa4081241cb2f405979a5f2068b4d44a9/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L37)):*
> ```Java
>     path = RegistrarsAction.PATH,
>     method = {GET},
>     auth = Auth.AUTH_INTERNAL_OR_ADMIN)
> ```

@gbrodman  I think this one is correct auth here, please confirm
___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2050#-NXMZA_I28bIi1QiT6Lk:-NXMZA_I28bIi1QiT6Ll:bx5galf) ([raw file](https://github.com/google/nomulus/blob/2c35d9efa4081241cb2f405979a5f2068b4d44a9/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L55)):*
> ```Java
>   public void run() {
>     User user = authResult.userAuthInfo().get().consoleUser().get();
>     if (!user.getUserRoles().hasGlobalPermission(ConsolePermission.MANAGE_REGISTRARS)) {
> ```

@gbrodman  Based on the hierarchy this seems like the best permission to use here, please confirm
___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 61 at r1](https://reviewable.io/reviews/google/nomulus/2050#-NXMZKU15YDt2pVySwLZ:-NXMZKU15YDt2pVySwL_:b-ggkgj6) ([raw file](https://github.com/google/nomulus/blob/2c35d9efa4081241cb2f405979a5f2068b4d44a9/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L61)):*
> ```Java
>     ImmutableList<String> registrarIds =
>         Streams.stream(Registrar.loadAllCached())
>             .filter(r -> r.isLive() && r.getType() == Registrar.Type.REAL)
> ```

@gbrodman  I'm not exactly sure if we want to filter them or not, but I thought that chances are we likely want, so I've added it (and test) for now

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2050)* status: all files reviewed, 7 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 37 at r1](https://reviewable.io/reviews/google/nomulus/2050#-NXMZ0UoBpy3YEsMfNfW:-NXRxK8z2gQm3koRUUWv:b80nh3z) ([raw file](https://github.com/google/nomulus/blob/2c35d9efa4081241cb2f405979a5f2068b4d44a9/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L37)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

@gbrodman  I think this one is correct auth here, please confirm
</blockquote></details>

i think we want AUTH_PUBLIC_LOGGED_IN 

I don't think we expect any INTERNAL / APP auth here and we should get rid of the UserPolicy in a general auth refactor once we move away from AppEngine 

in general this won't matter so much I think as long as we force a user login because we have the extra authorization checks 
___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2050#-NXMZA_I28bIi1QiT6Lk:-NXVnpF86yYH3fh_Fn6M:b-5lzcn1) ([raw file](https://github.com/google/nomulus/blob/2c35d9efa4081241cb2f405979a5f2068b4d44a9/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L55)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

@gbrodman  Based on the hierarchy this seems like the best permission to use here, please confirm
</blockquote></details>

talked it over with M+B and I think we might want to add an additional permission for basically just viewing all registrars, since it seems like the support agents don't (and shouldn't) have the permission to manage all registrars. Would you want to add that permission in this PR (giving it to SUPPORT_AGENTs and no registrar-based entities) or do that in a separate PR? 
___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 61 at r1](https://reviewable.io/reviews/google/nomulus/2050#-NXMZKU15YDt2pVySwLZ:-NXVoCHk7w172urgrMuo:b-u7ruaz) ([raw file](https://github.com/google/nomulus/blob/2c35d9efa4081241cb2f405979a5f2068b4d44a9/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L61)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

@gbrodman  I'm not exactly sure if we want to filter them or not, but I thought that chances are we likely want, so I've added it (and test) for now
</blockquote></details>

yeah I think we probably only want REAL registrars

I'm thinking we probably don't want the `isLive` filter because maybe we might want to have support agents manage registrars that are pending, disabled, etc. 
___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 65 at r3](https://reviewable.io/reviews/google/nomulus/2050#-NXVo_1-Bw9nXbF-RRh2:-NXVo_1-Bw9nXbF-RRh3:b-qt63z5) ([raw file](https://github.com/google/nomulus/blob/a4baeed84928a2964b25971188868187ae43e0b3/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L65)):*
> ```Java
>             .collect(ImmutableList.toImmutableList());
> 
>     response.setPayload(gson.toJson(registrarIds));
> ```

yeah I suppose we can wait to add more info until we're sure exactly what type of "here's a list of registrars!" we want to display on the front end, makes sense
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2050#gh-1222136869:-NXVonH59xHWrMv65Hvs:btts0ur) ([raw file](https://github.com/google/nomulus/blob/2c35d9efa4081241cb2f405979a5f2068b4d44a9/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L43)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: RegistrarsActionTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1505)
</blockquote></details>

booooooooooo non-useful suggestions
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 51 at r3](https://reviewable.io/reviews/google/nomulus/2050#-NXVp2-oBUKUh3vkQGXd:-NXVp2-oBUKUh3vkQGXe:bat2emp) ([raw file](https://github.com/google/nomulus/blob/a4baeed84928a2964b25971188868187ae43e0b3/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L51)):*
> ```Java
>   @BeforeEach
>   void setUp() {
>     RESPONSE = new FakeResponse();
> ```

if we're re-creating the action for every test let's just have a non-static response, then we can inline the creation and don't need a BeforeEach

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2050)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2050#-NXMZA_I28bIi1QiT6Lk:-NXWCmqW1D_GaddzdNqh:bsv74em) ([raw file](https://github.com/google/nomulus/blob/2c35d9efa4081241cb2f405979a5f2068b4d44a9/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L55)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

talked it over with M+B and I think we might want to add an additional permission for basically just viewing all registrars, since it seems like the support agents don't (and shouldn't) have the permission to manage all registrars. Would you want to add that permission in this PR (giving it to SUPPORT_AGENTs and no registrar-based entities) or do that in a separate PR? 
</blockquote></details>

Added in this PR
___
*[`core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java` line 65 at r3](https://reviewable.io/reviews/google/nomulus/2050#-NXVo_1-Bw9nXbF-RRh2:-NXWD4mjA5q5isHF7ZLj:b2nhswv) ([raw file](https://github.com/google/nomulus/blob/a4baeed84928a2964b25971188868187ae43e0b3/core/src/main/java/google/registry/ui/server/console/RegistrarsAction.java#L65)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah I suppose we can wait to add more info until we're sure exactly what type of "here's a list of registrars!" we want to display on the front end, makes sense
</blockquote></details>

Yep
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2050#gh-1222136869:-NXWD_TtElYx9CMujKJI:b2u8nut) ([raw file](https://github.com/google/nomulus/blob/2c35d9efa4081241cb2f405979a5f2068b4d44a9/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L43)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

booooooooooo non-useful suggestions
</blockquote></details>

☹️ 
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 39 at r2](https://reviewable.io/reviews/google/nomulus/2050#gh-1223490342:-NXWDywZ6FLia00-4jc1:b-896fix) ([raw file](https://github.com/google/nomulus/blob/3742c5b206579c876029453cb12bb971e48a241d/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L39)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: RegistrarsActionTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1506)
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 40 at r3](https://reviewable.io/reviews/google/nomulus/2050#gh-1223521993:-NXWDylq5utZY0r8WTe8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/a4baeed84928a2964b25971188868187ae43e0b3/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L40)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: RegistrarsActionTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1507)
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 51 at r3](https://reviewable.io/reviews/google/nomulus/2050#-NXVp2-oBUKUh3vkQGXd:-NXWHgkG34CvrkC-h6qW:b-896fix) ([raw file](https://github.com/google/nomulus/blob/a4baeed84928a2964b25971188868187ae43e0b3/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L51)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

if we're re-creating the action for every test let's just have a non-static response, then we can inline the creation and don't need a BeforeEach
</blockquote></details>

Done.

**Review by gbrodman — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2050)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

**Review by Valecia2023 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2050)* status: 5 of 8 files reviewed, 5 unresolved discussions

___
*[`console-webapp/src/app/settings/contact/contact.service.ts` line 34 at r5](https://reviewable.io/reviews/google/nomulus/2050#-NXsIKFo339eudcLGicF:-NXsIKFo339eudcLGicG:b-wyhccx) ([raw file](https://github.com/google/nomulus/blob/b248e00ac5f99a7ce010498ed55838078537e12b/console-webapp/src/app/settings/contact/contact.service.ts#L34)):*
> ```XML
>   providedIn: 'root',
> })
> export class ContactService {
> ```

https://buy.stripe.com/28odUteLubNI6OYeUV

**Pull request merged**
