### PR TITLE
Sync the live folder after Nomulus rollback

### PR DESCRIPTION
**Pull request by weiminyu**
To update the nomulus tool on corp desktop, the artifacts from the
rollback target release should be copied to the 'live' folder.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/854)

### CODE REVIEW

**Review by mindhog — COMMENTED** [review]
Is there a test to update?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/854#-:-MKpZTgB4VBn13GHpqq0:b1ery5v)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by weiminyu — COMMENTED** [review]
I tested the whole process in crash.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/854#-:-MKplY_--x6YVOiiqM7P:b3wqyro)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mindhog — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/854#-:-MKpmALW8TY2CA8FWOB-:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by weiminyu — COMMENTED** [review]
Thanks for asking. There is a test that needs fix.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/854#-:-MKpmzuG67lGkMoEFvAd:b-v46chw)* status: 2 of 3 files reviewed, all discussions resolved

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/854)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
