### PR TITLE
Make ExportDomainListsAction SQL-aware

### PR DESCRIPTION
**Pull request by jianglai**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1195)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1195#-MbapnrGC2Yq03b3E7Y4:-MbapnrGC2Yq03b3E7Y5:b-jertp9) ([raw file](https://github.com/google/nomulus/blob/9ff8fd10013df165064ce3097d0348f6888e5328/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L104)):*
> ```Java
>           .sendLinkToMapreduceConsole(response);
>     } else {
>       ImmutableListMultimap.Builder<String, String> tldToDomainsMapBuilder =
> ```

nit: should probably be "tldToDomainMapBuilder" (singular)
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 110 at r1](https://reviewable.io/reviews/google/nomulus/1195#-MbaqCCa23bAtCYV0aLm:-MbaqCCa23bAtCYV0aLn:b3uztb4) ([raw file](https://github.com/google/nomulus/blob/9ff8fd10013df165064ce3097d0348f6888e5328/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L110)):*
> ```Java
>                   jpaTm()
>                       .getEntityManager()
>                       .createNativeQuery(
> ```

LoL I just got done replacing all of these :-).  Please use jpaTm().query() instead (it doesn't matter in this case, since there are no model objects that need to be detached in the result, but it will be a lot easier to verify that we don't have to worry about detaching if we just consistently use our wrapper functions).
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 126 at r1](https://reviewable.io/reviews/google/nomulus/1195#-MbarIz6Di8U_1G2D56b:-MbarIz6Di8U_1G2D56c:b-nlr5ha) ([raw file](https://github.com/google/nomulus/blob/9ff8fd10013df165064ce3097d0348f6888e5328/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L126)):*
> ```Java
>                             tldToDomainsMapBuilder.put(tld, domain);
>                           }));
>       ImmutableListMultimap<String, String> tldToDomainsMap =
> ```

same nit here.

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @jianglai, and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 110 at r1](https://reviewable.io/reviews/google/nomulus/1195#-MbaqCCa23bAtCYV0aLm:-Mbbyeju3e5eh5RwqGNS:b-gykoze) ([raw file](https://github.com/google/nomulus/blob/9ff8fd10013df165064ce3097d0348f6888e5328/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L110)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Will it work? This is a native query and would never return an entity anyway. I don't think anything returned by a native query would be registered with the entity manager and therefore needs detaching. `jpaTm().query()` uses JPQL, not native SQL, right?
</blockquote></details>

Yes, it is JPQL.  Is there a reason you can't use JPQL for this?  I believe the only difference is that you can omit the annoying double-quotes from "Domain".

Yes, detaching is not necessary here.  Avoiding the underlying call just makes it easier to verify that we're definitely doing it correctly.  We might also want to remove getEntityManager() just as a form of verification.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 110 at r1](https://reviewable.io/reviews/google/nomulus/1195#-MbaqCCa23bAtCYV0aLm:-Mbd5J34537FzNLxSMWj:brn1cfj) ([raw file](https://github.com/google/nomulus/blob/9ff8fd10013df165064ce3097d0348f6888e5328/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L110)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Yes, it is JPQL.  Is there a reason you can't use JPQL for this?  I believe the only difference is that you can omit the annoying double-quotes from "Domain".

Yes, detaching is not necessary here.  Avoiding the underlying call just makes it easier to verify that we're definitely doing it correctly.  We might also want to remove getEntityManager() just as a form of verification.
</blockquote></details>

I think removing `getEntityManager()` is probably the better way of doing things. That way we are sure that we are calling our implementation of `createNativeQuery`. Maybe we don't need to expose the the entity manager at all to the user?

The reason why I used native query is because `creationDate` is a wrapper around `DateTime` and I am having trouble comparing it to `now`. Even though it is saved as a `timestamp_z`, with JPQL we are not dealing with columns directly, but Java fields (so 'creationDate` rather than `creation_date`), and I haven't found a way to set `now` to a value that JPQL thinks is comparable with `creationDate`. Do you have any suggestions?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 110 at r1](https://reviewable.io/reviews/google/nomulus/1195#-MbaqCCa23bAtCYV0aLm:-MbdRkRU3aFcxSPFnrps:b-5i6vtq) ([raw file](https://github.com/google/nomulus/blob/9ff8fd10013df165064ce3097d0348f6888e5328/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L110)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I think removing `getEntityManager()` is probably the better way of doing things. That way we are sure that we are calling our implementation of `createNativeQuery`. Maybe we don't need to expose the the entity manager at all to the user?

The reason why I used native query is because `creationDate` is a wrapper around `DateTime` and I am having trouble comparing it to `now`. Even though it is saved as a `timestamp_z`, with JPQL we are not dealing with columns directly, but Java fields (so 'creationDate` rather than `creation_date`), and I haven't found a way to set `now` to a value that JPQL thinks is comparable with `creationDate`. Do you have any suggestions?
</blockquote></details>

Hmm, actually I got JPQL to work. It looks like I have to convert the `DateTime` to a `CreateAutoTimestamp` when setting the parameters to pass validation. This kinda make sense because JPQL is trying to be smart and is comparing the Java type instead of the SQL type. But on the other hand it is misleading because you can see that the `:now` substitution is used to compare both `creationDate` and `deletionDate`, the latter of which is just a plain old `DateTime`. So the validation appears to be only getting the *first* bound type in the SQL statement when comparing the substituted type. In the end this is just validation, the Java types are converted to SQL types in constructing the actual query to run against the DB, so it works out OK as both `creationDate` and `deletionDate` are persisted as `timestamp_z`.

In fact after I swap the SQL statement to put `deletionDate` before `creationDate`, I don't have to convert the `DateTime` to `CreateAutoTimestamp` at all!

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @jianglai, and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 110 at r1](https://reviewable.io/reviews/google/nomulus/1195#-MbaqCCa23bAtCYV0aLm:-MbfYs2m11IDWDO9k8vC:b-da8fo7) ([raw file](https://github.com/google/nomulus/blob/9ff8fd10013df165064ce3097d0348f6888e5328/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L110)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Hmm, actually I got JPQL to work. It looks like I have to convert the `DateTime` to a `CreateAutoTimestamp` when setting the parameters to pass validation. This kinda make sense because JPQL is trying to be smart and is comparing the Java type instead of the SQL type. But on the other hand it is misleading because you can see that the `:now` substitution is used to compare both `creationDate` and `deletionDate`, the latter of which is just a plain old `DateTime`. So the validation appears to be only getting the *first* bound type in the SQL statement when comparing the substituted type. In the end this is just validation, the Java types are converted to SQL types in constructing the actual query to run against the DB, so it works out OK as both `creationDate` and `deletionDate` are persisted as `timestamp_z`.

In fact after I swap the SQL statement to put `deletionDate` before `creationDate`, I don't have to convert the `DateTime` to `CreateAutoTimestamp` at all!
</blockquote></details>

That's seriously weird -- sorry to have lead you down that path!

Can you add a comment explaining that the field order is significant? That's the kind of thing that a maintainer needs to know :-)

**Review by mindhog — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

**Review by mindhog — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195#-:-Mbg2gXC3Ya5p_FkiCHK:bb6ywmx)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: all files reviewed, 8 unresolved discussions (waiting on @jianglai and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 105 at r4](https://reviewable.io/reviews/google/nomulus/1195#-Mbghtt45kxKxm_t1vQ-:-Mbghtt45kxKxm_t1vQ0:b-972hxe) ([raw file](https://github.com/google/nomulus/blob/1bb398d0c632d7b5032e11abf2293f91e60829b0/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L105)):*
> ```Java
>           .sendLinkToMapreduceConsole(response);
>     } else {
>       ImmutableListMultimap.Builder<String, String> tldToDomainMapBuilder =
> ```

The `run()` function is too long now -- separate the Cloud SQL part out into a separate method.  Might want multiple helpers owing to length + indentation level. 
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 106 at r4](https://reviewable.io/reviews/google/nomulus/1195#-MbgiuH-9FREJH8DAtN0:-MbgiuH-9FREJH8DAtN1:b-at0h8m) ([raw file](https://github.com/google/nomulus/blob/1bb398d0c632d7b5032e11abf2293f91e60829b0/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L106)):*
> ```Java
>     } else {
>       ImmutableListMultimap.Builder<String, String> tldToDomainMapBuilder =
>           new ImmutableListMultimap.Builder<>();
> ```

Worth calling out that, with this approach, you are loading all domain names (and their TLDs) into memory simultaneously, 2x (you're also storing a sorted copy separately).  This should work at our current scale, but it's not completely futureproof.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 123 at r4](https://reviewable.io/reviews/google/nomulus/1195#-MbgiKrV-0mFLL25L82N:-MbgiKrV-0mFLL25L82O:be32dk4) ([raw file](https://github.com/google/nomulus/blob/1bb398d0c632d7b5032e11abf2293f91e60829b0/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L123)):*
> ```Java
>                 // substituted value.
>                 @SuppressWarnings("unchecked")
>                 Stream<Object[]> stream =
> ```

Why is this such a weak type?  You're getting strings, right?
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 134 at r4](https://reviewable.io/reviews/google/nomulus/1195#-MbgiXgO9SXpV6w6VVE5:-MbgiXgO9SXpV6w6VVE6:bw4uyls) ([raw file](https://github.com/google/nomulus/blob/1bb398d0c632d7b5032e11abf2293f91e60829b0/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L134)):*
> ```Java
>                             .setParameter("now", clock.nowUtc())
>                             .getResultStream();
>                 stream.forEach(
> ```

Is this maximally efficient?  Is batching being handled under the covers by Hibernate, and if so, what does that look like?  What is the batch size?
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 137 at r4](https://reviewable.io/reviews/google/nomulus/1195#-MbgiT_E5ZlHvttb-iOG:-MbgiT_E5ZlHvttb-iOH:bqvocnj) ([raw file](https://github.com/google/nomulus/blob/1bb398d0c632d7b5032e11abf2293f91e60829b0/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L137)):*
> ```Java
>                     row -> {
>                       @SuppressWarnings("unchecked")
>                       String tld = (String) ((Object[]) row)[0];
> ```

No way to get the correct String type out to begin with?
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 144 at r4](https://reviewable.io/reviews/google/nomulus/1195#-MbgjC8o7YR3U6UMOtz0:-MbgjC8o7YR3U6UMOtz1:b-gesc39) ([raw file](https://github.com/google/nomulus/blob/1bb398d0c632d7b5032e11abf2293f91e60829b0/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L144)):*
> ```Java
>               });
>       ImmutableListMultimap<String, String> tldToDomainMap =
>           tldToDomainMapBuilder.orderValuesBy(Ordering.natural()).build();
> ```

Would it be more efficient to maintain the list in sorted order to begin with than to sort it all at the end here like this?  It seems like this approach might use roughly 2X the memory.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 152 at r4](https://reviewable.io/reviews/google/nomulus/1195#-MbgjQ2Y5-MLTmfjN4pF:-MbgjQ2Y5-MLTmfjN4pG:b-cohg7e) ([raw file](https://github.com/google/nomulus/blob/1bb398d0c632d7b5032e11abf2293f91e60829b0/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L152)):*
> ```Java
>                 logger.atInfo().log(
>                     "Exporting %d domains for TLD %s to GCS and Drive.", domains.size(), tld);
>                 exportToGcs(tld, domainsList, gcsBucket, gcsBufferSize);
> ```

There seems to be some missing error handling here.  What errors do these `export...()` methods throw?  They're talking to external systems, so they can definitely fail.  As currently written, if the GCS export fails then the Drive export is not even attempted.  That seems wrong.  The two exports should have the chance of succeeding independently, no?

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: all files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @jianglai, and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 115 at r5](https://reviewable.io/reviews/google/nomulus/1195#-MbksM7T6ZHJYIvk8-I_:-MbksM7U6EjCTNGTB78v:b-e2g5cu) ([raw file](https://github.com/google/nomulus/blob/14cf4bc5e67042aad171679af55d3d70044ee49d/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L115)):*
> ```Java
>                             // (click.nowUtc()). Since creationTime is a CreateAutoTimestamp, if it
>                             // comes first, we will need to substitute "now" with
>                             // CreateAutoTimestamp.creat(clock.nowUtc()). This might look a bit
> ```

`.create(` -- (missing an "e")

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @jianglai, and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 106 at r4](https://reviewable.io/reviews/google/nomulus/1195#-MbgiuH-9FREJH8DAtN0:-MblO0iwAUtR_IjjYJAr:bwpi9u2) ([raw file](https://github.com/google/nomulus/blob/1bb398d0c632d7b5032e11abf2293f91e60829b0/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L106)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I've thought about this. The alternative is that since we already have the real TLD list we can query one TLD at a time (we don't have to get the real TLD separately if we only work in SQL -- we can just join the domain table with the tld table and filter on TLD type, but it is already available anyway).

This would reduce the memory requirement to hold all domains in one TLD instead of all TLDs. Sort of trading time for space as we have to run SQL multiple times. The reducer is also working at this level of memory requirement. It's a background job so I guess time is not critical so the trade off is probably worth it to guard against OOM down the road if we become too successful :P It also makes the processing downstream much easier as we don't have to keep a map anymore.
</blockquote></details>

I like this new approach.  It's simpler and less memory-intensive, and running separate queries by a single short indexed string column can't be that much more expensive on the DB than running a single query over all.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 129 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblMZxn0-fjICD-rP4b:-MblMZxn0-fjICD-rP4c:brtxgom) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L129)):*
> ```Java
>                                         + "WHERE tld = :tld "
>                                         + "AND deletionTime > :now "
>                                         + "ORDER by fullyQualifiedDomainName ASC",
> ```

Note that this doesn't actually do the right thing, e.g.:

```
// Raw string sorted order, as in your current query:
appz.dev
appmm.dev

// Sorted correctly by label:
appmm.dev
appz.dev
```

(Because period comes in the ASCII table than letters do.)

The simplest way I can think of to sort this correctly is to, in SQL, strip off the TLD part (should be very easy) and then sort just on the domain label.  Then, in Java land, you can append back on the TLD when writing to file.

Alternatively, we could just give up and not do this, as it seems like the Datastore implementation is already incorrectly sorting them, and frankly it's not thaaaat important that the contents of this file be sorted in a truly correct manner.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @CydeWeys, @jianglai, and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 138 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblOY79-0qBN3p0DvHh:-MblOY79-0qBN3p0DvHi:b-g709iw) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L138)):*
> ```Java
>                 "Exporting %d domains for TLD %s to GCS and Drive.", domains.size(), tld);
>             exportToGcs(tld, domainsList, gcsBucket, gcsBufferSize);
>             logger.atInfo().log("domain lists for TLD %s written out to GCS", tld);
> ```

Missing capitalization and a period, but also, I think it reads better in a move active voice, e.g.:

"Successfully wrote domain lists for TLD %s to GCS."
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 138 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblPWwS9Yn6q2nZBK9e:-MblPWwS9Yn6q2nZBK9f:brjjse9) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L138)):*
> ```Java
>                 "Exporting %d domains for TLD %s to GCS and Drive.", domains.size(), tld);
>             exportToGcs(tld, domainsList, gcsBucket, gcsBufferSize);
>             logger.atInfo().log("domain lists for TLD %s written out to GCS", tld);
> ```

This isn't correct, because the helper function itself can fail, but it's not rethrowing on failure, so this logging statement will run even on failure.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 140 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblOoTE6ls5j_Ybfwks:-MblOoTE6ls5j_Ybfwkt:b-21tyrs) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L140)):*
> ```Java
>             logger.atInfo().log("domain lists for TLD %s written out to GCS", tld);
>             exportToDrive(tld, domainsList, driveConnection);
>             logger.atInfo().log("domain lists for TLD %s written out to Drive", tld);
> ```

Ditto on the exact logged message and incorrectly logging success even when a failure has occurred.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 146 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblOPLwD__2zmtxhr5_:-MblOPLwD__2zmtxhr5a:b-ctkv96) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L146)):*
> ```Java
> 
>   protected static void exportToDrive(String tld, String domains, DriveConnection driveConnection) {
>     verifyNotNull(driveConnection, "expecting non-null driveConnection");
> ```

Should be "Expecting"
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 161 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblPADECvMxrEc6bMZv:-MblPADECvMxrEc6bMZw:b6vkss7) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L161)):*
> ```Java
>                 domains.getBytes(UTF_8));
>         logger.atInfo().log(
>             "Exporting registered domains succeeded for TLD %s, response was: %s", tld, resultMsg);
> ```

Isn't this a double log statement?  It seems to me it's duplicative of the logging statement in `run()` above.  Either log success inside the helper function or at the callsite, but not in both places.  Since you want to log the result message as well, logging within the helper function probably makes the most sense.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 179 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblOva05GW_IoLCpYG9:-MblOva05GW_IoLCpYGA:b-p1tqpt) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L179)):*
> ```Java
>     } catch (IOException e) {
>       logger.atSevere().withCause(e).log(
>           "Error exporting registered domains for TLD %s to GCS.", tld);
> ```

I know this is a pre-existing error message, but it can be improved upon while we're here making changes. It doesn't say what happens after the error.  The following is better:

"Error exporting registered domains for TLD %s to GCS; skipping."

Same for export to Drive above.

**Review by CydeWeys — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: 1 of 2 files reviewed, 12 unresolved discussions (waiting on @CydeWeys, @jianglai, and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 241 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblPlW65gKFFsXfDpKJ:-MblPlW65gKFFsXfDpKK:bn9qufm) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L241)):*
> ```Java
>       logger.atInfo().log("Exporting %d domains for TLD %s to GCS and Drive.", domains.size(), tld);
>       exportToGcs(tld, domainsList, gcsBucket, gcsBufferSize);
>       getContext().incrementCounter("domain lists written out to GCS");
> ```

These two counters are incorrectly incremented even on failures.  To do this correctly you'd want these two export functions to return success/failure booleans, and then increment a counter appropriately, e.g.:

```
boolean successGcs = exportToGcs(tld, domainsList, gcsBucket, gcsBufferSize);
getContext().incrementCounter(String.format("domain lists %s to GCS", successGcs ? "successfully written" : "that failed to write to"));
```
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 243 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblQEaC1jTQyceGOjQi:-MblQEaC1jTQyceGOjQj:b90rs1z) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L243)):*
> ```Java
>       getContext().incrementCounter("domain lists written out to GCS");
>       exportToDrive(tld, domainsList, driveConnection);
>       getContext().incrementCounter("domain lists written out to Drive");
> ```

Same comments here.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: 1 of 2 files reviewed, 12 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 115 at r5](https://reviewable.io/reviews/google/nomulus/1195#-MbksM7T6ZHJYIvk8-I_:-MbmUoGf-4WH7DZiD7ZV:b-896fix) ([raw file](https://github.com/google/nomulus/blob/14cf4bc5e67042aad171679af55d3d70044ee49d/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L115)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

`.create(` -- (missing an "e")
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 129 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblMZxn0-fjICD-rP4b:-MbmXHPGDmqaW3t9OuvE:berj8db) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L129)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Note that this doesn't actually do the right thing, e.g.:

```
// Raw string sorted order, as in your current query:
appz.dev
appmm.dev

// Sorted correctly by label:
appmm.dev
appz.dev
```

(Because period comes in the ASCII table than letters do.)

The simplest way I can think of to sort this correctly is to, in SQL, strip off the TLD part (should be very easy) and then sort just on the domain label.  Then, in Java land, you can append back on the TLD when writing to file.

Alternatively, we could just give up and not do this, as it seems like the Datastore implementation is already incorrectly sorting them, and frankly it's not thaaaat important that the contents of this file be sorted in a truly correct manner.
</blockquote></details>

I think you mean period comes **before** letters? Your comment is missing a crucial word. Doesn't that work in our favor as when you compare period with a letter it always comes first? so "abc.dev" vs "abcd.dev" will compare "." with "d" and place the former before the latter, which is what we want, right?

Also in your example the order is decided when you compare the fourth character "z" vs. "m", right? It has nothing to do with the dot.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 138 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblOY79-0qBN3p0DvHh:-MbmYunnE3sI4OUEuuV9:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L138)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Missing capitalization and a period, but also, I think it reads better in a move active voice, e.g.:

"Successfully wrote domain lists for TLD %s to GCS."
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 138 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblPWwS9Yn6q2nZBK9e:-MbmZIvH4NQdm3Qkyp2z:b6zrrkh) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L138)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This isn't correct, because the helper function itself can fail, but it's not rethrowing on failure, so this logging statement will run even on failure.
</blockquote></details>

Good catch.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 140 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblOoTE6ls5j_Ybfwks:-MbmZKik5VkYb5SOSOfX:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L140)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto on the exact logged message and incorrectly logging success even when a failure has occurred.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 146 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblOPLwD__2zmtxhr5_:-MbmZNzV8QJx2fX5ShK_:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L146)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should be "Expecting"
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 161 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblPADECvMxrEc6bMZv:-MbmZXTC8BT7J47Om1Zs:b43iprh) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L161)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Isn't this a double log statement?  It seems to me it's duplicative of the logging statement in `run()` above.  Either log success inside the helper function or at the callsite, but not in both places.  Since you want to log the result message as well, logging within the helper function probably makes the most sense.
</blockquote></details>

You are right, I was just blinding converting the `getContext()` calls to logs without realizing that they are redundant.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 179 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblOva05GW_IoLCpYG9:-MbnKwiNCoNc-wF9TUsn:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L179)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I know this is a pre-existing error message, but it can be improved upon while we're here making changes. It doesn't say what happens after the error.  The following is better:

"Error exporting registered domains for TLD %s to GCS; skipping."

Same for export to Drive above.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 241 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblPlW65gKFFsXfDpKJ:-MbnTMbr-bpDUFoGwuEz:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L241)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These two counters are incorrectly incremented even on failures.  To do this correctly you'd want these two export functions to return success/failure booleans, and then increment a counter appropriately, e.g.:

```
boolean successGcs = exportToGcs(tld, domainsList, gcsBucket, gcsBufferSize);
getContext().incrementCounter(String.format("domain lists %s to GCS", successGcs ? "successfully written" : "that failed to write to"));
```
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/export/ExportDomainListsAction.java, line 243 at r6](https://reviewable.io/reviews/google/nomulus/1195#-MblQEaC1jTQyceGOjQi:-MbnTMrL8dXklq8pFijG:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7b491d2fa572d3ce6412fbf3387cb3db6249f807/core/src/main/java/google/registry/export/ExportDomainListsAction.java#L243)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Same comments here.
</blockquote></details>

Done.

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: all files reviewed, 10 unresolved discussions (waiting on @CydeWeys)

**Review by jianglai — COMMENTED** [review]
> Dismissed @CydeWeys from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1195)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @CydeWeys and @mindhog)

**Pull request merged**
