### PR TITLE
Replace all existing vkey string to vkey.stringify() 

### PR DESCRIPTION
**Pull request by rachelguan**
This purpose of this PR is to replace all existing vkey strings with new vkey string representation strings created by stringify(). We need to make sure that the vkey strings from task queue (which are stringified) can be used to re-create the vkey successfully. 

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1430)

### CODE REVIEW

**Review by mindhog — APPROVED** [review]
No issues here, just be aware that we can't commit this until the PR that converts reads is safely rolled out.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1430#-:-MphMO1g2CiFFc1v_8D6:b2bdtv1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachelguan)

**Review by mindhog — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1430)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachelguan)

**Review by mindhog — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1430)* status: all files reviewed, 1 unresolved discussion (waiting on @rachelguan)

___
*[core/src/main/java/google/registry/model/index/EppResourceIndex.java, line 68 at r3](https://reviewable.io/reviews/google/nomulus/1430#-MrYMAh55FUaeStByzHo:-MrYMAh55FUaeStByzHp:b-femoq2) ([raw file](https://github.com/google/nomulus/blob/e539f8896daa982288fba96d160a69bfa62cb95a/core/src/main/java/google/registry/model/index/EppResourceIndex.java#L68)):*
> ```Java
>     instance.reference = resourceKey;
>     instance.kind = resourceKey.getKind();
>     // creates a web-safe key string, this value has never been used
> ```

"is not used"?

Also, ideally, if this isn't used we should remove it from the code (you don't need to do that here, but a TODO would be nice)

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1430)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/index/EppResourceIndex.java, line 68 at r3](https://reviewable.io/reviews/google/nomulus/1430#-MrYMAh55FUaeStByzHo:-MrYkKyZEgU6zm8Bjt5y:b-rnrapz) ([raw file](https://github.com/google/nomulus/blob/e539f8896daa982288fba96d160a69bfa62cb95a/core/src/main/java/google/registry/model/index/EppResourceIndex.java#L68)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

"is not used"?

Also, ideally, if this isn't used we should remove it from the code (you don't need to do that here, but a TODO would be nice)
</blockquote></details>

done.

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1430)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachelguan)

**Review by mindhog — APPROVED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1430)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachelguan)

**Pull request merged**
