### PR TITLE
Add console backend for EPP password change

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2396)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2396)* status: all files reviewed, 4 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 81 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3pfEu4kspDUYTIBS4:-Nv3pfEu4kspDUYTIBS5:bt6x6jb) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L81)):*
> ```Java
>         extractOptionalParameter(consoleApiParams.request(), "newPasswordRepeat");
> 
>     if (Stream.of(oldPassword, newPassword, newPasswordRepeat, registrarId)
> ```

can't we just use extractRequiredParameter? means we can avoid all the optionals
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 96 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3q_neBW5UCF_829N4:-Nv3q_neBW5UCF_829N5:b-oasvi) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L96)):*
> ```Java
>       registrar = registrarAccessor.getRegistrar(registrarId.get());
>     } catch (RegistrarAccessDeniedException e) {
>       setFailedResponse(e.getMessage(), HttpStatusCodes.STATUS_CODE_FORBIDDEN);
> ```

bit of a nit, but we probably want a 404 here instead of FORBIDDEN 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 101 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3pE6DBIQOh1ELItCI:-Nv3pE6DBIQOh1ELItCJ:bvsk45i) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L101)):*
> ```Java
> 
>     try {
>       credentials.validate(registrar, oldPassword.get());
> ```

Do we need to actually use the TransportCredentials? We should be able to just directly call `registrar.verifyPassword` 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 127 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3r3p6-7ECHslMa1S0:-Nv3r3p6-7ECHslMa1S1:bxq3jf6) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L127)):*
> ```Java
>   }
> 
>   private void setFailedResponse(String message, int code) {
> ```

should we put this in the ConsoleApiAction base class?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2396)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 81 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3pfEu4kspDUYTIBS4:-Nv8hZJiBHK3mCiiGW2Y:b-y3141l) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L81)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can't we just use extractRequiredParameter? means we can avoid all the optionals
</blockquote></details>

Yeah, makes sense
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 96 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3q_neBW5UCF_829N4:-Nv8h_ey3hUQP-g0Ei6J:b-896fix) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L96)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

bit of a nit, but we probably want a 404 here instead of FORBIDDEN
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 101 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3pE6DBIQOh1ELItCI:-Nv8h_xYDuXS_GrW9hqv:b-nvu306) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L101)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Do we need to actually use the TransportCredentials? We should be able to just directly call `registrar.verifyPassword`
</blockquote></details>

It basically just provides a nice clean error for me to handle and if verification process ever changes and signature of `registrar.verifyPassword` is changed I won't need to revisit this part. My guess that was the intention for `PasswordOnlyTransportCredentials` in the first place. If you feel stronly we better of calling `registrar.verifyPassword` I can update
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 127 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3r3p6-7ECHslMa1S0:-Nv8iQ_-9pyQNZcnQ5vU:b-896fix) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L127)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

should we put this in the ConsoleApiAction base class?
</blockquote></details>

Done.

**Review by gbrodman — CHANGES_REQUESTED** [review]
still failing tests, looks like

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2396#-:-NvDBsaQ43aEXNm5RuDD:bg5uqu7)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 101 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3pE6DBIQOh1ELItCI:-NvDBHLe237fdSzubwjQ:b33o3hc) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L101)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

It basically just provides a nice clean error for me to handle and if verification process ever changes and signature of `registrar.verifyPassword` is changed I won't need to revisit this part. My guess that was the intention for `PasswordOnlyTransportCredentials` in the first place. If you feel stronly we better of calling `registrar.verifyPassword` I can update
</blockquote></details>

I don't think it matters all that much either way. It looks like we have the class only so that we can inject a different credentials validator when running EPP commands from the command line versus those received from registrars (the latter also verifies IP addresses etc).

**Review by gbrodman — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2396)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

**Review by ptkach — COMMENTED** [review]
Updated again, not sure why the static import was messed up - I executed Idea's organize imports and jifa before submitting the last time. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2396#-:-NvrTs8R-3oNYG6H-sGM:b-6yzr22)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2396)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 101 at r1](https://reviewable.io/reviews/google/nomulus/2396#-Nv3pE6DBIQOh1ELItCI:-NvrU3_p17wiaA27EgNN:b-896fix) ([raw file](https://github.com/google/nomulus/blob/57b16f485308ec843d85a221dfed6acbc57b3657/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L101)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think it matters all that much either way. It looks like we have the class only so that we can inject a different credentials validator when running EPP commands from the command line versus those received from registrars (the latter also verifies IP addresses etc).
</blockquote></details>

Done.

**Review by gbrodman — COMMENTED** [review]
did you re-image your machine recently? I did and I had to again tell IDEA not to use wildcard imports 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2396#-:-NvrbeXQEF9NcgGsDMFz:b-rho27y)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2396#-:-Nvre_AI3F5YNGmHMkZm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
