### PR TITLE
Add login_email_address column to RegistrarPoc

### PR DESCRIPTION
**Pull request by jianglai**
This will replace the gae_user_id column to identify the registrar contact
when logging in the console.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1849)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1849)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1849)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1849)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman and @ptkach)

**Review by jianglai — COMMENTED** [review]
Ping. Hoping to get this in before next week's release.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1849#-:-NGcHLlZBQeVn-NNtDuT:bj62lgx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman and @ptkach)

**Review by gbrodman — APPROVED** [review]
yeah lgtm 

> Reviewed 1 of 7 files at r1, 4 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1849#-:-NGcKKQ-6Wz9KWEXzaAL:b-k4u4fw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys and @ptkach)

**Comment by jianglai** [comment]
Thanks!

**Pull request merged**
