### PR TITLE
Upgrade to Jakarta EE 10 Servlet

### PR DESCRIPTION
**Pull request by jianglai**
Upgrade to using Jakarta EE 10 from Java EE 8 by mostly following the [upgrade instructions](https://cloud.google.com/appengine/docs/standard/java-gen2/upgrade-java-runtime). Only the servlet package is upgrade. Other Jakarta EE components (like the persistence package that Hibernate depends on) need to be upgraded separately.

TESTED=deployed and successfully communicated with the pubapi endpoint for web WHOIS.

Note that this currently requires packaging the App Engine runtime per instructions [here](https://github.com/GoogleCloudPlatform/appengine-java-standard/blob/main/TRYLATESTBITSINPROD.md) due to https://github.com/GoogleCloudPlatform/appengine-java-standard/pull/98. This PR will only be merged when the fix is deployed to App Engine runtime. (https://rapid.corp.google.com/#/release/serverless_runtimes_run_java/java21_20240310_21_0).

Follow up: The fix has been deployed to App Engine and I've tested this PR without packing the App Engine runtime on alpha.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2362)

### CODE REVIEW

**Review by gbrodman — APPROVED** [review]
> Reviewed 188 of 207 files at r1, 7 of 19 files at r2, 13 of 13 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
