### PR TITLE
Set response payload when wiping out contact history PII

### PR DESCRIPTION
**Pull request by CydeWeys**
Also uses smaller batches in tests so that they don't take so long.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1376)

### CODE REVIEW

**Review by rachelguan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1376)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @rachelguan)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 89 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLoNYu0LVH4CBgRD__:-MlLoNYu0LVH4CBgRD_a:b-1khi4l) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L89)):*
> ```Java
>       String msg =
>           String.format(
>               "Done. Wiped out PII of %d ContactHistory entities in total.",
> ```

Adding "Done" makes it easier to understand that the the execution is complete but i think it would be nicer to combine two into one sentence.  
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 53 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLnYcp4lvIpBFTauOF:-MlLnYcq-D3F9wstcSk_:b-migwb8) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L53)):*
> ```Java
> 
>   private static final int TEST_BATCH_SIZE = 20;
>   private static final int MIN_MONTHS_BEFORE_WIPE_OUT = 18;
> ```

whats the reason behind changing the name to TEST_BATCH_SIZE if this is being used in a test file? 
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 240 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLp6GzEASGy8_1Zn77:-MlLp6GzEASGy8_1Zn78:br4rzt) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L240)):*
> ```Java
>     assertThat(response.getPayload())
>         .isEqualTo("Done. Wiped out PII of 56 ContactHistory entities in total.");
> ```

instead of writing a number explicitly, declare int numOfEntities = 56 and use string format to construct the message. that way it's clear where 56 comes from. 
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 277 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLpi9H3RwWiDRPQAZh:-MlLpi9I-_lSPsXiDBvC:b-4gbjm6) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L277)):*
> ```Java
>     assertThat(response.getPayload())
>         .isEqualTo("Done. Wiped out PII of 40 ContactHistory entities in total.");
> ```

same as above. make it easier to see where the number comes from.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1376)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @rachelguan)

___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 53 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLnYcp4lvIpBFTauOF:-MlMCcJWAgkp51P3US39:b-t5hkzo) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L53)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

whats the reason behind changing the name to TEST_BATCH_SIZE if this is being used in a test file? 
</blockquote></details>

It was confusing me (and I didn't realize it was separate from the `BATCH_SIZE` variable in the action itself because it shared a name). This way it's super clear it's the _test_ batch size, which is lower, rather than the normal batch size for the action.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 240 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLp6GzEASGy8_1Zn77:-MlMC5JD59bVf84sH7vN:bhrd87o) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L240)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

instead of writing a number explicitly, declare int numOfEntities = 56 and use string format to construct the message. that way it's clear where 56 comes from. 
</blockquote></details>

That'd be the right thing to do in production code, but in testing code you actually want as little logic as possible, using full raw strings (rather than using logic to build strings).  See https://engdoc.corp.google.com/eng/doc/devguide/testing/unit/best-practices.md?cl=head&polyglot=java#control-structures
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 277 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLpi9H3RwWiDRPQAZh:-MlMCoP2-pZCkABeAx30:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L277)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

same as above. make it easier to see where the number comes from. 
</blockquote></details>

Ditto.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1376)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @rachelguan)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 89 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLoNYu0LVH4CBgRD__:-MlMDkch-x1ASCSfcPI0:b-hta7le) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L89)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

Adding "Done" makes it easier to understand that the the execution is complete but i think it would be nicer to combine two into one sentence.  
</blockquote></details>

What's your preferred wording?  "Done." is a fine complete sentence as far as I'm concerned.
___
*[core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java, line 240 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLp6GzEASGy8_1Zn77:-MlMDhmQ3cMTuXAmuPMF:b-8vcjk4) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/test/java/google/registry/batch/WipeOutContactHistoryPiiActionTest.java#L240)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

That'd be the right thing to do in production code, but in testing code you actually want as little logic as possible, using full raw strings (rather than using logic to build strings).  See https://engdoc.corp.google.com/eng/doc/devguide/testing/unit/best-practices.md?cl=head&polyglot=java#control-structures
</blockquote></details>

Even better resource: http://go/tott/338

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1376)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @rachelguan)

___
*[core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java, line 89 at r1](https://reviewable.io/reviews/google/nomulus/1376#-MlLoNYu0LVH4CBgRD__:-MlMGJxP16Cm5_rhH4O2:brbebuz) ([raw file](https://github.com/google/nomulus/blob/0fea7ab0f1ef90bc82aadc60a22e5d1ae30f460f/core/src/main/java/google/registry/batch/WipeOutContactHistoryPiiAction.java#L89)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

i meant combining both into one sentence. 
</blockquote></details>

Yeah I understand that, but what is your preferred wording?  It could be "Done; wiped out ..."  But it's really two completely separate grammatical clauses, needing either a full stop or a semicolon between them.

**Pull request merged**
