### PR TITLE
Convert a bunch more @AutoValues to records

### PR DESCRIPTION
**Pull request by CydeWeys**
I think this is all the last low-hanging fruit.  All the remaining `@AutoValue`s are pretty complicated, using a lot of inheritance for behavior, that isn't really suitable for replacing with Java `record`s.  So we could either leave them as is, or remove `@AutoValue` and just have them be Javabeans/POJOs, but for now I'm touching them.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2412)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2412)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/monitoring/whitebox/EppMetric.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/2412#-NwGvDLW96nhhyqH76DY:-NwGvDLW96nhhyqH76DZ:b-vf5o4j) ([raw file](https://github.com/google/nomulus/blob/268a03b786131b23faa023ea81e781c7d2cdd297/core/src/main/java/google/registry/monitoring/whitebox/EppMetric.java#L54)):*
> ```Java
>   }
> 
>   public DateTime getStartTimestamp() {
> ```

annoying to have to redefine these, any chance it's worth refactoring to change the getters to just e.g. `startTimestamp()` ? 
___
*[`core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java` line 33 at r1](https://reviewable.io/reviews/google/nomulus/2412#-NwGurs5BVPEUJ0sk53d:-NwGurs5BVPEUJ0sk53e:b1oytup) ([raw file](https://github.com/google/nomulus/blob/268a03b786131b23faa023ea81e781c7d2cdd297/core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java#L33)):*
> ```Java
>   public String toString() {
>     // Use Object.toString(), which does not show the sensitive date in record fields.
>     return ((Object) this).toString();
> ```

wait does this actually work? I would expect this to infinite loop since we're not calling `super`?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2412)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`util/src/test/java/google/registry/util/EmailMessageTest.java` line 30 at r1](https://reviewable.io/reviews/google/nomulus/2412#-NwGvkFH8gxhK1I8n0M3:-NwGvkFH8gxhK1I8n0M4:b-96yl96) ([raw file](https://github.com/google/nomulus/blob/268a03b786131b23faa023ea81e781c7d2cdd297/util/src/test/java/google/registry/util/EmailMessageTest.java#L30)):*
> ```Java
>         EmailMessage.newBuilder()
>             .setSubject("Foo")
>             .setBody("We have been trying to reach you about your vehicle's extended warranty.")
> ```

hissssssssssssssssssssssssssssss

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2412)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/monitoring/whitebox/EppMetric.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/2412#-NwGvDLW96nhhyqH76DY:-NwGy5sM5A9G8a0QkwCQ:blxhhub) ([raw file](https://github.com/google/nomulus/blob/268a03b786131b23faa023ea81e781c7d2cdd297/core/src/main/java/google/registry/monitoring/whitebox/EppMetric.java#L54)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

annoying to have to redefine these, any chance it's worth refactoring to change the getters to just e.g. `startTimestamp()` ?
</blockquote></details>

I looked into doing it but it looked a little bit strange at the callsites (and required more refactoring overall).  I figured just having the getters on the record was easier.
___
*[`core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java` line 33 at r1](https://reviewable.io/reviews/google/nomulus/2412#-NwGurs5BVPEUJ0sk53d:-NwGyG7B4d0lyy3zKNrz:b-jm9o8e) ([raw file](https://github.com/google/nomulus/blob/268a03b786131b23faa023ea81e781c7d2cdd297/core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java#L33)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

wait does this actually work? I would expect this to infinite loop since we're not calling `super`?
</blockquote></details>

This calls the `Object.toString()` method which is defined as:

```
  public String toString() {
    return this.getClass().getName() + "@" + Integer.toHexString(this.hashCode());
  }
```

So, no recursion is involved.

Also note that you can't call `super` from within a `record`; it throws the error `Abstract method 'toString()' cannot be accessed directly`.

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2412)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java` line 33 at r1](https://reviewable.io/reviews/google/nomulus/2412#-NwGurs5BVPEUJ0sk53d:-NwH-cQg0jqzAdcWMvXD:b-261s0f) ([raw file](https://github.com/google/nomulus/blob/268a03b786131b23faa023ea81e781c7d2cdd297/core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java#L33)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This calls the `Object.toString()` method which is defined as:

```
  public String toString() {
    return this.getClass().getName() + "@" + Integer.toHexString(this.hashCode());
  }
```

So, no recursion is involved.

Also note that you can't call `super` from within a `record`; it throws the error `Abstract method 'toString()' cannot be accessed directly`.
</blockquote></details>

OK so I guess records are a special case with toString then, because yeah if this were a standard object the cast wouldn't do anything.

**Review by gbrodman — CHANGES_REQUESTED** [review]
wait did you test the toString for sure? 

i'm fairly certain this infinite-loops

**Review by gbrodman — CHANGES_REQUESTED** [review]
yeah it def does

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2412#-:-NwHH3xEAI2rBsPaSJ61:bvw3r1d)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by CydeWeys — COMMENTED** [review]
Fixed it, now with test.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2412#-:-NwKxS6j6naah3WQgs22:b78rjwc)* status: 34 of 36 files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2412)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by sahiix1 — APPROVED** [review]

**Pull request merged**
