### PR TITLE
Add RegistrationBehavior.NONPREMIUM_CREATE

### PR DESCRIPTION
**Pull request by gbrodman**
When using this token (which must be tied to a particular domain), the first year price (and only the first year price, i.e. the creation price) will be the standard price for this TLD. Future years (i.e. renewals) will continue at the normal premium price.

b/332928676, in part

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2481)

### CODE REVIEW

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2481)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java` line 3533 at r1](https://reviewable.io/reviews/google/nomulus/2481#gh-1640229935:-O-NUuGcC92PW8rhKPxY:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7278abfdbb1e66ff20ca5d5be43afb4794544bb7/core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java#L3533)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unread local variable

Variable 'AllocationToken token' is never read.

[Show more details](https://github.com/google/nomulus/security/code-scanning/11138)
</blockquote></details>

Done.

**Review by CydeWeys — COMMENTED** [review]
Hrm, so the way this would work, to execute a typical "this domain should always be standard priced", would be:

`nomulus -e ... generate_allocation_tokens --registration_behavior NONPREMIUM_CREATE --renewal_price_behavior NONPREMIUM -d ...`

It's a little wordy for such a common use case, but I can see how anything else requires more changes elsewhere.

I wonder if it would make sense to have a short-hand flag for `GenerateAllocationTokensCommand` that would set those two flags correctly?  `generate_allocation_tokens --standard_price`, something like that?  (And of course it would be an error to call that but also any of the other price-setting flags like the create/renew behavior or discount fraction.)   And then that would go into our playbook for creating internal domain names.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2481#-:-O-vqyCB9z3pTnSpbZ1O:b-ttr5sb)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Review by gbrodman — COMMENTED** [review]
Yes, that is how it would work. We are kind of somewhat decoupling the creation price from the renewal price as part of these changes to allow more flexible behavior. 

We could do that, though I'm not sure how often it'd be used. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2481#-:-O-w8nP-BysJSSk7koaX:bpnslp7)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2481#-:-O0G-91HD6o4nEgh-W00:bnfp4nl)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Pull request merged**
