### PR TITLE
Add resources widget front-end, enable settings widget navigation

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2151)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 9 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2151)* status: 13 of 18 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`console-webapp/src/app/home/widgets/contact-widget.component.html` line 16 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeieRcQ1ZVfodBTN0Hm:-NeieRcQ1ZVfodBTN0Hn:bv1ircz) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/contact-widget.component.html#L16)):*
> ```HTML
>         </button>
>         <p class="secondary-text">
>           Call Google Registry support at <b>+1 (404) 978 8419</b>
> ```

won't be in this PR, just flagging that we'll want to make this configurable as well 
___
*[`console-webapp/src/app/home/widgets/resources-widget.component.html` line 6 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeiemEg-XrTpdNUAh7g:-NeiemEg-XrTpdNUAh7h:b-fyvmo6) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/resources-widget.component.html#L6)):*
> ```HTML
>       <a
>         class="console-app__widget_left"
>         href="{{ userDataService.userData?.technicalDocsUrl }}"
> ```

i think we possibly might want to introduce a separate endpoint for retrieving all the informational fields e.g. technical docs URL, support phone number and email address

It seems like that'd fit better than including it in the user information.

Thoughts?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2151)* status: 13 of 18 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`console-webapp/src/app/home/widgets/resources-widget.component.html` line 6 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeiemEg-XrTpdNUAh7g:-Neig5E01E-Ez_aAhBxR:btxugyr) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/resources-widget.component.html#L6)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think we possibly might want to introduce a separate endpoint for retrieving all the informational fields e.g. technical docs URL, support phone number and email address

It seems like that'd fit better than including it in the user information.

Thoughts?
</blockquote></details>

Although I agree that having a separate endpoint might be better in ideal circumstances, than trying to fit technical docs url, phone num, email etc into user data, but due the **specifics of our situation** I don't think we should do that. Few things we need to consider:
1) This data immediately available and doesn't require no  DB queries, etc
2) We can make an argument that this data is to be shown pretty much all the time, as it's positioned on the home (default) page
3) We require at least the following data from the server in order to provide meaningful functionality to the user:
    3.1) list of registrars (in order to render a selector); 
    3.2) user data (in order to know what widgets/pages available to the user);
    3.3) misc data, like tech url, etc (in order to render widgets like resources, contacts )

Now, without all that data we can not make webapp fully available to the user and given that we already have at least 2 blocking requests (3.1 and 3.2) I strongly prefer not to make another blocking request given that the data for it is immediately available to us (see 1)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2151)* status: 13 of 18 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`console-webapp/src/app/home/widgets/resources-widget.component.html` line 6 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeiemEg-XrTpdNUAh7g:-Neipmov9tPtwyG2NTjJ:b-8jdk23) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/resources-widget.component.html#L6)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Although I agree that having a separate endpoint might be better in ideal circumstances, than trying to fit technical docs url, phone num, email etc into user data, but due the **specifics of our situation** I don't think we should do that. Few things we need to consider:
1) This data immediately available and doesn't require no  DB queries, etc
2) We can make an argument that this data is to be shown pretty much all the time, as it's positioned on the home (default) page
3) We require at least the following data from the server in order to provide meaningful functionality to the user:
    3.1) list of registrars (in order to render a selector); 
    3.2) user data (in order to know what widgets/pages available to the user);
    3.3) misc data, like tech url, etc (in order to render widgets like resources, contacts )

Now, without all that data we can not make webapp fully available to the user and given that we already have at least 2 blocking requests (3.1 and 3.2) I strongly prefer not to make another blocking request given that the data for it is immediately available to us (see 1)
</blockquote></details>

I think the immediate availability of the simple documentation data indicates even more so that it should be a separate network request. Because it doesn't require a DB query it should return pretty much immediately, meaning that it wouldn't block the loading of the front end (while we wait for registrars and users info). 

I don't see any other reasoning not to make the documentation data a separate request -- the fact that it's frequently visible doesn't seem to make a difference to me. 

Plus, we'll need to continue adding more information to it (and possibly more information to the users API), such as the area that I commented in elsewhere in this PR.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2151)* status: 13 of 18 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`console-webapp/src/app/home/widgets/resources-widget.component.html` line 6 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeiemEg-XrTpdNUAh7g:-NeisBjHD0HUrQmYGa2I:b-anp3yl) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/resources-widget.component.html#L6)):*
Still not convinced. See my comments below:
Before letting user to open home page we need to gather 3 things - registrars, user data, misc. Order of those things is irrelevant because the requests have to go out in parallel not sequential, regardless whether it's 2 requests or 3, otherwise the wait time will grow event more. 
Now you say:
> it wouldn't block the loading of the front end (while we wait for registrars and users info).
Well it would, because after all it's an extra http request, which aside from obvious network overhead doesn't have to be processed in order it was sent. That and the fact that handling that on front-end will become more complicated.

As I mentioned I see where you're coming from, but I don't think the downside in this case worth data separation even if we continue to extend the data in response.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2151)* status: 13 of 18 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`console-webapp/src/app/home/widgets/resources-widget.component.html` line 6 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeiemEg-XrTpdNUAh7g:-Neiugu-BfbEUdRJ7H-7:b2rh66o) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/resources-widget.component.html#L6)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Still not convinced. See my comments below:
Before letting user to open home page we need to gather 3 things - registrars, user data, misc. Order of those things is irrelevant because the requests have to go out in parallel not sequential, regardless whether it's 2 requests or 3, otherwise the wait time will grow event more. 
Now you say:
> it wouldn't block the loading of the front end (while we wait for registrars and users info).
Well it would, because after all it's an extra http request, which aside from obvious network overhead doesn't have to be processed in order it was sent. That and the fact that handling that on front-end will become more complicated.

As I mentioned I see where you're coming from, but I don't think the downside in this case worth data separation even if we continue to extend the data in response.
</blockquote></details>

My point is that I don't believe the addition of the third very-simple request for the documentation information will actually slow things down, since we're going to be bound by the other two requests that are going out in parallel (registrars and users) no matter what. 

At least, I'd hope they go out in parallel!

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2151)* status: 13 of 18 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`console-webapp/src/app/home/widgets/resources-widget.component.html` line 6 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeiemEg-XrTpdNUAh7g:-Nej04HX3LBAzfI-A1i6:b6aouxn) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/resources-widget.component.html#L6)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

My point is that I don't believe the addition of the third very-simple request for the documentation information will actually slow things down, since we're going to be bound by the other two requests that are going out in parallel (registrars and users) no matter what. 

At least, I'd hope they go out in parallel!
</blockquote></details>

It will slow things down, I don't see how it wouldn't as it's extra http request. Even sending 3 requests (/registrars, /userdata and say /miscdata) in parallel (what you're suggesting here) we have no guarantees that /miscdata will be processed first, in fact it might as well be received and processed last by the server depending on the network trafficking, that's what I've been trying to tell.

We're talking here about things that directly affect TTI of our web app - https://developer.chrome.com/en/docs/lighthouse/performance/interactive/ and I'd very much prefer to stay in the green zone.

My point is that given that we make user wait for the entire resource loading (html, css, js, etc) and necessary data (registrars, users) already, which we can't do anything anyway, we should consider not making another blocking (read TTI affecting) request unless it's **absolutely necessary**. And in this case I'm not convinced that it's in fact absolutely necessary.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 2 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2151)* status: all files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/app.component.ts` line 43 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeoOhgb3HPLNn4n_xnk:-NeoOhgb3HPLNn4n_xnl:bxs4bvr) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/app.component.ts#L43)):*
> ```XML
>       this.globalLoader.stopGlobalLoader(this);
>     });
>     this.globalLoader.startGlobalLoader(this);
> ```

1. It probably doesn't really matter too much, but shouldn't we start the global loader first before sending off the call to the user service? 
2. It seems odd to me that we have the one GlobalLoader blocking call here in the app instantiation and one call in the registrar service in the constructor. Maybe do both of them here? 
___
*[`console-webapp/src/app/home/widgets/resources-widget.component.html` line 6 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeiemEg-XrTpdNUAh7g:-NeoKthUAebvvfvZuc9y:b-44ykr4) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/resources-widget.component.html#L6)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

It will slow things down, I don't see how it wouldn't as it's extra http request. Even sending 3 requests (/registrars, /userdata and say /miscdata) in parallel (what you're suggesting here) we have no guarantees that /miscdata will be processed first, in fact it might as well be received and processed last by the server depending on the network trafficking, that's what I've been trying to tell.

We're talking here about things that directly affect TTI of our web app - https://developer.chrome.com/en/docs/lighthouse/performance/interactive/ and I'd very much prefer to stay in the green zone.

My point is that given that we make user wait for the entire resource loading (html, css, js, etc) and necessary data (registrars, users) already, which we can't do anything anyway, we should consider not making another blocking (read TTI affecting) request unless it's **absolutely necessary**. And in this case I'm not convinced that it's in fact absolutely necessary.
</blockquote></details>

discussed offline and we should hopefully be OK here 
___
*[`console-webapp/src/app/home/widgets/settings-widget.component.ts` line 33 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeoNWZM-UNs7bQ46JRi:-NeoNWZM-UNs7bQ46JRj:bb55moo) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/settings-widget.component.ts#L33)):*
> ```XML
>   }
> 
>   openSecPage() {
> ```

i know this is nitty, but can we use the full term `Security`? It removes ambiguity and 
___
*[`console-webapp/src/app/shared/services/userData.service.ts` line 28 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeoPAOP8zmTmiheNABn:-NeoPAOP8zmTmiheNABo:bwrhgft) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/shared/services/userData.service.ts#L28)):*
> ```XML
>   providedIn: 'root',
> })
> export class UserDataService {
> ```

Shouldn't this implement GlobalLoader?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2151)* status: 14 of 18 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/app.component.ts` line 43 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeoOhgb3HPLNn4n_xnk:-Nes47R86Q9kvz0KWgur:bebxjrf) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/app.component.ts#L43)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

1. It probably doesn't really matter too much, but shouldn't we start the global loader first before sending off the call to the user service? 
2. It seems odd to me that we have the one GlobalLoader blocking call here in the app instantiation and one call in the registrar service in the constructor. Maybe do both of them here?
</blockquote></details>

1) It matters functionally - loader is usually started after the call to cover the potential issue with the call itself that might arise and leave the loader hanging. In other words if `getUserData()` throws runtime error for whatever reason we won't have to deal with the ghost webapp loading state
2) Good point, however this is not a good place for loaders, in fact let me remove `getUserData` loader from here and put it in the service,  where it belongs.
___
*[`console-webapp/src/app/home/widgets/settings-widget.component.ts` line 33 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeoNWZM-UNs7bQ46JRi:-NesAZ_f7_Q6mCY2zHnj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/home/widgets/settings-widget.component.ts#L33)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i know this is nitty, but can we use the full term `Security`? It removes ambiguity and
</blockquote></details>

Done.
___
*[`console-webapp/src/app/shared/services/userData.service.ts` line 28 at r2](https://reviewable.io/reviews/google/nomulus/2151#-NeoPAOP8zmTmiheNABn:-NesA_4Z8RoB5tHYRE_-:b-7gvx66) ([raw file](https://github.com/google/nomulus/blob/16e80f6492252608034b19fe6d2f1a8c18464448/console-webapp/src/app/shared/services/userData.service.ts#L28)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Shouldn't this implement GlobalLoader?
</blockquote></details>

It does now as I moved globalLoader here call from `app.component.ts`

**Review by gbrodman — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
