### PR TITLE
Allow disabling UpdateAutoTimestamp updates

### PR DESCRIPTION
**Pull request by mindhog**
Allow us to disable timestamp updates within a try-with-resources block for a
given thread.  This functionality will be needed for transaction replays both
to and from datastore.

As part of this, also upgrade the UpdateAutoTimestampTest to a
DualDatabaseTest so we can verify that the functionality works both on
Datastore and Cloud SQL.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/906)

### CODE REVIEW

**Review by gbrodman — COMMENTED** [review]
Thoughts on adding a method to either the generic transaction manager or the JPA transaction manager called something like `transactWithoutUpdateTimestamp()` that would handle using this for us? 

That way we wouldn't need 
```
    try (UpdateAutoTimestamp.DisableAutoUpdateResource disabler =
        new UpdateAutoTimestamp.DisableAutoUpdateResource()) {
``` any time we wanted to use it 
```


> *[Reviewable](https://reviewable.io/reviews/google/nomulus/906#-:-MOIVlY5EIN0bIYPJv_n:b8dzf9s)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/model/UpdateAutoTimestampTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/906#-MOIWEHnAcrmfF242Lch:-MOIWEHnAcrmfF242Lci:bbayj6u) ([raw file](https://github.com/google/nomulus/blob/d2b0e65cf6b189f777a46d1a92040815b4b06691/core/src/test/java/google/registry/model/UpdateAutoTimestampTest.java#L84)):*
> ```Java
>   @TestOfyAndSql
>   void testDisabledUpdates() throws Exception {
> ```

nit: extra newline here

**Review by mindhog — COMMENTED** [review]
My own predisposition is to leave it this way: it's really for a very specialized case, and it's only going to end up in two places in the code (both during replay).  Putting it into the transaction manager makes it seem like it's fair game for general use, and it's really not.

That said, I don't feel strongly about this, and it's fairly easy to do.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/906#-:-MOIYQzg2AwFHnisrkR3:b-tjp7s6)* status: 0 of 4 files reviewed, all discussions resolved

___
*[core/src/test/java/google/registry/model/UpdateAutoTimestampTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/906#-MOIWEHnAcrmfF242Lch:-MOIZund6PTvmHVo2_r4:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d2b0e65cf6b189f777a46d1a92040815b4b06691/core/src/test/java/google/registry/model/UpdateAutoTimestampTest.java#L84)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit: extra newline here
</blockquote></details>

Done.

**Review by gbrodman — COMMENTED** [review]
Yeah, that's fair. Let's file a bug + TODO to remove this once we're done with replay then, and we should be good to go here

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/906#-:-MOIinBZ01C4M9EhWxwa:b4d7eq5)* status: 0 of 4 files reviewed, all discussions resolved

**Review by mindhog — COMMENTED** [review]
Done.  PTAL?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/906#-:-MOXoyY0AtScc9ZMYRTd:b-19xu53)* status: 0 of 4 files reviewed, all discussions resolved

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/906)* status: 0 of 4 files reviewed, all discussions resolved

**Pull request merged**
