### PR TITLE
Add user email prefix to the console user create

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2623)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2623)* status: all files reviewed, 4 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/users/users.service.ts` line 63 at r1](https://reviewable.io/reviews/google/nomulus/2623#-ODwwJAqAOMMP-8EurxH:-ODwwJAqAOMMP-8EurxI:biuv9iw) ([raw file](https://github.com/google/nomulus/blob/11ff9aa316e0730bedd971f59e6ca71b25f84c9c/console-webapp/src/app/users/users.service.ts#L63)):*
> ```XML
>   }
> 
>   createOrAddNewUser(maybeExistingUser: User) {
> ```

nit, but can rename this field to remove "maybe" 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 149 at r1](https://reviewable.io/reviews/google/nomulus/2623#-ODwwTir6rNY2j_QEM-l:-ODwwTir6rNY2j_QEM-m:b-tctlvv) ([raw file](https://github.com/google/nomulus/blob/11ff9aa316e0730bedd971f59e6ca71b25f84c9c/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L149)):*
> ```Java
>   private void runPostInTransaction() throws IOException {
>     validateRequestParams();
>     if (tm().loadByKeyIfPresent(VKey.create(User.class, this.userData.get().emailAddress))
> ```

can just use `tm().exists` right? 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 201 at r1](https://reviewable.io/reviews/google/nomulus/2623#-ODwwuRHAlblBFRX7fuQ:-ODwwuRHAlblBFRX7fuR:b-v5bapb) ([raw file](https://github.com/google/nomulus/blob/11ff9aa316e0730bedd971f59e6ca71b25f84c9c/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L201)):*
> ```Java
>     String newEmailPrefix = userData.get().emailAddress.trim();
> 
>     if (newEmailPrefix.length() != 3 || !newEmailPrefix.matches("^\\p{Alnum}+$")) {
> ```

what's this prefix regex? 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 270 at r1](https://reviewable.io/reviews/google/nomulus/2623#-ODwx2O5DcxEj1Aoxyob:-ODwx2O67erSTggB7C3R:b-ixfs2o) ([raw file](https://github.com/google/nomulus/blob/11ff9aa316e0730bedd971f59e6ca71b25f84c9c/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L270)):*
> ```Java
> 
>   private User verifyUserExists(String email) {
>     return tm().loadByKeyIfPresent(VKey.create(User.class, email))
> ```

same here w/r/t `exists`

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2623)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 270 at r1](https://reviewable.io/reviews/google/nomulus/2623#-ODwx2O5DcxEj1Aoxyob:-OE-vBf_8_Q2oIgOFUMT:b-bx081d) ([raw file](https://github.com/google/nomulus/blob/11ff9aa316e0730bedd971f59e6ca71b25f84c9c/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L270)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Unlike the other one before, this one actually should stay as it is. Exists wouldn't fit here, because we want to return the user or throw
</blockquote></details>

oof yeah sorry
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 196 at r2](https://reviewable.io/reviews/google/nomulus/2623#-OE0J2v_3spGpqD_FQwy:-OE0J2v_3spGpqD_FQwz:bld0hay) ([raw file](https://github.com/google/nomulus/blob/5df6e965a5a68027a06a96b3a608ea7ebaa1b18b/console-webapp/src/app/shared/services/backend.service.ts#L196)):*
> ```XML
>         catchError((err) =>
>           this.errorCatcher<User>(err, {
>             emailAddress: 'pavlotest-user2@domainregistry-sandbox.co',
> ```

heh i think this snuck in 
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 166 at r3](https://reviewable.io/reviews/google/nomulus/2623#-OE0JKWBEX1xW9xYY9Kn:-OE0JKWBEX1xW9xYY9Ko:b-hnrmun) ([raw file](https://github.com/google/nomulus/blob/71545d915d680973612eae1487955a425fd0b2a5/console-webapp/src/app/shared/services/backend.service.ts#L166)):*
> ```XML
>     return this.http
>       .get<User[]>(`/console-api/users?registrarId=${registrarId}`)
>       .pipe(
> ```

i think these snuck in from testing?

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2623)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2623)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 196 at r2](https://reviewable.io/reviews/google/nomulus/2623#-OE0J2v_3spGpqD_FQwy:-OE0MZ_B0LDnTU992AC9:b2nhswv) ([raw file](https://github.com/google/nomulus/blob/5df6e965a5a68027a06a96b3a608ea7ebaa1b18b/console-webapp/src/app/shared/services/backend.service.ts#L196)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

heh i think this snuck in
</blockquote></details>

Yep
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 166 at r3](https://reviewable.io/reviews/google/nomulus/2623#-OE0JKWBEX1xW9xYY9Kn:-OE0MYni2Oy0CoZWSlCj:b2nhswv) ([raw file](https://github.com/google/nomulus/blob/71545d915d680973612eae1487955a425fd0b2a5/console-webapp/src/app/shared/services/backend.service.ts#L166)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think these snuck in from testing?
</blockquote></details>

Yep

**Pull request merged**
