### PR TITLE
Fix copy causing premature hash calculation

### PR DESCRIPTION
**Pull request by mindhog**
The creation of a builder to set the DomainContent repo id in DomainHistory
triggers an equality check which causes the hash code of an associated
transfer data object to be calculated prematurely, before the Ofy keys are
reconstituted.  Replace this with a simple setter, which is acceptable in this
case because the object is being loaded and is considered to be not fully
constructed yet.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1189)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1189)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/EppResource.java, line 167 at r1](https://reviewable.io/reviews/google/nomulus/1189#-MbHm2-90MraJah7Sbsf:-MbHlvXoAjFQb5AIyBZJ:b-qkehwr) ([raw file](https://github.com/google/nomulus/blob/a75dde16e942ffa6660c3e6c73428c4459ae600e/core/src/main/java/google/registry/model/EppResource.java#L167)):*
> ```Java
>    * <p>In addition to this special case use, this method must exist to satisfy Hibernate.
>    */
>   public void setRepoId(String repoId) {
> ```

:/ not a fan of having this be public, even with the warning. Shame that it can't be package-protected at the very least. 

This should be fine though. 
___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 264 at r1](https://reviewable.io/reviews/google/nomulus/1189#-MbHeeCI3nD1li7M9IKe:-MbHeeCI3nD1li7M9IKf:bqs587a) ([raw file](https://github.com/google/nomulus/blob/a75dde16e942ffa6660c3e6c73428c4459ae600e/core/src/main/java/google/registry/model/domain/DomainHistory.java#L264)):*
> ```Java
>           // it.  In fact, we have to because going through the builder causes the hash codes of
>           // contained objects to be calculated prematurely.
>           domainContent.setRepoId(parent.getName());
> ```

I assume / believe similar lines probably exist in ContactHistory and HostHistory; have you looked at those?

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1189)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 264 at r1](https://reviewable.io/reviews/google/nomulus/1189#-MbHeeCI3nD1li7M9IKe:-MbLsA8yEeIAAnynfYs6:bpaqpez) ([raw file](https://github.com/google/nomulus/blob/a75dde16e942ffa6660c3e6c73428c4459ae600e/core/src/main/java/google/registry/model/domain/DomainHistory.java#L264)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I assume / believe similar lines probably exist in ContactHistory and HostHistory; have you looked at those? 
</blockquote></details>

Yes, you're right.  Though those cases are likely not problematic if host and contact builders don't do any comparisons of nested immutable objects.

Changed those as well.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1189)* status: all files reviewed, 2 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 118 at r2](https://reviewable.io/reviews/google/nomulus/1189#-MbMMtB1CtWx2j-Rpi9x:-MbMMtB1CtWx2j-Rpi9y:bhiuexg) ([raw file](https://github.com/google/nomulus/blob/0052709bc590fd50c7af16828149539fa10a2675/core/src/main/java/google/registry/model/contact/ContactHistory.java#L118)):*
> ```Java
>     }
>     if (contactBase != null && contactBase.getRepoId() == null) {
>       // hostBase hasn't been fully constructed yet, so it's ok to go in and mutate it.  Though the
> ```

s/hostBase/contactBase/g
___
*[core/src/main/java/google/registry/model/host/HostHistory.java, line 119 at r2](https://reviewable.io/reviews/google/nomulus/1189#-MbMMwk52CZnU-3VT1Up:-MbMMwk52CZnU-3VT1Uq:bcguwoy) ([raw file](https://github.com/google/nomulus/blob/0052709bc590fd50c7af16828149539fa10a2675/core/src/main/java/google/registry/model/host/HostHistory.java#L119)):*
> ```Java
>     }
>     if (hostBase != null && hostBase.getRepoId() == null) {
>       // hostBase hasn't been fully constructed yet, so it's ok to go in and mutate it.  Though the
> ```

s/hostBase/domainBase/g

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1189)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/contact/ContactHistory.java, line 118 at r2](https://reviewable.io/reviews/google/nomulus/1189#-MbMMtB1CtWx2j-Rpi9x:-MbMVLhN6bvz3vFmigB0:bmpx7xj) ([raw file](https://github.com/google/nomulus/blob/0052709bc590fd50c7af16828149539fa10a2675/core/src/main/java/google/registry/model/contact/ContactHistory.java#L118)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

s/hostBase/contactBase/g
</blockquote></details>

Gah.  Done.
___
*[core/src/main/java/google/registry/model/host/HostHistory.java, line 119 at r2](https://reviewable.io/reviews/google/nomulus/1189#-MbMMwk52CZnU-3VT1Up:-MbMVR3vA5mW2Mbj58e6:b-ejl4za) ([raw file](https://github.com/google/nomulus/blob/0052709bc590fd50c7af16828149539fa10a2675/core/src/main/java/google/registry/model/host/HostHistory.java#L119)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

s/hostBase/domainBase/g
</blockquote></details>

No, this one is actually correct :-)  Except for "can do thing..."  Fixed.

**Review by gbrodman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1189#-:-MbMWtQdBMjJ65XMgmj6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/host/HostHistory.java, line 119 at r2](https://reviewable.io/reviews/google/nomulus/1189#-MbMMwk52CZnU-3VT1Up:-MbMWqr998gUcFZsJhyW:bb59zqj) ([raw file](https://github.com/google/nomulus/blob/0052709bc590fd50c7af16828149539fa10a2675/core/src/main/java/google/registry/model/host/HostHistory.java#L119)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

No, this one is actually correct :-)  Except for "can do thing..."  Fixed.
</blockquote></details>

Whoops I blame Reviewable :P

**Pull request merged**
