### PR TITLE
Allow AppEngine deployment to qa environment

### PR DESCRIPTION
**Pull request by weiminyu**
This depends on a PR in the internal repo.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/986)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/986)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[build.gradle, line 124 at r1](https://reviewable.io/reviews/google/nomulus/986#-MUtfmTp-x4xkjy3mU67:-MUtfmTp-x4xkjy3mU68:b-tkplv8) ([raw file](https://github.com/google/nomulus/blob/fb19a2ff2e9623f76e6e49492a24e64b5c0c3b26/build.gradle#L124)):*
> ```Gradle
> // the root project.
> 
> def environments = ['production', 'sandbox', 'alpha', 'crash', 'qa']
> ```

I think you may need to add this to /projects.gradle, as well?  In any case, you probably should.

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/986)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[build.gradle, line 124 at r1](https://reviewable.io/reviews/google/nomulus/986#-MUtfmTp-x4xkjy3mU67:-MUtfzIl0fX47nkx6ESO:b-t2q368) ([raw file](https://github.com/google/nomulus/blob/fb19a2ff2e9623f76e6e49492a24e64b5c0c3b26/build.gradle#L124)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I think you may need to add this to /projects.gradle, as well?  In any case, you probably should.
</blockquote></details>

TBH, I'm not sure why we don't _extract_ this from projects.gradle.

**Review by mindhog — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/986)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/986)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[build.gradle, line 124 at r1](https://reviewable.io/reviews/google/nomulus/986#-MUtfmTp-x4xkjy3mU67:-MUtlDKACAGWQHvKPNbP:b-896fix) ([raw file](https://github.com/google/nomulus/blob/fb19a2ff2e9623f76e6e49492a24e64b5c0c3b26/build.gradle#L124)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

TBH, I'm not sure why we don't _extract_ this from projects.gradle.
</blockquote></details>

Done.

**Review by mindhog — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/986)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/986)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Pull request merged**
