### PR TITLE
Ensure that all relevant Keys can be converted to VKeys

### PR DESCRIPTION
**Pull request by gbrodman**
When replaying commit logs to SQL (specifically deletes) we will need to
convert Datastore Keys to SQL VKeys in order to know what (if anything)
to delete.

The test added to EntityTest (and the associated code changes) mean that
for every relevant object we'll be able to call
VKeyTranslatorFactory.createVKey(Key<?>) for all possible keys that we
care about. Note that we do not care about entities that only exist in
Datastore or entities that are non-replicated -- by their nature,
deletes for those types of objects in Datastore are not relevant in SQL.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/883)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/883)* status: all files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 776 at r1](https://reviewable.io/reviews/google/nomulus/883#-MMuG4UI8cdCz9wsMmOB:-MMuG4UJEtxlpptZCMXt:bqdc8z1) ([raw file](https://github.com/google/nomulus/blob/1120415a5dc74a3e549e55f12b9b1da63b2cea25/core/src/main/java/google/registry/model/registrar/Registrar.java#L776)):*
> ```Java
>       } else {
>         getInstance().billingAccountMap =
>             billingAccountMap.entrySet().stream()
> ```

Seems like there is a lot of unrelated reformatting going on here.  Any idea why?
___
*[core/src/test/java/google/registry/schema/replay/EntityTest.java, line 76 at r1](https://reviewable.io/reviews/google/nomulus/883#-MMuMhy-08mzHvJq50O6:-MMuMhy-08mzHvJq50O7:b2gs7yw) ([raw file](https://github.com/google/nomulus/blob/1120415a5dc74a3e549e55f12b9b1da63b2cea25/core/src/test/java/google/registry/schema/replay/EntityTest.java#L76)):*
> ```
> classes must not have a parent
> ```
"must have Objectify keys that do not have a parent" or "must have non-composite objectify keys" 
___
*[core/src/test/java/google/registry/schema/replay/EntityTest.java, line 108 at r1](https://reviewable.io/reviews/google/nomulus/883#-MMuNR3E5q6hzIrLD1vU:-MMuNR3E5q6hzIrLD1vV:b-cwvk9x) ([raw file](https://github.com/google/nomulus/blob/1120415a5dc74a3e549e55f12b9b1da63b2cea25/core/src/test/java/google/registry/schema/replay/EntityTest.java#L108)):*
> ```Java
>   }
> 
>   private <T> boolean hasParent(Class<T> clazz) {
> ```

again, "hasKeyWithParent" or "hasCompositeKey" is probably more accurate.
___
*[core/src/test/java/google/registry/schema/replay/EntityTest.java, line 121 at r1](https://reviewable.io/reviews/google/nomulus/883#-MMuOgoj2w5Yb8eb9rXd:-MMuOgoj2w5Yb8eb9rXe:b-36oany) ([raw file](https://github.com/google/nomulus/blob/1120415a5dc74a3e549e55f12b9b1da63b2cea25/core/src/test/java/google/registry/schema/replay/EntityTest.java#L121)):*
> ```Java
>     }
>     return builder.build();
>   }
> ```

This is a lot like what we're doing in g.r.model.ModelUtils.  Is it possible for us to reuse that code or to move this code into that class?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/883)* status: 25 of 27 files reviewed, 4 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 776 at r1](https://reviewable.io/reviews/google/nomulus/883#-MMuG4UI8cdCz9wsMmOB:-MMv3vq-Eh2eTX0ubuYz:b-artfct) ([raw file](https://github.com/google/nomulus/blob/1120415a5dc74a3e549e55f12b9b1da63b2cea25/core/src/main/java/google/registry/model/registrar/Registrar.java#L776)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Seems like there is a lot of unrelated reformatting going on here.  Any idea why?
</blockquote></details>

Just an autoformat, I don't think one had been done on this file yet. 
___
*[core/src/test/java/google/registry/schema/replay/EntityTest.java, line 76 at r1](https://reviewable.io/reviews/google/nomulus/883#-MMuMhy-08mzHvJq50O6:-MMv44hHA6Nq1KXmpHM5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1120415a5dc74a3e549e55f12b9b1da63b2cea25/core/src/test/java/google/registry/schema/replay/EntityTest.java#L76)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

> ```
> classes must not have a parent
> ```
"must have Objectify keys that do not have a parent" or "must have non-composite objectify keys" 
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/schema/replay/EntityTest.java, line 108 at r1](https://reviewable.io/reviews/google/nomulus/883#-MMuNR3E5q6hzIrLD1vU:-MMv49EZA0C4hry44Mz4:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1120415a5dc74a3e549e55f12b9b1da63b2cea25/core/src/test/java/google/registry/schema/replay/EntityTest.java#L108)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

again, "hasKeyWithParent" or "hasCompositeKey" is probably more accurate.
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/schema/replay/EntityTest.java, line 121 at r1](https://reviewable.io/reviews/google/nomulus/883#-MMuOgoj2w5Yb8eb9rXd:-MMv6zYl3C1qqR9f4Vau:be99p9m) ([raw file](https://github.com/google/nomulus/blob/1120415a5dc74a3e549e55f12b9b1da63b2cea25/core/src/test/java/google/registry/schema/replay/EntityTest.java#L121)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

This is a lot like what we're doing in g.r.model.ModelUtils.  Is it possible for us to reuse that code or to move this code into that class?
</blockquote></details>

Good call -- we'll need to modify the access modifier but we can definitely do that.

**Review by mindhog — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/883)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by mindhog — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/883#-:-MMvih0Z7e0HgyIhBxid:bb6ywmx)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Pull request merged**
