### PR TITLE
Fix a in issue with RDE

### PR DESCRIPTION
**Pull request by jianglai**
For some inexplicable reason, the RDE beam pipeline in both sandbox and
production has been broken for the past week or so. Our investigations
revealed that during the CoGropuByKey stage, some repo ID -> revision ID
pairs were duplicated. This may be a problem with the Dataflow runtime
which somehow introduced the duplicate during reshuffling.

This PR attempts to fix the symptom only by deduping the revision IDs. We
will do some more investigation and possibly follow up with the Dataflow
team if we determine it is an upstream issue.

TESTED=deployed the pipeline and successfully run sandbox RDE with it.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1593)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1593)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jianglai and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 378 at r1](https://reviewable.io/reviews/google/nomulus/1593#-N-Zv89T4kBPtVAhMp9a:-N-Zv89T4kBPtVAhMp9b:b-93rezu) ([raw file](https://github.com/google/nomulus/blob/45720fb439d7752a10113db9b2ccbf19140925f1/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L378)):*
> ```Java
>     // require manual intervention.
>     if (ids.size() != 1) {
>       ImmutableList<Long> dedupedIds = ids.stream().distinct().collect(toImmutableList());
> ```

`ImmutableSet<Long> dedupedIds = ImmutableSet.copyOf(ids);` seems nicer to me here.
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 380 at r1](https://reviewable.io/reviews/google/nomulus/1593#-N-ZuRSp3qhL_t5CN9HY:-N-ZuRSp3qhL_t5CN9HZ:b-a8a2yh) ([raw file](https://github.com/google/nomulus/blob/45720fb439d7752a10113db9b2ccbf19140925f1/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L380)):*
> ```Java
>       ImmutableList<Long> dedupedIds = ids.stream().distinct().collect(toImmutableList());
>       if (dedupedIds.size() != 1) {
>         throw new RuntimeException(
> ```

`RuntimeException` is vague and is generally only suitable for rethrowing a checked exception as a non-checked exception when there are relevant type constraints.  It's better to throw something more specific, such as using `checkState()` here to throw `IllegalStateException`.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1593)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 378 at r1](https://reviewable.io/reviews/google/nomulus/1593#-N-Zv89T4kBPtVAhMp9a:-N-__f120WAeveHTC80x:b-6d8fcs) ([raw file](https://github.com/google/nomulus/blob/45720fb439d7752a10113db9b2ccbf19140925f1/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L378)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`ImmutableSet<Long> dedupedIds = ImmutableSet.copyOf(ids);` seems nicer to me here.
</blockquote></details>

Good idea. I like it too.
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 380 at r1](https://reviewable.io/reviews/google/nomulus/1593#-N-ZuRSp3qhL_t5CN9HY:-N-__ik10_A0a8S38CgR:b66jcwy) ([raw file](https://github.com/google/nomulus/blob/45720fb439d7752a10113db9b2ccbf19140925f1/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L380)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`RuntimeException` is vague and is generally only suitable for rethrowing a checked exception as a non-checked exception when there are relevant type constraints.  It's better to throw something more specific, such as using `checkState()` here to throw `IllegalStateException`.
</blockquote></details>

We cannot use `checkState()` because we would like to log a severe message when there is a duplicate.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1593)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 380 at r1](https://reviewable.io/reviews/google/nomulus/1593#-N-ZuRSp3qhL_t5CN9HY:-N-cfZVa3o6LLy-mTqCE:bfqjzoo) ([raw file](https://github.com/google/nomulus/blob/45720fb439d7752a10113db9b2ccbf19140925f1/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L380)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

We cannot use `checkState()` because we would like to log a severe message when there is a duplicate.
</blockquote></details>

`checkState` should work:

if (ids.size() != 1) {
   dedupedIds = ...
   checkState(dedupedIds.szie() == 1, ...);
   logger.atSevere().log(...);
}

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1593)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 380 at r1](https://reviewable.io/reviews/google/nomulus/1593#-N-ZuRSp3qhL_t5CN9HY:-N-ckt0lCVYi7Kz_bvMZ:bb6un1j) ([raw file](https://github.com/google/nomulus/blob/45720fb439d7752a10113db9b2ccbf19140925f1/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L380)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

`checkState` should work:

if (ids.size() != 1) {
   dedupedIds = ...
   checkState(dedupedIds.szie() == 1, ...);
   logger.atSevere().log(...);
} 
</blockquote></details>

Done

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1593)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @jianglai, and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 381 at r3](https://reviewable.io/reviews/google/nomulus/1593#-N-eGtRqCHRHEY5B0QxC:-N-eGtRqCHRHEY5B0QxD:b-m2kmih) ([raw file](https://github.com/google/nomulus/blob/585b8ce4253502e821c0cd6bbb8e5264006e4b1d/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L381)):*
> ```Java
>       checkState(
>           dedupedIds.size() == 1,
>           String.format(
> ```

You don't need `String.format()` with `checkState()`
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 385 at r3](https://reviewable.io/reviews/google/nomulus/1593#-N-eGydA-moj89IE3k6D:-N-eGydA-moj89IE3k6E:b-8whazj) ([raw file](https://github.com/google/nomulus/blob/585b8ce4253502e821c0cd6bbb8e5264006e4b1d/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L385)):*
> ```Java
>               EPP_RESOURCE_FIELD_NAME.get(historyEntryClazz), repoId, ids));
>       logger.atSevere().log(
>           String.format(
> ```

You don't need `String.format()` with `log()` (and indeed it's better not to use it, as flogger will only call to-string/concatenate on the args being passed if the given logging level is actually enabled, vs `String.format()` will always do the string manipulations).

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1593)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 381 at r3](https://reviewable.io/reviews/google/nomulus/1593#-N-eGtRqCHRHEY5B0QxC:-N-ejM7233eEz5nux6HG:b-892rda) ([raw file](https://github.com/google/nomulus/blob/585b8ce4253502e821c0cd6bbb8e5264006e4b1d/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L381)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You don't need `String.format()` with `checkState()`
</blockquote></details>

Duh..
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 385 at r3](https://reviewable.io/reviews/google/nomulus/1593#-N-eGydA-moj89IE3k6D:-N-ejNBJ643ew8GTbBf5:b9bx1y0) ([raw file](https://github.com/google/nomulus/blob/585b8ce4253502e821c0cd6bbb8e5264006e4b1d/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L385)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You don't need `String.format()` with `log()` (and indeed it's better not to use it, as flogger will only call to-string/concatenate on the args being passed if the given logging level is actually enabled, vs `String.format()` will always do the string manipulations).
</blockquote></details>

Yeah, I guess I didn't think twice. I just moved some existing debug statement over here.

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1593)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @weiminyu)

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1593)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jianglai and @weiminyu)

**Pull request merged**
