### PR TITLE
A better Datastore bulk delete tool

### PR DESCRIPTION
**Pull request by weiminyu**
Implements an alternative to GCP builtin tool with better performance
and usability.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/947)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
In crash, delete-all takes 1.5 hr, as opposed to 20+ hrs with GCP builtin template. This extrapolates to  about 6 hrs for production data size.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/947#-:-MS4Wtj_6Q08nTfJ-gNL:b-nvzwa6)* status: 0 of 6 files reviewed, all discussions resolved

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/947)* status: all files reviewed, 8 unresolved discussions (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 164 at r1](https://reviewable.io/reviews/google/nomulus/947#-MS4iTxWD9QPtY44ZQOG:-MS4iTxWD9QPtY44ZQOH:b-nowf9d) ([raw file](https://github.com/google/nomulus/blob/eceb52e8544669257b845874c1935a532673436a/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L164)):*
> ```Java
>   static ImmutableList<String> parseKindsToDelete(BulkDeletePipelineOptions options) {
>     return ImmutableList.copyOf(
>         Splitter.on(",").omitEmptyStrings().trimResults().split(options.getKindsToDelete().trim()));
> ```

This should really verify that either the set consists only of "*" or that "*" is not a member (not sure that this is the right place for it.
___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 228 at r1](https://reviewable.io/reviews/google/nomulus/947#-MS8Ym7L7oW2cG7cnHWg:-MS8Ym7L7oW2cG7cnHWh:b7y52s4) ([raw file](https://github.com/google/nomulus/blob/eceb52e8544669257b845874c1935a532673436a/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L228)):*
> ```Java
>             "AssignSingletonKeyToKinds",
>             MapElements.into(kvs(strings(), strings())).via(kind -> KV.of("", kind)))
>         .apply("GatherKindsIntoCollection", GroupByKey.create())
> ```

I don't understand this transformation, it looks like you're combining the input set into a map and then turning it back into a set again?  Can you add a comment here?
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 146 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9YTF45bbZhdfI6lXl:-MS9YTF55VZOd_Q73gne:bn4apph) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L146)):*
> ```Java
> 
>     @Override
>     public abstract String toString();
> ```

I didn't know you could override a base class method and make it abstract!
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 187 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9aSbjA9J7X7tOh0CO:-MS9aSbjA9J7X7tOh0CP:b-1vc2a0) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L187)):*
> ```Java
>     /**
>      * Cloud Datastore system tables with statistics are periodically updated. This method fetches
>      * the latest timestamp (in microseconds) of statistics update using the {@code __Stat_Total__}
> ```

Should this mention that __Stat_Ns_Total__ is used when there is a namespace?
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 251 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9b9qu1O7kUpNMtLr5:-MS9b9qu1O7kUpNMtLr6:b3r1ag2) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L251)):*
> ```Java
>      * <p>Cloud Datastore provides no way to get a good estimate of how large the result of a query
>      * entity kind being queried, using the __Stat_Kind__ system table, assuming exactly 1 kind is
>      * specified in the query.
> ```

This doesn't seem to make sense? Should it be "provides _a_ way?"

Also, is this size of data returned by the query or average size of the entity?
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 326 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9dLeE6dyHJIRaqvLc:-MS9dLeE6dyHJIRaqvLd:b-pu3eov) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L326)):*
> ```Java
>       } catch (DatastoreException e) {
>         // Note: There is no specific error code or message to detect if the query already has a
>         // limit, so we just check for INVALID_ARGUMENT and assume that that the query might have
> ```

one "that" too many :-)
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 395 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9f7l0477ZgesZvKtq:-MS9eg1ADzzuKM1lVEMj:btnh2hu) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L395)):*
> ```Java
>     }
> 
>     /** Returns Number of entities available for reading. */
> ```

Should also document that a return value of -1 indicates an error (or maybe convert that to a RuntimeException.
Is this used anywhere?  I can't seem to find it in this PR.
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 431 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9gT9Z3Zz5xkN0xCbv:-MS9gT9Z3Zz5xkN0xCbw:bw0oowr) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L431)):*
> ```Java
>        *
>        *   3. The resulting {@code PCollection} is sharded using a {@link GroupByKey} operation. The
>        *   queries are extracted from they {@code KV<Integer, Iterable<Query>>} and flattened to
> ```

s/they/the/?
___
*[core/src/test/java/google/registry/beam/initsql/InitSqlTestUtils.java, line 96 at r2](https://reviewable.io/reviews/google/nomulus/947#-MSA-eC35p8bkfa2WR6u:-MSA-eC35p8bkfa2WR6v:b-vkjbqv) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/test/java/google/registry/beam/initsql/InitSqlTestUtils.java#L96)):*
> ```Java
>    * <p>This method makes assertions in the pipeline and only use {@link PAssert} on the result.
>    * This way it supports assertions on Objectify entities, which {@code PAssert} cannot do ( since
>    * we have not implemented Coders for them). Compared with PAssert-compatible options like {@code
> ```

This seems unrelated, is it intentional?

**Review by CydeWeys — CHANGES_REQUESTED** [review]
How aware of entity groups is this deletion job?  Does it know to group all deletes within a single entity group together on the same one shard?  (And note that entity groups get a little complicated thanks to inheritance.)

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/947#-:-MSA1zdk0D2RwWPxHZDo:b-2r3dfo)* status: all files reviewed, 9 unresolved discussions (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 103 at r2](https://reviewable.io/reviews/google/nomulus/947#-MSA1iC75HRIRAzet3Kb:-MSA1iC84Zzg52EK2lbh:b-9mv4q9) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L103)):*
> ```Java
> 
>   private void setupPipeline() {
>     checkState(!FORBIDDEN_PROJECTS.contains(options.getProject()));
> ```

Add an error message here so it's not just a generic `IllegalStateException` with no relevant error message.

**Review by weiminyu — COMMENTED** [review]
It doesn't try to group deletes by entity groups. However we haven't seen any "too much contention" exceptions in the current implementation, which happened in a native implementation.
I'd like to defer the optimization until it is absolutely necessary.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/947#-:-MSAFelg10t66o-p4DG1:b-m6oxmx)* status: 3 of 6 files reviewed, 10 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 164 at r1](https://reviewable.io/reviews/google/nomulus/947#-MS4iTxWD9QPtY44ZQOG:-MSVviwr-Z5WXLqzbn0h:b-lw822q) ([raw file](https://github.com/google/nomulus/blob/eceb52e8544669257b845874c1935a532673436a/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L164)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

This should really verify that either the set consists only of "*" or that "*" is not a member (not sure that this is the right place for it.
</blockquote></details>

Added an arg check earlier.
___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 228 at r1](https://reviewable.io/reviews/google/nomulus/947#-MS8Ym7L7oW2cG7cnHWg:-MSVxxY62MDtRimbLjjd:b-2szy9x) ([raw file](https://github.com/google/nomulus/blob/eceb52e8544669257b845874c1935a532673436a/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L228)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I don't understand this transformation, it looks like you're combining the input set into a map and then turning it back into a set again?  Can you add a comment here?
</blockquote></details>

Added an explanation. Also changed the MapKindsToTags to generate one map instead of KVs.
___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 103 at r2](https://reviewable.io/reviews/google/nomulus/947#-MSA1iC75HRIRAzet3Kb:-MSVvdZF2NE8mFl8QYpA:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L103)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Add an error message here so it's not just a generic `IllegalStateException` with no relevant error message.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 146 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9YTF45bbZhdfI6lXl:-MSVykZQ2bxf6E6gSgH9:b86h3u1) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L146)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I didn't know you could override a base class method and make it abstract!
</blockquote></details>

A bit unusual for sure. This is copied from the gcp sdk.
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 187 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9aSbjA9J7X7tOh0CO:-MSYPgwq3Ago3AVfB2cb:b-oy36jw) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L187)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Should this mention that __Stat_Ns_Total__ is used when there is a namespace?
</blockquote></details>

Added a disclaimer about comments at the class level. I don't see much benefit in fixing copied comments.
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 251 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9b9qu1O7kUpNMtLr5:-MSYPrGKCQ-mVXg6l24P:bb73xfv) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L251)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

This doesn't seem to make sense? Should it be "provides _a_ way?"

Also, is this size of data returned by the query or average size of the entity?
</blockquote></details>

Same
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 326 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9dLeE6dyHJIRaqvLc:-MSYPsaQ-LcbiazgAVm5:bb73xfv) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L326)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

one "that" too many :-)
</blockquote></details>

Same
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 395 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9f7l0477ZgesZvKtq:-MSYPuJvD4LWv6OxtlUD:bb73xfv) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L395)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Should also document that a return value of -1 indicates an error (or maybe convert that to a RuntimeException.
Is this used anywhere?  I can't seem to find it in this PR.
</blockquote></details>

Same
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 431 at r2](https://reviewable.io/reviews/google/nomulus/947#-MS9gT9Z3Zz5xkN0xCbv:-MSYPvtU37u9OgXB9GdW:bb73xfv) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L431)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

s/they/the/?
</blockquote></details>

Same
___
*[core/src/main/java/google/registry/beam/datastore/DatastoreV1.java, line 114 at r3](https://reviewable.io/reviews/google/nomulus/947#-MSYOxABD4hmdeZZcllQ:-MSYOxABD4hmdeZZcllR:bem2rzy) ([raw file](https://github.com/google/nomulus/blob/38b2f2a73c3733a53bc01049b7d182099240305e/core/src/main/java/google/registry/beam/datastore/DatastoreV1.java#L114)):*
> ```
>    * to the builder. Only the {@link #expand} method is modified from the original. Everything else
>    * including comments have been copied verbatim.
> ```
There is benefit in keeping copied code as close to the original as possible. Besides, I don't feel like fixing typos in copied code.
___
*[core/src/test/java/google/registry/beam/initsql/InitSqlTestUtils.java, line 96 at r2](https://reviewable.io/reviews/google/nomulus/947#-MSA-eC35p8bkfa2WR6u:-MSVzNvDCiK0BaRTMzfS:b-lxjgup) ([raw file](https://github.com/google/nomulus/blob/e5aec6836693789c5a0985234d545af224fb2b92/core/src/test/java/google/registry/beam/initsql/InitSqlTestUtils.java#L96)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

This seems unrelated, is it intentional?
</blockquote></details>

Yes. PAssert's containsInAnyOrder() method did not work like its correspondent in Truth when I was testing this class.
I found out that this is fixed now so I removed that statement from here.

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/947)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 228 at r1](https://reviewable.io/reviews/google/nomulus/947#-MS8Ym7L7oW2cG7cnHWg:-MSYTsjV3xpF6q6d3xUD:b-y7hrge) ([raw file](https://github.com/google/nomulus/blob/eceb52e8544669257b845874c1935a532673436a/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L228)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Added an explanation. Also changed the MapKindsToTags to generate one map instead of KVs.
</blockquote></details>

Thanks, but what I don't understand is: is there no more direct way to pass this set to MapKindsToTags?  Is it just a matter of ensuring that MapKindsToTags acts on the collection as a single element as opposed to trying to parallelize it?
___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 119 at r3](https://reviewable.io/reviews/google/nomulus/947#-MSYYbO0AsaYfq9U39yL:-MSYYbO0AsaYfq9U39yM:b-e07zg6) ([raw file](https://github.com/google/nomulus/blob/38b2f2a73c3733a53bc01049b7d182099240305e/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L119)):*
> ```Java
>           pipeline.apply("DiscoverEntityKinds", discoverEntityKinds(options.getProject()));
>     } else {
>       ImmutableList<String> kindsToDeleteParam = parseKindsToDelete(options);
> ```

Add a check to ensure that "*" is not a member?

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/947)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 228 at r1](https://reviewable.io/reviews/google/nomulus/947#-MS8Ym7L7oW2cG7cnHWg:-MSZSEkA13dR8nO2omrO:b7i1tlt) ([raw file](https://github.com/google/nomulus/blob/eceb52e8544669257b845874c1935a532673436a/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L228)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Thanks, but what I don't understand is: is there no more direct way to pass this set to MapKindsToTags?  Is it just a matter of ensuring that MapKindsToTags acts on the collection as a single element as opposed to trying to parallelize it?
</blockquote></details>

Yes, this is one way to make a single thread getting all data in a PCollection.

An alternative exists like this:
PCollectionView<String> kindView = kind.apply(View.asList());
pipeline.apply(Create.of((Void) null)
    .apply(ParDo.of(new DoFn<Void, KV<String, TupleTag>() {

    List<String> kinds = kindView...
   map kinds to tags

}).withSideInput(kindView)....

You do get a better way to gather the values in the kinds PCollection, but you'll also have to inject some value to drive the ParDo stage.
Personally I dislike this alternative more.
___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 119 at r3](https://reviewable.io/reviews/google/nomulus/947#-MSYYbO0AsaYfq9U39yL:-MSZSCY5-ifI9mu3cGiY:b-896fix) ([raw file](https://github.com/google/nomulus/blob/38b2f2a73c3733a53bc01049b7d182099240305e/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L119)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Add a check to ensure that "*" is not a member?
</blockquote></details>

Done.

**Review by mindhog — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/947)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 228 at r1](https://reviewable.io/reviews/google/nomulus/947#-MS8Ym7L7oW2cG7cnHWg:-MSZUNhd93SYtn4CUvBt:b4yw3vz) ([raw file](https://github.com/google/nomulus/blob/eceb52e8544669257b845874c1935a532673436a/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L228)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Yes, this is one way to make a single thread getting all data in a PCollection.

An alternative exists like this:
PCollectionView<String> kindView = kind.apply(View.asList());
pipeline.apply(Create.of((Void) null)
    .apply(ParDo.of(new DoFn<Void, KV<String, TupleTag>() {

    List<String> kinds = kindView...
   map kinds to tags

}).withSideInput(kindView)....

You do get a better way to gather the values in the kinds PCollection, but you'll also have to inject some value to drive the ParDo stage.
Personally I dislike this alternative more.


</blockquote></details>

Can you add something to that effect in the comment?  Simply some along the lines of "This trick sends all elements in the PCollection to a single thread/worker" would be adequate.

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/947)* status: all files reviewed, 3 unresolved discussions (waiting on @mindhog and @weiminyu)

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/947)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java, line 228 at r1](https://reviewable.io/reviews/google/nomulus/947#-MS8Ym7L7oW2cG7cnHWg:-MS_q-Hv3Tn0ctUdc-bJ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/eceb52e8544669257b845874c1935a532673436a/core/src/main/java/google/registry/beam/datastore/BulkDeletePipeline.java#L228)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can you add something to that effect in the comment?  Simply some along the lines of "This trick sends all elements in the PCollection to a single thread/worker" would be adequate.
</blockquote></details>

Done.

**Pull request merged**
