### PR TITLE
Convert more @AutoValues to Java records

### PR DESCRIPTION
**Pull request by CydeWeys**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2378)

### CODE REVIEW

**Review by jianglai — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378)* status: all files reviewed, 9 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 203 at r1](https://reviewable.io/reviews/google/nomulus/2378#-Nt1BQol5hxi__r5wQ9z:-Nt1BQol5hxi__r5wQA-:bng3ym8) ([raw file](https://github.com/google/nomulus/blob/cd5fd542efb2f99413afba18c880aabfb6ffa059/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L203)):*
> ```Java
>    * Key for each {@code BillingEvent}, when aggregating for the overall invoice.
>    *
>    * @param startDate The first day this invoice is valid, in yyyy-MM-dd format.
> ```

It's not the right way to use the `@param` tag. Maybe just inline comment after each parameter in the constructor?

**Review by CydeWeys — COMMENTED** [review]
PTAL, now with lots more changes.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378#-:-NuelBMHBA5xfqB3lvBp:bgqbqww)* status: 1 of 19 files reviewed, 9 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

**Review by CydeWeys — COMMENTED** [review]
PTAL, now with lots more changes.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378#-:-NuelBMHBA5xfqB3lvBp:bgqbqww)* status: 1 of 19 files reviewed, 9 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378)* status: 1 of 19 files reviewed, 9 unresolved discussions (waiting on @github-advanced-security[bot], @jianglai, and @param)

___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 203 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525485995:-NuelEjyBeyukdDu8PIt:b-hnuxo5) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L203)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "startDate" does not match any actual type parameter of type "InvoiceGroupingKey".

[Show more details](https://github.com/google/nomulus/security/code-scanning/3525)
</blockquote></details>

We need to figure out how to get rid of this check, as it's wrong.  These `@param`s as written do work correctly in IntelliJ and are useful.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378)* status: 1 of 19 files reviewed, 9 unresolved discussions (waiting on @github-advanced-security[bot], @jianglai, and @param)

___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 203 at r1](https://reviewable.io/reviews/google/nomulus/2378#-Nt1BQol5hxi__r5wQ9z:-Nuemmht9H_6KyoA_kHg:b-y2aner) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L203)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It's not the right way to use the `@param` tag. Maybe just inline comment after each parameter in the constructor?
</blockquote></details>

It is the right way though: https://stackoverflow.com/questions/61445534/how-to-document-java-record-parameters

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378)* status: all files reviewed, 17 unresolved discussions (waiting on @CydeWeys and @param)

___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 203 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525485995:-Nv2GF4mDyLsyhUBPAQQ:bv1i8rg) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L203)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

We need to figure out how to get rid of this check, as it's wrong.  These `@param`s as written do work correctly in IntelliJ and are useful.
</blockquote></details>

Probably need to configure CodeQL and add an exception. For now I've dismissed the alerts as false positive.
___
*[`core/src/main/java/google/registry/bsa/BsaDiffCreator.java` line 258 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2NOKDBUbHa_jx7fU_:-Nv2NOKDBUbHa_jx7fUa:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/3136919de9b1ef18355267f1ba8fb0cedea3090f/core/src/main/java/google/registry/bsa/BsaDiffCreator.java#L258)):*
> ```Java
>     }
> 
>     static Line of(String label, ImmutableList<Long> orderIds) {
> ```

Ditto.
___
*[`core/src/main/java/google/registry/bsa/api/BlockLabel.java` line 47 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2M27WDwNytJ7Y3DE6:-Nv2M27WDwNytJ7Y3DE7:b-rqxvo7) ([raw file](https://github.com/google/nomulus/blob/3136919de9b1ef18355267f1ba8fb0cedea3090f/core/src/main/java/google/registry/bsa/api/BlockLabel.java#L47)):*
> ```Java
>   }
> 
>   public static BlockLabel create(String label, LabelType type, ImmutableSet<String> idnTables) {
> ```

ditto.
___
*[`core/src/main/java/google/registry/bsa/api/BlockOrder.java` line 43 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2HnsO06eZTeLPE6W5:-Nv2HnsO06eZTeLPE6W6:b-37kegg) ([raw file](https://github.com/google/nomulus/blob/3136919de9b1ef18355267f1ba8fb0cedea3090f/core/src/main/java/google/registry/bsa/api/BlockOrder.java#L43)):*
> ```Java
>   }
> 
>   public static BlockOrder create(long orderId, OrderType orderType) {
> ```

The factory method seems superfluous at this point. We should just call the constructor directly.
___
*[`core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java` line 49 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2LjgD9THYOKpkDAVf:-Nv2LjgD9THYOKpkDAVg:b-n1u5aw) ([raw file](https://github.com/google/nomulus/blob/96e33f5b4fac4e943c22777f194c122c1093188c/core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java#L49)):*
> ```Java
>   }
> 
>   @Memoized
> ```

Was there a reason for the return value to be memoized in the first place?
___
*[`core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java` line 79 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2N5xp7DdXb8j6pkK1:-Nv2N5xp7DdXb8j6pkK2:b-137inx) ([raw file](https://github.com/google/nomulus/blob/3136919de9b1ef18355267f1ba8fb0cedea3090f/core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java#L79)):*
> ```Java
>   }
> 
>   public static UnblockableDomainChange createNew(UnblockableDomain unblockable) {
> ```

I'm curious why you think "create" is better than "of" in cases like this. It looks to me that "of" would have just worked fine and you won't have to change all the call sites.
___
*[`core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java` line 92 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2Lu7y6VOVg2nUeW4l:-Nv2Lu7y6VOVg2nUeW4m:b84wg8t) ([raw file](https://github.com/google/nomulus/blob/3136919de9b1ef18355267f1ba8fb0cedea3090f/core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java#L92)):*
> ```Java
>   }
> 
>   private static UnblockableDomainChange create(
> ```

Same comment regarding superfluous factory method.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378)* status: all files reviewed, 17 unresolved discussions (waiting on @jianglai and @param)

___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 203 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525485995:-Nv2sgfy-cCTgAAxQePk:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L203)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Probably need to configure CodeQL and add an exception. For now I've dismissed the alerts as false positive.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/bsa/api/BlockOrder.java` line 43 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2HnsO06eZTeLPE6W5:-Nv2siMb4sEzN05sDbLl:btdl0qa) ([raw file](https://github.com/google/nomulus/blob/3136919de9b1ef18355267f1ba8fb0cedea3090f/core/src/main/java/google/registry/bsa/api/BlockOrder.java#L43)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The factory method seems superfluous at this point. We should just call the constructor directly.
</blockquote></details>

I'm just following Effective Java here:  https://goto.google.com/ej3e-1   (and not doing more refactoring beyond the AutoValue to record change)

But overall agreed, a bog standard singular static create method here that just calls the single obvious constructor isn't adding THAT much value.
___
*[`core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java` line 49 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2LjgD9THYOKpkDAVf:-Nv2t9lUC8e9dXfRNjY0:bgk0rlq) ([raw file](https://github.com/google/nomulus/blob/96e33f5b4fac4e943c22777f194c122c1093188c/core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java#L49)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Was there a reason for the return value to be memoized in the first place?
</blockquote></details>

I looked into it and it did not seem like there was that much memoization going on, as the domain name is a very specific thing and won't repeat much in the data.  If it were something more common that would have thousands of separate instances being created that should be memoized, maybe it would be better to do.

But it's just a record containing one short string and one enum value, and without too much repetition, so it really doesn't matter that much.
___
*[`core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java` line 79 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2N5xp7DdXb8j6pkK1:-Nv2tRTNE6Ahrn55nVxx:b-jdpaek) ([raw file](https://github.com/google/nomulus/blob/3136919de9b1ef18355267f1ba8fb0cedea3090f/core/src/main/java/google/registry/bsa/api/UnblockableDomainChange.java#L79)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I'm curious why you think "create" is better than "of" in cases like this. It looks to me that "of" would have just worked fine and you won't have to change all the call sites.
</blockquote></details>

Because it's creating a new instance.  The verb "create" here is descriptive of what's going on whereas "of" is not.

**Review by jianglai — APPROVED** [review]

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378)* status: all files reviewed, 17 unresolved discussions (waiting on @jianglai and @param)

___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 204 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525485996:-NvhUQ1KDak3u40ZaDOj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L204)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "endDate" does not match any actual type parameter of type "InvoiceGroupingKey".

[Show more details](https://github.com/google/nomulus/security/code-scanning/3526)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 205 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525485997:-NvhUQFR791412eSmapA:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L205)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "productAccountKey" does not match any actual type parameter of type "InvoiceGroupingKey".

[Show more details](https://github.com/google/nomulus/security/code-scanning/3527)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 206 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525486001:-NvhUQU126lP_NoEApH8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L206)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "usageGroupingKey" does not match any actual type parameter of type "InvoiceGroupingKey".

[Show more details](https://github.com/google/nomulus/security/code-scanning/3528)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 207 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525486004:-NvhUQsS9t0kcnjPiPfP:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L207)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "description" does not match any actual type parameter of type "InvoiceGroupingKey".

[Show more details](https://github.com/google/nomulus/security/code-scanning/3529)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 209 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525486008:-NvhUR8N96FrN5W5qxUM:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L209)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "unitPrice" does not match any actual type parameter of type "InvoiceGroupingKey".

[Show more details](https://github.com/google/nomulus/security/code-scanning/3530)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 210 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525486011:-NvhUROP7XnHEm1j4z03:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L210)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "unitPriceCurrency" does not match any actual type parameter of type "InvoiceGroupingKey".

[Show more details](https://github.com/google/nomulus/security/code-scanning/3531)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 211 at r1](https://reviewable.io/reviews/google/nomulus/2378#gh-1525486013:-NvhURYu60kY4czRKwRB:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0220e39c478a3650db83fe18374ea3623a17b675/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L211)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "poNumber" does not match any actual type parameter of type "InvoiceGroupingKey".

[Show more details](https://github.com/google/nomulus/security/code-scanning/3532)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/bsa/BsaDiffCreator.java` line 258 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2NOKDBUbHa_jx7fU_:-NvhUTtl7gvvXBlQkwxv:b-896fix) ([raw file](https://github.com/google/nomulus/blob/09dc36d562bb50ef71c81fb0199be1a321d243a5/core/src/main/java/google/registry/bsa/BsaDiffCreator.java#L258)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/bsa/api/BlockLabel.java` line 47 at r2](https://reviewable.io/reviews/google/nomulus/2378#-Nv2M27WDwNytJ7Y3DE6:-NvhUTj_1nBHvKY-lEcT:b-896fix) ([raw file](https://github.com/google/nomulus/blob/09dc36d562bb50ef71c81fb0199be1a321d243a5/core/src/main/java/google/registry/bsa/api/BlockLabel.java#L47)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.

**Review by CydeWeys — COMMENTED** [review]
> Dismissed @jianglai from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378)* status: all files reviewed, 14 unresolved discussions (waiting on @jianglai and @param)

___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java` line 33 at r2](https://reviewable.io/reviews/google/nomulus/2378#gh-1552388402:-NvhUbPm65cE9FxmzAro:b-896fix) ([raw file](https://github.com/google/nomulus/blob/09dc36d562bb50ef71c81fb0199be1a321d243a5/core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java#L33)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "latestCompleted" does not match any actual type parameter of type "DownloadSchedule".

[Show more details](https://github.com/google/nomulus/security/code-scanning/6812)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java` line 34 at r2](https://reviewable.io/reviews/google/nomulus/2378#gh-1552388405:-NvhUbb34tA--acHYFxp:b-896fix) ([raw file](https://github.com/google/nomulus/blob/09dc36d562bb50ef71c81fb0199be1a321d243a5/core/src/main/java/google/registry/bsa/persistence/DownloadSchedule.java#L34)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "alwaysDownload" does not match any actual type parameter of type "DownloadSchedule".

[Show more details](https://github.com/google/nomulus/security/code-scanning/6813)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/bsa/persistence/RefreshSchedule.java` line 27 at r2](https://reviewable.io/reviews/google/nomulus/2378#gh-1552388408:-NvhUcKK97gNZU_spdDM:b-896fix) ([raw file](https://github.com/google/nomulus/blob/09dc36d562bb50ef71c81fb0199be1a321d243a5/core/src/main/java/google/registry/bsa/persistence/RefreshSchedule.java#L27)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Spurious Javadoc @param tags

@param tag "prevRefreshTime" does not match any actual type parameter of type "RefreshSchedule".

[Show more details](https://github.com/google/nomulus/security/code-scanning/6814)
</blockquote></details>

Done.

**Review by CydeWeys — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from 11 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378)* status: all files reviewed, 3 unresolved discussions (waiting on @jianglai)

**Review by CydeWeys — COMMENTED** [review]
> Dismissed @jianglai from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2378)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

**Pull request merged**
