### PR TITLE
Remove unnecessary MockitoExtension from Spec11PipelineTest

### PR DESCRIPTION
**Pull request by CydeWeys**
This is kind of a shot in the dark here, but this is one of the obvious
differences between this test class (which frequently experiences flakes) and
the other pipeline test classes which do not.

I also explicitly set the runner in the Spec11PipelineOptions, which seems
possibly related to the NPEs we're seeing in the flakes when it fails to get the
ThreadFactory. This is the only test that explicitly sets these options, so it's
not clear if the usual default to CrashingRunner works if the options are
overridden.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1115)

### CODE REVIEW

**Review by weiminyu — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — CHANGES_REQUESTED** [review]
I don't think setting the runner would matter. We are not using the test pipeline to construct the pipeline. Other parameters of the option is extracted when calling `saveToGcs` and `saveToSql`. It's better to remove it so to not cause confusion.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115#-:-MZOpYqC6ivKQLUViGxw:b-pwo0sr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 94 at r1](https://reviewable.io/reviews/google/nomulus/1115#-MZP-dGG9GlSmhqBfFAN:-MZP-dGG9GlSmhqBfFAO:b-urrw6w) ([raw file](https://github.com/google/nomulus/blob/dd6e5a17c925740a01a5e4d56fac9a1762f607cd/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L94)):*
> ```
> transient
> ```
I talked from memory and made a mistake regarding the 'transient' keyword.

This class does not pass inner classes/lambdas to the pipeline so 'transient' is not needed here.

The likely problems are probably in the Spec11Pipeline class, where lambdas are used three times, once in saveToSql and twice in saveToGcs.

Since Spec11Pipeline saves the 'pipeline' parameter, in tests the TestPipelineExtension is saved there and gets involved in serialization.
We should try turn those three lambdas into static classes.

**Review by CydeWeys — COMMENTED** [review]
When the options are specified (and this is the only test class where they are) it doesn't appear to default to `CrashingRunner`:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/beam/TestPipelineExtension.java;l=447-455;drc=d99278e7238acd472ded1a73d5b213c1dd27b70e?q=testpipelineextension&ss=nomulus%2Fnomulus

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115#-:-MZPM-05APQuEFI-AUuu:b-pk7xqx)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 94 at r1](https://reviewable.io/reviews/google/nomulus/1115#-MZP-dGG9GlSmhqBfFAN:-MZQGZYo7XwOPVinfQGF:b33yn2w) ([raw file](https://github.com/google/nomulus/blob/dd6e5a17c925740a01a5e4d56fac9a1762f607cd/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L94)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> transient
> ```
I talked from memory and made a mistake regarding the 'transient' keyword.

This class does not pass inner classes/lambdas to the pipeline so 'transient' is not needed here.

The likely problems are probably in the Spec11Pipeline class, where lambdas are used three times, once in saveToSql and twice in saveToGcs.

Since Spec11Pipeline saves the 'pipeline' parameter, in tests the TestPipelineExtension is saved there and gets involved in serialization.
We should try turn those three lambdas into static classes.




</blockquote></details>

This seems like an intrinsic design flaw of the `TestPipelineExtnesion`, or our use of pipeline, is it not? We are encouraged to use lambas that conform to the `SerializableFunction` interface in Beam for readability. If the test pipeline cannot be safely deserialized when lambda is used multiple times due to multiple static initialization, it looks to me that for testing's sake we should not save the `Pipeline` object as a field in `Spec11Pipeline`, or any other pipelines that we write.

Also, `InvoicingPipeline` also calls multiple lambdas, and we haven't encountered any flakiness.

The NPE error about ThreadFactory in failing tests still looks not much related to the possible static initialization issues here, truth be told.

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 94 at r1](https://reviewable.io/reviews/google/nomulus/1115#-MZP-dGG9GlSmhqBfFAN:-MZT7Tko1QFqUAHyHwBa:bwi6l0t) ([raw file](https://github.com/google/nomulus/blob/dd6e5a17c925740a01a5e4d56fac9a1762f607cd/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L94)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

This seems like an intrinsic design flaw of the `TestPipelineExtnesion`, or our use of pipeline, is it not? We are encouraged to use lambas that conform to the `SerializableFunction` interface in Beam for readability. If the test pipeline cannot be safely deserialized when lambda is used multiple times due to multiple static initialization, it looks to me that for testing's sake we should not save the `Pipeline` object as a field in `Spec11Pipeline`, or any other pipelines that we write.

Also, `InvoicingPipeline` also calls multiple lambdas, and we haven't encountered any flakiness.

The NPE error about ThreadFactory in failing tests still looks not much related to the possible static initialization issues here, truth be told.
</blockquote></details>

We should stop saving the pipeline object in our *pipeline classes. Maybe pass it in in the run() method instead.

Looking at the exception site, it seems that the only thing that can cause NPE there is that the code believe it is on AppEngine, which means the property com.google.appengine.runtime.environment is set. Maybe we should add an assert in the test class that this property is not set, and also print it in the kokoro runner.

**Review by jianglai — COMMENTED** [review]
`CrashingRunner` actually [throws](https://beam.apache.org/releases/javadoc/2.28.0/org/apache/beam/sdk/testing/CrashingRunner.html) when the pipeline runs, which is not what we want.

Here this `Spec11PipelineOptions` object is not actually passed to the `Pipeline` object, so setting the runner has no effect anyway. Note that there's the `Spec11Pipeline` object, and there's the `Pipeline` object. The latter is passed as a parameter to the former during construction (but we should change that as Weimin pointed out) and that's the one that actually consumes the `Spec11PipelineOptions`. But here we are not actually passing an `Pipeline` to `Spec11Pipeline`, but rather constructing a `TestPipelineExtension`, which is then used to test the static functions on `Spec11Pipeline`. We only construct a `Spec11PipelineOptions` because we need some of the parameters (but not all) in the static function.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115#-:-MZTHt1M-3GURo4XZj7p:b-rknn2a)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 94 at r1](https://reviewable.io/reviews/google/nomulus/1115#-MZP-dGG9GlSmhqBfFAN:-MZTJaaM2Sw5wOqQQDvX:b-glr0qx) ([raw file](https://github.com/google/nomulus/blob/dd6e5a17c925740a01a5e4d56fac9a1762f607cd/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L94)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

We should stop saving the pipeline object in our *pipeline classes. Maybe pass it in in the run() method instead.

Looking at the exception site, it seems that the only thing that can cause NPE there is that the code believe it is on AppEngine, which means the property com.google.appengine.runtime.environment is set. Maybe we should add an assert in the test class that this property is not set, and also print it in the kokoro runner.
</blockquote></details>

I think calling it in run() is the right call (no pun intended). I'll do it in a separate PR. It's strange to think that the environment could **sometimes** be mistaken as app engine. But yeah, adding a check here could help us know for sure. Ben, do you want to add that in this PR?

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jianglai and @weiminyu)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 94 at r1](https://reviewable.io/reviews/google/nomulus/1115#-MZP-dGG9GlSmhqBfFAN:-MZUEuc46ms-Q0qqyUuX:b69gn7b) ([raw file](https://github.com/google/nomulus/blob/dd6e5a17c925740a01a5e4d56fac9a1762f607cd/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L94)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I think calling it in run() is the right call (no pun intended). I'll do it in a separate PR. It's strange to think that the environment could **sometimes** be mistaken as app engine. But yeah, adding a check here could help us know for sure. Ben, do you want to add that in this PR?
</blockquote></details>

I'm struggling to find where the App Engine check is -- do you remember where?  I saw it yesterday.

**Review by CydeWeys — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115#-:-MZUMCITEpas5MOcJ9lF:bb71pro)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jianglai and @weiminyu)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 94 at r1](https://reviewable.io/reviews/google/nomulus/1115#-MZP-dGG9GlSmhqBfFAN:-MZUMBh485oYrsuQPA9O:b-896fix) ([raw file](https://github.com/google/nomulus/blob/dd6e5a17c925740a01a5e4d56fac9a1762f607cd/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L94)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I'm struggling to find where the App Engine check is -- do you remember where?  I saw it yesterday.
</blockquote></details>

Done.

**Review by jianglai — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
