### PR TITLE
 Delete WipeOutCloudSqlAciton 

### PR DESCRIPTION
**Pull request by jianglai**
This action was used during the datastore to Cloud SQL migration when we
periodically wiped out test environment.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2197)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys and @sarahcaseybot)

**Review by CydeWeys — COMMENTED** [review]
I agree the wipe out action can go, but I'm not sure about the load test action? We still have lots more performance work to get to whenever someone frees up, and they're likely gonna need that.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2197#-:-NiAP1Ef6IMhyLDpVSIz:b-c5339o)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)

**Review by jianglai — COMMENTED** [review]
We have not made any real changes to load test related code since we moved to Gradle in 2019. The only changes that happened are all related to other refactoring work. I understand the optionality but keeping it around just means having to sink time into maintaining things that are not actively used.

I've reverted the deletion, but I still have my reservations on it's value. Sarah, when was the last time you used it and did it work as expected?

> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2197#-:-NiFLexv4mxp2cx1bgzT:b-doxrt8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2197#-:-NiFgTE60Z3g49b7kQnR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahcaseybot)

**Pull request merged**
