### PR TITLE
Rename client ID to registrar ID in most places

### PR DESCRIPTION
**Pull request by CydeWeys**
This is a code-only change, that shouldn't require any sort of data
migration. Correspondingly, there are some existing uses of clientId that are
not migrated (e.g. Datastore fields, task queue payloads, URL parameters for
actions that might be hit from task queues, etc.). And it of course doesn't
modify any fields in EPP XML. Note that the Cloud SQL schema fields are
already named using the registar_id pattern.

This also doesn't yet touch on the -c parameters in nomulus tools; that will be
coming later (since that is an external manual touch-point, it will require a
lot more in the way of changes to various meta scripts and documentation).

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1317)

### CODE REVIEW

**Review by jianglai — CHANGES_REQUESTED** [review]
This refactor looks fine. I have two general questions though:

1. What is the motivation for the refactor? Is it just so that it "looks" more consistent? If we have fields in EPP that uses `clientId`, does that mean "client id" is the more correct name?

2. Given the amount of follow up work described in the description, is the migration really worth it?

> Reviewed 265 of 265 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1317#-:-Mj_QhN80eBf-63OhZJE:b-9lxu7f)* status: all files reviewed, 7 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/flows/HttpSessionMetadata.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZiHkt-FA3sRtBLnDv:-MjZiHkt-FA3sRtBLnDw:b4hkyw6) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/main/java/google/registry/flows/HttpSessionMetadata.java#L45)):*
> ```
> CLIENT_ID
> ```
What about this one?
___
*[core/src/main/java/google/registry/model/OteAccountBuilder.java, line 364 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZzZD27PYruXdaMp2Y:-MjZzZD27PYruXdaMp2Z:b-unoh6j) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/main/java/google/registry/model/OteAccountBuilder.java#L364)):*
> ```
> client ID
> ```
Change.
___
*[core/src/test/java/google/registry/flows/FlowTestCase.java, line 155 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZo5I_0Gd5DH3K8JUp:-MjZo5I_0Gd5DH3K8JUq:b-q7d02r) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/flows/FlowTestCase.java#L155)):*
> ```
> getClientIdForFlow
> ```
Change this as well?
___
*[core/src/test/java/google/registry/flows/FlowTestCase.java, line 160 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZo7q_0MLUA_IVp2gh:-MjZo7q_0MLUA_IVp2gi:b-vsz4z5) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/flows/FlowTestCase.java#L160)):*
> ```
> setRegistrarIdForFlow
> ```
And this.
___
*[core/src/test/java/google/registry/flows/ResourceFlowTestCase.java, line 169 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZoCs11DbUwmqsee3g:-MjZoCs11DbUwmqsee3h:b38wg8m) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/flows/ResourceFlowTestCase.java#L169)):*
> ```
> ClientId
> ```
Change? Do we want to change the log itself to use registrarId instead of clientId?
___
*[core/src/test/java/google/registry/model/OteAccountBuilderTest.java, line 155 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZzQZ38M24Pbea9X-T:-MjZzQZ38M24Pbea9X-U:birca9t) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/model/OteAccountBuilderTest.java#L155)):*
> ```
> forClientId
> ```
This one?
___
*[core/src/test/java/google/registry/model/OteAccountBuilderTest.java, line 294 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZzgFeEjJ6suSSWO1L:-MjZzgFeEjJ6suSSWO1M:b-owwje9) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/model/OteAccountBuilderTest.java#L294)):*
> ```
> ClientId
> ```
All these test names still contain client id.

**Review by CydeWeys — COMMENTED** [review]
1. The motivation is that it makes more sense internally in our codebase.  "Client ID" has always been a source of confusion for newcomers to the codebase because it doesn't directly map to anything else -- we don't have "clients".  And yes, it's used in EPP, but that'll be the only place it's used; once it leaves the EPP XML POJO it's uniformly registrarId everywhere else after this change.

2. It's really not that much follow-up work that we don't already get for free.  A lot of the remaining stuff will just happen naturally as we remove the remaining Datastore code and migrate away from task queues.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1317#-:-Mja3X5x6-oYu40KjpAW:b-t57jlp)* status: all files reviewed, 7 unresolved discussions (waiting on @CydeWeys)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1317)* status: 245 of 267 files reviewed, 7 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/flows/HttpSessionMetadata.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZiHkt-FA3sRtBLnDv:-Mja5w7KAncNj_pSH3ag:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/main/java/google/registry/flows/HttpSessionMetadata.java#L45)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> CLIENT_ID
> ```
What about this one?
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/OteAccountBuilder.java, line 364 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZzZD27PYruXdaMp2Y:-Mja64zg8LOZkSMlbdRN:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/main/java/google/registry/model/OteAccountBuilder.java#L364)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> client ID
> ```
Change.
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/flows/FlowTestCase.java, line 155 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZo5I_0Gd5DH3K8JUp:-Mja6Jlw2hgJx1Sqv4sP:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/flows/FlowTestCase.java#L155)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> getClientIdForFlow
> ```
Change this as well?
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/flows/FlowTestCase.java, line 160 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZo7q_0MLUA_IVp2gh:-Mja6L3V2Sm4uwuBcuJp:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/flows/FlowTestCase.java#L160)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> setRegistrarIdForFlow
> ```
And this.
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/flows/ResourceFlowTestCase.java, line 169 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZoCs11DbUwmqsee3g:-Mja6P-o-TK9-5a9lAGG:b-dj3k13) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/flows/ResourceFlowTestCase.java#L169)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> ClientId
> ```
Change? Do we want to change the log itself to use registrarId instead of clientId?
</blockquote></details>

Not yet -- I believe that's might be used somewhere for some kind of analytics that pulls from the log.  So I'm punting on it in this PR (which deals solely with code-only changes).
___
*[core/src/test/java/google/registry/model/OteAccountBuilderTest.java, line 155 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZzQZ38M24Pbea9X-T:-Mja6ohKBzDYNZvaboV8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/model/OteAccountBuilderTest.java#L155)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> forClientId
> ```
This one?
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/model/OteAccountBuilderTest.java, line 294 at r1](https://reviewable.io/reviews/google/nomulus/1317#-MjZzgFeEjJ6suSSWO1L:-Mja7AyI7ShZ-V_uKe9N:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d09fa0361cce731733acc6ffda152d42c4a2d90d/core/src/test/java/google/registry/model/OteAccountBuilderTest.java#L294)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> ClientId
> ```
All these test names still contain client id.
</blockquote></details>

Done.

**Review by jianglai — APPROVED** [review]
> Reviewed 24 of 24 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1317)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Comment by mindhog** [comment]
FWIW, I'm somewhat opposed to this change.  I'd rather have consistency across the board with the EPP name than the association with the registrar.  It's also not inaccurate, as a registry, registrars are our clients. 

More generally, I find that name changes (while they may be helpful to newcomers to a codebase) tend to be costly to existing developers.  They require mental reprogramming and often break outstanding PRs.  If they're going to be done at all, it may be better to wait until we're past the database migration when lots of other things are also in motion.

**Pull request merged**
