### PR TITLE
Add IcannHttpReporter failed response logging

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2252)

### CODE REVIEW

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2252)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java` line 100 at r1](https://reviewable.io/reviews/google/nomulus/2252#-Nl9_16eDAocSN3HtJvS:-Nl9plTY2rNy22oDLpfU:b-u1afjx) ([raw file](https://github.com/google/nomulus/blob/1542b3b1e445ac50ebd672729608ed4bbbd2d17e/core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java#L100)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This block is not very useful. Better remove it. The try-block can then be structured as follows:

```
int respondCode;
byte[] content;

try {
    responseCode = connection.getResponseCode();
    content = UrlConnectionUtils.getResponseBytes(connection);
} catch (IOException e) {
  log and return false
} finally {
  connection.disclose();
}
```

</blockquote></details>

I'm not sure that'd be correct, because I think there may be a legitimate case when IOException is not thrown but response code is invalid, so I had to create a custom error for such case. That should cover it all I hope
___
*[`core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java` line 114 at r1](https://reviewable.io/reviews/google/nomulus/2252#-Nl9_eLp0o-0p9VpFwhl:-Nl9plIVCBa7rXRn-MYU:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1542b3b1e445ac50ebd672729608ed4bbbd2d17e/core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java#L114)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

log response code,  new String(content, UTF_8) if content is not null, and e
</blockquote></details>

Done.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2252)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java` line 96 at r2](https://reviewable.io/reviews/google/nomulus/2252#-Nl9t2S_3-dgMw-CuUNO:-NlA2bRlCLhgs-zDhnQT:bv9lwsq) ([raw file](https://github.com/google/nomulus/blob/f72989a86f26933a5b8484416d74f28c6e0d57b5/core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java#L96)):*
> If the responseCode is not OK, we want to fall through to the logging after this block (after `finally` in the previous revision that seesm to have been overwritten).

I don't follow why do we need to fall through, as my implementation covers that case, by catching and logging what's available (if anything is at all)

> IOException is for `getResponseCode` and `getResponseBytes`, in which case there maybe nothing to show but the IOException itself.

Correct, in that case it will log with cause and default values I provided. Do you think it can be impoved?

> And you used to have a try-block around the `parseResult` call. That is appropriate since the method may throw XmlException.

In another comment you suggested to use `new String(content, UTF_8)`, which I though can be appropriate as we not necessary need to that pasing response as xml, try-cathing, just so that we can add parts to the log. We can just log the whole thing. That of course is for when the request failed. Have I misunderstood your suggestion?

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2252)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java` line 96 at r2](https://reviewable.io/reviews/google/nomulus/2252#-Nl9t2S_3-dgMw-CuUNO:-NlAB4qp2qAt0D1Iq8jj:b-nrve7c) ([raw file](https://github.com/google/nomulus/blob/f72989a86f26933a5b8484416d74f28c6e0d57b5/core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java#L96)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

> If the responseCode is not OK, we want to fall through to the logging after this block (after `finally` in the previous revision that seesm to have been overwritten).

I don't follow why do we need to fall through, as my implementation covers that case, by catching and logging what's available (if anything is at all)

> IOException is for `getResponseCode` and `getResponseBytes`, in which case there maybe nothing to show but the IOException itself.

Correct, in that case it will log with cause and default values I provided. Do you think it can be impoved?

> And you used to have a try-block around the `parseResult` call. That is appropriate since the method may throw XmlException.

In another comment you suggested to use `new String(content, UTF_8)`, which I though can be appropriate as we not necessary need to that pasing response as xml, try-cathing, just so that we can add parts to the log. We can just log the whole thing. That of course is for when the request failed. Have I misunderstood your suggestion?
</blockquote></details>

Sorry I misread your code.

I have a couple subjective opinions here:
1. The pattern of throwing than immediately catching it is not clean
2. By handling IOException and your custom exception in one block it mixes two different error cases.
3. The response is likely to be xml, so we should continue using the parseResult method to improve log readability.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2252)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java` line 96 at r2](https://reviewable.io/reviews/google/nomulus/2252#-Nl9t2S_3-dgMw-CuUNO:-NlAxeCwAYQQsEYeOooR:bmmwib8) ([raw file](https://github.com/google/nomulus/blob/f72989a86f26933a5b8484416d74f28c6e0d57b5/core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java#L96)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Sorry I misread your code.

I have a couple subjective opinions here:
1. The pattern of throwing than immediately catching it is not clean
2. By handling IOException and your custom exception in one block it mixes two different error cases.
3. The response is likely to be xml, so we should continue using the parseResult method to improve log readability.
</blockquote></details>

1) Removed
2) Created separate handler for possible exceptions
3) Added `parseResult` back
___
*[`core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java` line 102 at r2](https://reviewable.io/reviews/google/nomulus/2252#gh-1420925774:-NlAxqvb110AzSnsnKt7:b6ujch) ([raw file](https://github.com/google/nomulus/blob/f72989a86f26933a5b8484416d74f28c6e0d57b5/core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java#L102)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Log Injection

This log entry depends on a [user-provided value](1).

[Show more details](https://github.com/google/nomulus/security/code-scanning/1631)
</blockquote></details>

Not applicable

**Comment by ptkach** [comment]
@weiminyu  Gentle ping on this

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2252)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java` line 106 at r3](https://reviewable.io/reviews/google/nomulus/2252#-NliLLJp8FlNC7Wtg08N:-NliLLJq92A8mYx_cKch:bvpmt3i) ([raw file](https://github.com/google/nomulus/blob/5b07cd3511dfc39978cd88f2364290fd743c6e2e/core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java#L106)):*
> ```Java
>       }
>     } catch (IOException e) {
>       logger.atWarning().withCause(e).log("Connection to ICANN server failed", connection);
> ```

No "%s" in template, and connection may not give much info.

Also, this IOException may be either for response code or for content. If the latter, then response code is available and we should log it.



_Code quote:_
```Java
("Connection to ICANN server failed", connection)
```

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2252)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java` line 106 at r3](https://reviewable.io/reviews/google/nomulus/2252#-NliLLJp8FlNC7Wtg08N:-NliXT-M1QOl4Btnd-Pp:byx9w2e) ([raw file](https://github.com/google/nomulus/blob/5b07cd3511dfc39978cd88f2364290fd743c6e2e/core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java#L106)):*
> connection may not give much info.

Yeah, it's what we used to have there, so I decided to keep it

> Also, this IOException may be either for response code or for content

Good point, updated
___
*[`core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java` line 112 at r3](https://reviewable.io/reviews/google/nomulus/2252#gh-1421156879:-NliXcD35ZZILum4Tn9L:b-896fix) ([raw file](https://github.com/google/nomulus/blob/5b07cd3511dfc39978cd88f2364290fd743c6e2e/core/src/main/java/google/registry/reporting/icann/IcannHttpReporter.java#L112)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Log Injection

This log entry depends on a [user-provided value](1).

[Show more details](https://github.com/google/nomulus/security/code-scanning/1632)
</blockquote></details>

Done.

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2252)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

**Pull request merged**
