### PR TITLE
Change primary key of DelegationSignerData and add its history table

### PR DESCRIPTION
**Pull request by hstonec**
Per https://tools.ietf.org/html/rfc4034#appendix-B and https://tools.ietf.org/html/rfc4035#section-2.4, `keyTag` in `DelegationSignerData` is not unique and we should perform full-object comparison to determine if a `dsData` is unique.

So, this PR changed the primary key of the entity to use a composite key of all fields in `DelegationSignerData` to avoid the key conflict, and it also added a `DelegationSignerDataHistory` table to store the historic entities.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/841)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/841)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @CydeWeys, @hstonec, and @weiminyu)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 176 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0UdH56a1eO2pImLko:-MK0UdH56a1eO2pImLkp:b-mmfl77) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/core/src/main/java/google/registry/model/domain/DomainHistory.java#L176)):*
> ```Java
> 
>   /** Returns the collection of {@link DelegationSignerDataHistory} instances. */
>   public Set<DelegationSignerDataHistory> getDsDataHistories() {
> ```

Given that it's returning a `nullToEmptyImmutableCopy()`, the return type should be `ImmutableSet`.
___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 307 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0U_-A19PpKWfqUBXh:-MK0U_-A19PpKWfqUBXi:b-6u40w7) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/core/src/main/java/google/registry/model/domain/DomainHistory.java#L307)):*
> ```Java
>     public DomainHistory build() {
>       DomainHistory instance = super.build();
>       if (instance.domainContent != null) {
> ```

If `instance.domainContent` is null, shouldn't this throw an error?  That can't be valid, right?
___
*[core/src/main/java/google/registry/model/domain/secdns/DelegationSignerDataBase.java, line 35 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0UmsKCgNarXwbDlN4:-MK0UmsLCuTc2-eAGWE0:beg3mve) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/core/src/main/java/google/registry/model/domain/secdns/DelegationSignerDataBase.java#L35)):*
> ```Java
> @MappedSuperclass
> @Access(AccessType.FIELD)
> public abstract class DelegationSignerDataBase extends ImmutableObject
> ```

This is so ugly :/  It goes away when we move away from Datastore though right?
___
*[db/src/main/resources/sql/flyway.txt, line 65 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0Scne8yUI3JGflenR:-MK0Scne8yUI3JGflenS:bk4h9ku) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/db/src/main/resources/sql/flyway.txt#L65)):*
> ```vimhelp
> V63__add_schema_for_ds_data.sql
> V64__transfer_history_columns.sql
> V65__use_all_fields_in_ds_as_primary_key_and_add_its_history_talbe.sql
> ```

Typo in filename ("talbe").  Also this can be shorter and simpler.
___
*[db/src/main/resources/sql/flyway/V65__use_all_fields_in_ds_as_primary_key_and_add_its_history_talbe.sql, line 21 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0T0k3452f5Fre-SfU:-MK0T0k3452f5Fre-SfV:b-xr34wm) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/db/src/main/resources/sql/flyway/V65__use_all_fields_in_ds_as_primary_key_and_add_its_history_talbe.sql#L21)):*
> ```TSQL
>     primary key (key_tag, algorithm, digest_type, digest);
> 
> create table "DelegationSignerDataHistory" (
> ```

There's inconsistency here between the table name and the field names.  The id field name calls it `ds_data`, yet the table name is `DelegationSignerData`.  We need to standardize on a name and fix up all these tables.  Personally I think that `DelegationSignerData` is itself too long.

Given how these are subsidiary tables to the `Domain` table, I think `DomainDsData` and `DomainDsDataHistory` would be better table names.
___
*[db/src/main/resources/sql/schema/db-schema.sql.generated, line 234 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0TM9Y0sNa-xSlwgGp:-MK0TM9Y0sNa-xSlwgGq:b-d8nelh) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/db/src/main/resources/sql/schema/db-schema.sql.generated#L234)):*
> ```
>         digest_type int4 not null,
>         key_tag int4 not null,
>         domain_repo_id text,
> ```

Should the `domain_repo_id` be part of the primary key/uniqueness constraint too?  As written it seems to me that this would error out if registrars tried to reuse the same DS data across multiple domains?  (Not that that would necessarily be valid, but it's not our job to enforce it.)

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/841)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 176 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0UdH56a1eO2pImLko:-MK1WPosAMpwsHrEZkiv:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/core/src/main/java/google/registry/model/domain/DomainHistory.java#L176)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Given that it's returning a `nullToEmptyImmutableCopy()`, the return type should be `ImmutableSet`.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 307 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0U_-A19PpKWfqUBXh:-MK1YnLG50ng5wSWXQ_o:b6rvyxd) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/core/src/main/java/google/registry/model/domain/DomainHistory.java#L307)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

If `instance.domainContent` is null, shouldn't this throw an error?  That can't be valid, right?
</blockquote></details>

Ideally that is correct, however, in practice, we may need to create a `HistoryEntry` instance first(domainContent is null), use that to create `billingEvent`, `pollMessage`, etc. for the `domainBase`instance, finally, create the `domainHistory`.
___
*[db/src/main/resources/sql/flyway.txt, line 65 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0Scne8yUI3JGflenR:-MK1gq1FBSa9xaLeB9cw:b9oionq) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/db/src/main/resources/sql/flyway.txt#L65)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Typo in filename ("talbe").  Also this can be shorter and simpler.
</blockquote></details>

reworded it a little bit.
___
*[db/src/main/resources/sql/schema/db-schema.sql.generated, line 234 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0TM9Y0sNa-xSlwgGp:-MK24YD16cCh7QdsMHjJ:b-g1hs46) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/db/src/main/resources/sql/schema/db-schema.sql.generated#L234)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should the `domain_repo_id` be part of the primary key/uniqueness constraint too?  As written it seems to me that this would error out if registrars tried to reuse the same DS data across multiple domains?  (Not that that would necessarily be valid, but it's not our job to enforce it.)
</blockquote></details>

Makes sense, done.
___
*[core/src/main/java/google/registry/model/domain/secdns/DelegationSignerDataBase.java, line 35 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0UmsKCgNarXwbDlN4:-MK1_Oxb7ehWgL9INH9a:ba98nu0) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/core/src/main/java/google/registry/model/domain/secdns/DelegationSignerDataBase.java#L35)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is so ugly :/  It goes away when we move away from Datastore though right?
</blockquote></details>

You mean the `DelegationSignerDataBase` class itself is ugly?If so, unfortunately, it probably won't disappear after the migration. Mainly because Hibernate doesn't allow override the `@Id` property, as `DelegationSignerData` and `DelegationSignerDataHistory` have different primary keys (4 fields composite key vs dsDataHistoryId as key), we have to define the common fields in this base class and add `@Id` annotation in its subclass.
___
*[db/src/main/resources/sql/flyway/V65__use_all_fields_in_ds_as_primary_key_and_add_its_history_talbe.sql, line 21 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0T0k3452f5Fre-SfU:-MK1jyJI-T0cXMPQ7ZH9:b-frx2em) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/db/src/main/resources/sql/flyway/V65__use_all_fields_in_ds_as_primary_key_and_add_its_history_talbe.sql#L21)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There's inconsistency here between the table name and the field names.  The id field name calls it `ds_data`, yet the table name is `DelegationSignerData`.  We need to standardize on a name and fix up all these tables.  Personally I think that `DelegationSignerData` is itself too long.

Given how these are subsidiary tables to the `Domain` table, I think `DomainDsData` and `DomainDsDataHistory` would be better table names.
</blockquote></details>

I renamed both the base class and the history class but will do it for `DelegationSignerData` in a subsequent PR to help us focus on the schema in this PR.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/841)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 307 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0U_-A19PpKWfqUBXh:-MK0dPJm88zokcv-Tib_:b-chwe0w) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/core/src/main/java/google/registry/model/domain/DomainHistory.java#L307)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

Ideally that is correct, however, in practice, we may need to create a `HistoryEntry` instance first(domainContent is null), use that to create `billingEvent`, `pollMessage`, etc. for the `domainBase`instance, finally, create the `domainHistory`.
</blockquote></details>

This builder is also used to convert legacy HistoryEntry objects to DomainHistory, when domainContent is not available.
The null check needs to stay until after migration to Cloud SQL. Afterwards we may be able to drop it.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/841)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @hstonec and @weiminyu)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 307 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0U_-A19PpKWfqUBXh:-MKGX7GW5XsDbwAULk14:b-arhuxn) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/core/src/main/java/google/registry/model/domain/DomainHistory.java#L307)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This builder is also used to convert legacy HistoryEntry objects to DomainHistory, when domainContent is not available.
The null check needs to stay until after migration to Cloud SQL. Afterwards we may be able to drop it. 
</blockquote></details>

Can we add code comments to this effect then?
___
*[core/src/main/java/google/registry/model/domain/secdns/DelegationSignerData.java, line 218 at r2](https://reviewable.io/reviews/google/nomulus/841#-MKGXgClEYLFS1U14-Mm:-MKGXgClEYLFS1U14-Mn:b-rt3cfl) ([raw file](https://github.com/google/nomulus/blob/8a25d8865f3d743ef639778824878f0cccf62ac2/core/src/main/java/google/registry/model/domain/secdns/DelegationSignerData.java#L218)):*
> ```Java
>      */
>     @SuppressWarnings("unused")
>     private void setAlgorithm(int algorithm) {
> ```

Gus had some way to potentially not have to have all of these boilerplate getters/setters.  Ask him?  @gbrodman

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/841#-:-MKGY0YQ1d4Ys0GBRNqO:bnfp4nl)* status: 0 of 14 files reviewed, 2 unresolved discussions (waiting on @hstonec and @weiminyu)

**Review by weiminyu — APPROVED** [review]
> Reviewed 2 of 14 files at r1, 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/841)* status: all files reviewed, 2 unresolved discussions (waiting on @hstonec and @weiminyu)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/841)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @hstonec, and @weiminyu)

___
*[core/src/main/java/google/registry/model/domain/secdns/DelegationSignerData.java, line 218 at r2](https://reviewable.io/reviews/google/nomulus/841#-MKGXgClEYLFS1U14-Mm:-MKL0L5TDR-OWOs0PVID:b3to17x) ([raw file](https://github.com/google/nomulus/blob/8a25d8865f3d743ef639778824878f0cccf62ac2/core/src/main/java/google/registry/model/domain/secdns/DelegationSignerData.java#L218)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Gus had some way to potentially not have to have all of these boilerplate getters/setters.  Ask him?  @gbrodman 
</blockquote></details>

They might or might not be required here. In another case where we only used `@Access(AccessType.FIELD)` they weren't necessary, but there there's kind of a mix so I don't know how Hibernate would treat it. Worth trying out.

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/841)* status: 5 of 14 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/model/domain/DomainHistory.java, line 307 at r1](https://reviewable.io/reviews/google/nomulus/841#-MK0U_-A19PpKWfqUBXh:-MKpm5d42pwze8sPFNaX:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cbe860962c8cb3609b86251e199f4e207354a4dc/core/src/main/java/google/registry/model/domain/DomainHistory.java#L307)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Can we add code comments to this effect then?
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/model/domain/secdns/DelegationSignerData.java, line 218 at r2](https://reviewable.io/reviews/google/nomulus/841#-MKGXgClEYLFS1U14-Mm:-MKpoLKF1EqTXdBucUXv:b-b7pfz4) ([raw file](https://github.com/google/nomulus/blob/8a25d8865f3d743ef639778824878f0cccf62ac2/core/src/main/java/google/registry/model/domain/secdns/DelegationSignerData.java#L218)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

They might or might not be required here. In another case where we only used `@Access(AccessType.FIELD)` they weren't necessary, but there there's kind of a mix so I don't know how Hibernate would treat it. Worth trying out. 
</blockquote></details>

Yeah, in this case, the entity uses both `@Access(AccessType.RPOERTY)` and `@Access(AccessType.FIELD)` so the getters/sertters became required.

**Pull request merged**
