### PR TITLE
Add method to show readable key info

### PR DESCRIPTION
**Pull request by rachelguan**
Currently, there's only pretty print ofy key info not vkey. If we are replacing ofy keys with vkeys, we need to replace the output statement about ofy keys with vkeys' as well. 

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1431)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: all files reviewed, 2 unresolved discussions (waiting on @rachelguan)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 321 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCeeFO5OKG69O-A3NU:-MpCeeFO5OKG69O-A3NV:b-2bevt3) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L321)):*
> ```Java
>    * or both.
>    */
>   public String getInfo() {
> ```

Can we just make this override `toString()`?  I don't think we're losing anything by overriding `ImmutableObject.toString()`, that's just intended to provide a readable representation -- yours will be more readable.

This will allow us to avoid the `getInfo()` invocations every place we put this into a log message.
___
*[core/src/main/java/google/registry/persistence/VKey.java, line 324 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCfDrR6aWBzOSyn7fe:-MpCfDrR6aWBzOSyn7ff:b-awyz5c) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L324)):*
> ```Java
>     if (maybeGetOfyKey().isPresent() && maybeGetSqlKey().isPresent()) {
>       return String.format(
>           "VKey<%s>(sqlKey:%s,ofyKey:%s)",
> ```

Optional: In the interest of brevity, I would omit the "Key" suffix and just make this "`sql:%s,ofy:%s`".  Below, also.
___
*[core/src/main/java/google/registry/persistence/VKey.java, line 325 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCg8u23GUF4EKDpdeZ:-MpCg8u23GUF4EKDpde_:b3lr0tf) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L325)):*
> ```Java
>       return String.format(
>           "VKey<%s>(sqlKey:%s,ofyKey:%s)",
>           getKind().getSimpleName(), getSqlKey().toString(), getOfyKey().getName());
> ```

The ofy key doesn't necessarily have a name.  It can be either a name or a (long) id.  I'm also wondering about whether it should include the ofy kind.  I think this should always be the same as the VKey kind, but I'll verify that.  If for some reason that's not always true, we'll want to display it, at least if it's different.
___
*[core/src/test/java/google/registry/tools/GetResourceByKeyCommandTest.java, line 215 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCj9wi1lO_tMdHwGTf:-MpCj9wi1lO_tMdHwGTg:bupeq8) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/test/java/google/registry/tools/GetResourceByKeyCommandTest.java#L215)):*
> ```Java
>     assertThat(thrown)
>         .hasMessageThat()
>         .contains("Could not load resource for key: VKey<DomainBase>(sqlKey:2-TLD,ofyKey:2-TLD)");
> ```

In general, this is going to be a big improvement over what we get from `ImmutableObject`. :-)

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @mindhog and @rachelguan)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 321 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCeeFO5OKG69O-A3NU:-MpDYNAp2Ws0i1jJnpCt:bv6u3br) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L321)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can we just make this override `toString()`?  I don't think we're losing anything by overriding `ImmutableObject.toString()`, that's just intended to provide a readable representation -- yours will be more readable.

This will allow us to avoid the `getInfo()` invocations every place we put this into a log message.
</blockquote></details>

I didn't use toString() because I was thinking that since there're lots of toString() in our code, it's hard to find this particular method if we want to do code search. But I understand your reasons so i changed it to toString()
___
*[core/src/main/java/google/registry/persistence/VKey.java, line 324 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCfDrR6aWBzOSyn7fe:-MpDZSfo6LzbszRZledH:b-rns92z) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L324)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Optional: In the interest of brevity, I would omit the "Key" suffix and just make this "`sql:%s,ofy:%s`".  Below, also.
</blockquote></details>

I actually thought about  changing to that to utilize the lookup keys that are already in the file but i wanted to include keys since we've been calling them and sqlKeys.. done!

**Review by mindhog — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: all files reviewed, 1 unresolved discussion (waiting on @rachelguan)

**Review by mindhog — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @rachelguan)

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 325 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCg8u23GUF4EKDpdeZ:-MpleZt89Nt3yD9iE4ZW:bsrc2jb) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L325)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

The ofy key doesn't necessarily have a name.  It can be either a name or a (long) id.  I'm also wondering about whether it should include the ofy kind.  I think this should always be the same as the VKey kind, but I'll verify that.  If for some reason that's not always true, we'll want to display it, at least if it's different.
</blockquote></details>

so now for ofykey string, i will be using either name or id, depending on the availability. I'm not sure how to create a vkey with kind that's from ofy kind. It throws an error if I try to create such vkey via VKey.create() since it requires Key and VKey to have the same class.

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mindhog and @rachelguan)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 325 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCg8u23GUF4EKDpdeZ:-Mpm4MQC9-P1wGqaE-AL:bqfir5w) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L325)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

so now for ofykey string, i will be using either name or id, depending on the availability. I'm not sure how to create a vkey with kind that's from ofy kind. It throws an error if I try to create such vkey via VKey.create() since it requires Key and VKey to have the same class. 
</blockquote></details>

yes,  the "name or id" approach works.  Though you should probably add a test (I think you can probably even use an entity type with a string key -- just Key.create() the ofy key with a long id instead of a string).

Does your question on creating a vkey relate to this PR?

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 325 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCg8u23GUF4EKDpdeZ:-MpmFqPa4IE2pPo855WN:b-jo2iqq) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L325)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

yes,  the "name or id" approach works.  Though you should probably add a test (I think you can probably even use an entity type with a string key -- just Key.create() the ofy key with a long id instead of a string).

Does your question on creating a vkey relate to this PR?  
</blockquote></details>

added a toString() test case such that the name and id cases will be indirectly tested. 
and yes it is related to this PR.

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mindhog and @rachelguan)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 325 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCg8u23GUF4EKDpdeZ:-MpmRlUm1mhMmVendsUh:b-32lqyu) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L325)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

added a toString() test case such that the name and id cases will be indirectly tested. 
and yes it is related to this PR. 
</blockquote></details>

I'm guessing what you meant to ask is how to "create a vkey with kind that's *different* from ofy kind," is that correct?  I might be missing something, but it doesn't look like any of the `VKey.create()` methods currently enforce this (perhaps they should).  Is this to test `toString()` in the case where the two classes differ?
If we're enforcing this as an invariant,  you shouldn't have to do anything special for it in `toString()`.  If we're not, it would be helpful to have the ofy kind visible in the `toString()` output _if it differs from the vkey kind_.

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @mindhog)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 325 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCg8u23GUF4EKDpdeZ:-MpqKqOP3qN8Iw9Urt-m:b-fazn0e) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L325)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I'm guessing what you meant to ask is how to "create a vkey with kind that's *different* from ofy kind," is that correct?  I might be missing something, but it doesn't look like any of the `VKey.create()` methods currently enforce this (perhaps they should).  Is this to test `toString()` in the case where the two classes differ?
If we're enforcing this as an invariant,  you shouldn't have to do anything special for it in `toString()`.  If we're not, it would be helpful to have the ofy kind visible in the `toString()` output _if it differs from the vkey kind_.
</blockquote></details>

In any case, I think this PR is good as is.  We can discuss the "differing kinds" issue out-of-band, if you like.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1431)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @mindhog)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 325 at r1](https://reviewable.io/reviews/google/nomulus/1431#-MpCg8u23GUF4EKDpdeZ:-MpqdvQN6KcZrgDcigmU:b-c8n17v) ([raw file](https://github.com/google/nomulus/blob/525590d23e9d28edddd2ad3c6c8b026d427bc12e/core/src/main/java/google/registry/persistence/VKey.java#L325)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

In any case, I think this PR is good as is.  We can discuss the "differing kinds" issue out-of-band, if you like.
</blockquote></details>

yes that's exactly what i was trying to figure out. If there's a variant (vkey kind different from ofy kind), what format should i use to display and more importantly, how to create such vkey. 

i would like to discuss that outside of this PR.

**Pull request merged**
