### PR TITLE
Save db discrepancies to GCS

### PR DESCRIPTION
**Pull request by weiminyu**
Adds support for saving discrepancies in database comparison to a GCS bucket.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1527)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1527)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)

___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java, line 164 at r1](https://reviewable.io/reviews/google/nomulus/1527#-Mx0wXna8TZWpd581yG1:-Mx0wXnbEo9raUCglMwz:bg2q23b) ([raw file](https://github.com/google/nomulus/blob/9e1ef56780ad70fa43b265d5b3c84edb119a59a5/core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java#L164)):*
> ```Java
>           "Failed to parse one or both entities:\n%s\n%s\n",
>           Matcher.quoteReplacement(entry0.toString()).replaceAll("\n", "\n> "),
>           Matcher.quoteReplacement(entry1.toString()).replaceAll("\n", "\n< "));
> ```

Can we use `google.registry.util.DiffUtils` here to get  a fancy diff?

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1527)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java, line 164 at r1](https://reviewable.io/reviews/google/nomulus/1527#-Mx0wXna8TZWpd581yG1:-Mx1-C1m7eEIRIyBlIQA:b-896fix) ([raw file](https://github.com/google/nomulus/blob/9e1ef56780ad70fa43b265d5b3c84edb119a59a5/core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java#L164)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can we use `google.registry.util.DiffUtils` here to get  a fancy diff? 
</blockquote></details>

Done.

**Review by mindhog — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1527)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @weiminyu)

**Review by mindhog — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1527#-:-Mx11EeJ7kFcwYGQGEpj:bb6ywmx)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @weiminyu)

**Pull request merged**
