### PR TITLE
Find a suitable version of python.

### PR DESCRIPTION
**Pull request by mindhog**
When running presubmit, we were using /usr/bin/python3, which works fine on
systems that have a reasonably recent python version there.  However, our CI
system has a very old version of python there and prefers the use of "pyenv"
to modify the PATH to provide the desired version of python as simply
"python".  So add a check to use the first of "python" or "/usr/bin/python3"
that is at least version 3.7.3.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1338)

### CODE REVIEW

**Comment by jianglai** [comment]
Is this PR still necessary per cl/398550449?

**Review by mindhog — COMMENTED** [review]
Yes.  The fundamental problem is that we run /usr/bin/python3, which isn't the version that we install on the CI machines (but is on most developer machines). 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1338#-:-MkNEgd73sLzWikpX2Id:bfns8xd)* status: 0 of 2 files reviewed, all discussions resolved

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1338)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[build.gradle, line 215 at r2](https://reviewable.io/reviews/google/nomulus/1338#-MkbCVEm3Gh1RrWgW2CY:-MkbCVEn-6_1SubRYo4G:b-betj4d) ([raw file](https://github.com/google/nomulus/blob/cd4c681cc7d0a7970df31c520ac483534c9e9428/build.gradle#L215)):*
> ```
> 0x3060000 // should be 0x3070300
> ```
I don't understand the comment here? If it should be `0x3070300`, why is it not?

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1338)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[build.gradle, line 215 at r2](https://reviewable.io/reviews/google/nomulus/1338#-MkbCVEm3Gh1RrWgW2CY:-MkbCbWwAxgKNiRaC9SC:b-um1onv) ([raw file](https://github.com/google/nomulus/blob/cd4c681cc7d0a7970df31c520ac483534c9e9428/build.gradle#L215)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> 0x3060000 // should be 0x3070300
> ```
I don't understand the comment here? If it should be `0x3070300`, why is it not?
</blockquote></details>

sorry, I just caught that myself.  It was for debugging before the kokoro change went through. Fixed.

**Review by jianglai — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1338)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Pull request merged**
