### PR TITLE
Add angular signals and computed to the console

### PR DESCRIPTION
**Pull request by ptkach**
This change aims to simplify codebase by adding Angular 17 features, like signals, computed, @if/for directives to the codebase in places where we used to rely on rxjs subscription and less convenient html directives. 

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2308)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
can you clarify what "signals" and "computed" mean? Just looking at the PR description it's not clear. 

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2308#-:-NpLrFtC10zFSm6reTi5:b8290px)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/contact/contact.component.html` line 1 at r1](https://reviewable.io/reviews/google/nomulus/2308#-NpMPMaaDxQAJxIsd0bT:-NpMPMaaDxQAJxIsd0bU:b-jdnd99) ([raw file](https://github.com/google/nomulus/blob/fb5a9889c6d9fd18b4a0b77049f6e6e597974529/console-webapp/src/app/settings/contact/contact.component.html#L1)):*
> ```HTML
> @if (loading) {
> ```

what's the difference between the previous notations (using ngIf) versus these @-based annotations? Or, put another way, why would we want to use this over the other way? 
___
*[`console-webapp/src/app/settings/contact/contact.component.html` line 16 at r1](https://reviewable.io/reviews/google/nomulus/2308#-NpMPVBPC3yPrOGfr_am:-NpMPVBPC3yPrOGfr_an:b-i5wky6) ([raw file](https://github.com/google/nomulus/blob/fb5a9889c6d9fd18b4a0b77049f6e6e597974529/console-webapp/src/app/settings/contact/contact.component.html#L16)):*
> ```HTML
>     <h1>No contacts found</h1>
>   </div>
>   @for (group of groupedContacts(); track group.emailAddress) {
> ```

what does the "track" do? 
___
*[`console-webapp/src/app/settings/contact/contact.component.ts` line 122 at r1](https://reviewable.io/reviews/google/nomulus/2308#-NpMOATqAj-tJWAEP_kx:-NpMOATqAj-tJWAEP_ky:b88bmu6) ([raw file](https://github.com/google/nomulus/blob/fb5a9889c6d9fd18b4a0b77049f6e6e597974529/console-webapp/src/app/settings/contact/contact.component.ts#L122)):*
> ```XML
>       contact.types.forEach((type) => {
>         acc
>           .find((group: GroupedContacts) => group.value === type)
> ```

the syntax highlighting here is odd, I think we might want to use a different variable name than `type`

**Review by gbrodman — CHANGES_REQUESTED** [review]
weird it doesn't look to me like the commit message is updated? not sure what happened

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2308#-:-NpRGL-jCy0VTW63vYLo:b-vzs96w)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/contact/contact.component.html` line 10 at r2](https://reviewable.io/reviews/google/nomulus/2308#-NpRGVkD1LVbD-avrFRC:-NpRGVkD1LVbD-avrFRD:btiyozj) ([raw file](https://github.com/google/nomulus/blob/00c2c990f0e67db8edbb73d2802a08e3ec090731/console-webapp/src/app/settings/contact/contact.component.html#L10)):*
> ```HTML
>     <div
>       class="contact__empty-contacts"
>       *ngIf="contactService.contacts.length === 0"
> ```

i think we can remove this ngIf now, right?

**Review by ptkach — COMMENTED** [review]
I added the word "angular", not sure if you meant something else

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2308#-:-NpVO1uY0xQ-lHclNpCS:bjhhd5t)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`console-webapp/src/app/settings/contact/contact.component.html` line 10 at r2](https://reviewable.io/reviews/google/nomulus/2308#-NpRGVkD1LVbD-avrFRC:-NpVO7Pq5_bW2R9_S9fI:b-896fix) ([raw file](https://github.com/google/nomulus/blob/00c2c990f0e67db8edbb73d2802a08e3ec090731/console-webapp/src/app/settings/contact/contact.component.html#L10)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think we can remove this ngIf now, right?
</blockquote></details>

Done.

**Review by gbrodman — COMMENTED** [review]
"computed" doesn't really make sense because it's not a thing (it's just a type of signal) 

maybe some explanation of what this is and/or why we're adding it? Like, something about using signals to manage the registrar state instead of doing that manually? Not sure 

I think the formatting is failing 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2308#-:-NpWcvohAXJzaRjQq1qE:b-pdexbg)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by ptkach — COMMENTED** [review]
Updated description, fixed the formatting

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2308#-:-Np_qu440H4Us7yNrzGf:b-bgy1zu)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
