### PR TITLE
Use detaching queries for all criteria queries

### PR DESCRIPTION
**Pull request by mindhog**
Add a query(CriteriaQuery) method to JpaTransactionManager and replace all of the criteria query executions with it.  The new query method wraps the underlying TypedQuery with a DetachingTypedQuery, enabling "detach on load" for all criteria query objects.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1192)

### CODE REVIEW

**Review by gbrodman — COMMENTED** [review]
Thoughts on creating a presubmit check that verifies that we don't call `jpaTm().getEntityManager().createQuery(` except in existing allowed cases? I'm assuming we want to detach at pretty much all times. 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1192#-:-MbN-VInDUxi8iqJCjXD:b-lq0aqm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Review by mindhog — COMMENTED** [review]
I'm in favor. Though we might want to try to just lock out the entity manager instead and provide access methods for just the parts of it that we still need.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1192#-:-MbN2OeQ0Z2LG4aX3nxg:blw4v8v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Review by gbrodman — APPROVED** [review]
Can you file that as a bug in the appropriate place (wherever that is), please? LGTM overwise 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1192#-:-MbNCSbn7ij4sxNRG679:bpm16y1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Review by mindhog — COMMENTED** [review]
Added b/190206415

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1192#-:-MbNJBtjB9hB893CS3qg:bpp05ue)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Pull request merged**
