### PR TITLE
Fix Datastore "count" queries

### PR DESCRIPTION
**Pull request by mindhog**
The objectify "count()" method doesn't work for result sets larger than 1000
elements, use the original trick from "count domains" that fetches the keys
and counts them.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1201)

### CODE REVIEW

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1201)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 485 at r1](https://reviewable.io/reviews/google/nomulus/1201#-Mbgm7SE9aVXnNFLXp2j:-Mbgm7SE9aVXnNFLXp2k:b8u0nmh) ([raw file](https://github.com/google/nomulus/blob/9f2b2dc36e456630c800e0a9e0bc1195a6af77aa/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L485)):*
> ```Java
>       // Objectify provides a count() function, but unfortunately that doesn't work if there are
>       // more than 1000 (the default response page size?) entries in the database.  We use
>       // chunkAll() here as it provides a nice performance boost.
> ```

Provide a relevant link with more information.

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1201)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 485 at r1](https://reviewable.io/reviews/google/nomulus/1201#-Mbgm7SE9aVXnNFLXp2j:-Mbgp2tI1x-sKZFXtfBl:b8amzrp) ([raw file](https://github.com/google/nomulus/blob/9f2b2dc36e456630c800e0a9e0bc1195a6af77aa/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L485)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Provide a relevant link with more information.
</blockquote></details>

Can you describe what information you're looking for?  I haven't found anything documenting the 1000 max limitation aside from a [SO question suggesting that this had been fixed.](https://stackoverflow.com/questions/751124/how-does-one-get-a-count-of-rows-in-a-datastore-model-in-google-app-engine)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1201)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 485 at r1](https://reviewable.io/reviews/google/nomulus/1201#-Mbgm7SE9aVXnNFLXp2j:-MbgsmYf1OjqpHvz4UnT:b-izfp9j) ([raw file](https://github.com/google/nomulus/blob/9f2b2dc36e456630c800e0a9e0bc1195a6af77aa/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L485)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can you describe what information you're looking for?  I haven't found anything documenting the 1000 max limitation aside from a [SO question suggesting that this had been fixed.](https://stackoverflow.com/questions/751124/how-does-one-get-a-count-of-rows-in-a-datastore-model-in-google-app-engine)
</blockquote></details>

StackOverflow is fine.

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1201)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 485 at r1](https://reviewable.io/reviews/google/nomulus/1201#-Mbgm7SE9aVXnNFLXp2j:-MbguM3r8PwotA08YD1h:b-896fix) ([raw file](https://github.com/google/nomulus/blob/9f2b2dc36e456630c800e0a9e0bc1195a6af77aa/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L485)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

StackOverflow is fine.
</blockquote></details>

Done.

**Pull request merged**
