### PR TITLE
Add a method to set a "not in" WHERE clause in CriteriaQueryBuilder

### PR DESCRIPTION
**Pull request by jianglai**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1225)

### CODE REVIEW

**Review by gbrodman — COMMENTED** [review]
This is fine, but why bother adding it in if we don't use it? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1225#-:-MdOYGmV2ui1QxmrI6Wo:b-e2g1nv)* status: 0 of 2 files reviewed, all discussions resolved

**Review by jianglai — COMMENTED** [review]
It was used in the RDE migration PR, before I switched to using JPQL directly. I figured since I already wrote the code, we might as well merge it seeing that it can be useful in the future.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1225#-:-MdS1nVW1Bi966ODrk-U:bpwta54)* status: 0 of 2 files reviewed, all discussions resolved

**Review by jianglai — COMMENTED** [review]
Ping?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1225#-:-MdbhpHqBAQWJnm868HG:b-82oq9k)* status: 0 of 2 files reviewed, all discussions resolved

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
