### PR TITLE
Statically import Truth.assertThat() in tests

### PR DESCRIPTION
**Pull request by CydeWeys**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2395)

### CODE REVIEW

**Review by ptkach — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2395)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Comment by CydeWeys** [comment]
PTAL, had to make some more changes.

**Review by ptkach — APPROVED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2395)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

___
*[`core/src/test/java/google/registry/testing/GsonSubject.java` line 56 at r2](https://reviewable.io/reviews/google/nomulus/2395#gh-1556119427:-NuynYL7-D8ypcG2Cyts:b-kakm6e) ([raw file](https://github.com/google/nomulus/blob/8ac925b8cfb74c5b6b6527a43f6d863446fd526b/core/src/test/java/google/registry/testing/GsonSubject.java#L56)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Confusing overloading of methods

Method GsonSubject.isEqualTo(..) could be confused with overloaded method [Subject.isEqualTo](1), since dispatch depends on static types.

[Show more details](https://github.com/google/nomulus/security/code-scanning/6817)
</blockquote></details>

It doesn't seem like we care about this one?

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2395)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`core/src/test/java/google/registry/testing/GsonSubject.java` line 56 at r2](https://reviewable.io/reviews/google/nomulus/2395#gh-1556119427:-NuyoqpTEm94u3dA6SXE:bnbgpru) ([raw file](https://github.com/google/nomulus/blob/8ac925b8cfb74c5b6b6527a43f6d863446fd526b/core/src/test/java/google/registry/testing/GsonSubject.java#L56)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

It doesn't seem like we care about this one?
</blockquote></details>

Actually I was able to remove this method.

**Review by ptkach — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2395)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Review by CydeWeys — COMMENTED** [review]
... and I guess that means I need yet another LGTM.  PTAL.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2395#-:-NuzQkjm-ZXqN5Lb7mPd:b-9zhtz2)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Review by ptkach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2395)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Pull request merged**
