### PR TITLE
Skip poll messages on deletions for configured registrars

### PR DESCRIPTION
**Pull request by gbrodman**
See b/379331882 for more details

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2613)

### CODE REVIEW

**Review by gbrodman — COMMENTED** [review]
synced up offline and I think we're leaning toward this route, though with some logging and a different configuration point. The internal portion of the tests on this PR will likely fail until https://team-review.git.corp.google.com/c/domain-registry-eng/nomulus-internal/+/2382122 is merged. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2613#-:-OCEvx4vDjnjW1YIaDsg:b-vt0wyj)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[`core/src/main/java/google/registry/flows/domain/DomainDeleteFlow.java` line 217 at r1](https://reviewable.io/reviews/google/nomulus/2613#-OCE8Bo3CSp3GdhmMD9_:-OCEw3xvB1_OARQzbxtL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/3967dbd0cea39e23377b32b85037c75f04ec19f5/core/src/main/java/google/registry/flows/domain/DomainDeleteFlow.java#L217)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It's not clear to me why this list is used as a proxy for the registrars for which poll message insertion should be skipped.
</blockquote></details>

Done.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2613)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/flows/domain/DomainRestoreRequestFlow.java` line 186 at r2](https://reviewable.io/reviews/google/nomulus/2613#-OCF-4Or-Tb2W1DVQDtR:-OCF-4OsDSAytmhJyJRv:b-eho7pe) ([raw file](https://github.com/google/nomulus/blob/2fbd96ffab82f8a48245690b360147e53cd23ddc/core/src/main/java/google/registry/flows/domain/DomainRestoreRequestFlow.java#L186)):*
> ```Java
>     entitiesToSave.add(newDomain, domainHistory, autorenewEvent, autorenewPollMessage);
>     tm().putAll(entitiesToSave.build());
>     if (existingDomain.getDeletePollMessage() != null) {
> ```

Add a test for this case.

**Review by jianglai — APPROVED** [review]
LGTM, other than the test that Ben requested.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2613#-:-OCF-Hjy3DCSWHVOUn3b:b-lk13rj)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2613)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[`core/src/main/java/google/registry/flows/domain/DomainRestoreRequestFlow.java` line 186 at r2](https://reviewable.io/reviews/google/nomulus/2613#-OCF-4Or-Tb2W1DVQDtR:-OCF3dsg2bSqfERiEu77:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2fbd96ffab82f8a48245690b360147e53cd23ddc/core/src/main/java/google/registry/flows/domain/DomainRestoreRequestFlow.java#L186)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Add a test for this case.
</blockquote></details>

Done.

**Comment by gbrodman** [comment]
as mentioned above, the kokoro-internal test failure is expected until https://team-review.git.corp.google.com/c/domain-registry-eng/nomulus-internal/+/2382122 goes in

**Comment by gbrodman** [comment]
@CydeWeys any further thoughts?

**Review by CydeWeys — COMMENTED** [review]
No, it seems straightforward.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2613#-:-OCFn1LDAWbUlvG-LWD8:bkgbfwl)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @jianglai)

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2613#-:-OCFn3Dg9I1JlCx-ibWp:bnfp4nl)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
