### PR TITLE
Rename DomainBase -> Domain

### PR DESCRIPTION
**Pull request by CydeWeys**
This was a long time coming, but we couldn't do it until we left Datastore, as
the Java class name has to match the Datastore entity name.

Subsequent PRs will rename ContactResource to Contact and HostResource to Host,
so that everything matches the SQL table names (and is shorter!).

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1725)

### CODE REVIEW

**Review by CydeWeys — COMMENTED** [review]
+reviewer:@jianglai 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1725#-:-N8PCTn9D8qtuduETaVo:b81r1qu)* status: 0 of 223 files reviewed, all discussions resolved (waiting on @gbrodman and @jianglai)

**Review by gbrodman — COMMENTED** [review]
will review this now that i'm back 

> Reviewed 4 of 223 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1725#-:-N8UDlTh-pOZXjr_TydA:b-vcbgsk)* status: 4 of 223 files reviewed, all discussions resolved (waiting on @jianglai)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 219 of 223 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1725)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[`core/src/main/java/google/registry/model/domain/DomainContent.java` line 94 at r1](https://reviewable.io/reviews/google/nomulus/1725#-N8UgUwJ-Kf8nvxUCIHf:-N8UgUwJ-Kf8nvxUCIHg:bx5poqc) ([raw file](https://github.com/google/nomulus/blob/5d559085d7bf3ef6829d413798567db242c5d014/core/src/main/java/google/registry/model/domain/DomainContent.java#L94)):*
> ```Java
>  * the DB itself or as part of another entity.
>  *
>  * <p>For historical reasons, the name of this class is "DomainContent". Ideally it would be
> ```

technically we should probably also rename this to `DomainBase` like the comment says, but up to you if we should do that in a future PR or not. 
___
*[`core/src/main/java/google/registry/reporting/icann/TransactionsReportingQueryBuilder.java` line 78 at r1](https://reviewable.io/reviews/google/nomulus/1725#-N8UgwqeC9sJ1TOEcN6G:-N8UgwqeC9sJ1TOEcN6H:b-rm4sks) ([raw file](https://github.com/google/nomulus/blob/5d559085d7bf3ef6829d413798567db242c5d014/core/src/main/java/google/registry/reporting/icann/TransactionsReportingQueryBuilder.java#L78)):*
> ```Java
>     if (tm().isOfy()) {
>       registrarIanaIdQuery =
>           SqlTemplate.create(getQueryFromFile("registrar_iana_id.sql"))
> ```

delete this sql file too? (same question for all the other ones)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1725)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[`core/src/main/java/google/registry/model/domain/DomainContent.java` line 94 at r1](https://reviewable.io/reviews/google/nomulus/1725#-N8UgUwJ-Kf8nvxUCIHf:-N8UomBt-_OLPcZlBCkM:b-d34sh7) ([raw file](https://github.com/google/nomulus/blob/5d559085d7bf3ef6829d413798567db242c5d014/core/src/main/java/google/registry/model/domain/DomainContent.java#L94)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

technically we should probably also rename this to `DomainBase` like the comment says, but up to you if we should do that in a future PR or not. 
</blockquote></details>

Definitely not going to add that to this already long enough PR.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1725)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/reporting/icann/TransactionsReportingQueryBuilder.java` line 78 at r1](https://reviewable.io/reviews/google/nomulus/1725#-N8UgwqeC9sJ1TOEcN6G:-N8UplnuEXlDRp-eg_TN:b-896fix) ([raw file](https://github.com/google/nomulus/blob/5d559085d7bf3ef6829d413798567db242c5d014/core/src/main/java/google/registry/reporting/icann/TransactionsReportingQueryBuilder.java#L78)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

delete this sql file too? (same question for all the other ones)
</blockquote></details>

Done.

**Review by CydeWeys — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1725#-:-N8UqwGh-dyD_Vck5tKt:bb71pro)* status: 166 of 231 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

**Review by gbrodman — APPROVED** [review]
> Reviewed 65 of 65 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
