### PR TITLE
Remove DatabaseSnapshot

### PR DESCRIPTION
**Pull request by jianglai**
It is no longer being used.

Note: this PR is identical to #2105. For reasons that I don't understand, that PR still fails presubmit tests due to `TldTest` failures, which is fixed in #2107 and patched into that PR already.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2110)

### CODE REVIEW

**Review by weiminyu — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Comment by jianglai** [comment]
@weiminyu any idea `TldTest` keeps failing...? I first thought the other PR might be in some weird stuck state, but this one fails too..

**Comment by jianglai** [comment]
> @weiminyu any idea `TldTest` keeps failing...? I first thought the other PR might be in some weird stuck state, but this one fails too..

See my latest comment in #2105. I think I know why the tests are failing. Closing this PR now.

**Pull request closed without merging**
