### PR TITLE
Delete legacy console

### PR DESCRIPTION
**Pull request by jianglai**
It is with great pleasure that I bring forth this PR, wherein the legacy console is completely, utterly, and absolutely dismantled, destroyed, and decimated, along with it, [Pablo's black magick](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/javascript/google/registry/ui/js/util.js;l=117?q=black%20magic&ss=nomulus%2Fnomulus).

Rising from its ashes is the new console, with its all responsive angular glory. Whenever one stumbles upon the paths where the legacy console once lived (`/`, `/registrar`), an automatic redirect will guide one to the promised land that is `/console`.

The console is dead! Long live the console!

Note: all of the checks in `ContactAction` are lifted from `RegistrarSettingsAction`.

TESTED=deployed to alpha and tested both `/` and `/registrar` redirects.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2579)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 138 of 141 files at r1, 5 of 5 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, 4 of 4 files at r8, 3 of 10 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman and @ptkach)

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 135 of 141 files at r1, 3 of 5 files at r2, 3 of 5 files at r3, 1 of 1 files at r4, 2 of 2 files at r6, 1 of 3 files at r7, 1 of 4 files at r8, 2 of 10 files at r9, 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[`appengine_war.gradle` line 51 at r6](https://reviewable.io/reviews/google/nomulus/2579#-O8cZhMeDegW3RmrcI-A:-O8cZhMeDegW3RmrcI-B:bamuvxx) ([raw file](https://github.com/google/nomulus/blob/de8d9ca48b4e1f535ad08f6565031c5f090348f6/appengine_war.gradle#L51)):*
> ```Gradle
>     war {
>         from("${coreResourcesDir}/google/registry/ui/html") {
>             include "*.html"
> ```

Hmm, I'm a bit confused by this - where would html come from when old console files and build gradle task gets deleted?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @ptkach)

___
*[`appengine_war.gradle` line 51 at r6](https://reviewable.io/reviews/google/nomulus/2579#-O8cZhMeDegW3RmrcI-A:-O9B5nLY6uCi000fIlt7:b-qx4kaq) ([raw file](https://github.com/google/nomulus/blob/de8d9ca48b4e1f535ad08f6565031c5f090348f6/appengine_war.gradle#L51)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Hmm, I'm a bit confused by this - where would html come from when old console files and build gradle task gets deleted?
</blockquote></details>

We are still keeping this file for now, so `/registrar` will redirect to `/console`.

**Comment by jianglai** [comment]
Gentle ping.

**Review by ptkach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[`appengine_war.gradle` line 51 at r6](https://reviewable.io/reviews/google/nomulus/2579#-O8cZhMeDegW3RmrcI-A:-O9QYZtD98jdqMTllH0r:bvww0mv) ([raw file](https://github.com/google/nomulus/blob/de8d9ca48b4e1f535ad08f6565031c5f090348f6/appengine_war.gradle#L51)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

We are still keeping this file for now, so `/registrar` will redirect to `/console`.
</blockquote></details>

Right, yeah I missed that you put a html file there

**Review by ptkach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2579)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
