### PR TITLE
Add a cookie-based OAuth2 authenticator

### PR DESCRIPTION
**Pull request by gbrodman**
This uses the GoogleIdTokenVerifier to verify ID tokens passed in
(presumably from a front end) via cookies. This isn't used anywhere yet
but it will be used for front-end API calls for the new console.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1761)

### CODE REVIEW

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1761)* status: all files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/request/auth/AuthModule.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYFBkSCCarGypcnkBg:-NBYFBkSCCarGypcnkBh:b-mf5hh1) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/main/java/google/registry/request/auth/AuthModule.java#L54)):*
> ```Java
>       @Config("allowedOauthClientIds") ImmutableSet<String> allowedOauthClientIds,
>       NetHttpTransport httpTransport) {
>     return new GoogleIdTokenVerifier.Builder(httpTransport, new GsonFactory())
> ```

Should we inject [this](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/Modules.java;l=73;drc=37ed6c925c1f12c014c5d0c55fbb26c302a34ae2) instead?

`GsonFactory` [doc](https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.json.gson.GsonFactory) says only one global Json Factory should be provided.



_Code quote:_
```Java
new GsonFactory()
```
___
*[`core/src/main/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanism.java` line 72 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYs5Qo5ekxkOB5Cp_5:-NBYs5Qo5ekxkOB5Cp_6:b-szz06a) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/main/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanism.java#L72)):*
> ```Java
>       return AuthResult.NOT_AUTHENTICATED;
>     }
>     return AuthResult.create(AuthLevel.USER, UserAuthInfo.create(maybeUser.get()));
> ```

I'm I correct in assuming that this class only does authentication (as the name suggests), and authorization is handled later in the pipeline?



_Code quote:_
```Java
AuthResult.create(AuthLevel.USER, UserAuthInfo.create(maybeUser.get()))
```
___
*[`core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java` line 45 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYqnyf9GZgo3GWG_1G:-NBYqnyf9GZgo3GWG_1H:b-40ra17) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java#L45)):*
> ```Java
> 
>   @RegisterExtension
>   final AppEngineExtension appEngine = AppEngineExtension.builder().withCloudSql().build();
> ```

I don't think there is any App Engine dependency in this code path (or there shouldn't be). In that case you can use an extension from `JpaTestExtensions` instead.



_Code quote:_
```Java
AppEngineExtension.builder().withCloudSql().build()
```
___
*[`core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java` line 76 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYreeO8GdJkI51OeX3:-NBYreeO8GdJkI51OeX4:b-43wpyt) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java#L76)):*
> ```Java
>     AuthResult authResult = authenticationMechanism.authenticate(request);
>     assertThat(authResult.isAuthenticated()).isTrue();
>     Truth8.assertThat(authResult.userAuthInfo()).isPresent();
> ```

What's the reason to use the Truth8 version here? Does it have something to do with the issue with Java 8 vs Java 11 `Optional`s that tricks us a couple of times in the past?



_Code quote:_
```Java
Truth8
```

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1761)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/request/auth/AuthModule.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYFBkSCCarGypcnkBg:-NBYu80ACvTCqHlOfIj0:b-n2p86q) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/main/java/google/registry/request/auth/AuthModule.java#L54)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Should we inject [this](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/Modules.java;l=73;drc=37ed6c925c1f12c014c5d0c55fbb26c302a34ae2) instead?

`GsonFactory` [doc](https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.json.gson.GsonFactory) says only one global Json Factory should be provided.
</blockquote></details>

yeah it shouldn't matter much either way (I think) since this is a singleton but no harm in injecting it too 
___
*[`core/src/main/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanism.java` line 72 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYs5Qo5ekxkOB5Cp_5:-NBYuGL-2aegAJE9p_sJ:b-bvysqi) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/main/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanism.java#L72)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I'm I correct in assuming that this class only does authentication (as the name suggests), and authorization is handled later in the pipeline?
</blockquote></details>

Yep. Authorization in the old world is done with the `AuthenticatedRegistrarAccessor` (which basically tells us which registrars the given user can access). In the new world we'll rely on inspecting the returned user object to see if it has the required permission. 
___
*[`core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java` line 45 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYqnyf9GZgo3GWG_1G:-NBYv3a83Wk1CYkD9P4m:b-trxlbt) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java#L45)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I don't think there is any App Engine dependency in this code path (or there shouldn't be). In that case you can use an extension from `JpaTestExtensions` instead.
</blockquote></details>

yeah good call 
___
*[`core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java` line 76 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYreeO8GdJkI51OeX3:-NBYv4YNCFe1dKEFoEG6:byb1yfo) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java#L76)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

What's the reason to use the Truth8 version here? Does it have something to do with the issue with Java 8 vs Java 11 `Optional`s that tricks us a couple of times in the past?
</blockquote></details>

There's no technically-required reason, but Truth8 has the `isPresent` method which the older versions don't.

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/request/auth/AuthModule.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYFBkSCCarGypcnkBg:-NBZ4ODP3LZ-8n3zvZdW:b-wtk8bn) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/main/java/google/registry/request/auth/AuthModule.java#L54)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah it shouldn't matter much either way (I think) since this is a singleton but no harm in injecting it too 
</blockquote></details>

I meant that we should inject the JsonFactory from Jackson2Module here:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/Modules.java;l=73;drc=37ed6c925c1f12c014c5d0c55fbb26c302a34ae2

No need to use different JsonFactories in different part of the code base.
___
*[`core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java` line 76 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYreeO8GdJkI51OeX3:-NBZ4h4H8IX-L-HJio1n:b-7vo82j) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/test/java/google/registry/request/auth/CookieOAuth2AuthenticationMechanismTest.java#L76)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

There's no technically-required reason, but Truth8 has the `isPresent` method which the older versions don't.
</blockquote></details>

Ah, I see!

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/request/auth/AuthModule.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/1761#-NBYFBkSCCarGypcnkBg:-NBZAAR59V-ELIsD-AjK:bau9zp3) ([raw file](https://github.com/google/nomulus/blob/124a4378c33915495699ee8905fa90d782c49ddc/core/src/main/java/google/registry/request/auth/AuthModule.java#L54)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I meant that we should inject the JsonFactory from Jackson2Module here:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/Modules.java;l=73;drc=37ed6c925c1f12c014c5d0c55fbb26c302a34ae2

No need to use different JsonFactories in different part of the code base.
</blockquote></details>

oooo yeah (I updated the JSON factory creation as well because `JacksonFactory.getDefaultInstance` is deprecated)

**Review by jianglai — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/request/Modules.java` line 69 at r3](https://reviewable.io/reviews/google/nomulus/1761#-NB_Mti864_5BPSk8xc2:-NB_Mti99VwlWBfMvve7:b22opjo) ([raw file](https://github.com/google/nomulus/blob/e32fe1c80e9bbd3749f151bd9d29dd18a2273190/core/src/main/java/google/registry/request/Modules.java#L69)):*
> ```Java
>    * Dagger module that causes the Jackson2 JSON parser to be used for Google APIs requests.
>    *
>    * <p>Jackson1 and GSON can also satisfy the {@link JsonFactory} interface, but we've decided to
> ```

The javadoc needs to be updated.

**Review by jianglai — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/request/Modules.java` line 69 at r3](https://reviewable.io/reviews/google/nomulus/1761#-NB_Mti864_5BPSk8xc2:-NB_NCZ4AQswhdaheEuH:b-erd2m9) ([raw file](https://github.com/google/nomulus/blob/e32fe1c80e9bbd3749f151bd9d29dd18a2273190/core/src/main/java/google/registry/request/Modules.java#L69)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The javadoc needs to be updated. 
</blockquote></details>

And the class name itself…

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1761)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/request/Modules.java` line 69 at r3](https://reviewable.io/reviews/google/nomulus/1761#-NB_Mti864_5BPSk8xc2:-NBmK2N80VOGZbKsQlHr:b565vcd) ([raw file](https://github.com/google/nomulus/blob/e32fe1c80e9bbd3749f151bd9d29dd18a2273190/core/src/main/java/google/registry/request/Modules.java#L69)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

And the class name itself…
</blockquote></details>

hah good call, sorry i missed that

**Pull request merged**
