### PR TITLE
Unify email notifications for console updates

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2459)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2459)* status: all files reviewed, 11 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 152 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz519Tn19pDKg_EZyBV:-Nz519Tn19pDKg_EZyBW:b-pqn3dy) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L152)):*
> ```Java
>       Iterable<RegistrarPoc> contacts, Registrar registrar) {
>     ImmutableSet<Map<String, Object>> expandedContacts =
>         Streams.stream(contacts)
> ```

i think `contacts` can be a set, so you can just stream it directly 

but even then do we need to keep track of the contacts separately? The registrar itself has a method that gets the contacts on it. Though that method is a database call, I don't think we'd need to call it multiple times. 

and even then, we're already calling `registrar.getContacts()` multiple times when creating the EmailInfo objects anyway, so removing the existingContacts field from that makes up for it.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 164 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz53-7O9PBzdDGvxJkX:-Nz53-7O9PBzdDGvxJkY:b-f1vvki) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L164)):*
> ```Java
> 
>     Map<String, Object> registrarDiffMap = registrar.toDiffableFieldMap();
>     Set.of("passwordHash", "salt") // Set of fields to remove from final diff
> ```

seems like overkill to create a set here when there's just two fields? eh 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 184 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz59wcK00XKue1YXmBw:-Nz59wcK00XKue1YXmBx:b-avuegb) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L184)):*
> ```Java
>     Registrar existingRegistrar = emailInfo.registrar();
> 
>     Map<?, ?> diffs =
> ```

We know that we'll always want to send the email if the override is specified and it seems odd to have the generic method include the diffs that are only specified once

So you can just have two methods 

`void sendExternalUpdatesIfNecessary(EmailInfo emailInfo);` that figures out if we need to do anything and then calls the method below

and

`void sendExternalUpdates(Registrar registrar, Map<?, ?> diffs);` that does the actual work
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 195 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz59lds7NLmmixTYMvk:-Nz59lds7NLmmixTYMvl:b8tgr8i) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L195)):*
> ```Java
>     @SuppressWarnings("unchecked")
>     Set<String> changedKeys = (Set<String>) diffs.keySet();
>     if (CollectionUtils.difference(changedKeys, "lastUpdateTime").isEmpty()) {
> ```

can just use Sets.difference
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 209 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz592mID3bU3nlWm4aS:-Nz592mID3bU3nlWm4aT:b-di5lh5) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L209)):*
> ```Java
> 
>     String environment = Ascii.toLowerCase(String.valueOf(RegistryEnvironment.get()));
>     consoleApiParams
> ```

This gets a bit simpler if you inject the SendEmailUtils which does some of this for us.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 246 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz57hNr-50gSj6WG4U-:-Nz57hNr-50gSj6WG4U0:bpkn9v0) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L246)):*
> ```Java
>       Registrar registrar,
>       Registrar updatedRegistrar,
>       ImmutableSet<RegistrarPoc> contacts,
> ```

We can just call `getContacts` on the registrar when (if) we want the contacts, no point in requiring it here.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz56rmy4oVwnqQQWAe1:-Nz56rmz1cQhcIMC6Eun:bik0dyi) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L113)):*
> ```Java
>                       registrar.getContacts()),
>                   Optional.of(
>                       ImmutableMap.of("password", new DiffUtils.DiffPair("********", "••••••••"))));
> ```

Maybe use something like "redacted for security" rather than the random-ish characters? That seems clearer, especially since the number of characters probably won't line up.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5--M9B8w2nwYc5qvM:-Nz5--M9B8w2nwYc5qvN:b-rm70e3) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L113)):*
> ```Java
>                 contacts.get().stream().map(RegistrarPoc::toJsonMap).collect(toImmutableList())));
> 
>     if (!registrarAccessor.hasRoleOnRegistrar(Role.OWNER, registrar.getRegistrarId())) {
> ```

I don't think this is the right permission check since it's using the old role type
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 128 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5AtiU0K6j295JzTmS:-Nz5AtiV7MMYVzBDTa8S:bb4c3j8) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L128)):*
> ```Java
>             () -> {
>               RegistrarPoc.updateContacts(registrar, updatedContacts);
>               Registrar updatedRegistrar =
> ```

We should only do this if the contacts are actually different 
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleApiParams.java` line 28 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz58uizA34HujjslhI4:-Nz58uizA34HujjslhI5:b-ityzfo) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/registrar/ConsoleApiParams.java#L28)):*
> ```Java
>     Response response,
>     AuthResult authResult,
>     GmailClient gmailClient,
> ```

This doesn't fit with the rest of the fields, which have to do with the actual request and response themselves. Just inject the client into the action (or even better, inject the SendEmailUtils) 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 215 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5B7ViApPCDq-MZp9k:-Nz5B7ViApPCDq-MZp9l:b-nuu4l2) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L215)):*
> ```Java
>     assertThat(((FakeResponse) consoleApiParams.response()).getStatus()).isEqualTo(SC_FORBIDDEN);
>   }
> ```

We probably want to have a test with a no-op update, where nothing happens if the contacts are the same.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2459)* status: all files reviewed, 11 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 152 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz519Tn19pDKg_EZyBV:-Nz9xB959ClEK3SJOl7w:b1htz2z) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L152)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think `contacts` can be a set, so you can just stream it directly 

but even then do we need to keep track of the contacts separately? The registrar itself has a method that gets the contacts on it. Though that method is a database call, I don't think we'd need to call it multiple times. 

and even then, we're already calling `registrar.getContacts()` multiple times when creating the EmailInfo objects anyway, so removing the existingContacts field from that makes up for it.
</blockquote></details>

discussed offline, we still need to store the contacts in the EmailInfo object so as to keep the parallelism between expanding the old registrar and the new registrar 

however, i'm p sure we can still change contacts to be some type of set

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2459)* status: 1 of 14 files reviewed, 11 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 152 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz519Tn19pDKg_EZyBV:-Nz98jR0-VK5XyxG_L6l:b-d00h8f) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L152)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

discussed offline, we still need to store the contacts in the EmailInfo object so as to keep the parallelism between expanding the old registrar and the new registrar 

however, i'm p sure we can still change contacts to be some type of set
</blockquote></details>

Updated to be a Set
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 164 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz53-7O9PBzdDGvxJkX:-Nz99qLW-PdpYaOI23Vk:bqog80t) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L164)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

seems like overkill to create a set here when there's just two fields? eh
</blockquote></details>

Agreed
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 184 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz59wcK00XKue1YXmBw:-Nz9QC878JJTI8WCLndJ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L184)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We know that we'll always want to send the email if the override is specified and it seems odd to have the generic method include the diffs that are only specified once

So you can just have two methods 

`void sendExternalUpdatesIfNecessary(EmailInfo emailInfo);` that figures out if we need to do anything and then calls the method below

and

`void sendExternalUpdates(Registrar registrar, Map<?, ?> diffs);` that does the actual work
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 195 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz59lds7NLmmixTYMvk:-Nz9Qvdw0lPgKsB7bC_m:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L195)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can just use Sets.difference
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 209 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz592mID3bU3nlWm4aS:-NzA7B6M9RayfYVBAKyx:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L209)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This gets a bit simpler if you inject the SendEmailUtils which does some of this for us.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 246 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz57hNr-50gSj6WG4U-:-NzA7DqSBYjMJASzn4tY:b255xay) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L246)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We can just call `getContacts` on the registrar when (if) we want the contacts, no point in requiring it here.
</blockquote></details>

As discussed offline there's a point
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz56rmy4oVwnqQQWAe1:-NzA7Plt2bL1ssU-Cj4i:bvu3yd8) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L113)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Maybe use something like "redacted for security" rather than the random-ish characters? That seems clearer, especially since the number of characters probably won't line up.
</blockquote></details>

I don't know, having bother of them say "redacted for privacy" is confusing, but having one leaves the other one to be filled with starts or dots anyway, so why not have both? I believe it makes it more or less clear that the password has been updated.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5--M9B8w2nwYc5qvM:-NzA7sa24v-QYaY498p6:bu3fqw4) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L113)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think this is the right permission check since it's using the old role type
</blockquote></details>

Not sure what do you mean. This is what existing console has in place. 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 128 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5AtiU0K6j295JzTmS:-NzA8Zjl853H3hmMvl4i:bixilsa) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L128)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We should only do this if the contacts are actually different
</blockquote></details>

I think we can safely assume that if POST request with contacts is made there was a change. If that's not the case we can add a check to front-end to only submit a request (enable save button) when user makes a change
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleApiParams.java` line 28 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz58uizA34HujjslhI4:-NzA9D8tDH7wTrBmgS85:bg0mv2q) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/registrar/ConsoleApiParams.java#L28)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This doesn't fit with the rest of the fields, which have to do with the actual request and response themselves. Just inject the client into the action (or even better, inject the SendEmailUtils)
</blockquote></details>

Well this always served a purpose to unify common dependencies for Console API handlers. It just so happened that used to be Request/ Response related, but there's no reason it has to be. 

On a separate note - gmailClient or SendEmailUtils is required in a base class `ConsoleApiAction`, so injection and using it in tests is  rather difficult. This is the best way that works.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2459)* status: 1 of 14 files reviewed, 11 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 215 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5B7ViApPCDq-MZp9k:-NzACmWt3dydCrSu77Dd:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L215)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We probably want to have a test with a no-op update, where nothing happens if the contacts are the same.
</blockquote></details>

Done.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2459)* status: all files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz56rmy4oVwnqQQWAe1:-NzAQ11E034ROfkujWXx:b4pgsj2) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L113)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I don't know, having bother of them say "redacted for privacy" is confusing, but having one leaves the other one to be filled with starts or dots anyway, so why not have both? I believe it makes it more or less clear that the password has been updated.
</blockquote></details>

sure, i don't feel super strongly
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5--M9B8w2nwYc5qvM:-NzAFDc76fHHU02RtQUo:bowfc2z) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L113)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Not sure what do you mean. This is what existing console has in place.
</blockquote></details>

Right but this action isn't the existing console, it's the new one. The AuthenticatedRegistrarAccessor should be deleted once we move entirely to the new console, since it doesn't use the granular permissions model. 

In general ideally we move toward using the granular permission model so that we can delete AuthenticatedRegistrarAccessor sooner 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 128 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5AtiU0K6j295JzTmS:-NzAHWX54T_meVohxehp:b-fzkr3f) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L128)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I think we can safely assume that if POST request with contacts is made there was a change. If that's not the case we can add a check to front-end to only submit a request (enable save button) when user makes a change
</blockquote></details>

That is true about the UI, but we probably shouldn't be considering the UI when making sure we're doing the right thing on the backend. On the other hand, I'm not sure how easy that would be to implement. 

In any case, we should probably ignore the "contactsRequireSyncing" field in the registrar object when doing the comparison in "sendExternalUpdatesIfNecessary" right? 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 121 at r2](https://reviewable.io/reviews/google/nomulus/2459#-NzAO0A90pYRNUgCbx8X:-NzAO0A90pYRNUgCbx8Y:bwig6py) ([raw file](https://github.com/google/nomulus/blob/4a42ef7d4da1545bfd1e1f0a21af4658f22ab3ee/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L121)):*
> ```Java
>             savedRegistrar,
>             updatedRegistrar,
>             savedRegistrar.getContacts(),
> ```

FWIW, for this and for the WhoisRegistrarFieldsAction maybe we don't bother actually loading the contacts (especially since this, as written, would involve one database call for each of the "getContacts" calls)? We know they won't be changed, so maybe we just pass an empty set.
___
*[`core/src/main/java/google/registry/ui/server/registrar/ConsoleApiParams.java` line 28 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz58uizA34HujjslhI4:-NzAPrU-3l2sXnS6_sqO:b-7ajd9t) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/registrar/ConsoleApiParams.java#L28)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Well this always served a purpose to unify common dependencies for Console API handlers. It just so happened that used to be Request/ Response related, but there's no reason it has to be. 

On a separate note - gmailClient or SendEmailUtils is required in a base class `ConsoleApiAction`, so injection and using it in tests is  rather difficult. This is the best way that works.
</blockquote></details>

ugh yeah that's one downside to this injection structure
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 49 at r2](https://reviewable.io/reviews/google/nomulus/2459#-NzAPxfV7FeGQGx-ffac:-NzAPxfWE0kDGehMmiJT:b-pj6byc) ([raw file](https://github.com/google/nomulus/blob/4a42ef7d4da1545bfd1e1f0a21af4658f22ab3ee/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L49)):*
> ```Java
> import google.registry.request.auth.AuthenticatedRegistrarAccessor;
> import google.registry.testing.ConsoleApiParamsUtils;
> import goojohndoe@theregistrar.comgle.registry.testing.FakeResponse;
> ```

hey now

lol

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2459)* status: 7 of 14 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 113 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5--M9B8w2nwYc5qvM:-NzEOtED1H7GZh-v9apV:b-26lca4) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L113)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Right but this action isn't the existing console, it's the new one. The AuthenticatedRegistrarAccessor should be deleted once we move entirely to the new console, since it doesn't use the granular permissions model. 

In general ideally we move toward using the granular permission model so that we can delete AuthenticatedRegistrarAccessor sooner
</blockquote></details>

As per offline discussion I removed this check. I wasn't sure how and when old roles had been migrated to the new roles and I thought that contacts update still relies on the old role verification. 
___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 128 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5AtiU0K6j295JzTmS:-NzEWRvA-L4imN9lx-5T:b-w0z7ju) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L128)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

That is true about the UI, but we probably shouldn't be considering the UI when making sure we're doing the right thing on the backend. On the other hand, I'm not sure how easy that would be to implement. 

In any case, we should probably ignore the "contactsRequireSyncing" field in the registrar object when doing the comparison in "sendExternalUpdatesIfNecessary" right?
</blockquote></details>

Well yeah I agree that it might not be very easy to implement this check. However we made sure that no email is sent if there's no change, so other than a DB call to put a new contact there's downside. I'm not sure that it's worth looking into at the moment.

Re `contactsRequireSyncing` I thought so too, as I looked into existing implementation that doesn't have it excluded, but it doesn't affect comparison. So I did the same and it has no effect on a diff, test confirms it.
___
*[`core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java` line 121 at r2](https://reviewable.io/reviews/google/nomulus/2459#-NzAO0A90pYRNUgCbx8X:-NzEazeT95QPOtH01Sbw:b-orumjy) ([raw file](https://github.com/google/nomulus/blob/4a42ef7d4da1545bfd1e1f0a21af4658f22ab3ee/core/src/main/java/google/registry/ui/server/console/settings/SecurityAction.java#L121)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

FWIW, for this and for the WhoisRegistrarFieldsAction maybe we don't bother actually loading the contacts (especially since this, as written, would involve one database call for each of the "getContacts" calls)? We know they won't be changed, so maybe we just pass an empty set.
</blockquote></details>

Good point

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2459)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java` line 128 at r1](https://reviewable.io/reviews/google/nomulus/2459#-Nz5AtiU0K6j295JzTmS:-NzEejAr4f3RVh5XjTj3:b9ss8zv) ([raw file](https://github.com/google/nomulus/blob/1336e64b85c2b0fe1e354879bb3a242330434a7d/core/src/main/java/google/registry/ui/server/console/settings/ContactAction.java#L128)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Well yeah I agree that it might not be very easy to implement this check. However we made sure that no email is sent if there's no change, so other than a DB call to put a new contact there's downside. I'm not sure that it's worth looking into at the moment.

Re `contactsRequireSyncing` I thought so too, as I looked into existing implementation that doesn't have it excluded, but it doesn't affect comparison. So I did the same and it has no effect on a diff, test confirms it.
</blockquote></details>

oh cool
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 298 at r4](https://reviewable.io/reviews/google/nomulus/2459#gh-1622733045:-NzEepLWDX_qFLNmExSl:bgcbsj5) ([raw file](https://github.com/google/nomulus/blob/155e0cffa0d215ffba9bb6c37971feee3dacaee7/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L298)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unread local variable

Variable 'AuthenticatedRegistrarAccessor authenticatedRegistrarAccessor' is never read.

[Show more details](https://github.com/google/nomulus/security/code-scanning/9416)
</blockquote></details>

yeah should probably remove it

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2459)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 298 at r4](https://reviewable.io/reviews/google/nomulus/2459#gh-1622733045:-NzEfv9F2pCP0DeDU1Cq:b-896fix) ([raw file](https://github.com/google/nomulus/blob/155e0cffa0d215ffba9bb6c37971feee3dacaee7/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L298)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah should probably remove it
</blockquote></details>

Done.

**Pull request merged**
