### PR TITLE
Revert google-cloud-storage to 2.22.6

### PR DESCRIPTION
**Pull request by jianglai**
2.25.0 contains a breaking change that made HttpStorageOptions not
serializeable, which breaks RDE as it needs to access GCS from Beam.

2.22.6 was the last version that was used before the Gradle upgrade.

Also had to downgrade google-cloud-nio to pass the tests.

For some inexplicable reason, I had to manually add
guava-listenablefuture as
testRuntimeClasspath/runtimeClasspath/deploy_jar dependencies to the
networking, docs and prober subprojects' lock files, as running
`gradle test --write-locks` would NOT add them and succeed; but without
`--write-locks`, running the corresponding tests would fail.

See: b/294378137.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2093)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
love to introduce breaking changes in minor release versions

> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2093#-:-NawU-1CAAezL5ulu08G:bz8u4jh)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai and @weiminyu)

___
*[`console-webapp/gradle.lockfile` line 4 at r1](https://reviewable.io/reviews/google/nomulus/2093#-NawUZna63ao2Iq3gQJ5:-NawUZna63ao2Iq3gQJ6:b-nn877a) ([raw file](https://github.com/google/nomulus/blob/733e9a4a6aa3380497d9fd21ac9e82fdddd67cf6/console-webapp/gradle.lockfile#L4)):*
> ```
> # Manual edits can break the build and are not advised.
> # This file is expected to be part of source control.
> com.github.ben-manes.caffeine:caffeine:2.7.0=annotationProcessor,errorprone,testAnnotationProcessor
> ```

it seems odd that this all got deleted?
___
*[`docs/gradle.lockfile` line 192 at r1](https://reviewable.io/reviews/google/nomulus/2093#-NawUhrw9NDyGOdu7Vfe:-NawUhrw9NDyGOdu7Vff:bibtgio) ([raw file](https://github.com/google/nomulus/blob/733e9a4a6aa3380497d9fd21ac9e82fdddd67cf6/docs/gradle.lockfile#L192)):*
> ```
> io.confluent:common-config:5.3.2=deploy_jar,runtimeClasspath,testRuntimeClasspath
> io.confluent:common-utils:5.3.2=deploy_jar,runtimeClasspath,testRuntimeClasspath
> io.confluent:kafka-avro-serializer:5.3.2=deploy_jar,runtimeClasspath,testRuntimeClasspath
> ```

are all the deletions in this file as well expected?

**Review by weiminyu — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2093)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

**Review by gbrodman — COMMENTED** [review]
actually should we just upgrade to 2.26 when that's released, given that it shouldn't be long? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2093#-:-Nawkrmv6C4hQc3BiUdP:brmaw1p)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
We could, but the pipeline will remain broken until then. We could just manually switch to the old pipeline every time after a deployment, like Weimin did.

Also, I'm seeing the same error in tests now that I've downgraded... what is going on...?

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2093#-:-NawoxfrEapmNlI5cvV6:b7zur4p)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2093)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/gradle.lockfile` line 4 at r1](https://reviewable.io/reviews/google/nomulus/2093#-NawUZna63ao2Iq3gQJ5:-NawpIk_B2Y5ncnM-zSC:bg7qgo9) ([raw file](https://github.com/google/nomulus/blob/733e9a4a6aa3380497d9fd21ac9e82fdddd67cf6/console-webapp/gradle.lockfile#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it seems odd that this all got deleted?
</blockquote></details>

No, something is not right. I hate dealing with dependencies...

**Comment by gbrodman** [comment]
Yeah it might depend on how long it takes the fix PR to go in I suppose. It looks like they do releases fairly frequently

**Comment by jianglai** [comment]
> Yeah it might depend on how long it takes the fix PR to go in I suppose. It looks like they do releases fairly frequently

per b/294399427, they have a release train running. Not sure if this particular fix would get on that train, but it should definitely get on the next one.

**Review by jianglai — COMMENTED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2093)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`docs/gradle.lockfile` line 192 at r1](https://reviewable.io/reviews/google/nomulus/2093#-NawUhrw9NDyGOdu7Vfe:-Nb-UPeG3PuKdCxVAz7v:bt2vr1b) ([raw file](https://github.com/google/nomulus/blob/733e9a4a6aa3380497d9fd21ac9e82fdddd67cf6/docs/gradle.lockfile#L192)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

are all the deletions in this file as well expected?
</blockquote></details>

Fixed.

**Review by jianglai — COMMENTED** [review]
> Reviewed 9 of 12 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2093)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

**Review by jianglai — COMMENTED** [review]
> Dismissed @gbrodman from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2093)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

___
*[`console-webapp/gradle.lockfile` line 4 at r1](https://reviewable.io/reviews/google/nomulus/2093#-NawUZna63ao2Iq3gQJ5:-NbFn6L8AmK-JPbVlcZn:bt2vr1b) ([raw file](https://github.com/google/nomulus/blob/733e9a4a6aa3380497d9fd21ac9e82fdddd67cf6/console-webapp/gradle.lockfile#L4)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

No, something is not right. I hate dealing with dependencies...
</blockquote></details>

Fixed.

**Pull request merged**
