### PR TITLE
Send registrars poll messages when we add/remove server-side statuses

### PR DESCRIPTION
**Pull request by CydeWeys**
---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1417)

### CODE REVIEW

**Review by rachelguan — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1417)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @rachelguan)

___
*[core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java, line 215 at r1](https://reviewable.io/reviews/google/nomulus/1417#-MoKo_zW6K1N5L7cpI_i:-MoKo_zW6K1N5L7cpI_j:b-wrj939) ([raw file](https://github.com/google/nomulus/blob/2c28f4eec933e4676a4b85ae30e2f5ca8dc7bd41/core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java#L215)):*
> ```Java
>         .hasAuthInfoPwd("2BARfoo")
>         .and()
>         .hasOneHistoryEntryEachOfTypes(HistoryEntry.Type.DOMAIN_CREATE, DOMAIN_UPDATE)
> ```

is there a reason to remove HistoryEntry.Type for DOMAIN_UPDATE but not for DOMAIN_CREATE?
___
*[core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java, line 1001 at r1](https://reviewable.io/reviews/google/nomulus/1417#-MoKqD8B7sMckKNTywuy:-MoKqD8C-ouRN4-geTv6:b-k5b4sk) ([raw file](https://github.com/google/nomulus/blob/2c28f4eec933e4676a4b85ae30e2f5ca8dc7bd41/core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java#L1001)):*
> ```Java
>         CommitMode.LIVE, UserPrivileges.SUPERUSER, loadFile("generic_success_response.xml"));
>     DomainBase updatedDomain = reloadResourceByForeignKey();
>     assertPollMessagesForResource(
> ```

i'm suggesting to include test case(s) for the poll messages so we can explicitly see how the poll messages are supposed to look like.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1417)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @rachelguan)

___
*[core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java, line 1001 at r1](https://reviewable.io/reviews/google/nomulus/1417#-MoKqD8B7sMckKNTywuy:-Mo_SFuq0MWwKqK8YYsJ:bngp50j) ([raw file](https://github.com/google/nomulus/blob/2c28f4eec933e4676a4b85ae30e2f5ca8dc7bd41/core/src/test/java/google/registry/flows/domain/DomainUpdateFlowTest.java#L1001)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

i'm suggesting to include test case(s) for the poll messages so we can explicitly see how the poll messages are supposed to look like. 
</blockquote></details>

Done, but, it's literally just this String inside the normal poll response.  And it has to be a lifecycle test as it requires multiple invocations of flows rather than a single flow invocation.

**Review by rachelguan — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1417#-:-Mo_UN4X4UHok-tioquo:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @rachelguan)

**Review by rachelguan — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1417#-:-Mo_UN4X4UHok-tioquo:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @rachelguan)

**Pull request merged**
