### PR TITLE
Add screenshot tests for the new registrar console

### PR DESCRIPTION
**Pull request by gbrodman**
This required updating to a newer version of Selenium, building the console dist/ folder, and serving that folder.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2577)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 12 of 95 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2577)* status: 12 of 95 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/test/java/google/registry/webdriver/ConsoleScreenshotTest.java` line 41 at r1](https://reviewable.io/reviews/google/nomulus/2577#-O8buAZT9bEkckQ4D7Z5:-O8buAZT9bEkckQ4D7Z6:b87k9qi) ([raw file](https://github.com/google/nomulus/blob/5f66464d005fb9a5f758260cebfbf1e23d75aad8/core/src/test/java/google/registry/webdriver/ConsoleScreenshotTest.java#L41)):*
> ```Java
>  * because we aren't really serving the webapp the same way that an actual webserver (e.g. Express)
>  * would, we're just statically serving the distribution. As a result, we cannot load URLs, e.g.
>  * "/#/settings", directly.
> ```

Can you elaborate on why we can't load URLs? All navigation happens within the webapp via angular router, so as long as URL is correct, webapp should handle it. 
___
*[`core/src/test/java/google/registry/webdriver/ConsoleScreenshotTest.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2577#-O8bv3v_CgTUfXG3Z7Rc:-O8bv3v_CgTUfXG3Z7Rd:bhr9xj3) ([raw file](https://github.com/google/nomulus/blob/5f66464d005fb9a5f758260cebfbf1e23d75aad8/core/src/test/java/google/registry/webdriver/ConsoleScreenshotTest.java#L43)):*
> ```Java
>  * "/#/settings", directly.
>  */
> public class ConsoleScreenshotTest extends WebDriverTestCase {
> ```

Hmm all those retries and sleeps make me a uneasy about this approach. Is it possible to replace with something more explicit, like:
```
WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "myDynamicElement"))
```



_Code quote:_
```Java
T
```

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2577)* status: 12 of 95 files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`core/src/test/java/google/registry/webdriver/ConsoleScreenshotTest.java` line 41 at r1](https://reviewable.io/reviews/google/nomulus/2577#-O8buAZT9bEkckQ4D7Z5:-O8c2w403NQZK6FqOnon:b-bflyc4) ([raw file](https://github.com/google/nomulus/blob/5f66464d005fb9a5f758260cebfbf1e23d75aad8/core/src/test/java/google/registry/webdriver/ConsoleScreenshotTest.java#L41)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Can you elaborate on why we can't load URLs? All navigation happens within the webapp via angular router, so as long as URL is correct, webapp should handle it.
</blockquote></details>

It's because that routing depends on the existence of the express (?) server than handles routing in general, that anything under /console should go to the console routing service. Here we're dealing with the raw pages (like, we're loading /console/index.html directly) we can't count on any routing. 
___
*[`core/src/test/java/google/registry/webdriver/ConsoleScreenshotTest.java` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2577#-O8bv3v_CgTUfXG3Z7Rc:-O8c4Oak3FJe0z128bTG:b-d27y90) ([raw file](https://github.com/google/nomulus/blob/5f66464d005fb9a5f758260cebfbf1e23d75aad8/core/src/test/java/google/registry/webdriver/ConsoleScreenshotTest.java#L43)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Hmm all those retries and sleeps make me a uneasy about this approach. Is it possible to replace with something more explicit, like:
```
WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "myDynamicElement"))
```
</blockquote></details>

The issue is that much of the time we're waiting on an effect (like a highlighting, or a shadow) to fade to make sure we can get a reliable constant color/image. Otherwise, we end up with e.g. spurious failures caused by slight degrees of a button's highlighting fading after we click on it.

**Comment by gbrodman** [comment]
gonna wait until approval to fix the merge conflicts in the lockfiles, to avoid extra work

**Review by ptkach — APPROVED** [review]
Very cool, thanks! How does it compare to the old console wrt running time? Is it faster?

> Reviewed 83 of 95 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2577#-:-O8cXoYS35fOkRI9YNon:b-skm06q)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
It seems pretty similar! 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2577#-:-O8hLApSDIIOKpmwBr_I:b-yzdbk9)* status: 81 of 95 files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
