### PR TITLE
Update ListDomainsAction to SQL

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1036)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1036)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/tools/server/ListDomainsAction.java, line 82 at r1](https://reviewable.io/reviews/google/nomulus/1036#-MWev_k4EcIllFRdACJN:-MWev_k4EcIllFRdACJO:brzxlmw) ([raw file](https://github.com/google/nomulus/blob/8bb6dde6a1f6e14ad64942ab6d4d164cbead990d/core/src/main/java/google/registry/tools/server/ListDomainsAction.java#L82)):*
> ```Java
>     return ImmutableSet.copyOf(
>         domains.stream()
>             .sorted(comparing(EppResource::getCreationTime).reversed())
> ```

This should be happening only on the Datastore branch, as you're already doing it in the SQL query itself.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1036)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/tools/server/ListDomainsAction.java, line 82 at r1](https://reviewable.io/reviews/google/nomulus/1036#-MWev_k4EcIllFRdACJN:-MWexJnh-0tobcQ05Z58:bma6si3) ([raw file](https://github.com/google/nomulus/blob/8bb6dde6a1f6e14ad64942ab6d4d164cbead990d/core/src/main/java/google/registry/tools/server/ListDomainsAction.java#L82)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This should be happening only on the Datastore branch, as you're already doing it in the SQL query itself.
</blockquote></details>

Done. Tricky bit is that we need to do the sorting after putting all the batches together but that's fine.

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1036)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1036)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mindhog)

**Pull request merged**
