### PR TITLE
Make Nomulus work on GKE with external load balancer

### PR DESCRIPTION
**Pull request by jianglai**
This will create a multi-cluster external load balancer exposing HTTP
traffic to nomulus running in clusters in the fleet.

Note that this is only an intermediate step. The endpoints need to be split into services that can be independently scaled, and become IAP-protected HTTPS endpoints.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2527)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2527)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2527)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by jianglai — COMMENTED** [review]
Friendly ping.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2527#-:-O4AnH9B54orSSKLQmBb:b-u78c44)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by weiminyu — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2527)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys and @ptkach)

**Pull request merged**
