### PR TITLE
Enforce newline at EOF on HTML and S?CSS files

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2357)

### CODE REVIEW

**Review by ptkach — COMMENTED** [review]
Hmm, this seems like a duplication effort - we already have :console-webapp:checkFormatting gradle taks that fails if formatting is off, inclusing EOF new line. I just tested it locally in html, scss and ts files and it does fail indeed as expected. Why do you think we need this as well?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2357#-:-NsTYkmF9hSyJiA9_B7p:b4vbahz)* status: 0 of 2 files reviewed, all discussions resolved

**Review by gbrodman — COMMENTED** [review]
Oh, does it? I was looking at your PR and noticed some files that didn't have a newline at the end of the file and I assumed you had probably run the formatting task at some point. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2357#-:-NsTx1W62rcvockZn4zv:b-sh2745)* status: 0 of 2 files reviewed, all discussions resolved

**Review by ptkach — COMMENTED** [review]
Yes it should be doing that. If it's not - it's an issue. I just ran it on that PR and it finished successfully, meaning there's no violations. I randomly opened a bunch of new files and all of them have EOF newline. Can you please add the files that you say don't have a newline to that PR we're talking about? Thanks!  

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2357#-:-NsUdnzf-ecgRwvSrmAr:b-2ychvi)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by gbrodman** [comment]
yeah looks like that's correct -- weird, not sure why that was happening before then

**Pull request closed without merging**
