### PR TITLE
Add a renewal cost for tokens when renewal is SPECIFIED

### PR DESCRIPTION
**Pull request by gbrodman**
This also tightens up some of the restrictions around bulk tokens -- they must have a discount fraction of 1 and have a SPECIFIED renewal price of 0. This is because we charge per bulk package, not per domain. 

Note: this is not used yet

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2484)

### CODE REVIEW

**Comment by gbrodman** [comment]
Note: before this is deployed, we will want to add renewal prices to all existing SPECIFIED tokens in the database. All have been used already, so it should be fairly straightforward to just set them to be the standard create price (the pre-existing behavior)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
What's your plan for doing that, running a bunch of nomulus tools?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2484#-:-O0oZxL75dp28nHSrI8R:bmoh9b0)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java` line 3897 at r2](https://reviewable.io/reviews/google/nomulus/2484#-O0oa2n23rGK3ImFK356:-O0oa2n23rGK3ImFK357:b9i42vz) ([raw file](https://github.com/google/nomulus/blob/33b1b75f380a268946d693a21308f4be48b42f86/core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java#L3897)):*
> ```Java
>                 .setToken("abc123")
>                 .setTokenType(BULK_PRICING)
>                 .setDiscountFraction(1)
> ```

Maybe these should be `1.0` to make it clear it's a float and not an int?

**Review by CydeWeys — COMMENTED** [review]
This renewal price isn't actually used anywhere yet -- is that for a subsequent PR?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2484#-:-O0oaGSs4hciiLxrln4F:b-m733op)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
1. Yes, after this PR is deployed we can just run a ton of update_allocation_token commands (we'll need to run those in sandbox too I'd imagine). 
2. Yes, it is for a subsequent PR. I wanted this PR to go through first because 1. smaller PRs yay 2. after this goes through we can prepare the database (related to your first question) before actually changing the behavior

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2484#-:-O0oaPKX-dkUt4QlsxVn:b-ay88f6)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java` line 3897 at r2](https://reviewable.io/reviews/google/nomulus/2484#-O0oa2n23rGK3ImFK356:-O0obQcvEB_GxodedI73:bcjvokr) ([raw file](https://github.com/google/nomulus/blob/33b1b75f380a268946d693a21308f4be48b42f86/core/src/test/java/google/registry/flows/domain/DomainCreateFlowTest.java#L3897)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Maybe these should be `1.0` to make it clear it's a float and not an int?
</blockquote></details>

Sure idc. Done (in many other places too)

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2484#-:-O1Njmv95wQEihek0y9O:bnfp4nl)* status: 0 of 21 files reviewed, all discussions resolved

**Pull request merged**
