### PR TITLE
Preserve update_time when replicating to SQL

### PR DESCRIPTION
**Pull request by weiminyu**
Prevent InitSqlPipeline from changing the UpdateAutoTimestamp fields in
entities.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1316)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1316)* status: all files reviewed, 2 unresolved discussions (waiting on @mindhog and @weiminyu)

___
*[core/src/main/java/google/registry/beam/common/RegistryJpaIO.java, line 281 at r1](https://reviewable.io/reviews/google/nomulus/1316#-MjUdWI486LkWmykdjNm:-MjUdWI486LkWmykdjNn:bksl7hk) ([raw file](https://github.com/google/nomulus/blob/9c83930692389cc47105319a58d988bafd438502/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L281)):*
> ```Java
>     /**
>      * Signal to the writer that entities should be written as is, without data manipulation in
>      * PrePersist/PreUpdate methods.
> ```

This comment and the variable name in general doesn't seem to me to be accurate. The only thing that's disabled (as far as I can tell) is the update-auto-timestamp change, as opposed to PrePersist / PreUpdate methods in general. 
___
*[core/src/main/java/google/registry/beam/common/RegistryJpaIO.java, line 385 at r1](https://reviewable.io/reviews/google/nomulus/1316#-MjUdLSl11RYZkKdbDHq:-MjUdLSl11RYZkKdbDHr:btygopu) ([raw file](https://github.com/google/nomulus/blob/9c83930692389cc47105319a58d988bafd438502/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L385)):*
> ```Java
>           actuallyProcessElement(kv);
>         }
>         return;
> ```

seems a bit odd to have the return statement here when we could just use an `else` corresponding to the `if (writeAsRawData)`

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1316)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/beam/common/RegistryJpaIO.java, line 281 at r1](https://reviewable.io/reviews/google/nomulus/1316#-MjUdWI486LkWmykdjNm:-MjUvL2R0bc9P164-Ddk:b-896fix) ([raw file](https://github.com/google/nomulus/blob/9c83930692389cc47105319a58d988bafd438502/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L281)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This comment and the variable name in general doesn't seem to me to be accurate. The only thing that's disabled (as far as I can tell) is the update-auto-timestamp change, as opposed to PrePersist / PreUpdate methods in general. 
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/beam/common/RegistryJpaIO.java, line 385 at r1](https://reviewable.io/reviews/google/nomulus/1316#-MjUdLSl11RYZkKdbDHq:-MjUvNrMBwOBBP2FPkTh:b-gtnq41) ([raw file](https://github.com/google/nomulus/blob/9c83930692389cc47105319a58d988bafd438502/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L385)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

seems a bit odd to have the return statement here when we could just use an `else` corresponding to the `if (writeAsRawData)` 
</blockquote></details>

Personally I prefer guard statements over if-else.

It'd look better if the if block is shorter, but "if (!writeAsRawData)" runs into another code smell, and reverse the variable name and meaning doesn't work too well at the sites of use.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1316)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)

___
*[core/src/main/java/google/registry/beam/common/RegistryJpaIO.java, line 328 at r2](https://reviewable.io/reviews/google/nomulus/1316#-MjVOpUA9_EN6jUdrydZ:-MjVNElKA4-dZdtjMfZ4:b-1rgjm5) ([raw file](https://github.com/google/nomulus/blob/f7dfcd192e8b8f92b34dd238653131f1e3bbaebc/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L328)):*
> ```Java
>               "Write in batch for " + name(),
>               ParDo.of(
>                   new SqlBatchWriter<>(name(), jpaConverter(), !disableUpdateAutoTimestamp())));
> ```

It seems kind of like a code smell to reverse it like this; I think we want it to always stay "positive" 

Why not use `withUpdateAutoTimestamp` everywhere, then below  in `processElement` we could just do 

```
if (withUpdateAutoTimestamp) {
  actuallyProcessElement(...);
} else {
  ...
}
``` or something?  
```

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1316)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/beam/common/RegistryJpaIO.java, line 328 at r2](https://reviewable.io/reviews/google/nomulus/1316#-MjVOpUA9_EN6jUdrydZ:-MjVahWgEOGqt5WWhPV8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f7dfcd192e8b8f92b34dd238653131f1e3bbaebc/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L328)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It seems kind of like a code smell to reverse it like this; I think we want it to always stay "positive" 

Why not use `withUpdateAutoTimestamp` everywhere, then below  in `processElement` we could just do 

```
if (withUpdateAutoTimestamp) {
  actuallyProcessElement(...);
} else {
  ...
}
``` or something?  
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1316)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @weiminyu)

**Pull request merged**
