### PR TITLE
Migrate Spec11 pipeline to flex template

### PR DESCRIPTION
**Pull request by jianglai**
Unfortunately this PR has turned out to be much bigger than I initially
conceived. However this is no good way to separate it out because the
changes are intertwined. This PR includes 3 main changes:

1. Change the spec11 pipline to use Dataflow Flex Template.
2. Retire the use of the old JPA layer that relies on credential saved
   in KMS.
3. Some extensive refactoring to streamline the logic and improve test
   isolation.

TESTED=deployed to alpha and verified that the pipeline is launched and finished successfully.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1073)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> Reviewed 5 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073)* status: 5 of 19 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[core/src/main/java/google/registry/beam/spec11/Spec11PipelineOptions.java, line 24 at r1](https://reviewable.io/reviews/google/nomulus/1073#-MYAmcwe6XBrdpgBikhe:-MYAmcwe6XBrdpgBikhf:b-sl22x7) ([raw file](https://github.com/google/nomulus/blob/71a61fa59e9373544686b6fe7c5a7e1fa878ace7/core/src/main/java/google/registry/beam/spec11/Spec11PipelineOptions.java#L24)):*
> ```
> String getProjectId()
> ```
The ancestor interface (GcpOptions) already has this property. No need to redefine unless the Description is important.
___
*[core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json, line 42 at r1](https://reviewable.io/reviews/google/nomulus/1073#-MYAnnOp4lUX7v3RTErs:-MYAnnOp4lUX7v3RTErt:b-i1w0tx) ([raw file](https://github.com/google/nomulus/blob/71a61fa59e9373544686b6fe7c5a7e1fa878ace7/core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json#L42)):*
> ```
> "projectId"
> ```
If you don't drop this property from the options, please also drop it here.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073)* status: 3 of 22 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[core/src/main/java/google/registry/beam/spec11/Spec11PipelineOptions.java, line 24 at r1](https://reviewable.io/reviews/google/nomulus/1073#-MYAmcwe6XBrdpgBikhe:-MYFWlWp2OT5aZcvzgMJ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/71a61fa59e9373544686b6fe7c5a7e1fa878ace7/core/src/main/java/google/registry/beam/spec11/Spec11PipelineOptions.java#L24)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> String getProjectId()
> ```
The ancestor interface (GcpOptions) already has this property. No need to redefine unless the Description is important.
</blockquote></details>

Done.
___
*[core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json, line 42 at r1](https://reviewable.io/reviews/google/nomulus/1073#-MYAnnOp4lUX7v3RTErs:-MYFWp9E7YmtPHLG1u71:b-896fix) ([raw file](https://github.com/google/nomulus/blob/71a61fa59e9373544686b6fe7c5a7e1fa878ace7/core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json#L42)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> "projectId"
> ```
If you don't drop this property from the options, please also drop it here.
</blockquote></details>

Done.

**Review by weiminyu — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073)* status: 4 of 22 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @jianglai, and @weiminyu)

___
*[core/src/main/java/google/registry/beam/BeamUtils.java, line 70 at r2](https://reviewable.io/reviews/google/nomulus/1073#-MYFeE6660q79ElOkAyo:-MYFeE6660q79ElOkAyp:b-h2fdzr) ([raw file](https://github.com/google/nomulus/blob/b016baa8345e2f03fa5832daa931b6e879931840/core/src/main/java/google/registry/beam/BeamUtils.java#L70)):*
> ```
> Job name must be unique and consists of only characters [-a-z0-9]
> ```
I think this just applies to flex templates. May want to clarify.
___
*[core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java, line 104 at r2](https://reviewable.io/reviews/google/nomulus/1073#-MYFeZjjBjHVjbCIm77N:-MYFeZjjBjHVjbCIm77O:b35jtn2) ([raw file](https://github.com/google/nomulus/blob/b016baa8345e2f03fa5832daa931b6e879931840/core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java#L104)):*
> ```
> setParameters
> ```
Forgot to mention: the 'registryEnvironment' variable is required if dagger is to be used on the beam workers, which is the case with JpaTransactionManager. In nomulus the value should be RegistryEnvironment.get().name().

**Review by weiminyu — COMMENTED** [review]
Before deployment we need to ensure all grants are in place.

The launcher of flex pipelines needs access to the staged metadata files.  In our case this means the default appengine account needs access to the *-deploy/live/beam folder.

The runner of the pipelines needs access to the pipeline docker images. Although our container registries are private, the runner account can get access through GCS permissions. It needs storage viewer permission to the container registry owner's artifacts bucket.

The best approach is to express such requirements in customer launcher and runner roles (b/184793344). But they probably won't be available before this PR is submitted. If so we may have to set up permissions manually.

Specifically:

appengine default accounts in alpha and crash should be able to access gs://domain-registry-alpha-deploy
appengine default accounts in qa, sandbox, and prod should be able to access gs://domain-registry-dev-deploy

Compute engine default accounts in alpha and crash should be able to access gs://domain-registry-alpha-deploy
Compute engine default accounts in qa, sandbox, and prod should be able to access gs://artifacts.domain-registry-dev.appspot.com

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073#-:-MYFhDiA8LwgK4uBEdrz:b171hvu)* status: 4 of 22 files reviewed, 4 unresolved discussions (waiting on @gbrodman, @jianglai, and @weiminyu)

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073)* status: 4 of 22 files reviewed, 4 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[core/src/main/java/google/registry/beam/BeamUtils.java, line 70 at r2](https://reviewable.io/reviews/google/nomulus/1073#-MYFeE6660q79ElOkAyo:-MYHvVq9Af3z-FVjIx2H:b-896fix) ([raw file](https://github.com/google/nomulus/blob/b016baa8345e2f03fa5832daa931b6e879931840/core/src/main/java/google/registry/beam/BeamUtils.java#L70)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> Job name must be unique and consists of only characters [-a-z0-9]
> ```
I think this just applies to flex templates. May want to clarify.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java, line 104 at r2](https://reviewable.io/reviews/google/nomulus/1073#-MYFeZjjBjHVjbCIm77N:-MYI2esbC2YbWYGf0G_v:b-896fix) ([raw file](https://github.com/google/nomulus/blob/b016baa8345e2f03fa5832daa931b6e879931840/core/src/main/java/google/registry/reporting/spec11/GenerateSpec11ReportAction.java#L104)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> setParameters
> ```
Forgot to mention: the 'registryEnvironment' variable is required if dagger is to be used on the beam workers, which is the case with JpaTransactionManager. In nomulus the value should be RegistryEnvironment.get().name().
</blockquote></details>

Done.

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073)* status: 4 of 22 files reviewed, 6 unresolved discussions (waiting on @gbrodman, @jianglai, and @weiminyu)

___
*[core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json, line 59 at r1](https://reviewable.io/reviews/google/nomulus/1073#-MYIe2lo8AAIptl3Y_Ie:-MYIe2lo8AAIptl3Y_If:b-344ha5) ([raw file](https://github.com/google/nomulus/blob/71a61fa59e9373544686b6fe7c5a7e1fa878ace7/core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json#L59)):*
> ```
> spec11_pipeline
> ```
___
*[core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json, line 51 at r3](https://reviewable.io/reviews/google/nomulus/1073#-MYIe4BVCnK2y7ieba2u:-MYIe4BVCnK2y7ieba2v:br2yg7v) ([raw file](https://github.com/google/nomulus/blob/cb2440a9815ce8dcfc9412961c62dfd89134b235/core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json#L51)):*
> ```
> "Nomulus CommitLog start time"
> ```
Need update.

**Review by jianglai — COMMENTED** [review]
> appengine default accounts in alpha and crash should be able to access gs://domain-registry-alpha-deploy
> appengine default accounts in qa, sandbox, and prod should be able to access gs://domain-registry-dev-deploy
> Compute engine default accounts in alpha and crash should be able to access gs://domain-registry-alpha-deploy
> Compute engine default accounts in qa, sandbox, and prod should be able to access gs://artifacts.domain-registry-dev.appspot.com

I think you meant that "Compute engine default accounts in alpha and crash should be able to access gs://artifacts.domain-registry-alpha.appspot.com", right?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073#-:-MYehY7M4MEUzysPbMJw:butjcbt)* status: 4 of 22 files reviewed, 6 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json, line 59 at r1](https://reviewable.io/reviews/google/nomulus/1073#-MYIe2lo8AAIptl3Y_Ie:-MYehqObClc8lwAacScP:b-896fix) ([raw file](https://github.com/google/nomulus/blob/71a61fa59e9373544686b6fe7c5a7e1fa878ace7/core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json#L59)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> spec11_pipeline
> ```

</blockquote></details>

Done.
___
*[core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json, line 51 at r3](https://reviewable.io/reviews/google/nomulus/1073#-MYIe4BVCnK2y7ieba2u:-MYehqip9OYd1IyzTecY:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cb2440a9815ce8dcfc9412961c62dfd89134b235/core/src/main/resources/google/registry/beam/spec11_pipeline_metadata.json#L51)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> "Nomulus CommitLog start time"
> ```
Need update.
</blockquote></details>

Done.

**Review by weiminyu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 19 files at r1, 2 of 9 files at r2, 3 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073)* status: 11 of 22 files reviewed, 3 unresolved discussions (waiting on @gbrodman, @jianglai, and @weiminyu)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 108 at r4](https://reviewable.io/reviews/google/nomulus/1073#-MYkwOFYEhr1l7ZM_f2_:-MYkwOFYEhr1l7ZM_f2a:bgadl87) ([raw file](https://github.com/google/nomulus/blob/9fc104d39677f8aa6260a892c6d0cd19283196b8/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L108)):*
> ```
> beamJpaExtension
> ```
I don't think this rule is needed anymore. It can be deleted along with BeamJpaModule.

**Review by weiminyu — APPROVED** [review]
> Reviewed 5 of 19 files at r1, 2 of 9 files at r2, 1 of 2 files at r3, 3 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman, @jianglai, and @weiminyu)

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1073)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 108 at r4](https://reviewable.io/reviews/google/nomulus/1073#-MYkwOFYEhr1l7ZM_f2_:-MYm03MO7jJudMY_vKuw:bciuwi) ([raw file](https://github.com/google/nomulus/blob/9fc104d39677f8aa6260a892c6d0cd19283196b8/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L108)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> beamJpaExtension
> ```
I don't think this rule is needed anymore. It can be deleted along with BeamJpaModule.
</blockquote></details>

Removed the extension. I think we should delete `BeamJpaModule` and `BeamJpaExtension` in a separate PR. This one is big as it is.

**Pull request merged**
