### PR TITLE
Reformat a file

### PR DESCRIPTION
**Pull request by jianglai**
Constants should be SNAKE_CASE named and static fields usually go before
instance fields.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1305)

### CODE REVIEW

**Review by rachelguan — COMMENTED** [review]
thanks will keep that in mind.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1305#-:-Mic-lg70NY9XX9t1IFL:b-qbfdo1)* status: 0 of 1 files reviewed, all discussions resolved

**Review by jianglai — COMMENTED** [review]
Hi Rachel, you'll need to actually approve this PR for it to be mergeable.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1305#-:-MihOuec7E9GId6ok_fn:b-hegigo)* status: 0 of 1 files reviewed, all discussions resolved

**Review by rachelguan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1305)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Comment by jianglai** [comment]
Thanks! And just an FYI usually we leave it to the author to merge the PR. It's OK in this case as it's just a simple reformat but there might be cases where the author want to plan the merge order of several related PRs.

**Pull request merged**
