### PR TITLE
Make Kythe work with Java 17

### PR DESCRIPTION
**Pull request by jianglai**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2293)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2293)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2293)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2293)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`build.gradle` line 214 at r3](https://reviewable.io/reviews/google/nomulus/2293#-NowG08B45AgmIEe8vQV:-NowG08B45AgmIEe8vQW:bux3ikv) ([raw file](https://github.com/google/nomulus/blob/79354b9bf0abae1b0aa5367244c510ee1b19798b/build.gradle#L214)):*
> ```Gradle
>         options.forkOptions.executable =
>           file("${System.env.JAVA_HOME}/bin/javac")
>         options.compilerArgs = ["--add-exports",
> ```

Gee, that adds quite a bit of noise to the file. Is it because tools.jar doesn't come with jdk we installed? Is there any other openjdk that we can use instead?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2293)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`build.gradle` line 214 at r3](https://reviewable.io/reviews/google/nomulus/2293#-NowG08B45AgmIEe8vQV:-NowH1ii3dg08S7oevLL:bz92vwi) ([raw file](https://github.com/google/nomulus/blob/79354b9bf0abae1b0aa5367244c510ee1b19798b/build.gradle#L214)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Gee, that adds quite a bit of noise to the file. Is it because tools.jar doesn't come with jdk we installed? Is there any other openjdk that we can use instead?
</blockquote></details>

it's because higher versions of JDK have more [modules](https://www.oracle.com/corporate/features/understanding-java-9-modules.html) unexposed by default, and the Kythe extractor needs access to these modules. See details in b/321278681.

**Pull request merged**
