### PR TITLE
Do not use shaded dependencies from testcontainers

### PR DESCRIPTION
**Pull request by jianglai**
Also fixed a flaky test where it depends on the current date. On a leap
day, now + 1 year - 1 year results in 2/28 instead of 2/29.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2343)

### CODE REVIEW

**Comment by jianglai** [comment]
Note that FOSS SQL integration tests run deployed code against new SQL, therefore they still fail on 2/29/2024 due to the flaky test.

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2343)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @jianglai and @sarahcaseybot)

___
*[`core/src/test/java/google/registry/model/billing/BillingBaseTest.java` line 54 at r2](https://reviewable.io/reviews/google/nomulus/2343#-Nrpxxs841uX9VW66SvJ:-Nrpxxs841uX9VW66SvK:b4hfvb7) ([raw file](https://github.com/google/nomulus/blob/6fc8dcb0017e772692183000949f681074175d65/core/src/test/java/google/registry/model/billing/BillingBaseTest.java#L54)):*
> ```Java
> /** Unit tests for {@link BillingBase}. */
> public class BillingBaseTest extends EntityTestCase {
>   private final DateTime now = DateTime.parse("2012-01-23T22:33:44Z");
> ```

We should add a note in BillingRecurrence.java that leap year is not a problem when doing that `minusYears` call.



_Code quote:_
```Java
DateTime.parse("2012-01-23T22:33:44Z");
```

**Review by jianglai — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2343)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot and @weiminyu)

___
*[`core/src/test/java/google/registry/model/billing/BillingBaseTest.java` line 54 at r2](https://reviewable.io/reviews/google/nomulus/2343#-Nrpxxs841uX9VW66SvJ:-Nrq1jqX375OY52eIfKw:bb6un1j) ([raw file](https://github.com/google/nomulus/blob/6fc8dcb0017e772692183000949f681074175d65/core/src/test/java/google/registry/model/billing/BillingBaseTest.java#L54)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

We should add a note in BillingRecurrence.java that leap year is not a problem when doing that `minusYears` call.
</blockquote></details>

Done

**Review by weiminyu — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2343)* status: all files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot)

**Pull request merged**
