### PR TITLE
Add VKey to String and String to VKey methods

### PR DESCRIPTION
**Pull request by rachelguan**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1396)

### CODE REVIEW

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 43 at r6](https://reviewable.io/reviews/google/nomulus/1396#-Mn7K0GD5q_CE8VVtu22:-MnSAZjFEl-2-vt1sLGD:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4fdda6bfa0e1ada3344b50298cd8153c1318be44/core/src/main/java/google/registry/persistence/VKey.java#L43)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

It would be useful to document the format of a stringified key, this probably belongs in the javadoc for the `stringify()` method.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/persistence/VKey.java, line 46 at r7](https://reviewable.io/reviews/google/nomulus/1396#-Mn7XVwCDRulrCln6DZ6:-MnSAc8r9K5JYiKn7AF0:bob1bkf) ([raw file](https://github.com/google/nomulus/blob/85f335f72784c3b750a070ea00aa7ab1dba138f1/core/src/main/java/google/registry/persistence/VKey.java#L46)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Base58 is strictly limited to alphanumerics and excludes letters that are visually ambiguous.  It's less popular than Base64 (and harder to implement and likely a little less performant) but certainly viable.
</blockquote></details>

decided to go with the more popular choice Base64 for this use case. 
___
*[core/src/test/java/google/registry/persistence/VKeyTest.java, line 159 at r8](https://reviewable.io/reviews/google/nomulus/1396#-MnBDyUy32AfJkuO0MWT:-MnSAyQlEE17zn1lztRQ:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/9d27cdfbc438e4e0051500ac3ba0c20901e13149/core/src/test/java/google/registry/persistence/VKeyTest.java#L159)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Please split up the overly long strings (presumably before or after the "@" signs) here and below.
</blockquote></details>

done

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396#-:-MnSCLpq5sD7id7V0TTC:bnfp4nl)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @mindhog)

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r9, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396)* status: all files reviewed, 6 unresolved discussions (waiting on @rachelguan)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 140 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVWKDA4Ydq_3VAih1j:-MnVWKDA4Ydq_3VAih1k:b3j714t) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/core/src/main/java/google/registry/persistence/VKey.java#L140)):*
> ```Java
>    * <p>Example of a Vkey string by fromWebsafeKey(): agR0ZXN0chYLEgpEb21haW5CYXNlIgZST0lELTEM
>    *
>    * <p>Example of a vkey string by stringify(): google.registry.testing.TestObject@sql:rO0ABX +
> ```

Please enclose the first portion of the string in quotes, too: "google.registry.testing.TestObject@sql:rO0ABX" + ...
  
 
___
*[core/src/main/java/google/registry/persistence/VKey.java, line 298 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVWzugDoLXXYHSGs-X:-MnVWzugDoLXXYHSGs-Y:bvebitv) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/core/src/main/java/google/registry/persistence/VKey.java#L298)):*
> ```
> @
> ```

Colon, in this case.  Also, please enclose the single character symbols in quotes ("@", ":").
___
*[core/src/test/java/google/registry/persistence/VKeyTest.java, line 161 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVXV7wCYPA_lmnovtJ:-MnVXV7wCYPA_lmnovtK:bkixo43) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/core/src/test/java/google/registry/persistence/VKeyTest.java#L161)):*
> ```Java
>     assertThat(vkey.stringify())
>         .isEqualTo(
>             "kind:google.registry.model.domain.DomainBase@sql:rO0ABXQABlJPSUQtMQ@ofy:agR0ZXN0chYLEgpEb21haW5CYXNlIgZST0lELTEM");
> ```

Please split the overly long string (again, preferably at the "@" or ":" symbols).
___
*[core/src/test/java/google/registry/persistence/VKeyTest.java, line 260 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVXvMI-BZoH4g_KqJL:-MnVXvMI-BZoH4g_KqJM:bldjlcy) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/core/src/test/java/google/registry/persistence/VKeyTest.java#L260)):*
> ```Java
>                 VKey.create(
>                     "kind:google.registry.testi"
>                         + "ng.TestObject@sql:rO0ABXQAA2Zvbw==@ofy:agR0ZXN0cjELEg9FbnRpdHlHcm91cFJvb3QiCWNyb3Nz"
> ```

Split the overly long string (you may want to set up your editor/IDE to indicate the 100 character point, I believe intellij supports this?)
___
*[util/build.gradle, line 63 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVYeEACMJAke4lQEgn:-MnVYeEACMJAke4lQEgo:blaxfsv) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/util/build.gradle#L63)):*
> ```Gradle
>   testAnnotationProcessor deps['com.google.auto.value:auto-value']
>   testAnnotationProcessor deps['com.google.dagger:dagger-compiler']
>     compile 'commons-codec:commons-codec:1.15'
> ```

One of these things is not like the others :-).

For specifying dependencies, we add an entry for the actual maven id (consisting of "group:artifact:version") to `dependencies.gradle`, and then reference the dependency as `deps['group:artifact']` in this section.

Also, please add the new compile command with th eother compile commands (preferably sorted) and fix the indentation. 
___
*[util/src/main/java/google/registry/util/SerializeUtils.java, line 96 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnV_rVxCltDj9bHCysi:-MnV_rVxCltDj9bHCysj:b-dame1z) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/util/src/main/java/google/registry/util/SerializeUtils.java#L96)):*
> ```Java
>     checkArgument(
>         Base64.isBase64(objectString) && !objectString.endsWith("="),
>         "Object string is not in base 64");
> ```

We generally use "//" (C++ style) comments in the implementation.

But more importantly, does base64 not give a reasonable exception in these cases? 

It seems to me that this check isn't very helpful: at this point, if there is a trailing equal sign that hasn't been escaped, we will have already failed to parse the URL correctly.  If we did get to this point, and the decodeBase64 below is able to deal with it, we certainly wouldn't want the check to interfere with that.

If you wanted this kind of protection, you'd probably want to put it in `stringify()`, so that no bad value gets put in the URL in the first place.  But in this case, I think we're better off just trusting the underlying code and tests.

**Review by mindhog — COMMENTED** [review]
Almost there.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396#-:-MnVclbhARFo4WX7jY4z:b-debr7t)* status: all files reviewed, 6 unresolved discussions (waiting on @rachelguan)

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @mindhog and @rachelguan)

___
*[core/src/main/java/google/registry/persistence/VKey.java, line 140 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVWKDA4Ydq_3VAih1j:-MnVzaTf2v_4Qve7OvWf:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/core/src/main/java/google/registry/persistence/VKey.java#L140)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Please enclose the first portion of the string in quotes, too: "google.registry.testing.TestObject@sql:rO0ABX" + ...
  
 

</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/persistence/VKey.java, line 298 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVWzugDoLXXYHSGs-X:-MnVzuoI89UKn_8HKdlf:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/core/src/main/java/google/registry/persistence/VKey.java#L298)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

> ```
> @
> ```

Colon, in this case.  Also, please enclose the single character symbols in quotes ("@", ":").
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/persistence/VKeyTest.java, line 161 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVXV7wCYPA_lmnovtJ:-MnW-GUP6Je0FuTjoK3S:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/core/src/test/java/google/registry/persistence/VKeyTest.java#L161)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Please split the overly long string (again, preferably at the "@" or ":" symbols).
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/persistence/VKeyTest.java, line 260 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVXvMI-BZoH4g_KqJL:-MnW-X8y0emxzJ0PUIeD:bnvqrzf) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/core/src/test/java/google/registry/persistence/VKeyTest.java#L260)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Split the overly long string (you may want to set up your editor/IDE to indicate the 100 character point, I believe intellij supports this?)
</blockquote></details>

done. ran with jIFA and reformatted the portion but no error when running with coreDev.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @mindhog and @rachelguan)

___
*[util/src/main/java/google/registry/util/SerializeUtils.java, line 96 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnV_rVxCltDj9bHCysi:-MnW21tG7OO4Q4Nccnqs:b-pu25en) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/util/src/main/java/google/registry/util/SerializeUtils.java#L96)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

We generally use "//" (C++ style) comments in the implementation.

But more importantly, does base64 not give a reasonable exception in these cases? 

It seems to me that this check isn't very helpful: at this point, if there is a trailing equal sign that hasn't been escaped, we will have already failed to parse the URL correctly.  If we did get to this point, and the decodeBase64 below is able to deal with it, we certainly wouldn't want the check to interfere with that.

If you wanted this kind of protection, you'd probably want to put it in `stringify()`, so that no bad value gets put in the URL in the first place.  But in this case, I think we're better off just trusting the underlying code and tests.
</blockquote></details>

changed the commenting style. 

so the method i use in stringify() would not return string with trailing equal sign. 
parse() is used to handle string created by stringify(). However, in case parse() is used to create vkey with string that's in the right format but not generated by stringify(), [may contain padding] isBase64() from apache will return true. 

it's just a sanity check that i decided to add when testing with base 64 strings. i can remove that.

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r12, 1 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @mindhog and @rachelguan)

___
*[util/src/main/java/google/registry/util/SerializeUtils.java, line 96 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnV_rVxCltDj9bHCysi:-MnW9prVEe2pjQ97aMkN:b-693qmi) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/util/src/main/java/google/registry/util/SerializeUtils.java#L96)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

changed the commenting style. 

so the method i use in stringify() would not return string with trailing equal sign. 
parse() is used to handle string created by stringify(). However, in case parse() is used to create vkey with string that's in the right format but not generated by stringify(), [may contain padding] isBase64() from apache will return true. 

it's just a sanity check that i decided to add when testing with base 64 strings. i can remove that.  
</blockquote></details>

Yeah, unless `Base64.decodeBase64()` does something completely bad (like silently succeeding with bad data or throwing an exception with a useless message)  I'd recommend removing the entire `checkArgument()`.  `decodeBase64()` will most likely fail with an exception for an invalid base64 string, and (at the point at which it is called) if there are padding equal signs, you don't care because they've already been successfully parsed out of the URL.

It's good that you're verifying that there are no padding equal signs, but you're already covering that in the test suite.  No need to do so in the production code.

**Review by rachelguan — COMMENTED** [review]
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396)* status: all files reviewed, 2 unresolved discussions (waiting on @mindhog and @rachelguan)

___
*[util/build.gradle, line 63 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnVYeEACMJAke4lQEgn:-MnW3CkY-tXfEVHGuziR:b-ruckrx) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/util/build.gradle#L63)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

One of these things is not like the others :-).

For specifying dependencies, we add an entry for the actual maven id (consisting of "group:artifact:version") to `dependencies.gradle`, and then reference the dependency as `deps['group:artifact']` in this section.

Also, please add the new compile command with th eother compile commands (preferably sorted) and fix the indentation. 
</blockquote></details>

it threw 2 warning with unadded dependencies from jIFA so i just did a quick fix by running a lint command. 

fixed and built the project successfully via ./gradlew coreDev

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @mindhog)

___
*[util/src/main/java/google/registry/util/SerializeUtils.java, line 96 at r11](https://reviewable.io/reviews/google/nomulus/1396#-MnV_rVxCltDj9bHCysi:-MnWQy7-792W9xYNDDmW:bypkdgg) ([raw file](https://github.com/google/nomulus/blob/ee9fe0f1e862e8779caaef11f29346021173a4eb/util/src/main/java/google/registry/util/SerializeUtils.java#L96)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Yeah, unless `Base64.decodeBase64()` does something completely bad (like silently succeeding with bad data or throwing an exception with a useless message)  I'd recommend removing the entire `checkArgument()`.  `decodeBase64()` will most likely fail with an exception for an invalid base64 string, and (at the point at which it is called) if there are padding equal signs, you don't care because they've already been successfully parsed out of the URL.

It's good that you're verifying that there are no padding equal signs, but you're already covering that in the test suite.  No need to do so in the production code.
</blockquote></details>

Done. removed that

**Review by mindhog — APPROVED** [review]
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachelguan)

**Review by rachelguan — COMMENTED** [review]
> Reviewed 1 of 2 files at r13, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1396)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachelguan)

**Pull request merged**
