### PR TITLE
Rename HostResource table to Host

### PR DESCRIPTION
**Pull request by mindhog**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/804)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/804)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[db/src/main/resources/sql/flyway/V54__rename_host_table.sql, line 20 at r1](https://reviewable.io/reviews/google/nomulus/804#-MHSvcEW34IF8m1fS74R:-MHSvcEW34IF8m1fS74S:b5zdoei) ([raw file](https://github.com/google/nomulus/blob/95fe95d6797a95c129bd145a8fc54c5a1ec2c73d/db/src/main/resources/sql/flyway/V54__rename_host_table.sql#L20)):*
> ```TSQL
> ALTER TABLE "DomainHost" DROP CONSTRAINT fk_domainhost_host_valid;
> ALTER TABLE "HostResource" DROP CONSTRAINT "HostResource_pkey";
> DROP TABLE "HostResource";
> ```

Why not https://www.techonthenet.com/postgresql/tables/alter_table.php  ?

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/804)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[db/src/main/resources/sql/flyway/V54__rename_host_table.sql, line 20 at r1](https://reviewable.io/reviews/google/nomulus/804#-MHSvcEW34IF8m1fS74R:-MHSvj663YTgInrEgsww:b-9x8vtc) ([raw file](https://github.com/google/nomulus/blob/95fe95d6797a95c129bd145a8fc54c5a1ec2c73d/db/src/main/resources/sql/flyway/V54__rename_host_table.sql#L20)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why not https://www.techonthenet.com/postgresql/tables/alter_table.php  ?
</blockquote></details>

```
ALTER TABLE table_name
  RENAME TO new_table_name;
```

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/804)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[db/src/main/resources/sql/flyway/V54__rename_host_table.sql, line 20 at r1](https://reviewable.io/reviews/google/nomulus/804#-MHSvcEW34IF8m1fS74R:-MHWpFeV7Sz-7L5DTL1w:bf8prpn) ([raw file](https://github.com/google/nomulus/blob/95fe95d6797a95c129bd145a8fc54c5a1ec2c73d/db/src/main/resources/sql/flyway/V54__rename_host_table.sql#L20)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

```
ALTER TABLE table_name
  RENAME TO new_table_name;
```
</blockquote></details>

I didn't know about it :-)  Done.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/804)* status: 0 of 4 files reviewed, all discussions resolved

___
*[db/src/main/resources/sql/flyway/V54__rename_host_table.sql, line 20 at r1](https://reviewable.io/reviews/google/nomulus/804#-MHSvcEW34IF8m1fS74R:-MHlHB3H2WyM35WBLxKU:b-o4m0ei) ([raw file](https://github.com/google/nomulus/blob/95fe95d6797a95c129bd145a8fc54c5a1ec2c73d/db/src/main/resources/sql/flyway/V54__rename_host_table.sql#L20)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I didn't know about it :-)  Done.
</blockquote></details>

I didn't either, but I assumed there had to be a way to rename a table rather than drop it entirely and re-create it from scratch because the latter approach loses all data in the table and thus wouldn't typically even be an option!  Google to the rescue.  (Surprisingly, it wasn't Stackoverflow that came up as the first result.)

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/804#-:-MHlHZcd6DO72h36fa8k:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved

**Pull request merged**
