### PR TITLE
Add a Beam pipeline to generate RDE deposit (part 1)

### PR DESCRIPTION
**Pull request by jianglai**
This is the first part of the RdeStagingAction SQL migration where the
mapper logic is implemented in Beam.

A few helper methods are added to convert the DomainContent, HostBase
and ContactBase to their respective terminal child classes. This is
necessary and possible because the child classes do not have extra
fields and the base classes exist only to be embedded to other entities
(such as the various HistoryEntry entities). The conversion is necessary
because most of our code expects the terminal classes, such as the
RdeMarshaller's various marshallXXX() methods. The alternative would be
to change all the call sites, which seems to be much more disruptive.

Unfortunately there is is no good way to do this conversion than just
creating a builder and setting every fields there is.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1219)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md5A_bZ88JA98IlqIr1:-Md5A_b_AWOLi80yCKKN:bau7w5a) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L135)):*
> ```
> id -> VKey.createSql(Registrar.class, id)
> ```
Nice trick to sidestep the need for a coder for EppResource objects but passing the VKey around.

However, this does require an extra load-by-key query for each individual EppResource object. We may want investigate whether it has an impact on performance.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md5A_bZ88JA98IlqIr1:-MdHtaQb6rHNvOSlvVag:b-rswr2o) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L135)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> id -> VKey.createSql(Registrar.class, id)
> ```
Nice trick to sidestep the need for a coder for EppResource objects but passing the VKey around.

However, this does require an extra load-by-key query for each individual EppResource object. We may want investigate whether it has an impact on performance. 
</blockquote></details>

I think this is just delaying the load from the read connector to the first transform. Unless there's a significant performance difference between loading all the resources in the initial query vs. loading a resources individually by its primary key?

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 0 of 24 files reviewed, 9 unresolved discussions (waiting on @gbrodman, @jianglai, and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md5A_bZ88JA98IlqIr1:-MdHzfAu6cObwG6XgwLa:b-lhklt6) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L135)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I think this is just delaying the load from the read connector to the first transform. Unless there's a significant performance difference between loading all the resources in the initial query vs. loading a resources individually by its primary key?
</blockquote></details>

There really aren't that many real `Registrar` entities anyway, and this is only run once daily, so I can't see how it should affect performance, not unless the registrar is being loaded for each domain (that's not happening here, right?)

But there is another potential wrinkle -- with this approach we can get an inconsistent set of `Registrar` entities, e.g. if several of them happen to be updated right around the time we run RDE, we might randomly get some of the updates but not others.  Does that matter?
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 1 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdHylL_2yBiFhR3kDWa:-MdHylLaAnvSvsFthp47:b-vmzkyv) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L1)):*
> ```Java
> // Copyright 2018 The Nomulus Authors. All Rights Reserved.
> ```

Wrong year.
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 90 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdHyyvxDet1-CqU07ww:-MdHyyvxDet1-CqU07wx:b70vnd4) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L90)):*
> ```Java
>   private static final String EPP_RESOURCE_QUERY =
>       "SELECT id FROM %entity% "
>           + "WHERE COALESCE(creationClientId, '') NOT LIKE 'prober-%' "
> ```

Are all 3 of these clauses necessary?  We already have these?

And is `COALESCE` really necessary here?  Surely `NULL NOT LIKE '...'` doesn't return true?
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 95 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdHzE6i9grRP9Wd5KVH:-MdHzE6i9grRP9Wd5KVI:b-1knum7) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L95)):*
> ```Java
> 
>   public static String createEppResourceQuery(Class<? extends EppResource> clazz) {
>     return EPP_RESOURCE_QUERY.replace("%entity%", clazz.getAnnotation(Entity.class).name())
> ```

This isn't how templated SQL queries work.  Because you're not doing any escaping here, this could, in theory, maybe somehow, leave open a SQL injection attack.

Why not just template the name of the table properly?
___
*[core/src/main/java/google/registry/model/contact/ContactBase.java, line 294 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI01si6DTb8bUr68m9:-MdI01si6DTb8bUr68mA:bkun8he) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/model/contact/ContactBase.java#L294)):*
> ```Java
>   }
> 
>   public ContactResource asContactResource() {
> ```

A Javadoc explaining what this is, why it's necessary, what it's used for, etc., would be helpful.
___
*[core/src/main/java/google/registry/model/contact/ContactBase.java, line 294 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI0RJ62CYHr3fsAyI-:-MdI0RJ62CYHr3fsAyI0:b3gm26p) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/model/contact/ContactBase.java#L294)):*
> ```Java
>   }
> 
>   public ContactResource asContactResource() {
> ```

@gbrodman, you're confirming that there's no better way to do this?  Seeing as how `ContactResource` directly extends `ContactBase`, I'm surprised that this is the best way to do it?  Also might it make more sense for this to be in `ContactResource`, as in, something like`new ContactResource.Builder().setFieldsFromContactBase(contactBase).build()` or `ContactResource.fromContactBase(contactBase)` or `new ContactResource(contactBase)`?  It feels a little strange to see the base class referring to the extending class, rather than vice-versa.

And this approach seems fragile; you can imagine a new field being added to an EPP resource (like the auto-renew end time which I recently added), but then forgetting to add it here, and then it only fails in RDE in production.

Are there tests we can add to guard against this?
___
*[core/src/main/java/google/registry/rde/PendingDeposit.java, line 98 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI1h1fCvn6FIe8ooFf:-MdI1h1gCHpR0iHsgZfx:b-olp2y1) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/rde/PendingDeposit.java#L98)):*
> ```Java
>   PendingDeposit() {}
> 
>   public static class PendingDepositCoder extends AtomicCoder<PendingDeposit> {
> ```

Missing Javadoc.
___
*[core/src/main/java/google/registry/rde/RdeFragmenter.java, line 36 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI1qCg1_2mMnEBqPcO:-MdI1qCg1_2mMnEBqPcP:b63vk2z) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/rde/RdeFragmenter.java#L36)):*
> ```Java
> /** Loading cache that turns a resource into XML for the various points in time and modes. */
> public class RdeFragmenter {
>   private final Map<WatermarkModePair, Optional<DepositFragment>> cache = new HashMap<>();
> ```

Does thread synchronization matter here?  https://crunchify.com/hashmap-vs-concurrenthashmap-vs-synchronizedmap-how-a-hashmap-can-be-synchronized-in-java/

Also why aren't you using Guava's `LoadingCache`, like we do throughout our codebase?

(Is this just for memoization?)
___
*[core/src/main/java/google/registry/rde/RdeFragmenter.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI2gTOEoqK65t_a1I8:-MdI2gTOEoqK65t_a1I9:bfqdbq5) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/rde/RdeFragmenter.java#L91)):*
> ```Java
>       return result;
>     } else {
>       throw new AssertionError(resource.toString());
> ```

Not a useful error message (admittedly this is pre-existing, but we might as well fix it now).

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 0 of 24 files reviewed, 9 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md5A_bZ88JA98IlqIr1:-MdHwhLE9B65cD55Lb9E:b-i4wffg) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L135)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There really aren't that many real `Registrar` entities anyway, and this is only run once daily, so I can't see how it should affect performance, not unless the registrar is being loaded for each domain (that's not happening here, right?)

But there is another potential wrinkle -- with this approach we can get an inconsistent set of `Registrar` entities, e.g. if several of them happen to be updated right around the time we run RDE, we might randomly get some of the updates but not others.  Does that matter?
</blockquote></details>

I'm also referring to the same pattern used in createInputs().

Batch query is typically much faster than querying elements individually, especially since we are doing millions of calls here.
But depending on the rest of the application it may or may not worth optimize for it. We should probably leave a todo here as a reminder to look back.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 21 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 21 of 24 files reviewed, 12 unresolved discussions (waiting on @CydeWeys, @jianglai, and @weiminyu)

___
*[core/src/main/java/google/registry/model/contact/ContactBase.java, line 294 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI0RJ62CYHr3fsAyI-:-MdI3pVp3dmtEk23f8tU:b-oab7ni) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/model/contact/ContactBase.java#L294)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

@gbrodman, you're confirming that there's no better way to do this?  Seeing as how `ContactResource` directly extends `ContactBase`, I'm surprised that this is the best way to do it?  Also might it make more sense for this to be in `ContactResource`, as in, something like`new ContactResource.Builder().setFieldsFromContactBase(contactBase).build()` or `ContactResource.fromContactBase(contactBase)` or `new ContactResource(contactBase)`?  It feels a little strange to see the base class referring to the extending class, rather than vice-versa.

And this approach seems fragile; you can imagine a new field being added to an EPP resource (like the auto-renew end time which I recently added), but then forgetting to add it here, and then it only fails in RDE in production.

Are there tests we can add to guard against this?
</blockquote></details>

I agree that this seems fragile, and we should put this in a builder (similar to how we already use copyFrom in HistoryEntry::builder 
___
*[core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java, line 68 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md3jfkA8MZpEICNgWat:-Md3jfkA8MZpEICNgWau:b3ox9j9) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java#L68)):*
> ```Java
>    * Adds a WHERE clause to the query specifying that a value must not be in the given collection.
>    */
>   public CriteriaQueryBuilder<T> whereFieldIsNotIn(String fieldName, Collection<?> values) {
> ```

If we don't use this, we should remove it from the PR as unnecessary code.
___
*[core/src/test/java/google/registry/flows/EppPointInTimeTest.java, line 162 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI2j-KDEL58XUotCTj:-MdI2j-L1h3GjdLx0mWx:b-rhud6c) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/test/java/google/registry/flows/EppPointInTimeTest.java#L162)):*
> ```Java
>       assertAboutImmutableObjects()
>           .that(loadAtPointInTime(latest, timeAtFirstUpdate))
>           .isEqualExceptFields(domainAfterFirstUpdate, "updateTimestamp");
> ```

Wait, why is the update timestamp getting updated? That shouldn't be happening AFAIK 
___
*[core/src/test/java/google/registry/testing/DatastoreEntityExtension.java, line 54 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI1B365X71BbP3wNH7:-MdI1B365X71BbP3wNH8:bfkt808) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/test/java/google/registry/testing/DatastoreEntityExtension.java#L54)):*
> ```Java
>    * Whether all threads should be masqueraded as GAE threads.
>    *
>    * <p>This is particularly useful when new threads are spawn during a test. For example when
> ```

very nitty: spawn -> spawned (and same in the next paragraph) 
___
*[core/src/test/java/google/registry/testing/DatastoreEntityExtension.java, line 59 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI1RCQ8AaJ6wRe9LfQ:-MdI1RCQ8AaJ6wRe9LfR:bcmth4l) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/test/java/google/registry/testing/DatastoreEntityExtension.java#L59)):*
> ```Java
>    *
>    * <p>Warning: by setting this value to true, any thread spawn by the current JVM will be
>    * masqueraded during the execution of the current test test, including those running other tests
> ```

1. "test" is duplicated 
2. I'm not sure "masqueraded" is the right term here or at least it might require a bit more information, are you in essence saying that every thread spawned by this thread will pretend to be this thread?

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 21 of 24 files reviewed, 13 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 155 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI472Z9iZWD5F43jMA:-MdI472Z9iZWD5F43jMB:bgo3iac) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L155)):*
> ```
> .apply("Marshal " + clazz.getSimpleName() + " into DepositFragment", mapToFragments(clazz));
> ```
mapToFragments could be a high-fanout function. Consider adding a Reshuffle stage after this:

https://cloud.google.com/dataflow/docs/guides/deploying-a-pipeline#preventing-fusion

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 21 of 24 files reviewed, 13 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md5A_bZ88JA98IlqIr1:-MdIBSkXEPsNgMZb_lk8:b-lll00o) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L135)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

I'm also referring to the same pattern used in createInputs().

Batch query is typically much faster than querying elements individually, especially since we are doing millions of calls here.
But depending on the rest of the application it may or may not worth optimize for it. We should probably leave a todo here as a reminder to look back.
</blockquote></details>

@cydeweys As for concurrent updates, the soft updates don't matter since the pipeline will try to find the correct snapshot at the reporting time.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 8 of 27 files reviewed, 13 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md5A_bZ88JA98IlqIr1:-MdKCZPHEsIECgXS4AUc:b-wbke1d) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L135)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

@cydeweys As for concurrent updates, the soft updates don't matter since the pipeline will try to find the correct snapshot at the reporting time. 
</blockquote></details>

@weiminyu loading snapshots only happens for epp resources, not registrars. Since we don't current load registrars at the time of the watermark anyway I don't think it is a big issue. Of course we are talking about internal inconsistency vs general stale data, so maybe we should ask Crystal for clarification?

Regarding using EntityProto as coder (as suggested in the email thread), that class is from the datastore SDK so we will have to fork that code (or live with a dependency on the SDK).
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 1 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdHylL_2yBiFhR3kDWa:-MdJNkEx36sYUJddGqO8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L1)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Wrong year.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 90 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdHyyvxDet1-CqU07ww:-MdJNvPME0lOFU3SghEF:b4qmll8) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L90)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Are all 3 of these clauses necessary?  We already have these?

And is `COALESCE` really necessary here?  Surely `NULL NOT LIKE '...'` doesn't return true?
</blockquote></details>

I am copying the logic from mapper, which does check for all three conditions. And `NULL NOT LIKE '...'` returns `NULL`, which is not `TRUE, so the entity got dropped... I'm surprised as well, see this:

https://stackoverflow.com/questions/22818070/behaviour-of-not-like-with-null-values

"Comparisons with NULL not using IS NULL or IS NOT NULL return NULL instead of true or false in most/all database systems."
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 95 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdHzE6i9grRP9Wd5KVH:-MdJQKMW7F1bAh35vUTN:b48xkcq) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L95)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This isn't how templated SQL queries work.  Because you're not doing any escaping here, this could, in theory, maybe somehow, leave open a SQL injection attack.

Why not just template the name of the table properly?
</blockquote></details>

Because we are replacing the FROM part. When calling `setParameter` (at least with JPQL), Hibernate actually does the field name -> column name translation for you (that's why you can use field name in your HPL/JPQL query) so it needs to know the entity beforehand. If you ask it to set the table itself it would not work. If we were using native query then yes, but I think in that case there's actually *more* injection attack risk because no sanitation is done at all on the injected parameters.

The injection attack risk here should remain theoretical because we also control the table name (set by the `@Entity` annotation).

See here: https://stackoverflow.com/questions/40956013/how-to-replace-table-name-with-value-from-parameter-while-using-spring-data-jpa
___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 155 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI472Z9iZWD5F43jMA:-MdKPRw15y8BwmqbM6DE:b-896fix) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L155)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> .apply("Marshal " + clazz.getSimpleName() + " into DepositFragment", mapToFragments(clazz));
> ```
mapToFragments could be a high-fanout function. Consider adding a Reshuffle stage after this:

https://cloud.google.com/dataflow/docs/guides/deploying-a-pipeline#preventing-fusion
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/rde/PendingDeposit.java, line 98 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI1h1fCvn6FIe8ooFf:-MdKhuph0lweBl_xJCU7:b-896fix) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/rde/PendingDeposit.java#L98)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Missing Javadoc.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/rde/RdeFragmenter.java, line 36 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI1qCg1_2mMnEBqPcO:-MdKjMxW0mG92FCpM86_:b-5hdp4g) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/rde/RdeFragmenter.java#L36)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Does thread synchronization matter here?  https://crunchify.com/hashmap-vs-concurrenthashmap-vs-synchronizedmap-how-a-hashmap-can-be-synchronized-in-java/

Also why aren't you using Guava's `LoadingCache`, like we do throughout our codebase?

(Is this just for memoization?)
</blockquote></details>

I don't think synchronization matters here as we create a new `RdeFragmenter` for each resource, which is only accessed by a single thread.

This is also pre-existing code moved from the mapper to its own class. It does not look like `LoadingCache` is a good fit here because when a non-domain resource is marshalled to XML we proactively put them the in cache for more keys that needed. i. e. the key is (watermark, mode), but every time we marshall a resource we always put them as value for both (watermark, FULL) and (watermark, THIN), regardless of what `mode` actually is.
___
*[core/src/main/java/google/registry/rde/RdeFragmenter.java, line 91 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI2gTOEoqK65t_a1I8:-MdKjE5Q6hpJOa8gUYFU:b-896fix) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/rde/RdeFragmenter.java#L91)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Not a useful error message (admittedly this is pre-existing, but we might as well fix it now).
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/flows/EppPointInTimeTest.java, line 162 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI2j-KDEL58XUotCTj:-MdKPrw07oJ3tT3rIDbb:b4pont5) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/test/java/google/registry/flows/EppPointInTimeTest.java#L162)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Wait, why is the update timestamp getting updated? That shouldn't be happening AFAIK 
</blockquote></details>

It is not getting updated. There is no way to set `updateTimestamp` programmatically, it is automatically set when the entity is persisted into the database. So this field in the copy is null. Given that the copy is only used in RDE and `updateTimestamp` is an implementation detail that is not exposed to RDE, I think it is fine to leave it null. Unless you have reasons to believe it'll cause a problem?
___
*[core/src/test/java/google/registry/testing/DatastoreEntityExtension.java, line 54 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI1B365X71BbP3wNH7:-MdKQtus5JSfHZR-LWPH:b-896fix) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/test/java/google/registry/testing/DatastoreEntityExtension.java#L54)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

very nitty: spawn -> spawned (and same in the next paragraph) 
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/testing/DatastoreEntityExtension.java, line 59 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI1RCQ8AaJ6wRe9LfQ:-MdKQuWhCfDd7XcsJ8B_:b-eiv0rp) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/test/java/google/registry/testing/DatastoreEntityExtension.java#L59)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

1. "test" is duplicated 
2. I'm not sure "masqueraded" is the right term here or at least it might require a bit more information, are you in essence saying that every thread spawned by this thread will pretend to be this thread? 
</blockquote></details>

What I meant was that every thread created by the current JVM will have the same thread local value set to the placeholder value, which might be a problem when you use the AppEngineExtension in other threads, which sets up a more complicated environment to mimic the behavior of GAE.

Updated the comment for clarity.
___
*[core/src/main/java/google/registry/model/contact/ContactBase.java, line 294 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI0RJ62CYHr3fsAyI-:-MdKef-K6vqUohxkUzBU:b-yk8g1) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/model/contact/ContactBase.java#L294)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I agree that this seems fragile, and we should put this in a builder (similar to how we already use copyFrom in HistoryEntry::builder 
</blockquote></details>

Moved the code to `ContactResource.Builder.copyFrom()`. I don't think there is a good way to downcast a parent class to a child class in general even though they have exactly the same fields. If you guys can come up with something, I'm all ears.

There are added tests (see `ContactResourceTest.testContactBasetoContactResource()`), but it all depends on if the test resource is constructed with all the fields.
___
*[core/src/main/java/google/registry/model/contact/ContactBase.java, line 294 at r2](https://reviewable.io/reviews/google/nomulus/1219#-MdI01si6DTb8bUr68m9:-MdKf_me6cWFPmNrYVsP:b-tjw9j6) ([raw file](https://github.com/google/nomulus/blob/27b0f73c04d11f6436955ee72c0c66bd26a65dc9/core/src/main/java/google/registry/model/contact/ContactBase.java#L294)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

A Javadoc explaining what this is, why it's necessary, what it's used for, etc., would be helpful.
</blockquote></details>

It's a moot point now.
___
*[core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java, line 68 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md3jfkA8MZpEICNgWat:-MdKfhhS3O8q-6I7Q6Xb:bx6c8qq) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java#L68)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

If we don't use this, we should remove it from the PR as unnecessary code.
</blockquote></details>

Created #1225 for this. FWIW it was added because originally the plan was to load the entities from SQL using `CriteriaQueryBuilder` but it involves serializing the entities to pass between stages. So it was changed to use JPQL instead and this addition went unused.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 8 of 27 files reviewed, 12 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @jianglai)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md5A_bZ88JA98IlqIr1:-MdMz6PC9jWoU1zSx86z:bvbytw4) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L135)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

@weiminyu loading snapshots only happens for epp resources, not registrars. Since we don't current load registrars at the time of the watermark anyway I don't think it is a big issue. Of course we are talking about internal inconsistency vs general stale data, so maybe we should ask Crystal for clarification?

Regarding using EntityProto as coder (as suggested in the email thread), that class is from the datastore SDK so we will have to fork that code (or live with a dependency on the SDK).
</blockquote></details>

I mentioned EntityProto in the email specifically for the Datastore-sourced interim solution. I don't mean to use it for the long term either. But I expect that a serializer would be needed sometime in the future for other use cases anyway, and we can change it here if the performance impact is not trivial.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 8 of 27 files reviewed, 12 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[core/src/main/java/google/registry/beam/rde/RdePipeline.java, line 135 at r1](https://reviewable.io/reviews/google/nomulus/1219#-Md5A_bZ88JA98IlqIr1:-MdN4W1tCuC5eizW_Gcs:b52klib) ([raw file](https://github.com/google/nomulus/blob/bffec2f867ea8ad40dfa6a282ffd7ae187f9af49/core/src/main/java/google/registry/beam/rde/RdePipeline.java#L135)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

I mentioned EntityProto in the email specifically for the Datastore-sourced interim solution. I don't mean to use it for the long term either. But I expect that a serializer would be needed sometime in the future for other use cases anyway, and we can change it here if the performance impact is not trivial.
</blockquote></details>

I'll leave a TODO.

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 8 of 27 files reviewed, 11 unresolved discussions (waiting on @CydeWeys and @gbrodman)

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219)* status: 8 of 27 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

**Review by gbrodman — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1219#-:-MdSGycB51oXGjThNlMt:bnfp4nl)* status: 8 of 27 files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
