### PR TITLE
Compare datastore to sql action

### PR DESCRIPTION
**Pull request by weiminyu**
Ready for review.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1507)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1507)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java, line 143 at r1](https://reviewable.io/reviews/google/nomulus/1507#-Muw7Co0D7ymNWGxWPdV:-Muw7Co13Iu6c3KC_QGD:bbfrpbw) ([raw file](https://github.com/google/nomulus/blob/322b83ba8ba830d68309417edb85a4d36edda01a/core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java#L143)):*
> ```Java
>     // Trigger an async CommitLog export, and wait until the checkpoint is exported to GCS.
>     // Although we can add support to synchronous execution, it can disrupt the export cadence
>     // when the system is busy
> ```

Just so you're aware - I've seen a recent case where GCS propagation took a _very long time_ (~40 minutes).  In this state, files can be visible or not depending on the observer.
___
*[core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1507#-Muw8CNg4284AF8PIK-o:-Muw8CNg4284AF8PIK-p:b-87v3p9) ([raw file](https://github.com/google/nomulus/blob/322b83ba8ba830d68309417edb85a4d36edda01a/core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java#L149)):*
> ```Java
>     if (!checkpoint.isPresent()) {
>       commitLogCheckpointAction.createCheckPointAndStartAsyncExport();
>     }
> ```

I'm a bit confused -- is two retries magical somehow?  Would a Retrier be more appropriate?

Also, it doesn't look like this waits for it, as the comment indicates, right?  It just starts the async export and enqueues a task.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1507)* status: 8 of 15 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java, line 149 at r1](https://reviewable.io/reviews/google/nomulus/1507#-Muw8CNg4284AF8PIK-o:-MvUVcbhDkzGMIdX0pH5:b8vwgrq) ([raw file](https://github.com/google/nomulus/blob/322b83ba8ba830d68309417edb85a4d36edda01a/core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java#L149)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I'm a bit confused -- is two retries magical somehow?  Would a Retrier be more appropriate?

Also, it doesn't look like this waits for it, as the comment indicates, right?  It just starts the async export and enqueues a task.
</blockquote></details>

Explained inline.

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1507)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)

___
*[core/src/main/java/google/registry/tools/ValidateDatastoreWithSqlCommand.java, line 154 at r2](https://reviewable.io/reviews/google/nomulus/1507#-MvUdQB1Ankmdr7lQEwS:-MvUdQB1Ankmdr7lQEwT:b-ahq2fq) ([raw file](https://github.com/google/nomulus/blob/12eb24d3ea332f72762f16f2ea4c7b692c2e2dfd/core/src/main/java/google/registry/tools/ValidateDatastoreWithSqlCommand.java#L154)):*
> ```Java
>           while (DATAFLOW_JOB_RUNNING_STATES.contains(getDataflowJobStatus(jobId))) {
>             sleeper.sleepInterruptibly(JOB_POLLING_INTERVAL);
>           }
> ```

Can you add an option to not wait?  It would be useful for controlling scripts (not sure that we're ever likely to do that, but it's likely easier to address here than at the point where we want it).

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1507)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/tools/ValidateDatastoreWithSqlCommand.java, line 154 at r2](https://reviewable.io/reviews/google/nomulus/1507#-MvUdQB1Ankmdr7lQEwS:-MvVAlgDDEZahg5uQLVv:b-h1eqtx) ([raw file](https://github.com/google/nomulus/blob/12eb24d3ea332f72762f16f2ea4c7b692c2e2dfd/core/src/main/java/google/registry/tools/ValidateDatastoreWithSqlCommand.java#L154)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can you add an option to not wait?  It would be useful for controlling scripts (not sure that we're ever likely to do that, but it's likely easier to address here than at the point where we want it).
</blockquote></details>

Waiting is required to maintain the snapshot until another reader has started using it. BEAM API doesn't give us enough information to know which stages have completed. Unless this command the BEAM pipeline communicate using the database or pub/sub, the safest way is to wait until the pipeline completes.

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1507)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/tools/ValidateDatastoreWithSqlCommand.java, line 154 at r2](https://reviewable.io/reviews/google/nomulus/1507#-MvUdQB1Ankmdr7lQEwS:-MvYplcpCNnaoB7J0h4V:bdsf1sw) ([raw file](https://github.com/google/nomulus/blob/12eb24d3ea332f72762f16f2ea4c7b692c2e2dfd/core/src/main/java/google/registry/tools/ValidateDatastoreWithSqlCommand.java#L154)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Waiting is required to maintain the snapshot until another reader has started using it. BEAM API doesn't give us enough information to know which stages have completed. Unless this command the BEAM pipeline communicate using the database or pub/sub, the safest way is to wait until the pipeline completes.
</blockquote></details>

Ah, I see.  Thanks for the explanation.

**Pull request merged**
