### PR TITLE
Remove DatabaseSnapshot

### PR DESCRIPTION
**Pull request by jianglai**
It is no longer being used.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2105)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2105)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 99 at r1](https://reviewable.io/reviews/google/nomulus/2105#-Nbuobi9ADbBEp97m1Gi:-Nbuobi9ADbBEp97m1Gj:b-jkocl0) ([raw file](https://github.com/google/nomulus/blob/ee7c8fb0180dc35a4ee45d8ff06bb569e6cbc65a/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L99)):*
> ```Java
>   public EntityManager getStandaloneEntityManager() {
>     return emf.createEntityManager();
>   }
> ```

Let's keep this method, maybe as a test helper.  It provides an easy way to trigger various exceptions from Hibernate/psql.

I'm going to use this in an upcoming PR. 



_Code quote:_
```Java
  public EntityManager getStandaloneEntityManager() {
    return emf.createEntityManager();
  }
```

**Review by jianglai — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2105)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 99 at r1](https://reviewable.io/reviews/google/nomulus/2105#-Nbuobi9ADbBEp97m1Gi:-NbusLgZDT7yyLH6xpYB:b-896fix) ([raw file](https://github.com/google/nomulus/blob/ee7c8fb0180dc35a4ee45d8ff06bb569e6cbc65a/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L99)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Let's keep this method, maybe as a test helper.  It provides an easy way to trigger various exceptions from Hibernate/psql.

I'm going to use this in an upcoming PR.
</blockquote></details>

Done.

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Comment by jianglai** [comment]
OK I think I know why the presubmit tests keeps failing:

https://source.cloud.google.com/results/invocations/cc2db8f8-955e-4b55-bcb1-8f7c672d5664/log

It's failing at:

```
+ ./integration/run_compatibility_tests.sh -p domain-registry-dev -s sql
```

Based on the description [here], its running the deployed test suite (which does not contain the fix in #2107) against the schema in this PR. We need to deploy a new version first.

What's more interesting is how the bug that #2107 fixed slipped in in the first place. It should have been blocked by presubmit tests. It looks like something on kokoro changed silently which made this test start to fail.

**Pull request merged**
