### PR TITLE
Make RefreshDnsForAllDomains SQL-aware

### PR DESCRIPTION
**Pull request by jianglai**
Also marks a few mapreduce actions as @Deprecated as they are no longer
needed in SQL.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1197)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[core/src/main/java/google/registry/batch/ResaveAllEppResourcesAction.java, line 57 at r1](https://reviewable.io/reviews/google/nomulus/1197#-Mbf_-jaAmHDtk9sfkOo:-Mbf_-jaAmHDtk9sfkOp:bxxjr51) ([raw file](https://github.com/google/nomulus/blob/6db46b892c89558cf4b65830fc1bc48598431da3/core/src/main/java/google/registry/batch/ResaveAllEppResourcesAction.java#L57)):*
> ```Java
>     path = "/_dr/task/resaveAllEppResources",
>     auth = Auth.AUTH_INTERNAL_OR_ADMIN)
> @Deprecated
> ```

I'm not sure at-Deprecated has the right semantics for this case as that implies "don't use this" rather then "no longer needed."  Can you maybe add a comment to these indicating that these are unnecessary for SQL?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/batch/ResaveAllEppResourcesAction.java, line 57 at r1](https://reviewable.io/reviews/google/nomulus/1197#-Mbf_-jaAmHDtk9sfkOo:-Mbg2QSsDGLLbuaA8tSw:b-svoygo) ([raw file](https://github.com/google/nomulus/blob/6db46b892c89558cf4b65830fc1bc48598431da3/core/src/main/java/google/registry/batch/ResaveAllEppResourcesAction.java#L57)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I'm not sure at-Deprecated has the right semantics for this case as that implies "don't use this" rather then "no longer needed."  Can you maybe add a comment to these indicating that these are unnecessary for SQL? 
</blockquote></details>

If we were using Java 11 we could have added `forRemoval = true` to `@Deprecated`.

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @jianglai, and @mindhog)

___
*[core/src/main/java/google/registry/backup/DeleteOldCommitLogsAction.java, line 69 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbghGI11hwVkCg7Riti:-MbghGI11hwVkCg7Ritj:b-ocermg) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/backup/DeleteOldCommitLogsAction.java#L69)):*
> ```Java
>     path = "/_dr/task/deleteOldCommitLogs",
>     auth = Auth.AUTH_INTERNAL_OR_ADMIN)
> // No longer needed in SQL. Subject to future removal.
> ```

Can you add this comment to the other "deprecated" classes, too?

**Review by mindhog — APPROVED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: all files reviewed, 4 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 103 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbgkHA84-c-y1eESZ6V:-MbgkHA84-c-y1eESZ6W:bg6sjo) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L103)):*
> ```Java
>       tm().transact(
>               () ->
>                   jpaTm()
> ```

Extract the contents of the transaction to a separate helper function.
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 108 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbgkPyhD7IABhJMqHpG:-MbgkPyhD7IABhJMqHpH:b-yok3zr) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L108)):*
> ```Java
>                               + "WHERE tld IN (:tlds) "
>                               + "AND deletionTime > :now "
>                               + "AND creationTime <= :now",
> ```

Why is this necessary?  It's not possible for domains to be have been created in the future.  There's no such thing as a pending domain create.
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 128 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbgkdXe9ka21t5V0h2I:-MbgkdXe9ka21t5V0h2J:bukohin) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L128)):*
> ```Java
>                               response.setPayload(message);
>                               response.setStatus(HttpStatus.SC_INTERNAL_SERVER_ERROR);
>                               throw t;
> ```

The "log and rethrow" pattern is a code smell.
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 128 at r2](https://reviewable.io/reviews/google/nomulus/1197#-Mbgkta0EKTyToodCTRb:-Mbgkta0EKTyToodCTRc:bvk4tw6) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L128)):*
> ```Java
>                               response.setPayload(message);
>                               response.setStatus(HttpStatus.SC_INTERNAL_SERVER_ERROR);
>                               throw t;
> ```

Is this really the correct thing to do?  If a single domain's DNS fails to refresh (out of potentially millions), then we terminate and give up?

Note that the mapreduce does NOT terminate on a single failure.  It counts and logs failures but does not terminate the entire task.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/backup/DeleteOldCommitLogsAction.java, line 69 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbghGI11hwVkCg7Riti:-MbhOs7_8dWfWKx684ML:b-vpntku) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/backup/DeleteOldCommitLogsAction.java#L69)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can you add this comment to the other "deprecated" classes, too?
</blockquote></details>

I thought I already did?
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 103 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbgkHA84-c-y1eESZ6V:-Mbi7Tuw4lPllCDMLdFx:b-xnls4n) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L103)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Extract the contents of the transaction to a separate helper function.
</blockquote></details>

As I said in the other PR, there seems to be limited benefit in doing this. Once the migration is done the run method will just call a helper function, which is only called by the run method, and located somewhere else in the file. Is there a particular reason that you'd prefer this way?
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 108 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbgkPyhD7IABhJMqHpG:-Mbi7tHl1NDgT72ZzOhO:b9vfjrb) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L108)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why is this necessary?  It's not possible for domains to be have been created in the future.  There's no such thing as a pending domain create.
</blockquote></details>

I wondered about this as well. The old mapreduce does this by calling `isActive(domain, now)`. Maybe it's leaving the possibility to run the action at a certain time? But again the time is not injected so it's not possible to provide it. Interestingly we don't always do this: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/EppResourceUtils.java;l=70?q=getlinked&ss=nomulus%2Fnomulus

I guess this can be removed to optimize SQL performance.
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 128 at r2](https://reviewable.io/reviews/google/nomulus/1197#-Mbgkta0EKTyToodCTRb:-Mbi8wPV7wCXeAJfuZ26:b-c3tnjw) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L128)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is this really the correct thing to do?  If a single domain's DNS fails to refresh (out of potentially millions), then we terminate and give up?

Note that the mapreduce does NOT terminate on a single failure.  It counts and logs failures but does not terminate the entire task.
</blockquote></details>

Good point. 
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 128 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbgkdXe9ka21t5V0h2I:-MbiACU82vPNZw-mCj0i:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L128)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The "log and rethrow" pattern is a code smell.
</blockquote></details>

Done.

**Review by mindhog — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: all files reviewed, 5 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 103 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbgkHA84-c-y1eESZ6V:-MblJFPV6dRIExYlPA7A:b-jwocjv) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L103)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

As I said in the other PR, there seems to be limited benefit in doing this. Once the migration is done the run method will just call a helper function, which is only called by the run method, and located somewhere else in the file. Is there a particular reason that you'd prefer this way?
</blockquote></details>

It's marginal here, but the other PR has a function that's even longer and more indented.
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 108 at r2](https://reviewable.io/reviews/google/nomulus/1197#-MbgkPyhD7IABhJMqHpG:-MblJWJX85Cc37XlwoVG:b65he8o) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L108)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I wondered about this as well. The old mapreduce does this by calling `isActive(domain, now)`. Maybe it's leaving the possibility to run the action at a certain time? But again the time is not injected so it's not possible to provide it. Interestingly we don't always do this: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/EppResourceUtils.java;l=70?q=getlinked&ss=nomulus%2Fnomulus

I guess this can be removed to optimize SQL performance.
</blockquote></details>

I can see some actions that require running at a specific point in the past for which you'd want to exclude more recently created domains (RDE is the most obvious use case), but that's not relevant here.  Refreshing DNS for all domains is idempotent and that action should generally be a noop anyway unless DNS is out of date.  It also doesn't make sense to run a refresh at some point in the past.
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 128 at r2](https://reviewable.io/reviews/google/nomulus/1197#-Mbgkta0EKTyToodCTRb:-MblK55IDrzg1juxHuem:b7v2f36) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L128)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Good point. 
</blockquote></details>

Can you add a test below where, say, refreshing DNS fails on just 1 of 3, and verify that it still succeeds on the other 2?
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 119 at r3](https://reviewable.io/reviews/google/nomulus/1197#-MblKaiO53TsRq7s-gJt:-MblKaiO53TsRq7s-gJu:bxldyv8) ([raw file](https://github.com/google/nomulus/blob/db9b74b663a79607e751ef15aec91d2a14c5b6b5/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L119)):*
> ```Java
>                                   domainName,
>                                   Duration.standardMinutes(random.nextInt(smearMinutes)));
>                               logger.atInfo().log("active domain %s refreshed.", domainName);
> ```

This is gonna be way too noisy.  We don't need a million plus domain names in our logs if we run this action.  Note that logging is not analogous to incrementing a mapreduce counter (what happens on success in the other mapreduce).
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 122 at r3](https://reviewable.io/reviews/google/nomulus/1197#-MblL75w-DMM8H39cd_P:-MblL75w-DMM8H39cd_Q:b-aj5onr) ([raw file](https://github.com/google/nomulus/blob/db9b74b663a79607e751ef15aec91d2a14c5b6b5/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L122)):*
> ```Java
>                             } catch (Throwable t) {
>                               logger.atSevere().withCause(t).log(
>                                   "Error while refreshing DNS for domain %s", domainName);
> ```

A more accurate error message is probably "Error while enqueuing DNS refresh of domain %s."  Remember that this action isn't actually doing the refreshing, it's just adding the DNS task queue pull entries so that the next time `ReadDnsQueueAction` runs, it does the refreshing.  That could independently still fail even if this succeeds.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 128 at r2](https://reviewable.io/reviews/google/nomulus/1197#-Mbgkta0EKTyToodCTRb:-MbnbJhB3kNbwFjSyTl6:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c175dcf3b014e27d39e629694a7c9c1eb0c1584f/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L128)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Can you add a test below where, say, refreshing DNS fails on just 1 of 3, and verify that it still succeeds on the other 2?
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 119 at r3](https://reviewable.io/reviews/google/nomulus/1197#-MblKaiO53TsRq7s-gJt:-MbnbLkW1izWxKdL2LOC:b-896fix) ([raw file](https://github.com/google/nomulus/blob/db9b74b663a79607e751ef15aec91d2a14c5b6b5/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L119)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is gonna be way too noisy.  We don't need a million plus domain names in our logs if we run this action.  Note that logging is not analogous to incrementing a mapreduce counter (what happens on success in the other mapreduce).
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java, line 122 at r3](https://reviewable.io/reviews/google/nomulus/1197#-MblL75w-DMM8H39cd_P:-MbnU-2KEWUX2Of2NYRs:b-896fix) ([raw file](https://github.com/google/nomulus/blob/db9b74b663a79607e751ef15aec91d2a14c5b6b5/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L122)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

A more accurate error message is probably "Error while enqueuing DNS refresh of domain %s."  Remember that this action isn't actually doing the refreshing, it's just adding the DNS task queue pull entries so that the next time `ReadDnsQueueAction` runs, it does the refreshing.  That could independently still fail even if this succeeds.
</blockquote></details>

Done.

**Review by mindhog — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1197)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

**Pull request merged**
