### PR TITLE
Add console user update and minor fixes to delete 

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2610)

### CODE REVIEW

**Review by gbrodman — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2610)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2610)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 272 at r2](https://reviewable.io/reviews/google/nomulus/2610#-OBl0UhK8FweF24QpxHz:-OBl0UhK8FweF24QpxI-:bbfgj17) ([raw file](https://github.com/google/nomulus/blob/8f7e666eb4bf236313fa5daf504641fafbf543ba/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L272)):*
> ```Java
> 
>   public record UserData(
>       @Expose String emailAddress, @Expose String role, @Expose @Nullable String password) {}
> ```

I think this probably doesn't quite match the paradigm that we want of multi-accreditation, AKA "one login can have permissions to multiple registrar objects, with potentially different roles on each of them". Thoughts?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2610)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 272 at r2](https://reviewable.io/reviews/google/nomulus/2610#-OBl0UhK8FweF24QpxHz:-OBl1ruG1jgcDPnXxfuK:b-f0jhtm) ([raw file](https://github.com/google/nomulus/blob/8f7e666eb4bf236313fa5daf504641fafbf543ba/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L272)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think this probably doesn't quite match the paradigm that we want of multi-accreditation, AKA "one login can have permissions to multiple registrar objects, with potentially different roles on each of them". Thoughts?
</blockquote></details>

What I have doesn't prevent multi-accreditation. I will add it on top of what I have as a part of future update

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2610)* status: 10 of 12 files reviewed, all discussions resolved

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 272 at r2](https://reviewable.io/reviews/google/nomulus/2610#-OBl0UhK8FweF24QpxHz:-OBl55vZBPW9IXz6devW:be2hh83) ([raw file](https://github.com/google/nomulus/blob/8f7e666eb4bf236313fa5daf504641fafbf543ba/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L272)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

What I have doesn't prevent multi-accreditation. I will add it on top of what I have as a part of future update
</blockquote></details>

synced up offline-- we'll follow up on this later

**Pull request merged**
