### PR TITLE
Migrate DNS query table

### PR DESCRIPTION
**Pull request by gbrodman**
This is a direct copy of Lai's PR #2483. His comments:

Currently, Cloud DNS activity data is saved in an internal Plx table and we query it via BQ-plx bridge. The bridge is being deprecated and we are asked to use BQ-TS federation instead.

Per b/322853331, I've created a BQ table in the same project that Nomulus runs, which exposes the same data in the Plx table. This means that we can query this table directly without going through the bridge, and open source the code as a result.

There is a corresponding change in Git-on-Borg to update the config file and remove the Java code that performs the query via BQ-plx bridge:

https://team-review.git.corp.google.com/c/domain-registry-eng/nomulus-internal/+/2312377

My comments (Gus): I've tested this on alpha using the new systems that they want for us to have in place and it works properly. When this is merged and deployed we can do a test run to verify that it generates reports properly, with sufficient time until next month's run on October 2 to fix any issues.

This and the internal PR will both fail checks because they are mutually dependent, unfortunately.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2543)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2543)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/reporting/icann/CloudDnsCountQueryCoordinator.java` line 26 at r1](https://reviewable.io/reviews/google/nomulus/2543#-O5xvuzN3DAkt4HOqXAi:-O5xvuzN3DAkt4HOqXAj:bipk1oz) ([raw file](https://github.com/google/nomulus/blob/754627e61780aed0b686309ca36f3c5d7d7df7f1/core/src/main/java/google/registry/reporting/icann/CloudDnsCountQueryCoordinator.java#L26)):*
> ```Java
> 
> /**
>  * DNS Count query that relies on a table Cloud DNS publishes internally.
> ```

So this just won't work at all for open source Nomulus users?  What are they supposed to do?

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2543)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/reporting/icann/CloudDnsCountQueryCoordinator.java` line 26 at r1](https://reviewable.io/reviews/google/nomulus/2543#-O5xvuzN3DAkt4HOqXAi:-O5y5GWGB3qYIUVFeRyL:bg1kpfo) ([raw file](https://github.com/google/nomulus/blob/754627e61780aed0b686309ca36f3c5d7d7df7f1/core/src/main/java/google/registry/reporting/icann/CloudDnsCountQueryCoordinator.java#L26)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

The same thing they did before, where they'd have to implement something and configure its usage in the config files
</blockquote></details>


That's what I expected -- can we just explicitly say that here, then?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2543)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/reporting/icann/CloudDnsCountQueryCoordinator.java` line 26 at r1](https://reviewable.io/reviews/google/nomulus/2543#-O5xvuzN3DAkt4HOqXAi:-O5y6_gUB84mROE_yyoW:b-896fix) ([raw file](https://github.com/google/nomulus/blob/754627e61780aed0b686309ca36f3c5d7d7df7f1/core/src/main/java/google/registry/reporting/icann/CloudDnsCountQueryCoordinator.java#L26)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

That's what I expected -- can we just explicitly say that here, then?
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2543#-:-O5y6yFB6auuxMb7fcPl:bnfp4nl)* status: 0 of 30 files reviewed, all discussions resolved

**Pull request merged**
