### PR TITLE
Add a daily batch action to upload unavailable domains to BSA

### PR DESCRIPTION
**Pull request by CydeWeys**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2265)

### CODE REVIEW

**Review by CydeWeys — COMMENTED** [review]
+reviewer:@weiminyu Please have a preliminary review.  I'm going to start testing in alpha soon.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2265#-:-NnQ2fTDCZHSAvCYiMk5:b-tcpif1)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @weiminyu)

**Review by CydeWeys — COMMENTED** [review]
(Will write tests later 😬)

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2265#-:-NnQ2l0O9nFV6KVegibQ:bdxb5n)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @weiminyu)

**Review by weiminyu — APPROVED** [review]
> Reviewed 19 of 22 files at r2, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2265)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2265)* status: 24 of 26 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomains.java` line 74 at r6](https://reviewable.io/reviews/google/nomulus/2265#-NneoSEx4DuaROqB4rlT:-NneoSEx4DuaROqB4rlU:b3cxa31) ([raw file](https://github.com/google/nomulus/blob/35978c86e6cb02d26ed61e264300da6832973e54/core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomains.java#L74)):*
> ```Java
>     method = POST,
>     auth = Auth.AUTH_API_ADMIN)
> public class UploadBsaUnavailableDomains implements Runnable {
> ```

Similar classes all have `Action` as class name suffix.



_Code quote:_
```Java
UploadBsaUnavailableDomains
```

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2265)* status: 3 of 26 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomains.java` line 74 at r6](https://reviewable.io/reviews/google/nomulus/2265#-NneoSEx4DuaROqB4rlT:-NnjS8afBbkzxwaJMYo3:b-896fix) ([raw file](https://github.com/google/nomulus/blob/35978c86e6cb02d26ed61e264300da6832973e54/core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomains.java#L74)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Similar classes all have `Action` as class name suffix.
</blockquote></details>

Done.

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2265)* status: 3 of 26 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

**Pull request merged**
