### PR TITLE
Add more logging in the event of replay put/delete failure

### PR DESCRIPTION
**Pull request by gbrodman**
Getting errors that are difficult to debug without this data, see https://pantheon.corp.google.com/logs/viewer?project=domain-registry-sandbox&minLogLevel=0&expandAll=false&timestamp=2021-07-30T15:07:25.910000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2021-07-30T14:07:34.689Z&interval=PT1H&resource=gae_app%2Fmodule_id%2Fbackend&logName=projects%2Fdomain-registry-sandbox%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2021-07-30T15:06:45.868879000Z&filters=text:replayCommitLogsToSql&advancedFilter=replayCommitLogsToSql&dateRangeEnd=2021-07-30T15:07:34.689Z

Something is causing a delete of that delegation signer data during a standard "put" operation and it's failing because that dsdata is cascadingly assigned to the non-deleted domain (in Datastore and in SQL, the dsData is still there and attached)

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1262)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1262)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 253 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsjYf17R7YuvkG1EES:-MfsjYf17R7YuvkG1EET:b-nlnk1m) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L253)):*
> ```Java
>       }
>     } catch (Throwable t) {
>       logger.atSevere().log("Error when replaying object %s", ofyPojo);
> ```

Missing a `.withCause()`.
___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 278 at r1](https://reviewable.io/reviews/google/nomulus/1262#-Mfsjjjz2O6txb2RPcRU:-Mfsjjjz2O6txb2RPcRV:b-jove50) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L278)):*
> ```Java
>         ReplaySpecializer.beforeSqlDelete(entityVKey);
>         jpaTm().delete(entityVKey);
>       }
> ```

Do you want to log an `else` case here too just in case, like above?
___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 280 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsjgSn4HPbjy0qT_OX:-MfsjgSn4HPbjy0qT_OY:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L280)):*
> ```Java
>       }
>     } catch (Throwable t) {
>       logger.atSevere().log("Error when deleting key %s", entityVKey);
> ```

Ditto.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1262)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 253 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsjYf17R7YuvkG1EES:-MfskWq1DInQEcDv0SzI:b3c2cw2) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L253)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Missing a `.withCause()`.
</blockquote></details>

No, since we're throwing. 
___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 278 at r1](https://reviewable.io/reviews/google/nomulus/1262#-Mfsjjjz2O6txb2RPcRU:-MfskdqxEARqgelMDIif:b-ti1p1x) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L278)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Do you want to log an `else` case here too just in case, like above?
</blockquote></details>

nah, there are going to be a lot of entities that aren't replayed, it'd just be noisy 
___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 280 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsjgSn4HPbjy0qT_OX:-Mfsk_uS-uayqMNIwV75:b3c2cw2) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L280)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

No, since we're throwing.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1262)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 253 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsjYf17R7YuvkG1EES:-Mfslu7i2fS19CEkVyEK:b-e1y0eo) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L253)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

No, since we're throwing. 
</blockquote></details>

Yeah, but then you're not logging the error alongside this message.  So you say "Error when replaying object _____" but then don't actually say what the error is.  It's gonna be somewhere else in the error output.

Might be better just to not re-throw and have this method return a success boolean, and bail out at the callsite if it's false.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1262)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 253 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsjYf17R7YuvkG1EES:-MfsmOGnEVXnKWr-mqbP:b-h5tqch) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L253)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yeah, but then you're not logging the error alongside this message.  So you say "Error when replaying object _____" but then don't actually say what the error is.  It's gonna be somewhere else in the error output.

Might be better just to not re-throw and have this method return a success boolean, and bail out at the callsite if it's false.
</blockquote></details>

I mean it'd be logged on the next line as the exception gets handled, which is right next to this one.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1262)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 216 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsmcfT1-w6LcEKekCX:-MfsmcfT1-w6LcEKekCY:b-g6d3rl) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L216)):*
> ```Java
>           allTransactions.size(), metadata.getName(), metadata.getSize());
>     } catch (IOException e) {
>       throw new RuntimeException(
> ```

So long as we're looking at error handling, it's not clear to me why this checked-to-unchecked exception conversion is necessary, when you could just instead add some `throws` clauses and then have everything be more explicit.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1262)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 253 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsjYf17R7YuvkG1EES:-MfsngnH1s2KJKd-dhQV:bhuqynd) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L253)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I mean it'd be logged on the next line as the exception gets handled, which is right next to this one. 
</blockquote></details>

No, it wouldn't get logged on the next line, it'll be logged eventually wherever that exception actually ends up being handled.  But the mere fact that an exception is thrown at a given line does not immediately trigger logging.  It's gonna end up being logged here:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java;l=136?q=replaycommitlogs&ss=nomulus%2Fnomulus  (that's quite a few lines and layers of nested function calls away)

But anyway, per offline discussion, unblocking this so you can get to testing.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1262#-:-MfsoN9jCvmjorKfJvt-:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1262)* status: 0 of 1 files reviewed, 2 unresolved discussions

___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 216 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsmcfT1-w6LcEKekCX:-MfspCsa8W91NVSDq8au:b9278yp) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L216)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

So long as we're looking at error handling, it's not clear to me why this checked-to-unchecked exception conversion is necessary, when you could just instead add some `throws` clauses and then have everything be more explicit.
</blockquote></details>

This is inside of a transaction so we can't throw checked exceptions in it unfortunately. 
___
*[core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java, line 253 at r1](https://reviewable.io/reviews/google/nomulus/1262#-MfsjYf17R7YuvkG1EES:-MfspZqoD0S1sFxm5XTO:bg7012l) ([raw file](https://github.com/google/nomulus/blob/9f30a5f246f0329f08498db7957df446beceacfc/core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java#L253)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

No, it wouldn't get logged on the next line, it'll be logged eventually wherever that exception actually ends up being handled.  But the mere fact that an exception is thrown at a given line does not immediately trigger logging.  It's gonna end up being logged here:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/backup/ReplayCommitLogsToSqlAction.java;l=136?q=replaycommitlogs&ss=nomulus%2Fnomulus  (that's quite a few lines and layers of nested function calls away)

But anyway, per offline discussion, unblocking this so you can get to testing.
</blockquote></details>

fair, this should hopefully be short-lived anyway .

**Pull request merged**
