### PR TITLE
Close sidenav on click

### PR DESCRIPTION
**Pull request by gbrodman**
It shouldn't stick around after we've clicked on one of the links

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2156)

### CODE REVIEW

**Review by gbrodman — COMMENTED** [review]
I'm not sure what you mean -- closing a hamburger-menu-type sidebar when you click on a link in it is a super common paradigm across a ton of webpages that I've seen when it opens up a new page, especially when the sidebar pops out and covers up content on the new page. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2156#-:-NetNs56CdHcPyj6ryJV:b-becpij)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ptkach — COMMENTED** [review]
As shown offline, it's more about sequence of operations. I think you can add a router event subscription to listen to when navigation ends and only then trigger sidebar close - https://indepth.dev/posts/1028/angular-router-series-pillar-2-understanding-the-routers-navigation-cycle 
I believe that should at least provide a better UX. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2156#-:-NetV8V9AUKnjzuAD-bw:b-31i21h)* status: 0 of 1 files reviewed, all discussions resolved

**Review by gbrodman — COMMENTED** [review]
ok so this ends up being a bit more code than the other way, but now we just close the sidenav any time the router is done navigating somewhere. Thoughts? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2156#-:-NfCPL4d9jOTeug1jfLy:b-rlsoc1)* status: 0 of 2 files reviewed, all discussions resolved

**Review by ptkach — COMMENTED** [review]
that's correct, I anticipate it to to be just a few lines more code, however it should make transition more straightforward for the user. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2156#-:-NfCa8JaCSzb9bwIyOsB:bhccy0v)* status: 0 of 2 files reviewed, all discussions resolved

**Review by ptkach — APPROVED** [review]
You are correct. I wonder if there's an indicator somewhere which would clearly highlight the revision being reviewed

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2156#-:-NfCcWyX4hYazW5x2yNq:b5t751o)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`console-webapp/src/app/app.component.ts` line 48 at r2](https://reviewable.io/reviews/google/nomulus/2156#-NfCcN4DAStcSdEN9vfi:-NfCcN4DAStcSdEN9vfj:bo5cpot) ([raw file](https://github.com/google/nomulus/blob/a6e6587840688f4d149b474ea70d153207de9b38/console-webapp/src/app/app.component.ts#L48)):*
> ```XML
> 
>   ngAfterViewInit() {
>     this.router.events.subscribe((event) => {
> ```

Nice :)

**Pull request merged**
