### PR TITLE
Add discount price columns to AllocationToken table

### PR DESCRIPTION
**Pull request by jicelhay**
Schema update changes to prepare for b/358151081.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2547)

### CODE REVIEW

**Review by CydeWeys — COMMENTED** [review]
On the PR description, here's the style guide we use: https://cbea.ms/git-commit/

So the first line would be something like "Add allocation token discount price columns to database schema"

Crucially, all this PR does is update the DB schema, but nowhere in the current description does it ever mention anything about updating the DB schema.  And also feel free to link the bug you're working on.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2547#-:-O62ZK-0Cu24MU2NkBJY:b-xwxzaf)* status: 0 of 5 files reviewed, all discussions resolved

**Review by jicelhay — COMMENTED** [review]
Thanks for the link! I updated the tittle to provide  a concise explanation of the PR.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2547#-:-O62kn434-UTgvpfsKFT:bt3isvm)* status: 0 of 5 files reviewed, all discussions resolved

**Review by CydeWeys — COMMENTED** [review]
And worth point out that, from that link, we don't follow all the rules about line length.  Generally I just make sure my commit summary isn't too long for a GitHub commit (if it is it'll get an ellipsis and then the rest moved into the commit description).  I don't know exactly how many characters it takes to do that but it's more than 50 for sure.  And wrapping the commit description line length to 72 characters isn't particularly necessary either.

But the rest of it is good advice.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2547#-:-O62pyqP5qcBuziU_AVE:b-171bl2)* status: 0 of 5 files reviewed, all discussions resolved

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2547#-:-O62qJ0O03_AestZeAIf:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved

**Review by CydeWeys — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2547)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jicelhay)

**Pull request merged**
