### PR TITLE
Better configure DocumentBuilderFactory to help prevent XXE

### PR DESCRIPTION
**Pull request by CydeWeys**
For more information see: https://community.veracode.com/s/article/Java-Remediation-Guidance-for-XXE

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2132)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
Could you update the stax parser in XmlSanitizer too: https://github.com/google/nomulus/blob/ebf07833e55e421ac38a9cef26295e403b825602/core/src/main/java/google/registry/flows/EppXmlSanitizer.java#L162

The one in XmlTransformer can be used as a template: https://github.com/google/nomulus/blob/ebf07833e55e421ac38a9cef26295e403b825602/core/src/main/java/google/registry/xml/XmlTransformer.java#L111

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2132#-:-Nd1xCaf40BCavRRqIuZ:b-ckdey3)* status: 0 of 2 files reviewed, all discussions resolved

**Review by CydeWeys — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2132#-:-Nd22CIJAfMWhyDpGNFx:b-896fix)* status: 0 of 3 files reviewed, all discussions resolved

**Review by CydeWeys — COMMENTED** [review]
PTAL.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2132#-:-Nd22EoAC80vjiigNnNH:b-83330m)* status: 0 of 3 files reviewed, all discussions resolved

**Review by weiminyu — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
