### PR TITLE
Add Gmail Client and set up tests

### PR DESCRIPTION
**Pull request by weiminyu**
Add a Gmail client prototype. Also added manually triggered email tests in CannedScriptExecutionActon.

We will test Gmail with Google Workspace in Sandbox, since Alpha and Crash are not properly set up for Google Workspace, and we have not figured out why.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2048)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2048)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @jianglai and @weiminyu)

___
*[`core/src/main/java/google/registry/groups/GmailModule.java` line 28 at r1](https://reviewable.io/reviews/google/nomulus/2048#-NXMa23o9qfgHAFvPva_:-NXMa23o9qfgHAFvPvaa:bmc54gu) ([raw file](https://github.com/google/nomulus/blob/1b6ea20936778622b4609e9a9e20ac812717fbd8/core/src/main/java/google/registry/groups/GmailModule.java#L28)):*
> ```Java
> public class GmailModule {
> 
>   @Provides
> ```

Is there a reason we don't want it to be a singleton?

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2048)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

___
*[`core/src/main/java/google/registry/groups/GmailModule.java` line 28 at r1](https://reviewable.io/reviews/google/nomulus/2048#-NXMa23o9qfgHAFvPva_:-NXMaWO31WoGvmS0UXr9:b8go2vq) ([raw file](https://github.com/google/nomulus/blob/1b6ea20936778622b4609e9a9e20ac812717fbd8/core/src/main/java/google/registry/groups/GmailModule.java#L28)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Is there a reason we don't want it to be a singleton? 
</blockquote></details>

Good catch. Thanks.

**Review by ptkach — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2048)* status: all files reviewed, 4 unresolved discussions (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/batch/CannedScriptExecutionAction.java` line 101 at r2](https://reviewable.io/reviews/google/nomulus/2048#-NXQQJ241td39YrevoMz:-NXQQJ25-XthzqZHHm_W:b7zi2om) ([raw file](https://github.com/google/nomulus/blob/230178ed16e52d9fcc1e9bc2f79e68739cea8d5c/core/src/main/java/google/registry/batch/CannedScriptExecutionAction.java#L101)):*
> ```Java
>   }
> 
>   // Checks if Directory and GroupSettings still work after GWorkspace changes.
> ```

Can you explain a bit what changed that would have resulted in Directory and GroupSettings API call failures?



_Code quote:_
```Java
// Checks if Directory and GroupSettings still work after GWorkspace changes.
```
___
*[`core/src/main/java/google/registry/groups/GmailClient.java` line 59 at r2](https://reviewable.io/reviews/google/nomulus/2048#-NXQPhA666lEUBZmLkCA:-NXQPhA666lEUBZmLkCB:b-i65ia5) ([raw file](https://github.com/google/nomulus/blob/230178ed16e52d9fcc1e9bc2f79e68739cea8d5c/core/src/main/java/google/registry/groups/GmailClient.java#L59)):*
> ```Java
>   @CanIgnoreReturnValue
>   public Message sendEmail(EmailMessage emailMessage) {
>     Message message = toGmailMessage(toMimeMessage(emailMessage));
> ```

Is there a reason to have two chained calls? `toGmailMessage` can convert an `EmailMessage` directly in place, right?



_Code quote:_
```Java
toGmailMessage(toMimeMessage(emailMessage))
```
___
*[`core/src/main/java/google/registry/groups/GmailClient.java` line 61 at r2](https://reviewable.io/reviews/google/nomulus/2048#-NXQPBJN67dZTt0TjD5U:-NXQPBJN67dZTt0TjD5V:b-9gl1n2) ([raw file](https://github.com/google/nomulus/blob/230178ed16e52d9fcc1e9bc2f79e68739cea8d5c/core/src/main/java/google/registry/groups/GmailClient.java#L61)):*
> ```Java
>     Message message = toGmailMessage(toMimeMessage(emailMessage));
>     try {
>       return gmail.users().messages().send("me", message).execute();
> ```

What does "me" do here? Is it the name of the sender? It seems weird to send an email as "me"...



_Code quote:_
```Java
"me"
```
___
*[`core/src/main/java/google/registry/groups/GmailClient.java` line 84 at r2](https://reviewable.io/reviews/google/nomulus/2048#-NXQPQGL5H298pU-dwOY:-NXQPQGL5H298pU-dwOZ:b-fqsjnr) ([raw file](https://github.com/google/nomulus/blob/230178ed16e52d9fcc1e9bc2f79e68739cea8d5c/core/src/main/java/google/registry/groups/GmailClient.java#L84)):*
> ```Java
>     try {
>       MimeMessage msg =
>           new MimeMessage(Session.getDefaultInstance(new Properties(), /* authenticator= */ null));
> ```

Is this intentional?



_Code quote:_
```Java
/* authenticator= */
```

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2048)* status: all files reviewed, 4 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/batch/CannedScriptExecutionAction.java` line 101 at r2](https://reviewable.io/reviews/google/nomulus/2048#-NXQQJ241td39YrevoMz:-NXQoypt1SufeaiLQMob:b-x8kyj9) ([raw file](https://github.com/google/nomulus/blob/230178ed16e52d9fcc1e9bc2f79e68739cea8d5c/core/src/main/java/google/registry/batch/CannedScriptExecutionAction.java#L101)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Can you explain a bit what changed that would have resulted in Directory and GroupSettings API call failures?
</blockquote></details>

We'll add a scope. This is unlikely to cause problem but this gives the peace of mind.
___
*[`core/src/main/java/google/registry/groups/GmailClient.java` line 59 at r2](https://reviewable.io/reviews/google/nomulus/2048#-NXQPhA666lEUBZmLkCA:-NXQqJhP3SncHYoZOkht:b-xgib22) ([raw file](https://github.com/google/nomulus/blob/230178ed16e52d9fcc1e9bc2f79e68739cea8d5c/core/src/main/java/google/registry/groups/GmailClient.java#L59)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is there a reason to have two chained calls? `toGmailMessage` can convert an `EmailMessage` directly in place, right?
</blockquote></details>

It'll be easier to write tests.
___
*[`core/src/main/java/google/registry/groups/GmailClient.java` line 61 at r2](https://reviewable.io/reviews/google/nomulus/2048#-NXQPBJN67dZTt0TjD5U:-NXQpj6aC0AlpVP76yBK:b-git1qd) ([raw file](https://github.com/google/nomulus/blob/230178ed16e52d9fcc1e9bc2f79e68739cea8d5c/core/src/main/java/google/registry/groups/GmailClient.java#L61)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

What does "me" do here? Is it the name of the sender? It seems weird to send an email as "me"...
</blockquote></details>

"me" is the special value meaning the credential user, documented in the Gmail doc. We will explain more when this is productionized.
___
*[`core/src/main/java/google/registry/groups/GmailClient.java` line 84 at r2](https://reviewable.io/reviews/google/nomulus/2048#-NXQPQGL5H298pU-dwOY:-NXQq9FHA-1OtZVRaByb:b-4baium) ([raw file](https://github.com/google/nomulus/blob/230178ed16e52d9fcc1e9bc2f79e68739cea8d5c/core/src/main/java/google/registry/groups/GmailClient.java#L84)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is this intentional?
</blockquote></details>

Yes.  Style recommendation is to document raw values.
We don't always follow it but this is copy-paste code and it is already there.

**Review by jianglai — APPROVED** [review]

**Pull request merged**
