### PR TITLE
Convert more flow tests to replay/compare

### PR DESCRIPTION
**Pull request by mindhog**
Add the replay extension to another batch of flow tests.  In the course of
this:

- Refactor out domain deletion code into DatabaseHelper so that it can be used
  from multiple tests.
- Make null handling uniform for contact phone numbers.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1009)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1009)* status: all files reviewed, 2 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/contact/ContactBase.java, line 194 at r1](https://reviewable.io/reviews/google/nomulus/1009#-MVr2-gm5Uyz3lOeGHx5:-MVr2-gm5Uyz3lOeGHx6:b-sfqt3f) ([raw file](https://github.com/google/nomulus/blob/27e5dafa3d4b63597de82ec75d209f619b5638b8/core/src/main/java/google/registry/model/contact/ContactBase.java#L194)):*
> ```Java
> 
>   @OnLoad
>   void postLoad() {
> ```

nit: method name `onLoad` 
___
*[core/src/main/java/google/registry/model/contact/ContactBase.java, line 339 at r1](https://reviewable.io/reviews/google/nomulus/1009#-MVr26SHAgQFpFiFmko5:-MVr26SHAgQFpFiFmko6:by0ir74) ([raw file](https://github.com/google/nomulus/blob/27e5dafa3d4b63597de82ec75d209f619b5638b8/core/src/main/java/google/registry/model/contact/ContactBase.java#L339)):*
> ```Java
>     }
> 
>     public B setVoiceNumber(ContactPhoneNumber voiceNumber) {
> ```

Minor, but I think it might be better to follow the pattern that some of the other classes (e.g. PollMessage) follow here where there's a method called from `build` that fills out the objects as necessary, so that the logic of "fill out weird fields" is in as few places as possible

**Comment by mindhog** [comment]
Well, this sucks.  I'm not seeing your comments in reviewable :-(   Responding here:

[postLoad -> onLoad](https://reviewable.io/reviews/google/nomulus/1009#-MVr2-gm5Uyz3lOeGHx5:-MVr2-gm5Uyz3lOeGHx6:b-sfqt3f)

Done.  (Thanks for that, it started out as a PostLoad when I was still experimenting with it./

[setter vs build()](https://reviewable.io/reviews/google/nomulus/1009#-MVr26SHAgQFpFiFmko5:-MVr26SHAgQFpFiFmko6:by0ir74)

I see your point, but I disagree: the thing about a build() method is that you can do normalization in it by dealing with a field whether it has been populated or not.  The case for doing it in a setter is that it puts the weird in the place where it needs to be: at the gateway where a denormalized value is introduced.  It's already presumed to be normalized if it's in an existing object.  I've added something similar to DomainContent for several fields (nsHosts and gracePeriods) so there is precedent for this, as well.

It's worth noting that if objectify's loader used the Builder, we wouldn't need the OnLoad in either case :-)

**Review by gbrodman — APPROVED** [review]
Yeah, shame that there's no way of having only one method to instantiate the object. 

Fair enough. 

> Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1009#-:-MVs3MSH0Awq7Dvy1YaD:bwylphx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1009)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1009)* status: 10 of 17 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java, line 495 at r4](https://reviewable.io/reviews/google/nomulus/1009#-MW5FEq36iX_xj0wOolq:-MW5FEq4190x7ml_o1b0:bgx46h9) ([raw file](https://github.com/google/nomulus/blob/d9ce9e3ed5f5cae4da9773028f9f40c902c1ac1a/core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java#L495)):*
> ```Java
>     // Transfer should have been requested.
>     domain = reloadResourceByForeignKey();
>     DomainTransferData td = domain.getTransferData();
> ```

I think this line may have snuck in?

**Review by mindhog — COMMENTED** [review]
> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1009)* status: 9 of 17 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java, line 495 at r4](https://reviewable.io/reviews/google/nomulus/1009#-MW5FEq36iX_xj0wOolq:-MW5Otn680jLTDimMYzv:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d9ce9e3ed5f5cae4da9773028f9f40c902c1ac1a/core/src/test/java/google/registry/flows/domain/DomainTransferRequestFlowTest.java#L495)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think this line may have snuck in? 
</blockquote></details>

Done.

**Review by gbrodman — APPROVED** [review]
> Reviewed 7 of 8 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1009)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mindhog)

**Pull request merged**
