### PR TITLE
Add console users action

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2573)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2573)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 90 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7oSAtR-6RV-KfiXdMr:-O7oSAtR-6RV-KfiXdMs:b-ivkd48) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L90)):*
> ```Java
>       checkPermission(user, registrarId, ConsolePermission.MANAGE_USERS);
>       tm().transact(() -> runInTransaction(user));
>     }
> ```

ew'd probably want to set a failure status in an `else` clause right? 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 96 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7oXG6qBN6UNYLI1g7_:-O7oXG6qBN6UNYLI1g7a:b-784y0c) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L96)):*
> ```Java
>   protected void getHandler(User user) {
>     if (user.getUserRoles().hasGlobalPermission(ConsolePermission.MANAGE_USERS)) {
>       consoleApiParams.response().setPayload(gson.toJson(getAllUsers()));
> ```

Are you envisioning all of the users being on the same page in the UI if the user is an admin? If so, I'm wondering how we'll handle the case where a user is not an admin but is a primary contact on multiple registrars 

Basically, I'm thinking we might want to ignore the provided registrar ID entirely (and show all users that the user has access to) or only show users for this registrar ID, regardless of whether or not the user is an admin.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 103 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7oW6SgBoRG-cTGiAUb:-O7oW6SgBoRG-cTGiAUc:brp3d00) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L103)):*
> ```Java
>     List<User> users =
>         getAllUsers().stream()
>             .filter(u -> u.getUserRoles().getRegistrarRoles().containsKey(registrarId))
> ```

ew this is gross haha, i wish we had a better way to get the users for a particular registrar
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 132 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7ocq7kBT5HwfDuKprE:-O7ocq7kBT5HwfDuKprF:bqc6ulb) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L132)):*
> ```Java
>     }
> 
>     UserRoles userRolesBuilder =
> ```

nit, but technically this is no longer a "builder" 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 135 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7ocdKv8aVuCNCoU4xQ:-O7ocdKv8aVuCNCoU4xR:bbexsc5) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L135)):*
> ```Java
>         new UserRoles.Builder()
>             .setRegistrarRoles(ImmutableMap.of(registrarId, ACCOUNT_MANAGER))
>             .setIsAdmin(false)
> ```

fwiw i think this and GlobalRole.NONE are the defaults so no need to specify /shrug

**Review by gbrodman — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2573)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @ptkach)

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2573)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 90 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7oSAtR-6RV-KfiXdMr:-O7og0z10Gwvzkk6lFPe:bbm1zwt) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L90)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ew'd probably want to set a failure status in an `else` clause right?
</blockquote></details>

It's a temporary flag, so I wasn't planning on taking care of the response all that much, but sure I can add a failure status. 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 96 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7oXG6qBN6UNYLI1g7_:-O7ogWos-xvdo8ssMj0j:b-bgfzkd) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L96)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Are you envisioning all of the users being on the same page in the UI if the user is an admin? If so, I'm wondering how we'll handle the case where a user is not an admin but is a primary contact on multiple registrars 

Basically, I'm thinking we might want to ignore the provided registrar ID entirely (and show all users that the user has access to) or only show users for this registrar ID, regardless of whether or not the user is an admin.
</blockquote></details>

I've been thinking about it too and i kept global part only because I realized that 99% of the time this screen will be used by partners and 1% by global role users. In that 1% it will likely be quick role update for the user and in that case selecting registrart would be an extra step. However I'm not married to this so I will just rid of that block.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 103 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7oW6SgBoRG-cTGiAUb:-O7oh_em5exiCTGQPKSt:bdbdxr0) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L103)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ew this is gross haha, i wish we had a better way to get the users for a particular registrar
</blockquote></details>

yeah, it'd also be a big performance issue on a larger amount of users, but we're good
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 132 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7ocq7kBT5HwfDuKprE:-O7ohqIP6wcAyAIMOy_n:b-p8h0os) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L132)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit, but technically this is no longer a "builder"
</blockquote></details>

true, this has undergone some rewrites and the name hasn't kept up
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 135 at r2](https://reviewable.io/reviews/google/nomulus/2573#-O7ocdKv8aVuCNCoU4xQ:-O7oiHrZ00njsb4M7uNh:b-896fix) ([raw file](https://github.com/google/nomulus/blob/fcb2a7373404e655dd17f2e3dc844ba126d6c48d/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L135)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

fwiw i think this and GlobalRole.NONE are the defaults so no need to specify /shrug
</blockquote></details>

Done.

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2573)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2573)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
