### PR TITLE
Add script to allow quickly update number of instances

### PR DESCRIPTION
**Pull request by ptkach**
This is a fast and easy way to update number of instances for the service deployed to app engine. Works with manual-scaling types services.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2112)

### CODE REVIEW

**Comment by ptkach** [comment]
@weiminyu  I tested it in sandbox successfully

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2112)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`release/update_num_instances.sh` line 22 at r1](https://reviewable.io/reviews/google/nomulus/2112#-Nc33_eK4Rq6GrFc-gmc:-Nc33_eK4Rq6GrFc-gmd:b-d1h1lz) ([raw file](https://github.com/google/nomulus/blob/6c4fa4021fd820e192e42fa9344a9064069c5d97/release/update_num_instances.sh#L22)):*
> ```Shell
> #
> # Example:
> # ./update_num_instances.sh domain-registry-sandbox pubapi
> ```

Please remember to add this to the playbook http://cs/google3/googledata/production/playbooks/domain_registry/procedures/set_appengine_num_instances.md.



_Code quote:_
```Shell
./update_num_instances.sh domain-registry-sandbox pubapi
```
___
*[`release/update_num_instances.sh` line 23 at r1](https://reviewable.io/reviews/google/nomulus/2112#-Nc35feh8KDAXjZFHbrJ:-Nc35feh8KDAXjZFHbrK:byty8at) ([raw file](https://github.com/google/nomulus/blob/6c4fa4021fd820e192e42fa9344a9064069c5d97/release/update_num_instances.sh#L23)):*
> ```Shell
> # Example:
> # ./update_num_instances.sh domain-registry-sandbox pubapi
> ```

Do we need a `set -e` here to fail fast?
___
*[`release/update_num_instances.sh` line 35 at r1](https://reviewable.io/reviews/google/nomulus/2112#-Nc35Brh5sxqDcpcgjoj:-Nc35Brh5sxqDcpcgjok:b-199c73) ([raw file](https://github.com/google/nomulus/blob/6c4fa4021fd820e192e42fa9344a9064069c5d97/release/update_num_instances.sh#L35)):*
> ```Shell
>     --format="csv[no-heading](VERSION.ID)")
> 
> service_description=$(curl -H "Authorization: Bearer $(gcloud auth print-access-token)" https://appengine.googleapis.com/v1/apps/${project}/services/${service}/versions/${deployed_version})
> ```

Set this to a variable for reuse?



_Code quote:_
```Shell
"Authorization: Bearer $(gcloud auth print-access-token)"
```

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2112)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @weiminyu)

___
*[`release/update_num_instances.sh` line 22 at r1](https://reviewable.io/reviews/google/nomulus/2112#-Nc33_eK4Rq6GrFc-gmc:-Nc38gcbBAL4sv7n94LM:bs95954) ([raw file](https://github.com/google/nomulus/blob/6c4fa4021fd820e192e42fa9344a9064069c5d97/release/update_num_instances.sh#L22)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Please remember to add this to the playbook http://cs/google3/googledata/production/playbooks/domain_registry/procedures/set_appengine_num_instances.md.
</blockquote></details>

I will, I wanted to hear your thoughts on this one first and get merged
___
*[`release/update_num_instances.sh` line 23 at r1](https://reviewable.io/reviews/google/nomulus/2112#-Nc35feh8KDAXjZFHbrJ:-Nc38l4LBTwE55-nCnx3:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6c4fa4021fd820e192e42fa9344a9064069c5d97/release/update_num_instances.sh#L23)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Do we need a `set -e` here to fail fast?
</blockquote></details>

Done.
___
*[`release/update_num_instances.sh` line 35 at r1](https://reviewable.io/reviews/google/nomulus/2112#-Nc35Brh5sxqDcpcgjoj:-Nc38lxa4tfcfmdVXXig:b-dn401n) ([raw file](https://github.com/google/nomulus/blob/6c4fa4021fd820e192e42fa9344a9064069c5d97/release/update_num_instances.sh#L35)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Set this to a variable for reuse?
</blockquote></details>

I've considered it, but decided against for the following reasons - 1) in between the calls input is required, which technically can take time and token can expire 2) i think it's more secure not to store it

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2112)* status: 0 of 1 files reviewed, 1 unresolved discussion

**Pull request merged**
