### PR TITLE
Refactor test DB creation for BEAM pipelines and properly deploy Spec11

### PR DESCRIPTION
**Pull request by gbrodman**
This change also allows us to do proper DB testing in the
Spec11PipelineTest which we were mocking out before.

This also drops the Spec11 foreign keys the same way that #897 does for
the same reason -- we can't guarantee that these objects exist in SQL
yet. b/175059784 to re-add them once we're done.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/903)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/903)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/903#-MOYFlcRB0WMzVna_RpN:-MOYFlcRB0WMzVna_RpO:b-wrday9) ([raw file](https://github.com/google/nomulus/blob/673a869f42cd070edee86cc3e6b41eb655bd4277/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L84)):*
> ```
> transient
> ```
Let's document somewhere that transient is needed because serializable inner classes/lambdas are used in ParDo functions.
___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 104 at r1](https://reviewable.io/reviews/google/nomulus/903#-MOYD6694CUL8kQ9HEg5:-MOYD6694CUL8kQ9HEg6:b-st1rru) ([raw file](https://github.com/google/nomulus/blob/673a869f42cd070edee86cc3e6b41eb655bd4277/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L104)):*
> ```
> // Must not be transient!
> ```
This field can be transient. WriteToSqlTest needed it as non-transient (and other fields as transient) because this field is used in a lambda passed to the pipeline. InitSqlPipelineTest copied the snippet but did not remove it when the setup routine was changed.

**Review by gbrodman — COMMENTED** [review]
This PR now modifies the BEAM SQL connection to use only the `SqlCredentialStore` -- I'd imagine we wouldn't want to merge this until we're confident that that works. 

The local JPA TM uses the local credential file -- this is what's used in the unit tests. Thoughts on how to test the socket factory JPA TM in the Spec11PipelineTest (if we even want to)? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/903#-:-MPkd0i0EbFKkAF3xsYm:b-ol1p5h)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @weiminyu)

___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 84 at r1](https://reviewable.io/reviews/google/nomulus/903#-MOYFlcRB0WMzVna_RpN:-MPkcrJ_AFHE276gKK-5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/673a869f42cd070edee86cc3e6b41eb655bd4277/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L84)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> transient
> ```
Let's document somewhere that transient is needed because serializable inner classes/lambdas are used in ParDo functions.
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java, line 104 at r1](https://reviewable.io/reviews/google/nomulus/903#-MOYD6694CUL8kQ9HEg5:-MPkcsB5D7LWuANnGF8c:b-896fix) ([raw file](https://github.com/google/nomulus/blob/673a869f42cd070edee86cc3e6b41eb655bd4277/core/src/test/java/google/registry/beam/spec11/Spec11PipelineTest.java#L104)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> // Must not be transient!
> ```
This field can be transient. WriteToSqlTest needed it as non-transient (and other fields as transient) because this field is used in a lambda passed to the pipeline. InitSqlPipelineTest copied the snippet but did not remove it when the setup routine was changed. 
</blockquote></details>

Done.

**Review by weiminyu — COMMENTED** [review]
In tests you can use the FakeSecretManagerClient to back the SqlCredentialStore. See SqlCredentialStoreTest. You may need a new module.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/903#-:-MQNQU7L3W_fWhOrXsAA:b-o5keia)* status: 0 of 10 files reviewed, all discussions resolved

**Review by weiminyu — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/903)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 162 at r2](https://reviewable.io/reviews/google/nomulus/903#-MQNyTOS4SOfBIqpPPKW:-MQNyTOT08OXVTaquXqt:bc5x3ym) ([raw file](https://github.com/google/nomulus/blob/b313f5c8120d1f9b0e10f1258204085e96e30ae3/core/src/main/java/google/registry/persistence/PersistenceModule.java#L162)):*
> ```
> sqlCredential.password()
> ```
Lets wait until the credential store is validated

**Review by gbrodman — COMMENTED** [review]
Yeah, we'll need to do some refactoring because currently there's no way to inject the secret manager client but I can take a look at that. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/903#-:-MQO-Ecf9-DGDNsvrV-1:bmwtph)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 162 at r2](https://reviewable.io/reviews/google/nomulus/903#-MQNyTOS4SOfBIqpPPKW:-MQO-BhZ0OhN_uAnfyzd:b-lwpyk2) ([raw file](https://github.com/google/nomulus/blob/b313f5c8120d1f9b0e10f1258204085e96e30ae3/core/src/main/java/google/registry/persistence/PersistenceModule.java#L162)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> sqlCredential.password()
> ```
Lets wait until the credential store is validated
</blockquote></details>

For sure, I wouldn't merge this until we're confident in that.

**Review by gbrodman — COMMENTED** [review]
@weiminyu , thoughts on this refactoring? I created the PersistenceTestModule for the local DB and we keep the cloud-SQL-connection DB in PersistenceModule. This seems like the best and cleanest way for the tests to use the local DB without a ton of boilerplate code everywhere, I think. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/903#-:-MR1LHan-ZHBkjJ-QVfq:bqoor0j)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

**Review by gbrodman — COMMENTED** [review]
@weiminyu any thoughts? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/903#-:-MRvq1QJ09CQvyRad825:bo0vfk1)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/903)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[core/src/test/java/google/registry/persistence/PersistenceTestModule.java, line 76 at r3](https://reviewable.io/reviews/google/nomulus/903#-MShjYeyAR1xvLqoU4hN:-MShjYeyAR1xvLqoU4hO:b-7xlkaw) ([raw file](https://github.com/google/nomulus/blob/acc7fec255eaf40226eb16e8c08982237028d4b7/core/src/test/java/google/registry/persistence/PersistenceTestModule.java#L76)):*
> ```
> SecretManagerModule.class,
> ```
If we replace this with a FakeSecretManagerModule that binds SecreteManagerClient to FakeSecretManagerClient, tests would not need the credential files anymore.
The BeamJpaModule no longer needs to provide the username and password, and BeamJpaExtension will need to set up the fake credential store.

**Review by weiminyu — COMMENTED** [review]
Please take a look at my comment to the new PersistenceTestModule.

We probably want a separate pr to switch to secretmanager first, which is blocked by the security review.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/903#-:-MSmjK-m5v43TG3XmhpB:bvru4uk)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @weiminyu)

**Comment by gbrodman** [comment]
moot

**Pull request closed without merging**
