### PR TITLE
Refactor away inner transaction in AllocationToken.loadToken()

### PR DESCRIPTION
**Pull request by CydeWeys**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2127)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: all files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java` line 186 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci4YsxD0__oe9GB3iJ:-Nci4YsxD0__oe9GB3iK:budgl8w) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java#L186)):*
> ```Java
>         allocationTokenExtension.map(
>             tokenExtension ->
>                 tm().transact(
> ```

it seems like we have (this is not new) a ton of mini-transactions inside DomainCheckFlow. Is it better to have a bunch of small read-only transactions (thus entering/exiting transactions more frequently) or is it better to have one larger read-only transaction (possibly keeping locks for longer, but avoiding the transaction overhead)? 
___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 143 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci549gEeVHIFvOJkbb:-Nci549gEeVHIFvOJkbc:b-un7zk9) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L143)):*
> ```Java
>     when(allocationTokenExtension.getAllocationToken()).thenReturn("tokeN");
>     assertThat(
>             tm().transact(
> ```

what about a test method that encapsulates this? Like, calling something like `DatabaseHelper.transactWithoutThrowing(() -> flowUtils.verify.....))`
___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 482 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci5VYN1rkAWzhWQ8Zo:-Nci5VYN1rkAWzhWQ8Zp:bryb56v) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L482)):*
> ```Java
>         .that(
>             tm().transact(
>                     () ->
> ```

i think it might make more sense to move the transact call one level inward, to keep the two `assert` calls closer to each other

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java` line 186 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci4YsxD0__oe9GB3iJ:-NciGg_ACM67eGFqQGvc:bg069fs) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java#L186)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it seems like we have (this is not new) a ton of mini-transactions inside DomainCheckFlow. Is it better to have a bunch of small read-only transactions (thus entering/exiting transactions more frequently) or is it better to have one larger read-only transaction (possibly keeping locks for longer, but avoiding the transaction overhead)?
</blockquote></details>

Yes, see https://github.com/google/nomulus/pull/2129 for a better solution to the overall problem that will prevent us from having to add lots of little transactions into flows (I wasn't liking that either).  That will go in first and then I will fix up this PR subsequently.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java` line 186 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci4YsxD0__oe9GB3iJ:-NciGg_ACM67eGFqQGvc:bg069fs) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java#L186)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it seems like we have (this is not new) a ton of mini-transactions inside DomainCheckFlow. Is it better to have a bunch of small read-only transactions (thus entering/exiting transactions more frequently) or is it better to have one larger read-only transaction (possibly keeping locks for longer, but avoiding the transaction overhead)?
</blockquote></details>

Yes, see https://github.com/google/nomulus/pull/2129 for a better solution to the overall problem that will prevent us from having to add lots of little transactions into flows (I wasn't liking that either).  That will go in first and then I will fix up this PR subsequently.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 143 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci549gEeVHIFvOJkbb:-NciGs0v2tyCBFCx3O-O:b-4gr95a) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L143)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what about a test method that encapsulates this? Like, calling something like `DatabaseHelper.transactWithoutThrowing(() -> flowUtils.verify.....))`
</blockquote></details>

It doesn't work because the issue is with the exceptions themselves being thrown in the lambda.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 143 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci549gEeVHIFvOJkbb:-NciGs0v2tyCBFCx3O-O:b-4gr95a) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L143)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what about a test method that encapsulates this? Like, calling something like `DatabaseHelper.transactWithoutThrowing(() -> flowUtils.verify.....))`
</blockquote></details>

It doesn't work because the issue is with the exceptions themselves being thrown in the lambda.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 482 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci5VYN1rkAWzhWQ8Zo:-NciH7MQ9BdlBBcegkOQ:bu20k79) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L482)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think it might make more sense to move the transact call one level inward, to keep the two `assert` calls closer to each other
</blockquote></details>

It doesn't work. `assertThrows()` doesn't throw a checked exception, so it's eligible to be in the lambda, but `verifyAllocationTokenIfPresent()` does throw a checked exception, so it can't be in the lambda without something wrapping it that swallows that exception without rethrowing it.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 482 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci5VYN1rkAWzhWQ8Zo:-NciH7MQ9BdlBBcegkOQ:bu20k79) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L482)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think it might make more sense to move the transact call one level inward, to keep the two `assert` calls closer to each other
</blockquote></details>

It doesn't work. `assertThrows()` doesn't throw a checked exception, so it's eligible to be in the lambda, but `verifyAllocationTokenIfPresent()` does throw a checked exception, so it can't be in the lambda without something wrapping it that swallows that exception without rethrowing it.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 482 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci5VYN1rkAWzhWQ8Zo:-NciH7MQ9BdlBBcegkOQ:bu20k79) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L482)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think it might make more sense to move the transact call one level inward, to keep the two `assert` calls closer to each other
</blockquote></details>

It doesn't work. `assertThrows()` doesn't throw a checked exception, so it's eligible to be in the lambda, but `verifyAllocationTokenIfPresent()` does throw a checked exception, so it can't be in the lambda without something wrapping it that swallows that exception without rethrowing it.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java` line 186 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci4YsxD0__oe9GB3iJ:-NciKJxa1dD9yl7ReFLf:bbqhww5) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java#L186)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yes, see https://github.com/google/nomulus/pull/2129 for a better solution to the overall problem that will prevent us from having to add lots of little transactions into flows (I wasn't liking that either).  That will go in first and then I will fix up this PR subsequently.
</blockquote></details>

got it, sgtm
___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 143 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci549gEeVHIFvOJkbb:-NciJvVVDVck_k8SH-97:b-deftuf) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L143)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It doesn't work because the issue is with the exceptions themselves being thrown in the lambda.
</blockquote></details>

ugh right idk what i was thinking 
___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 482 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci5VYN1rkAWzhWQ8Zo:-NciJbpV4UEjrrXi7pLR:b1xrzlh) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L482)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It doesn't work. `assertThrows()` doesn't throw a checked exception, so it's eligible to be in the lambda, but `verifyAllocationTokenIfPresent()` does throw a checked exception, so it can't be in the lambda without something wrapping it that swallows that exception without rethrowing it.
</blockquote></details>

hmmm yeah, what about moving the transact call outward so it's the first line in the method?

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 482 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci5VYN1rkAWzhWQ8Zo:-NcxyDAmCtRp9npyKYue:b-m0rzpz) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L482)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

hmmm yeah, what about moving the transact call outward so it's the first line in the method?
</blockquote></details>

I mean it's possible, but is it better?  Personally I'd rather see the asserts at the top level rather than the meaningless transactional wrapper.

**Review by CydeWeys — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127#-:-NcxyOse0IzXqbcSWLd0:bb71pro)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @jianglai)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java` line 186 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci4YsxD0__oe9GB3iJ:-NcxyQv_5WYhBKQ8VX_6:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java#L186)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

got it, sgtm
</blockquote></details>

Done.

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

___
*[`core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java` line 482 at r1](https://reviewable.io/reviews/google/nomulus/2127#-Nci5VYN1rkAWzhWQ8Zo:-NcxzDNCB-P7hSgrDSjx:b32wko) ([raw file](https://github.com/google/nomulus/blob/e9302d6cd3e2d3f5be113f44ad4420557daa624d/core/src/test/java/google/registry/flows/domain/token/AllocationTokenFlowUtilsTest.java#L482)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I mean it's possible, but is it better?  Personally I'd rather see the asserts at the top level rather than the meaningless transactional wrapper.
</blockquote></details>

eh

**Pull request closed without merging**
