### PR TITLE
Add create/delete/update commands for User objects

### PR DESCRIPTION
**Pull request by gbrodman**
This also includes the change of allowing the Java User object to have a null GAIA ID (when creating user objects, we don't know what the GAIA ID is).

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1936)

### CODE REVIEW

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 9 of 12 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1936)* status: all files reviewed, 11 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java` line 60 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP446_W0VT39P5rCLB4:-NP446_W0VT39P5rCLB5:b-wywbyp) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java#L60)):*
> ```Java
> 
>   @Nullable
>   abstract User getOldUser(String email);
> ```

`getExistingUser`



_Code quote:_
```Java
getOldUser
```
___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java` line 77 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP45RU9AXXvABPYAYbX:-NP45RU9AXXvABPYAYbY:bvsyzhn) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java#L77)):*
> ```Java
>     builder.setUserRoles(userRolesBuilder.build());
>     User newUser = builder.build();
>     UserDao.saveUser(newUser);
> ```

Are we not concerned about the user object changing between when it was read and when the new object is saved here?



_Code quote:_
```Java
UserDao.saveUser(newUser);
```
___
*[`core/src/main/java/google/registry/tools/CreateUserCommand.java` line 22 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP45zqW3Un406-3V-Fc:-NP45zqW3Un406-3V-Fd:b-mcx36h) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/CreateUserCommand.java#L22)):*
> ```Java
> import google.registry.model.console.User;
> import google.registry.model.console.UserDao;
> import org.jetbrains.annotations.Nullable;
> ```

Bad JetBrains, trying to sneak in its own annotation!



_Code quote:_
```Java
org.jetbrains.annotations.Nullable;
```
___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP453Wg6-L1GzJB9Sf5:-NP453Wh7vLMaNfPudgc:b656f8i) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L39)):*
> ```Java
>   protected String prompt() {
>     checkArgumentNotNull(email, "Email must be provided");
>     checkArgumentPresent(UserDao.loadUser(email), "Email does not correspond to a valid user");
> ```

There's no point checking if the email exists here, because you have to check it again in the same transaction where you delete the user.



_Code quote:_
```Java
checkArgumentPresent(UserDao.loadUser(email), "Email does not correspond to a valid user");
```
___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 45 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP44rJT7bCVw3dC8zlc:-NP44rJT7bCVw3dC8zld:b-vh1s0i) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L45)):*
> ```Java
>   @Override
>   protected String execute() throws Exception {
>     checkArgumentNotNull(email, "Email must be provided");
> ```

Do we need to check this again? It's already checked in `prompt()`.



_Code quote:_
```Java
checkArgumentNotNull(email, "Email must be provided");
```
___
*[`core/src/main/java/google/registry/tools/RegistryToolComponent.java` line 107 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP46UsGBfZbsBAsPTZ3:-NP46UsH02hQdy9bL2DB:b-hla2f5) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/RegistryToolComponent.java#L107)):*
> ```Java
>   void inject(CreateTldCommand command);
> 
>   void inject(CreateUserCommand command);
> ```

FWIW I don't think any of the new commands have any injectable fields, so it is not necessary to have injectors for them.



_Code quote:_
```Java
inject(CreateUserCommand command)
```
___
*[`core/src/main/java/google/registry/tools/UpdateUserCommand.java` line 22 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP464jrBmqmUPfJScFi:-NP464jrBmqmUPfJScFj:bgcpudb) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/UpdateUserCommand.java#L22)):*
> ```Java
> import google.registry.model.console.User;
> import google.registry.model.console.UserDao;
> import org.jetbrains.annotations.Nullable;
> ```

Real sneaky!



_Code quote:_
```Java
org.jetbrains.annotations.Nullable
```

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1936)* status: all files reviewed, 11 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java` line 60 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP446_W0VT39P5rCLB4:-NPO9cIn5bPmu-nXU8xE:b-896fix) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java#L60)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

`getExistingUser`
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java` line 77 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP45RU9AXXvABPYAYbX:-NPODoJF04z7PtqAFcU4:b-vg2sr7) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java#L77)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Are we not concerned about the user object changing between when it was read and when the new object is saved here?
</blockquote></details>

I don't think this will be a problem since this is manually done, but yeah we can wrap it. 
___
*[`core/src/main/java/google/registry/tools/CreateUserCommand.java` line 22 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP45zqW3Un406-3V-Fc:-NPODseL929XoRvkW6dB:b-7h1xwd) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/CreateUserCommand.java#L22)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Bad JetBrains, trying to sneak in its own annotation!
</blockquote></details>

wtf! 
___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP453Wg6-L1GzJB9Sf5:-NPOERGxB9Kx_vETOCFy:b-kajyqi) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L39)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

There's no point checking if the email exists here, because you have to check it again in the same transaction where you delete the user.
</blockquote></details>

I think it's beneficial to have it in both places because there's no transactionality between `prompt` and `execute` just in case 
___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 45 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP44rJT7bCVw3dC8zlc:-NPOEMp74ENNazoqrry2:bejgg8z) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L45)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Do we need to check this again? It's already checked in `prompt()`.
</blockquote></details>

indeed not 
___
*[`core/src/main/java/google/registry/tools/RegistryToolComponent.java` line 107 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP46UsGBfZbsBAsPTZ3:-NPOECV_CC1e77BTdmQ9:b-1jrj0) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/RegistryToolComponent.java#L107)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

FWIW I don't think any of the new commands have any injectable fields, so it is not necessary to have injectors for them.
</blockquote></details>

ah i wasn't sure if that was the case, neat. 
___
*[`core/src/main/java/google/registry/tools/UpdateUserCommand.java` line 22 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP464jrBmqmUPfJScFi:-NPOEG_Y4fgZAX8KpYZZ:b-1lyswe) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/UpdateUserCommand.java#L22)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Real sneaky!
</blockquote></details>

booooooo

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1936)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java` line 77 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP45RU9AXXvABPYAYbX:-NPSk3NbB5BMpa2SbqrH:bvrowpj) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java#L77)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think this will be a problem since this is manually done, but yeah we can wrap it. 
</blockquote></details>

Better safe than sorry. But why making a separate function just for this? Can't we just wrap everything in-place inside `tm().transact()`?
___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP453Wg6-L1GzJB9Sf5:-NPSnLT-A9kb5Ee6BhMm:b-hqiojv) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L39)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think it's beneficial to have it in both places because there's no transactionality between `prompt` and `execute` just in case 
</blockquote></details>

Sorry I think I worded it incorrectly. I meant that you have to check it in *another* transaction in `execute()`. So if the email does not correspond to a valid user here, you stop. If it does, you immediately run `execute()` afterward, which checks the same thing again in another transaction, because things might have changed between `prompt()` and `execute()`.

In the end, the first check is redundant. If you don't check it there, you check it in `execute()`. If you do, you check it again in `execute()`.

**Review by gbrodman — COMMENTED** [review]
> Dismissed @github-code-scanning[bot] from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1936)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP453Wg6-L1GzJB9Sf5:-NPTYI3e8-S6j3yG9rkC:b3r0d2e) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L39)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Sorry I think I worded it incorrectly. I meant that you have to check it in *another* transaction in `execute()`. So if the email does not correspond to a valid user here, you stop. If it does, you immediately run `execute()` afterward, which checks the same thing again in another transaction, because things might have changed between `prompt()` and `execute()`.

In the end, the first check is redundant. If you don't check it there, you check it in `execute()`. If you do, you check it again in `execute()`.
</blockquote></details>

Yeah, it's redundant, but that's why it's in the `prompt` method anyway so we can give the user more meaningful feedback sooner 
___
*[`core/src/main/java/google/registry/tools/RegistryToolComponent.java` line 107 at r1](https://reviewable.io/reviews/google/nomulus/1936#-NNmx00__UkIL1WeHv1V-r1-107:-NPTYPnwEU9CTgR2cqZ9:b-896fix) ([raw file](https://github.com/google/nomulus/blob/a529c374ae4d7169184d0a1f031fd1e112656a61/core/src/main/java/google/registry/tools/RegistryToolComponent.java#L107)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Useless parameter

The parameter 'command' is never used.

[Show more details](https://github.com/google/nomulus/security/code-scanning/764)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/tools/RegistryToolComponent.java` line 169 at r1](https://reviewable.io/reviews/google/nomulus/1936#-NNmx00__UkIL1WeHv1V-r1-169:-NPTYSp34Pshg6GJjoqU:b-896fix) ([raw file](https://github.com/google/nomulus/blob/a529c374ae4d7169184d0a1f031fd1e112656a61/core/src/main/java/google/registry/tools/RegistryToolComponent.java#L169)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Useless parameter

The parameter 'command' is never used.

[Show more details](https://github.com/google/nomulus/security/code-scanning/763)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/tools/RegistryToolComponent.java` line 107 at r2](https://reviewable.io/reviews/google/nomulus/1936#-NNmx00__UkIL1WeHv1V-r2-107:-NPTYRNN0RIqGoDQJoy_:b-896fix) ([raw file](https://github.com/google/nomulus/blob/84511e5a2dcd5d696e64f027c85094796d931932/core/src/main/java/google/registry/tools/RegistryToolComponent.java#L107)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Useless parameter

The parameter 'command' is never used.

[Show more details](https://github.com/google/nomulus/security/code-scanning/766)
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/tools/RegistryToolComponent.java` line 109 at r2](https://reviewable.io/reviews/google/nomulus/1936#-NNmx00__UkIL1WeHv1V-r2-109:-NPTYS649qQ7p-nNFxGV:b-896fix) ([raw file](https://github.com/google/nomulus/blob/84511e5a2dcd5d696e64f027c85094796d931932/core/src/main/java/google/registry/tools/RegistryToolComponent.java#L109)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Useless parameter

The parameter 'command' is never used.

[Show more details](https://github.com/google/nomulus/security/code-scanning/765)
</blockquote></details>

Done.

**Review by jianglai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1936)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP453Wg6-L1GzJB9Sf5:-NPTdfjKCC6ya9RXbtqI:beoafrg) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L39)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah, it's redundant, but that's why it's in the `prompt` method anyway so we can give the user more meaningful feedback sooner 
</blockquote></details>

If it fails in `execute()`, doesn't it tell you "Email no longer corresponds to a valid user"? How is that "sooner"? If everything works out fine, we would have done two transactions to load the user for no apparent benefit. What really matters is that the user exists in the second transaction (in `execute()`), so whether the user exist before that transaction runs is irrelevant -- if they don't, you still have to spend first transaction to check on that in order to not run the second one; if they do, you have to check again in the the second one anyway. Is there something that I missed here?

We can just have the check in `execute()` throw "Email does not correspond to a valid user". Unless there's a difference in where the exception is thrown, in terms of how the users are notified, between `prompt()` and `execute()`?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1936)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP453Wg6-L1GzJB9Sf5:-NPTgUxy19rmxcO9s2b-:bo78let) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L39)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

If it fails in `execute()`, doesn't it tell you "Email no longer corresponds to a valid user"? How is that "sooner"? If everything works out fine, we would have done two transactions to load the user for no apparent benefit. What really matters is that the user exists in the second transaction (in `execute()`), so whether the user exist before that transaction runs is irrelevant -- if they don't, you still have to spend first transaction to check on that in order to not run the second one; if they do, you have to check again in the the second one anyway. Is there something that I missed here?

We can just have the check in `execute()` throw "Email does not correspond to a valid user". Unless there's a difference in where the exception is thrown, in terms of how the users are notified, between `prompt()` and `execute()`?
</blockquote></details>

It does fail there, but given that we're deleting something we want the prompt just in case. I really don't see this as a big deal given that it's a manual command that we'll very rarely run

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1936)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java` line 77 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP45RU9AXXvABPYAYbX:-NPTtviiAolPMhRgeeXE:bfaqsg3) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java#L77)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Better safe than sorry. But why making a separate function just for this? Can't we just wrap everything in-place inside `tm().transact()`?
</blockquote></details>

we could, but this has nicer indentation

**Review by jianglai — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1936)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP453Wg6-L1GzJB9Sf5:-NPXhoZnC9ZHtxrD26d0:b-74mwx1) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L39)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It does fail there, but given that we're deleting something we want the prompt just in case. I really don't see this as a big deal given that it's a manual command that we'll very rarely run 
</blockquote></details>

Sure. I don't think it's worth fixating on. But you get the prompt anyway as it is a `ConfirmingCommand`, not sure why it would affect the decision on where to throw the exception.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1936)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/tools/DeleteUserCommand.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1936#-NP453Wg6-L1GzJB9Sf5:-NPy8pG86FiUOmcWTWyR:b-o8d2aq) ([raw file](https://github.com/google/nomulus/blob/006c5bd21729aa0534ebe613c7ac9489b23c3192/core/src/main/java/google/registry/tools/DeleteUserCommand.java#L39)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Sure. I don't think it's worth fixating on. But you get the prompt anyway as it is a `ConfirmingCommand`, not sure why it would affect the decision on where to throw the exception.
</blockquote></details>

Yeah it seems low-stakes, might as well just throw it as early as possible

**Pull request merged**
