### PR TITLE
Store DatabaseMigrationSchedule in SQL instead of Datastore

### PR DESCRIPTION
**Pull request by gbrodman**
This requires messing around with some of the JPA unit test rule
creation since it requires saving / retrieving the schedule pretty much
always (which itself includes the hstore extension).

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1269)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 36 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java, line 47 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkG89I6Btdp9rH4MfM:-MgkG89I6Btdp9rH4MfN:b-3a7v4v) ([raw file](https://github.com/google/nomulus/blob/a3eb472386567736753a18eb5bcde4ef6126c0e3/core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java#L47)):*
> ```Java
> @Entity
> @InCrossTld
> public class DatabaseMigrationStateSchedule extends CrossTldSingleton implements SqlOnlyEntity {
> ```

Won't these changes have to be broken out into a separate PR that can only be committed once the DB changes below are committed and deployed?
___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkFnVf53XrW9vpQOwa:-MgkFnVf53XrW9vpQOwb:beu92z7) ([raw file](https://github.com/google/nomulus/blob/a3eb472386567736753a18eb5bcde4ef6126c0e3/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L45)):*
> ```Java
>   private static final ImmutableSet<String> IGNORE_ENTITIES =
>       ImmutableSet.of(
>           // DMSS tests clean up after themselves so we can't tell that any entities were persisted
> ```

"DMSS" is not an abbreviation we're commonly using.  If the comment needs to be longer to include the full unambiguous string, so be t.
___
*[core/src/test/resources/google/registry/export/crosstld_kinds.txt, line 4 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkGb554LvE1LbKb2_a:-MgkGb5699Nuu28xXn0D:ba4lahu) ([raw file](https://github.com/google/nomulus/blob/9811cdb85c5cd184386ee665b46dec186f868b2b/core/src/test/resources/google/registry/export/crosstld_kinds.txt#L4)):*
> ```help
> ClaimsListSingleton
> Cursor
> DatabaseMigrationStateSchedule
> ```

Per above comment, I don't think you can remove the Datastore stuff quite yet.
___
*[db/src/main/resources/sql/flyway/V100__database_migration_schedule.sql, line 15 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkF_jV1k0SqOCkz95p:-MgkF_jV1k0SqOCkz95q:bswvmtr) ([raw file](https://github.com/google/nomulus/blob/a3eb472386567736753a18eb5bcde4ef6126c0e3/db/src/main/resources/sql/flyway/V100__database_migration_schedule.sql#L15)):*
> ```TSQL
> -- limitations under the License.
> 
> CREATE TABLE "DatabaseMigrationStateSchedule" (
> ```

Add a singleton constraint so that this table can only contain one row.  See: https://cloudoki.com/database-singleton-table/

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 36 files reviewed, 4 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java, line 47 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkG89I6Btdp9rH4MfM:-MgkT4vt8A2KmXxpdRME:bi06u0j) ([raw file](https://github.com/google/nomulus/blob/a3eb472386567736753a18eb5bcde4ef6126c0e3/core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java#L47)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Won't these changes have to be broken out into a separate PR that can only be committed once the DB changes below are committed and deployed?
</blockquote></details>

Nah that process only applies to changes of existing schema where we don't want to lose data. For adding things, it's totally fine to do both in one
___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkFnVf53XrW9vpQOwa:-MgkTTCr23Fq--4eJMHd:b-896fix) ([raw file](https://github.com/google/nomulus/blob/a3eb472386567736753a18eb5bcde4ef6126c0e3/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L45)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

"DMSS" is not an abbreviation we're commonly using.  If the comment needs to be longer to include the full unambiguous string, so be t.
</blockquote></details>

Done.
___
*[core/src/test/resources/google/registry/export/crosstld_kinds.txt, line 4 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkGb554LvE1LbKb2_a:-MgkTeMN8T_YGUyY7xy9:bnmxbyk) ([raw file](https://github.com/google/nomulus/blob/9811cdb85c5cd184386ee665b46dec186f868b2b/core/src/test/resources/google/registry/export/crosstld_kinds.txt#L4)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Per above comment, I don't think you can remove the Datastore stuff quite yet.
</blockquote></details>

responded above
___
*[db/src/main/resources/sql/flyway/V100__database_migration_schedule.sql, line 15 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkF_jV1k0SqOCkz95p:-MgkVLRA-vjYaWp4eKAD:b-tbuxbq) ([raw file](https://github.com/google/nomulus/blob/a3eb472386567736753a18eb5bcde4ef6126c0e3/db/src/main/resources/sql/flyway/V100__database_migration_schedule.sql#L15)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Add a singleton constraint so that this table can only contain one row.  See: https://cloudoki.com/database-singleton-table/
</blockquote></details>

Cool, I didn't know about that. Done.

**Review by gbrodman — COMMENTED** [review]
Oh, I should also note that I ran the JPA demo pipeline in Crash with this change (and schema) and it showed up green

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269#-:-MgkXFFl9c9kD1-g8okh:beojvku)* status: 0 of 36 files reviewed, 4 unresolved discussions (waiting on @CydeWeys)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 36 files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[db/src/main/resources/sql/flyway/V100__database_migration_schedule.sql, line 15 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkF_jV1k0SqOCkz95p:-MgllzE_9CnEsafYc9DK:b-8rp19i) ([raw file](https://github.com/google/nomulus/blob/a3eb472386567736753a18eb5bcde4ef6126c0e3/db/src/main/resources/sql/flyway/V100__database_migration_schedule.sql#L15)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Cool, I didn't know about that. Done. 
</blockquote></details>

Yeah I didn't either, I just figured there had to be a pattern for a singleton table, and sure enough, there was!

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 36 files reviewed, 5 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 47 at r3](https://reviewable.io/reviews/google/nomulus/1269#-MgnRvIW2-eZ9Z20fuNc:-MgnRvIX8ru22_qQgiOZ:b-g7lxfr) ([raw file](https://github.com/google/nomulus/blob/2f1d89468fc0e9491473f8c04cd81b8788f28483/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L47)):*
> ```
> DatabaseMigrationStateSchedule
> ```
We should add a DatabaseMigrationStateSchedule test to the SqlIntegrationTestSuite, and document it here. That way schema mismatch with this entity can be detected.

While you are at it, could you add TransactionTest to SqlIntegrationTestSuite too, and update the comments about TransactionEntity below? TransactionEntity also got removed by tests so cannot be verified here, but we should include its test in the suite.
___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 49 at r3](https://reviewable.io/reviews/google/nomulus/1269#-MgnSMYZCUF-k4WGUeG5:-MgnSMYZCUF-k4WGUeG6:b-inr2n) ([raw file](https://github.com/google/nomulus/blob/2f1d89468fc0e9491473f8c04cd81b8788f28483/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L49)):*
> ```
>           "DelegationSignerData",
>           "DesignatedContact",
>           "GracePeriod",
> ```
These three and RegistrarContact below it, can be deleted now.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 38 files reviewed, 5 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 47 at r3](https://reviewable.io/reviews/google/nomulus/1269#-MgnRvIW2-eZ9Z20fuNc:-MgpyWWcE1UYg9H1QRzS:b-qvt6yf) ([raw file](https://github.com/google/nomulus/blob/2f1d89468fc0e9491473f8c04cd81b8788f28483/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L47)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> DatabaseMigrationStateSchedule
> ```
We should add a DatabaseMigrationStateSchedule test to the SqlIntegrationTestSuite, and document it here. That way schema mismatch with this entity can be detected.

While you are at it, could you add TransactionTest to SqlIntegrationTestSuite too, and update the comments about TransactionEntity below? TransactionEntity also got removed by tests so cannot be verified here, but we should include its test in the suite.
</blockquote></details>

Done with the database migration schedule -- now, instead of deleting the entity we just reset it to the default after every test that uses it. 

I'm not doing the TransactionTest / TransactionEntity changes as those require significant changes and fixes -- the coverage extension requires that we're running against a standard DB saving standard objects and as far as I'm aware, the replay doesn't work quite properly yet for standard objects' create/update auto timestamps. I filed https://b.corp.google.com/issues/196226502, but I tried to get this to work for a bit today to no avail. This seems like a bigger task. 
___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 49 at r3](https://reviewable.io/reviews/google/nomulus/1269#-MgnSMYZCUF-k4WGUeG5:-MgpzCSkEE8fXXKc98_S:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2f1d89468fc0e9491473f8c04cd81b8788f28483/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L49)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>           "DelegationSignerData",
>           "DesignatedContact",
>           "GracePeriod",
> ```
These three and RegistrarContact below it, can be deleted now.
</blockquote></details>

Done.

**Review by weiminyu — APPROVED** [review]
> Reviewed 2 of 13 files at r3, 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 3 of 38 files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 3 of 38 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 46 at r4](https://reviewable.io/reviews/google/nomulus/1269#-MgqWNKtC8xWSp9dwG7h:-MgqWNKtC8xWSp9dwG7i:b-xbio21) ([raw file](https://github.com/google/nomulus/blob/37ac6e2e97b15fcf079ae65d9d62077c4df63c74/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L46)):*
> ```
> "DatabaseMigrationStateSchedule",
> ```
If we don't delete this anymore, do we still need to ignore it here?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 2 of 40 files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 46 at r4](https://reviewable.io/reviews/google/nomulus/1269#-MgqWNKtC8xWSp9dwG7h:-Mgq_iBQ83D7UtVzQE01:b5zld0v) ([raw file](https://github.com/google/nomulus/blob/37ac6e2e97b15fcf079ae65d9d62077c4df63c74/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L46)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> "DatabaseMigrationStateSchedule",
> ```
If we don't delete this anymore, do we still need to ignore it here?
</blockquote></details>

Yeah I think it mistakenly snuck back in. Fixed.

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 2 of 40 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @weiminyu)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 2 of 40 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @weiminyu)

___
*[-- commits, line 1 at r5](https://reviewable.io/reviews/google/nomulus/1269#-Mgqf3b-DPqfVHnP2qrT:-Mgqf3b-DPqfVHnP2qrU:bkwjkcj) ([raw file](https://github.com/google/nomulus/blob/f12d11087d4f4927a33aff9f03565fa2ea8a85f5/-- commits#L1)):*
Well look what we have here ...

Turn-about is fair play, no?  :D
___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java, line 47 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkG89I6Btdp9rH4MfM:-MgqfCId7Nxh-he_d3L3:bpqwkao) ([raw file](https://github.com/google/nomulus/blob/a3eb472386567736753a18eb5bcde4ef6126c0e3/core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java#L47)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Nah that process only applies to changes of existing schema where we don't want to lose data. For adding things, it's totally fine to do both in one
</blockquote></details>

Was this resolved with Weimin yet?  It seemed to be his understanding as well that the schema should be added separately and before the code that relies on it.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 2 of 40 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @gbrodman, @sarahcaseybot, and @weiminyu)

___
*[core/src/test/resources/google/registry/export/crosstld_kinds.txt, line 4 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkGb554LvE1LbKb2_a:-MgqfQ3w2Og9BG9t65Ew:b2u9suj) ([raw file](https://github.com/google/nomulus/blob/9811cdb85c5cd184386ee665b46dec186f868b2b/core/src/test/resources/google/registry/export/crosstld_kinds.txt#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

responded above
</blockquote></details>

Even ignoring the issue above, I definitely don't see how it's safe to switch over from Datastore to Cloud SQL in a single go like this -- it's quite susceptible to breakage during a deployment.  It seems to me like Cloud SQL needs to be added, then have some kind of dual-read with fallback, and then only subsequently can Datastore be removed.  @sarahcaseybot used this pattern many times for the synchronous migrations.

The only way it's safe to just abruptly change it like this without a rollback-resistant fallback would be if it's still completely unused in the live code -- is it?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 2 of 40 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @sarahcaseybot, and @weiminyu)

___
*[-- commits, line 1 at r5](https://reviewable.io/reviews/google/nomulus/1269#-Mgqf3b-DPqfVHnP2qrT:-Mgv-xUp-Hoj8RiQlDTX:b-aebvsg) ([raw file](https://github.com/google/nomulus/blob/f12d11087d4f4927a33aff9f03565fa2ea8a85f5/-- commits#L1)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Well look what we have here ...

Turn-about is fair play, no?  :D
</blockquote></details>

har har har :P 
___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java, line 47 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkG89I6Btdp9rH4MfM:-Mgv-tOC5dMzPYL-CQlU:b-b7ruda) ([raw file](https://github.com/google/nomulus/blob/a3eb472386567736753a18eb5bcde4ef6126c0e3/core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java#L47)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Was this resolved with Weimin yet?  It seemed to be his understanding as well that the schema should be added separately and before the code that relies on it.
</blockquote></details>

Yes, this is done and the schema has been added and deployed. We should be good to go. 
___
*[core/src/test/resources/google/registry/export/crosstld_kinds.txt, line 4 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkGb554LvE1LbKb2_a:-Mgv0Lp48cSI2_MLQoIt:b-7h085l) ([raw file](https://github.com/google/nomulus/blob/9811cdb85c5cd184386ee665b46dec186f868b2b/core/src/test/resources/google/registry/export/crosstld_kinds.txt#L4)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Even ignoring the issue above, I definitely don't see how it's safe to switch over from Datastore to Cloud SQL in a single go like this -- it's quite susceptible to breakage during a deployment.  It seems to me like Cloud SQL needs to be added, then have some kind of dual-read with fallback, and then only subsequently can Datastore be removed.  @sarahcaseybot used this pattern many times for the synchronous migrations.

The only way it's safe to just abruptly change it like this without a rollback-resistant fallback would be if it's still completely unused in the live code -- is it?
</blockquote></details>

The schema has been deployed so we should be good to go. If the object doesn't exist in SQL, we just treat that as the uninitialized state of things and start in DATASTORE_ONLY mode, which is exactly what we want to happen.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 2 of 40 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @sarahcaseybot, and @weiminyu)

___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 44 at r6](https://reviewable.io/reviews/google/nomulus/1269#-Mgv2E7XAuRYpoYcxrTZ:-Mgv2E7Y2w-qCxdkZDUu:b-26aio4) ([raw file](https://github.com/google/nomulus/blob/cdf95a867f2f7b2e1a2836d3c410e41d483bdeec/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L44)):*
> ```Java
>   private static final ImmutableSet<String> IGNORE_ENTITIES =
>       ImmutableSet.of(
>           // DatabaseMigrationStateSchedule is persisted in tests, however any test that sets it
> ```

Unfortunately we must include this here for now -- I got this PR mixed up with the read-only code which will allow us to remove this.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, 2 unresolved discussions (waiting on @gbrodman, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java, line 233 at r7](https://reviewable.io/reviews/google/nomulus/1269#-Mgvx4-D6QMrHWzSlApN:-Mgvx4-D6QMrHWzSlApO:bk80arr) ([raw file](https://github.com/google/nomulus/blob/3f903d384e030f1a262c4ad5856195f621631800/core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java#L233)):*
> ```Java
>               } catch (PersistenceException e) {
>                 logger.atWarning().withCause(e).log(
>                     "Error when retrieving migration schedule; this should only happen in tests.");
> ```

If this should only happen in tests then it should be `SEVERE` on production, no?  Or maybe throw an exception for real in a non-testing environment?  It feels like this should be checking the current environment.

Why is this happening in tests anyway?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @sarahcaseybot, and @weiminyu)

___
*[core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java, line 233 at r7](https://reviewable.io/reviews/google/nomulus/1269#-Mgvx4-D6QMrHWzSlApN:-Mgw6cGG-S5wttdx6dUI:b77b5sl) ([raw file](https://github.com/google/nomulus/blob/3f903d384e030f1a262c4ad5856195f621631800/core/src/main/java/google/registry/model/common/DatabaseMigrationStateSchedule.java#L233)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

If this should only happen in tests then it should be `SEVERE` on production, no?  Or maybe throw an exception for real in a non-testing environment?  It feels like this should be checking the current environment.

Why is this happening in tests anyway?
</blockquote></details>

Yeah, we can check the environment. It's happening because there ends up being some race conditions / overlap when setting up / tearing down the SQL environment in various tests.

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot and @weiminyu)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, 1 unresolved discussion (waiting on @sarahcaseybot and @weiminyu)

___
*[core/src/test/resources/google/registry/export/crosstld_kinds.txt, line 4 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkGb554LvE1LbKb2_a:-Mgw7MaC0rBtJUsQE2Sz:bh8g8on) ([raw file](https://github.com/google/nomulus/blob/9811cdb85c5cd184386ee665b46dec186f868b2b/core/src/test/resources/google/registry/export/crosstld_kinds.txt#L4)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

The schema has been deployed so we should be good to go. If the object doesn't exist in SQL, we just treat that as the uninitialized state of things and start in DATASTORE_ONLY mode, which is exactly what we want to happen. 
</blockquote></details>

Well actually now it'll error out, will it not?

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, all discussions resolved (waiting on @weiminyu)

___
*[core/src/test/resources/google/registry/export/crosstld_kinds.txt, line 4 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkGb554LvE1LbKb2_a:-Mgw7dhfCcdZ8DON2ZkU:b-ew3tc) ([raw file](https://github.com/google/nomulus/blob/9811cdb85c5cd184386ee665b46dec186f868b2b/core/src/test/resources/google/registry/export/crosstld_kinds.txt#L4)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Well actually now it'll error out, will it not?
</blockquote></details>

Never mind, `loadSingleton()` is OK if there are no rows in the table.  It'll only error out if there's _more_ than 1 row.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, all discussions resolved (waiting on @weiminyu)

___
*[core/src/test/resources/google/registry/export/crosstld_kinds.txt, line 4 at r1](https://reviewable.io/reviews/google/nomulus/1269#-MgkGb554LvE1LbKb2_a:-Mgw7m-W9wvJCGKk8iKk:bpqcbia) ([raw file](https://github.com/google/nomulus/blob/9811cdb85c5cd184386ee665b46dec186f868b2b/core/src/test/resources/google/registry/export/crosstld_kinds.txt#L4)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Never mind, `loadSingleton()` is OK if there are no rows in the table.  It'll only error out if there's _more_ than 1 row.
</blockquote></details>

Right, or if it can't find the table at all (that's the error that occurs in some unit tests if there's a race condition)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, all discussions resolved (waiting on @weiminyu)

___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 44 at r6](https://reviewable.io/reviews/google/nomulus/1269#-Mgv2E7XAuRYpoYcxrTZ:-Mgw7qmb4Zk51ERhkP9j:b3xpr69) ([raw file](https://github.com/google/nomulus/blob/cdf95a867f2f7b2e1a2836d3c410e41d483bdeec/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L44)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Unfortunately we must include this here for now -- I got this PR mixed up with the read-only code which will allow us to remove this. 
</blockquote></details>

Explicitly make this a TODO then?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, all discussions resolved (waiting on @weiminyu)

___
*[core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java, line 44 at r6](https://reviewable.io/reviews/google/nomulus/1269#-Mgv2E7XAuRYpoYcxrTZ:-Mgw8C1eA_kzR6FiGr29:bb74ce2) ([raw file](https://github.com/google/nomulus/blob/cdf95a867f2f7b2e1a2836d3c410e41d483bdeec/core/src/test/java/google/registry/persistence/transaction/JpaEntityCoverageExtension.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Explicitly make this a TODO then?
</blockquote></details>

Sure

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @weiminyu)

___
*[db/src/main/resources/sql/schema/db-schema.sql.generated, line 241 at r9](https://reviewable.io/reviews/google/nomulus/1269#-MgwEw5d2ekNLuTPRi2x:-MgwEw5d2ekNLuTPRi2y:b-so3k36) ([raw file](https://github.com/google/nomulus/blob/a8b67a31256dc6fa23455763c1ff2bce727e5377/db/src/main/resources/sql/schema/db-schema.sql.generated#L241)):*
> ```
>     );
> 
>     create table "DatabaseMigrationStateSchedule" (
> ```

Shouldn't this not be here given that the schema was already committed and deployed?

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269#-:-MgwGOq12r_s-GtCr9Ez:bnfp4nl)* status: 0 of 41 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @weiminyu)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1269)* status: 0 of 41 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[db/src/main/resources/sql/schema/db-schema.sql.generated, line 241 at r9](https://reviewable.io/reviews/google/nomulus/1269#-MgwEw5d2ekNLuTPRi2x:-MgwMbo70icB4RGgbVob:b-vz7ehh) ([raw file](https://github.com/google/nomulus/blob/a8b67a31256dc6fa23455763c1ff2bce727e5377/db/src/main/resources/sql/schema/db-schema.sql.generated#L241)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Shouldn't this not be here given that the schema was already committed and deployed?
</blockquote></details>

Nah, this is what's generated from the Java code which goes in here

**Pull request merged**
