### PR TITLE
Convert HostResourceTest to work with Cloud SQL

### PR DESCRIPTION
**Pull request by hstonec**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/905)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/905)* status: all files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 754 at r1](https://reviewable.io/reviews/google/nomulus/905#-MOHMqgfBoaj6QkY7YoB:-MOHMqgfBoaj6QkY7YoC:b8wpq9b) ([raw file](https://github.com/google/nomulus/blob/5f743c7fe1bc8439089229f080ab51407dc13f65/core/src/test/java/google/registry/testing/DatabaseHelper.java#L754)):*
> ```Java
> 
>   /** Persists and returns a {@link Registrar} with the specified registrarId. */
>   public static Registrar persistNewRegistrar(String registrarId) {
> ```

Just call the other persistNewRegistrar()?

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/905)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/test/java/google/registry/testing/DatabaseHelper.java, line 754 at r1](https://reviewable.io/reviews/google/nomulus/905#-MOHMqgfBoaj6QkY7YoB:-MOHTiZL5Vox3ltbHnNX:b-896fix) ([raw file](https://github.com/google/nomulus/blob/5f743c7fe1bc8439089229f080ab51407dc13f65/core/src/test/java/google/registry/testing/DatabaseHelper.java#L754)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Just call the other persistNewRegistrar()?
</blockquote></details>

Done.

**Review by mindhog — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/905)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by mindhog — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/905#-:-MOHXCmLBVZOdQzspRIO:bb6ywmx)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Pull request merged**
