### PR TITLE
Add simple registry-lock-verification page

### PR DESCRIPTION
**Pull request by gbrodman**
This is a fairly simple page that solely exists to display the result from the action, and to link the user back to the domain list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2499)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2499)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/lock/registryLockVerify.component.html` line 7 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2PsNwF6Zm-OM-sY8WH:-O2PsNwF6Zm-OM-sY8WI:bemipti) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.html#L7)):*
> ```HTML
>     <mat-spinner />
>   </div>
>   } @else {
> ```

This assumes that the response is always successful. What if the request failed for one reason or another?
___
*[`console-webapp/src/app/lock/registryLockVerify.component.scss` line 2 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2Ps_MD95w8fqGBeV9t:-O2Ps_MD95w8fqGBeV9u:bo3tsk5) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.scss#L2)):*
> ```SCSS
> .console-app__registry-lock {
>   > div {
> ```

I'd probably make it a little more specific. All direct child divs is a bit too broad and can make any future changes more difficult 
___
*[`console-webapp/src/app/lock/registryLockVerify.component.ts` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2Pt83D9_Ut421S9Lno:-O2Pt83D9_Ut421S9Lnp:b-yuw0jr) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.ts#L43)):*
> ```XML
> 
>   ngOnInit() {
>     this.route.queryParamMap.subscribe((params: ParamMap) => {
> ```

I think we should make it one time subsription - `take(1)` I believe should do it
___
*[`console-webapp/src/app/lock/registryLockVerify.component.ts` line 63 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2PuPvn-SA_pFaNCOV7:-O2PuPvn-SA_pFaNCOV8:bvnys9y) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.ts#L63)):*
> ```XML
> 
>   domainListUrl() {
>     return `/#/domain-list?registrarId=${this.registrarService.registrarId()}`;
> ```

Have you tested it locally or on alpha? I don't think that's supposed to work. You probably need something like `createUrlTree`

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2499)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/lock/registryLockVerify.component.html` line 7 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2PsNwF6Zm-OM-sY8WH:-O2QtTYr9JVlvKOBTr-E:b-n3z39b) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.html#L7)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

This assumes that the response is always successful. What if the request failed for one reason or another?
</blockquote></details>

yeah you're right 
___
*[`console-webapp/src/app/lock/registryLockVerify.component.scss` line 2 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2Ps_MD95w8fqGBeV9t:-O2QodWP9OqjxA2byZfs:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.scss#L2)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I'd probably make it a little more specific. All direct child divs is a bit too broad and can make any future changes more difficult
</blockquote></details>

Done.
___
*[`console-webapp/src/app/lock/registryLockVerify.component.ts` line 43 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2Pt83D9_Ut421S9Lno:-O2QXcdH7vfEha6qwZRR:b-896fix) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.ts#L43)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I think we should make it one time subsription - `take(1)` I believe should do it
</blockquote></details>

Done.
___
*[`console-webapp/src/app/lock/registryLockVerify.component.ts` line 63 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2PuPvn-SA_pFaNCOV7:-O2QT9ti3v7kZQ9YpzMC:bubss1l) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.ts#L63)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Have you tested it locally or on alpha? I don't think that's supposed to work. You probably need something like `createUrlTree`
</blockquote></details>

locally yes, alpha no. It worked locally. 

if the URL is `http://localhost:4200/#/registry-lock-verify?lockVerificationCode=foobar` then returning a fake "valid" response from the backend means the domains-list link is `http://localhost:4200/#/domain-list?registrarId=TheRegistrar`

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2499)* status: 4 of 9 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`console-webapp/src/app/lock/registryLockVerify.component.ts` line 63 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2PuPvn-SA_pFaNCOV7:-O2R1CKq5xfguH9TxFR6:b-bemfhl) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.ts#L63)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

locally yes, alpha no. It worked locally. 

if the URL is `http://localhost:4200/#/registry-lock-verify?lockVerificationCode=foobar` then returning a fake "valid" response from the backend means the domains-list link is `http://localhost:4200/#/domain-list?registrarId=TheRegistrar`
</blockquote></details>

Yeah, but non-local environment has different base path and that's done so that proper service can intercept and serve the request - `/console/#/home` for example. Notice "console" part which is not present locally.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2499)* status: 4 of 9 files reviewed, 5 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/lock/registryLockVerify.component.ts` line 20 at r2](https://reviewable.io/reviews/google/nomulus/2499#gh-1687058653:-O2RETGhEE82ItSWbTVu:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4c2352d04181cbb8655f96743b2b0bc880500d56/console-webapp/src/app/lock/registryLockVerify.component.ts#L20)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import MatSnackBar.

[Show more details](https://github.com/google/nomulus/security/code-scanning/12424)
</blockquote></details>

Done.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2499)* status: 4 of 9 files reviewed, 5 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/lock/registryLockVerify.component.ts` line 63 at r1](https://reviewable.io/reviews/google/nomulus/2499#-O2PuPvn-SA_pFaNCOV7:-O2RMZF2-UT04RvNxHVQ:b-wxbt0r) ([raw file](https://github.com/google/nomulus/blob/7907099aa09b0ceb2195fb207d80082419a4f85b/console-webapp/src/app/lock/registryLockVerify.component.ts#L63)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Yeah, but non-local environment has different base path and that's done so that proper service can intercept and serve the request - `/console/#/home` for example. Notice "console" part which is not present locally.
</blockquote></details>

hm yeah true -- turns out, the solution is even better than createUrlTree. 

This solution works both locally and on alpha

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 3 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2499)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`console-webapp/src/app/lock/registryLockVerify.component.html` line 15 at r3](https://reviewable.io/reviews/google/nomulus/2499#-O2VAweXD-CyB1cyaSJu:-O2VAweXD-CyB1cyaSJv:bg6394u) ([raw file](https://github.com/google/nomulus/blob/85c64423a059eb34e19ab74805a3e59ac8457601/console-webapp/src/app/lock/registryLockVerify.component.html#L15)):*
> ```HTML
>   <a
>     class="text-l"
>     routerLink="/domain-list"
> ```

Perfect, ideally though we'd want this to use PATH from DomainListComponent

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2499)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @github-advanced-security[bot] and @ptkach)

___
*[`console-webapp/src/app/lock/registryLockVerify.component.html` line 15 at r3](https://reviewable.io/reviews/google/nomulus/2499#-O2VAweXD-CyB1cyaSJu:-O2Vbjr7BvkxbeK9LAt3:bf34aze) ([raw file](https://github.com/google/nomulus/blob/85c64423a059eb34e19ab74805a3e59ac8457601/console-webapp/src/app/lock/registryLockVerify.component.html#L15)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Perfect, ideally though we'd want this to use PATH from DomainListComponent
</blockquote></details>

Unfortunately we cannot refer to it directly, but we can refer to it indirectly

**Review by ptkach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2499)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`console-webapp/src/app/lock/registryLockVerify.component.html` line 15 at r3](https://reviewable.io/reviews/google/nomulus/2499#-O2VAweXD-CyB1cyaSJu:-O2Vf9hpDw073beVHU2k:bdowu5q) ([raw file](https://github.com/google/nomulus/blob/85c64423a059eb34e19ab74805a3e59ac8457601/console-webapp/src/app/lock/registryLockVerify.component.html#L15)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Unfortunately we cannot refer to it directly, but we can refer to it indirectly
</blockquote></details>

Yeah, that's exactly what I meant. You can't access static variable or any variables at all from other components from angular template, otherwise it'd be quite difficult for angular to track changes ;)

**Pull request merged**
