### PR TITLE
Add unique constraints on domain_hosts

### PR DESCRIPTION
**Pull request by weiminyu**
Add unique constraints on DomainHost (child of DomainBase) and
DomainHistoryHost (child of DomainHistory). DomainHost is non-entity
embedded object and Hibernate does not define indexes automatically.

This should improve read and write performance of the parent entities.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/911)

### CODE REVIEW

**Review by CydeWeys — COMMENTED** [review]
Ooooof, does the lack of an index on that table explain a lot of the performance issues?  That would totally make sense if it had been table scanning.  If so, good find.

How did you find this?  Query performance analyzer?  Any kind of procedure you can share with the rest of the team?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/911#-:-MP5R8ii2MmxUmlHrKNa:b-t5hi69)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @CydeWeys, @gbrodman, and @hstonec)

**Review by gbrodman — COMMENTED** [review]
Yeah, how'd you find this? And does adding a unique constraint imply an index creation (i'm assuming so)?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/911#-:-MP5wS5mBxN5s_TmQq6_:bxx94sx)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @CydeWeys, @gbrodman, @hstonec, and @mindhog)

**Review by CydeWeys — COMMENTED** [review]
Yes, this implicitly creates the index.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/911#-:-MP5xmKr-8HenIupBt4i:b-7bdj62)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @CydeWeys, @hstonec, and @mindhog)

**Review by weiminyu — COMMENTED** [review]
I eyeballed the schema of Domain's child tables in psql first and verified with explain afterwards.

One gotcha: 'explain insert' is not useful since the output doesn't mention indexes. Use explain with select or update statements instead.

Interesting finding: scanning an empty table is a LOT slower than looking up an empty index. Presumably the index is in memory. The index on "DomainHistoryHost" allows a 9x speedup of HistoryEntry insertion even though nothing was written.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/911#-:-MP6-y_t-vfIqkPsfWjM:b-pa499a)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @CydeWeys, @hstonec, and @mindhog)

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/911#-:-MP69H_Q8SnTeGW_flud:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @hstonec and @mindhog)

**Pull request merged**
