### PR TITLE
Add new registrar screen to the console

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2469)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2469)* status: all files reviewed, 4 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/registrar/newRegistrar.component.html` line 26 at r1](https://reviewable.io/reviews/google/nomulus/2469#-NzcsKg61ATh-xsKnrDc:-NzcsKg61ATh-xsKnrDd:berxzzm) ([raw file](https://github.com/google/nomulus/blob/bb37a4bed45cde7348dba2c3e51006ccbd4d705a/console-webapp/src/app/registrar/newRegistrar.component.html#L26)):*
> ```HTML
>     <section>
>       <mat-form-field appearance="outline">
>         <mat-label>Client ID: </mat-label>
> ```

I think we should probably go with "Registrar ID" here, we've been trying to migrate to using that over clientId over time 
___
*[`console-webapp/src/app/registrar/newRegistrar.component.html` line 37 at r1](https://reviewable.io/reviews/google/nomulus/2469#-NzcsVzf2QQcUibToKma:-NzcsVzf2QQcUibToKmb:bwxtdz8) ([raw file](https://github.com/google/nomulus/blob/bb37a4bed45cde7348dba2c3e51006ccbd4d705a/console-webapp/src/app/registrar/newRegistrar.component.html#L37)):*
> ```HTML
>     <section>
>       <mat-form-field appearance="outline">
>         <mat-label>Registrar Console Username: </mat-label>
> ```

this is not correct; the console will have individual users. This is the registrar email address 
___
*[`console-webapp/src/app/registrar/newRegistrar.component.html` line 152 at r1](https://reviewable.io/reviews/google/nomulus/2469#-NzcsqlLAp0m0AzJR-Er:-NzcsqlLAp0m0AzJR-Es:bfyqoxs) ([raw file](https://github.com/google/nomulus/blob/bb37a4bed45cde7348dba2c3e51006ccbd4d705a/console-webapp/src/app/registrar/newRegistrar.component.html#L152)):*
> ```HTML
>     <section>
>       <mat-form-field appearance="outline">
>         <mat-label>Zip/postal code: </mat-label>
> ```

ZIP should be entirely capitalized (Zone Improvement Plan) 

Also we should probably title-case Postal Code here and Region above, similar to how we do Country Code
___
*[`console-webapp/src/app/registrar/newRegistrar.component.ts` line 73 at r1](https://reviewable.io/reviews/google/nomulus/2469#-NzctMASDXtevA1Oogpk:-NzctMASDXtevA1Oogpl:b-88aw7q) ([raw file](https://github.com/google/nomulus/blob/bb37a4bed45cde7348dba2c3e51006ccbd4d705a/console-webapp/src/app/registrar/newRegistrar.component.ts#L73)):*
> ```XML
>       );
>       this.registrarService.saveRegistrar(this.newRegistrar).subscribe({
>         complete: () => {
> ```

out of curiosity is it possible to use a method reference directly like we can do in Java? e.g. like in Java this would be `complete: this::goBack`

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2469)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/registrar/newRegistrar.component.html` line 26 at r1](https://reviewable.io/reviews/google/nomulus/2469#-NzcsKg61ATh-xsKnrDc:-Nzd6LsGEIYU94Uz09TG:b-896fiz) ([raw file](https://github.com/google/nomulus/blob/bb37a4bed45cde7348dba2c3e51006ccbd4d705a/console-webapp/src/app/registrar/newRegistrar.component.html#L26)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we should probably go with "Registrar ID" here, we've been trying to migrate to using that over clientId over time
</blockquote></details>

Done,
___
*[`console-webapp/src/app/registrar/newRegistrar.component.html` line 37 at r1](https://reviewable.io/reviews/google/nomulus/2469#-NzcsVzf2QQcUibToKma:-Nzd6Piy43vUopQCqLRx:b-w3xwkg) ([raw file](https://github.com/google/nomulus/blob/bb37a4bed45cde7348dba2c3e51006ccbd4d705a/console-webapp/src/app/registrar/newRegistrar.component.html#L37)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this is not correct; the console will have individual users. This is the registrar email address
</blockquote></details>

Done, I used to have it as in old console
___
*[`console-webapp/src/app/registrar/newRegistrar.component.html` line 152 at r1](https://reviewable.io/reviews/google/nomulus/2469#-NzcsqlLAp0m0AzJR-Er:-Nzd6Ubl2cgm6DAaDlmA:b-896fix) ([raw file](https://github.com/google/nomulus/blob/bb37a4bed45cde7348dba2c3e51006ccbd4d705a/console-webapp/src/app/registrar/newRegistrar.component.html#L152)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ZIP should be entirely capitalized (Zone Improvement Plan) 

Also we should probably title-case Postal Code here and Region above, similar to how we do Country Code
</blockquote></details>

Done.
___
*[`console-webapp/src/app/registrar/newRegistrar.component.ts` line 73 at r1](https://reviewable.io/reviews/google/nomulus/2469#-NzctMASDXtevA1Oogpk:-Nzd6VEr5QaBRY-IvUWS:b-hwqd2z) ([raw file](https://github.com/google/nomulus/blob/bb37a4bed45cde7348dba2c3e51006ccbd4d705a/console-webapp/src/app/registrar/newRegistrar.component.ts#L73)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

out of curiosity is it possible to use a method reference directly like we can do in Java? e.g. like in Java this would be `complete: this::goBack`
</blockquote></details>

Well yes and no. Yes - it's possible as JS is a functional first language, long before java was, but no - it doesn't work in our case (at least in a simple way) because in js you have to take care of the context (`this`).  If written in a straightforward way - `complete: this.onBack` it will call `onBack` not with the context of newRegistrar instance, which in turn will fail inside the `onBack`.
 In order for it to work it has be either binded, like `complete: this.onBack.bind(this)` or wrapped in lambda (in js it's called arrow function). The latter is used far more frequently these days.

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2469)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

___
*[`console-webapp/src/app/registrar/newRegistrar.component.ts` line 73 at r1](https://reviewable.io/reviews/google/nomulus/2469#-NzctMASDXtevA1Oogpk:-NzdY8GQ-uzknIWCd9x9:b-cvdoti) ([raw file](https://github.com/google/nomulus/blob/bb37a4bed45cde7348dba2c3e51006ccbd4d705a/console-webapp/src/app/registrar/newRegistrar.component.ts#L73)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Well yes and no. Yes - it's possible as JS is a functional first language, long before java was, but no - it doesn't work in our case (at least in a simple way) because in js you have to take care of the context (`this`).  If written in a straightforward way - `complete: this.onBack` it will call `onBack` not with the context of newRegistrar instance, which in turn will fail inside the `onBack`.
 In order for it to work it has be either binded, like `complete: this.onBack.bind(this)` or wrapped in lambda (in js it's called arrow function). The latter is used far more frequently these days.
</blockquote></details>

Got it yeah, the binding is necessary

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2469)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
