### PR TITLE
Remove the mention of ofy in most places

### PR DESCRIPTION
**Pull request by jianglai**
There are still some mentions of ofy after this PR, but mostly in places
that would need to be modified later anyway.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1872)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1872)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/config/files/nomulus-config-unittest.yaml` line 14 at r1](https://reviewable.io/reviews/google/nomulus/1872#-NIi-KRf7s7JbDR21irt:-NIi-KRf7s7JbDR21iru:bhzlwgi) ([raw file](https://github.com/google/nomulus/blob/342ae7a5de4a76f609dc405c9940284d6f3fa7cd/core/src/main/java/google/registry/config/files/nomulus-config-unittest.yaml#L14)):*
> ```YAML
> 
> datastore:
>   eppResourceIndexBucketsNum: 3
> ```

I think the version in nomulus-internal also has this block and needs update too.



_Code quote:_
```YAML
datastore:
  eppResourceIndexBucketsNum: 3
  baseOfyRetryMillis: 0
```

**Comment by jianglai** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1872)_ status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @jianglai)
> 
> _[`core/src/main/java/google/registry/config/files/nomulus-config-unittest.yaml` line 14 at r1](https://reviewable.io/reviews/google/nomulus/1872#-NIi-KRf7s7JbDR21irt:-NIi-KRf7s7JbDR21iru:bhzlwgi) ([raw file](https://github.com/google/nomulus/blob/342ae7a5de4a76f609dc405c9940284d6f3fa7cd/core/src/main/java/google/registry/config/files/nomulus-config-unittest.yaml#L14)):_
> 
> > ```yaml
> > datastore:
> >   eppResourceIndexBucketsNum: 3
> > ```
> 
> I think the version in nomulus-internal also has this block and needs update too.
> 
> _Code quote:_
> 
> ```yaml
> datastore:
>   eppResourceIndexBucketsNum: 3
>   baseOfyRetryMillis: 0
> ```

I checked and there's no override in the internal repo.

**Review by jianglai — COMMENTED** [review]
Gentle ping. Making sure the ball is out of my court.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1872#-:-NIo9js662sXwsnquYTC:b-orqj9g)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1872)* status: 0 of 10 files reviewed, all discussions resolved

**Pull request merged**
