### PR TITLE
Validate SQL with Datastore being Primary

### PR DESCRIPTION
**Pull request by weiminyu**
Validates asynchronously replicated data in SQL from Datastore which is the primary data source.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1436)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 20 of 25 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1436)* status: all files reviewed, 7 unresolved discussions (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/beam/comparedb/SqlSnapshots.java, line 137 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpDosqu1Nf2lD3O57Ty:-MpDosqu1Nf2lD3O57Tz:b-hu9nge) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/SqlSnapshots.java#L137)):*
> ```Java
>                 loadContactHistory(pipeline, snapshotId));
>         continue;
>       }
> ```

I presume these can't be collapsed into a single "if" statement because of the typing constraints?
___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlPipelineOptions.java, line 20 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpH92244qGGZ08QjFD8:-MpH92244qGGZ08QjFD9:b52ungw) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/ValidateSqlPipelineOptions.java#L20)):*
> ```Java
> 
> /** BEAM pipeline options for {@link ValidateSqlPipeline}. */
> public interface ValidateSqlPipelineOptions extends RegistryPipelineOptions {}
> ```

Is there a reason not to just use RegistryPipelineOptions for this?  Is it purely for naming consistency?
___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java, line 66 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpH9l505II_PkNf7wVp:-MpH9l505II_PkNf7wVq:bt0pjbn) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java#L66)):*
> ```
> slightly better 
> ```

Faster?  Or better in some other way?
___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java, line 230 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpHKOA52MylHFE_t55t:-MpHKOA52MylHFE_t55u:b87qzdk) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java#L230)):*
> ```Java
>             && authInfo.getPw().getRepoId() == null
>             && authInfo.getPw().getValue() == null) {
>           authField.set(eppResource, null);
> ```

Any reason not to just always make this field null?  A comment would be helpful here.
___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java, line 270 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpHM8qq8OinXU0YcMc4:-MpHM8qq8OinXU0YcMc5:b-hw10ad) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java#L270)):*
> ```Java
>         hostBase.setAccessible(true);
>         hostBase.set(historyEntry, null);
>       }
> ```

I'm confused as to why we're nulling out the content objects, here (though I get that history objects are weird).  But don't we want to compare the contents at given history revisions?
___
*[core/src/main/java/google/registry/model/ImmutableObject.java, line 162 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpHNd_K4muH4yVOOu99:-MpHNd_K4muH4yVOOu9A:b1ruyfs) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/model/ImmutableObject.java#L162)):*
> ```Java
>    * <p>This method makes use of {@link #toStringHelper}, which embeds {@link
>    * System#identityHashCode} in the output string. Subclasses that require deterministic string
>    * representations <em>across</em> JVM instances should override this method.
> ```

FWIW, I'd be in favor of removing the identity hashes.  I've never seen a case where it's useful, and it makes it very hard to apply simple textual diffs to debug output.
___
*[core/src/test/java/google/registry/beam/initsql/DatastoreSetupHelper.java, line 74 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpHT-hkEK-kGc-EtnhI:-MpHT-hl6z_U9KV_9Kqt:b-8axmh) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/test/java/google/registry/beam/initsql/DatastoreSetupHelper.java#L74)):*
> ```Java
>   /**
>    * All kinds of entities to be set up in the Datastore. Must contain all kinds known to {@link
>    * InitSqlPipeline}.
> ```

Can we just use the value from InitSqlPipeline?

**Review by weiminyu — COMMENTED** [review]
> Reviewed 24 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1436)* status: all files reviewed, 7 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/beam/comparedb/SqlSnapshots.java, line 137 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpDosqu1Nf2lD3O57Ty:-MphNJ2NDYRpSvkmbO44:b2y4i5p) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/SqlSnapshots.java#L137)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I presume these can't be collapsed into a single "if" statement because of the typing constraints?
</blockquote></details>

I'm not clear why you mean by a single if. Do you mean ternary if?
___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlPipelineOptions.java, line 20 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpH92244qGGZ08QjFD8:-MphOZBx7OoBIkaP3AGT:bsvoevm) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/ValidateSqlPipelineOptions.java#L20)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Is there a reason not to just use RegistryPipelineOptions for this?  Is it purely for naming consistency?
</blockquote></details>

I plan to add more flags to this but haven't gotten around doing it.
___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java, line 66 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpH9l505II_PkNf7wVp:-MphOxIdEHrIk08ZHgQp:b-896fix) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java#L66)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

> ```
> slightly better 
> ```

Faster?  Or better in some other way?
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java, line 230 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpHKOA52MylHFE_t55t:-MphRvYg9CK3FeFhLRtu:b-896fix) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java#L230)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Any reason not to just always make this field null?  A comment would be helpful here.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java, line 270 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpHM8qq8OinXU0YcMc4:-MphRymVCL6WtrATapZP:bt8xdsy) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/ValidateSqlUtils.java#L270)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I'm confused as to why we're nulling out the content objects, here (though I get that history objects are weird).  But don't we want to compare the contents at given history revisions?
</blockquote></details>

History objects from Datastore do not have contents.  Added a note inline.
___
*[core/src/main/java/google/registry/model/ImmutableObject.java, line 162 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpHNd_K4muH4yVOOu99:-MphTFdz5yCiU7qkQbgu:bmxtgjd) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/model/ImmutableObject.java#L162)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

FWIW, I'd be in favor of removing the identity hashes.  I've never seen a case where it's useful, and it makes it very hard to apply simple textual diffs to debug output.
</blockquote></details>

created b/208281598
___
*[core/src/test/java/google/registry/beam/initsql/DatastoreSetupHelper.java, line 74 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpHT-hkEK-kGc-EtnhI:-MphTfQKCH-6cOOAvVqa:bxwjakr) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/test/java/google/registry/beam/initsql/DatastoreSetupHelper.java#L74)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can we just use the value from InitSqlPipeline?
</blockquote></details>

It's a bit messy. InitSqlPipeline has multiple phases so the classes are included in multiple lists. Don't want to expose too much internal info to a test helper.

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1436)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/beam/comparedb/SqlSnapshots.java, line 137 at r2](https://reviewable.io/reviews/google/nomulus/1436#-MpDosqu1Nf2lD3O57Ty:-MpkrlTmEi53MGz2DiSW:bv3hop9) ([raw file](https://github.com/google/nomulus/blob/b5318f83cb303d128fc7263d8f99907634096a2a/core/src/main/java/google/registry/beam/comparedb/SqlSnapshots.java#L137)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

I'm not clear why you mean by a single if. Do you mean ternary if?
</blockquote></details>

I mean:

```
if (clazz == DomainBase.class || clazz == DomainHistory.class || clazz == ContactHistory.class) {
          perTypeSnapshots =
            perTypeSnapshots.and(
                createSqlEntityTupleTag(clazz),
                loadAndAssembleDomainHistory(pipeline, snapshotId));
        continue;
}
```

The code in all three cases is functionally identical, but again I'm not sure if Java's type system will let you get away with this.

**Review by mindhog — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1436)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @weiminyu)

**Pull request merged**
