### PR TITLE
Apply formating change

### PR DESCRIPTION
**Pull request by jianglai**
The formatting tool is making these changes (when running `gradle
jIFA`).

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2069)

### CODE REVIEW

**Review by ptkach — COMMENTED** [review]
I'm not sure where that comes from. I've checked out master and run the command and I'm not getting these changes produced. In fact these changes are not expected, `prettier` tool that we use **removes** commas, not adds them. Are you sure you do not have `eslint` or something of that sort added by Idea?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2069#-:-NZfVH72Eo38dByh9bDS:bturqil)* status: 0 of 7 files reviewed, all discussions resolved

**Comment by jianglai** [comment]
Try running `./gradlew jIFA` in master. It should produce these changes.

**Review by ptkach — CHANGES_REQUESTED** [review]
Added PR - https://github.com/google/nomulus/pull/2070 , which should make console formatting more straightforward  

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2069#-:-NZfZBnk9vWoi90zEjyj:bjj46z5)* status: 0 of 7 files reviewed, all discussions resolved

**Review by ptkach — COMMENTED** [review]
I think we simultaneously added comments. Anyhow, like I said I've tried the command and it gets me no changes. Let's try to merge the PR 2070 and see if it gets the issue resolved for you

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2069#-:-NZf_7bL31n_Ggr-1BtC:bgtpklj)* status: 0 of 7 files reviewed, all discussions resolved

**Review by jianglai — COMMENTED** [review]
Interesting. Maybe some tools installed on my machines is at a different version from yours. I'll try again after #2070 is merged.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2069#-:-NZfcvvJ5fKrjfSLgoUh:bp3luc5)* status: 0 of 7 files reviewed, all discussions resolved

**Comment by jianglai** [comment]
After #2070, running `./gradle jIFA` no longer makes these changes.

**Pull request closed without merging**
