### PR TITLE
Add a command to fix duplicate id issue for BillingEvent.Recurring

### PR DESCRIPTION
**Pull request by hstonec**
This PR added a `DedupeRecurringBillingEventIdsCommand` command to address the duplicate id issue we found for certain `BillingEvent.Recurring` entities. The command reassigns a unique id and also updates any reference in the `Domain` or
`BillingEvent.OneTime` entity.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/798)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/798)* status: 0 of 5 files reviewed, 17 unresolved discussions (waiting on @CydeWeys and @hstonec)

___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 57 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCG6M6BTh5Ry5VNpxu:-MHCG6M6BTh5Ry5VNpxv:b-d6t3h3) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L57)):*
> ```Java
> 
> /**
>  * A MapReduce that re-saves the problematic {@link
> ```

The Javadoc needs a summary explaining exactly what's going on and why it's save.  It needs to cover what's being changed, how, and why it's safe to do so, e.g. we're *sure* that nothing else anywhere beyond what's being changed here is referring to these IDs.

(Also, do past generated invoices refer to these IDs?)
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 58 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCFhoaCay4Y8Ga2PCI:-MHCFhoaCay4Y8Ga2PCJ:b-8skk0p) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L58)):*
> ```Java
> /**
>  * A MapReduce that re-saves the problematic {@link
>  * google.registry.model.billing.BillingEvent.Recurring} entities with unique id.
> ```

"IDs"
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 64 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCGUai54GXwpighr7l:-MHCGUai54GXwpighr7m:b-il7l8x) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L64)):*
> ```Java
>     path = "/_dr/task/resaveRecurringBillingEventWithUniqueId",
>     auth = Auth.AUTH_INTERNAL_OR_ADMIN)
> public class ResaveRecurringBillingEventAction implements Runnable {
> ```

A better name would be `DedupeRecurringBillingEventIdsAction`.  "Resave" just implies that's it's re-saving them as-is, a la `ResaveAllEppResourcesAction`, which is not what's happening here -- this mapreduce is performing a specific action of deduping the entities, not a generic resave, and the specific action of deduping is actually changing the IDs of the entities themselves so it's not really re-saving so much as it is deleting and re-creating, i.e. moving.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 75 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCE2knBUsMFOy9qpWF:-MHCE2knBUsMFOy9qpWG:b-mway4c) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L75)):*
> ```Java
>   @Inject
>   @Parameter(GCS_BUCKET)
>   String gcsBucket;
> ```

Considering this is a one-off scrap mapreduce, what's the point in making the GCS bucket configurable?  Just hard-code the one to use.

Also as written I don't think this will actually work because you haven't written a `@Provides` method anywhere to provide the `GCS_BUCKET` parameter.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 91 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCGMCn5Fz5IIh2XcYC:-MHCGMCn5Fz5IIh2XcYD:b-6b0272) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L91)):*
> ```Java
>   public void run() {
>     mrRunner
>         .setJobName("Re-save problematic BillingEvent.Recurring entities with unique id")
> ```

s/problematic/duplicate/

They're problematic because they're duplicates, so no need to be vague when a better precise word is available.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 115 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCH4Av6meyuleCxi0_:-MHCH4Av6meyuleCxi0a:bmfr3xm) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L115)):*
> ```Java
>       } else if (billingEvent instanceof OneTime) {
>         OneTime oneTime = (OneTime) billingEvent;
>         if (oneTime.getCancellationMatchingBillingEvent() != null) {
> ```

The handling of canceled one times definitely needs a callout in the Javadocs above explaining exactly what's going on.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 122 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCHAK_4VYlCmCyvcbB:-MHCHAK_4VYlCmCyvcbC:bkjnsl5) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L122)):*
> ```Java
>   }
> 
>   /** Mapper to re-save all HistoryEntry entities. */
> ```

This ain't a mapper and it ain't working on HistoryEntries ...
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 142 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCHJhG9mSF_8T_C5Zc:-MHCHJhG9mSF_8T_C5Zd:b-jcbpq4) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L142)):*
> ```Java
>       // If the set is empty or there is only 1 recurring billing event with this id, the recurring
>       // billing event already uses a unique id so we don't need to make any change.
>       if (billingEventInput.getRecurrings().size() <= 1) {
> ```

Use `getContext().incrementCounter(...)` for useful output of exactly what's going on in this case and all others.  See other mapreduces as an example of how to do so.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 159 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCILuOAQPN4dV6m41r:-MHCILuOAQPN4dV6m41s:b-5xzh7n) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L159)):*
> ```Java
>                 "Saved the new BillingEvent.Recurring entity with key %s.\n", newRecurringVKey));
> 
>         updateOneTimeBillingEvent(
> ```

These `update` verbs used in your helper methods are too generic and don't really explain what the methods are actually doing.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 175 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIWJK1b4yDTZ3nQYK:-MHCIWJK1b4yDTZ3nQYL:b6spajf) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L175)):*
> ```Java
>                 () -> {
>                   if (!isDryRun) {
>                     ofy().save().entities(entitiesToSave.build()).now();
> ```

These two `.now()` calls aren't necessary and make the mapreduce slightly less performant because they're requiring multiple server round trips when a single one would do.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 182 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCEeEg-9Q2dH1iZYx6:-MHCEeEg-9Q2dH1iZYx7:b-vnr2a5) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L182)):*
> ```Java
>                           "Deleted the old BillingEvent.Recurring entity with key %s.\n",
>                           oldRecurringVKey));
>                   createGcsFileFromBytes(
> ```

This seems overly complicated here.  Are you just trying to output the changes made?  Is a `logger` not sufficient for some reason?  How many changes are there and how much do we truly care about knowing the details of every single change?  Isn't it more that we know we're done when we run this mapreduce and there's 0 IDs changed?

Also you were going to write out each change to its own file, generating potentially tens of thousands of different individual files?  There's no way we'd ever be able to consume all that information correctly.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 208 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIhaP4ZD8kh8_5H99:-MHCIhaP4ZD8kh8_5H9A:bdwpt3u) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L208)):*
> ```Java
> 
>     /**
>      * Resaves all associated BillingEvent.OneTime entities with the updated
> ```

Three lines is too long for a Javadoc summary fragment.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 209 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIl1jCTCYT0biJfii:-MHCIl1jCTCYT0biJfij:bb8wldn) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L209)):*
> ```Java
>     /**
>      * Resaves all associated BillingEvent.OneTime entities with the updated
>      * cancellationMatchingBillingEvent field pointing to the BillingEvent.Recurring entity with
> ```

Needs some `{@link}` or `<code>` formatting as appropriate.  (Probably the first one.)
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 241 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIu5a9Ou6QIgSYQ6T:-MHCIu5a9Ou6QIgSYQ6U:b-iw0fze) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L241)):*
> ```Java
> 
>     /**
>      * The following 4 fields in the domain entity can be or have a reference to this
> ```

Ditto, way too long summary fragment.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 243 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIxWABzSyK7XQUgEx:-MHCIxWABzSyK7XQUgEy:brwxee9) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L243)):*
> ```Java
>      * The following 4 fields in the domain entity can be or have a reference to this
>      * BillingEvent.Recurring entity, so we need to check them and replace them with the new entity
>      * when necessary: 1. domain.autorenewBillingEvent 2.
> ```

Numbered lists are generally formatted one per line.  (And for what you're trying to do, you'll need to use a `<ol>` or similar; remember that Javadoc is ultimately an HTML format that is intended to be consumed via Web browser).
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 285 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCJI9IEoSi--ZpfAGs:-MHCJI9IEoSi--ZpfAGt:b-s7qfc0) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L285)):*
> ```Java
>         domainChange.append(
>             String.format(
>                 "  Changed transferData.serverApproveAutoRenewEvent from %s to %s.\n",
> ```

You're formatting these as complete English sentences but if we ever actually needed to use them for anything (like to figure out what a given ID was changed to) they'd be easier to consume in a more machine readable format.  Something like:

```
Changes:
field1: old, new
field2: old, new
...
```
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 337 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCHnKGARA0e-57eFn1:-MHCHnKGARA0e-57eFn2:berh082) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L337)):*
> ```Java
>     }
> 
>     private static class BillingEventInput {
> ```

I don't think this class really has a reason to exist.  You can make things simpler by, at the beginning of the `reduce()` method, simply inline a simplified version of the code from `getBillingEventInput()` (which can go away itself as well).

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/798)* status: 0 of 5 files reviewed, 17 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 57 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCG6M6BTh5Ry5VNpxu:-MHIXYHkBZrvBgCakVi5:bb1tjmf) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L57)):*
Updated the javadoc.


> (Also, do past generated invoices refer to these IDs?)
I don't think so, looking at the [billing_events.sql](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/beam/invoicing/sql/billing_events.sql;l=1?q=billing_events.&sq=&ss=nomulus%2Fnomulus), only `BillingEvent.OneTime`'s id is used in the report, and we don't change them in this action(we may change some `BillingEvent.OneTime.cancellationMatchingBillingEvent` though). Do you know if there is any other place I need to check?
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 58 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCFhoaCay4Y8Ga2PCI:-MHHR3Tv6Bz2rbVPfmss:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L58)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

"IDs"
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 64 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCGUai54GXwpighr7l:-MHHRKvtBavw45b7ovED:bfbq99i) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L64)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

A better name would be `DedupeRecurringBillingEventIdsAction`.  "Resave" just implies that's it's re-saving them as-is, a la `ResaveAllEppResourcesAction`, which is not what's happening here -- this mapreduce is performing a specific action of deduping the entities, not a generic resave, and the specific action of deduping is actually changing the IDs of the entities themselves so it's not really re-saving so much as it is deleting and re-creating, i.e. moving.
</blockquote></details>

Good point, done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 75 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCE2knBUsMFOy9qpWF:-MHHSSET1pDS-A-w8ki6:b-eo361n) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L75)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Considering this is a one-off scrap mapreduce, what's the point in making the GCS bucket configurable?  Just hard-code the one to use.

Also as written I don't think this will actually work because you haven't written a `@Provides` method anywhere to provide the `GCS_BUCKET` parameter.
</blockquote></details>

Making it configurable allows me to test this in Alpha and write the result to a bucket in the alpha project.

I have added the corresponding `@Provides` method in the module.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 91 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCGMCn5Fz5IIh2XcYC:-MHI1tqH-e31lMc42blV:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L91)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

s/problematic/duplicate/

They're problematic because they're duplicates, so no need to be vague when a better precise word is available.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 115 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCH4Av6meyuleCxi0_:-MHI4Tel1ubYHVrsyoQ5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L115)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The handling of canceled one times definitely needs a callout in the Javadocs above explaining exactly what's going on.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 122 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCHAK_4VYlCmCyvcbB:-MHI8-vS5mjDL9RiACRj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L122)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This ain't a mapper and it ain't working on HistoryEntries ...
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 142 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCHJhG9mSF_8T_C5Zc:-MHIKqBO9Q_3Mqs0qCMU:b-hbpgd4) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L142)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Use `getContext().incrementCounter(...)` for useful output of exactly what's going on in this case and all others.  See other mapreduces as an example of how to do so.
</blockquote></details>

Do you mean to have a counter per id(like in the mapper add `incrementCounter("Recurring billing event with id: %d", id)`) and use it in the reducer to determine if we need to proceed? If so, do you know if there is a limit of counter size, i.e. can we have a counter per entity?  
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 159 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCILuOAQPN4dV6m41r:-MHIMdjS070flX4OMVmu:by21fvt) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L159)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These `update` verbs used in your helper methods are too generic and don't really explain what the methods are actually doing.
</blockquote></details>

Changed the name and also added a few comments to explain the purpose here.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 175 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIWJK1b4yDTZ3nQYK:-MHINgUi6jg-aaOKKQkl:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L175)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These two `.now()` calls aren't necessary and make the mapreduce slightly less performant because they're requiring multiple server round trips when a single one would do.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 182 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCEeEg-9Q2dH1iZYx6:-MHIU3AN3CFffBM4N21h:b-z6jd59) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L182)):*
>This seems overly complicated here. Are you just trying to output the changes made? Is a logger not sufficient for some reason? How many changes are there and how much do we truly care about knowing the details of every single change? Isn't it more that we know we're done when we run this mapreduce and there's 0 IDs changed?

I just feel that this is a safe choice in case we need to trace back what entities we have touched. Using GCS here because we can put it in the same transaction that changes the entity to guarantee that both the GCS file and the entity changes are made together, using `logger` doesn't provide that consistency. If we really don't care about the mapping between the old and new entity, we can use `logger`. Thoughts?


>Also you were going to write out each change to its own file, generating potentially tens of thousands of different individual files? There's no way we'd ever be able to consume all that information correctly.

Not really, we only create a file for the entity having duplicate id. So it is should around ~50 files.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 208 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIhaP4ZD8kh8_5H99:-MHI_sBL-D_l04kElHAK:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L208)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Three lines is too long for a Javadoc summary fragment.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 209 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIl1jCTCYT0biJfii:-MHI_swIADj2ohUIIPJ5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L209)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs some `{@link}` or `<code>` formatting as appropriate.  (Probably the first one.)
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 241 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIu5a9Ou6QIgSYQ6T:-MHI_tVvD2EltV20Oml1:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L241)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto, way too long summary fragment.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 243 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCIxWABzSyK7XQUgEx:-MHIcKbk46IcvkIB6ENh:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L243)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Numbered lists are generally formatted one per line.  (And for what you're trying to do, you'll need to use a `<ol>` or similar; remember that Javadoc is ultimately an HTML format that is intended to be consumed via Web browser).
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 285 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCJI9IEoSi--ZpfAGs:-MHIcMu_4HhaRESDTZas:b-kno0m3) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L285)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You're formatting these as complete English sentences but if we ever actually needed to use them for anything (like to figure out what a given ID was changed to) they'd be easier to consume in a more machine readable format.  Something like:

```
Changes:
field1: old, new
field2: old, new
...
```
</blockquote></details>

I will make this change if we decide to write the entity changes to a GCS file.
___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 337 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCHnKGARA0e-57eFn1:-MHIfO_UDcudHV_uFOWT:b-896fix) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L337)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I don't think this class really has a reason to exist.  You can make things simpler by, at the beginning of the `reduce()` method, simply inline a simplified version of the code from `getBillingEventInput()` (which can go away itself as well).
</blockquote></details>

Done.

**Review by CydeWeys — COMMENTED** [review]
Holding off on this until it's rewritten to not be a mapreduce (per discussion).  Ping me when that's done and it's ready for another review.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/798#-:-MHSuix51E5YmK1e2yqg:bt5i22p)* status: 0 of 8 files reviewed, 17 unresolved discussions (waiting on @CydeWeys)

**Review by hstonec — COMMENTED** [review]
PTAL. I have refactored the code to implement the functionality in a nomulus command.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/798#-:-MHq5yVw0AZZJzmb7jPM:b-phxowa)* status: 0 of 7 files reviewed, 17 unresolved discussions (waiting on @CydeWeys)

**Review by hstonec — COMMENTED** [review]
ping :)

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/798#-:-MI-qZrH2lSwG2N0E_7I:bq54zy0)* status: 0 of 7 files reviewed, 17 unresolved discussions (waiting on @CydeWeys)

**Review by CydeWeys — APPROVED** [review]
This is high-risk so definitely make sure to test it on sandbox first.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/798#-:-MI5LGzIB7CRJ2Prdnso:b2k8l2b)* status: 0 of 7 files reviewed, all discussions resolved

___
*[core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java, line 182 at r1](https://reviewable.io/reviews/google/nomulus/798#-MHCEeEg-9Q2dH1iZYx6:-MI5L4j77q5NVHkQgRGb:bdwq4v1) ([raw file](https://github.com/google/nomulus/blob/39d858a557bb17fb296d559d3394aff2750acee4/core/src/main/java/google/registry/tools/server/ResaveRecurringBillingEventAction.java#L182)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

>This seems overly complicated here. Are you just trying to output the changes made? Is a logger not sufficient for some reason? How many changes are there and how much do we truly care about knowing the details of every single change? Isn't it more that we know we're done when we run this mapreduce and there's 0 IDs changed?

I just feel that this is a safe choice in case we need to trace back what entities we have touched. Using GCS here because we can put it in the same transaction that changes the entity to guarantee that both the GCS file and the entity changes are made together, using `logger` doesn't provide that consistency. If we really don't care about the mapping between the old and new entity, we can use `logger`. Thoughts?


>Also you were going to write out each change to its own file, generating potentially tens of thousands of different individual files? There's no way we'd ever be able to consume all that information correctly.

Not really, we only create a file for the entity having duplicate id. So it is should around ~50 files.
</blockquote></details>

OK, that's fine, and worth keeping around.

**Review by hstonec — COMMENTED** [review]
Tested in sandbox and it worked as expected.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/798#-:-MLEwoPV-BjWV_TRPUAX:b-uhim8a)* status: 0 of 7 files reviewed, all discussions resolved

**Pull request merged**
