### PR TITLE
Allow BEAM pipeline to choose JDBC isolation levels

### PR DESCRIPTION
**Pull request by weiminyu**
Some BEAM pipelines may only perform READ-ONLY (e.g., reporting) or
blind-write (datastore to sql data migration) operations, which do not
need the default TRANSACTION_SERIALIZABLE isolation level. In such
cases, a less strict level allows better performance.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/916)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/916)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @gbrodman, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 289 at r1](https://reviewable.io/reviews/google/nomulus/916#-MPekSoUEfYvwogowO9s:-MPekSoUEfYvwogowO9t:b-x3nn9t) ([raw file](https://github.com/google/nomulus/blob/c65134bc75836b5ccb40bf524f6ff89efc8af580/core/src/main/java/google/registry/persistence/PersistenceModule.java#L289)):*
> ```Java
>    */
>   public enum TransactionIsolation {
>     TRANSACTION_READ_UNCOMMITTED,
> ```

Put Javadocs on these explaining what each one does.  Absent that it's not clear to me what these really mean, e.g. does `READ` mean `READ_ONLY`?  Some renaming might be in order too.  Also I don't think the `TRANSACTION_` prefix is adding anything; does it mean transactional?  Are there non-transactional isolation levels envisioned?

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/916)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @gbrodman, @mindhog, and @weiminyu)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 289 at r1](https://reviewable.io/reviews/google/nomulus/916#-MPekSoUEfYvwogowO9s:-MPelffz2BjDBuNC7Ktw:bok649u) ([raw file](https://github.com/google/nomulus/blob/c65134bc75836b5ccb40bf524f6ff89efc8af580/core/src/main/java/google/registry/persistence/PersistenceModule.java#L289)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Put Javadocs on these explaining what each one does.  Absent that it's not clear to me what these really mean, e.g. does `READ` mean `READ_ONLY`?  Some renaming might be in order too.  Also I don't think the `TRANSACTION_` prefix is adding anything; does it mean transactional?  Are there non-transactional isolation levels envisioned?
</blockquote></details>

Right, I see that you're referring the names in `java.sql.Connection` ... so why re-define them here then?  Why not just reference those?

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/916)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 289 at r1](https://reviewable.io/reviews/google/nomulus/916#-MPekSoUEfYvwogowO9s:-MPk_rfu-rdTWNYmA6lt:bp6fu25) ([raw file](https://github.com/google/nomulus/blob/c65134bc75836b5ccb40bf524f6ff89efc8af580/core/src/main/java/google/registry/persistence/PersistenceModule.java#L289)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Right, I see that you're referring the names in `java.sql.Connection` ... so why re-define them here then?  Why not just reference those?
</blockquote></details>

These are the names of integer variables in Connection.java. However, we need the string literals to configure Hibernate.

**Review by mindhog — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/916)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/916)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @weiminyu)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 288 at r1](https://reviewable.io/reviews/google/nomulus/916#-MQNV7LH8nnqZH3bAZrR:-MQNV7LH8nnqZH3bAZrS:b-p1l5za) ([raw file](https://github.com/google/nomulus/blob/c65134bc75836b5ccb40bf524f6ff89efc8af580/core/src/main/java/google/registry/persistence/PersistenceModule.java#L288)):*
> ```Java
>    * <p>Enum names must match the corresponding variable names in {@link java.sql.Connection}.
>    */
>   public enum TransactionIsolation {
> ```

Maaaybe this should be `TransactionIsolationLevel`?  We'll likely be statically importing it at most use call sites, so I'm not expecting the added length to matter too much.
___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 289 at r1](https://reviewable.io/reviews/google/nomulus/916#-MPekSoUEfYvwogowO9s:-MQNUBADC4XapG9yPvVC:b-si3l6j) ([raw file](https://github.com/google/nomulus/blob/c65134bc75836b5ccb40bf524f6ff89efc8af580/core/src/main/java/google/registry/persistence/PersistenceModule.java#L289)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

These are the names of integer variables in Connection.java. However, we need the string literals to configure Hibernate.
</blockquote></details>

Ughhh.

Can you add a private field here on the enum then with a constructor so that it's clear how each one matches up with the corresponding Connection field, and in an IDE you can ctrl-click through to see the exact one?  I.e. this like would look like:

```
  TRANSACTION_READ_UNCOMMITTED(Connection.TRANSACTION_READ_UNCOMMITTED)
.....

  private TransactionIsolation(int transactionIsolationLevel) { ... }
    // Or whatever name you think is good for transactionIsolationLevel
```

We can then use that field when we need to do the conversion to the actual `Connection` value, but it leaves us free to give these enums that we're using better more sensible names.  Basically it seems like a good idea to uncouple our names for these with Connection's names for them, while still maintaining that 1-to-1 correspondence.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/916)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 288 at r1](https://reviewable.io/reviews/google/nomulus/916#-MQNV7LH8nnqZH3bAZrR:-MQNedcrDUWdlN31pgcb:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c65134bc75836b5ccb40bf524f6ff89efc8af580/core/src/main/java/google/registry/persistence/PersistenceModule.java#L288)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Maaaybe this should be `TransactionIsolationLevel`?  We'll likely be statically importing it at most use call sites, so I'm not expecting the added length to matter too much.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 289 at r1](https://reviewable.io/reviews/google/nomulus/916#-MPekSoUEfYvwogowO9s:-MQNvI9Y1gn69osGlXIQ:b-9nocf2) ([raw file](https://github.com/google/nomulus/blob/c65134bc75836b5ccb40bf524f6ff89efc8af580/core/src/main/java/google/registry/persistence/PersistenceModule.java#L289)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ughhh.

Can you add a private field here on the enum then with a constructor so that it's clear how each one matches up with the corresponding Connection field, and in an IDE you can ctrl-click through to see the exact one?  I.e. this like would look like:

```
  TRANSACTION_READ_UNCOMMITTED(Connection.TRANSACTION_READ_UNCOMMITTED)
.....

  private TransactionIsolation(int transactionIsolationLevel) { ... }
    // Or whatever name you think is good for transactionIsolationLevel
```

We can then use that field when we need to do the conversion to the actual `Connection` value, but it leaves us free to give these enums that we're using better more sensible names.  Basically it seems like a good idea to uncouple our names for these with Connection's names for them, while still maintaining that 1-to-1 correspondence.
</blockquote></details>

Added a reflection-based check in constructor

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/916)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @mindhog)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 289 at r1](https://reviewable.io/reviews/google/nomulus/916#-MPekSoUEfYvwogowO9s:-MQQ92q09f4LVnSFZ3wf:badh6j5) ([raw file](https://github.com/google/nomulus/blob/c65134bc75836b5ccb40bf524f6ff89efc8af580/core/src/main/java/google/registry/persistence/PersistenceModule.java#L289)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Added a reflection-based check in constructor
</blockquote></details>

Additional note: uncoupling our names with Connection's names is not necessarily beneficial. E.g., the HikariCP connection pool, which we use with Hibernate, only accept these string values. If we ever use HikariCP directly,  consistent naming would be necessary.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/916#-:-MQSTeJ07Elt6K6UMV2L:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @gbrodman and @mindhog)

**Pull request merged**
