### PR TITLE
Script to rolling-start Nomulus

### PR DESCRIPTION
**Pull request by weiminyu**
Add a script to restart Nomulus non-disruptively. This can be used after
a configuration change to external resources (e.g.,  Cloud SQL
credential) to make Nomulus pick up the latest config.

Also added proper support to paging based List api methods, replacing the
current hack that forces the server to return everything in one response.
The List method for instances has a lower limit on page size than others
which is not sufficient for our project.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/888)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/888)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)

___
*[release/rollback/appengine.py, line 121 at r1](https://reviewable.io/reviews/google/nomulus/888#-MNOIzlW0ITaCpSyqbvx:-MNOIzlX-ycWAPsI_Lva:b7ohtj1) ([raw file](https://github.com/google/nomulus/blob/274aec8efa216818928f678a79c524bee728657a/release/rollback/appengine.py#L121)):*
> ```Python
>                                                           servicesId=
>                                                           service_id,
>                                                           pageToken=page_token)
> ```

Optional: An alternate approach to wrapping the call in a lambda would be to pass the function objects in to a modified version of your "list_all_pages" function.  So the the function would be implemented like (omitting the type annotations and most of the implementation):

    def list_all_pages(func,  *args, **kwargs):
      ...
      result = func(*args, pageToken=page_token, **kwargs)
      ...

At which point a call-site would be:

    common.list_all_pages(self._versions.list, appsId=self._project, servicesId=service_id)

The advantage to this is that you wouldn't need to define all of these lambdas.  The disadvantage is that you'd lose type-checking, though I'm not sure you're getting very much from it as I think that the underlying cloud api functions are all dynamic and therefore not type-checked anyway.

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/888)* status: all files reviewed, 4 unresolved discussions (waiting on @weiminyu)

___
*[release/rollback/common.py, line 130 at r1](https://reviewable.io/reviews/google/nomulus/888#-MNOYPzr-El80l2FYXUV:-MNOYPzr-El80l2FYXUW:b9ver5y) ([raw file](https://github.com/google/nomulus/blob/274aec8efa216818928f678a79c524bee728657a/release/rollback/common.py#L130)):*
> ```Python
> # yapf: disable
> ListRequestFactory = NewType(
>     'ListRequestFactory', Callable[[str], http.HttpRequest])
> ```

I don't think the NewType is what you want.  This creates ListRequestFactory which is derived from Callable[...] which would require that the functions you pass into list_all_pages be derived from ListRequestFactory, when in fact they are derived from Callable[...].  And, in fact, this does show up as an error under "mypy".   Doing "ListRequestFactory = Callable[...]" should be just fine.
___
*[release/rollback/common.py, line 155 at r1](https://reviewable.io/reviews/google/nomulus/888#-MNO_wZ195G2MmFLhodF:-MNO_wZ26fPqBW_Ua1ke:b-ad9ky7) ([raw file](https://github.com/google/nomulus/blob/274aec8efa216818928f678a79c524bee728657a/release/rollback/common.py#L155)):*
> ```Python
>         result_collector.extend(response.get(data_field, []))
>         page_token = response.get('nextPageToken')
>         if page_token:
> ```

I think that

    if not page_token:
       return tuple(...)

would be clearer and terser.
___
*[release/rollback/rolling_restart.py, line 91 at r1](https://reviewable.io/reviews/google/nomulus/888#-MNOeA9n8xRz5cbeUsxy:-MNOeA9o4tQ67z3ch2Yc:b-u2lnm) ([raw file](https://github.com/google/nomulus/blob/274aec8efa216818928f678a79c524bee728657a/release/rollback/rolling_restart.py#L91)):*
> ```Python
>             if cmd.instance_name in running_instances:
>                 print('Waiting for VM to shut down...')
>                 continue
> ```

I recall at least one outage where GAE wasn't restarting instances.  It seems like it would be a pretty simple addition to just also verify that the number of instances is what we started with, no?

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/888)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @mindhog)

___
*[release/rollback/appengine.py, line 121 at r1](https://reviewable.io/reviews/google/nomulus/888#-MNOIzlW0ITaCpSyqbvx:-MNQm_bvCqanqU6GtHt7:b-896fix) ([raw file](https://github.com/google/nomulus/blob/274aec8efa216818928f678a79c524bee728657a/release/rollback/appengine.py#L121)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Optional: An alternate approach to wrapping the call in a lambda would be to pass the function objects in to a modified version of your "list_all_pages" function.  So the the function would be implemented like (omitting the type annotations and most of the implementation):

    def list_all_pages(func,  *args, **kwargs):
      ...
      result = func(*args, pageToken=page_token, **kwargs)
      ...

At which point a call-site would be:

    common.list_all_pages(self._versions.list, appsId=self._project, servicesId=service_id)

The advantage to this is that you wouldn't need to define all of these lambdas.  The disadvantage is that you'd lose type-checking, though I'm not sure you're getting very much from it as I think that the underlying cloud api functions are all dynamic and therefore not type-checked anyway.
</blockquote></details>

Done.
___
*[release/rollback/common.py, line 130 at r1](https://reviewable.io/reviews/google/nomulus/888#-MNOYPzr-El80l2FYXUV:-MNQVGWe5elnclN3Z69l:b3cfmo6) ([raw file](https://github.com/google/nomulus/blob/274aec8efa216818928f678a79c524bee728657a/release/rollback/common.py#L130)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I don't think the NewType is what you want.  This creates ListRequestFactory which is derived from Callable[...] which would require that the functions you pass into list_all_pages be derived from ListRequestFactory, when in fact they are derived from Callable[...].  And, in fact, this does show up as an error under "mypy".   Doing "ListRequestFactory = Callable[...]" should be just fine.
</blockquote></details>

Realized that the named type is redundant. Dropped it and using Callable directly on the parameter.
___
*[release/rollback/common.py, line 155 at r1](https://reviewable.io/reviews/google/nomulus/888#-MNO_wZ195G2MmFLhodF:-MNQQxuD83_oxntTDQDK:bmfxpif) ([raw file](https://github.com/google/nomulus/blob/274aec8efa216818928f678a79c524bee728657a/release/rollback/common.py#L155)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I think that

    if not page_token:
       return tuple(...)

would be clearer and terser.
</blockquote></details>

Done.
___
*[release/rollback/rolling_restart.py, line 91 at r1](https://reviewable.io/reviews/google/nomulus/888#-MNOeA9n8xRz5cbeUsxy:-MNPj5Q6CWqUlBSmTqX7:b-gnax39) ([raw file](https://github.com/google/nomulus/blob/274aec8efa216818928f678a79c524bee728657a/release/rollback/rolling_restart.py#L91)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I recall at least one outage where GAE wasn't restarting instances.  It seems like it would be a pretty simple addition to just also verify that the number of instances is what we started with, no? 
</blockquote></details>

Added the check for manual scaling versions. Basic and auto scaling are load driven and do not always replace deleted instances.

**Review by mindhog — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/888)* status: all files reviewed, 3 unresolved discussions (waiting on @mindhog and @weiminyu)

___
*[release/rollback/common.py, line 132 at r2](https://reviewable.io/reviews/google/nomulus/888#-MNTL6OF7oCthpWqoh9-:-MNTL6OF7oCthpWqoh90:bo5nzpd) ([raw file](https://github.com/google/nomulus/blob/e9733a894e6c6ad261200d3f05fabfb15e1798a5/release/rollback/common.py#L132)):*
> ```Python
>             items to be returned. This is guaranteed to be an Iterable
>             type.
> ```

We would typically document *args and **kwargs as well, in this case with something like:

    *args: Positional arguments passed to "func"

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/888)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @mindhog)

___
*[release/rollback/common.py, line 132 at r2](https://reviewable.io/reviews/google/nomulus/888#-MNTL6OF7oCthpWqoh9-:-MNTrSD7EfNCYIg40Xwc:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e9733a894e6c6ad261200d3f05fabfb15e1798a5/release/rollback/common.py#L132)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

We would typically document *args and **kwargs as well, in this case with something like:

    *args: Positional arguments passed to "func"
</blockquote></details>

Done.

**Pull request merged**
