### PR TITLE
Add /console/userdata endpoint

### PR DESCRIPTION
**Pull request by ptkach**
Provides initial set of data, necessary to start the UI

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2137)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
can you say in the commit message / PR what the significance of the admin / global role fields are, and how they'll be used in the UI?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2137#-:-Ndg1WDs3OGZhlBoynDQ:bpbcbil)* status: all files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java` line 80 at r1](https://reviewable.io/reviews/google/nomulus/2137#-NdfyBZ2E-MjtjPl1mA5:-NdfyBZ2E-MjtjPl1mA6:b-uaeprl) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java#L80)):*
> ```Java
>   WhoisRegistrarFieldsAction whoisRegistrarFieldsAction();
> 
>   ConsoleUserDataAction consoleUserDataAction();
> ```

not entirely part of this PR, but can we alphabetize all these? 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 67 at r1](https://reviewable.io/reviews/google/nomulus/2137#-Ndg-oW40ZnV_jnIK9k3:-Ndg-oW40ZnV_jnIK9k4:b-jd8o5o) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L67)):*
> ```Java
>     User user = authInfo.consoleUser().get();
> 
>     JSONObject json = new JSONObject();
> ```

should we just use gson to format all this?

**Review by ptkach — COMMENTED** [review]
Added comments to the code, commit message / pr can be harder to find later

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2137#-:-NdkSaYq8TFLCyZoWt-J:bq0rho6)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java` line 80 at r1](https://reviewable.io/reviews/google/nomulus/2137#-NdfyBZ2E-MjtjPl1mA5:-NdkSi6V95dD7tEXBe_Y:b-y455x6) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java#L80)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

not entirely part of this PR, but can we alphabetize all these?
</blockquote></details>

Done, however to me it feels like it adds noise to the PR
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 67 at r1](https://reviewable.io/reviews/google/nomulus/2137#-Ndg-oW40ZnV_jnIK9k3:-NdkSyn42aKtAxAF_5U5:b-8b11j9) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L67)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

should we just use gson to format all this?
</blockquote></details>

Added
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 39 at r1](https://reviewable.io/reviews/google/nomulus/2137#gh-1317726685:-NdkT-Hf6MK8cq8-zK77:bbleekw) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L39)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused classes and interfaces

Unused class: ConsoleUserDataActionTest is not referenced within this codebase. If not used as an external API it should be removed.

[Show more details](https://github.com/google/nomulus/security/code-scanning/1560)
</blockquote></details>

Done. This is a test.

**Review by jianglai — DISMISSED** [review]
Apologies for the delay. I was a bit swamped by all the things that need to catch up.

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2137#-:-Ne3bDQ8AQPVd4WvEozo:b-i9682s)* status: all files reviewed, 6 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], and @ptkach)

___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 39 at r1](https://reviewable.io/reviews/google/nomulus/2137#gh-1317726685:-Ne3aKQX1SQ6smJlJ0VR:b-m78gk5) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L39)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Done. This is a test.
</blockquote></details>

I'm curious why this message shows up. Is it because the class didn't have a javadoc before?
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 51 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne3au-c27V_VGJFxdb2:-Ne3au-c27V_VGJFxdb3:b-b2o8si) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L51)):*
> ```Java
> 
>   @Test
>   void testSuccess_getContactInfo() throws IOException {
> ```

I felt that this test class is a bit lacking. Shouldn't you test cases where authentication fails, and for users with different roles?
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 66 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne3aqca66AgejDV0aZF:-Ne3aqca66AgejDV0aZG:b-kx6ii6) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L66)):*
> ```Java
>   }
> 
>   private User createUser(UserRoles userRoles) {
> ```

Seems unnecessary if you are only going to use this method once.
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 74 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne3aaJDEUrej5yfhCmF:-Ne3aaJDEUrej5yfhCmG:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L74)):*
> ```Java
>   }
> 
>   private ConsoleUserDataAction createAction(AuthResult authResult) throws IOException {
> ```

Ditto.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2137)* status: all files reviewed, 7 unresolved discussions (waiting on @github-code-scanning[bot] and @ptkach)

___
*[`core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java` line 80 at r1](https://reviewable.io/reviews/google/nomulus/2137#-NdfyBZ2E-MjtjPl1mA5:-Ne5Q44u5VqK7Ku49dt_:b-smww1f) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/main/java/google/registry/module/frontend/FrontendRequestComponent.java#L80)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Done, however to me it feels like it adds noise to the PR
</blockquote></details>

yeah we should have been doing this as we went along -- I don't remember exactly where I read this but in one of the style guides it says that it's best to clean up surrounding code as you go 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 67 at r1](https://reviewable.io/reviews/google/nomulus/2137#-Ndg-oW40ZnV_jnIK9k3:-Ne5QLLm8_zEnMhZnpYD:b-pujegc) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L67)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Added
</blockquote></details>

i don't think this comment was addressed? 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 70 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne5RFxP7zhR121p3bYf:-Ne5RFxP7zhR121p3bYg:bqq7pxk) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L70)):*
> ```Java
>     // Both isAdmin and globalRole flags are used by UI as an indicator to hide / show admin
>     // specific set of widgets and screens.
>     // For example - Admin sees everything, while Registrar sees registrar-specific set of screens
> ```

this comment should be fleshed out more and made more clear -- what is "admin"? what is "Registrar"? 
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 39 at r1](https://reviewable.io/reviews/google/nomulus/2137#gh-1317726685:-Ne5QPu75XfrqtEK2de7:b-fqri0b) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L39)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I'm curious why this message shows up. Is it because the class didn't have a javadoc before?
</blockquote></details>

this message shows up pretty much all the time unfortunately 
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 60 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne5QweTEqJqToeajqjQ:-Ne5QweTEqJqToeajqjR:b-9zt2xn) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L60)):*
> ```Java
>     action.run();
>     assertThat(response.getStatus()).isEqualTo(HttpStatusCodes.STATUS_CODE_OK);
>     Map jsonObject = GSON.fromJson(response.getPayload(), Map.class);
> ```

should use TypeTokens instead to avoid raw containers

`GSON.fromJson(myString, new TypeToken<Map<String, String>>(){});`

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2137)* status: all files reviewed, 7 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], and @jianglai)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 67 at r1](https://reviewable.io/reviews/google/nomulus/2137#-Ndg-oW40ZnV_jnIK9k3:-Ne8oQCfAA0FSjHilHM_:b-hfvskx) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L67)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i don't think this comment was addressed?
</blockquote></details>

Can you please clarify what do you mean by "use gson to format all this"? I might be not following the request correctly, but `JSONObject` provides extremely easy way here for us to construct a response, while taking care of "Basic types" conversion. The code looks straightforward and clean. How will GSON make it better?
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 70 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne5RFxP7zhR121p3bYf:-Ne8qzK08_CVrGFLME1f:b48z10n) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L70)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this comment should be fleshed out more and made more clear -- what is "admin"? what is "Registrar"?
</blockquote></details>

I decided against providing more information here, as it essentially duplicates information in `UserRole.java` and `RegistrarRole.java`, if flesh out is necessary, then that's where it should be done. 
Frontend code however will have separate comments as soon as we get to it. 
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 39 at r1](https://reviewable.io/reviews/google/nomulus/2137#gh-1317726685:-Ne8rhlg2WU1bRr43EYZ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L39)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this message shows up pretty much all the time unfortunately
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 51 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne3au-c27V_VGJFxdb2:-Ne8vr62DIgB_FzsreXz:b-xkjx90) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L51)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I felt that this test class is a bit lacking. Shouldn't you test cases where authentication fails, and for users with different roles?
</blockquote></details>

Added console user verification test, apart from that there's just not much to test really. Auth is mostly covered by `@Action` functionality and has nothing to do with `ConsoleUserDataAction.java` specifics. The point here is to verify that the data is what we expect and it's just GET, so that's all
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 60 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne5QweTEqJqToeajqjQ:-Ne8rjTp88Q71_bEVfco:b98i88h) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L60)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

should use TypeTokens instead to avoid raw containers

`GSON.fromJson(myString, new TypeToken<Map<String, String>>(){});`
</blockquote></details>

Similarly to my comment higher up, I don't see how would we benefit from it. Current implementation provides concise way to handle Json's basic types without manual conversion, eg false != "false" . Please elaborate why do you think it's necessary here
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 66 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne3aqca66AgejDV0aZF:-Ne9B4_c00Z5-ZO3Sol2:ba3dfob) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L66)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Seems unnecessary if you are only going to use this method once.
</blockquote></details>

Removed
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 74 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne3aaJDEUrej5yfhCmF:-Ne9B5s_4CDMd3p1kzBw:b-v56a66) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L74)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Used twice now, keeping it

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2137)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], and @jianglai)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 67 at r1](https://reviewable.io/reviews/google/nomulus/2137#-Ndg-oW40ZnV_jnIK9k3:-Ne9UFTyBnoHLtoZL-Gm:b-n5elor) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L67)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

well for one, i hope that this iteration fails Kokoro testing because the gson variable isn't used 

but xxxxxxin general we should prefer immutable objects, so it's preferable to use `String result = gson.toJson(ImmutableMap.of(....))` or something like that
</blockquote></details>

Now I see what you mean, it wasn't clear from your first comment. Updated now, btw we don't necessary need gson to achieve use of immutable data structures. 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 70 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne5RFxP7zhR121p3bYf:-Ne9V5C53r0vVcov2wLA:bqn50p3) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L70)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We definitely need more clarification here. For one thing, this uses the term "Registrar" that doesn't appear in the code anywhere around here and it's not clear what is meant. 

In addition, the backend role info is notably different from the way that these are used on the front end (deciding how much information to show). This information needs to be displayed here in some way.
</blockquote></details>

I've added more clarification, however these values are not created or modified here, so I'd not expect this place to provide a lot of information on what these values are, as that information should be available in `UserRole.java` or `RegistrarRole.java`.
As I mentioned previously use of those value on front-end will have to be commented on separately on front-end. 

To be clear - these values are not needed on front-end at the moment and I've just added them in order to make it clear were and how they'd come from, as it was something we'd discussed offline on multiple occasions. This however blocks `technicalDocsUrl` field delivery, which in fact is needed, so if we can't reach an agreement sooner (this has been pending for almost a week now) I will resort to removing this for now. 
___
*[`core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java` line 60 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne5QweTEqJqToeajqjQ:-Ne9XPjv1ji0MIshZ-Fg:b-kth9r5) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/test/java/google/registry/ui/server/console/ConsoleUserDataActionTest.java#L60)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

that's not what this comment is saying at all, I'm saying that if we use the TypeToken we can stop using the raw Map class 

But in general it's better to just use `assertThat(someMap).containsExactly(key1, value1, key2, value2...)` because then you don't need multiple lines
</blockquote></details>

Updated to use `containsExactly`

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2137)* status: all files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot], @jianglai, and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 67 at r1](https://reviewable.io/reviews/google/nomulus/2137#-Ndg-oW40ZnV_jnIK9k3:-Ne9ZhjN0eUEyMEHOTub:b-jo0dw6) ([raw file](https://github.com/google/nomulus/blob/fac97c5cb0a812d9d8114ab3c873504b26f47c10/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L67)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Now I see what you mean, it wasn't clear from your first comment. Updated now, btw we don't necessary need gson to achieve use of immutable data structures.
</blockquote></details>

great thanks! also idk what happened with the "xxxxxxxxxx" in my comment, I must have leaned on the keyboard accidentally haha 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 70 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne5RFxP7zhR121p3bYf:-Ne9Zn624TXgicRwwl4N:bzi1132) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L70)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I've added more clarification, however these values are not created or modified here, so I'd not expect this place to provide a lot of information on what these values are, as that information should be available in `UserRole.java` or `RegistrarRole.java`.
As I mentioned previously use of those value on front-end will have to be commented on separately on front-end. 

To be clear - these values are not needed on front-end at the moment and I've just added them in order to make it clear were and how they'd come from, as it was something we'd discussed offline on multiple occasions. This however blocks `technicalDocsUrl` field delivery, which in fact is needed, so if we can't reach an agreement sooner (this has been pending for almost a week now) I will resort to removing this for now.
</blockquote></details>

yeah I get that they're not created here, but essentially like documentation on an API we need to discuss what the meaning is of the values we're providing and how they should be used. 

looks good, but can we fix the line breaks + indentation on the comments?

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2137)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @gbrodman, @github-code-scanning[bot], and @jianglai)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java` line 70 at r2](https://reviewable.io/reviews/google/nomulus/2137#-Ne5RFxP7zhR121p3bYf:-Ne9breT579TjXjojG5B:b-ofs0dy) ([raw file](https://github.com/google/nomulus/blob/d5004e6587def44067f12dd6be38ae088cd10fc7/core/src/main/java/google/registry/ui/server/console/ConsoleUserDataAction.java#L70)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah I get that they're not created here, but essentially like documentation on an API we need to discuss what the meaning is of the values we're providing and how they should be used. 

looks good, but can we fix the line breaks + indentation on the comments?
</blockquote></details>

Fixed line breaks, I guess jifa messed it up

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2137)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @jianglai)

**Pull request merged**
