### PR TITLE
Add delete user to the console

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2603)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2603)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 81 at r1](https://reviewable.io/reviews/google/nomulus/2603#-OAt2gMP91Gmy1Ahzj5j:-OAt2gMP91Gmy1Ahzj5k:bxryw6z) ([raw file](https://github.com/google/nomulus/blob/2961639a9a1ff64adb7a8d53e800882842d71052/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L81)):*
> ```Java
>     String requestMethod = consoleApiParams.request().getMethod();
>     try {
>       if (requestMethod.equals(GET.toString())) {
> ```

i guess we probably should add a HEAD handler to this somewhere as well? not that it's used, but just to round things out
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 167 at r1](https://reviewable.io/reviews/google/nomulus/2603#-OAtKGA002ZUqyj68GW0:-OAtKGA002ZUqyj68GW1:bnntmnv) ([raw file](https://github.com/google/nomulus/blob/2961639a9a1ff64adb7a8d53e800882842d71052/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L167)):*
> ```Java
>     VKey<User> key = VKey.create(User.class, email);
>     tm().delete(key);
>     user.revokeIapPermission(email, maybeGroupEmailAddress, cloudTasksUtils, null, iamClient);
> ```

Nit, but we should probably use the static `User` instead of referring to the user object (just to make it clear that there are no issues with revoking the IAP permissions after deleting the user object from the DB) 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 207 at r1](https://reviewable.io/reviews/google/nomulus/2603#-OAtFNOV1DcT1G0eHBQm:-OAtFNOV1DcT1G0eHBQn:b-xseki9) ([raw file](https://github.com/google/nomulus/blob/2961639a9a1ff64adb7a8d53e800882842d71052/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L207)):*
> ```Java
>     tm().put(builder.build());
> 
>     consoleApiParams.response().setStatus(SC_CREATED);
> ```

oh neat, that's right

**Review by ptkach — COMMENTED** [review]
Second iteration refactors quite a few things, which hopefully should make the logic more straightforward and less error-prone.  This whole thing turned out to be quite bigger bite than I anticipated. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2603#-:-OAtYwiC1zhFirihBHO8:b-jdc4wo)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 81 at r1](https://reviewable.io/reviews/google/nomulus/2603#-OAt2gMP91Gmy1Ahzj5j:-OAtYWz9ErcB-calhdaX:b-chjvko) ([raw file](https://github.com/google/nomulus/blob/2961639a9a1ff64adb7a8d53e800882842d71052/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L81)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i guess we probably should add a HEAD handler to this somewhere as well? not that it's used, but just to round things out
</blockquote></details>

I really don't see us ever using it. Not sure how come we have HEAD, but didn't have PUT or DELETE, but I'm not convinced we will ever have a use-case for it.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 167 at r1](https://reviewable.io/reviews/google/nomulus/2603#-OAtKGA002ZUqyj68GW0:-OAtYspa5ApcKaw5Y3tY:b-h369k) ([raw file](https://github.com/google/nomulus/blob/2961639a9a1ff64adb7a8d53e800882842d71052/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L167)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Nit, but we should probably use the static `User` instead of referring to the user object (just to make it clear that there are no issues with revoking the IAP permissions after deleting the user object from the DB)
</blockquote></details>

Done, good point

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2603)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 81 at r1](https://reviewable.io/reviews/google/nomulus/2603#-OAt2gMP91Gmy1Ahzj5j:-OAyFZRR9d3_hGKW3aI1:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2961639a9a1ff64adb7a8d53e800882842d71052/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L81)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i don't think we will either, but we probably want to at least include it in the statement here (maybe make it a switch statement) just so that we don't accidentally run a POST and get weird results
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 172 at r2](https://reviewable.io/reviews/google/nomulus/2603#-OAxoc_nBHC7_4-e4jMf:-OAyFfLc5eAhVS5gfjxT:bmzp1jx) ([raw file](https://github.com/google/nomulus/blob/cf4ab926585e569067d1bb064d21c87aa840fbc7/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L172)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this doesn't quite match the if statement above 

I think we want to allow the main registrar user plus three additional users, right? so it should be > 4
</blockquote></details>

I believe what I have here is correct - "=" covers exactly the case you mentioned - original user + 3 new users, that'd make it 4 total and prevent new creations, ">" covers the case when for some reason extra users were created with nomulus tool and then another attempt is made through the console.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 175 at r2](https://reviewable.io/reviews/google/nomulus/2603#-OAxoYVX9Ej8HYWVuXk5:-OAyGW9m1HcPA-YBrNam:b68x00z) ([raw file](https://github.com/google/nomulus/blob/cf4ab926585e569067d1bb064d21c87aa840fbc7/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L175)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

wait what? I thought we were limiting it to 3 users, so how could there be this many?
</blockquote></details>

This is basically for when someone would go and create and delete users bunch of times. It's nothing but an increment so that each newly created user would have unique name.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2603)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 172 at r2](https://reviewable.io/reviews/google/nomulus/2603#-OAxoc_nBHC7_4-e4jMf:-OAyI7Pi1gTgLmT5tuhq:b-w0yspw) ([raw file](https://github.com/google/nomulus/blob/cf4ab926585e569067d1bb064d21c87aa840fbc7/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L172)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I believe what I have here is correct - "=" covers exactly the case you mentioned - original user + 3 new users, that'd make it 4 total and prevent new creations, ">" covers the case when for some reason extra users were created with nomulus tool and then another attempt is made through the console.
</blockquote></details>

got it 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 175 at r2](https://reviewable.io/reviews/google/nomulus/2603#-OAxoYVX9Ej8HYWVuXk5:-OAyI9KeEmMpMtVTfbNf:bkx2pqb) ([raw file](https://github.com/google/nomulus/blob/cf4ab926585e569067d1bb064d21c87aa840fbc7/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L175)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

This is basically for when someone would go and create and delete users bunch of times. It's nothing but an increment so that each newly created user would have unique name.
</blockquote></details>

if we delete a user and then create another user, wouldn't we just reuse the email address? 

we run `tm().delete(key)` in the deletion bit so loadByKeyIfPresent should be empty for that one

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2603)* status: 6 of 14 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java` line 175 at r2](https://reviewable.io/reviews/google/nomulus/2603#-OAxoYVX9Ej8HYWVuXk5:-OB2O4Qw1F07dzgJykN4:b-zeuyn2) ([raw file](https://github.com/google/nomulus/blob/cf4ab926585e569067d1bb064d21c87aa840fbc7/core/src/main/java/google/registry/ui/server/console/ConsoleUsersAction.java#L175)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

if we delete a user and then create another user, wouldn't we just reuse the email address? 

we run `tm().delete(key)` in the deletion bit so loadByKeyIfPresent should be empty for that one
</blockquote></details>

Right, I was changing this a few times and this version indeed doesn't need range to be this big

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2603)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/users/userEdit.component.ts` line 66 at r4](https://reviewable.io/reviews/google/nomulus/2603#-OB6rCrp8vy0WvO_Pr8d:-OB6rCrp8vy0WvO_Pr8e:b-pwv02u) ([raw file](https://github.com/google/nomulus/blob/8156cdefe4780431cbbe3f56f1d1391468fe2b1e/console-webapp/src/app/users/userEdit.component.ts#L66)):*
> ```XML
>   deleteUser() {
>     this.isLoading = true;
>     this.usersService.deleteUser(this.userDetails.emailAddress).subscribe({
> ```

this is pretty nitty, but can we just use "emailAddress" everywhere like it is here? it's a mix between that and "userEmail" (in the backend method) and i think this is probably better 
___
*[`console-webapp/src/app/users/users.service.ts` line 41 at r4](https://reviewable.io/reviews/google/nomulus/2603#-OB6wXqFEcId2szjcc7-:-OB6wXqG4hTTxgHBYaeR:b-ouwv6e) ([raw file](https://github.com/google/nomulus/blob/8156cdefe4780431cbbe3f56f1d1391468fe2b1e/console-webapp/src/app/users/users.service.ts#L41)):*
> ```XML
> export class UsersService {
>   users = signal<User[]>([]);
>   viewingUserEmail = signal<string>('');
> ```

Thoughts on maybe something like "currentlyOpenUserEmail"? I'm thinking that just "viewingUserEmail" might be a bit ambiguous between "the user that we are currently viewing" (correct) versus "the user that is doing the viewing" (incorrect).

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2603)* status: 9 of 14 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/users/userEdit.component.ts` line 66 at r4](https://reviewable.io/reviews/google/nomulus/2603#-OB6rCrp8vy0WvO_Pr8d:-OB7gCBm5uXPd1UsNE_z:bb6vmix) ([raw file](https://github.com/google/nomulus/blob/8156cdefe4780431cbbe3f56f1d1391468fe2b1e/console-webapp/src/app/users/userEdit.component.ts#L66)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this is pretty nitty, but can we just use "emailAddress" everywhere like it is here? it's a mix between that and "userEmail" (in the backend method) and i think this is probably better
</blockquote></details>

Fair
___
*[`console-webapp/src/app/users/users.service.ts` line 41 at r4](https://reviewable.io/reviews/google/nomulus/2603#-OB6wXqFEcId2szjcc7-:-OB7gDtc21myqdJ5M9gw:b-4tce3r) ([raw file](https://github.com/google/nomulus/blob/8156cdefe4780431cbbe3f56f1d1391468fe2b1e/console-webapp/src/app/users/users.service.ts#L41)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Thoughts on maybe something like "currentlyOpenUserEmail"? I'm thinking that just "viewingUserEmail" might be a bit ambiguous between "the user that we are currently viewing" (correct) versus "the user that is doing the viewing" (incorrect).
</blockquote></details>

currentlyOpenUserEmail is better indeed

**Review by gbrodman — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
