### PR TITLE
Remove remnants of JUnit 4 rules

### PR DESCRIPTION
**Pull request by jianglai**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1336)

### CODE REVIEW

**Review by mindhog — APPROVED** [review]
> Reviewed 74 of 101 files at r1, 25 of 30 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1336)* status: 98 of 101 files reviewed, all discussions resolved (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/beam/common/RegistryJpaIO.java, line 259 at r1](https://reviewable.io/reviews/google/nomulus/1336#-MkJ4uToChk1mkNSOnxZ:-MkJ4uToChk1mkNSOnx_:bnrx42r) ([raw file](https://github.com/google/nomulus/blob/6193ce4986440988d9e6e9b3d4e10c229e4a6ccb/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L259)):*
> ```Java
>      * significantly greater than the number of threads working on this transformation (see next
>      * paragraph for more information). On the other hand, it should not be too large to the point
>      * that the number of elements per shard is lower than {@link #batchSize()}. As a extension of thumb,
> ```

Haha, I was waiting for something like this!

**Review by jianglai — COMMENTED** [review]
> Reviewed 101 of 101 files at r1, 30 of 30 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1336)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/beam/common/RegistryJpaIO.java, line 259 at r1](https://reviewable.io/reviews/google/nomulus/1336#-MkJ4uToChk1mkNSOnxZ:-MkJBIhK6xbx9-sv7nC8:bm8p7gc) ([raw file](https://github.com/google/nomulus/blob/6193ce4986440988d9e6e9b3d4e10c229e4a6ccb/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L259)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Haha, I was waiting for something like this!
</blockquote></details>

LoL You saw that I caught it myself, right?

**Review by CydeWeys — CHANGES_REQUESTED** [review]
It's too bad that "extension" is such a longer word than "rule".

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1336#-:-MkJKHuf9vvtyi7_s8U3:b-z5ezor)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/test/java/google/registry/persistence/transaction/JpaTestExtensions.java, line 48 at r3](https://reviewable.io/reviews/google/nomulus/1336#-MkJJx4G69mnAEuOPFnP:-MkJJx4G69mnAEuOPFnQ:b20zm6z) ([raw file](https://github.com/google/nomulus/blob/c695d07e8e84aed6eb8a35c14bd55e6e883450a0/core/src/test/java/google/registry/persistence/transaction/JpaTestExtensions.java#L48)):*
> ```Java
> 
>   /**
>    * Junit extension for integration tests with JPA framework, when the underlying database is
> ```

As long as you're modifying this anyway, this should be "JUnit".

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1336)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/test/java/google/registry/persistence/transaction/JpaTestExtensions.java, line 48 at r3](https://reviewable.io/reviews/google/nomulus/1336#-MkJJx4G69mnAEuOPFnP:-MkKPdjZEUF5Pdn2bjl8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c695d07e8e84aed6eb8a35c14bd55e6e883450a0/core/src/test/java/google/registry/persistence/transaction/JpaTestExtensions.java#L48)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

As long as you're modifying this anyway, this should be "JUnit".
</blockquote></details>

Done.

**Pull request merged**
