### PR TITLE
Set payload in success response after sending notification emails

### PR DESCRIPTION
**Pull request by rachelguan**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1377)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1377)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 101 at r1](https://reviewable.io/reviews/google/nomulus/1377#-MlMBkbDBDhejH1ChlM1:-MlMBkbDBDhejH1ChlM2:bxf6865) ([raw file](https://github.com/google/nomulus/blob/dab710b2b03e2b1866c338f0e25e6bbe85c1e47c/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L101)):*
> ```Java
>       sendNotificationEmails();
>       response.setStatus(SC_OK);
>       response.setPayload("Finished sending all expiring certificate notification emails.");
> ```

Log this message at `INFO` too.  Also, it'd be nice if `sendNotificationEmails()` returned the number of emails sent which you could then log here.
___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 157 at r1](https://reviewable.io/reviews/google/nomulus/1377#-MlMBPc92hdhjQV6D8yB:-MlMBPc92hdhjQV6D8yC:bz6x8jt) ([raw file](https://github.com/google/nomulus/blob/dab710b2b03e2b1866c338f0e25e6bbe85c1e47c/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L157)):*
> ```Java
>       Date expirationDate = certificateChecker.getCertificate(certificate.get()).getNotAfter();
>       logger.atInfo().log(
>           "Registrar %s should receive an email that its %s SSL certificate will expire on %s.",
> ```

I know this is out of scope for this PR, but since you're revisiting logging ...

What does "should" mean here?  That's kind of vague.  Something like "Sending email to registrar %s that its ..." is more clear exactly what action is being taken.  "Should" doesn't imply that that action is actually happening.
___
*[core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java, line 645 at r1](https://reviewable.io/reviews/google/nomulus/1377#-MlMB86vERcZz313vNZL:-MlMB86wBs72oYvD52Oh:b-jf26qw) ([raw file](https://github.com/google/nomulus/blob/dab710b2b03e2b1866c338f0e25e6bbe85c1e47c/core/src/test/java/google/registry/batch/SendExpiringCertificateNotificationEmailActionTest.java#L645)):*
> ```Java
>     action.run();
>     assertThat(response.getStatus()).isEqualTo(SC_OK);
>     assertThat(response.getPayload()).isEqualTo("Finished sending all expiring certificate"
> ```

This string should be able to fit all on one line without needing a `+` operator.  The overall statement will be two lines but the text shouldn't need to be broken up.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1377)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 101 at r1](https://reviewable.io/reviews/google/nomulus/1377#-MlMBkbDBDhejH1ChlM1:-MllJxY75E66UernO6rA:bak7t5t) ([raw file](https://github.com/google/nomulus/blob/dab710b2b03e2b1866c338f0e25e6bbe85c1e47c/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L101)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Yeah, that's exactly what I'm suggesting.  And I don't see any readability concerns in `int numEmailsSent = sendNotificationEmails();`  What do you think is problematic there?
</blockquote></details>

just seem a bit redundant but it's reasonable to change to your suggestion. 
I have the log message as 
"Done. Attempted to send %d expiring certificate notification emails in total."to keep things consistent with the logic and log in sendNotificationEmails(). 
I will remove the ambiguous words like "attempted"  and "should" in the PR where i change the email address recipients logs related to sendNotificationEmails() and sendNotificationEmail().

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1377)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @rachelguan)

___
*[core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java, line 273 at r4](https://reviewable.io/reviews/google/nomulus/1377#-MluE1WPE20F9dbVnbGk:-MluE1WPE20F9dbVnbGl:b-oqetcw) ([raw file](https://github.com/google/nomulus/blob/833a79719924e71db056c78fb8d0a6fe87209b27/core/src/main/java/google/registry/batch/SendExpiringCertificateNotificationEmailAction.java#L273)):*
> ```Java
>       }
>     }
>     logger.atInfo().log(
> ```

Shouldn't this be removed?  Otherwise you're logging the same thing twice.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1377#-:-MlvDXzb52VhmlwmI661:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
