### PR TITLE
Move truly public endpoints to a separate Auth

### PR DESCRIPTION
**Pull request by jianglai**
This allows us to more easily refactor public endpoints that still use
the legacy auth mechanism to identify logged-in users (for the legacy
console).

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2200)

### CODE REVIEW

**Review by gbrodman — COMMENTED** [review]
nit: "truly" in commit msg 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2200#-:-Ni1KwNS1kiYtzRZhvt3:b-7j7fcp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Comment by jianglai** [comment]
> nit: "truly" in commit msg
> 
> > Reviewed 6 of 6 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/2200#-:-Ni1KwNS1kiYtzRZhvt3:b-7j7fcp)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

Oops. Done.

**Review by jianglai — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
PTAL.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2200#-:-Ni50OkUAT04kTAUr2s-:b-83330m)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by gbrodman — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2200#-:-Ni5snyHDpccDVyrmzEC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
