### PR TITLE
Convert RegistrarTest to working with Postgresql

### PR DESCRIPTION
**Pull request by hstonec**
This PR converted `RegistrarTest` to working with SQL, and it also made the necessary ofy() -> tm() changes in the related code.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/865)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/865)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @gbrodman and @hstonec)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 661 at r1](https://reviewable.io/reviews/google/nomulus/865#-MLy-vKFBfLGwhIhMe_w:-MLy-vKFBfLGwhIhMe_x:b-3ptrwi) ([raw file](https://github.com/google/nomulus/blob/f13cab5a580001dc6785e3644565bd01fb90a1ff/core/src/main/java/google/registry/model/registrar/Registrar.java#L661)):*
> ```Java
>                                 "FROM RegistrarPoc WHERE registrarId = :registrarId",
>                                 RegistrarContact.class)
>                             .setParameter("registrarId", clientIdentifier)
> ```

:( at "clientIdentifier", not necessary to change here though 
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 1009 at r1](https://reviewable.io/reviews/google/nomulus/865#-MLy0KJ1CBFyLQkP-CwC:-MLy0KJ2AD4KIV2QU6e5:bdsh3hn) ([raw file](https://github.com/google/nomulus/blob/f13cab5a580001dc6785e3644565bd01fb90a1ff/core/src/main/java/google/registry/model/registrar/Registrar.java#L1009)):*
> ```Java
>     return ofyOrJpaTm(
>         () -> ImmutableList.copyOf(ofy().load().type(Registrar.class).ancestor(getCrossTldKey())),
>         () -> tm().transact(() -> tm().loadAll(Registrar.class)));
> ```

question: is there any reason to use `jpaTm()` or `tm()` in these calls, where we know it's going to be the JPA transaction manager because of the `ofyOrJpaTm()` call? 
___
*[core/src/test/java/google/registry/model/registrar/RegistrarTest.java, line 566 at r1](https://reviewable.io/reviews/google/nomulus/865#-MLy0oMS4b1TufkGhCiv:-MLy0oMS4b1TufkGhCiw:bngo85i) ([raw file](https://github.com/google/nomulus/blob/f13cab5a580001dc6785e3644565bd01fb90a1ff/core/src/test/java/google/registry/model/registrar/RegistrarTest.java#L566)):*
> ```Java
>   }
> 
>   @TestOfyAndSql
> ```

Should this just be TestOfyOnly?
___
*[core/src/test/java/google/registry/model/registrar/RegistrarTest.java, line 607 at r1](https://reviewable.io/reviews/google/nomulus/865#-MLy0tuR1UgJBEx-Bve3:-MLy0tuS59_oLmlX-2du:b-4ztnbw) ([raw file](https://github.com/google/nomulus/blob/f13cab5a580001dc6785e3644565bd01fb90a1ff/core/src/test/java/google/registry/model/registrar/RegistrarTest.java#L607)):*
> ```Java
>   }
> 
>   @TestOfyAndSql
> ```

Q: do we have any tests / way of verifying that methods in the @DualDatabaseTest classes are annotated with one of the db-specific test annotations? 
___
*[core/src/test/java/google/registry/testing/DatastoreHelper.java, line 1152 at r1](https://reviewable.io/reviews/google/nomulus/865#-MLy11bhCogZ0lOQ5gid:-MLy11bhCogZ0lOQ5gie:b3m9l6o) ([raw file](https://github.com/google/nomulus/blob/f13cab5a580001dc6785e3644565bd01fb90a1ff/core/src/test/java/google/registry/testing/DatastoreHelper.java#L1152)):*
> ```Java
>         () -> tm().transact(() -> ofy().load().fromEntity(ofy().save().toEntity(resource))),
>         () -> {
>           // We have to separate the read and write operation into different transactions
> ```

huh, interesting.

**Review by gbrodman — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/865)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec)

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/865)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 661 at r1](https://reviewable.io/reviews/google/nomulus/865#-MLy-vKFBfLGwhIhMe_w:-MMGihbnC-MsDTIVjW4y:bm7pnbc) ([raw file](https://github.com/google/nomulus/blob/f13cab5a580001dc6785e3644565bd01fb90a1ff/core/src/main/java/google/registry/model/registrar/Registrar.java#L661)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

:( at "clientIdentifier", not necessary to change here though 
</blockquote></details>

yeah, unfortunately, that is the class field and is used by Datastore so we probably can't change it until the migration is finished.
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 1009 at r1](https://reviewable.io/reviews/google/nomulus/865#-MLy0KJ1CBFyLQkP-CwC:-MMGoPxV2x1kR9yrS1jd:b-aggima) ([raw file](https://github.com/google/nomulus/blob/f13cab5a580001dc6785e3644565bd01fb90a1ff/core/src/main/java/google/registry/model/registrar/Registrar.java#L1009)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

question: is there any reason to use `jpaTm()` or `tm()` in these calls, where we know it's going to be the JPA transaction manager because of the `ofyOrJpaTm()` call? 
</blockquote></details>

I only use `jpaTm()` when I need to use JPA specific method, like `getEntityManager()`, otherwise I use `tm()` because it is shorter and more generic.
___
*[core/src/test/java/google/registry/model/registrar/RegistrarTest.java, line 566 at r1](https://reviewable.io/reviews/google/nomulus/865#-MLy0oMS4b1TufkGhCiv:-MMGqdpkBRLo-JBUC6ER:b-g1hs46) ([raw file](https://github.com/google/nomulus/blob/f13cab5a580001dc6785e3644565bd01fb90a1ff/core/src/test/java/google/registry/model/registrar/RegistrarTest.java#L566)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Should this just be TestOfyOnly?
</blockquote></details>

Makes sense, done.
___
*[core/src/test/java/google/registry/model/registrar/RegistrarTest.java, line 607 at r1](https://reviewable.io/reviews/google/nomulus/865#-MLy0tuR1UgJBEx-Bve3:-MMGqgtRASyPh5yi-K9i:bymmsd8) ([raw file](https://github.com/google/nomulus/blob/f13cab5a580001dc6785e3644565bd01fb90a1ff/core/src/test/java/google/registry/model/registrar/RegistrarTest.java#L607)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Q: do we have any tests / way of verifying that methods in the @DualDatabaseTest classes are annotated with one of the db-specific test annotations? 
</blockquote></details>

Yes, we do, see [here](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/testing/DualDatabaseTestInvocationContextProvider.java;l=129-149?q=dual&ss=nomulus%2Fnomulus)

**Review by gbrodman — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/865)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/865)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
