### PR TITLE
Add cron config for the bsaDownload job in Sandbox

### PR DESCRIPTION
**Pull request by weiminyu**
This PR depends on go/r3pr/2256

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2267)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2267)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[`core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml` line 167 at r1](https://reviewable.io/reviews/google/nomulus/2267#-NnFgicQEzIfHp8WLyI6:-NnFgicQEzIfHp8WLyI7:b-l8y81p) ([raw file](https://github.com/google/nomulus/blob/0033e06b102d86048d1270dd9c8f1f7e26c0860a/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L167)):*
> ```XML
> 
>   <task>
>     <url><![CDATA[/_dr/task/bsaDownload]]></url>
> ```

It won't work as is: 
1) scheduler only supports backend service as of now, as that's where all existing requests used to be. 
2) All existing actions we have are GET endpoints, so scheduler creates GET actions by default.

I will need to update scheduler to allow for bsa service endpoints, that should cover 1. However for 2 would you be able to make `bsaDownloadAction` a GET and POST?

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2267)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[`core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml` line 167 at r1](https://reviewable.io/reviews/google/nomulus/2267#-NnFgicQEzIfHp8WLyI6:-NnK8jHG6fE2Tln_oace:bg5tnb1) ([raw file](https://github.com/google/nomulus/blob/0033e06b102d86048d1270dd9c8f1f7e26c0860a/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L167)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Yes, we can make it GET and POST.
</blockquote></details>

Now that https://github.com/google/nomulus/pull/2268 is merged you can add `<service>bsa</service>` here and that should work

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2267)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @ptkach)

___
*[`core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml` line 167 at r1](https://reviewable.io/reviews/google/nomulus/2267#-NnFgicQEzIfHp8WLyI6:-NnKb8062-0ncbQnbE9n:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0033e06b102d86048d1270dd9c8f1f7e26c0860a/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L167)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Now that https://github.com/google/nomulus/pull/2268 is merged you can add `<service>bsa</service>` here and that should work
</blockquote></details>

Done.

**Review by ptkach — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2267)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2267#-:-NnLPnV0BY6h4kI-thqu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

**Review by PunkinAnarcrassy — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2267)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
