### PR TITLE
Fix GCS bucket/subdir handling in IcannReportingStager

### PR DESCRIPTION
**Pull request by jianglai**
After the migration to the new GCS API it becomes apparent that the
BlobId.of() method needs to take the bucket name (without any trailing
directories) as the first argument. I did a search on all occurrences of
"BlobId.of" in the code base and verified that it is only in the ICANN
reporting job that the API was misused.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1265)

### CODE REVIEW

**Review by CydeWeys — COMMENTED** [review]
Commit/PR description can be more precise than "Fixed a bug in _____".  Should be something like "Fix GCS bucket/subdir handling in IcannReportingStager".  That way it's more findable if we need to look for it in the future (which given the change to this API, may well be the case).

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1265#-:-Mg7FR-yEZOzAj2x0pBo:bo7kh15)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by jianglai** [comment]
> Commit/PR description can be more precise than "Fixed a bug in _____". Should be something like "Fix GCS bucket/subdir handling in IcannReportingStager". That way it's more findable if we need to look for it in the future (which given the change to this API, may well be the case).
> 
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1265#-:-Mg7FR-yEZOzAj2x0pBo:bo7kh15)_ status: 0 of 1 files reviewed, all discussions resolved

Done.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1265)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java, line 256 at r2](https://reviewable.io/reviews/google/nomulus/1265#-Mg7HYYk6fgufQp1AIGj:-Mg7HYYk6fgufQp1AIGk:b-xz4o36) ([raw file](https://github.com/google/nomulus/blob/5d300172a256883242575c547b93321d4ca9b672/core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java#L256)):*
> ```Java
>     // Upload resulting CSV file to GCS
>     byte[] reportBytes = reportCsv.getBytes(UTF_8);
>     String reportFilename =
> ```

Rename this to `reportFilePath` or similar for clarity.
___
*[core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java, line 271 at r2](https://reviewable.io/reviews/google/nomulus/1265#-Mg7HbsQCvnt72UsYOek:-Mg7HbsQCvnt72UsYOel:b-89a4l7) ([raw file](https://github.com/google/nomulus/blob/5d300172a256883242575c547b93321d4ca9b672/core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java#L271)):*
> ```Java
>   /** Creates and stores a manifest file on GCS, indicating which reports were generated. */
>   void createAndUploadManifest(String subdir, ImmutableList<String> filenames) throws IOException {
>     String manifestFilename = String.format("%s/%s", subdir, MANIFEST_FILE_NAME);
> ```

Ditto

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1265)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java, line 256 at r2](https://reviewable.io/reviews/google/nomulus/1265#-Mg7HYYk6fgufQp1AIGj:-Mg7_ofo07YGy9hKBYEm:b-896fix) ([raw file](https://github.com/google/nomulus/blob/5d300172a256883242575c547b93321d4ca9b672/core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java#L256)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Rename this to `reportFilePath` or similar for clarity.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java, line 271 at r2](https://reviewable.io/reviews/google/nomulus/1265#-Mg7HbsQCvnt72UsYOek:-Mg7_ovB2RoV-jfZWbqL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/5d300172a256883242575c547b93321d4ca9b672/core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java#L271)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1265)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jianglai)

___
*[core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java, line 256 at r2](https://reviewable.io/reviews/google/nomulus/1265#-Mg7HYYk6fgufQp1AIGj:-Mg7bVGp5YSM76g9noKd:b-wd3v2j) ([raw file](https://github.com/google/nomulus/blob/5d300172a256883242575c547b93321d4ca9b672/core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java#L256)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Kind of looks a little strange with the lower case `p` rather than the way I suggested it ...

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1265#-:-Mg7baSL6JRc8QYrUimT:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1265)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @jianglai)

___
*[core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java, line 256 at r2](https://reviewable.io/reviews/google/nomulus/1265#-Mg7HYYk6fgufQp1AIGj:-Mg7dOgn2LCyGC9lqdoh:btje4tx) ([raw file](https://github.com/google/nomulus/blob/5d300172a256883242575c547b93321d4ca9b672/core/src/main/java/google/registry/reporting/icann/IcannReportingStager.java#L256)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Kind of looks a little strange with the lower case `p` rather than the way I suggested it ...
</blockquote></details>

Actually had to back out this change. The file name (with preceeding folders) are needed in creating the manifest file below...

**Pull request merged**
