### PR TITLE
Check for entity nonexistence in SqlBatchWriter

### PR DESCRIPTION
**Pull request by gbrodman**
Passing in an already-existing instance is an antipattern because it can lead to race conditions where something else modified the object in between when the pipeline loaded it and when you're saving it. The Write action should only be writing new entities.

We cannot check IDs for the objects (some IDs are not autogenerated so they might exist already). We also cannot call `insert` on the objects because the underlying JPA `persist` call adds the input object to the persistence context, meaning that any modifications (e.g. updateTimestamp) are reflected in the input object. Beam doesn't allow modification of input objects, so this throws an exception

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1824)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1824)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/google/nomulus/1824#-NFAEE8SCXBJakPzReeq):*
Actually I think we should require that all IDs are already filled in, for reasons stated in https://b.corp.google.com/issues/247806191#comment4 



_Code quote:_
```
  We cannot check IDs for the objects (some IDs are not autogenerated so
  they might exist already). We also cannot call `insert` on the objects
```

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1824)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/google/nomulus/1824#-NFAEE8SCXBJakPzReeq):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Actually I think we should require that all IDs are already filled in, for reasons stated in https://b.corp.google.com/issues/247806191#comment4 
</blockquote></details>

Fair point, that would match up with https://docs.google.com/document/d/1mFWC9zshHnAL3Cy-IoD3MKKylvWKN0bizZoE5i08rCg/edit# well. 

My initial thought is that that should wait for a separate PR because it'll require the implementation of the SQL-based ID allocation, right?

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1824)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/google/nomulus/1824#-NFAEE8SCXBJakPzReeq):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Fair point, that would match up with https://docs.google.com/document/d/1mFWC9zshHnAL3Cy-IoD3MKKylvWKN0bizZoE5i08rCg/edit# well. 

My initial thought is that that should wait for a separate PR because it'll require the implementation of the SQL-based ID allocation, right? 
</blockquote></details>

If you want to check in a version that just checks for updates now, please add a todo for the id check. 
___
*[`core/src/main/java/google/registry/beam/common/RegistryJpaIO.java` line 411 at r1](https://reviewable.io/reviews/google/nomulus/1824#-NFJyRDm9fIBVgooDZHP:-NFJyRDm9fIBVgooDZHQ:b-f4d4hm) ([raw file](https://github.com/google/nomulus/blob/3579639ffbe3c1ebd30433b082b5840d72536b19/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L411)):*
Could you inline the relevant commit message? It's easier to find in the code. 

> We also cannot call insert on the objects because the underlying JPA persist call adds the input object to the persistence context, meaning that any modifications (e.g. updateTimestamp) are reflected in the input object. Beam doesn't allow modification of input objects, so this throws an exception

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1824)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/google/nomulus/1824#-NFAEE8SCXBJakPzReeq):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

If you want to check in a version that just checks for updates now, please add a todo for the id check. 
</blockquote></details>

Yeah I see the ID check as completely separate, because once we implement that design doc, every object will always have an ID anyway regardless of whether it's an existing object or a new one. 
___
*[`core/src/main/java/google/registry/beam/common/RegistryJpaIO.java` line 411 at r1](https://reviewable.io/reviews/google/nomulus/1824#-NFJyRDm9fIBVgooDZHP:-NFKHeDS4lHOQ27-Ad6-:b-896fix) ([raw file](https://github.com/google/nomulus/blob/3579639ffbe3c1ebd30433b082b5840d72536b19/core/src/main/java/google/registry/beam/common/RegistryJpaIO.java#L411)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Could you inline the relevant commit message? It's easier to find in the code. 

> We also cannot call insert on the objects because the underlying JPA persist call adds the input object to the persistence context, meaning that any modifications (e.g. updateTimestamp) are reflected in the input object. Beam doesn't allow modification of input objects, so this throws an exception
</blockquote></details>

Done.

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1824)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

**Pull request merged**
