### PR TITLE
Expand nomulus get_domain command to load up deleted domain data too

### PR DESCRIPTION
**Pull request by ptkach**
This covers b/277237652

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2018)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2018)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/test/java/google/registry/tools/GetDomainCommandTest.java` line 121 at r2](https://reviewable.io/reviews/google/nomulus/2018#-NUcL3J3B-femBdHuxJo:-NUcL3J3B-femBdHuxJp:b-eby06z) ([raw file](https://github.com/google/nomulus/blob/40ba87549b6efb10533f646dbc83e33d15e61007/core/src/test/java/google/registry/tools/GetDomainCommandTest.java#L121)):*
> ```Java
> 
>   @Test
>   void testSuccess_printDeletedDomain() throws Exception {
> ```

Add a test where both a deleted domain and a current domain exist, and check that the command outputs both correctly.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2018)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/test/java/google/registry/tools/GetDomainCommandTest.java` line 121 at r2](https://reviewable.io/reviews/google/nomulus/2018#-NUcL3J3B-femBdHuxJo:-NUcXNMP1V2AITRQBiC6:b-8b11j9) ([raw file](https://github.com/google/nomulus/blob/877e360ff716b8841b48e4910434886f745c6653/core/src/test/java/google/registry/tools/GetDomainCommandTest.java#L121)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Add a test where both a deleted domain and a current domain exist, and check that the command outputs both correctly.
</blockquote></details>

Added

**Comment by ptkach** [comment]
@CydeWeys Kind ping on this

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2018#-:-NV6EyNM7-OcxYZJSJsw:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
