### PR TITLE
Re-add database migration state commands

### PR DESCRIPTION
**Pull request by CydeWeys**
These were removed in PR #1661, but we do still need them for the time being
until we complete the ID migration as well.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1702)

### CODE REVIEW

**Review by gbrodman — COMMENTED** [review]
Is this just a standard git revert, or are there other changes? 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1702#-:-N6TwVaN1VGL0yP2ZkoI:b-hvnxnu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by CydeWeys — COMMENTED** [review]
It's not a git revert, more of a checkout of some files from a specific revision and then manually merging in the file changes with some modifications to accommodate other changes that have gone in since then.  Just a revert wouldn't do it.  But it's mostly a revert in spirit.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1702#-:-N6hqCNKCu8KLACosdj3:b-fpymcu)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @gbrodman)

**Comment by gbrodman** [comment]
seems to be just formatting and checkstyle failing

**Review by CydeWeys — COMMENTED** [review]
Fixed presubmits (but they'll take a bit longer to run).  Feel free to LGTM if everything is good besides the presubmits; the presubmits enforce themselves.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1702#-:-N6j4aU_7yh5LqCS_WIg:b-o2zyv0)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1702)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
