### PR TITLE
Remove Duplicate billing events from the invoicing pipeline

### PR DESCRIPTION
**Pull request by jianglai**
The Distinct transform removes duplicates based on the serialized format
of the elements. By providing a deterministic coder, we can guarantee
that no duplicates exist.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2326)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2326)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2326)* status: all files reviewed, 3 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 310 at r1](https://reviewable.io/reviews/google/nomulus/2326#-Nqj7y390qvFYbTA1LUM:-Nqj7y390qvFYbTA1LUN:bjgid0a) ([raw file](https://github.com/google/nomulus/blob/8a218493dc856e04ae33ebe24775cdac6e989aca/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L310)):*
> ```Java
>   }
> 
>   static class BillingEventCoder extends AtomicCoder<BillingEvent> {
> ```

Huh, it's weird that doing this so manually is necessary.
___
*[`core/src/main/java/google/registry/beam/billing/InvoicingPipeline.java` line 106 at r1](https://reviewable.io/reviews/google/nomulus/2326#-Nqj7gJ48DouZDAEPzEq:-Nqj7gJ48DouZDAEPzEr:b-bohzrx) ([raw file](https://github.com/google/nomulus/blob/8a218493dc856e04ae33ebe24775cdac6e989aca/core/src/main/java/google/registry/beam/billing/InvoicingPipeline.java#L106)):*
> ```Java
>         .apply("Read BillingEvents from Cloud SQL", read)
>         .apply("Remove null elements", Filter.by(Objects::nonNull))
>         .apply("Remove duplicates", Distinct.create());
> ```

See, I knew it had to be easy enough!
___
*[`core/src/test/java/google/registry/beam/billing/InvoicingPipelineTest.java` line 369 at r1](https://reviewable.io/reviews/google/nomulus/2326#-Nqj7owdD9OmPhQuIg_D:-Nqj7owdD9OmPhQuIg_E:bdiqjij) ([raw file](https://github.com/google/nomulus/blob/8a218493dc856e04ae33ebe24775cdac6e989aca/core/src/test/java/google/registry/beam/billing/InvoicingPipelineTest.java#L369)):*
> ```Java
>             """);
>   }
> ```

I don't see a test that shows duplicates being removed?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2326)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/beam/billing/BillingEvent.java` line 310 at r1](https://reviewable.io/reviews/google/nomulus/2326#-Nqj7y390qvFYbTA1LUM:-NqnTEGb4e-CqGnXQCIW:b-8ywbn9) ([raw file](https://github.com/google/nomulus/blob/8a218493dc856e04ae33ebe24775cdac6e989aca/core/src/main/java/google/registry/beam/billing/BillingEvent.java#L310)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Huh, it's weird that doing this so manually is necessary.
</blockquote></details>

In theory we could take advantage of `AutoValueSchema`, but it only [works with `AutoValue` classes that have its getters named as `getXxx()`](https://stackoverflow.com/questions/62546191/how-do-i-use-an-autovalue-data-type-for-my-pcollection-in-apache-beam). I tried it and it doesn't seem worth it, given the amount of refactoring, and it also makes the code less legible than just using `xxx()` as getters.
___
*[`core/src/test/java/google/registry/beam/billing/InvoicingPipelineTest.java` line 369 at r1](https://reviewable.io/reviews/google/nomulus/2326#-Nqj7owdD9OmPhQuIg_D:-NqnTjAU0TrfcGDBp0JN:b-jr7w6o) ([raw file](https://github.com/google/nomulus/blob/8a218493dc856e04ae33ebe24775cdac6e989aca/core/src/test/java/google/registry/beam/billing/InvoicingPipelineTest.java#L369)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I don't see a test that shows duplicates being removed?
</blockquote></details>

It is not easy to write tests for because if we do the de-duplication `readFromCloudSql` function, we need to have SQL return duplicate results for testing. It is not possible as the primary ID is one of the fields tested for equality. I actually separated out the de-dup step to a separate function and wrote test for it, and it worked as expected. But I feel then we are just testing if `Distinct` works, which is outside the responsibility of the user of the Beam framework. Not to mention it adds an additional function just to call `Distinct`, which seems redundant. So I rolled back that part.

Most importantly, if we trust `Distinct` does [what it says it does](https://beam.apache.org/releases/javadoc/current/index.html?org/apache/beam/sdk/transforms/Distinct.html), we only need to make sure that the coder for `BillingEvent` is deterministic, and there is a test for that.

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2326)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @CydeWeys)

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2326)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @jianglai)

**Pull request merged**
