### PR TITLE
Add a command to generate ER diagram for SQL schema

### PR DESCRIPTION
**Pull request by hstonec**
Added a command to generate ER diagram and also a unit test to ensure that the golden ER diagrams, i.e. `db/src/main/resources/sql/er_diagram/brief_er_diagram.html` and `db/src/main/resources/sql/er_diagram/full_er_diagram.html`, are up to date.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/839)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 68 of 68 files at r1, 56 of 56 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/839)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec)

___
*[core/src/nonprod/java/google/registry/tools/GenerateSqlErDiagramCommand.java, line 79 at r1](https://reviewable.io/reviews/google/nomulus/839#-MJbo-cb33mVGQD5WP5-:-MJbo-cb33mVGQD5WP50:bu23fi5) ([raw file](https://github.com/google/nomulus/blob/091a0ba029b74d799570906f4dc02c71f69c5b9e/core/src/nonprod/java/google/registry/tools/GenerateSqlErDiagramCommand.java#L79)):*
> ```Java
>   @Parameter(
>       names = "--diagram_type",
>       description = "Type of the generated ER diagram (defaults to ALL).")
> ```

Does this automatically show the options for an enum type?  If not, please add them to the message.
___
*[core/src/nonprod/java/google/registry/tools/GenerateSqlErDiagramCommand.java, line 184 at r1](https://reviewable.io/reviews/google/nomulus/839#-MJc0rbO6D91suxeMaxT:-MJc0rbO6D91suxeMaxU:b-xj3gj6) ([raw file](https://github.com/google/nomulus/blob/091a0ba029b74d799570906f4dc02c71f69c5b9e/core/src/nonprod/java/google/registry/tools/GenerateSqlErDiagramCommand.java#L184)):*
> ```Java
>         OutputOptionsBuilder.newOutputOptions(DiagramOutputFormat.htmlx, outputFile);
> 
>     SchemaCrawlerExecutable executable = new SchemaCrawlerExecutable(command);
> ```

If this is, as the name implies, an executable, where does it live?  Do users need to install something or will it get pulled in with our dependencies?
___
*[core/src/nonprod/resources/google/registry/tools/svg-pan-zoom.min.js, line 0 at r1](https://reviewable.io/reviews/google/nomulus/839#-MJc1Qn71Ji9R6AF_1PY:-MJc1Qn71Ji9R6AF_1PZ:b-uv5q2t) ([raw file](https://github.com/google/nomulus/blob/091a0ba029b74d799570906f4dc02c71f69c5b9e/core/src/nonprod/resources/google/registry/tools/svg-pan-zoom.min.js#L0)):*
Do we have source for this?  Where does it come from?

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/839)* status: 11 of 68 files reviewed, 3 unresolved discussions (waiting on @mindhog)

___
*[core/src/nonprod/java/google/registry/tools/GenerateSqlErDiagramCommand.java, line 79 at r1](https://reviewable.io/reviews/google/nomulus/839#-MJbo-cb33mVGQD5WP5-:-MJdD8C20wSEoTeWpidD:b-896fix) ([raw file](https://github.com/google/nomulus/blob/091a0ba029b74d799570906f4dc02c71f69c5b9e/core/src/nonprod/java/google/registry/tools/GenerateSqlErDiagramCommand.java#L79)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Does this automatically show the options for an enum type?  If not, please add them to the message.
</blockquote></details>

Done.
___
*[core/src/nonprod/java/google/registry/tools/GenerateSqlErDiagramCommand.java, line 184 at r1](https://reviewable.io/reviews/google/nomulus/839#-MJc0rbO6D91suxeMaxT:-MJdB0Nq-xHrx_BT2u7v:b-hdehg6) ([raw file](https://github.com/google/nomulus/blob/091a0ba029b74d799570906f4dc02c71f69c5b9e/core/src/nonprod/java/google/registry/tools/GenerateSqlErDiagramCommand.java#L184)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

If this is, as the name implies, an executable, where does it live?  Do users need to install something or will it get pulled in with our dependencies?
</blockquote></details>

The name is confusing and the user doesn't need to install anything, all the dependencies will be pulled by gradle.

There were some dependency missing in the previous revision and I fixed them in the latest revision.
___
*[core/src/nonprod/resources/google/registry/tools/svg-pan-zoom.min.js, line  at r1](https://reviewable.io/reviews/google/nomulus/839#-MJc1Qn71Ji9R6AF_1PY:-MJdBL959MgVlAMoxSm-:b-ncgmyn) ([raw file](https://github.com/google/nomulus/blob/091a0ba029b74d799570906f4dc02c71f69c5b9e/core/src/nonprod/resources/google/registry/tools/svg-pan-zoom.min.js#L)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Do we have source for this?  Where does it come from?
</blockquote></details>

Not sure why reviewable doesn't display the code, it is just a normal JS code file downloaded from https://github.com/ariutta/svg-pan-zoom. These information are also put at the beginning of the fil

**Review by mindhog — COMMENTED** [review]
> Reviewed 57 of 57 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/839)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by mindhog — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/839#-:-MJg1E3i6BMVBbmUu3OI:bb6ywmx)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Pull request merged**
