### PR TITLE
Add RegistrarUpdateHistory objects for console changes

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2585)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 7 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2585)* status: 7 of 13 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 267 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8bx9Ln0-7XCAk1HrBH:-O8bx9Ln0-7XCAk1HrBI:b1uj509) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L267)):*
> ```Java
>   }
> 
>   protected void finishAndPersistConsoleUpdateHistory(ConsoleUpdateHistory.Builder<?, ?> builder) {
> ```

Do we want to log the response? It'd def be helpful, although might present a separate complexities for when we send sensitive data in response
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 59 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8bwith-AaolADzERfg:-O8bwith-AaolADzERfh:b-isez80) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L59)):*
> ```Java
>       new PasswordOnlyTransportCredentials();
>   private final AuthenticatedRegistrarAccessor registrarAccessor;
>   private final Gson gson;
> ```

At this point I wonder if it'd make sense to make gson a part of `consoleApiParams`?
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 118 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8bxbMF5ekTVS9ir4vd:-O8bxbMF5ekTVS9ir4ve:b4m4i7j) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L118)):*
> ```Java
>                       .setType(ConsoleUpdateHistory.Type.REGISTRAR_UPDATE)
>                       .setRegistrar(updatedRegistrar)
>                       .setRequestBody(gson.toJson(eppRequestBody)));
> ```

Hmm I'm not so sure about this one - `eppRequestBody` contains sensitive information and storing it in db as a plain text is...questionable?
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUpdateRegistrarAction.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8byAntA9kKT5cADqsW:-O8byAntA9kKT5cADqsX:b-rfila) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleUpdateRegistrarAction.java#L57)):*
> ```Java
>   ConsoleUpdateRegistrarAction(
>       ConsoleApiParams consoleApiParams,
>       Gson gson,
> ```

Same as others - probably worth making it a part of `consoleApiParams`, refactoring it out later will be more difficult if this is merged

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2585)* status: 1 of 30 files reviewed, 4 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java` line 267 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8bx9Ln0-7XCAk1HrBH:-O8cpYIZ3V2--2g2JwXw:b-up5wu2) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleApiAction.java#L267)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Do we want to log the response? It'd def be helpful, although might present a separate complexities for when we send sensitive data in response
</blockquote></details>

Yeah, I think it might not be super useful to log the response since we're also saving the state of the entity at that time. 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 59 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8bwith-AaolADzERfg:-O8csHGAEz35e5r-JCLL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L59)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

At this point I wonder if it'd make sense to make gson a part of `consoleApiParams`?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 118 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8bxbMF5ekTVS9ir4vd:-O8cpKCQE_z3M9TCzabF:bgvyvhu) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L118)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Hmm I'm not so sure about this one - `eppRequestBody` contains sensitive information and storing it in db as a plain text is...questionable?
</blockquote></details>

yeah, the more I'm thinking about it the more we probably might just want to remove that field from the DB entirely. Probably we could also remove the HTTP method as well (since it's probably not going to be useful)

Thoughts?
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleUpdateRegistrarAction.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8byAntA9kKT5cADqsW:-O8csHh_AQNqyrBEAObi:b-896fix) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleUpdateRegistrarAction.java#L57)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Same as others - probably worth making it a part of `consoleApiParams`, refactoring it out later will be more difficult if this is merged
</blockquote></details>

Done.

**Review by gbrodman — COMMENTED** [review]
> Dismissed @ptkach from a discussion.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2585)* status: 28 of 30 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 118 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8bxbMF5ekTVS9ir4vd:-OBBzD6675jpbY8CmO0i:b4c28ab) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L118)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I think we should keep it, but we need to remove any sensitive data before saving manually. I can't think of any generic way to handle this. Can you?
</blockquote></details>

I haven't been able to come up with one. 

Do you know of any concrete use cases where it could be helpful? If not I'm leaning toward deleting it to make things simpler / smaller

**Review by gbrodman — COMMENTED** [review]
friendly ping

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2585#-:-OBfsqqY29R7eWES7zh-:b-50swta)* status: 25 of 30 files reviewed, 1 unresolved discussion (waiting on @ptkach)

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2585)* status: 25 of 30 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 118 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8bxbMF5ekTVS9ir4vd:-OC0BQgB4-l6kbyhKZ9D:b-9rtmoe) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L118)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I haven't been able to come up with one. 

Do you know of any concrete use cases where it could be helpful? If not I'm leaning toward deleting it to make things simpler / smaller
</blockquote></details>

We recently had this issue with user trying to update security settings - ip whitelist and ssl cert, which they claimed had been failing. It's because there was a video of the screen I could tell that the update came through, but it was the email sending what failed, which in turned hanged the request for a while. GCP logs do not store this data and it's not always possible to get users to provide the data that being sent. Speaking of HTTP method - that should also stay we now have 4 methods in Users action.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2585)* status: 25 of 30 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java` line 118 at r1](https://reviewable.io/reviews/google/nomulus/2585#-O8bxbMF5ekTVS9ir4vd:-OC0L7DA7VdIHIXU9Xqk:b-4fxzj8) ([raw file](https://github.com/google/nomulus/blob/dbbcba3e89ed4cdc350b5003fcabd61f34939768/core/src/main/java/google/registry/ui/server/console/ConsoleEppPasswordAction.java#L118)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

We recently had this issue with user trying to update security settings - ip whitelist and ssl cert, which they claimed had been failing. It's because there was a video of the screen I could tell that the update came through, but it was the email sending what failed, which in turned hanged the request for a while. GCP logs do not store this data and it's not always possible to get users to provide the data that being sent. Speaking of HTTP method - that should also stay we now have 4 methods in Users action.
</blockquote></details>

Fair enough. We can manually sanitize the password data here, and everywhere else the JSON representation of the registrar should prevent us from actually including any password information. How does that sound?

**Review by ptkach — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2585)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Pull request merged**
