### PR TITLE
Add OT&E create and status to the new console

### PR DESCRIPTION
**Pull request by ptkach**
This change allows us to safely delete the following from the old console:

[ConsoleOteSetupAction](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/ui/server/registrar/ConsoleOteSetupAction.java;bpv=1;bpt=1;l=61?q=ConsoleOte&ss=nomulus%2Fnomulus&gsn=ConsoleOteSetupAction&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgithub.com%2Fgoogle%2Fnomulus%3Flang%3Djava%3Fpath%3Dgoogle.registry.ui.server.registrar.ConsoleOteSetupAction%23ec203b4d693fdd53d26709f78a800106909d6115ada375cf0caffa6a3982692b) and [OteStatusAction](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/ui/server/registrar/OteStatusAction.java;bpv=1;bpt=1;l=49?gsn=OteStatusAction&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgithub.com%2Fgoogle%2Fnomulus%3Flang%3Djava%3Fpath%3Dgoogle.registry.ui.server.registrar.OteStatusAction%233a35b651d6187eb7963081caf1442b8b44a5900cef1db7eb8cf4f1240dd4d7bb) and tests obviously [OteStatusActionTest](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/ui/server/registrar/OteStatusActionTest.java;bpv=1;bpt=1;l=42?q=otestatusac&ss=nomulus%2Fnomulus&gsn=OteStatusActionTest&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgithub.com%2Fgoogle%2Fnomulus%3Flang%3Djava%3Fpath%3Dgoogle.registry.ui.server.registrar.OteStatusActionTest%23ab5ce755f125527cfd6fbd6a4c2a0e359d25797a38d9f6dde67ef1bfad857978) and [ConsoleOteSetupActionTest](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/ui/server/registrar/ConsoleOteSetupActionTest.java;bpv=1;bpt=1;l=63?gsn=ConsoleOteSetupActionTest&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgithub.com%2Fgoogle%2Fnomulus%3Flang%3Djava%3Fpath%3Dgoogle.registry.ui.server.registrar.ConsoleOteSetupActionTest%235d1300554a25709ef384bdd862da29c3c802229f84530fa3147b3865a74de3b3)

I merged both actions into 1 as I don't really see why they should be separete as they have a large overlap in logic. I've reviewed the guides used by Tech support to conduct said operations and simplified the logic, eg removed password field from the request.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2534)

### CODE REVIEW

**Comment by ptkach** [comment]
I'm working on front-end part in a separate PR

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 7 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2534)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java` line 111 at r2](https://reviewable.io/reviews/google/nomulus/2534#-O4vJfx82trcQ5au1zZV:-O4vJfx82trcQ5au1zZW:b-2vx8jr) ([raw file](https://github.com/google/nomulus/blob/cc29b487fba9399d3cec56d2b23aa789a833a3c5/core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java#L111)):*
> ```Java
>         OteAccountBuilder.forRegistrarId(this.oteCreateData.get().registrarId)
>             .addUser(this.oteCreateData.get().registrarEmail)
>             .setPassword(password);
> ```

I think we probably want to return the password in the data somehow right? We do for the existing frontend action and the existing nomulus tool command

we probably want a test to verify that the password is returned too right? 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java` line 124 at r2](https://reviewable.io/reviews/google/nomulus/2534#-O4vEjt89VKEdyEMiqEF:-O4vEjt89VKEdyEMiqEG:biufb03) ([raw file](https://github.com/google/nomulus/blob/cc29b487fba9399d3cec56d2b23aa789a833a3c5/core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java#L124)):*
> ```Java
> 
>     if (!user.getUserRoles().hasGlobalPermission(ConsolePermission.EDIT_REGISTRAR_DETAILS)) {
>       setFailedResponse("User doesn't have a permission to create OT&E accounts", SC_BAD_REQUEST);
> ```

I think we want to change the message here since this is the GET request (it's just checking on the status)
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java` line 128 at r2](https://reviewable.io/reviews/google/nomulus/2534#-O4vDvmy3epg-cFtCttN:-O4vDvmy3epg-cFtCttO:b-ayebwx) ([raw file](https://github.com/google/nomulus/blob/cc29b487fba9399d3cec56d2b23aa789a833a3c5/core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java#L128)):*
> ```Java
>     }
> 
>     String baseClientId = OteAccountBuilder.getBaseRegistrarId(registrarId);
> ```

can we call it baseRegistrarId instead? trying to get rid of the "client ID" usage in the codebase whenever possible

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2534)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/model/registrar/RegistrarBase.java` line 236 at r3](https://reviewable.io/reviews/google/nomulus/2534#-O4vWx5J1_ydT38odz_H:-O4vWx5J1_ydT38odz_I:b-i4zcz1) ([raw file](https://github.com/google/nomulus/blob/878ff5db6fd0f5165cee504198c13dfa7e29dda6/core/src/main/java/google/registry/model/registrar/RegistrarBase.java#L236)):*
> ```Java
> 
>   /** The type of this registrar. */
>   @Expose
> ```

I realized I'd need this field on UI to know when to render status check button. I don't think it risks any non-public information exposure, please correct me if I'm wrong
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java` line 111 at r2](https://reviewable.io/reviews/google/nomulus/2534#-O4vJfx82trcQ5au1zZV:-O4vMhKw9WYsaeIZ6M7-:blt5xv5) ([raw file](https://github.com/google/nomulus/blob/cc29b487fba9399d3cec56d2b23aa789a833a3c5/core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java#L111)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we probably want to return the password in the data somehow right? We do for the existing frontend action and the existing nomulus tool command

we probably want a test to verify that the password is returned too right?
</blockquote></details>

That's right, thanks
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java` line 124 at r2](https://reviewable.io/reviews/google/nomulus/2534#-O4vEjt89VKEdyEMiqEF:-O4vNPheAHEKfCnCHD2f:b-bu91xm) ([raw file](https://github.com/google/nomulus/blob/cc29b487fba9399d3cec56d2b23aa789a833a3c5/core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java#L124)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think we want to change the message here since this is the GET request (it's just checking on the status)
</blockquote></details>

Updated
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java` line 128 at r2](https://reviewable.io/reviews/google/nomulus/2534#-O4vDvmy3epg-cFtCttN:-O4vWviK-N7F3--iOsl8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/cc29b487fba9399d3cec56d2b23aa789a833a3c5/core/src/main/java/google/registry/ui/server/console/ConsoleOteAction.java#L128)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

can we call it baseRegistrarId instead? trying to get rid of the "client ID" usage in the codebase whenever possible
</blockquote></details>

Done.

**Review by gbrodman — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2534)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
