### PR TITLE
Maintain only one row in the TmchCrl table at all times

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/869)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/869)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/tmch/TmchCrl.java, line 89 at r1](https://reviewable.io/reviews/google/nomulus/869#-MLnvBZeBahKA0CVL_sV:-MLnvBZf2VvELMjPfDN8:b2p6qv8) ([raw file](https://github.com/google/nomulus/blob/40212cc01f5bbacc97ac0d438d314cf73e56c2b7/core/src/main/java/google/registry/model/tmch/TmchCrl.java#L89)):*
> ```Java
>                             .executeUpdate();
>                         jpaTm().putWithoutBackup(tmchCrl);
>                       });
> ```

Any reason we're not just using the SINGLETON_ID as the primary key for this?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/869)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/tmch/TmchCrl.java, line 89 at r1](https://reviewable.io/reviews/google/nomulus/869#-MLnvBZeBahKA0CVL_sV:-MLnwS9lCD7U7-ex0rq6:b-ox46n6) ([raw file](https://github.com/google/nomulus/blob/40212cc01f5bbacc97ac0d438d314cf73e56c2b7/core/src/main/java/google/registry/model/tmch/TmchCrl.java#L89)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Any reason we're not just using the SINGLETON_ID as the primary key for this?
</blockquote></details>

It's better to not have extra fields if we don't need them

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/869)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/tmch/TmchCrl.java, line 89 at r1](https://reviewable.io/reviews/google/nomulus/869#-MLnvBZeBahKA0CVL_sV:-MLnyJip2qFbYPotDpbC:b-c75kvi) ([raw file](https://github.com/google/nomulus/blob/40212cc01f5bbacc97ac0d438d314cf73e56c2b7/core/src/main/java/google/registry/model/tmch/TmchCrl.java#L89)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

It's better to not have extra fields if we don't need them 
</blockquote></details>

Why so?  There's a single row in the table, so it's not as though it's going to consume a lot of extra space.  And you could use the Ignore annotation to keep it out of datastore.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/869)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/tmch/TmchCrl.java, line 89 at r1](https://reviewable.io/reviews/google/nomulus/869#-MLnvBZeBahKA0CVL_sV:-MLnza5-8k9sNPrYxeZe:b3avtfw) ([raw file](https://github.com/google/nomulus/blob/40212cc01f5bbacc97ac0d438d314cf73e56c2b7/core/src/main/java/google/registry/model/tmch/TmchCrl.java#L89)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Why so?  There's a single row in the table, so it's not as though it's going to consume a lot of extra space.  And you could use the Ignore annotation to keep it out of datastore.
</blockquote></details>

There's just no need -- see discussion on https://reviewable.io/reviews/google/nomulus/860#-

**Review by mindhog — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/869)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/tmch/TmchCrl.java, line 89 at r1](https://reviewable.io/reviews/google/nomulus/869#-MLnvBZeBahKA0CVL_sV:-MLo2zuT295kosIN_ocz:b1uh1w3) ([raw file](https://github.com/google/nomulus/blob/40212cc01f5bbacc97ac0d438d314cf73e56c2b7/core/src/main/java/google/registry/model/tmch/TmchCrl.java#L89)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

There's just no need -- see discussion on https://reviewable.io/reviews/google/nomulus/860#- 
</blockquote></details>

well, it would solve this problem quite nicely :-)

**Pull request merged**
