### PR TITLE
Remove CommitLog and MapReduce-related code

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1670)

### CODE REVIEW

**Comment by mindhog** [comment]
Seems like this dowgrades a number of things.  `show_upgrade_diffs` output is:

```
Package version change report:
change package-name: {old versions} -> {new versions}
=====================================================

updated com.google.api-client:google-api-client: {1.35.0, 1.34.1, 1.35.1} -> {1.35.0, 1.34.0, 1.34.1}
updated com.google.api:gax: {2.18.1} -> {2.18.1, 2.16.0}
updated com.google.apis:google-api-services-storage: {v1-rev20220604-1.32.1} -> {v1-rev20220509-1.32.1}
updated com.google.auth:google-auth-library-credentials: {1.7.0} -> {1.6.0, 1.7.0}
updated com.google.auth:google-auth-library-oauth2-http: {1.7.0} -> {1.6.0, 1.7.0}
updated com.google.cloud:google-cloud-storage: {2.8.0} -> {2.7.2}
updated com.google.errorprone:error_prone_annotations: {2.13.1, 2.11.0, 2.14.0, 2.3.4, 2.7.1} -> {2.13.1, 2.11.0, 2.3.4, 2.7.1}
updated com.google.http-client:google-http-client-apache-v2: {1.42.0, 1.41.8} -> {1.41.7, 1.41.8}
updated com.google.http-client:google-http-client-appengine: {1.42.0, 1.41.8} -> {1.41.8}
updated com.google.http-client:google-http-client-gson: {1.42.0, 1.41.8} -> {1.41.7, 1.41.8}
updated com.google.http-client:google-http-client: {1.42.0, 1.41.8} -> {1.41.7, 1.41.8}
updated com.google.oauth-client:google-oauth-client: {1.34.0, 1.34.1, 1.33.3} -> {1.34.0, 1.33.2, 1.33.3}
updated org.objenesis:objenesis: {2.1, 3.2, 1.2} -> {2.1, 3.2}
updated io.netty:netty-tcnative-boringssl-static: {2.0.46.Final, 2.0.53.Final} -> {2.0.46.Final, 2.0.52.Final}
updated io.netty:netty-tcnative-classes: {2.0.46.Final, 2.0.53.Final} -> {2.0.46.Final, 2.0.52.Final}
updated com.google.api-client:google-api-client-appengine: {1.35.1} -> {1.35.0}
updated com.google.api-client:google-api-client-java6: {1.35.1} -> {1.35.0}
updated com.google.api-client:google-api-client-servlet: {1.35.1} -> {1.35.0}
updated com.google.apis:google-api-services-sqladmin: {v1beta4-rev20220513-1.32.1} -> {v1beta4-rev20220323-1.32.1}
updated com.google.cloud.sql:jdbc-socket-factory-core: {1.6.1} -> {1.6.0}
updated com.google.oauth-client:google-oauth-client-appengine: {1.34.1} -> {1.34.0}
updated com.google.oauth-client:google-oauth-client-java6: {1.34.1} -> {1.34.0}
updated com.google.oauth-client:google-oauth-client-jetty: {1.34.1} -> {1.34.0}
updated com.google.oauth-client:google-oauth-client-servlet: {1.34.1} -> {1.34.0}
updated org.postgresql:postgresql: {42.4.0} -> {42.3.6}
updated com.google.cloud:google-cloud-nio: {0.124.4} -> {0.124.2}
updated org.apache.tomcat:tomcat-annotations-api: {10.1.0-M16} -> {10.1.0-M15}
updated com.google.cloud.sql:postgres-socket-factory: {1.6.1} -> {1.6.0}
updated com.sun.xml.bind:jaxb-osgi: {4.0.0} -> {4.0.0-M4}
removed com.google.appengine.tools:appengine-mapreduce
removed com.googlecode.charts4j:charts4j
removed it.unimi.dsi:fastutil
```

**Review by mindhog — APPROVED** [review]
I'm not terribly concerned about the downgrades, though we might want to try a dependency upgrade to lock some of this stuff into newer versions.

> Reviewed 264 of 264 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1670#-:-N5GEiu_9KTHskyaN3yL:bbt6xv6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
Yeah, the dependency downgrade is due to the removal of the mapreduce package. I'm not quite sure why that happens -- my initial thought is that we might want to just fix that in a separate dependency upgrade PR afterward. Thoughts? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1670#-:-N5GI-9U8pbkbQU1wIAk:bjscsmf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by mindhog — APPROVED** [review]
Yeah, I'm ok with us fixing it afterwards.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1670#-:-N5GQxV_4JHYxn6FAJ_S:bswxoea)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
