### PR TITLE
Use the new IANA url for registrar RDAP base URLs

### PR DESCRIPTION
**Pull request by gbrodman**
Fortunately this no longer requires a log-in, we can just send a GET
request and receive a CSV result in return.

This also adds the apache-commons CSV parser to the dependencies and
uses it for claims list and SMDRL parsing.

See https://b.corp.google.com/issues/237784559 for more details 

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1703)

### CODE REVIEW

**Comment by gbrodman** [comment]
fyi this is no longer a work in progress, should be good to review I think

**Review by CydeWeys — CHANGES_REQUESTED** [review]
Can you split out the `CsvParser` conversion on claims list/etc. into a separate PR?  Those changes don't seem to be germane to this PR (rather, they're a follow-up refactoring).  Don't want to block this review on RDAP base URLs for that stuff.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1703#-:-N6iopgi9DhrPKHBEHww:b4prmok)* status: 0 of 134 files reviewed, 7 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6ijRhJ655pbO8DcKZd:-N6ijRhJ655pbO8DcKZe:b-urh1yk) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L69)):*
> ```Java
>     ImmutableMap<String, String> ianaIdsToUrls = getIanaIdsToUrls();
>     Registrar.loadAllKeysCached()
>         .forEach((key) -> tm().transact(() -> processRegistrar(key, ianaIdsToUrls)));
> ```

Unnecessary parentheses?



_Code quote:_
```Java
(key)
```
___
*[`core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6ijWdc0uhuf6GNOC-R:-N6ijWdc0uhuf6GNOC-S:b-gh0n01) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L69)):*
> ```Java
>     ImmutableMap<String, String> ianaIdsToUrls = getIanaIdsToUrls();
>     Registrar.loadAllKeysCached()
>         .forEach((key) -> tm().transact(() -> processRegistrar(key, ianaIdsToUrls)));
> ```

I don't think each registrar needs a separate transaction, especially seeing as how the vast majority of them aren't being updated.
___
*[`core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java` line 114 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6imOfwELLKiwYQTimp:-N6imOfwELLKiwYQTimq:bvtv7e1) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L114)):*
> ```Java
>     if (registrar.getRdapBaseUrls().equals(baseUrls)) {
>       logger.atInfo().log(
>           "No change in RDAP base URLs for registrar %s", registrar.getRegistrarId());
> ```

Considering how this happens >99% of the time, it's probably not worth logging each one individually, as that's just going to be noisy.  Better to simply keep a running tally of how many had no change, and then log a single line at the end, something like "No change in RDAP base URLs for NN registrars."
___
*[`core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java` line 123 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6inEGzAH8vXyNg2oNw:-N6inEGzAH8vXyNg2oNx:bjn40wy) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L123)):*
> ```Java
>           registrar.getRegistrarId(), registrar.getRdapBaseUrls(), baseUrls);
>     }
>     tm().put(registrar.asBuilder().setRdapBaseUrls(baseUrls).build());
> ```

Why even call this when the know the URLs are unchanged?  Why not only call it when there's an actual update to be made?
___
*[`core/src/main/java/google/registry/tmch/ClaimsListParser.java` line 56 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6inbrc-SZ_Ymii3wS-:-N6inbrc-SZ_Ymii3wS0:blq2a3t) ([raw file](https://github.com/google/nomulus/blob/2a5b427a808c3af4fc0154cf9a28b6e54a3dd319/core/src/main/java/google/registry/tmch/ClaimsListParser.java#L56)):*
> ```Java
>     // Second line contains headers: DNL,lookup-key,insertion-datetime
>     List<String> secondLine = Splitter.on(',').splitToList(lines.get(1));
>     checkArgument(secondLine.size() == 3, String.format(
> ```

There's a lot of error-checking here that you're removing.  Are you sure that the new code is as safe?  I feel like I've seen some of these error conditions actually hit in prod before?  Same for Smdrl below.
___
*[`core/src/main/java/google/registry/tmch/SmdrlCsvParser.java` line 58 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6io3eH-8lMrwCQiydF:-N6io3eH-8lMrwCQiydG:bz87ely) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/tmch/SmdrlCsvParser.java#L58)):*
> ```Java
>             .setSkipHeaderRecord(true)
>             .build()
>             .parse(new StringReader(Joiner.on('\n').join(lines.subList(1, lines.size()))));
> ```

Something feels off here.  If we've already split up the input into lines, then why are we reconstituting it for the sake of the `CsvParser`?  Seems like the method definition `parse(List<String> lines)` is now wrong?  Same for `ClaimsListParser` above.
___
*[`core/src/main/java/google/registry/tmch/TmchDnlAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6ioPIMBdSmcphnlyIp:-N6ioPIMBdSmcphnlyIq:bnkuijc) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/tmch/TmchDnlAction.java#L55)):*
> ```Java
>     try {
>       ImmutableList<String> lines =
>           marksdb.fetchSignedCsv(marksdbDnlLoginAndPassword, DNL_CSV_PATH, DNL_SIG_PATH);
> ```

Looks like `fetchSignedCsv()` should now be returning a `String` containing the entire file contents, rather than parsing it into discrete lines first only to reconstitute the file prior to sending it to `CsvParser`.

**Review by gbrodman — COMMENTED** [review]
yeah fair enough 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1703#-:-N6ir0CgDS__Vrs9KGEN:b-9qmi90)* status: 0 of 134 files reviewed, 7 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6ijWdc0uhuf6GNOC-R:-N6itO4T-NZ8iXgTHlWY:b3d71qm) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L69)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I don't think each registrar needs a separate transaction, especially seeing as how the vast majority of them aren't being updated.
</blockquote></details>

sure, i was just keeping the semantics the same 
___
*[`core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java` line 69 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6ijRhJ655pbO8DcKZd:-N6itPds1Snd9jSMGeDW:b-896fix) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L69)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Unnecessary parentheses?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java` line 114 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6imOfwELLKiwYQTimp:-N6istdF2Z5iWQ8s8fNi:b1li5f1) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L114)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Considering how this happens >99% of the time, it's probably not worth logging each one individually, as that's just going to be noisy.  Better to simply keep a running tally of how many had no change, and then log a single line at the end, something like "No change in RDAP base URLs for NN registrars."
</blockquote></details>

sure sounds good 
___
*[`core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java` line 123 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6inEGzAH8vXyNg2oNw:-N6ipG31CVxfx6GgHhqr:b-iqnx5w) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/rdap/UpdateRegistrarRdapBaseUrlsAction.java#L123)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why even call this when the know the URLs are unchanged?  Why not only call it when there's an actual update to be made?
</blockquote></details>

this is actually what happens already due to the return statement -- it'll be clearer with the new code though 
___
*[`core/src/main/java/google/registry/tmch/ClaimsListParser.java` line 56 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6inbrc-SZ_Ymii3wS-:-N6iqcvr4omzEeSx5hCV:b-k7wdfr) ([raw file](https://github.com/google/nomulus/blob/2a5b427a808c3af4fc0154cf9a28b6e54a3dd319/core/src/main/java/google/registry/tmch/ClaimsListParser.java#L56)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There's a lot of error-checking here that you're removing.  Are you sure that the new code is as safe?  I feel like I've seen some of these error conditions actually hit in prod before?  Same for Smdrl below.
</blockquote></details>

If the provided data is incorrect, it fortunately throws similar IllegalArgumentExceptions. You can see that in the test cases. 

Moot for now, moving to other PR 
___
*[`core/src/main/java/google/registry/tmch/SmdrlCsvParser.java` line 58 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6io3eH-8lMrwCQiydF:-N6iqNjQ6j9pJ_T7T7AG:b-r39r3p) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/tmch/SmdrlCsvParser.java#L58)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Something feels off here.  If we've already split up the input into lines, then why are we reconstituting it for the sake of the `CsvParser`?  Seems like the method definition `parse(List<String> lines)` is now wrong?  Same for `ClaimsListParser` above.
</blockquote></details>

It's because the result that the remote URL gives us isn't actually a proper CSV. It's something like 

```
randomData,dateTime
columnName1,columnName2
row1value1,row1value2
row2value1,row2value2
```

etc
So we need to know to skip the first line. 

Moot for new, moving to other PR 
___
*[`core/src/main/java/google/registry/tmch/TmchDnlAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/1703#-N6ioPIMBdSmcphnlyIp:-N6iqurNEsjXfWWBUcSO:b-ujtqm8) ([raw file](https://github.com/google/nomulus/blob/0efffc38b3d98b5d1d6a4d79edeb640fbe4cb5f6/core/src/main/java/google/registry/tmch/TmchDnlAction.java#L55)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Looks like `fetchSignedCsv()` should now be returning a `String` containing the entire file contents, rather than parsing it into discrete lines first only to reconstitute the file prior to sending it to `CsvParser`.
</blockquote></details>

annoyingly, it's not a proper CSV. See the discussion in SmdrlCsvParser

**Review by mindhog — COMMENTED** [review]
```
$ python3 config/show_upgrade_diffs.py gbrodman rdapUrls
updated com.google.api-client:google-api-client: {1.35.0, 1.34.1, 1.34.0} -> {1.35.1, 1.35.2, 1.35.0}                                                                                        
updated com.google.api.grpc:proto-google-common-protos: {2.8.3} -> {2.9.0}                                                                                                                   
updated com.google.api.grpc:proto-google-iam-v1: {1.3.4} -> {1.4.1}                                                                                                                          
updated com.google.api:api-common: {2.2.0} -> {2.2.1}                                                                                                                                        
updated com.google.api:gax-httpjson: {0.103.1} -> {0.103.2}                                                                                                                                  
updated com.google.api:gax: {2.16.0, 2.18.1} -> {2.18.1, 2.18.2}                                                                                                                             
updated com.google.apis:google-api-services-storage: {v1-rev20220509-1.32.1} -> {v1-rev20220608-1.32.1}                                                                                      
updated com.google.auth:google-auth-library-credentials: {1.6.0, 1.7.0} -> {1.8.0, 1.7.0}                                                                                                    
updated com.google.auth:google-auth-library-oauth2-http: {1.6.0, 1.7.0} -> {1.8.0, 1.7.0}                                                                                                    
updated com.google.cloud:google-cloud-core-http: {2.7.1} -> {2.8.0}                                                                                                                          
updated com.google.cloud:google-cloud-core: {2.7.1} -> {2.8.0}                                                                                                                               
updated com.google.cloud:google-cloud-storage: {2.7.2} -> {2.9.0, 2.9.2}                                                                                                                     
updated com.google.errorprone:error_prone_annotations: {2.7.1, 2.3.4, 2.11.0, 2.13.1} -> {2.7.1, 2.3.4, 2.14.0, 2.11.0}                                                                      
updated com.google.http-client:google-http-client-apache-v2: {1.41.7, 1.41.8} -> {1.42.0, 1.41.8}                                                                                            
updated com.google.http-client:google-http-client-appengine: {1.41.8} -> {1.42.0}                                                                                                            
updated com.google.http-client:google-http-client-gson: {1.41.7, 1.41.8} -> {1.42.0, 1.41.8}                                                                                                 
updated com.google.http-client:google-http-client-jackson2: {1.41.8} -> {1.42.0}                                                                                                             
updated com.google.http-client:google-http-client: {1.41.7, 1.41.8} -> {1.42.0, 1.41.8}                                                                                                      
updated com.google.oauth-client:google-oauth-client: {1.33.2, 1.33.3, 1.34.0} -> {1.34.1, 1.34.0}                                                                                            
updated com.google.protobuf:protobuf-java-util: {4.0.0-rc-2, 3.20.1} -> {4.0.0-rc-2, 3.21.1}                                                                                                 
updated com.google.protobuf:protobuf-java: {2.5.0, 3.20.1, 4.0.0-rc-2, 3.4.0} -> {2.5.0, 4.0.0-rc-2, 3.21.1, 3.4.0}                                                                          
updated io.grpc:grpc-context: {1.46.0, 1.27.2} -> {1.47.0, 1.27.2}                                                                                                                           
updated org.checkerframework:checker-qual: {3.22.0, 3.5.0, 2.11.1, 3.19.0, 3.12.0, 2.10.0, 3.13.0, 3.0.0} -> {3.5.0, 2.11.1, 3.19.0, 3.12.0, 2.10.0, 3.13.0, 3.0.0, 3.22.2}
updated org.junit.jupiter:junit-jupiter-api: {5.9.0-M1} -> {5.9.0-RC1}
updated org.junit.jupiter:junit-jupiter-engine: {5.9.0-M1} -> {5.9.0-RC1}
updated org.junit.platform:junit-platform-commons: {1.9.0-M1} -> {1.9.0-RC1}
updated org.junit.platform:junit-platform-engine: {1.9.0-M1} -> {1.9.0-RC1}
updated org.junit:junit-bom: {5.9.0-M1} -> {5.9.0-RC1}
updated org.slf4j:slf4j-api: {1.7.36, 2.0.0-alpha7, 1.7.35, 1.7.2} -> {2.0.0-alpha7, 1.7.2, 1.7.36}
updated com.google.api.grpc:proto-google-cloud-tasks-v2: {2.2.0} -> {2.3.0}
updated com.google.api.grpc:proto-google-cloud-tasks-v2beta2: {0.92.0} -> {0.93.0}
updated com.google.api.grpc:proto-google-cloud-tasks-v2beta3: {0.92.0} -> {0.93.0}
updated com.google.api:gax-grpc: {2.18.1} -> {2.18.2}
updated com.google.cloud:google-cloud-tasks: {2.2.0} -> {2.3.0}
updated com.google.re2j:re2j: {1.6} -> {1.7}
updated io.grpc:grpc-api: {1.46.0} -> {1.47.0}
updated io.grpc:grpc-protobuf-lite: {1.46.0} -> {1.47.0}
updated io.grpc:grpc-protobuf: {1.46.0} -> {1.47.0}
updated io.grpc:grpc-stub: {1.46.0} -> {1.47.0}
updated io.netty:netty-tcnative-boringssl-static: {2.0.46.Final, 2.0.52.Final} -> {2.0.53.Final, 2.0.46.Final}
updated io.netty:netty-tcnative-classes: {2.0.46.Final, 2.0.52.Final} -> {2.0.53.Final, 2.0.46.Final}
updated org.junit.jupiter:junit-jupiter-params: {5.9.0-M1} -> {5.9.0-RC1}
updated org.junit.platform:junit-platform-launcher: {1.9.0-M1} -> {1.9.0-RC1}
updated org.junit.platform:junit-platform-runner: {1.9.0-M1} -> {1.9.0-RC1}
updated org.junit.platform:junit-platform-suite-api: {1.9.0-M1} -> {1.9.0-RC1}
updated org.testcontainers:junit-jupiter: {1.17.2} -> {1.17.3}
updated org.testcontainers:testcontainers: {1.17.2} -> {1.17.3}
updated io.grpc:grpc-alts: {1.44.0, 1.46.0} -> {1.45.1, 1.47.0}
updated io.grpc:grpc-auth: {1.44.0, 1.46.0} -> {1.45.1, 1.47.0}
updated io.grpc:grpc-core: {1.44.1, 1.46.0} -> {1.45.1, 1.47.0}
updated io.grpc:grpc-googleapis: {1.46.0} -> {1.47.0}
updated io.grpc:grpc-grpclb: {1.44.0, 1.46.0} -> {1.45.1, 1.47.0}
updated io.grpc:grpc-netty-shaded: {1.44.0, 1.46.0} -> {1.45.1, 1.47.0}
updated io.grpc:grpc-services: {1.44.0, 1.46.0} -> {1.45.1, 1.47.0}
updated io.grpc:grpc-xds: {1.44.0, 1.46.0} -> {1.45.1, 1.47.0}
updated org.junit.platform:junit-platform-suite-commons: {1.9.0-M1} -> {1.9.0-RC1}
updated com.google.api-client:google-api-client-appengine: {1.35.0} -> {1.35.2}
updated com.google.api-client:google-api-client-java6: {1.35.0} -> {1.35.2}
updated com.google.api-client:google-api-client-servlet: {1.35.0} -> {1.35.2}
updated com.google.api.grpc:grpc-google-cloud-bigquerystorage-v1: {2.10.0} -> {2.12.2}
updated com.google.api.grpc:grpc-google-cloud-bigquerystorage-v1beta1: {0.134.0} -> {0.136.2}                                                                                                
updated com.google.api.grpc:grpc-google-cloud-bigquerystorage-v1beta2: {0.134.0} -> {0.136.2}                                                                                                
updated com.google.api.grpc:grpc-google-cloud-bigtable-v2: {2.5.3} -> {2.6.2}
updated com.google.api.grpc:grpc-google-cloud-pubsub-v1: {1.97.5} -> {1.98.4}
updated com.google.api.grpc:grpc-google-cloud-pubsublite-v1: {1.5.0} -> {1.5.4}
updated com.google.api.grpc:grpc-google-cloud-spanner-admin-database-v1: {6.20.0} -> {6.23.3}
updated com.google.api.grpc:grpc-google-cloud-spanner-admin-instance-v1: {6.20.0} -> {6.23.3}
updated com.google.api.grpc:grpc-google-cloud-spanner-v1: {6.20.0} -> {6.23.3}
updated com.google.api.grpc:grpc-google-common-protos: {2.7.2} -> {2.8.3}
updated com.google.api.grpc:proto-google-cloud-bigquerystorage-v1: {2.10.0} -> {2.12.2}
updated com.google.api.grpc:proto-google-cloud-bigquerystorage-v1beta1: {0.134.0} -> {0.136.2}
updated com.google.api.grpc:proto-google-cloud-bigquerystorage-v1beta2: {0.134.0} -> {0.136.2}
updated com.google.api.grpc:proto-google-cloud-bigtable-admin-v2: {2.5.3} -> {2.6.2}
updated com.google.api.grpc:proto-google-cloud-bigtable-v2: {2.5.3} -> {2.6.2}
updated com.google.api.grpc:proto-google-cloud-datastore-v1: {0.93.4} -> {0.93.10}
updated com.google.api.grpc:proto-google-cloud-firestore-v1: {3.0.14} -> {3.1.0}
updated com.google.api.grpc:proto-google-cloud-pubsub-v1: {1.98.0} -> {1.98.4}
updated com.google.api.grpc:proto-google-cloud-pubsublite-v1: {1.5.0} -> {1.5.4}
updated com.google.api.grpc:proto-google-cloud-secretmanager-v1: {2.2.0} -> {2.3.0}
updated com.google.api.grpc:proto-google-cloud-secretmanager-v1beta1: {2.2.0} -> {2.3.0}
updated com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1: {6.20.0} -> {6.23.3}
updated com.google.api.grpc:proto-google-cloud-spanner-admin-instance-v1: {6.20.0} -> {6.23.3}
updated com.google.api.grpc:proto-google-cloud-spanner-v1: {6.20.0} -> {6.23.3}
updated com.google.apis:google-api-services-appengine: {v1-rev20220509-1.32.1} -> {v1-rev20220612-1.32.1}
updated com.google.apis:google-api-services-cloudkms: {v1-rev20220513-1.32.1} -> {v1-rev20220617-1.32.1}
updated com.google.apis:google-api-services-monitoring: {v3-rev20220525-1.32.1} -> {v3-rev20220626-1.32.1}
updated com.google.apis:google-api-services-sheets: {v4-rev20220411-1.32.1} -> {v4-rev20220620-1.32.1}
updated com.google.apis:google-api-services-sqladmin: {v1beta4-rev20220323-1.32.1} -> {v1beta4-rev20220513-1.32.1}
updated com.google.cloud.datastore:datastore-v1-proto-client: {2.1.3} -> {2.2.10}
updated com.google.cloud.sql:jdbc-socket-factory-core: {1.6.0} -> {1.6.1}
updated com.google.cloud:google-cloud-bigquerystorage: {2.10.0} -> {2.12.2}
updated com.google.cloud:google-cloud-bigtable: {2.5.3} -> {2.6.2}
updated com.google.cloud:google-cloud-core-grpc: {2.4.0} -> {2.6.0}
updated com.google.cloud:google-cloud-firestore: {3.0.14} -> {3.1.0}
updated com.google.cloud:google-cloud-pubsub: {1.116.0} -> {1.116.4}
updated com.google.cloud:google-cloud-pubsublite: {1.5.0} -> {1.5.4}
updated com.google.cloud:google-cloud-secretmanager: {2.2.0} -> {2.3.0}
updated com.google.cloud:google-cloud-spanner: {6.20.0} -> {6.23.3}
updated com.google.cloud:proto-google-cloud-firestore-bundle-v1: {3.0.14} -> {3.1.0}
updated com.google.gwt:gwt-user: {2.9.0} -> {2.10.0}
updated com.google.http-client:google-http-client-protobuf: {1.40.1} -> {1.41.7}
updated com.google.oauth-client:google-oauth-client-appengine: {1.34.0} -> {1.34.1}
updated com.google.oauth-client:google-oauth-client-java6: {1.34.0} -> {1.34.1}
updated com.google.oauth-client:google-oauth-client-jetty: {1.34.0} -> {1.34.1}
updated com.google.oauth-client:google-oauth-client-servlet: {1.34.0} -> {1.34.1}
updated io.grpc:grpc-census: {1.44.0} -> {1.45.1}
updated io.grpc:grpc-netty: {1.44.0} -> {1.45.1}
updated org.apache.beam:beam-model-fn-execution: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-model-job-management: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-model-pipeline: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-runners-core-construction-java: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-runners-core-java: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-runners-google-cloud-dataflow-java: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-runners-java-fn-execution: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-sdks-java-core: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-sdks-java-expansion-service: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-sdks-java-extensions-arrow: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-sdks-java-extensions-protobuf: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-sdks-java-fn-execution: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-sdks-java-io-google-cloud-platform: {2.39.0} -> {2.40.0}
updated org.apache.beam:beam-sdks-java-io-kafka: {2.39.0} -> {2.40.0}
added org.apache.commons:commons-csv: {1.9.0}
updated org.flywaydb:flyway-core: {6.0.1, 8.5.12} -> {6.0.1, 8.5.13}
added org.gwtproject:gwt-user: {2.10.0}
updated org.hibernate:hibernate-core: {5.6.9.Final} -> {5.6.10.Final}
updated org.hibernate:hibernate-hikaricp: {5.6.9.Final} -> {5.6.10.Final}
updated org.jsoup:jsoup: {1.15.1} -> {1.15.2}
updated org.postgresql:postgresql: {42.3.6} -> {42.4.0}
updated org.testcontainers:database-commons: {1.17.2} -> {1.17.3}
updated org.testcontainers:jdbc: {1.17.2} -> {1.17.3}
updated org.testcontainers:postgresql: {1.17.2} -> {1.17.3}
updated com.google.cloud:google-cloud-nio: {0.124.2} -> {0.124.7}
updated org.apache.beam:beam-runners-direct-java: {2.39.0} -> {2.40.0}
updated org.apache.tomcat:tomcat-annotations-api: {10.1.0-M15} -> {10.1.0-M16}
updated org.junit.jupiter:junit-jupiter-migrationsupport: {5.9.0-M1} -> {5.9.0-RC1}
updated org.testcontainers:selenium: {1.17.2} -> {1.17.3}
updated com.google.cloud.sql:postgres-socket-factory: {1.6.0} -> {1.6.1}
updated com.sun.xml.bind:jaxb-osgi: {4.0.0-M4} -> {4.0.0}

```

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1703#-:-N6nONfz8PAIkAf7M8Ra:b-6uxh3y)* status: 0 of 134 files reviewed, 7 unresolved discussions (waiting on @CydeWeys)

**Review by mindhog — APPROVED** [review]
> Reviewed 126 of 134 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1703)* status: all files reviewed, 7 unresolved discussions (waiting on @CydeWeys)

**Pull request merged**
