### PR TITLE
Add a credential store backed by Secret Manager

### PR DESCRIPTION
**Pull request by weiminyu**
Added a SqlCredentialStore that stores user credentials with one level
of indirection: for each credential, an addtional secret is used to
identify the 'live' version of the credential. This is a work in
progress and the overall design is explained in
go/dr-sql-security.

Also added two nomulus commands for credential management. They are
stop-gap measures that will be deprecated by the planned privilege
management system.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/901)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
lgtm alert fixed.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/901#-:-MO7CABwBAFJw5SqNHXh:b-dajddn)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @mindhog)

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/901)* status: all files reviewed, 5 unresolved discussions (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java, line 38 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7CH6MBNU9NFojOv-3:-MO7CH6NBUj_7yBZql-a:bj1zyhm) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java#L38)):*
> ```Java
>   @Override
>   public final String toString() {
>     // Ensure password is not accidentally logged.
> ```

I'm confused by this comment, was it intended to be a TODO?
___
*[core/src/main/java/google/registry/privileges/secretmanager/SqlCredentialStore.java, line 80 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7FuW46YzcPqWK4xs8:-MO7FuW46YzcPqWK4xs9:b-bg7tp0) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/privileges/secretmanager/SqlCredentialStore.java#L80)):*
> ```Java
>       csmClient.createSecret(secretId);
>     } catch (NoSuchSecretResourceException ignore) {
>       // Not a problem.
> ```

Can you elaborate on this?  I'm confused as to why the createSecret() call would raise an exception called "NoSuchSecretResourceException" if the resource already exists?
___
*[core/src/main/java/google/registry/privileges/secretmanager/SqlCredentialStore.java, line 95 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7HA5sB2PuY4qqWz3x:-MO7HA5sB2PuY4qqWz3y:b-65x6j) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/privileges/secretmanager/SqlCredentialStore.java#L95)):*
> ```Java
> 
>   private void saveLiveLabel(SqlUser user, SecretVersionName dataVersionName) {
>     String liveLableSecretId = getLiveLabelSecretId(user, dbInstance);
> ```

s/Lable/Label/
___
*[core/src/main/java/google/registry/privileges/secretmanager/SqlUser.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7Kspf85sbtQCQdvub:-MO7Kspf85sbtQCQdvuc:bg63cjx) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/privileges/secretmanager/SqlUser.java#L45)):*
> ```Java
>   /** Cloud SQL user types. Please see class javadoc of {@link SqlUser} for more information. */
>   enum UserType {
>     ROBOT
> ```

Are human user accounts not served by this?
___
*[core/src/main/java/google/registry/tools/SaveSqlCredentialCommand.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7NdM2B3BfZvk9V3PM:-MO7NdM2B3BfZvk9V3PN:bn6fcoq) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/tools/SaveSqlCredentialCommand.java#L55)):*
> ```Java
>   @Override
>   public void run() throws Exception {
>     String password = Files.readAllLines(inputPath, StandardCharsets.UTF_8).get(0);
> ```

Can we just add an option to generate these right here?

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/901)* status: 10 of 14 files reviewed, 5 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java, line 38 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7CH6MBNU9NFojOv-3:-MO7xCbq0ZVhqaOSjPvT:bxihxdt) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/privileges/secretmanager/SqlCredential.java#L38)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I'm confused by this comment, was it intended to be a TODO?
</blockquote></details>

Reworded
___
*[core/src/main/java/google/registry/privileges/secretmanager/SqlCredentialStore.java, line 80 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7FuW46YzcPqWK4xs8:-MO7x7iy8TeFqiaHzrFK:b-lx4fj3) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/privileges/secretmanager/SqlCredentialStore.java#L80)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can you elaborate on this?  I'm confused as to why the createSecret() call would raise an exception called "NoSuchSecretResourceException" if the resource already exists?
</blockquote></details>

Fixed. 
___
*[core/src/main/java/google/registry/privileges/secretmanager/SqlCredentialStore.java, line 95 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7HA5sB2PuY4qqWz3x:-MO7wnnI-ysV4jwUfQAt:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/privileges/secretmanager/SqlCredentialStore.java#L95)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

s/Lable/Label/
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/privileges/secretmanager/SqlUser.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7Kspf85sbtQCQdvub:-MO7xFjt6q9pbP9ENDjr:bdg7u8m) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/privileges/secretmanager/SqlUser.java#L45)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Are human user accounts not served by this?
</blockquote></details>

They will be included later. Added a comment. 
___
*[core/src/main/java/google/registry/tools/SaveSqlCredentialCommand.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7NdM2B3BfZvk9V3PM:-MO89Vru5p15R5Bh7695:bz8rshw) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/tools/SaveSqlCredentialCommand.java#L55)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Can we just add an option to generate these right here?
</blockquote></details>

Made the command prompt for password if input is not specified.

**Review by mindhog — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/901)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[core/src/main/java/google/registry/tools/SaveSqlCredentialCommand.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7NdM2B3BfZvk9V3PM:-MOCSXSzBl7T5vVxFz81:b-p4taxi) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/tools/SaveSqlCredentialCommand.java#L55)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Made the command prompt for password if input is not specified.
</blockquote></details>

It's probably better to allow generating one, but we can add that later.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/901)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/tools/SaveSqlCredentialCommand.java, line 55 at r1](https://reviewable.io/reviews/google/nomulus/901#-MO7NdM2B3BfZvk9V3PM:-MOCTAxdDreCR_JryCbG:b-uumz1r) ([raw file](https://github.com/google/nomulus/blob/c87282f07fbf91e5ba24bdf7593ca825fc54ce4d/core/src/main/java/google/registry/tools/SaveSqlCredentialCommand.java#L55)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

It's probably better to allow generating one, but we can add that later.
</blockquote></details>

This command is for the short term. Main purpose is to add the existing passwords fetched from the keyring to the secret manager.

Auto generation needs to wait until we have a password change tool that can also updates the database.

**Pull request merged**
