### PR TITLE
Allow console access for FTE global role

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2419)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2419)* status: all files reviewed, 5 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 39 at r1](https://reviewable.io/reviews/google/nomulus/2419#-NwfHeAP89MS_SJ8Ej4d:-NwfHeAP89MS_SJ8Ej4e:b-lb0cor) ([raw file](https://github.com/google/nomulus/blob/9c2e57bb9e1d1f48eaabe324a6e8d1f57d57bc46/console-webapp/src/app/shared/services/backend.service.ts#L39)):*
> ```XML
>     // This is a temporary redirect to the old console untill the new console
>     // is fully released and enabled
>     if(error.url && window.location.href.indexOf(error.url) < 0) {
> ```

nit: space after `if` 
___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 245 at r1](https://reviewable.io/reviews/google/nomulus/2419#-NwfFtJIDtK_Sq9KJU3I:-NwfFtJIDtK_Sq9KJU3J:bngmndm) ([raw file](https://github.com/google/nomulus/blob/9c2e57bb9e1d1f48eaabe324a6e8d1f57d57bc46/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L245)):*
> ```Java
>     } else {
>       try {
>         Cookie cookie =
> ```

i think this shouldn't be necessary once my registry lock PR goes on (or i could split that little bit out into a separate PR I suppose) 

actually yeah i just made it a separate PR, https://github.com/google/nomulus/pull/2421 
___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 241 at r1](https://reviewable.io/reviews/google/nomulus/2419#-NwfG08d05SKr22fJcFx:-NwfG08d05SKr22fJcFy:bxvyilp) ([raw file](https://github.com/google/nomulus/blob/9c2e57bb9e1d1f48eaabe324a6e8d1f57d57bc46/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L241)):*
> ```Java
>       return new ContactAction(consoleApiParams, GSON, registrarId, Optional.empty());
>     } else {
>       Cookie cookie =
> ```

same thing re: this hopefully not being necessary
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 120 at r1](https://reviewable.io/reviews/google/nomulus/2419#-NwfG5YJD3ZSdGH8qOQN:-NwfG5YJD3ZSdGH8qOQO:bxvyilp) ([raw file](https://github.com/google/nomulus/blob/9c2e57bb9e1d1f48eaabe324a6e8d1f57d57bc46/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L120)):*
> ```Java
>       throws IOException {
>     consoleApiParams = FakeConsoleApiParams.get(Optional.of(authResult));
>     Cookie cookie =
> ```

same thing re: this hopefully not being necessary
___
*[`core/src/test/java/google/registry/ui/server/console/settings/WhoisRegistrarFieldsActionTest.java` line 168 at r1](https://reviewable.io/reviews/google/nomulus/2419#-NwfG6uHA-k5vdGVbHFJ:-NwfG6uI7mO_vjVZQe0a:bxvyilp) ([raw file](https://github.com/google/nomulus/blob/9c2e57bb9e1d1f48eaabe324a6e8d1f57d57bc46/core/src/test/java/google/registry/ui/server/console/settings/WhoisRegistrarFieldsActionTest.java#L168)):*
> ```Java
>     consoleApiParams = FakeConsoleApiParams.get(Optional.of(authResult));
>     when(consoleApiParams.request().getMethod()).thenReturn(Action.Method.POST.toString());
>     Cookie cookie =
> ```

same thing re: this hopefully not being necessary

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2419)* status: 15 of 17 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java` line 245 at r1](https://reviewable.io/reviews/google/nomulus/2419#-NwfFtJIDtK_Sq9KJU3I:-NwfQlq-25wBA4L9UOB8:bm9k9rx) ([raw file](https://github.com/google/nomulus/blob/9c2e57bb9e1d1f48eaabe324a6e8d1f57d57bc46/core/src/test/java/google/registry/ui/server/console/RegistrarsActionTest.java#L245)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

i think this shouldn't be necessary once my registry lock PR goes on (or i could split that little bit out into a separate PR I suppose) 

actually yeah i just made it a separate PR, https://github.com/google/nomulus/pull/2421
</blockquote></details>

as with the rest I will wait for our discussion in #2421  to resolve

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2419)* status: 11 of 18 files reviewed, 4 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java` line 241 at r1](https://reviewable.io/reviews/google/nomulus/2419#-NwfG08d05SKr22fJcFx:-NwkQM200Q89RFetOmrL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/9c2e57bb9e1d1f48eaabe324a6e8d1f57d57bc46/core/src/test/java/google/registry/ui/server/console/settings/ContactActionTest.java#L241)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

same thing re: this hopefully not being necessary
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java` line 120 at r1](https://reviewable.io/reviews/google/nomulus/2419#-NwfG5YJD3ZSdGH8qOQN:-NwkQMaJ4KYeIsw_7D0p:b-896fix) ([raw file](https://github.com/google/nomulus/blob/9c2e57bb9e1d1f48eaabe324a6e8d1f57d57bc46/core/src/test/java/google/registry/ui/server/console/settings/SecurityActionTest.java#L120)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

same thing re: this hopefully not being necessary
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/ui/server/console/settings/WhoisRegistrarFieldsActionTest.java` line 168 at r1](https://reviewable.io/reviews/google/nomulus/2419#-NwfG6uHA-k5vdGVbHFJ:-NwkQN4C8J3JO4pGPRg0:b-896fix) ([raw file](https://github.com/google/nomulus/blob/9c2e57bb9e1d1f48eaabe324a6e8d1f57d57bc46/core/src/test/java/google/registry/ui/server/console/settings/WhoisRegistrarFieldsActionTest.java#L168)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

same thing re: this hopefully not being necessary
</blockquote></details>

Done.

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2419)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2419)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Comment by ptkach** [comment]
Conflicts with #2350 that made it first are now resolved

**Review by gbrodman — APPROVED** [review]
> Reviewed 5 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2419)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
