### PR TITLE
Allow for change of registry lock passwords in User objects

### PR DESCRIPTION
**Pull request by gbrodman**
This essentially enables the "forgot password" flow

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2609)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2609)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/UpdateUserCommand.java` line 30 at r1](https://reviewable.io/reviews/google/nomulus/2609#-OBWFqmp6PAwNgZMLWSd:-OBWFqmp6PAwNgZMLWSe:b-yp8hc8) ([raw file](https://github.com/google/nomulus/blob/b84a5911046b922b8e63287f6c3c9e9522400302/core/src/main/java/google/registry/tools/UpdateUserCommand.java#L30)):*
> ```Java
> public class UpdateUserCommand extends CreateOrUpdateUserCommand {
> 
>   @Parameter(names = "--remove_registry_lock_password", description = "Removes the registry ")
> ```

Should we replace it with more broad - update_password, which can be used to remove as well, by providing an empty string

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2609)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/tools/UpdateUserCommand.java` line 30 at r1](https://reviewable.io/reviews/google/nomulus/2609#-OBWFqmp6PAwNgZMLWSd:-OBWGep_7ViBRlWkZwjg:bbt5dp6) ([raw file](https://github.com/google/nomulus/blob/b84a5911046b922b8e63287f6c3c9e9522400302/core/src/main/java/google/registry/tools/UpdateUserCommand.java#L30)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Should we replace it with more broad - update_password, which can be used to remove as well, by providing an empty string
</blockquote></details>

I don't think so, because then it allows support to change things that maybe they shouldn't be able to change. This is clearer for sure

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2609)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/UpdateUserCommand.java` line 30 at r1](https://reviewable.io/reviews/google/nomulus/2609#-OBWFqmp6PAwNgZMLWSd:-OBWIl-T08AyOvJDGhk-:bhyep7x) ([raw file](https://github.com/google/nomulus/blob/b84a5911046b922b8e63287f6c3c9e9522400302/core/src/main/java/google/registry/tools/UpdateUserCommand.java#L30)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I don't think so, because then it allows support to change things that maybe they shouldn't be able to change. This is clearer for sure
</blockquote></details>

it can be put behind the check for user role or admin flag or both

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2609)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/UpdateUserCommand.java` line 43 at r2](https://reviewable.io/reviews/google/nomulus/2609#-OBWeENMBW3YrC975q15:-OBWeENMBW3YrC975q16:b-ydfgo9) ([raw file](https://github.com/google/nomulus/blob/411059921d3ea8d3ef05eb025eaefbca2a76dff1/core/src/main/java/google/registry/tools/UpdateUserCommand.java#L43)):*
> ```Java
>         checkArgumentPresent(
>             tm().loadByKeyIfPresent(VKey.create(User.class, email)), "User %s not found", email);
>     if (!removeRegistryLockPassword && registryLockPassword == null) {
> ```

do you think that `executeInTransaction` from CreateOrUpdateUserCommand.java might be a better place for applying the updates, comparing to `getExistingUser` method?

**Review by gbrodman — COMMENTED** [review]
friendly ping

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2609#-:-OBfsj3x-b1izOQdPwd8:b-50swta)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ptkach)

**Review by ptkach — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2609)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java` line 117 at r4](https://reviewable.io/reviews/google/nomulus/2609#-OBgO3ZvES-NE_OaifC9:-OBgO3ZvES-NE_OaifCA:b-n58wyu) ([raw file](https://github.com/google/nomulus/blob/9896c06dfa7261c1b59967f608ce9ddcdc4aa26f/core/src/main/java/google/registry/tools/CreateOrUpdateUserCommand.java#L117)):*
> ```Java
>       } else {
>         checkArgument(
>             user != null && user.getRegistryLockEmailAddress().isPresent(),
> ```

good catch that we need to check both param and existing user.

**Pull request merged**
