### PR TITLE
Update private key formatting to avoid triggering release failure

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2430)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2430)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @ptkach)

___
*[`core/src/test/java/google/registry/testing/sftp/TestSftpServer.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/2430#-NxDUUrN7yGVO0fGKjMt:-NxDUUrN7yGVO0fGKjMu:b-yahlfb) ([raw file](https://github.com/google/nomulus/blob/a85d8d33b2c48df5f19d64f3e3397d04011874ff/core/src/test/java/google/registry/testing/sftp/TestSftpServer.java#L54)):*
> ```Java
>   }
> ```

Add a comment to explain the situation.

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2430)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @ptkach)

___
*[`core/src/test/java/google/registry/testing/sftp/TestSftpServer.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/2430#-NxDUUrN7yGVO0fGKjMt:-NxDV6kNDtwglCyFQxnt:b-afh0nn) ([raw file](https://github.com/google/nomulus/blob/a85d8d33b2c48df5f19d64f3e3397d04011874ff/core/src/test/java/google/registry/testing/sftp/TestSftpServer.java#L54)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Add a comment to explain the situation.
</blockquote></details>

Document that we don't want to use the `git push -o nokeycheck` suggestion in our release script.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2430)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @weiminyu)

___
*[`core/src/test/java/google/registry/testing/sftp/TestSftpServer.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/2430#-NxDUUrN7yGVO0fGKjMt:-NxDVwRy7YjDw8CAzvzk:b-l4396t) ([raw file](https://github.com/google/nomulus/blob/a85d8d33b2c48df5f19d64f3e3397d04011874ff/core/src/test/java/google/registry/testing/sftp/TestSftpServer.java#L54)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Document that we don't want to use the `git push -o nokeycheck` suggestion in our release script.
</blockquote></details>

Added a comment

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2430)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @ptkach)

___
*[`core/src/test/java/google/registry/testing/sftp/TestSftpServer.java` line 54 at r1](https://reviewable.io/reviews/google/nomulus/2430#-NxDUUrN7yGVO0fGKjMt:-NxDcKVK29TF5k82QZ5v:b-h81uvv) ([raw file](https://github.com/google/nomulus/blob/a85d8d33b2c48df5f19d64f3e3397d04011874ff/core/src/test/java/google/registry/testing/sftp/TestSftpServer.java#L54)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Added a comment
</blockquote></details>

No that I think about it, we should drop this change and add `nokeycheck` to 
https://github.com/google/nomulus/blob/49d2e34e12eed5ff52671a8dd747fb9c64522405/release/cloudbuild-release.yaml#L213 and 
https://github.com/google/nomulus/blob/49d2e34e12eed5ff52671a8dd747fb9c64522405/release/cloudbuild-release.yaml#L215

We are pushing a combined repo. The private repo is already checked, and the public repo is already out (and unlikely to have real private key anyway). 
Bypassing the check is safe.

**Comment by ptkach** [comment]
Closed in favor of - https://github.com/google/nomulus/pull/2431

**Pull request closed without merging**
