### PR TITLE
Migrate DNS query table

### PR DESCRIPTION
**Pull request by jianglai**
Currently, Cloud DNS activity data is saved in an internal Plx table and we query it via BQ-plx bridge. The bridge is being deprecated and we are asked to use BQ-TS federation instead.

Per b/322853331, I've created a BQ table in the same project that Nomulus runs, which exposes the same data in the Plx table. This means that we can query this table directly without going through the bridge, and open source the code as a result.

There is a corresponding change in Git-on-Borg to update the config file and remove the Java code that performs the query via BQ-plx bridge:

https://team-review.git.corp.google.com/c/domain-registry-eng/nomulus-internal/+/2312377

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2483)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 31 of 31 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2483)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by gbrodman — CHANGES_REQUESTED** [review]
I don't think that https://team-review.git.corp.google.com/c/domain-registry-eng/nomulus-internal/+/2312377 updates the config file unless I'm missing something? 

> Reviewed 20 of 31 files at r1, 1 of 4 files at r5, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2483#-:-O4gEd7x9RGsW-VJwHTz:btf4jw3)* status: all files reviewed, 4 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java` line 37 at r6](https://reviewable.io/reviews/google/nomulus/2483#-O4knanA5OUNWvJEE2Ix:-O4knanA5OUNWvJEE2Iy:bexzftc) ([raw file](https://github.com/google/nomulus/blob/bb36e360873385e7d1f29906482deb266a82618a/core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java#L37)):*
> ```Java
>  * config file.
>  *
>  * <p>Due to limitations of {@link MembersInjector}, any injectable field needs to be declared in
> ```

if we want, we can get around this by doing constructor injection instead (this is what we do a bunch elsewhere in the codebase). I forget if we ever decided as a team whether we preferred constructor or member injection 

I guess here, if we move to constructor injection then we can get rid of all Bigquery references in this class itself, which seems like a good thing if we want it to be generic
___
*[`core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java` line 40 at r6](https://reviewable.io/reviews/google/nomulus/2483#-O4kocQW9LztJmUickQa:-O4kocQXEtkYreopqTXm:bx1883b) ([raw file](https://github.com/google/nomulus/blob/bb36e360873385e7d1f29906482deb266a82618a/core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java#L40)):*
> ```Java
>  * the base class, even if it is only used in a derived class.
>  */
> public abstract class DnsCountQueryCoordinator {
> ```

Why does this need to be an abstract class instead of an interface? It doesn't seem like we're sharing any functionality between the actual query coordinator and the dummy one. 
___
*[`core/src/main/java/google/registry/reporting/icann/InternalDnsCountQueryCoordinator.java` line 32 at r6](https://reviewable.io/reviews/google/nomulus/2483#-O4knTsk-e6xaKFBB2BF:-O4knTsk-e6xaKFBB2BG:b-x13rnp) ([raw file](https://github.com/google/nomulus/blob/bb36e360873385e7d1f29906482deb266a82618a/core/src/main/java/google/registry/reporting/icann/InternalDnsCountQueryCoordinator.java#L32)):*
> ```Java
>  * Google Registry's zones.
>  */
> public class InternalDnsCountQueryCoordinator extends DnsCountQueryCoordinator {
> ```

I think we can probably rename this to remove the "Internal" right? Because this is now open-source

**Review by gbrodman — CHANGES_REQUESTED** [review]
nah, not a huge deal -- just the PR description mentioned that it changes the config file. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2483#-:-O4vFcYG-LCMQvT5F8iW:b-kigflv)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

___
*[`core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java` line 37 at r6](https://reviewable.io/reviews/google/nomulus/2483#-O4knanA5OUNWvJEE2Ix:-O4vHbsUEUqvF2Pyk36Y:b-ckwbbq) ([raw file](https://github.com/google/nomulus/blob/cce209f89bbd0ce7f056c748339abfcdde2d9602/core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java#L37)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The problem with constructor injection is that we need to know the constructor at compile. As you can see [here](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinatorModule.java;l=39?q=Dnscount&ss=nomulus%2Fnomulus), because the exact class is customizable, we have to use reflection instead.
</blockquote></details>

Is the benefit to this just getting rid of the Params class? Because before we were able to use an interface because we relied on any subclass taking in the Params as a constructor argument. 
___
*[`core/src/main/java/google/registry/reporting/icann/InternalDnsCountQueryCoordinator.java` line 32 at r6](https://reviewable.io/reviews/google/nomulus/2483#-O4knTsk-e6xaKFBB2BF:-O4vF7ZgDm4YiJoWl9xK:b-k6e3ma) ([raw file](https://github.com/google/nomulus/blob/cce209f89bbd0ce7f056c748339abfcdde2d9602/core/src/main/java/google/registry/reporting/icann/InternalDnsCountQueryCoordinator.java#L32)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I've thought about it, but it still depend on the internally available data that's exposed via BigQuery. I don't want to create the illusion that anyone will be able to use Cloud DNS and get the activity data out of the box.
</blockquote></details>

Eh yeah I was thinking maybe including "Bigquery" in the name somewhere but this way we don't need to change the internal config file hah.

**Review by jianglai — COMMENTED** [review]
Renamed the subclass, now there are indeed some changes in the internal CR.

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2483#-:-O4vNfjYAeX0eqNtVrxw:b-7cyuac)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java` line 37 at r6](https://reviewable.io/reviews/google/nomulus/2483#-O4knanA5OUNWvJEE2Ix:-O4vKpUh96UT4oVJMSv_:b-epewnq) ([raw file](https://github.com/google/nomulus/blob/cce209f89bbd0ce7f056c748339abfcdde2d9602/core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java#L37)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Is the benefit to this just getting rid of the Params class? Because before we were able to use an interface because we relied on any subclass taking in the Params as a constructor argument.
</blockquote></details>

Well, it's kinda like picking your poison -- if you use a Params class, that class needs to contain all the fields that any subclass might need. Personally I felt that this way is cleaner as it contains one fewer layer of indirection.
___
*[`core/src/main/java/google/registry/reporting/icann/InternalDnsCountQueryCoordinator.java` line 32 at r6](https://reviewable.io/reviews/google/nomulus/2483#-O4knTsk-e6xaKFBB2BF:-O4vLG4oAqjaJ6keTErT:b-531x9e) ([raw file](https://github.com/google/nomulus/blob/cce209f89bbd0ce7f056c748339abfcdde2d9602/core/src/main/java/google/registry/reporting/icann/InternalDnsCountQueryCoordinator.java#L32)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Eh yeah I was thinking maybe including "Bigquery" in the name somewhere but this way we don't need to change the internal config file hah.
</blockquote></details>

Well, I guess it could be re-named, and we'll just check in this PR first before the internal CR.

**Review by gbrodman — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2483)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java` line 37 at r6](https://reviewable.io/reviews/google/nomulus/2483#-O4knanA5OUNWvJEE2Ix:-O4vZhXx0Y-KUChB4a2G:b-9l59db) ([raw file](https://github.com/google/nomulus/blob/cce209f89bbd0ce7f056c748339abfcdde2d9602/core/src/main/java/google/registry/reporting/icann/DnsCountQueryCoordinator.java#L37)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Well, it's kinda like picking your poison -- if you use a Params class, that class needs to contain all the fields that any subclass might need. Personally I felt that this way is cleaner as it contains one fewer layer of indirection.
</blockquote></details>

eh yeah that makes sense

**Review by gbrodman — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2483)* status: all files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

**Comment by jianglai** [comment]
Merged as https://github.com/google/nomulus/pull/2543.

**Pull request closed without merging**
