### PR TITLE
Convert Registry related tests to working with SQL

### PR DESCRIPTION
**Pull request by hstonec**
This PR converted `RegistryTest` and `RegistriesTest` to working with SQL, and it also made the necessary `ofy() -> tm()` changes in the related code.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/862)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/862)* status: all files reviewed, 2 unresolved discussions (waiting on @hstonec)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 214 at r1](https://reviewable.io/reviews/google/nomulus/862#-MLhCgHG88bSyqZO81OY:-MLhCgHG88bSyqZO81OZ:b-6sc7ys) ([raw file](https://github.com/google/nomulus/blob/d3403772182c740d4f794732f938229662746348/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L214)):*
> ```Java
>     return ofyOrJpaTm(
>         () -> ofy().load().type(PremiumList.class).parent(getCrossTldKey()).id(name).now(),
>         () -> PremiumListDao.getLatestRevision(name).orElseThrow(NoSuchElementException::new));
> ```

Unrelated to this PR, but this ofyOrJpaTm thing is weird -- it looks like it's going to run these in a transaction but it's really just a normal conditional.  Can we just replace it with an "isOfy()" method and then just do "if (tm().isOfy()) { ... ofy action ... } else { ... jpa action ... }" (or "tm().isOfy() ? <ofy> : <jpa>" in this case)?  It would be more obvious and likely more performant. 
___
*[core/src/test/java/google/registry/model/registry/RegistriesTest.java, line 43 at r1](https://reviewable.io/reviews/google/nomulus/862#-MLhUd8SCaKsZ5FV-pMj:-MLhUd8SCaKsZ5FV-pMk:bf5uz0h) ([raw file](https://github.com/google/nomulus/blob/d3403772182c740d4f794732f938229662746348/core/src/test/java/google/registry/model/registry/RegistriesTest.java#L43)):*
> ```Java
>   }
> 
>   @TestOfyAndSql
> ```

Is it possilble for us to dispense with all of these "TestOfyAndSql" annotations given that we're annotating the classes with @DualDatabaseTest?  Does that not imply that all of the tests within it are dual database?

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/862)* status: all files reviewed, 2 unresolved discussions (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 214 at r1](https://reviewable.io/reviews/google/nomulus/862#-MLhCgHG88bSyqZO81OY:-MLhpFpu9AQZnlYBgB2F:b-osmu24) ([raw file](https://github.com/google/nomulus/blob/d3403772182c740d4f794732f938229662746348/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L214)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Unrelated to this PR, but this ofyOrJpaTm thing is weird -- it looks like it's going to run these in a transaction but it's really just a normal conditional.  Can we just replace it with an "isOfy()" method and then just do "if (tm().isOfy()) { ... ofy action ... } else { ... jpa action ... }" (or "tm().isOfy() ? <ofy> : <jpa>" in this case)?  It would be more obvious and likely more performant. 
</blockquote></details>

How about having something like `tm().ifOfy(() -> {// code}).ifJpa(() -> {// code})` ? I just feel `tm().isOfy()` will result in more lines of code.
___
*[core/src/test/java/google/registry/model/registry/RegistriesTest.java, line 43 at r1](https://reviewable.io/reviews/google/nomulus/862#-MLhUd8SCaKsZ5FV-pMj:-MLhrIu6DnhnYlH6i32m:bn07mx0) ([raw file](https://github.com/google/nomulus/blob/d3403772182c740d4f794732f938229662746348/core/src/test/java/google/registry/model/registry/RegistriesTest.java#L43)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Is it possilble for us to dispense with all of these "TestOfyAndSql" annotations given that we're annotating the classes with @DualDatabaseTest?  Does that not imply that all of the tests within it are dual database?
</blockquote></details>

`@DualDatabaseTest` implements [TestTemplateInvocationContextProvider](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/TestTemplateInvocationContextProvider.html) which per [this doc](https://junit.org/junit5/docs/current/user-guide/#writing-tests-test-templates) requires the test method is annotated with `@TestTemplate`(Note that, @TestOfyAndSql is annotated with @TestTemplate and it will be propagated to the test). This means that at least we need to replace `@Test` with `@TestTemplate`, and obviously `@TestTemplate` is not very readable so I introduced `@TestOfyAndSql`.

**Review by mindhog — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/862)* status: all files reviewed, 1 unresolved discussion (waiting on @hstonec)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 214 at r1](https://reviewable.io/reviews/google/nomulus/862#-MLhCgHG88bSyqZO81OY:-MLhvItO2TcMWqvq8WLM:bszjsp4) ([raw file](https://github.com/google/nomulus/blob/d3403772182c740d4f794732f938229662746348/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L214)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

How about having something like `tm().ifOfy(() -> {// code}).ifJpa(() -> {// code})` ? I just feel `tm().isOfy()` will result in more lines of code.
</blockquote></details>

I don't see how?  In every case I can recall it would be less code, including this one:

    return tm().isOfy()
        ?  ofy().load().type(PremiumList.class).parent(getCrossTldKey()).id(name).now()
        : PremiumListDao.getLatestRevision(name).orElseThrow(NoSuchElementException::new));

Can I send you a PR for it?  This would at least uncover the differences.

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/862)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

___
*[core/src/main/java/google/registry/model/registry/label/PremiumList.java, line 214 at r1](https://reviewable.io/reviews/google/nomulus/862#-MLhCgHG88bSyqZO81OY:-MLhz6lE3lWlZRr4MeUT:b4lleva) ([raw file](https://github.com/google/nomulus/blob/d3403772182c740d4f794732f938229662746348/core/src/main/java/google/registry/model/registry/label/PremiumList.java#L214)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

I don't see how?  In every case I can recall it would be less code, including this one:

    return tm().isOfy()
        ?  ofy().load().type(PremiumList.class).parent(getCrossTldKey()).id(name).now()
        : PremiumListDao.getLatestRevision(name).orElseThrow(NoSuchElementException::new));

Can I send you a PR for it?  This would at least uncover the differences.
</blockquote></details>

Sure, thank you!

**Pull request merged**
