### PR TITLE
Add OkHttp as a library used by the core Nomulus project

### PR DESCRIPTION
**Pull request by CydeWeys**
This will be used in a subsequent PR (see #2265) to upload the unavailable domain names list to the BSA.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2272)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2272)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`dependencies.gradle` line 171 at r1](https://reviewable.io/reviews/google/nomulus/2272#-NnQAmiC2e6aN63jp_kv:-NnQAmiC2e6aN63jp_kw:b-lzgt5t) ([raw file](https://github.com/google/nomulus/blob/028a7e8f71ef516e53528b6bac59d59aac11c202/dependencies.gradle#L171)):*
> ```Gradle
>       'commons-codec:commons-codec:[1.15,)',
>       'com.squareup:javapoet:[1.13.0,)',
>       'com.squareup.okhttp3:okhttp:[4.10.0,4.99.0]', // Don't use v5 which is in alpha yet.
> ```

Need to append '!!' to the version range to be strict.
Otherwise if some other dependency prefers v5 it'll be upgraded.

See Table 1 on https://docs.gradle.org/current/userguide/rich_versions.html for semantics.



_Code quote:_
```Gradle
'com.squareup.okhttp3:okhttp:[4.10.0,4.99.0]'
```

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2272)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`dependencies.gradle` line 171 at r1](https://reviewable.io/reviews/google/nomulus/2272#-NnQAmiC2e6aN63jp_kv:-NnQGpjZ5_lYEbNvjkB9:b-896fix) ([raw file](https://github.com/google/nomulus/blob/028a7e8f71ef516e53528b6bac59d59aac11c202/dependencies.gradle#L171)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Need to append '!!' to the version range to be strict.
Otherwise if some other dependency prefers v5 it'll be upgraded.

See Table 1 on https://docs.gradle.org/current/userguide/rich_versions.html for semantics.
</blockquote></details>

Done.

**Review by CydeWeys — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2272#-:-NnQGsqC8Kwa_PxqUsMb:bb71pro)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2272)* status: 0 of 19 files reviewed, all discussions resolved

**Pull request merged**
