### PR TITLE
Replace PupApi primary DB calls with replica

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1742)

### CODE REVIEW

**Review by jianglai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1742)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @ptkach)

___
*[`core/src/main/java/google/registry/module/pubapi/PubApiComponent.java` line 75 at r2](https://reviewable.io/reviews/google/nomulus/1742#-N9cUmqyAosQmzRX_Mx7:-N9cUmqz6E4JFCk2bzZN:byyr695) ([raw file](https://github.com/google/nomulus/blob/55bc1e44a20eda8a61a2e79bb65143e00372845b/core/src/main/java/google/registry/module/pubapi/PubApiComponent.java#L75)):*
> ```Java
>   Lazy<MetricReporter> metricReporter();
> 
>   @Component.Builder
> ```

I think you can install a module that contains a `@Binds` method to bind `@AppEngineJpaTm` to `@ReadonlyReplicaJpaTm` to this component instead. It's more elegant than using a boolean, and arguably more Dagger-idiomatic.

https://dagger.dev/dev-guide/faq.html#binds

Also check how we use `@Binds` in our codebase.



_Code quote:_
```Java
  @Component.Builder
  interface Builder {
    @BindsInstance
    Builder forceUseReplica(
        @Nullable @Config("forceUseReplica") Boolean forceUseReplica);
    PubApiComponent build();
  }
```

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1742)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/module/pubapi/PubApiComponent.java` line 75 at r2](https://reviewable.io/reviews/google/nomulus/1742#-N9cUmqyAosQmzRX_Mx7:-NA6W1VIEp4lXl2__pEC:b-34f67t) ([raw file](https://github.com/google/nomulus/blob/55bc1e44a20eda8a61a2e79bb65143e00372845b/core/src/main/java/google/registry/module/pubapi/PubApiComponent.java#L75)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I think you can install a module that contains a `@Binds` method to bind `@AppEngineJpaTm` to `@ReadonlyReplicaJpaTm` to this component instead. It's more elegant than using a boolean, and arguably more Dagger-idiomatic.

https://dagger.dev/dev-guide/faq.html#binds

Also check how we use `@Binds` in our codebase.
</blockquote></details>

No longer applicable as different approach has been chosen

**Review by jianglai — COMMENTED** [review]
Is this PR abandoned at this point?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1742#-:-NAFAC_OEzxE8L4Wul3G:b-7jd7c3)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

**Review by ptkach — COMMENTED** [review]
Absolutely not, it's updated as per our discussion - change only low hanging fruits. It's pending alpha server verification on my side (recall schema release fails blocking any alpha e2e tests). However all tests pass with this change

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1742#-:-NAFAkgtDiGN3cyRpdm2:b-mh9uyf)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

**Review by jianglai — COMMENTED** [review]
I think this should work. Based on the comment to the `loadByForeignKeyCached` method, it can be used for WHOIS. So I think it is safe to assume it should also work for RDAP where we can tolerate some staleness.

And yes, we do want to deploy and test all the actions changed here.

> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1742#-:-NAKT1te-3P3UbJohA_h:b-xueva9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by gbrodman — CHANGES_REQUESTED** [review]
Yeah, this is definitely a good thing to do, even if it isn't necessarily 100% ideal (relative to just injecting the replica as the standard `tm()`. 

Let's update the commit / PR title and message to be accurate though. 

Also just checking, are there any instances in the pubapi code where we still call `tm()` or `loadByForeignKey` (without the caching) ?

> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1742#-:-NAKcReoCBBFrOz9cmrM:b-m2yr4r)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by ptkach — COMMENTED** [review]
@jianglai  All actions have been tested and verified in alpha just now, there seems to be no regression as far as I can tell on any of the actions. 

@gbrodman Commit title updated. Most of the instances have been replaced, however per offline discussion those instances which are rather difficult to replace we agreed to leave out of scope, as time investment for implementation and verification doesn't seem to justify potential outcome. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1742#-:-NALa3b22J6NP7Hb2zQv:b-bq6xi)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @gbrodman and @jianglai)

**Review by jianglai — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1742)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1742)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
