### PR TITLE
Expand registrar schema to support sending expiring certificate notification emails

### PR DESCRIPTION
**Pull request by rachelguan**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1247)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @jianglai, and @rachelguan)

___
*[db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql, line 16 at r1](https://reviewable.io/reviews/google/nomulus/1247#-Mf4pDxrADrpjEnwk_QB:-Mf4pDxrADrpjEnwk_QC:b-odqywk) ([raw file](https://github.com/google/nomulus/blob/fb1d9024079e622d3ce91b33963501863ac38a2c/db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql#L16)):*
> ```
> add column if not exists "last_expiring_cert_notification_sent_date" timestamptz;
> ```
This should either be nullable or have a default value. Same for the column below.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @jianglai, and @weiminyu)

___
*[db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql, line 16 at r1](https://reviewable.io/reviews/google/nomulus/1247#-Mf4pDxrADrpjEnwk_QB:-Mf9UFOq38iEEGP5vmxe:bpfh2su) ([raw file](https://github.com/google/nomulus/blob/fb1d9024079e622d3ce91b33963501863ac38a2c/db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql#L16)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> add column if not exists "last_expiring_cert_notification_sent_date" timestamptz;
> ```
This should either be nullable or have a default value. Same for the column below.


</blockquote></details>

added not null at the end for both columns. assigned START_OF_TIME to both in registrar.java as initial value.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @CydeWeys, @jianglai, and @weiminyu)

___
*[db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql, line 16 at r1](https://reviewable.io/reviews/google/nomulus/1247#-Mf4pDxrADrpjEnwk_QB:-Mf9UgdiEIhsetmrq5Of:b-r86ews) ([raw file](https://github.com/google/nomulus/blob/fb1d9024079e622d3ce91b33963501863ac38a2c/db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql#L16)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

added not null at the end for both columns. assigned START_OF_TIME to both in registrar.java as initial value. 
</blockquote></details>

also ran the DDL scripts after modifying this file.

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @jianglai, and @rachelguan)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 864 at r2](https://reviewable.io/reviews/google/nomulus/1247#-Mf9dMuy02S3LI2mbvp1:-Mf9dMuy02S3LI2mbvp2:b-1u3jkx) ([raw file](https://github.com/google/nomulus/blob/d1403e111f9783b1c48817d6052e96a671bd78c0/core/src/main/java/google/registry/model/registrar/Registrar.java#L864)):*
> ```
> now
> ```
Check not null
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 869 at r2](https://reviewable.io/reviews/google/nomulus/1247#-Mf9dSIGA1p18gmeAqmc:-Mf9dSIH4Ouv1Ws119hE:bqws0pc) ([raw file](https://github.com/google/nomulus/blob/d1403e111f9783b1c48817d6052e96a671bd78c0/core/src/main/java/google/registry/model/registrar/Registrar.java#L869)):*
> ```
> now
> ```
Save
___
*[db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql, line 16 at r1](https://reviewable.io/reviews/google/nomulus/1247#-Mf4pDxrADrpjEnwk_QB:-Mf9eGQp1sflhB-8iLBG:b-u64zrx) ([raw file](https://github.com/google/nomulus/blob/fb1d9024079e622d3ce91b33963501863ac38a2c/db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql#L16)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

also ran the DDL scripts after modifying this file. 
</blockquote></details>

Drop the 'not null' here. We are enforcing not-null in code, not in schema.

Adding a 'not null' column without specifying a default value is bad practice because the change will fail if the target table is not empty.

On the other hand, adding a 'not null' column with a default value may lock up the table for some period if the table is large.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @jianglai, and @weiminyu)

___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 864 at r2](https://reviewable.io/reviews/google/nomulus/1247#-Mf9dMuy02S3LI2mbvp1:-Mf9wpyS055eyDOZXMUD:b-aqvael) ([raw file](https://github.com/google/nomulus/blob/d1403e111f9783b1c48817d6052e96a671bd78c0/core/src/main/java/google/registry/model/registrar/Registrar.java#L864)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> now
> ```
Check not null
</blockquote></details>

added null check and added test cases for both getters and setters. 
___
*[core/src/main/java/google/registry/model/registrar/Registrar.java, line 869 at r2](https://reviewable.io/reviews/google/nomulus/1247#-Mf9dSIGA1p18gmeAqmc:-Mf9wjYuBC5IeIsGaStw:bclqsv7) ([raw file](https://github.com/google/nomulus/blob/d1403e111f9783b1c48817d6052e96a671bd78c0/core/src/main/java/google/registry/model/registrar/Registrar.java#L869)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
> now
> ```
Save
</blockquote></details>

i assume that means same as above. applied code changes to both DateTime variables. 
___
*[db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql, line 16 at r1](https://reviewable.io/reviews/google/nomulus/1247#-Mf4pDxrADrpjEnwk_QB:-Mf9pLf_9jVtxWxzf8fl:beucxak) ([raw file](https://github.com/google/nomulus/blob/fb1d9024079e622d3ce91b33963501863ac38a2c/db/src/main/resources/sql/flyway/V98__add_last_expiring_cert_notification_sent_date.sql#L16)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Drop the 'not null' here. We are enforcing not-null in code, not in schema.

Adding a 'not null' column without specifying a default value is bad practice because the change will fail if the target table is not empty.

On the other hand, adding a 'not null' column with a default value may lock up the table for some period if the table is large.
</blockquote></details>

removed not null and re-ran the DDL scripts.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @jianglai, @rachelguan, and @weiminyu)

___
*[core/src/test/java/google/registry/model/registrar/RegistrarTest.java, line 420 at r4](https://reviewable.io/reviews/google/nomulus/1247#-MfDcJF4-JbLshJ0RozN:-MfDcJF4-JbLshJ0RozO:b-pkz6z5) ([raw file](https://github.com/google/nomulus/blob/92c1c7d2faf86f6008b31e941c11e7b4daaa7705/core/src/test/java/google/registry/model/registrar/RegistrarTest.java#L420)):*
> ```Java
>   @TestOfyAndSql
>   void testSuccess_getLastExpiringCertNotificationSentDate_returnsInitialValue() {
>     assertThat(registrar.asBuilder().build().getLastExpiringCertNotificationSentDate())
> ```

Why are you calling `registrar.asBuilder().build()` here and elsewhere?  That should be a no-op.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @jianglai, and @weiminyu)

___
*[core/src/test/java/google/registry/model/registrar/RegistrarTest.java, line 420 at r4](https://reviewable.io/reviews/google/nomulus/1247#-MfDcJF4-JbLshJ0RozN:-MfDsRdJ3sJPjQj8S-Pl:b1dwy16) ([raw file](https://github.com/google/nomulus/blob/92c1c7d2faf86f6008b31e941c11e7b4daaa7705/core/src/test/java/google/registry/model/registrar/RegistrarTest.java#L420)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why are you calling `registrar.asBuilder().build()` here and elsewhere?  That should be a no-op.
</blockquote></details>

goot catch. removing RegistrarTest.java and Registrar.java to a separate PR. keeping this PR schema change only.

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @jianglai, @rachelguan, and @weiminyu)

___
*[core/src/test/resources/google/registry/model/schema.txt, line 604 at r5](https://reviewable.io/reviews/google/nomulus/1247#-MfDswua8N7WXC6avXs5:-MfDswua8N7WXC6avXs6:b-on3uqb) ([raw file](https://github.com/google/nomulus/blob/4974110210d74dcfa9da619cd1cfb91b7b89faa4/core/src/test/resources/google/registry/model/schema.txt#L604)):*
> ```
>   org.joda.time.DateTime lastExpiringCertNotificationSentDate;
>   org.joda.time.DateTime lastExpiringFailoverCertNotificationSentDate;
> ```
Exclude this file too. 

This is objectify schema generated from Java code. Tests will fail if this file is not also excluded.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @CydeWeys, @jianglai, and @weiminyu)

___
*[core/src/test/resources/google/registry/model/schema.txt, line 604 at r5](https://reviewable.io/reviews/google/nomulus/1247#-MfDswua8N7WXC6avXs5:-MfDxJcP-HJsn2eTSmZx:bb7f2mf) ([raw file](https://github.com/google/nomulus/blob/4974110210d74dcfa9da619cd1cfb91b7b89faa4/core/src/test/resources/google/registry/model/schema.txt#L604)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

> ```
>   org.joda.time.DateTime lastExpiringCertNotificationSentDate;
>   org.joda.time.DateTime lastExpiringFailoverCertNotificationSentDate;
> ```
Exclude this file too. 

This is objectify schema generated from Java code. Tests will fail if this file is not also excluded.
</blockquote></details>

done

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @jianglai, and @weiminyu)

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1247#-:-MfF0zmm8JrVZxGE6Y27:bnfp4nl)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @jianglai and @weiminyu)

**Pull request merged**
