### PR TITLE
Extend IP validation test with message verification

### PR DESCRIPTION
**Pull request by ptkach**
This is a follow up on my last [PR](https://github.com/google/nomulus/pull/1726) to update the test not only to verify the instance of the exception, but the text as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1736)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1736)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

___
*[`core/src/test/java/google/registry/flows/TlsCredentialsTest.java` line 100 at r1](https://reviewable.io/reviews/google/nomulus/1736#-N8zAIziAHTzTmgaexGv:-N8zAIzjCjhp2pypaUQv:bq7nacf) ([raw file](https://github.com/google/nomulus/blob/7fdbb86c02705a19f33779eb7a948ddf59f863c1/core/src/test/java/google/registry/flows/TlsCredentialsTest.java#L100)):*
> ```Java
>     assertThat(thrown)
>         .hasMessageThat()
>         .isEqualTo("Registrar IP address /127.0.0.1 is not in stored allow list");
> ```

Why is there a slash in there?

**Comment by ptkach** [comment]
> 

That's what stored as client address, being set [here](https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/flows/TlsCredentials.java;l=71?q=tls&ss=nomulus%2Fnomulus) . I've not updated this part , so figured it's expected.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1736)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

___
*[`core/src/test/java/google/registry/flows/TlsCredentialsTest.java` line 100 at r1](https://reviewable.io/reviews/google/nomulus/1736#-N8zAIziAHTzTmgaexGv:-N8zFDi8DlPlb6KoMsic:bsnnqf1) ([raw file](https://github.com/google/nomulus/blob/7fdbb86c02705a19f33779eb7a948ddf59f863c1/core/src/test/java/google/registry/flows/TlsCredentialsTest.java#L100)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why is there a slash in there?
</blockquote></details>

I think you want to use `.getHostAddress()` instead of implicitly using the `toString()` method of `InetAddress`.  The `toString()` method is weird.

**Comment by ptkach** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1736)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)
> 
> _[`core/src/test/java/google/registry/flows/TlsCredentialsTest.java` line 100 at r1](https://reviewable.io/reviews/google/nomulus/1736#-N8zAIziAHTzTmgaexGv:-N8zFDi8DlPlb6KoMsic:bsnnqf1) ([raw file](https://github.com/google/nomulus/blob/7fdbb86c02705a19f33779eb7a948ddf59f863c1/core/src/test/java/google/registry/flows/TlsCredentialsTest.java#L100)):_
> 
> Previously, CydeWeys (Ben McIlwain) wrote…
> I think you want to use `.getHostAddress()` instead of implicitly using the `toString()` method of `InetAddress`. The `toString()` method is weird.

Well that's why doing tests is good, fixed the test now

**Review by jianglai — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1736)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @sarahcaseybot)

**Pull request merged**
