### PR TITLE
Upgrade to Beam 2.34.0

### PR DESCRIPTION
**Pull request by jianglai**
This version of Beam does not have an explicit dependency on log4j.
There are a couple of other things that need to change due to the
upgrade.

1) The new version pulls in a dependency that is not on Maven Central
but on packages.confluent.io, so we need to explicitly add this repo.

2) The new version has a dependency on flogger 0.6 anb above , which removed
the LoggerConfig class (see google/flogger#142).
We therefore backported the class. In the long term we should do what
was suggested in the issue and use the normal JDK Logger config
directly.

3) The intSqlPipeline dependency graph also needs to be updated.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1472)

### CODE REVIEW

**Comment by jianglai** [comment]
Please note that currently the presubmits do not pass because of the added maven URL, which is not recognized by the gradleproxy used in `update_dependency.sh`. This will be fixed in a separate CL, but this PR itself is ready for review.

**Review by mindhog — APPROVED** [review]
It's worth noting that this change downgrades io.dropwizard.metrics:metrics-core: (not that this is necessarily a bad thing).

Full version diffs (per config/show_upgrade_diffs.py):

updated com.fasterxml.jackson.core:jackson-core: {2.11.3, 2.12.3, 2.12.1} -> {2.11.3, 2.12.4, 2.12.1}                                                                                                                                                                           
updated com.fasterxml.jackson:jackson-bom: {2.12.3, 2.12.1} -> {2.12.4, 2.12.1}                                                                                                                                                                                                  
updated com.google.api.grpc:proto-google-common-protos: {2.1.0, 2.3.2} -> {2.5.0, 2.1.0, 2.3.2}                                                                                                                                                                                  
updated com.google.api.grpc:proto-google-iam-v1: {1.0.14, 1.0.10} -> {1.0.14, 1.1.0, 1.0.10}                                                                                                                                                                                     
updated com.google.api:api-common: {1.10.1, 1.10.4} -> {1.10.1, 1.10.4, 2.0.2}                                                                                                                                                                                                   
updated com.google.api:gax-httpjson: {0.83.0, 0.79.0} -> {0.88.0, 0.79.0}                                                                                                                                                                                                        
updated com.google.api:gax: {1.62.0, 1.66.0} -> {1.62.0, 1.66.0, 2.4.1}                                                                                                                                                                                                          
updated com.google.auth:google-auth-library-credentials: {0.23.0, 0.26.0, 0.24.1} -> {0.26.0, 0.24.1, 0.23.0, 1.1.0}                                                                                                                                                             
updated com.google.auth:google-auth-library-oauth2-http: {0.23.0, 0.26.0, 0.24.1} -> {0.26.0, 0.24.1, 0.23.0, 1.1.0}                                                                                                                                                             
updated com.google.auto.value:auto-value-annotations: {1.7.4, 1.8.1} -> {1.7.4, 1.8.1, 1.8.2}                                                                                                                                                                                    
updated com.google.cloud:google-cloud-core-http: {1.94.1, 1.95.4, 1.94.3} -> {1.94.1, 2.1.0, 1.94.3}                                                                                                                                                                             
updated com.google.cloud:google-cloud-core: {1.95.4, 1.94.3} -> {2.1.0, 1.94.3}                                                                                                                                                                                                  
updated com.google.code.gson:gson: {2.7, 2.8.6, 2.8.7} -> {2.8.6, 2.7, 2.8.7, 2.8.8}                                                                                                                                                                                             
updated com.google.errorprone:error_prone_annotations: {2.7.1, 2.5.1, 2.3.4} -> {2.7.1, 2.9.0, 2.5.1, 2.3.4}                                                                                                                                                                     
updated com.google.http-client:google-http-client-gson: {1.38.1, 1.39.2, 1.39.0} -> {1.40.0, 1.39.2, 1.38.1, 1.39.0}                                                                                                                                                             
updated com.google.http-client:google-http-client: {1.38.1, 1.39.2, 1.39.0} -> {1.40.0, 1.39.2, 1.38.1, 1.39.0}                                                                                                                                                                  
updated io.grpc:grpc-context: {1.36.0, 1.22.1, 1.39.0} -> {1.36.0, 1.22.1, 1.40.1, 1.39.0}                                                                                                                                                                                       
updated org.apache.commons:commons-lang3: {3.8.1, 3.5} -> {3.8.1}                                                                                                                                                                                                                
updated org.checkerframework:checker-qual: {3.9.1, 3.8.0, 3.5.0, 3.0.0, 2.10.0, 2.11.1} -> {3.18.0, 3.9.1, 3.8.0, 3.5.0, 3.0.0, 2.10.0, 2                                                                                                                                        .11.1}                                                                                                                                                              
updated com.fasterxml.jackson.core:jackson-annotations: {2.12.3, 2.10.3, 2.12.1} -> {2.12.4, 2.10.3, 2.12.1}                                                                                                                                                                     
updated com.google.api:gax-grpc: {1.66.0} -> {2.4.1, 1.66.0}                                                                                                                                                                                                                     
updated com.google.flogger:flogger-system-backend: {0.5.1} -> {0.6, 0.7.3}                                                                                                                                                                                                       
updated com.google.flogger:flogger: {0.5.1} -> {0.7.3}                                                                                                                                                                                                                           
updated io.grpc:grpc-alts: {1.39.0} -> {1.40.1, 1.39.0}                                                                                                                                                                                                                          
updated io.grpc:grpc-api: {1.39.0} -> {1.40.1, 1.39.0}                                                                                                                                                                                                                           
updated io.grpc:grpc-auth: {1.39.0} -> {1.40.1, 1.39.0}                                                                                                                                                                                                                          
updated io.grpc:grpc-core: {1.39.0} -> {1.40.1, 1.39.0}                                                                                                                                                                                                                          
updated io.grpc:grpc-grpclb: {1.39.0} -> {1.40.1, 1.39.0}                                                                                                                                                                                                                        
updated io.grpc:grpc-netty-shaded: {1.39.0} -> {1.40.1, 1.39.0}                                                                                                                                                                                                                  
updated io.grpc:grpc-protobuf-lite: {1.39.0} -> {1.40.1, 1.39.0}                                                                                                                                                                                                                 
updated io.grpc:grpc-protobuf: {1.39.0} -> {1.40.1, 1.39.0}                                                                                                                                                                                                                      
updated io.grpc:grpc-stub: {1.39.0} -> {1.40.1, 1.39.0}                                                                                                                                                                                                                          
updated io.netty:netty-buffer: {4.1.51.Final, 4.1.59.Final} -> {4.1.59.Final, 4.1.52.Final}                                                                                                                                                                                 
updated io.netty:netty-codec-http: {4.1.51.Final, 4.1.59.Final} -> {4.1.59.Final, 4.1.52.Final}                                                                                                                                                                                  
updated io.netty:netty-codec: {4.1.51.Final, 4.1.59.Final} -> {4.1.59.Final, 4.1.52.Final}                                                                                                                                                                              
updated io.netty:netty-common: {4.1.51.Final, 4.1.59.Final} -> {4.1.59.Final, 4.1.52.Final}                                                                                                                                                                                 
updated io.netty:netty-handler: {4.1.51.Final, 4.1.59.Final} -> {4.1.59.Final, 4.1.52.Final}                                                                                                                                                                                    
updated io.netty:netty-resolver: {4.1.51.Final, 4.1.59.Final} -> {4.1.59.Final, 4.1.52.Final}                                                                                                                                                                                    
updated io.netty:netty-transport: {4.1.51.Final, 4.1.59.Final} -> {4.1.59.Final, 4.1.52.Final}                                                                                                                                                                                   
updated joda-time:joda-time: {2.10.5, 2.9.2} -> {2.10.10, 2.9.2}                                                                                                                                                                                                    
updated org.yaml:snakeyaml: {1.17, 1.21} -> {1.17, 1.21, 1.27}                                                                                                                                                                                                                   
added com.101tec:zkclient: {0.10}                                                                                                                                                                                                                                               
updated com.fasterxml.jackson.core:jackson-databind: {2.12.3, 2.12.1} -> {2.12.4}                                                                                                                                                                                                
added com.fasterxml.jackson.dataformat:jackson-dataformat-yaml: {2.12.4}                                                                                                                                                                                                         
updated com.google.api-client:google-api-client-jackson2: {1.30.10} -> {1.31.3}                                                                                                                                                                                                  
updated com.google.api.grpc:grpc-google-cloud-bigquerystorage-v1: {1.5.5} -> {2.1.0}                                                                                                                                                                                             
updated com.google.api.grpc:grpc-google-cloud-bigquerystorage-v1beta1: {0.105.5} -> {0.125.0}                                                                                                                                                                                    
updated com.google.api.grpc:grpc-google-cloud-bigquerystorage-v1beta2: {0.105.5} -> {0.125.0}                                                                                                                                                                                    
updated com.google.api.grpc:grpc-google-cloud-bigtable-admin-v2: {1.14.0} -> {1.27.1}                                                                                                                                                                                            
updated com.google.api.grpc:grpc-google-cloud-bigtable-v2: {1.14.0} -> {1.27.1}                                                                                                                                                                                                  
updated com.google.api.grpc:grpc-google-cloud-pubsub-v1: {1.90.3} -> {1.96.2}                                                                                                                                                                                                    
updated com.google.api.grpc:grpc-google-cloud-pubsublite-v1: {0.7.0} -> {1.2.0}                                                                                                                                                                                                  
updated com.google.api.grpc:grpc-google-cloud-spanner-admin-database-v1: {2.0.2} -> {6.12.1}                                                                                                                                                                                     
updated com.google.api.grpc:grpc-google-cloud-spanner-admin-instance-v1: {2.0.2} -> {6.12.1}                                                                                                                                                                                     
updated com.google.api.grpc:grpc-google-cloud-spanner-v1: {2.0.2} -> {6.12.1}                                                                                                                                                                                                    
updated com.google.api.grpc:grpc-google-common-protos: {1.18.1} -> {2.3.2}                                                                                                                                                                                                       
updated com.google.api.grpc:proto-google-cloud-bigquerystorage-v1: {1.5.5} -> {2.1.0}                                                                                                                                                                                            
updated com.google.api.grpc:proto-google-cloud-bigquerystorage-v1beta1: {0.105.5} -> {0.125.0}                                                                                                                                                                                   
updated com.google.api.grpc:proto-google-cloud-bigquerystorage-v1beta2: {0.105.5} -> {0.125.0}                                                                                                                                                                                   
updated com.google.api.grpc:proto-google-cloud-bigtable-admin-v2: {1.14.0} -> {2.1.0}                                                                                                                                                                                            
updated com.google.api.grpc:proto-google-cloud-bigtable-v2: {1.16.1} -> {2.1.0}
updated com.google.api.grpc:proto-google-cloud-datastore-v1: {0.88.9} -> {0.91.3}
added com.google.api.grpc:proto-google-cloud-firestore-v1: {3.0.2}
updated com.google.api.grpc:proto-google-cloud-pubsub-v1: {1.92.0} -> {1.96.2}
updated com.google.api.grpc:proto-google-cloud-pubsublite-v1: {0.7.0} -> {1.2.0}
updated com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1: {2.0.2} -> {6.12.1}
updated com.google.api.grpc:proto-google-cloud-spanner-admin-instance-v1: {2.0.2} -> {6.12.1}
updated com.google.api.grpc:proto-google-cloud-spanner-v1: {2.0.2} -> {6.12.1}
updated com.google.apis:google-api-services-bigquery: {v2-rev20200916-1.30.10} -> {v2-rev20210813-1.32.1}
updated com.google.apis:google-api-services-clouddebugger: {v2-rev20200501-1.30.10} -> {v2-rev20210813-1.32.1}
updated com.google.apis:google-api-services-cloudresourcemanager: {v1-rev20200720-1.30.10} -> {v1-rev20210815-1.32.1}
updated com.google.apis:google-api-services-dataflow: {v1b3-rev20200713-1.30.10} -> {v1b3-rev20210818-1.32.1}
updated com.google.apis:google-api-services-healthcare: {v1beta1-rev20200713-1.30.10} -> {v1-rev20210806-1.32.1}
updated com.google.apis:google-api-services-iamcredentials: {v1-rev20201022-1.30.10} -> {v1-rev20201022-1.31.0}
updated com.google.apis:google-api-services-pubsub: {v1-rev20200713-1.30.10} -> {v1-rev20210809-1.32.1}
updated com.google.cloud.bigdataoss:gcsio: {2.1.6} -> {2.2.2}
updated com.google.cloud.bigdataoss:util: {2.1.6} -> {2.2.2}
updated com.google.cloud.bigtable:bigtable-client-core: {1.16.0} -> {1.23.1}
added com.google.cloud.bigtable:bigtable-metrics-api: {1.23.1}
updated com.google.cloud:google-cloud-bigquery: {1.122.2} -> {2.1.2}
updated com.google.cloud:google-cloud-bigquerystorage: {1.5.5} -> {2.1.0}
updated com.google.cloud:google-cloud-bigtable: {1.14.0} -> {1.27.1}
updated com.google.cloud:google-cloud-core-grpc: {1.93.9} -> {2.1.0}
added com.google.cloud:google-cloud-firestore: {3.0.2}
updated com.google.cloud:google-cloud-pubsub: {1.110.0} -> {1.114.2}
updated com.google.cloud:google-cloud-pubsublite: {0.7.0} -> {1.2.0}
updated com.google.cloud:google-cloud-spanner: {2.0.2} -> {6.12.1}
added com.google.cloud:grpc-gcp: {1.1.0}
added com.google.cloud:proto-google-cloud-firestore-bundle-v1: {3.0.2}
added com.google.flatbuffers:flatbuffers-java: {1.12.0}
updated com.google.flogger:google-extensions: {0.5.1} -> {0.6}
added io.confluent:common-config: {5.3.2}
added io.confluent:common-utils: {5.3.2}
added io.confluent:kafka-avro-serializer: {5.3.2}
added io.confluent:kafka-schema-registry-client: {5.3.2}
updated io.dropwizard.metrics:metrics-core: {3.2.6} -> {3.1.2}
updated io.github.classgraph:classgraph: {4.8.65, 4.8.102} -> {4.8.104}
updated io.grpc:grpc-netty: {1.32.2} -> {1.40.0}
updated io.netty:netty-codec-http2: {4.1.51.Final} -> {4.1.52.Final}
updated io.opencensus:opencensus-contrib-grpc-util: {0.24.0} -> {0.28.0}
added org.apache.arrow:arrow-format: {5.0.0}
added org.apache.arrow:arrow-memory-core: {5.0.0}
added org.apache.arrow:arrow-vector: {5.0.0}
updated org.apache.beam:beam-model-fn-execution: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-model-job-management: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-model-pipeline: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-runners-core-construction-java: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-runners-core-java: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-runners-google-cloud-dataflow-java: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-runners-java-fn-execution: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-sdks-java-core: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-sdks-java-expansion-service: {2.28.0} -> {2.34.0}
added org.apache.beam:beam-sdks-java-extensions-arrow: {2.34.0}
updated org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-sdks-java-extensions-protobuf: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-sdks-java-fn-execution: {2.28.0} -> {2.34.0}
updated org.apache.beam:beam-sdks-java-io-google-cloud-platform: {2.28.0} -> {2.34.0}
added org.apache.beam:beam-sdks-java-io-kafka: {2.34.0}
added org.apache.beam:beam-vendor-bytebuddy-1_11_0: {0.1}
added org.apache.beam:beam-vendor-grpc-1_36_0: {0.2}
added org.springframework:spring-core: {4.3.18.RELEASE}
added org.springframework:spring-expression: {4.3.18.RELEASE}
updated org.xerial.snappy:snappy-java: {1.1.4} -> {1.1.8.4}
updated io.netty:netty-codec-socks: {4.1.51.Final} -> {4.1.52.Final}
updated io.netty:netty-handler-proxy: {4.1.51.Final} -> {4.1.52.Final}
updated org.apache.beam:beam-runners-direct-java: {2.28.0} -> {2.34.0}
removed com.github.rholder:guava-retryingremoved com.google.api.grpc:proto-google-cloud-bigquerystorage-v1alpha2
removed org.apache.beam:beam-vendor-bytebuddy-1_10_8removed org.apache.beam:beam-vendor-grpc-1_26_0
removed org.apache.beam:beam-vendor-sdks-java-extensions-protobuf

> Reviewed 17 of 81 files at r1, 116 of 116 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1472#-:-Mr2hdAACk1Ru3E5Mj6K:b-t5i4v2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)



<!-- Sent from Reviewable.io -->

**Review by weiminyu — CHANGES_REQUESTED** [review]
> Reviewed 1 of 116 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1472)* status: all files reviewed, 3 unresolved discussions (waiting on @jianglai)

___
*[build.gradle, line 191 at r2](https://reviewable.io/reviews/google/nomulus/1472#-Mr5NCEcAR4dLvGrZzjX:-Mr5NCEcAR4dLvGrZzjY:b-xert7w) ([raw file](https://github.com/google/nomulus/blob/236c0210bc2e6f4be2521abd192dece07a7754fa/build.gradle#L191)):*
> ```Gradle
>       maven {
>         url "http://packages.confluent.io/maven/"
>       }
> ```

How about limiting this repo to confluent only:
maven {
    url ...
    content {
          includeGroup 'io.confluent'
     }
}
___
*[dependencies.gradle, line 141 at r2](https://reviewable.io/reviews/google/nomulus/1472#-Mr5PohH1K1J_3lnPS4I:-Mr5PohH1K1J_3lnPS4J:brnqfmy) ([raw file](https://github.com/google/nomulus/blob/236c0210bc2e6f4be2521abd192dece07a7754fa/dependencies.gradle#L141)):*
> ```Gradle
>       'org.apache.beam:beam-runners-direct-java:2.34.0',
>       'org.apache.beam:beam-runners-google-cloud-dataflow-java:2.34.0',
>       'org.apache.beam:beam-sdks-java-core:2.34.0',
> ```

Consider documenting the expiration date for 2.34 (Nov 2022) and the support status page
http://cloud.google.com/dataflow/docs/support/sdk-version-support-status



_Code quote:_
```Gradle
      'org.apache.beam:beam-runners-core-construction-java:2.34.0',
      'org.apache.beam:beam-runners-direct-java:2.34.0',
      'org.apache.beam:beam-runners-google-cloud-dataflow-java:2.34.0',
      'org.apache.beam:beam-sdks-java-core:2.34.0',
      'org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:2.34.0',
      'org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.34.0',
```
___
*[util/src/main/java/google/registry/util/LoggerConfig.java, line 63 at r2](https://reviewable.io/reviews/google/nomulus/1472#-Mr5P5kR7ZQPexT8THvW:-Mr5P5kSB8n_LevfRUhd:bec708c) ([raw file](https://github.com/google/nomulus/blob/236c0210bc2e6f4be2521abd192dece07a7754fa/util/src/main/java/google/registry/util/LoggerConfig.java#L63)):*
> ```Java
> // See https://github.com/google/flogger/issues/142.
> @CheckReturnValue
> public final class LoggerConfig {
> ```

Rename to JdkLoggerConfig to be clear? 
We are doing it internally: https://source.corp.google.com/search?q=JdkLoggerConfig



_Code quote:_
```Java
LoggerConfig
```

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1472)* status: all files reviewed, 4 unresolved discussions (waiting on @jianglai)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/google/nomulus/1472#-Mr5Qcxh2YYFfgk3SsXX):*
2.34



_Code quote:_
```
2.32
```

**Review by jianglai — COMMENTED** [review]
Do we even know what it does?

> Reviewed 20 of 81 files at r1, 1 of 116 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1472#-:-Mr7yg0k1OVL3PHeXLLw:b-dfjpd0)* status: all files reviewed, 4 unresolved discussions (waiting on @weiminyu)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/google/nomulus/1472#-Mr5Qcxh2YYFfgk3SsXX):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

2.34
</blockquote></details>

Oops. Done.
___
*[build.gradle, line 191 at r2](https://reviewable.io/reviews/google/nomulus/1472#-Mr5NCEcAR4dLvGrZzjX:-Mr7wT-F5lu5Ay10cvwg:b2avpn0) ([raw file](https://github.com/google/nomulus/blob/236c0210bc2e6f4be2521abd192dece07a7754fa/build.gradle#L191)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

How about limiting this repo to confluent only:
maven {
    url ...
    content {
          includeGroup 'io.confluent'
     }
}
</blockquote></details>

Also removed `google()` because it was never actually used.
___
*[dependencies.gradle, line 141 at r2](https://reviewable.io/reviews/google/nomulus/1472#-Mr5PohH1K1J_3lnPS4I:-Mr7ws5M1aA0eDwUGBtf:b-mto431) ([raw file](https://github.com/google/nomulus/blob/236c0210bc2e6f4be2521abd192dece07a7754fa/dependencies.gradle#L141)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Consider documenting the expiration date for 2.34 (Nov 2022) and the support status page
http://cloud.google.com/dataflow/docs/support/sdk-version-support-status
</blockquote></details>

Done, but this comment is bound to go rot... No one is going to proactively check this file and see whether any dependency's support status has lapsed.
___
*[util/src/main/java/google/registry/util/LoggerConfig.java, line 63 at r2](https://reviewable.io/reviews/google/nomulus/1472#-Mr5P5kR7ZQPexT8THvW:-Mr7ycRX43msjY-npdtC:b-896fix) ([raw file](https://github.com/google/nomulus/blob/236c0210bc2e6f4be2521abd192dece07a7754fa/util/src/main/java/google/registry/util/LoggerConfig.java#L63)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Rename to JdkLoggerConfig to be clear? 
We are doing it internally: https://source.corp.google.com/search?q=JdkLoggerConfig
</blockquote></details>

Done.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1472)* status: 5 of 286 files reviewed, 4 unresolved discussions (waiting on @jianglai, @mindhog, and @weiminyu)

___
*[build.gradle, line 191 at r2](https://reviewable.io/reviews/google/nomulus/1472#-Mr5NCEcAR4dLvGrZzjX:-Mr7z4oZ6EXcHAuV_4Xn:b-aq8hgv) ([raw file](https://github.com/google/nomulus/blob/236c0210bc2e6f4be2521abd192dece07a7754fa/build.gradle#L191)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Also removed `google()` because it was never actually used.
</blockquote></details>

Actually, maybe we can keep it here. I see no harm.

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1472)* status: 5 of 287 files reviewed, all discussions resolved (waiting on @jianglai, @mindhog, and @weiminyu)

**Review by weiminyu — APPROVED** [review]
io.dropwizard.metrics:metrics-core is used by the bigtable client, a dependency of beam sdk. So not a problem. 3.1.2 is really old though.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1472#-:-Mr8MoTK664oCcJODstC:bgtezgx)* status: 5 of 287 files reviewed, all discussions resolved (waiting on @jianglai, @mindhog, and @weiminyu)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 116 files at r2, 42 of 281 files at r3, 269 of 269 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1472)* status: 288 of 289 files reviewed, all discussions resolved (waiting on @jianglai and @mindhog)

**Pull request merged**
