### PR TITLE
Update IDN tables with latest approved by ICANN

### PR DESCRIPTION
**Pull request by CydeWeys**
This also adds README files to explain the two different IDN table locations (which have different purposes). See http://b/278565478 for more information.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1995)

### CODE REVIEW

**Review by gbrodman — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1995)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kokosta)

**Review by kokosta — APPROVED** [review]
LGTM

**Review by kokosta — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1995#-:-NTL7EYN5EZ4KCuF4jY1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1995)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/idn/Latin-IDN.txt` line 5 at r1](https://reviewable.io/reviews/google/nomulus/1995#-NTLBUjgAJ3tlMuIhKce:-NTLBUjgAJ3tlMuIhKcf:b-qs8r16) ([raw file](https://github.com/google/nomulus/blob/391e2054a4d055a1902add86d8634baff9adf74b/core/src/main/java/google/registry/idn/Latin-IDN.txt#L5)):*
> ```help
> # Version: 2.0
> # Effective Date: 2023-04-04
> # URL: https://www.iana.org/domains/idn-tables/tables/google_latn_2.0.txt
> ```

actually, what's up with this URL? it doesn't seem like it exists

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1995)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/idn/Latin-IDN.txt` line 5 at r1](https://reviewable.io/reviews/google/nomulus/1995#-NTLBUjgAJ3tlMuIhKce:-NTLBnD823FsEOHehQsm:brobh0r) ([raw file](https://github.com/google/nomulus/blob/391e2054a4d055a1902add86d8634baff9adf74b/core/src/main/java/google/registry/idn/Latin-IDN.txt#L5)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

actually, what's up with this URL? it doesn't seem like it exists 
</blockquote></details>

It's not published yet.  It will be soon, right Kalina?

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1995)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/idn/Latin-IDN.txt` line 5 at r1](https://reviewable.io/reviews/google/nomulus/1995#-NTLBUjgAJ3tlMuIhKce:-NTLBrcDE3-e0PgIuFSt:b-4j7w4h) ([raw file](https://github.com/google/nomulus/blob/391e2054a4d055a1902add86d8634baff9adf74b/core/src/main/java/google/registry/idn/Latin-IDN.txt#L5)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

It's not published yet.  It will be soon, right Kalina?
</blockquote></details>

We have this table approved by ICANN, but my understanding is that IANA publishing occurs on a bit of a delay.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1995)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/idn/Latin-IDN.txt` line 5 at r1](https://reviewable.io/reviews/google/nomulus/1995#-NTLBUjgAJ3tlMuIhKce:-NTLBwW-AYEnF28Jp0ql:bset687) ([raw file](https://github.com/google/nomulus/blob/391e2054a4d055a1902add86d8634baff9adf74b/core/src/main/java/google/registry/idn/Latin-IDN.txt#L5)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

We have this table approved by ICANN, but my understanding is that IANA publishing occurs on a bit of a delay.
</blockquote></details>

There's also a chicken-and-egg problem in that we have to send them the table first prior to it being approved (and later published), but we don't actually know what the URL is gonna be until after that happens.  So it's possible we might have to come back through here later once the update is published and fix this.

**Review by kokosta — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1995)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/idn/Latin-IDN.txt` line 5 at r1](https://reviewable.io/reviews/google/nomulus/1995#-NTLBUjgAJ3tlMuIhKce:-NTLDPZm7h0mcV8_c5v9:b1kdpwu) ([raw file](https://github.com/google/nomulus/blob/391e2054a4d055a1902add86d8634baff9adf74b/core/src/main/java/google/registry/idn/Latin-IDN.txt#L5)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ah ok yeah that makes sense, for some reason I was under the impression that the flow of data was from them to us rather than the other way around 
</blockquote></details>

Yes, it should be published when the ICANN approval person sends the table over to IANA. Based on other files in IANA directory, this url is correct (I mean, will be.)

**Pull request merged**
