### PR TITLE
Use new renew cost calculation in handleFeeRequest()

### PR DESCRIPTION
**Pull request by CydeWeys**
The purpose of this PR is to change the renewal cost calculation in `handleFeeRequest()` in `DomainFlowUtil` and fix existing test cases in check and info flow test after adding the new renew price calculation to `DomainFlowUtil`. 

- Missing billing events in existing test cases of `DomainInfoFlowTest.Java`:  two of the existing test cases for renewal have `eventBillingAndHistory` in `doSuccessTest()` as false (which is the default setting). However, if the domain is persisted, corresponding billing event should be there as well. I added a helper method that creates sample `DomainHistory` and `Recurring`  for an existing domain and the changes were made in those two test cases. 

- Missing billing events in existing test cases of `DomainCheckFlowTest.Java`: similar to the issue in `DomainInfoFlowTest` where `DomainHistory` and `Recurring` billing event objects are missing. A helper method was added that could be used to persist billing event for an existing domain. Because of this change, one of the test cases failed because of mismatching xml response file. The content remains the same except the tags are now added in the first `<epp>` tag.  See the diff in `...s/google/registry/flows/domain/domain_check_fee_premium_eap_response_v06_with_renewal.xml`. This file currently has only been used once in all the test cases. 
Moreover, the tags include v11 and v12 and the expiration date ends with .001 second instead of .002.

This is based on PR #1637 by @rachelguan with additional substantial modifications by me.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1694)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1694)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java` line 859 at r3](https://reviewable.io/reviews/google/nomulus/1694#-N6P6-LkBvnZhE-NKSe2:-N6P5buD3VL_iEwRipvI:bnuqbgm) ([raw file](https://github.com/google/nomulus/blob/e564a80ea3c70ca72b7f3daa7d5f6631dd599946/core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java#L859)):*
> ```Java
>         "domain_info_fee.xml",
>         updateSubstitutions(
>             SUBSTITUTION_BASE, "NAME", "example.tld", "COMMAND", "renew", "PERIOD", "1"));
> ```

don't need to set a NAME of example.tld here, it's already that  (same for the other tests below) 
___
*[`core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java` line 882 at r3](https://reviewable.io/reviews/google/nomulus/1694#-N6P6RDc3jNa1rj8ilk9:-N6P6RDc3jNa1rj8ilkA:b-b73qkv) ([raw file](https://github.com/google/nomulus/blob/e564a80ea3c70ca72b7f3daa7d5f6631dd599946/core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java#L882)):*
> ```Java
>             SUBSTITUTION_BASE, "NAME", "example.tld", "COMMAND", "renew", "PERIOD", "1"));
>     persistTestEntities("example.tld", false);
>     setUpBillingEventForExistingDomain(SPECIFIED, Money.of(USD, 3));
> ```

out of curiosity, have we updated the internal-registration allocation token documentation to say that we should use a SPECIFIED renewal price behavior on those tokens? I assume it's still the standard heavy-discount plus a SPECIFIED renewal behavior.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1694)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java` line 882 at r3](https://reviewable.io/reviews/google/nomulus/1694#-N6P6RDc3jNa1rj8ilk9:-N6PGFo71o3SIlb-w9bF:bg70ppg) ([raw file](https://github.com/google/nomulus/blob/e564a80ea3c70ca72b7f3daa7d5f6631dd599946/core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java#L882)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

out of curiosity, have we updated the internal-registration allocation token documentation to say that we should use a SPECIFIED renewal price behavior on those tokens? I assume it's still the standard heavy-discount plus a SPECIFIED renewal behavior. 
</blockquote></details>

We haven't updated the documentation because these PRs aren't quite finished.  Once they are finished, we should absolutely switch over to the new, better mechanism.

(Also this shouldn't be a blocking comment.)

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1694)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java` line 859 at r3](https://reviewable.io/reviews/google/nomulus/1694#-N6P6-LkBvnZhE-NKSe2:-N6PIb-LAJHqvdQgOgzf:bd2tlws) ([raw file](https://github.com/google/nomulus/blob/e564a80ea3c70ca72b7f3daa7d5f6631dd599946/core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java#L859)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

No I'm referring to https://github.com/google/nomulus/blob/master/core/src/test/java/google/registry/flows/domain/DomainInfoFlowTest.java#L87-L91 
</blockquote></details>

Done.  Didn't even notice `updateSubstitutions()` was being called.

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1694)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
