### PR TITLE
Remove not null constraint request_log_id column

### PR DESCRIPTION
**Pull request by ptkach**
This is blocking https://github.com/google/nomulus/pull/1910 from being merge, which in turn is blocking https://github.com/google/nomulus/pull/1911

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1917)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
You probably need to split this to two as well, one with the Java change and the other one with the schema change. I suspect presubmit would not pass as is.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1917#-:-NMFrnIQ5gNKCXjbSN84:bfb2twu)* status: 0 of 7 files reviewed, all discussions resolved

**Review by ptkach — COMMENTED** [review]
Are you sure? To me it seems like removing constraint wouldn't need a split and adding a constraint would. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1917#-:-NMGG18qBttLaun9_ad9:b-t1u3tk)* status: 0 of 7 files reviewed, all discussions resolved

**Comment by jianglai** [comment]
> Are you sure? To me it seems like removing constraint wouldn't need a split and adding a constraint would.
> 
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1917#-:-NMGG18qBttLaun9_ad9:b-t1u3tk)_ status: 0 of 7 files reviewed, all discussions resolved

Apparently you are right!

**Review by jianglai — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1917)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`db/src/main/resources/sql/flyway/V134__drop_not_null_request_id_lock_table.sql` line 1 at r1](https://reviewable.io/reviews/google/nomulus/1917#-NMGU_Jk4OU9gFHzsx3_:-NMGU_Jk4OU9gFHzsx3a:bpl4k8u) ([raw file](https://github.com/google/nomulus/blob/329613f3271b58bad7e495dc05c888651a1679ab/db/src/main/resources/sql/flyway/V134__drop_not_null_request_id_lock_table.sql#L1)):*
> ```TSQL
> -- Copyright 2022 The Nomulus Authors. All Rights Reserved.
> ```

2023.

Admittedly I myself probably didn't remember to update the date in my recent PRs...



_Code quote:_
```TSQL
2022
```

**Pull request merged**
