### PR TITLE
Update TMCH root certificate

### PR DESCRIPTION
**Pull request by jianglai**
See b/260945047.

Also refactored the corresponding tests, which should future updates easier.

This change should be deployed at or around 2023-02-15T16:00:00Z.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1918)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1918)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 74 of 75 files at r2, 109 of 109 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1918)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 8 of 75 files at r2, 109 of 109 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1918)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @jianglai)

___
*[`core/src/test/java/google/registry/tmch/TmchTestData.java` line 62 at r5](https://reviewable.io/reviews/google/nomulus/1918#-NMjThPh8a5lDY8KK9xO:-NMjThPh8a5lDY8KK9xP:bn7nxnf) ([raw file](https://github.com/google/nomulus/blob/0bbde1e412edcc718a53fd0c83ef7bbda86fc522/core/src/test/java/google/registry/tmch/TmchTestData.java#L62)):*
> ```Java
>   }
> 
>   public static ImmutableList<String> extractLabels(String filepath) {
> ```

what's up with this method? I don't think I see it being used anywhere

**Review by jianglai — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1918)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[`core/src/test/java/google/registry/tmch/TmchTestData.java` line 62 at r5](https://reviewable.io/reviews/google/nomulus/1918#-NMjThPh8a5lDY8KK9xO:-NMjXOuv2_iDcCrtBRnL:bscy0sy) ([raw file](https://github.com/google/nomulus/blob/0bbde1e412edcc718a53fd0c83ef7bbda86fc522/core/src/test/java/google/registry/tmch/TmchTestData.java#L62)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what's up with this method? I don't think I see it being used anywhere 
</blockquote></details>

It's used in `DomainCreateFlowTest`.



_Code quote:_
```Java
extractLabels
```

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1918)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

___
*[`core/src/test/java/google/registry/tmch/TmchTestData.java` line 62 at r5](https://reviewable.io/reviews/google/nomulus/1918#-NMjThPh8a5lDY8KK9xO:-NMjY9tF65CVtY0xLBG4:b73vwga) ([raw file](https://github.com/google/nomulus/blob/0bbde1e412edcc718a53fd0c83ef7bbda86fc522/core/src/test/java/google/registry/tmch/TmchTestData.java#L62)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It's used in `DomainCreateFlowTest`.
</blockquote></details>

ah, github sneakily hadn't expanded all of the files

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1918)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
