### PR TITLE
Move console global loader, fix table scrollers

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2494)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2494)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/google/nomulus/2494#-O1XSGZFBWKjOR3ZkxLv):*
commit message should conform to the guidelines e.g. https://engdoc.corp.google.com/eng/doc/devguide/coding/review/developer/cl-descriptions.md?cl=head

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2494)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @gbrodman)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/google/nomulus/2494#-O1XSGZFBWKjOR3ZkxLv):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

commit message should conform to the guidelines e.g. https://engdoc.corp.google.com/eng/doc/devguide/coding/review/developer/cl-descriptions.md?cl=head
</blockquote></details>

Updated

**Review by gbrodman — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2494#-:-O1cI0iT7hFbA_lojJGt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2494)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
