### PR TITLE
Remove ofy support from Address

### PR DESCRIPTION
**Pull request by jianglai**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1759)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1759)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1759)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/model/eppcommon/Address.java` line 62 at r3](https://reviewable.io/reviews/google/nomulus/1759#-NAPX7iNDmSCvYE9dpx5:-NAPX7iNDmSCvYE9dpx6:b-q48iau) ([raw file](https://github.com/google/nomulus/blob/c95314f7a7628fbd579dc6a12a38265df4a4bab0/core/src/main/java/google/registry/model/eppcommon/Address.java#L62)):*
> ```Java
>    * At most three lines of addresses parsed from XML elements.
>    *
>    * <p>This filed is used to marshall to/unmarshall from XML elements. When persisting to/from SQL,
> ```

nits: "field", and also "(un)marshal" with one L 

good explanation though 
___
*[`core/src/test/java/google/registry/model/eppcommon/AddressTest.java` line 96 at r3](https://reviewable.io/reviews/google/nomulus/1759#-NAPZS5T5Q4AlFHYVn3F:-NAPZS5T5Q4AlFHYVn3G:b-l7p8dh) ([raw file](https://github.com/google/nomulus/blob/c95314f7a7628fbd579dc6a12a38265df4a4bab0/core/src/test/java/google/registry/model/eppcommon/AddressTest.java#L96)):*
> ```Java
>     assertAddress(savedEntity.address, "line1", "line2");
>     assertThat(savedEntity.address.streetLine3).isNull();
>   }
> ```

This isn't exactly related to this PR, but should we forbid the case where one street field is null/empty but one(s) after it aren't? Like, I feel like the case where 

```
street1 = null
street2 = something
street3 = something
```

is probably bad?

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1759)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/model/eppcommon/Address.java` line 62 at r3](https://reviewable.io/reviews/google/nomulus/1759#-NAPX7iNDmSCvYE9dpx5:-NAPas1l4dvl-CxZWrJA:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c95314f7a7628fbd579dc6a12a38265df4a4bab0/core/src/main/java/google/registry/model/eppcommon/Address.java#L62)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nits: "field", and also "(un)marshal" with one L 

good explanation though 
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/model/eppcommon/AddressTest.java` line 96 at r3](https://reviewable.io/reviews/google/nomulus/1759#-NAPZS5T5Q4AlFHYVn3F:-NAPbJgM30Dp_fCKaBm1:b3d0n3p) ([raw file](https://github.com/google/nomulus/blob/c95314f7a7628fbd579dc6a12a38265df4a4bab0/core/src/test/java/google/registry/model/eppcommon/AddressTest.java#L96)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This isn't exactly related to this PR, but should we forbid the case where one street field is null/empty but one(s) after it aren't? Like, I feel like the case where 

```
street1 = null
street2 = something
street3 = something
```

is probably bad?
</blockquote></details>

The street list is set via the `setStreet` method on the builder, which takes an `ImmutableList`. The `ImmutableList` builder already prevents null elements, so all we need to worry about is empty strings. I think it makes sense to disallow empty strings in the provided list, regardless of where they are. If you have a list of `["foo", "bar", ""]`, it should just be `["foo", "bar"]`.

Added a check and the corresponding test.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1759)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/model/eppcommon/Address.java` line 163 at r5](https://reviewable.io/reviews/google/nomulus/1759#-NAQ-PzBE_UY1Z3rT4M1:-NAQ-PzC2EmfWdtcxnjt:b-yldpmb) ([raw file](https://github.com/google/nomulus/blob/1661cf873117c2bb5b52843b87bf19ff4a447a08/core/src/main/java/google/registry/model/eppcommon/Address.java#L163)):*
> ```Java
>           "Street address must have [1-3] lines: %s",
>           street);
>       //noinspection ConstantConditions
> ```

up to you if you want to do this, but you can get around this required comment by using guava's Strings::isNullOrEmpty

**Review by gbrodman — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1759#-:-NAQ-awA8spdMI8CebQe:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

**Comment by jianglai** [comment]
> > Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1759)_ status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)
> 
> _[`core/src/main/java/google/registry/model/eppcommon/Address.java` line 163 at r5](https://reviewable.io/reviews/google/nomulus/1759#-NAQ-PzBE_UY1Z3rT4M1:-NAQ-PzC2EmfWdtcxnjt:b-yldpmb) ([raw file](https://github.com/google/nomulus/blob/1661cf873117c2bb5b52843b87bf19ff4a447a08/core/src/main/java/google/registry/model/eppcommon/Address.java#L163)):_
> 
> > ```java
> >           "Street address must have [1-3] lines: %s",
> >           street);
> >       //noinspection ConstantConditions
> > ```
> 
> up to you if you want to do this, but you can get around this required comment by using guava's Strings::isNullOrEmpty

The warning is on the nullness of `steet` itself, which is a bit silly because we already checked for that in the previous `checkArgument` statement...

**Pull request merged**
