### PR TITLE
Change BillingEvent parent to Key<DomainHistory>

### PR DESCRIPTION
**Pull request by jianglai**
Only domain related actions can result in billing. The fact that the
@PostLoad method on DomainHistory creates a Key whose parent is a Key to
DomainBase further corroborates with this statement. Therefore it makes
sense to change the parent type to be more restrictive. This also makes
it easier down the road to expand recurring billing events to onetimes.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1178)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 293 at r1](https://reviewable.io/reviews/google/nomulus/1178#-MaUolDU7KJ6CDOG0Tww:-MaUolDU7KJ6CDOG0Twx:b-4r7l6g) ([raw file](https://github.com/google/nomulus/blob/0c83a8788e958452f4145d8149ba2af84a77a232/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L293)):*
> ```Java
>     BillingEvent.OneTime billingEvent = persistSimpleResource(
>         new BillingEvent.OneTime.Builder()
>             .setParent((DomainHistory) historyEntry.toChildHistoryEntity())
> ```

We should be able to change the variable type above to avoid the cast.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 293 at r1](https://reviewable.io/reviews/google/nomulus/1178#-MaUolDU7KJ6CDOG0Tww:-MaV53Cd8lx5cmxGQQ2a:b-nwsigi) ([raw file](https://github.com/google/nomulus/blob/0c83a8788e958452f4145d8149ba2af84a77a232/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L293)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

We should be able to change the variable type above to avoid the cast. 
</blockquote></details>

Did this first, but for some reason if I call `toChildHistoryEntyty` on the return value of `persistSimpleResource` above I get a cast error:

```
class google.registry.model.reporting.HistoryEntry cannot be cast to class google.registry.model.domain.DomainHistory (google.registry.model.reporting.HistoryEntry and google.registry.model.domain.DomainHistory are in unnamed module of loader 'app')
java.lang.ClassCastException: class google.registry.model.reporting.HistoryEntry cannot be cast to class google.registry.model.domain.DomainHistory (google.registry.model.reporting.HistoryEntry and google.registry.model.domain.DomainHistory are in unnamed module of loader 'app')
```

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 293 at r1](https://reviewable.io/reviews/google/nomulus/1178#-MaUolDU7KJ6CDOG0Tww:-MaV8YOc7waLetQIYUpc:b-wp4jto) ([raw file](https://github.com/google/nomulus/blob/0c83a8788e958452f4145d8149ba2af84a77a232/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L293)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Did this first, but for some reason if I call `toChildHistoryEntyty` on the return value of `persistSimpleResource` above I get a cast error:

```
class google.registry.model.reporting.HistoryEntry cannot be cast to class google.registry.model.domain.DomainHistory (google.registry.model.reporting.HistoryEntry and google.registry.model.domain.DomainHistory are in unnamed module of loader 'app')
java.lang.ClassCastException: class google.registry.model.reporting.HistoryEntry cannot be cast to class google.registry.model.domain.DomainHistory (google.registry.model.reporting.HistoryEntry and google.registry.model.domain.DomainHistory are in unnamed module of loader 'app')
```
</blockquote></details>

Yeah that's because persistResource returns the thing persisted, which for Datastore is a history entry (iirc). 

You need to create the DomainHistory, persist it, possibly reload it explicitly as a DomainHistory (maybe?), then use it

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 293 at r1](https://reviewable.io/reviews/google/nomulus/1178#-MaUolDU7KJ6CDOG0Tww:-MaWNb1iEH6mwT3IVMsa:bcyzbg0) ([raw file](https://github.com/google/nomulus/blob/0c83a8788e958452f4145d8149ba2af84a77a232/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L293)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yeah that's because persistResource returns the thing persisted, which for Datastore is a history entry (iirc). 

You need to create the DomainHistory, persist it, possibly reload it explicitly as a DomainHistory (maybe?), then use it 
</blockquote></details>

Actually, `persistResource` is fine. A lot of the files in this PR use it to persist and load `DomainHistory`. It is the `persistSimpleResource` method, which ultimately uses `loadByEntitiesIfPresent` that didn't do the conversion correctly, unlike `loadByEntity`. `persistResource` uses the latter rather than the former.

Fixed.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: 28 of 31 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @jianglai)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 228 at r2](https://reviewable.io/reviews/google/nomulus/1178#-MaYsSc107g56MEN_ZCP:-MaYsSc107g56MEN_ZCQ:b-l3y05u) ([raw file](https://github.com/google/nomulus/blob/452651ece834c654e28c383c842ff63c62402225/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L228)):*
> ```Java
>   @Override
>   public <T> ImmutableList<T> loadByEntitiesIfPresent(Iterable<T> entities) {
>     return Streams.stream(entities)
> ```

This seems like a performance degradation; I think we need to do the same object-transformation logic in the result of the previously-existing `.entities(entities).values()` call rather than delegate to `loadByEntity`

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 283 at r2](https://reviewable.io/reviews/google/nomulus/1178#-MaYt7G73YiNjz0eXWNC:-MaYt7G73YiNjz0eXWND:b-q0gdiy) ([raw file](https://github.com/google/nomulus/blob/452651ece834c654e28c383c842ff63c62402225/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L283)):*
> ```Java
>   private static Set<ImmutableObject> persistDomainAndDescendants(String fqdn) {
>     DomainBase domain = persistDeletedDomain(fqdn, DELETION_TIME);
>     DomainHistory historyEntry =
> ```

super nit: variable name

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: 30 of 31 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 228 at r2](https://reviewable.io/reviews/google/nomulus/1178#-MaYsSc107g56MEN_ZCP:-MaZ5uINC-9YLrPUSf8G:b-896fix) ([raw file](https://github.com/google/nomulus/blob/452651ece834c654e28c383c842ff63c62402225/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L228)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This seems like a performance degradation; I think we need to do the same object-transformation logic in the result of the previously-existing `.entities(entities).values()` call rather than delegate to `loadByEntity` 
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 283 at r2](https://reviewable.io/reviews/google/nomulus/1178#-MaYt7G73YiNjz0eXWNC:-MaZ5uqu6BDYSLq8JlIp:bq4cjdy) ([raw file](https://github.com/google/nomulus/blob/452651ece834c654e28c383c842ff63c62402225/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L283)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

super nit: variable name 
</blockquote></details>

I thought about it but there are so many of them in this PR which makes it not seem like a worthy endeavor. A `DomainHistory` is a `HistoryEntry` after all. Unless you feel strongly about it...

**Review by gbrodman — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178#-:-MaZEgGD7vq4KyWyjnDo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 234 at r3](https://reviewable.io/reviews/google/nomulus/1178#-MaZEbpg03WhzEgbmCiQ:-MaZEbpg03WhzEgbmCiR:b7h3dyt) ([raw file](https://github.com/google/nomulus/blob/54e10162e0247fbbd2678300cbc35f86afbfbfcc/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L234)):*
> ```Java
>         .stream()
>         .map(DatastoreTransactionManager::toSqlEntity)
>         .map(entity -> (T) entity)
> ```

hah this is unfortunate 
___
*[core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java, line 283 at r2](https://reviewable.io/reviews/google/nomulus/1178#-MaYt7G73YiNjz0eXWNC:-MaZ7M36B8PA5iMOLm_3:b32wko) ([raw file](https://github.com/google/nomulus/blob/452651ece834c654e28c383c842ff63c62402225/core/src/test/java/google/registry/batch/DeleteProberDataActionTest.java#L283)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I thought about it but there are so many of them in this PR which makes it not seem like a worthy endeavor. A `DomainHistory` is a `HistoryEntry` after all. Unless you feel strongly about it... 
</blockquote></details>

eh

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: 31 of 32 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[gjf.out, line 0 at r4](https://reviewable.io/reviews/google/nomulus/1178#-MaZZD3KDZqODlO0vM2o:-MaZZD3L1O-voXw99N6J:b-pn9q8k) ([raw file](https://github.com/google/nomulus/blob/4b279a7c996196ce99c9dc49b70fd937de86946d/gjf.out#L0)):*
plz remove (I have a PR open that incidentally adds this to .gitignore, we could also do that here)

**Review by gbrodman — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178)* status: 31 of 33 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[gjf.out, line  at r4](https://reviewable.io/reviews/google/nomulus/1178#-MaZZD3KDZqODlO0vM2o:-MaZpGoI0Nc71JBOx69a:b-inyfdy) ([raw file](https://github.com/google/nomulus/blob/4b279a7c996196ce99c9dc49b70fd937de86946d/gjf.out#L)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

plz remove (I have a PR open that incidentally adds this to .gitignore, we could also do that here) 
</blockquote></details>

Done. Added to `.gitignore`. Do  you know why this file keeps popping up?

**Review by gbrodman — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1178#-:-MaZrB_l71q6JT2JYWZr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

___
*[gjf.out, line  at r4](https://reviewable.io/reviews/google/nomulus/1178#-MaZZD3KDZqODlO0vM2o:-MaZr7ZG6Ntn_dsIVLnl:b-grn3lo) ([raw file](https://github.com/google/nomulus/blob/4b279a7c996196ce99c9dc49b70fd937de86946d/gjf.out#L)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Done. Added to `.gitignore`. Do  you know why this file keeps popping up?
</blockquote></details>

It's the output from google-java-format run through the Gradle task, I believe.

**Pull request merged**
