### PR TITLE
Upgrade testcontainers to work around a race

### PR DESCRIPTION
**Pull request by weiminyu**
testcontainers 1.15.x has a race condition that occasionally causes deadlocks.
This can be worked around by upgrading to 1.15.2 and set transport type to
http5.

See https://github.com/testcontainers/testcontainers-java/issues/3531
for more information.

There are two changes that are not lockfiles:
- dependencies.gradle
- java_common.gradle

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1080)

### CODE REVIEW

**Review by jianglai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1080)* status: 0 of 66 files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)

___
*[java_common.gradle, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1080#-MYDU6aP9hnBdHXS7edS:-MYDU6aP9hnBdHXS7edT:b-fbdh6t) ([raw file](https://github.com/google/nomulus/blob/343b3e6f412554ce875c60968d9d733a72593eab/java_common.gradle#L104)):*
> ```
> environment
> ```
Does this actually work? I only see this method exists in type `Exec`, but not `Test`:

https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Exec.html
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/Test.html

**Review by mindhog — COMMENTED** [review]
FYI, show_upgrade_diffs output is:

```
Package version change report:
change package-name: {old versions} -> {new versions}
=====================================================

updated org.testcontainers:database-commons: {1.15.1} -> {1.15.2}
updated org.testcontainers:jdbc: {1.15.1} -> {1.15.2}
updated org.testcontainers:postgresql: {1.15.1} -> {1.15.2}
updated org.testcontainers:testcontainers: {1.15.1} -> {1.15.2}
updated org.testcontainers:junit-jupiter: {1.15.1} -> {1.15.2}
updated org.testcontainers:selenium: {1.15.1} -> {1.15.2}
```

> Reviewed 2 of 66 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1080#-:-MYFSIlDCAfDc2nn627p:b1p4gp1)* status: 2 of 66 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

**Review by mindhog — APPROVED** [review]
> Reviewed 64 of 66 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[java_common.gradle, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1080#-MYDU6aP9hnBdHXS7edS:-MYFUrcTBVJHp4zrgqYo:bto8ump) ([raw file](https://github.com/google/nomulus/blob/343b3e6f412554ce875c60968d9d733a72593eab/java_common.gradle#L104)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> environment
> ```
Does this actually work? I only see this method exists in type `Exec`, but not `Test`:

https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Exec.html
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/Test.html
</blockquote></details>

It does [appear to exist in Test](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/Test.html#environment-java.lang.String-java.lang.Object-).

**Comment by jianglai** [comment]
> > Reviewed 64 of 66 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1080)_ status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)
> 
> _[java_common.gradle, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1080#-MYDU6aP9hnBdHXS7edS:-MYFUrcTBVJHp4zrgqYo:bto8ump) ([raw file](https://github.com/google/nomulus/blob/343b3e6f412554ce875c60968d9d733a72593eab/java_common.gradle#L104)):_
> 
> Previously, jianglai (Lai Jiang) wrote…
> It does [appear to exist in Test](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/Test.html#environment-java.lang.String-java.lang.Object-).

You are right. Not sure how I missed that.

**Review by jianglai — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1080#-:-MYFWdZOBmCL2bNjIBzm:bb6ywmx)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Pull request merged**
