### PR TITLE
Add Flyway file for lastUpdateTimeViaEpp

### PR DESCRIPTION
**Pull request by gbrodman**
See b/248035435 for more details / reasoning, but basically this will make it easier if we ever need to restore user actions in the future (or figure out which user actions went wrong)

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1828)

### CODE REVIEW

**Review by CydeWeys — COMMENTED** [review]
I'm not 100% sold on this name.  `last_manual_update_time` doesn't seem right to me, as many EPP updates which would update this field are in fact automated actions, not manual actions, e.g. a registrar performing a bulk routine change of nameservers across domains under management.

How about something like `last_epp_flow_update_time` or `last_update_time_via_epp`?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1828#-:-NFUkDn885VM1lYPag7n:b-boulxj)* status: 0 of 5 files reviewed, all discussions resolved

**Review by gbrodman — COMMENTED** [review]
yeah I think you're right, and I think the latter is better (just to cover as much ground as possible). 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1828#-:-NFyd__LCKtG1nb693dn:b-ekijjj)* status: 0 of 5 files reviewed, all discussions resolved

**Review by CydeWeys — COMMENTED** [review]
All right, so where does `last_update_time_via_epp` fit in with the existing fields `last_epp_update_time`, `last_epp_update_registrar_id`, and `update_timestamp`?  It's kind of becoming a confusing morass at this point.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1828#-:-NZlRFb532RVSzu10Aa1:b5k2ulj)* status: 0 of 5 files reviewed, all discussions resolved

**Comment by gbrodman** [comment]
`last_epp_update_time` reflects the last update of basically any of the EPP-related fields. As commented on the bug, it can be updated in situations like autorenews or removal of grace periods (things that happen during projection) meaning that it does not actually reflect the last time an EPP request was sent that updates this field. 

i'm not necessarily 100% convinced that we need to do this, but this helps protect against the type of situation where the Domain and DomainHistory objects get out of sync (what happened last September). last_epp_update_time wasn't usable / valid then because of the aforementioned other ways in which it could be changed. 

update_timestamp is just the basic field that gets updated any time anything happens

**Review by CydeWeys — COMMENTED** [review]
So `last_epp_update_time` is really more like `last_rdds_update_time` or `last_update_time_in_rdds`?  Ooof.  Ideally we'd update that too, but it's gonna be a bit more work.  Wish we'd named that one better in the beginning.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1828#-:-NZlXwk72HL3aiIcHDnS:b442sjt)* status: 0 of 5 files reviewed, all discussions resolved

**Review by gbrodman — COMMENTED** [review]
What do you mean exactly by "rdds"? Either way yeah it's kind of an in-between sort of field unfortunately 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1828#-:-NZm2Wxk2LzIMqqGlJzm:bxsam5g)* status: 0 of 5 files reviewed, all discussions resolved

**Review by CydeWeys — COMMENTED** [review]
https://www.icann.org/en/blogs/details/whats-new-on-the-rdds-roadmap-10-9-2020-en

It's the umbrella term for WHOIS/RDAP/anything else in the future that accomplishes the same thing.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1828#-:-N_0Pb3_4sqikJZkEY4x:b-ke6cmp)* status: 0 of 5 files reviewed, all discussions resolved

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1828#-:-N_0V6jt3iBqrjgjBYOj:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved

**Review by CydeWeys — COMMENTED** [review]
Just make sure that the field descriptions in the subsequent Java code PR are _really_ good so that people can keep these 3 different things straight.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1828#-:-N_0V93j3obAHZKgG054:bvjdale)* status: 0 of 5 files reviewed, all discussions resolved

**Pull request merged**
