### PR TITLE
Fix VKey reconstruction issue in BillingEvent

### PR DESCRIPTION
**Pull request by hstonec**
The VKey reconstructed from BillingEvent loaded from Cloud SQL was not fully compatible with the original VKey, its `VKey.getOfy()` key missed its parent key, i.e. `Key<DomainBase>` and `Key<HistoryEntry>`. This PR fixed the problem
by adding `postLoad()` method to set `parent` field correctly.

Also, this PR disabled auto-generation for the `BillingEvent`'s id field in Cloud SQL as it conflicts with the way the id
is generated from `Buildable.build`.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/805)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
This generally looks good, but we should probably hold off on submission until after the design review.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/805#-:-MHHkase9hSiLie4pgnN:bhhglm8)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec)

___
*[core/src/main/java/google/registry/model/billing/BillingEvent.java, line 261 at r1](https://reviewable.io/reviews/google/nomulus/805#-MHHgg6e7tvV0ZdOAGGi:-MHHgg6e7tvV0ZdOAGGj:b-wq07m7) ([raw file](https://github.com/google/nomulus/blob/d5ce3248185c2e7c8e4f0fdc724e8a7799c1fb1a/core/src/main/java/google/registry/model/billing/BillingEvent.java#L261)):*
> ```Java
>     }
> 
>     public B setParent(Key<HistoryEntry> parentKey) {
> ```

Should parentKey be a VKey?  It seems like it would simplify the call-sites.
___
*[core/src/test/java/google/registry/model/billing/BillingEventTest.java, line 179 at r1](https://reviewable.io/reviews/google/nomulus/805#-MHHhbGv6RyNF0FS7fUX:-MHHhbGv6RyNF0FS7fUY:bhzwa6u) ([raw file](https://github.com/google/nomulus/blob/d5ce3248185c2e7c8e4f0fdc724e8a7799c1fb1a/core/src/test/java/google/registry/model/billing/BillingEventTest.java#L179)):*
> ```Java
> 
>     BillingEvent.OneTime persisted = jpaTm().transact(() -> jpaTm().load(oneTime.createVKey()));
>     // TODO(b/168325240): Remove this fix after VKeyConverter generates symmetric key.
> ```

"generates symmetric key for AllocationToken"?
___
*[db/src/main/resources/sql/flyway/V54__drop_default_value_and_sequences_for_billing_event.sql, line 1 at r1](https://reviewable.io/reviews/google/nomulus/805#-MHHlQqt3wYUVeB_gMSv:-MHHlQqt3wYUVeB_gMSw:b1m5oyq) ([raw file](https://github.com/google/nomulus/blob/d5ce3248185c2e7c8e4f0fdc724e8a7799c1fb1a/db/src/main/resources/sql/flyway/V54__drop_default_value_and_sequences_for_billing_event.sql#L1)):*
> ```TSQL
> -- Copyright 2020 The Nomulus Authors. All Rights Reserved.
> ```

Just a head's up: I'm currently also using V54 in #804 -- we can change one or the other depending on which lands first.

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/805)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec and @mindhog)

___
*[core/src/main/java/google/registry/model/billing/BillingEvent.java, line 261 at r1](https://reviewable.io/reviews/google/nomulus/805#-MHHgg6e7tvV0ZdOAGGi:-MHMYcpoBp8Z2enHQy1Z:budx1v7) ([raw file](https://github.com/google/nomulus/blob/d5ce3248185c2e7c8e4f0fdc724e8a7799c1fb1a/core/src/main/java/google/registry/model/billing/BillingEvent.java#L261)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Should parentKey be a VKey?  It seems like it would simplify the call-sites.
</blockquote></details>

Are you thinking any specific use case? I am thinking even we have a vkey for the parent key, in most of the use cases we will still have to extract its ofy key so I am inclined to keep it.
___
*[core/src/test/java/google/registry/model/billing/BillingEventTest.java, line 179 at r1](https://reviewable.io/reviews/google/nomulus/805#-MHHhbGv6RyNF0FS7fUX:-MHMVHlw5CEJyAqHuT_Z:b-896fix) ([raw file](https://github.com/google/nomulus/blob/d5ce3248185c2e7c8e4f0fdc724e8a7799c1fb1a/core/src/test/java/google/registry/model/billing/BillingEventTest.java#L179)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

"generates symmetric key for AllocationToken"?
</blockquote></details>

Done.

**Review by mindhog — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/805)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec and @mindhog)

___
*[core/src/main/java/google/registry/model/billing/BillingEvent.java, line 261 at r1](https://reviewable.io/reviews/google/nomulus/805#-MHHgg6e7tvV0ZdOAGGi:-MHMa6lB9dg0-Mfp29F4:blnnsap) ([raw file](https://github.com/google/nomulus/blob/d5ce3248185c2e7c8e4f0fdc724e8a7799c1fb1a/core/src/main/java/google/registry/model/billing/BillingEvent.java#L261)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

Are you thinking any specific use case? I am thinking even we have a vkey for the parent key, in most of the use cases we will still have to extract its ofy key so I am inclined to keep it.
</blockquote></details>

Nothing specific, no.  But if this is called from the business practice code it seems like we would generally be using vkeys, no?

**Review by hstonec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/805)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec and @mindhog)

___
*[core/src/main/java/google/registry/model/billing/BillingEvent.java, line 261 at r1](https://reviewable.io/reviews/google/nomulus/805#-MHHgg6e7tvV0ZdOAGGi:-MHNH_xcDN1jyYnQN692:b-jeh3xo) ([raw file](https://github.com/google/nomulus/blob/d5ce3248185c2e7c8e4f0fdc724e8a7799c1fb1a/core/src/main/java/google/registry/model/billing/BillingEvent.java#L261)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Nothing specific, no.  But if this is called from the business practice code it seems like we would generally be using vkeys, no?
</blockquote></details>

I think we use VKey just for entity itself but not for its parent, it seems to work well.

**Review by mindhog — APPROVED** [review]
LGTM.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/805#-:-MHWabM-3SFzbzWgGn3_:b-85i63v)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec and @mindhog)

**Review by mindhog — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/805)* status: all files reviewed, 3 unresolved discussions (waiting on @hstonec and @mindhog)

**Pull request merged**
