### PR TITLE
Remove buildSrc

### PR DESCRIPTION
**Pull request by jianglai**
We don't use the upload results feature (kokoro picks the results
artifacts directly and uploads them).

Keeping it around is a maintenance burden.

Also fixed a deprecation warning.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2379)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys and @weiminyu)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys and @weiminyu)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys and @weiminyu)

**Review by weiminyu — APPROVED** [review]
> Reviewed 18 of 19 files at r1, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2379)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
