### PR TITLE
Add mapreduce action to create synthetic history entries

### PR DESCRIPTION
**Pull request by gbrodman**
RDE and zone file generation require being able to tell what objects
looked like in the past (though not beyond 30 days, or whatever the
Datastore retention period is set to). In Datastore, to answer this we
look at commit logs, and in SQL we will look at the History objects
stored for each EPP resource. This action can be run once while in
Datastore-primary-SQL-secondary to make sure that every EPP resource has
at least one history entry for which the resource-at-this-time field is
filled out in the SQL world.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1125)

### CODE REVIEW

**Review by CydeWeys — COMMENTED** [review]
Why a mapreduce action instead of a Dataflow job?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1125#-:-MZoHW9PAg5zpd6cQgtr:b-mdd5f4)* status: 0 of 3 files reviewed, all discussions resolved

**Review by gbrodman — COMMENTED** [review]
There's already existing infrastructure for the "mapping over all EppResource objects" paradigm, and given that this is scrap work anyway it didn't seem necessary to have it as a dataflow job. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1125#-:-MZo__tJBy79BswkURP2:b-9z95xe)* status: 0 of 3 files reviewed, all discussions resolved

**Review by gbrodman — COMMENTED** [review]
OK @cydeweys , PTAL / any thoughts? It seems easier to write this as a mapreduce rather than a dataflow because 

1. it requires less infrastructure code
2. it's only run once, so deploying an entire template seems like overkill 
3. there's already infrastructure for the "map over all EPP resources" part
4. It doesn't need to run in the SQL world

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1125#-:-M_22VCw4yeKxcSvplVB:bz8o5i7)* status: 0 of 4 files reviewed, all discussions resolved

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1125)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 1 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_QsFlM-QAy8UKTguCI:-M_TELe57MaBTznUqGCa:bklbe5p) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L1)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Wrong year
</blockquote></details>

wdym, it's still March 2020?

done.
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 45 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_QtYZ-3g0qCe_KIBFm:-M_TFb9r0i3RkWE6Jyko:b-896fix) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L45)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs an explanation of what exactly the history object contains.  I'm guessing the answer is essentially nothing, that all we're doing is triggering async replication to populate the current state of the history content, but that should be made clear.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 52 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_QsazY2_L7xVtyo1n2:-M_TFcmTCMsz_QL-O6Gk:b-3303wb) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L52)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

So as of now, we still don't have any history content in Cloud SQL at all, because the one-time import doesn't create it?  We're relying solely on async replication for this data?  (With getting that running asap being your highest priority.)  And we need to turn that on first before we can run this action and have it do its job?
</blockquote></details>

Correct. This action must be run during the period of time when Datastore is primary and SQL is secondary. 
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 57 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_Qvwe44_YfrCPvbJlh:-M_TFvHJAdZjR9H2wCrz:b-xs7lou) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L57)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You need to add this path to backend's `web.xml` for it to actually be callable.
</blockquote></details>

Of course, thanks.
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 65 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_QtMAk0ZCBeEAtirbF:-M_TG3Z31ApT8_OD13_X:b-896fix) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L65)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

New code should be written using constructor injection.  The style guide prefers it.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 72 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_QtSQAC-KEtjiyKEDM:-M_THSqk5qU_AZ1yVB26:b-896fix) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L72)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Might want to clarify why it makes the migration tougher.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 99 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_QuiyI6lVNn0D6ORS1:-M_TH1W17zZTJLZmoW8J:b-ujx2fw) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L99)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is wrong (and is incompatible with `setRequestedByRegistrar(false)` besides).  It needs to be the registry client ID.  These history entries are not associated with any action taken by the registrar, which is what setting them this way would imply.
</blockquote></details>

Ah, I see -- the registrar ID here should correspond to the "registrar" performing the action, of course 
___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 104 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_QuNvO-PbfujSS9pJK:-M_THU5hB6CV7oBeD0mw:b-bzzl6m) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L104)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs a much better reason than that.  Something like "Backfill EPP resource history content for Cloud SQL migration".  Remember, this string is all that people are going to be seeing in isolation years down the line when they're trying to debug some issue in prod, see this, and then wonder what the heck it's all about.
</blockquote></details>

Ah, I didn't know we could / wanted to use long strings for this. 
___
*[core/src/test/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesActionTest.java, line 1 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_Qtw3524xGAnUjGx90:-M_TFKtn28ynSVeUC6KE:b-896fix) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/test/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesActionTest.java#L1)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Wrong year.
</blockquote></details>

Done.
___
*[core/src/test/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesActionTest.java, line 43 at r1](https://reviewable.io/reviews/google/nomulus/1125#-M_Qu2IK1NLynU46RNhC:-M_TOWg10HtUxg6pSLnH:b-gejbae) ([raw file](https://github.com/google/nomulus/blob/59e013312116a1cc8f6c538ddcd106be1ce9dcf1/core/src/test/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesActionTest.java#L43)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

If you're only gonna have one test then these should all be inlined in said one test.  But I think you need more than one test.  You don't have any deleted EPP resources being tested, nor do you have any existing history entries on any of these entities.
</blockquote></details>

Fair, this can be moved around a decent bit. 

Added tests for the two use cases you mentioned.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1125)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 65 at r2](https://reviewable.io/reviews/google/nomulus/1125#-M_X8mRC8NfPdWG_9F_1:-M_X8mRD1fUsHA4wIRjL:bka5mbk) ([raw file](https://github.com/google/nomulus/blob/daa1f73fd45544d9d40fdbb1d8a4133c6ba84c32/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L65)):*
> ```Java
> 
>   private static final String REASON =
>       "Backfill EPP resource history objects during the Cloud SQL migration to guarantee at "
> ```

This is a little too long now (remember, we're going to create a history entry containing this for all of our millions of EPP resources).

You can see get some ideas from the existing reasons by running the following BigQuery query:

```
SELECT reason, COUNT(*) AS num FROM `domain-registry.latest_datastore_export.HistoryEntry` GROUP BY reason ORDER BY num DESC
```

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1125)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java, line 65 at r2](https://reviewable.io/reviews/google/nomulus/1125#-M_X8mRC8NfPdWG_9F_1:-M_XhMoLBir23RmBX0vI:bgzrhv8) ([raw file](https://github.com/google/nomulus/blob/daa1f73fd45544d9d40fdbb1d8a4133c6ba84c32/core/src/main/java/google/registry/tools/javascrap/CreateSyntheticHistoryEntriesAction.java#L65)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is a little too long now (remember, we're going to create a history entry containing this for all of our millions of EPP resources).

You can see get some ideas from the existing reasons by running the following BigQuery query:

```
SELECT reason, COUNT(*) AS num FROM `domain-registry.latest_datastore_export.HistoryEntry` GROUP BY reason ORDER BY num DESC
```
</blockquote></details>

Ah, fair enough

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1125#-:-M_aB2qHEId0LQIgODSi:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
