### PR TITLE
Add page for WHOIS-editable fields in the console

### PR DESCRIPTION
**Pull request by gbrodman**
This isn't the prettiest thing, but it replicates the type of view / edit functionality that we had in the original console.

Of note: this doesn't include input field validation, which would probably be a good idea to add at some point.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2155)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2155)* status: all files reviewed, 5 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/angular.json` line 44 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetCzAe1QCauccH270_:-NetCzAe1QCauccH270a:bfpvbq5) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/angular.json#L44)):*
> ```JSON
>                 {
>                   "type": "initial",
>                   "maximumWarning": "2mb",
> ```

Have you checked if it complains with the production build? What I believe you see is mainly related to us using non-minified and non-obfuscated development build, prod build should provide better optimized output. 



_Code quote:_
```JSON
2mb
```
___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 10 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetDRwK2A2C-tfR5aK5:-NetDRwK2A2C-tfR5aK6:b-ru402u) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L10)):*
> ```HTML
>     <mat-progress-bar mode="indeterminate"></mat-progress-bar>
>   </div>
>   <div class="section">
> ```

"section" and other class names are too generic and prone to name collision. I prefer css BEM, which based on my experience provides a little bit more clarity - https://getbem.com/introduction/



_Code quote:_
```HTML
"section">
```
___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 15 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetKQIx8tidnd22BPeJ:-NetKQIy85fqeII82lga:b-2o3hrx) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L15)):*
> ```HTML
>     </div>
>     <div class="section-form">
>       <input
> ```

Weird, these look nothing like angular material inputs, any ideas why? 
One a separate note - there're quite a few of these inputs and they are all stacked. I'd suggest to position them next to each other at least on desktop with larger screens. 
___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 87 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetLGmn8nYY1HIphxjS:-NetLGmn8nYY1HIphxjT:b-fbfgl) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L87)):*
> ```HTML
>       <input
>         matInput
>         type="text"
> ```

type email
___
*[`console-webapp/src/app/settings/whois/whois.component.ts` line 71 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetF6a-8T5AslB58qEV:-NetF6a-8T5AslB58qEW:b-f1f356) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.ts#L71)):*
> ```XML
> 
>   resetDataSource() {
>     this.registrar = this.registrarService.registrar;
> ```

Have you tried whether the reset actually works? Like edit and then cancel and see original value (value before edit made)
I'd expect that it'd not, because it just a reference to an object, which you then update with ngModel, so that should update the original object by the reference.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2155)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/angular.json` line 44 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetCzAe1QCauccH270_:-NetM0AC4Mz7BFho8r-4:b-n24559) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/angular.json#L44)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Have you checked if it complains with the production build? What I believe you see is mainly related to us using non-minified and non-obfuscated development build, prod build should provide better optimized output.
</blockquote></details>

hmm this was causing the QA deployment to fail; what do you suggest? 
___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 10 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetDRwK2A2C-tfR5aK5:-NfCu-n3DFswgRJBdP9l:bbk5b3j) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L10)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

"section" and other class names are too generic and prone to name collision. I prefer css BEM, which based on my experience provides a little bit more clarity - https://getbem.com/introduction/
</blockquote></details>

talked it over offline and I see what you mean 
___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 15 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetKQIx8tidnd22BPeJ:-NetRwlT5NnREUwiMkYO:b-7zpe3t) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L15)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Weird, these look nothing like angular material inputs, any ideas why? 
One a separate note - there're quite a few of these inputs and they are all stacked. I'd suggest to position them next to each other at least on desktop with larger screens.
</blockquote></details>

You mean having like, two columns of fields? That seems significantly more jumbled to me -- AFAIK general UI principles are that you should avoid multiple columns and that a decent chunk of whitespace on the sides of the screen is OK if the content is narrow (examples like Substack and Medium where it's text-heavy, Github settings, etc) 

I don't know why they look different.  I'll do some debugging. 

edit: solved it, need the `<mat-form-field>` 
___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 87 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetLGmn8nYY1HIphxjS:-NetQzW_7rMHjSxeRUbU:bnyl402) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L87)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

type email
</blockquote></details>

Done (also in the other place too) 
___
*[`console-webapp/src/app/settings/whois/whois.component.ts` line 71 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetF6a-8T5AslB58qEV:-NetNqsg6K-Abn5ApFVV:brnm7vz) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.ts#L71)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Have you tried whether the reset actually works? Like edit and then cancel and see original value (value before edit made)
I'd expect that it'd not, because it just a reference to an object, which you then update with ngModel, so that should update the original object by the reference.
</blockquote></details>

Good call. We need to do a deep copy of the registrar first (not a shallow copy). It seems like the best way to do a deep copy of a relatively simple object is to use JSON stringification

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2155)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 15 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetKQIx8tidnd22BPeJ:-NfD3Zvg59NYN9YOTROO:bl0suok) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L15)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

You mean having like, two columns of fields? That seems significantly more jumbled to me -- AFAIK general UI principles are that you should avoid multiple columns and that a decent chunk of whitespace on the sides of the screen is OK if the content is narrow (examples like Substack and Medium where it's text-heavy, Github settings, etc) 

I don't know why they look different.  I'll do some debugging. 

edit: solved it, need the `<mat-form-field>`
</blockquote></details>

Great that you found what was causing the form fields look off.
There's some guidelines re form fields positioning that you might wanna take a look at - https://carbon.googleplex.com/google-material-3/pages/text-fields/guidelines

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2155)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 15 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetKQIx8tidnd22BPeJ:-NfHe-GXE-peCqsnYInC:b-50ta47) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L15)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Great that you found what was causing the form fields look off.
There's some guidelines re form fields positioning that you might wanna take a look at - https://carbon.googleplex.com/google-material-3/pages/text-fields/guidelines
</blockquote></details>

What's your point re: that link?

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2155)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 15 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetKQIx8tidnd22BPeJ:-NfHr3BJ2DsY2_fvz7yf:b-87uq5h) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L15)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

What's your point re: that link?
</blockquote></details>

My point is that as it says we should avoid stacking up large text fields. We should also avoid having too much empty space. My initial thought was maybe making them in a columns layout, especially related fields, like address, etc, which I think would make it better (not ideal) with a minimal efforts. However if you really feel like making an improvement to it, it's usually considered a good practice to make it a modal with editable fields on desktop or a slide out on mobile, it's considerably more code, but see contacts edit page for example.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2155)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 15 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetKQIx8tidnd22BPeJ:-NfI84xe42IhOeSxZzcu:b-msfokf) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L15)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

My point is that as it says we should avoid stacking up large text fields. We should also avoid having too much empty space. My initial thought was maybe making them in a columns layout, especially related fields, like address, etc, which I think would make it better (not ideal) with a minimal efforts. However if you really feel like making an improvement to it, it's usually considered a good practice to make it a modal with editable fields on desktop or a slide out on mobile, it's considerably more code, but see contacts edit page for example.
</blockquote></details>

Which part are you referring to? These text fields here shouldn't be very large, and the linked page has tons of examples of many single-line text inputs one after another. 

The only multi-column segments appear when there are fields that are inextricably linked (e.g. area code + phone number, or start time + end time for an event), or when the fields appear in a small modal where space is essential. 

Because these are all simple individual fields, and not groups of widgets, I don't think it makes sense to group them into columns

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2155)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/whois/whois.component.html` line 15 at r1](https://reviewable.io/reviews/google/nomulus/2155#-NetKQIx8tidnd22BPeJ:-NfRuUlz7l9rrIdepw3-:bkovpwc) ([raw file](https://github.com/google/nomulus/blob/abf37dd076af8e2b6034bb4086b47d77be755349/console-webapp/src/app/settings/whois/whois.component.html#L15)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Which part are you referring to? These text fields here shouldn't be very large, and the linked page has tons of examples of many single-line text inputs one after another. 

The only multi-column segments appear when there are fields that are inextricably linked (e.g. area code + phone number, or start time + end time for an event), or when the fields appear in a small modal where space is essential. 

Because these are all simple individual fields, and not groups of widgets, I don't think it makes sense to group them into columns
</blockquote></details>

synced up offline, we're grouping the address bits into two columns and widening the rest (this is done in the PR now)

**Review by ptkach — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2155)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Pull request merged**
