### PR TITLE
Add SQL functionality to DeleteLoadTestDataAction

### PR DESCRIPTION
**Pull request by gbrodman**
This isn't directly meant to be run in production so some of the rough
edges (doesn't delete domains, can't delete contacts that are referenced
by an existing domain) are fine. We can handle those in
DeleteProberTestAction when we do the more comprehensive deletions.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1211)

### CODE REVIEW

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1211)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java, line 157 at r1](https://reviewable.io/reviews/google/nomulus/1211#-Mcqg9DqArGnQjAzJhJv:-Mcqg9DqArGnQjAzJhJw:bhukb1q) ([raw file](https://github.com/google/nomulus/blob/504a75174724e682f002788ea90bf2695e3b9c0f/core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java#L157)):*
> ```
> Integer.MAX_VALUE
> ```
This can be `null`, which does not set the query limit.
___
*[core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java, line 160 at r1](https://reviewable.io/reviews/google/nomulus/1211#-McqgKgn1P92PvE9oYrQ:-McqgKgn1P92PvE9oYrR:bmkkd8f) ([raw file](https://github.com/google/nomulus/blob/504a75174724e682f002788ea90bf2695e3b9c0f/core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java#L160)):*
> ```
> ImmutableSet.of()
> ```
Why setting it to empty? Shouldn't we just delete the host in question?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1211)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java, line 157 at r1](https://reviewable.io/reviews/google/nomulus/1211#-Mcqg9DqArGnQjAzJhJv:-Mct3HB0BmKB0OSAb37I:b-896fix) ([raw file](https://github.com/google/nomulus/blob/504a75174724e682f002788ea90bf2695e3b9c0f/core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java#L157)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> Integer.MAX_VALUE
> ```
This can be `null`, which does not set the query limit.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java, line 160 at r1](https://reviewable.io/reviews/google/nomulus/1211#-McqgKgn1P92PvE9oYrQ:-Mct3Koi8_xAhvXqECl8:b-kxwq9e) ([raw file](https://github.com/google/nomulus/blob/504a75174724e682f002788ea90bf2695e3b9c0f/core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java#L160)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

> ```
> ImmutableSet.of()
> ```
Why setting it to empty? Shouldn't we just delete the host in question?
</blockquote></details>

Yes but if we delete it without removing it from the domain first, it'll throw a foreign key exception

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1211)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java, line 160 at r1](https://reviewable.io/reviews/google/nomulus/1211#-McqgKgn1P92PvE9oYrQ:-MctEAJtDlqWp47C_AaX:bkvpkbo) ([raw file](https://github.com/google/nomulus/blob/504a75174724e682f002788ea90bf2695e3b9c0f/core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java#L160)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Yes but if we delete it without removing it from the domain first, it'll throw a foreign key exception 
</blockquote></details>

I meant we should just delete the host from the list of nameservers, instead of setting the list to empty, right?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1211)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java, line 160 at r1](https://reviewable.io/reviews/google/nomulus/1211#-McqgKgn1P92PvE9oYrQ:-MctN02vEgizWbpcImq2:bwenlh9) ([raw file](https://github.com/google/nomulus/blob/504a75174724e682f002788ea90bf2695e3b9c0f/core/src/main/java/google/registry/batch/DeleteLoadTestDataAction.java#L160)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I meant we should just delete the host from the list of nameservers, instead of setting the list to empty, right?
</blockquote></details>

Ah, done. Yeah it's more complex (and it shouldn't really matter) but still

**Review by jianglai — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
