### PR TITLE
Add a reg-lock verification action to the new console

### PR DESCRIPTION
**Pull request by gbrodman**
The front end will have a (hidden) page that passes the verification
code to this API endpoint and displays the result.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2467)

### CODE REVIEW

**Comment by gbrodman** [comment]
friendly ping

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2467)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2467#-O-belgQCNZBwtiu_WJj:-O-belgQCNZBwtiu_WJk:bfg8ssj) ([raw file](https://github.com/google/nomulus/blob/5494bf668d1147601af94aa6ce1428f8ebf46a28/core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java#L55)):*
> ```Java
>     domainLockUtils.verifyVerificationCode(lockVerificationCode, user.getUserRoles().isAdmin());
>     // TODO: send to a custom console landing page, but for now just redirect back to the console
>     String url = String.format("%s/%s", consoleApiParams.request().getServerName(), "console");
> ```

First of all servername is not needed as console ui is hosted on the same server, so relative url is more preferable.
Apart from that I suggest not to use an url to direct console, but better keep simple JSON contract and allow front-end to do the thing and navigate where it needs upon receiving the response, this way API doesn't need to know about paths on front-end

**Review by ptkach — COMMENTED** [review]
sorry I totally forgot to click publish on my comment

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2467#-:-O-bgVb5BP74JgU9tk95:b63zn65)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2467)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2467#-O-belgQCNZBwtiu_WJj:-O-qxjO34RA46nucIImD:bf43ksa) ([raw file](https://github.com/google/nomulus/blob/5494bf668d1147601af94aa6ce1428f8ebf46a28/core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java#L55)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

First of all servername is not needed as console ui is hosted on the same server, so relative url is more preferable.
Apart from that I suggest not to use an url to direct console, but better keep simple JSON contract and allow front-end to do the thing and navigate where it needs upon receiving the response, this way API doesn't need to know about paths on front-end
</blockquote></details>

This action is not called via a JSON request; is not an API. This action is triggered by the user clicking a link in an email, meaning that they're just opening up a fresh link in a new tab.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2467)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2467#-O-belgQCNZBwtiu_WJj:-O0Ph8Xr0uSAQFuZ9sZB:b-fjrvmg) ([raw file](https://github.com/google/nomulus/blob/5494bf668d1147601af94aa6ce1428f8ebf46a28/core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java#L55)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

This action is not called via a JSON request; is not an API. This action is triggered by the user clicking a link in an email, meaning that they're just opening up a fresh link in a new tab.
</blockquote></details>

Ehhhh, I think I get what you were saying and I think this new way (what I'm pretty sure you were suggesting) is better. The front end will have a page that the email will link to, and that page will call this JSON API.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2467)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2467#-O-belgQCNZBwtiu_WJj:-O0QJFK39ylCsx4WtWge:b4tqm1v) ([raw file](https://github.com/google/nomulus/blob/5494bf668d1147601af94aa6ce1428f8ebf46a28/core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java#L55)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Ehhhh, I think I get what you were saying and I think this new way (what I'm pretty sure you were suggesting) is better. The front end will have a page that the email will link to, and that page will call this JSON API.
</blockquote></details>

to be more clear, I think what I have now implemented is what you were suggesting.

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2467)* status: all files reviewed, 1 unresolved discussion (waiting on @gbrodman and @jianglai)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockAction.java` line 159 at r2](https://reviewable.io/reviews/google/nomulus/2467#-O1IjZ7L8LgkStZykocG:-O1IjZ7L8LgkStZykocH:b-pe24c0) ([raw file](https://github.com/google/nomulus/blob/a07fe3f5ea2857ca0112b74827d60e9ac3c29393/core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockAction.java#L159)):*
> ```Java
>               .setScheme("https")
>               .setHost(consoleApiParams.request().getServerName())
>               .setPath("/console/registry-lock-verify")
> ```

We use hash routing system in console ui, so most routes look like /console/#/{route_name} 
___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2467#-O-belgQCNZBwtiu_WJj:-O1Ijn6bDjrsrbFcaEBg:bmgm47e) ([raw file](https://github.com/google/nomulus/blob/5494bf668d1147601af94aa6ce1428f8ebf46a28/core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockVerifyAction.java#L55)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

to be more clear, I think what I have now implemented is what you were suggesting.
</blockquote></details>

That's exactly what I meant, sorry if I didn't make it clear. I believe this is better than sending a redirect

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2467)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockAction.java` line 159 at r2](https://reviewable.io/reviews/google/nomulus/2467#-O1IjZ7L8LgkStZykocG:-O1In4Va97eITeGJPwsc:b-896fix) ([raw file](https://github.com/google/nomulus/blob/a07fe3f5ea2857ca0112b74827d60e9ac3c29393/core/src/main/java/google/registry/ui/server/console/ConsoleRegistryLockAction.java#L159)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

We use hash routing system in console ui, so most routes look like /console/#/{route_name}
</blockquote></details>

Done.

**Review by ptkach — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2467)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

**Pull request merged**
