### PR TITLE
Remove Ofy

### PR DESCRIPTION
**Pull request by jianglai**
So long, farewell, adios, ciao, sayonara, 再见!

TESTED=deployed to alpha and used `nomulus list_tlds` to confirm that the web app can receive and serve requests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1863)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 54 of 54 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1863)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by jianglai — COMMENTED** [review]
Gentle ping.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1863#-:-NIJtLKG-rKvKp_3RL3S:bq2fntq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Review by gbrodman — CHANGES_REQUESTED** [review]
yeah sorry for some reason I thought this was still failing checks

> Reviewed 54 of 54 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1863#-:-NIJuQ1W3GNFtJ1hL27n:b-r95720)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/model/IdService.java` line 101 at r2](https://reviewable.io/reviews/google/nomulus/1863#-NIJvGU75SSyn2fCVuSm:-NIJvGU75SSyn2fCVuSn:b-aseeco) ([raw file](https://github.com/google/nomulus/blob/a72c484e3eafd53b42a6fb5b138db5bd5304ac76/core/src/main/java/google/registry/model/IdService.java#L101)):*
> ```Java
>   private IdService() {}
> 
>   public static long allocateId() {
> ```

Just double-checking, removing Objectify does not affect our ability to get IDs from Datastore if we need them, right? As in, Objectify only handles the translation layer between Datastore and our object representations, right? 
___
*[`core/src/main/javascript/soyutils_usegoog.js` line 1011 at r2](https://reviewable.io/reviews/google/nomulus/1863#-NIJvqHb6_Rkr9zeFEY2:-NIJvqHb6_Rkr9zeFEY3:b-x1yl83) ([raw file](https://github.com/google/nomulus/blob/63d34538485ccd03b7d6b1617030dfb45274b0d7/core/src/main/javascript/soyutils_usegoog.js#L1011)):*
> ```JavaScript
> soy.BLOCK_TAGS_RE_ =
>     /^\/?(address|blockquote|dd|div|dl|dt|h[1-6]|hr|li|ol|p|pre|table|tr|ul)$/i;
> // LINT.ThenChange(
> ```

haha what
___
*[`core/src/test/java/google/registry/server/ServletWrapperDelegatorServlet.java` line 37 at r2](https://reviewable.io/reviews/google/nomulus/1863#-NIJwgzLE-c6TryXptl-:-NIJwgzLE-c6TryXptl0:b-jx2vz8) ([raw file](https://github.com/google/nomulus/blob/a72c484e3eafd53b42a6fb5b138db5bd5304ac76/core/src/test/java/google/registry/server/ServletWrapperDelegatorServlet.java#L37)):*
> ```Java
>  *
>  * <p>The actual invocation of the delegate does not happen within this servlet's lifecycle.
>  * Therefore, the task on the queue must manually invoke filters within the queue task.
> ```

nit: likely want to remove this line of javadoc

**Review by jianglai — COMMENTED** [review]
No worries. All these kokoro changes did mess things up.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1863#-:-NIJxBls1nqNljU0Xr9H:ba56tsq)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/model/IdService.java` line 101 at r2](https://reviewable.io/reviews/google/nomulus/1863#-NIJvGU75SSyn2fCVuSm:-NIJxJeA2mYwhtUnFPXr:bispo94) ([raw file](https://github.com/google/nomulus/blob/a72c484e3eafd53b42a6fb5b138db5bd5304ac76/core/src/main/java/google/registry/model/IdService.java#L101)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Just double-checking, removing Objectify does not affect our ability to get IDs from Datastore if we need them, right? As in, Objectify only handles the translation layer between Datastore and our object representations, right? 
</blockquote></details>

That's my understanding as well. Ofy is only the ORM layer, so to speak. The key allocation is done by calling the datastore API directly.
___
*[`core/src/main/javascript/soyutils_usegoog.js` line 1011 at r2](https://reviewable.io/reviews/google/nomulus/1863#-NIJvqHb6_Rkr9zeFEY2:-NIJxgN76NbNLp2-pUq6:b8xm5yh) ([raw file](https://github.com/google/nomulus/blob/63d34538485ccd03b7d6b1617030dfb45274b0d7/core/src/main/javascript/soyutils_usegoog.js#L1011)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

haha what
</blockquote></details>

I have no idea what it does (nor do I wish to learn...), but refers to code locations long gone, so whatever...

Also, the linter directives are only meaning inside google3 I believe, so they are doing absolutely nothing here.
___
*[`core/src/test/java/google/registry/server/ServletWrapperDelegatorServlet.java` line 37 at r2](https://reviewable.io/reviews/google/nomulus/1863#-NIJwgzLE-c6TryXptl-:-NIJydD_C2bLwl6nXuHM:b-oz8tym) ([raw file](https://github.com/google/nomulus/blob/a72c484e3eafd53b42a6fb5b138db5bd5304ac76/core/src/test/java/google/registry/server/ServletWrapperDelegatorServlet.java#L37)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit: likely want to remove this line of javadoc
</blockquote></details>

Good call.

**Review by gbrodman — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1863)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
