### PR TITLE
Add columns needed to implement pull queue alternative

### PR DESCRIPTION
**Pull request by jianglai**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1914)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1914)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`db/src/main/resources/sql/flyway/V133__add_pull_queue_replace_columns.sql` line 23 at r1](https://reviewable.io/reviews/google/nomulus/1914#-NMBCbXyDNrIpyW5SWfZ:-NMBCbXzBPB_boMhfvU9:bmo8g4z) ([raw file](https://github.com/google/nomulus/blob/afbbca4992aa45f3caf470065aaf76032bdf35b1/db/src/main/resources/sql/flyway/V133__add_pull_queue_replace_columns.sql#L23)):*
> ```TSQL
> ALTER TABLE "Host"
>     ADD COLUMN IF NOT EXISTS dns_refresh_request_time timestamptz;
> CREATE INDEX IDXnjhib7v6fj7dhj5qydkefkl2u ON "Domain" (lordn_phase);
> ```

You should be able to add "where lordn_phase is not 'NONE'" at the end.

Similar for Host: dns_refresh_request_time is not null



_Code quote:_
```TSQL
CREATE INDEX IDXnjhib7v6fj7dhj5qydkefkl2u ON "Domain" (lordn_phase);
```

**Review by jianglai — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1914)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`db/src/main/resources/sql/flyway/V133__add_pull_queue_replace_columns.sql` line 23 at r1](https://reviewable.io/reviews/google/nomulus/1914#-NMBCbXyDNrIpyW5SWfZ:-NMCNG476MyOrmtApgpP:bn9nnmp) ([raw file](https://github.com/google/nomulus/blob/afbbca4992aa45f3caf470065aaf76032bdf35b1/db/src/main/resources/sql/flyway/V133__add_pull_queue_replace_columns.sql#L23)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

You should be able to add "where lordn_phase is not 'NONE'" at the end.

Similar for Host: dns_refresh_request_time is not null
</blockquote></details>

Done. I don't see this done in any other flyway files though. I guess these two columns are there for specific use cases where we know exactly how we are going apply filters on the select statement.

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1914)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`db/src/main/resources/sql/flyway/V133__add_pull_queue_replace_columns.sql` line 16 at r2](https://reviewable.io/reviews/google/nomulus/1914#-NMF9TH41y1wSCQZynwO:-NMF9TH41y1wSCQZynwP:b-iukyhh) ([raw file](https://github.com/google/nomulus/blob/1a19fb140f00cf2667ef9c9502bf178b7a372ecc/db/src/main/resources/sql/flyway/V133__add_pull_queue_replace_columns.sql#L16)):*
> ```TSQL
> 
> ALTER TABLE "Domain"
>     ADD COLUMN IF NOT EXISTS lordn_phase text DEFAULT 'NONE';
> ```

Add NOT NULL to prevent accidental insertion of null by code?



_Code quote:_
```TSQL
lordn_phase text DEFAULT 'NONE
```

**Review by jianglai — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1914)* status: all files reviewed, 1 unresolved discussion (waiting on @weiminyu)

___
*[`db/src/main/resources/sql/flyway/V133__add_pull_queue_replace_columns.sql` line 16 at r2](https://reviewable.io/reviews/google/nomulus/1914#-NMF9TH41y1wSCQZynwO:-NMFR35r6QorfpCTAU6-:bopml5h) ([raw file](https://github.com/google/nomulus/blob/1a19fb140f00cf2667ef9c9502bf178b7a372ecc/db/src/main/resources/sql/flyway/V133__add_pull_queue_replace_columns.sql#L16)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Add NOT NULL to prevent accidental insertion of null by code?
</blockquote></details>

The java code already has a default, but I guess you can go out of your way to call the builder and set the value to be null. Done.

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1914)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request merged**
