### PR TITLE
Remove the use of GCS APIs provided from GAE SDK

### PR DESCRIPTION
**Pull request by jianglai**
The API provided by the GAE SDK will not be available outside GAE
runtime. This presents a problem when we migrate off of GAE. More
pressingly, the RDE pipeline migration to Beam requires that we write to
GCS on GCE. Previously we were able to sidestep the issue by delegating
the writes to FileIO provided by Beam, which knows how to write to GCS.
However the RDE pipeline cannot use FileIO directly as it needs to write
to multiple files in one go and explicit use of GCS API is needed.

An unfortunate side effect of the API migration is that the new testing
library contains a bug which makes serializing GcsUtils impossible. It
is fixed upstream but not released yet. The fix has been backported for
the time being.

This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1228)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
As a kind of general comment, well-written descriptive PR commit messages are of course great, and help reviewers a lot, but that same level of detail should also be present in the source itself, as the Javadoc is more likely to be referred to on an ongoing basis by other programmers (since it's right there in the source code file you already have open), vs having to dig through Blame history on a given file to excavate an old commit message.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1228#-:-MdbtRlF6Rc4Cu-x3oEP:b-i0tm2s)* status: 0 of 185 files reviewed, 4 unresolved discussions (waiting on @jianglai and @weiminyu)

___
*[core/src/main/java/google/registry/gcs/GcsUtils.java, line 44 at r4](https://reviewable.io/reviews/google/nomulus/1228#-Mdbsz489UlkphI-vtry:-Mdbsz489UlkphI-vtrz:b-9xj1du) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/GcsUtils.java#L44)):*
> ```Java
> import javax.inject.Inject;
> 
> /** Utilities for working with Google Cloud Storage. */
> ```

Elaborate in the Javadoc why this needs to be `Serializable`.
___
*[core/src/main/java/google/registry/gcs/GcsUtils.java, line 135 at r4](https://reviewable.io/reviews/google/nomulus/1228#-Mdbs3Q0A-b9iw6ctjvX:-Mdbs3Q0A-b9iw6ctjvY:b-w2xg59) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/GcsUtils.java#L135)):*
> ```Java
>   /** Returns {@code true} if a file exists and is non-empty on Google Cloud Storage. */
>   public boolean existsAndNotEmpty(BlobId blobId) {
>     Blob blob;
> ```

This whole function can be rewritten more simply as:

```
try {
  Blob blob = storage().get(blobId);
  return blob != null && blob.getSize() > 0;
} catch (StorageException e) {
  // ...
}
```
___
*[core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java, line 42 at r4](https://reviewable.io/reviews/google/nomulus/1228#-MdbsMaf2jfYVTIfv5PO:-MdbsMaf2jfYVTIfv5PP:b3sobcx) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java#L42)):*
> ```Java
> import javax.annotation.concurrent.NotThreadSafe;
> 
> /**
> ```

This file needs comments on where it comes from, what version this is, why it's here, when in the future it might not be here, etc. -- all the details you included in the PR description.
___
*[core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java, line 43 at r4](https://reviewable.io/reviews/google/nomulus/1228#-Mdbrb8m9X3cw1piZ-xg:-Mdbrb8m9X3cw1piZ-xh:bdh6r6h) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java#L43)):*
> ```Java
> 
> /**
>  * A bare-bones in-memory implementation of StorageRpc, meant for testing.
> ```

If this is meant for testing then it's not in the right package.  Should be in the `testing` package.

**Review by jianglai — COMMENTED** [review]
> Reviewed 164 of 181 files at r1, 57 of 73 files at r2, 17 of 20 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1228)* status: 184 of 186 files reviewed, 4 unresolved discussions (waiting on @CydeWeys, @jianglai, and @weiminyu)

___
*[core/src/main/java/google/registry/gcs/GcsUtils.java, line 44 at r4](https://reviewable.io/reviews/google/nomulus/1228#-Mdbsz489UlkphI-vtry:-Mdc7BBG-2ZVCkK3NrX7:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/GcsUtils.java#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Elaborate in the Javadoc why this needs to be `Serializable`.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/gcs/GcsUtils.java, line 135 at r4](https://reviewable.io/reviews/google/nomulus/1228#-Mdbs3Q0A-b9iw6ctjvX:-Mdc7OT52vwi-TVgfImf:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/GcsUtils.java#L135)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This whole function can be rewritten more simply as:

```
try {
  Blob blob = storage().get(blobId);
  return blob != null && blob.getSize() > 0;
} catch (StorageException e) {
  // ...
}
```
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java, line 42 at r4](https://reviewable.io/reviews/google/nomulus/1228#-MdbsMaf2jfYVTIfv5PO:-Mdc9lL38TEhmGpBmuMA:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java#L42)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This file needs comments on where it comes from, what version this is, why it's here, when in the future it might not be here, etc. -- all the details you included in the PR description.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java, line 43 at r4](https://reviewable.io/reviews/google/nomulus/1228#-Mdbrb8m9X3cw1piZ-xg:-Mdc9mN1E8QerQY296pt:b-yq01ti) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java#L43)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

If this is meant for testing then it's not in the right package.  Should be in the `testing` package.
</blockquote></details>

If we put them under `testing` we'd have to include a dependency on `testing` from `core`, which seems counter-intuitive. Hopefully a new release from upstream will happen soon and we can just remove these files.

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1228)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys and @weiminyu)

**Review by weiminyu — COMMENTED** [review]
> Reviewed 106 of 181 files at r1, 57 of 73 files at r2, 17 of 20 files at r3, 4 of 5 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1228)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys)

**Review by weiminyu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1228#-:-Me2cLe-DvUZYvyqJ7-f:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @CydeWeys)

**Review by CydeWeys — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1228)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java, line 42 at r4](https://reviewable.io/reviews/google/nomulus/1228#-MdbsMaf2jfYVTIfv5PO:-Me5lt39Cjh04jY7ciZw:bulygo3) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java#L42)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it?
___
*[core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java, line 43 at r4](https://reviewable.io/reviews/google/nomulus/1228#-Mdbrb8m9X3cw1piZ-xg:-Me5lxxs9G-bWWhdjYUw:bub3mj0) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java#L43)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

If we put them under `testing` we'd have to include a dependency on `testing` from `core`, which seems counter-intuitive. Hopefully a new release from upstream will happen soon and we can just remove these files.
</blockquote></details>

I'm recommending the `testing` _package_ inside the core subproject, not the `testing` _subproject_.  See `google.registry.testing`, https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/testing/

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1228)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java, line 42 at r4](https://reviewable.io/reviews/google/nomulus/1228#-MdbsMaf2jfYVTIfv5PO:-Me6fxgO0VCeK7Igbda7:b-ysj9ci) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java#L42)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Is it?
</blockquote></details>

Sorry, should have been more clear. Added a `README.md` file in the directory.
___
*[core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java, line 43 at r4](https://reviewable.io/reviews/google/nomulus/1228#-Mdbrb8m9X3cw1piZ-xg:-Me6g6Qi1QETRf24gKnY:b-sugt4q) ([raw file](https://github.com/google/nomulus/blob/f5ef5d09452a34558338737fa64dc0ccc753a651/core/src/main/java/google/registry/gcs/backport/FakeStorageRpc.java#L43)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I'm recommending the `testing` _package_ inside the core subproject, not the `testing` _subproject_.  See `google.registry.testing`, https://cs.opensource.google/nomulus/nomulus/+/master:core/src/test/java/google/registry/testing/
</blockquote></details>

That would not work as the `test` configuration  depends on the `main` configuration within the `core` package, not the other way around. Realistically these files would be removed with in a couple of weeks (according to the upstream maintainers), so I don't think we need to be too strict about where to put them temporarily to make the most structural sense.

**Review by jianglai — COMMENTED** [review]
PTAL. Moved the backported files to be under `test`.

> Reviewed 36 of 36 files at r6.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1228#-:-Me7cXvjDAEipvgvL20j:b-an728)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1228)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

**Pull request merged**
