### PR TITLE
Add flyway files for allocateId sequence alternative

### PR DESCRIPTION
**Pull request by ptkach**
This PR implement DB part for allocateId SQL sequence alternative. Java part - https://github.com/google/nomulus/pull/1831

Tested in alpha

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1830)

### CODE REVIEW

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jianglai and @ptkach)

___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 18 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLHWpA0KxLAsD_09PF:-NFLHWpB4jPT72XelCem:b-ko1a1g) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L18)):*
> ```TSQL
>     START WITH 59880480006
>     INCREMENT BY 1
>     MINVALUE 59880480005
> ```

Why different from `start`



_Code quote:_
```TSQL
59880480005
```
___
*[`db/src/main/resources/sql/schema/nomulus.golden.sql` line 1117 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLHtfrEl2TZjwJ7tEL:-NFLHtfrEl2TZjwJ7tEM:b-xpxb91) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/schema/nomulus.golden.sql#L1117)):*
> ```TSQL
> 
> CREATE SEQUENCE public.project_wide_unique_id_seq
>     START WITH 11477200586932224
> ```

This is different from flyway script. Can this pass presubmit tests?



_Code quote:_
```TSQL
11477200586932224
```

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @jianglai and @ptkach)

___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 20 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLK6G82_u6RXPi_q3z:-NFLK6G82_u6RXPi_q4-:bp7q030) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L20)):*
> ```TSQL
>     MINVALUE 59880480005
>     NO MAXVALUE
>     CACHE 1;
> ```

This may have performance issues. I can't think of any use cases where monotonously increasing ordering is required across all thread.

Please check with Ben about this. 



_Code quote:_
```TSQL
1
```

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @jianglai and @weiminyu)

___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 18 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLHWpA0KxLAsD_09PF:-NFPAvh4-w9yFKyJT2l4:b-ldn8c4) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L18)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Why different from `start`
</blockquote></details>

Postgres doc doesn't really shade any light on being less, but I recall from working with Oracle db that there it was strictly enforced and minvalue had to be less than start. Since we're not loosing anything by doing so, I figured it'd be safer to do it this way
___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 20 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLK6G82_u6RXPi_q3z:-NFPBQfA-tavaVQqw5Xs:b5vwe8b) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L20)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This may have performance issues. I can't think of any use cases where monotonously increasing ordering is required across all thread.

Please check with Ben about this. 
</blockquote></details>

I was on the fence about that, but CACHE 1 is used everywhere else across the project this is what I've used. 
___
*[`db/src/main/resources/sql/schema/nomulus.golden.sql` line 1117 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLHtfrEl2TZjwJ7tEL:-NFPBa4cBI-RFd0kt9gp:b-r9ewpx) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/schema/nomulus.golden.sql#L1117)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

This is different from flyway script. Can this pass presubmit tests?
</blockquote></details>

Not sure why it didn't get updated when I changed the value. I regenerated the file now. Thanks for pointing out!

**Review by weiminyu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @jianglai and @ptkach)

___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 20 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLK6G82_u6RXPi_q3z:-NFUPpTa7GOCjrSEyCrL:bmlcnur) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L20)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I was on the fence about that, but CACHE 1 is used everywhere else across the project this is what I've used. 
</blockquote></details>

Like I said earlier, please check with Ben who may have an opinion on this.

Can you do some measurement fetching ids with cache 1 on alpha? 

We should also check our SQL write QPS. Maybe it is too low for id latency to matter, but we should have some data.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @jianglai and @weiminyu)

___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 20 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLK6G82_u6RXPi_q3z:-NFUbMBQAfPf0vAmzqhz:bsqlmbx) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L20)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Like I said earlier, please check with Ben who may have an opinion on this.

Can you do some measurement fetching ids with cache 1 on alpha? 

We should also check our SQL write QPS. Maybe it is too low for id latency to matter, but we should have some data.
</blockquote></details>

Interestingly the default is also `1` if otherwise not specified, which is presumably where all of these values came from (we didn't manually create all of these existing sequences).  And the cache is per-connection, not global.

It does seem like a larger cache value might improve performance somewhat, based on some cursory googling.  Maybe a value of `100` is reasonable?  This sequence is going to be used by lots of things, many of which take place simultaneously (e.g. a domain create is going to need to grab at least 5 ids, for the domain itself, the history entry, and poll messages/autorenews/billing events).  So `1` does seem too low.

We might also consider not using the same sequence for everything.  Like all EPP resources (domains, contacts, and hosts) should use the same sequence, but does that necessarily need to be the same sequence as, say, registry lock entities?  I doubt it.

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)* status: all files reviewed, 4 unresolved discussions (waiting on @ptkach and @weiminyu)

___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 20 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLK6G82_u6RXPi_q3z:-NF_k57G3VvFPRKM5WB9:b-lyshea) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L20)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Interestingly the default is also `1` if otherwise not specified, which is presumably where all of these values came from (we didn't manually create all of these existing sequences).  And the cache is per-connection, not global.

It does seem like a larger cache value might improve performance somewhat, based on some cursory googling.  Maybe a value of `100` is reasonable?  This sequence is going to be used by lots of things, many of which take place simultaneously (e.g. a domain create is going to need to grab at least 5 ids, for the domain itself, the history entry, and poll messages/autorenews/billing events).  So `1` does seem too low.

We might also consider not using the same sequence for everything.  Like all EPP resources (domains, contacts, and hosts) should use the same sequence, but does that necessarily need to be the same sequence as, say, registry lock entities?  I doubt it.
</blockquote></details>

The current datastore allocation scheme use a single global pool for everything. It's probably for historical reasons? Or maybe there was no performance benefit to distinguish between entities.
___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 15 at r2](https://reviewable.io/reviews/google/nomulus/1830#-NF_iGEYCJfzdGEzEGtP:-NF_iGEYCJfzdGEzEGtQ:b-mphsx7) ([raw file](https://github.com/google/nomulus/blob/2211d68278294a99bb87c8d1d0dad4da8fdebfc0/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L15)):*
> ```TSQL
> -- limitations under the License.
> 
> CREATE SEQUENCE public."project_wide_unique_id_seq"
> ```

It should be noted that all of our tables are CamelCase. For consistency, this one should be too.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @jianglai and @weiminyu)

___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 20 at r1](https://reviewable.io/reviews/google/nomulus/1830#-NFLK6G82_u6RXPi_q3z:-NFjLcEG7aDIoacjMnG-:b9iatga) ([raw file](https://github.com/google/nomulus/blob/e378ece409e76d52a72bc7f4aef1ce902add8f5a/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L20)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The current datastore allocation scheme use a single global pool for everything. It's probably for historical reasons? Or maybe there was no performance benefit to distinguish between entities.
</blockquote></details>

Re cache - I've updated ```cache``` to equal ```10``` for now, assuming we have an unexpected large numbers already assigned I'd prefer not rush increasing the numbers. 

Re separate identifiers - this change is inline with current allocateId implementation and I was rushing to completed it rather sooner than later as it's blocking #1810  . Adding separate identifiers will increase complexity, take time to implement (delay #1810  even more) and not necessary bring any benefit. 
___
*[`db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql` line 15 at r2](https://reviewable.io/reviews/google/nomulus/1830#-NF_iGEYCJfzdGEzEGtP:-NFjL_tS9_tZbpk-J05E:bb6un1j) ([raw file](https://github.com/google/nomulus/blob/2211d68278294a99bb87c8d1d0dad4da8fdebfc0/db/src/main/resources/sql/flyway/V129__create_allocateId_sequence_alternative.sql#L15)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It should be noted that all of our tables are CamelCase. For consistency, this one should be too.
</blockquote></details>

Done

**Review by weiminyu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

**Comment by ptkach** [comment]
> > Reviewed 2 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1830)_ status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

@jianglai  Is there anything else pending here or it can be merged?

**Review by jianglai — APPROVED** [review]
I would still like to test if you can use CamelCase for the table name by using double quotes. But other than that it's good to go.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1830#-:-NFsrJQ4E6LbBKLrwLfx:bgan6lc)* status: all files reviewed, 2 unresolved discussions (waiting on @weiminyu)

**Comment by ptkach** [comment]
> I would still like to test if you can use CamelCase for the table name by using double quotes. But other than that it's good to go.
> 
> > _[Reviewable](https://reviewable.io/reviews/google/nomulus/1830#-:-NFsrJQ4E6LbBKLrwLfx:bgan6lc)_ status: all files reviewed, 2 unresolved discussions (waiting on @weiminyu)

@jianglai  Just to avoid confusion - this is **camelCase** and this is **PascalCase** 😄  Regardless of that neither works with nextval even with double quotes and escaping.

**Comment by jianglai** [comment]
camel case can be used to describe both cases, depending on if the first letter is capitalized.

https://en.wikipedia.org/wiki/Camel_case

More relevant is the usage in Google, which I believe universally refers to them as `CamelCase` and `camelCase`, respectively. See [here](https://engdoc.corp.google.com/eng/doc/devguide/java/style/index.md?cl=head#s5.3-camel-case)

So you are not wrong, but I don't want you to get confused when you see `CamelCase` referred to a lot inside Google.

**Pull request merged**
