### PR TITLE
Add replay extension to more domain tests

### PR DESCRIPTION
**Pull request by mindhog**
Add replay to DomainRenewFlowTest and DomainUpdateFlowTest.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/893)

### CODE REVIEW

**Review by hstonec — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/893)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hstonec and @mindhog)

___
*[core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java, line 107 at r1](https://reviewable.io/reviews/google/nomulus/893#-MNdv9jL-C1yrsW7pwqw:-MNdv9jL-C1yrsW7pwqx:b-57o5b2) ([raw file](https://github.com/google/nomulus/blob/4cb8a81f16fa7042d9c2ddea83124c753a0a4e4b/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L107)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   @Order(value = Order.DEFAULT - 3)
>   @RegisterExtension
>   final SetClockExtension setClockExtension = new SetClockExtension();
>   @Order(value = Order.DEFAULT - 2)
> ```
</details>

I have been thinking if there is a way to set the order globally? Or at least make the extension itself be aware that it is executed before/after other extension and that is not acceptable?

**Review by hstonec — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/893)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hstonec and @mindhog)

___
*[core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java, line 162 at r1](https://reviewable.io/reviews/google/nomulus/893#-MNdyKPRCcTkxbyDPQhI:-MNdyKPRCcTkxbyDPQhJ:b37rpx6) ([raw file](https://github.com/google/nomulus/blob/4cb8a81f16fa7042d9c2ddea83124c753a0a4e4b/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L162)):*
> ```
>               } catch (Exception e) {
>                 throw new RuntimeException("Error persisting domain", e);
>               }
> ```
Why do we need to catch the exception here?

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/893)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hstonec and @weiminyu)

___
*[core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java, line 107 at r1](https://reviewable.io/reviews/google/nomulus/893#-MNdv9jL-C1yrsW7pwqw:-MNeB_X_9hTa87L7HuhF:bwjo54y) ([raw file](https://github.com/google/nomulus/blob/4cb8a81f16fa7042d9c2ddea83124c753a0a4e4b/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L107)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
>   @Order(value = Order.DEFAULT - 3)
>   @RegisterExtension
>   final SetClockExtension setClockExtension = new SetClockExtension();
>   @Order(value = Order.DEFAULT - 2)
> ```
I have been thinking if there is a way to set the order globally? Or at least make the extension itself be aware that it is executed before/after other extension and that is not acceptable?
</blockquote></details>

If there is, the docs make no mention of it: https://junit.org/junit5/docs/5.4.1/api/org/junit/jupiter/api/extension/RegisterExtension.html

This is unfortunate, what we would like is to be able to say "this extension must come before these other extensions," essentially imposing a sort of dependency graph.

@weiminyu do you know of a way to do this?
___
*[core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java, line 162 at r1](https://reviewable.io/reviews/google/nomulus/893#-MNdyKPRCcTkxbyDPQhI:-MNeCQSr2vhKfyOTzFvL:bnbkp79) ([raw file](https://github.com/google/nomulus/blob/4cb8a81f16fa7042d9c2ddea83124c753a0a4e4b/core/src/test/java/google/registry/flows/domain/DomainRenewFlowTest.java#L162)):*
<details><summary><i>Previously, hstonec (Shicong Huang) wrote…</i></summary><blockquote>

> ```
>               } catch (Exception e) {
>                 throw new RuntimeException("Error persisting domain", e);
>               }
> ```
Why do we need to catch the exception here?
</blockquote></details>

Presumably because Supplier.get() doesn't define "throws Exception" (and getUniqueIdFromCommand() does -- I get a compile-time error without the try/catch).

Probably not worthwhile to change the lambda interface that transact() accepts.

**Review by hstonec — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/893#-:-MNisiYq6919FkbeAZZr:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @weiminyu)

**Pull request merged**
