### PR TITLE
Fix Gradle dependency version pinning

### PR DESCRIPTION
**Pull request by weiminyu**
In Gradle 7, version labels require '!!' at the end to be free from any forced upgrade.

Hibernate needs to be pinned. Latest version has problem with Joda Money, which needs investigation.

Upgraded most dependencies to the latest version.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1843)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
Btw, this should fix the db:flyway* Gradle tasks.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1843#-:-NG2V2wqBlxDZXsZarX3:b-mdi6po)* status: 0 of 15 files reviewed, all discussions resolved (waiting on @jianglai and @ptkach)

**Review by jianglai — CHANGES_REQUESTED** [review]
It the problem with Joda Money because of this:

https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/persistence/converter/JodaMoneyType.java;l=46?q=money&ss=nomulus%2Fnomulus

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1843#-:-NG3OQeWEj72u2vEhi9g:bkrty7b)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach and @weiminyu)

___
*[`dependencies.gradle` line 115 at r1](https://reviewable.io/reviews/google/nomulus/1843#-NG3Olq_EwOs326APzRI:-NG3Olq_EwOs326APzRJ:b-8z62qa) ([raw file](https://github.com/google/nomulus/blob/cf1816a1fd04270cdd464cfa257dba7faf00a72d/dependencies.gradle#L115)):*
> ```Gradle
>       'com.google.api-client:google-api-client-java6:[1.31.3,2.0)!!',
>       'com.google.api-client:google-api-client:[1.31.3,2.0)!!',
>       'com.google.api-client:google-api-client-appengine:[1.31.3,2.0)',
> ```

What does it mean to not have a `!!` at the end, then? Is the upper bound meaningless then, or merely a suggestions that can be broken by transitive dependencies? 



_Code quote:_
```Gradle
'com.google.api-client:google-api-client-appengine:[1.31.3,2.0)',
```

**Review by weiminyu — COMMENTED** [review]
There is just one message : Money is immutable. And it starts in 5.6.12.Final, not 6.x

Need to investigate but it's not urgent.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1843#-:-NG3Qo0c4aswyaCVLboc:b-72ie7f)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

___
*[`dependencies.gradle` line 115 at r1](https://reviewable.io/reviews/google/nomulus/1843#-NG3Olq_EwOs326APzRI:-NG3RICL2ngY01-0OGFa:b-p36ooe) ([raw file](https://github.com/google/nomulus/blob/cf1816a1fd04270cdd464cfa257dba7faf00a72d/dependencies.gradle#L115)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

What does it mean to not have a `!!` at the end, then? Is the upper bound meaningless then, or merely a suggestions that can be broken by transitive dependencies? 
</blockquote></details>

Without !!, there are two cases:
* 'com.google.api-client:google-api-client-appengine:[1.31.3,2.0)': 'required' version: at least in this range, and Gradle may decide on its own to upgrade.
* 'jline:jline:1.0': according to their doc also means 'required' but in practice means 'prefer': choose 1.0, unless forced higher by upstream dependencies. 

Their doc is at https://docs.gradle.org/current/userguide/rich_versions.html#sec:required-version

We may have to add a lot more '!!'s when we upgrade. But there are breaking changes going forward to 7.5.1, and we may have to
do whatever works for the version we are on

**Review by weiminyu — COMMENTED** [review]
It is our error message. Hibernate attempts to set JodaMoneyType's property.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1843#-:-NG3Zm0j79XOTSBVLHj_:bd3b3tr)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1843)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

___
*[`dependencies.gradle` line 115 at r1](https://reviewable.io/reviews/google/nomulus/1843#-NG3Olq_EwOs326APzRI:-NG3a60h5XoVl1Rykg_u:b1ro5fn) ([raw file](https://github.com/google/nomulus/blob/cf1816a1fd04270cdd464cfa257dba7faf00a72d/dependencies.gradle#L115)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Without !!, there are two cases:
* 'com.google.api-client:google-api-client-appengine:[1.31.3,2.0)': 'required' version: at least in this range, and Gradle may decide on its own to upgrade.
* 'jline:jline:1.0': according to their doc also means 'required' but in practice means 'prefer': choose 1.0, unless forced higher by upstream dependencies. 

Their doc is at https://docs.gradle.org/current/userguide/rich_versions.html#sec:required-version

We may have to add a lot more '!!'s when we upgrade. But there are breaking changes going forward to 7.5.1, and we may have to
do whatever works for the version we are on



</blockquote></details>

If you read the dependency related error message in current Gradle 7.0, 'jline:jline:1.0' means 'strictly'.
And we know `com.google.api-client:google-api-client-appengine:[1.31.3,2.0)` is not 'strictly'.

That's all we know. 
I don't trust their online doc, for now.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1843)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

___
*[`dependencies.gradle` line 115 at r1](https://reviewable.io/reviews/google/nomulus/1843#-NG3Olq_EwOs326APzRI:-NG3abel6jUUMonnQlff:bli06ws) ([raw file](https://github.com/google/nomulus/blob/cf1816a1fd04270cdd464cfa257dba7faf00a72d/dependencies.gradle#L115)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

If you read the dependency related error message in current Gradle 7.0, 'jline:jline:1.0' means 'strictly'.
And we know `com.google.api-client:google-api-client-appengine:[1.31.3,2.0)` is not 'strictly'.

That's all we know. 
I don't trust their online doc, for now.
</blockquote></details>

We should probably adopt their recommendation to declare version-less dependencies with a constraints section using rich semantics.

That will take some time to implement.

**Review by weiminyu — COMMENTED** [review]
Actually 5.6.12.Final is buggy. A fix is uploaded to maven central today. Redoing update_dependency.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1843#-:-NG3htGq9dVKOpgEMKAu:b-w0kkzx)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

**Review by weiminyu — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1843#-:-NG3vGERDN4PDppXS9tT:bb6un1j)* status: 1 of 15 files reviewed, 1 unresolved discussion (waiting on @jianglai and @ptkach)

**Review by jianglai — APPROVED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1843)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach and @weiminyu)

___
*[`dependencies.gradle` line 115 at r1](https://reviewable.io/reviews/google/nomulus/1843#-NG3Olq_EwOs326APzRI:-NGK6KFr1Xmw-KAsm1oA:b8o0iiu) ([raw file](https://github.com/google/nomulus/blob/cf1816a1fd04270cdd464cfa257dba7faf00a72d/dependencies.gradle#L115)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

We should probably adopt their recommendation to declare version-less dependencies with a constraints section using rich semantics.

That will take some time to implement.
</blockquote></details>

I think you should have cited [this link](https://docs.gradle.org/current/userguide/single_versions.html) which actually explains the notation. Maybe worthwhile adding it to the file itself.

**Pull request merged**
