### PR TITLE
Pass stack trace to validate_datastore user

### PR DESCRIPTION
**Pull request by weiminyu**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1537)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1537)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mindhog and @weiminyu)

___
*[core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java, line 120 at r1](https://reviewable.io/reviews/google/nomulus/1537#-MxGHYv0AlqVvH0PIHEU:-MxGHYv0AlqVvH0PIHEV:b-ipznmh) ([raw file](https://github.com/google/nomulus/blob/3df41303cf5cc32c354a57a645809289a7b4ec1f/core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java#L120)):*
> ```Java
>       return;
>     } catch (Throwable e) {
>       response.setStatus(SC_INTERNAL_SERVER_ERROR);
> ```

Can we add a `logger.atSevere().withCause(e).log(.....);` call here?

Instinctively I went into the App Engine logs to try and debug this and there was nothing in there.  So we should have log output in there too.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1537)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @mindhog)

___
*[core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java, line 120 at r1](https://reviewable.io/reviews/google/nomulus/1537#-MxGHYv0AlqVvH0PIHEU:-MxGIfRp2Jb2j0-Ayokx:b-896fix) ([raw file](https://github.com/google/nomulus/blob/3df41303cf5cc32c354a57a645809289a7b4ec1f/core/src/main/java/google/registry/backup/SyncDatastoreToSqlSnapshotAction.java#L120)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Can we add a `logger.atSevere().withCause(e).log(.....);` call here?

Instinctively I went into the App Engine logs to try and debug this and there was nothing in there.  So we should have log output in there too.
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1537#-:-MxGJFLq249tbEM41ZtV:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @mindhog)

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1537)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @weiminyu)

**Pull request merged**
