### PR TITLE
Add TaskInfo and use it to store shared task info

### PR DESCRIPTION
**Pull request by rachelguan**
Add a structure to store task info that is shared among multiple action files.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1445)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
I'm not sure if this is ready for review yet as it still as the WIP label.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1445#-:-Mqpr4R648XnDXPyItvl:bpecl9)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
I don't quite understand the need for a separate `TaskInfo` class here. It seems like all you are doing is to create a `TaskInfo` in one method and  then decompose the created `TaskInfo` to feed to `CloudTasksUtils.enqueue()`. Why can't you just create a `Task` by calling one of the helper method on `CloudTasksUtils` and then feed it to `CloudTasksUtils.enqueue(queue, task)`?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1445#-:-Mr5LBpm8JHzni7sUp9M:bxmhdqj)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @jianglai)

**Review by rachelguan — COMMENTED** [review]
The reason i did that was that, some of the information used by another class does not belong to that class. It's just a way I thought to encapsulate and avoid writing the same information twice. It is possible to achieve the same result by declaring all the information public (queue name, path, service, params and jitterSeconds) ..

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1445#-:-Mr5T1ObC_-i2JXs3GFL:b-gszwgz)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
It looks to me that you only need to know the queue name and the task in order to enqueue a task, is it not? So your first method can create that task and the second method will take the task and get the queue via injection. You currently get the queue via injection in the first method, but that can easily be moved. Did I miss anything else?

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1445#-:-MrK_DJl1lV9LCl11fYJ:b-prdsgs)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @jianglai)

**Review by rachelguan — COMMENTED** [review]
I gave it some thought and I think it is indeed not necessary to include another structure for this. Closing this PR. 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1445#-:-Msb4r6v7Do7TgA0TYpk:be00jim)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @jianglai)

**Pull request closed without merging**
