### PR TITLE
Convert DeleteExpiredDomainsAction to QueryComposer

### PR DESCRIPTION
**Pull request by gbrodman**
I think this one needed to wait until the detach-on-load PR went in, but
now we should be all set.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1180)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1180)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 141 at r1](https://reviewable.io/reviews/google/nomulus/1180#-MadYm5L6pwBe24z-vnP:-MadYm5MBDlw2pY0bZ8-:biklffq) ([raw file](https://github.com/google/nomulus/blob/81411624ba9d75bc0e30cd9b4cc80fca5789145c/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L141)):*
> ```Java
>                     .where("autorenewEndTime", Comparator.LTE, runTime)
>                     .stream()
>                     // Datastore can't do two inequalities in one query so do the second in-memory
> ```

Cloud SQL *can* do two inequalities in one query though, so it should.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1180)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 141 at r1](https://reviewable.io/reviews/google/nomulus/1180#-MadYm5L6pwBe24z-vnP:-MadYstT-mhL3g7dBsqI:bj8up3q) ([raw file](https://github.com/google/nomulus/blob/81411624ba9d75bc0e30cd9b4cc80fca5789145c/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L141)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Cloud SQL *can* do two inequalities in one query though, so it should.
</blockquote></details>

(So, time for an if/else branch depending on DB mode.)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1180)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 141 at r1](https://reviewable.io/reviews/google/nomulus/1180#-MadYm5L6pwBe24z-vnP:-MadjWm425XrZREUvxPg:b-zbhg2t) ([raw file](https://github.com/google/nomulus/blob/81411624ba9d75bc0e30cd9b4cc80fca5789145c/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L141)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

(So, time for an if/else branch depending on DB mode.)
</blockquote></details>

Actually if I'm reading https://cloud.google.com/appengine/docs/standard/go111/datastore/query-restrictions#inequality_filters_are_limited_to_at_most_one_property right, we should be able to do this in a Datastore query as well. In that case, the previously-existing comment was incorrect.

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1180)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 141 at r1](https://reviewable.io/reviews/google/nomulus/1180#-MadYm5L6pwBe24z-vnP:-MaiI0MRC_fafXRfORVH:b-rsj35h) ([raw file](https://github.com/google/nomulus/blob/81411624ba9d75bc0e30cd9b4cc80fca5789145c/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L141)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Actually if I'm reading https://cloud.google.com/appengine/docs/standard/go111/datastore/query-restrictions#inequality_filters_are_limited_to_at_most_one_property right, we should be able to do this in a Datastore query as well. In that case, the previously-existing comment was incorrect. 
</blockquote></details>

Yes, AFAIK inequality + equality queries are fine.

Also, in general, I'm personally more inclined to accept a small (and temporary) performance hit on the SQL side over branching the code.  For purposes of the migration, my feeling is we're better off having as small a footprint of differing code as possible.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1180)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 141 at r1](https://reviewable.io/reviews/google/nomulus/1180#-MadYm5L6pwBe24z-vnP:-MaiK_zi-tzn_as0KjE1:bbhyxii) ([raw file](https://github.com/google/nomulus/blob/81411624ba9d75bc0e30cd9b4cc80fca5789145c/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L141)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Yes, AFAIK inequality + equality queries are fine.

Also, in general, I'm personally more inclined to accept a small (and temporary) performance hit on the SQL side over branching the code.  For purposes of the migration, my feeling is we're better off having as small a footprint of differing code as possible. 
</blockquote></details>

ugh i made the change but apparently I forgot (???) to push it yesterday, just pushed

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1180)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 141 at r1](https://reviewable.io/reviews/google/nomulus/1180#-MadYm5L6pwBe24z-vnP:-MaiKjnD7mkGhH7m9ROG:b8a19ot) ([raw file](https://github.com/google/nomulus/blob/81411624ba9d75bc0e30cd9b4cc80fca5789145c/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L141)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

ugh i made the change but apparently I forgot (???) to push it yesterday, just pushed 
</blockquote></details>

May as well fix it to work with Datastore then (and remove the now-inaccurate comment).  That comment was accurate was I was envisioning the second filter as being "deletionTime is greater than now", but then I must've realized that any domain with a deletionTime set at all is either already deleted or in the process of being deleted, thus won't need any further deletion actions.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1180)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java, line 141 at r1](https://reviewable.io/reviews/google/nomulus/1180#-MadYm5L6pwBe24z-vnP:-MaiLUWW5cF3wBNR4uwh:b-7z0mqs) ([raw file](https://github.com/google/nomulus/blob/81411624ba9d75bc0e30cd9b4cc80fca5789145c/core/src/main/java/google/registry/batch/DeleteExpiredDomainsAction.java#L141)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

May as well fix it to work with Datastore then (and remove the now-inaccurate comment).  That comment was accurate was I was envisioning the second filter as being "deletionTime is greater than now", but then I must've realized that any domain with a deletionTime set at all is either already deleted or in the process of being deleted, thus won't need any further deletion actions.
</blockquote></details>

yeah that's already done in the code I pushed a few minutes ago, but depending on how you're viewing this conversation Reviewable might be showing you out-of-date code

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1180)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/env/common/default/WEB-INF/datastore-indexes.xml, line 44 at r2](https://reviewable.io/reviews/google/nomulus/1180#-MaiLW5h8akf-pllOBnb:-MaiLW5h8akf-pllOBnc:b-m14i9x) ([raw file](https://github.com/google/nomulus/blob/bc27d578de973a4a1fe538c11eec65d9086b8e3d/core/src/main/java/google/registry/env/common/default/WEB-INF/datastore-indexes.xml#L44)):*
> ```XML
>     <property name="deletionTime" direction="asc"/>
>   </datastore-index>
>   
> ```

FYI you're going to need to run the re-save all EPP resources action after this gets deployed in order to populate this new index.  Until you do, the delete expired domains action won't find the domains to work on properly.

Fortunately I already wrote said action in such a way that it's resilient to indexes being wrong (see all the double-checking going on inside `runDomainDeleteFlow()`).

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1180)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/env/common/default/WEB-INF/datastore-indexes.xml, line 44 at r2](https://reviewable.io/reviews/google/nomulus/1180#-MaiLW5h8akf-pllOBnb:-MaiN5q0BDQslRnvVgrs:b-wnhccf) ([raw file](https://github.com/google/nomulus/blob/bc27d578de973a4a1fe538c11eec65d9086b8e3d/core/src/main/java/google/registry/env/common/default/WEB-INF/datastore-indexes.xml#L44)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

FYI you're going to need to run the re-save all EPP resources action after this gets deployed in order to populate this new index.  Until you do, the delete expired domains action won't find the domains to work on properly.

Fortunately I already wrote said action in such a way that it's resilient to indexes being wrong (see all the double-checking going on inside `runDomainDeleteFlow()`).
</blockquote></details>

Good call, I just made a note.

**Pull request merged**
