### PR TITLE
Add retries to DriveConnection.listFiles() on GoogleJsonResponseExceptions

### PR DESCRIPTION
**Pull request by jicelhay**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2541)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2541)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @github-advanced-security[bot] and @jicelhay)

___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 38 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZDTS3DWwJWhhkP96V:-O5ZDTS3DWwJWhhkP96W:bb5du7x) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L38)):*
> ```Java
> 
>   /** Number of times a request to Drive will be retried before propagating a failure. */
>   private static final int MAX_RETRIES = 3;
> ```

Considering that this is the number of failures across all requested pages, it probably needs to be higher.  3 would be suitable for retrying only a single retry, rather than every request in a large group.

Maybe something in the 7-10 range?
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 136 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZDgrWDgvmL_2NviVc:-O5ZDgrWDgvmL_2NviVd:b-vovzpr) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L136)):*
> ```Java
>    */
>   public List<String> listFiles(String parentFolderId, String query) throws IOException {
>     int currentRequestExecution = 0;
> ```

The name of this variable is simultaneously long while not actually being description.  I think `int failures` or `int errors` should be fine.  `fetchFailures` or `numFailures` would work too but maybe a little more verbose without adding clarity.
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 137 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZLgT7CxpalD9WMs06:-O5ZLgT7CxpalD9WMs07:bpv4fs3) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L137)):*
> ```Java
>   public List<String> listFiles(String parentFolderId, String query) throws IOException {
>     int currentRequestExecution = 0;
>     boolean requestExecutionFailed;
> ```

`latestRequestFailed` strikes me as a good name for this one, and it's especially clear when used in the `while` block.  The lengthy string `Execution` doesn't really add anything.
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 146 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZLvreA-Qhxdo0oV-g:-O5ZLvreA-Qhxdo0oV-h:bk262of) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L146)):*
> ```Java
>     req.setQ(q.toString());
>     do {
>       FileList files;
> ```

No need to split this declaration out as a separate line before the `try` block.
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 152 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZMQo6556k72TmJvne:-O5ZMQo6556k72TmJvnf:b-k27yl0) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L152)):*
> ```Java
>         files.getFiles().forEach(file -> result.add(file.getId()));
>         req.setPageToken(files.getNextPageToken());
>       } catch (GoogleJsonResponseException googleJsonResponseException) {
> ```

You can just name the exception variable here `e`.  That's common and less verbose.
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 154 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZMWbeCR1qkBZNL7y9:-O5ZMWbeCR1qkBZNL7yA:b-a72dst) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L154)):*
> ```Java
>       } catch (GoogleJsonResponseException googleJsonResponseException) {
>         if (currentRequestExecution >= MAX_RETRIES) {
>           throw googleJsonResponseException;
> ```

You probably want to wrap this inside another Exception to make a really clear message.  Something like:

```
throw new RuntimeException(String.format("Max failures reached while attempting to list Drive files in folder %s with query %s; failing permanently", parentFolderId, query), e);
```

Feel free to workshop that exception message a little bit.
___
*[`core/src/test/java/google/registry/storage/drive/DriveConnectionTest.java` line 183 at r1](https://reviewable.io/reviews/google/nomulus/2541#gh-1737079086:-O5ZNZKkCw_I1Vh0erzC:b3ks9) ([raw file](https://github.com/google/nomulus/blob/5ae0edfcd99f174037fbd7b3ee13dcec89e61e8a/core/src/test/java/google/registry/storage/drive/DriveConnectionTest.java#L183)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unread local variable

Variable 'File testFile' is never read.

[Show more details](https://github.com/google/nomulus/security/code-scanning/15005)
</blockquote></details>

^

**Review by jicelhay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2541)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 38 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZDTS3DWwJWhhkP96V:-O5ZZqgACbGksiO2ZUCr:b-p70gwg) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L38)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Considering that this is the number of failures across all requested pages, it probably needs to be higher.  3 would be suitable for retrying only a single retry, rather than every request in a large group.

Maybe something in the 7-10 range?
</blockquote></details>

Set to 10, let's see how it behaves.
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 136 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZDgrWDgvmL_2NviVc:-O5Z_36f1Z-K3GmVw_yc:btp42d9) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L136)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The name of this variable is simultaneously long while not actually being description.  I think `int failures` or `int errors` should be fine.  `fetchFailures` or `numFailures` would work too but maybe a little more verbose without adding clarity.
</blockquote></details>

Ok, renamed.
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 137 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZLgT7CxpalD9WMs06:-O5Z_6y01dM0hVufkH5B:btp42d9) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L137)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`latestRequestFailed` strikes me as a good name for this one, and it's especially clear when used in the `while` block.  The lengthy string `Execution` doesn't really add anything.
</blockquote></details>

Ok, renamed.
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 146 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZLvreA-Qhxdo0oV-g:-O5Z_8Q-CKoH1gOkWSOK:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L146)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

No need to split this declaration out as a separate line before the `try` block.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 152 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZMQo6556k72TmJvne:-O5Z_9LL6IdISAx7vU28:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L152)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You can just name the exception variable here `e`.  That's common and less verbose.
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 154 at r2](https://reviewable.io/reviews/google/nomulus/2541#-O5ZMWbeCR1qkBZNL7y9:-O5Z_9vY1ZNRD32XLA6Y:bwn230t) ([raw file](https://github.com/google/nomulus/blob/c6e7f512f5f348d7e7921abc8d9cc46afd0dd6c8/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L154)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You probably want to wrap this inside another Exception to make a really clear message.  Something like:

```
throw new RuntimeException(String.format("Max failures reached while attempting to list Drive files in folder %s with query %s; failing permanently", parentFolderId, query), e);
```

Feel free to workshop that exception message a little bit.
</blockquote></details>

Used that, just added some periods.
___
*[`core/src/test/java/google/registry/storage/drive/DriveConnectionTest.java` line 183 at r1](https://reviewable.io/reviews/google/nomulus/2541#gh-1737079086:-O5Z04co0bikyaoWfyo0:b-896fix) ([raw file](https://github.com/google/nomulus/blob/5ae0edfcd99f174037fbd7b3ee13dcec89e61e8a/core/src/test/java/google/registry/storage/drive/DriveConnectionTest.java#L183)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unread local variable

Variable 'File testFile' is never read.

[Show more details](https://github.com/google/nomulus/security/code-scanning/15005)
</blockquote></details>

Done.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2541)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @jicelhay)

___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 155 at r3](https://reviewable.io/reviews/google/nomulus/2541#-O5ZahbRBKV5VEXSsuVx:-O5ZahbRBKV5VEXSsuVy:b-i5bety) ([raw file](https://github.com/google/nomulus/blob/3bbd9be9cd42a3a584707cf913a95042e71fa870/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L155)):*
> ```Java
>           throw new RuntimeException(
>               String.format(
>                   "Max. failures reached while attempting to list Drive files in folder %s with query %s; failing permanently.",
> ```

Super nit but people will understand what "max" means without having to put a period here.



_Code quote:_
```Java
.
```

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2541#-:-O5Zatc14UwYsAhpz0WW:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @jicelhay)

**Review by jicelhay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2541)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/storage/drive/DriveConnection.java` line 155 at r3](https://reviewable.io/reviews/google/nomulus/2541#-O5ZahbRBKV5VEXSsuVx:-O5Zj8XE935Fc1-q3-sI:b-896fix) ([raw file](https://github.com/google/nomulus/blob/3bbd9be9cd42a3a584707cf913a95042e71fa870/core/src/main/java/google/registry/storage/drive/DriveConnection.java#L155)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Super nit but people will understand what "max" means without having to put a period here.
</blockquote></details>

Done.
___
*[`core/src/test/java/google/registry/storage/drive/DriveConnectionTest.java` line 183 at r1](https://reviewable.io/reviews/google/nomulus/2541#gh-1737079086:-O5ZjRy7-l9xnvH97tPI:b-896fix) ([raw file](https://github.com/google/nomulus/blob/5ae0edfcd99f174037fbd7b3ee13dcec89e61e8a/core/src/test/java/google/registry/storage/drive/DriveConnectionTest.java#L183)):*
<details><summary><i>Previously, jicelhay (Juan Celhay) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Pull request merged**
