### PR TITLE
Use Cloud SQL passwords from the Secret Manager

### PR DESCRIPTION
**Pull request by weiminyu**
Continue fetching passwords from Keyring until this change is deployed.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/959)

### CODE REVIEW

**Review by mindhog — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/959)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @weiminyu)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 274 at r1](https://reviewable.io/reviews/google/nomulus/959#-MT2QRdo0X0-NJfFvfNb:-MT2QRdo0X0-NJfFvfNc:b-5r2lxm) ([raw file](https://github.com/google/nomulus/blob/bb92dec2fbde7457739cbd6d31fb4301881062a6/core/src/main/java/google/registry/persistence/PersistenceModule.java#L274)):*
> ```
> com.google.common.base.Preconditions.checkState
> ```

Do we really want to throw an exception in this case?   Seems like a pretty tall order.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/959)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/persistence/PersistenceModule.java, line 274 at r1](https://reviewable.io/reviews/google/nomulus/959#-MT2QRdo0X0-NJfFvfNb:-MT2RHD39q6-iULb2MqL:b-w3vqbp) ([raw file](https://github.com/google/nomulus/blob/bb92dec2fbde7457739cbd6d31fb4301881062a6/core/src/main/java/google/registry/persistence/PersistenceModule.java#L274)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

> ```
> com.google.common.base.Preconditions.checkState
> ```

Do we really want to throw an exception in this case?   Seems like a pretty tall order.
</blockquote></details>

1. Fail fast in canary so that we can stop the deployment.
2. We've been loading from SecretManager and compare them for several weeks.

**Review by gbrodman — APPROVED** [review]
I assume you've done this, but have you checked the logs to make sure none of these errors have been showing up? 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/959#-:-MT2e1yu8xOTMTOMm86o:b-ombukm)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/959)* status: all files reviewed, 1 unresolved discussion (waiting on @mindhog)

**Review by mindhog — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/959)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by weiminyu — COMMENTED** [review]
Yes, I've checked in all environments.

Also tested this PR in alpha.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/959#-:-MT3fs0X2Ah03ziS2M0W:b-uceq35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @weiminyu)

**Pull request merged**
