### PR TITLE
Add a third poll message column in TransferData for domain transfers

### PR DESCRIPTION
**Pull request by gbrodman**
Because we don't store serverApproveEntities specifically as a set in
the SQL world, we need to make sure that the entities are all separated
and stored if they exist. For domain transfers, there exist three
separate poll messages (client losing, client gaining, autorenew) so we
need to store and retrieve that one.

Founnd this while converting domain transfer flows to SQL.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/974)

### CODE REVIEW

**Review by mindhog — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/974)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mindhog — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/974)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mindhog — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/974#-:-MULBoVpDj_fye2gtSEh:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by gbrodman** [comment]
thanks, the second push was because previously the VXX_.sql file didn't get added for some reason

**Comment by gbrodman** [comment]
oops, typo in the field name in the sql file (now it should match the others)

**Review by mindhog — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/974)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mindhog — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/974#-:-MUPKwsY6qxW8Pr8ghKT:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
