### PR TITLE
Show HTTP response code when PUT fails

### PR DESCRIPTION
**Pull request by jianglai**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2038)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2038#-NW8bXiGDQYVL8-WRWA9:-NW8bkdd95Lb7XWCaVEe:bwu2054) ([raw file](https://github.com/google/nomulus/blob/02c86a3624d06bc53b40f069237264936232a3d3/core/src/main/java/google/registry/rde/RdeReporter.java#L95)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Shouldn't we be logging the response message here too?  Just the response code on its own is not that much additional information.
</blockquote></details>

The simplest thing to do here might be to `break` on everything besides `SC_OK`.  Then you take advantage of the logging below.  But throwing an exception bypasses all that.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2038#-NW8bXiGDQYVL8-WRWA9:-NW8cAOo7Dt9BEq2gtFj:busr2ud) ([raw file](https://github.com/google/nomulus/blob/02c86a3624d06bc53b40f069237264936232a3d3/core/src/main/java/google/registry/rde/RdeReporter.java#L95)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

The simplest thing to do here might be to `break` on everything besides `SC_OK`.  Then you take advantage of the logging below.  But throwing an exception bypasses all that.
</blockquote></details>

It's not clear why `SC_BAD_REQUEST` would not throw in the first place.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2038#-NW8bXiGDQYVL8-WRWA9:-NW8ihSG11kE5B5qhzP9:bv4x0lo) ([raw file](https://github.com/google/nomulus/blob/02c86a3624d06bc53b40f069237264936232a3d3/core/src/main/java/google/registry/rde/RdeReporter.java#L95)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

It's not clear why `SC_BAD_REQUEST` would not throw in the first place.
</blockquote></details>

I think this change is worse now though as now you're entirely bypassing the section below:

```
    XjcIirdeaResult result = parseResult(rsp.getContent());
    if (result.getCode().getValue() != 1000) {
      logger.atWarning().log(
          "PUT rejected: %d %s\n%s",
          result.getCode().getValue(), result.getMsg(), result.getDescription());
      throw new InternalServerErrorException(result.getMsg());
    }
```

Also I think there's unexpected interactions with the exception you're throwing and `callWithRetry()`.  I think this all needs a rethink.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2038#-NW8bXiGDQYVL8-WRWA9:-NW8jBEE9DYLyzldrnxl:b-2n03rr) ([raw file](https://github.com/google/nomulus/blob/02c86a3624d06bc53b40f069237264936232a3d3/core/src/main/java/google/registry/rde/RdeReporter.java#L95)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think this change is worse now though as now you're entirely bypassing the section below:

```
    XjcIirdeaResult result = parseResult(rsp.getContent());
    if (result.getCode().getValue() != 1000) {
      logger.atWarning().log(
          "PUT rejected: %d %s\n%s",
          result.getCode().getValue(), result.getMsg(), result.getDescription());
      throw new InternalServerErrorException(result.getMsg());
    }
```

Also I think there's unexpected interactions with the exception you're throwing and `callWithRetry()`.  I think this all needs a rethink.
</blockquote></details>

Note how the existing processing, that correctly logs things, is already throwing an exception.  But if you throw an exception here, you're bypassing that entirely.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 95 at r1](https://reviewable.io/reviews/google/nomulus/2038#-NW8bXiGDQYVL8-WRWA9:-NW8k-4gAp_f-NGGNHWu:b8jnben) ([raw file](https://github.com/google/nomulus/blob/02c86a3624d06bc53b40f069237264936232a3d3/core/src/main/java/google/registry/rde/RdeReporter.java#L95)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Note how the existing processing, that correctly logs things, is already throwing an exception.  But if you throw an exception here, you're bypassing that entirely.
</blockquote></details>

Ah, you are right. Now it makes sense why `SC_BAD_REQUEST` would not throw here. I think the original logic is OK, but using switch kind of make it harder to understand. Basically if we get `OK` or `SC_BAD_REQUEST`, we proceed to check if the response body contained within is valid. If we get anything but, we throw an unrecoverable runtime error (which is now logged). If there's transient network issue that results in `urlFetchService.fetch` throwing a socket timeout exception, the PUT request will be retried.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 94 at r3](https://reviewable.io/reviews/google/nomulus/2038#-NW8mXRs58IeygFmZQ4u:-NW8mXRs58IeygFmZQ4v:bjumbu8) ([raw file](https://github.com/google/nomulus/blob/884f23a60c647e43913887a458f802624e25e238/core/src/main/java/google/registry/rde/RdeReporter.java#L94)):*
> ```Java
>                 throw new RuntimeException(
>                     String.format(
>                         "PUT failed: %d\n%s", responseCode, Arrays.toString(rsp1.getContent())));
> ```

This is a strange thing to put into the exception message (it's not really how it's intended to be used).  I would log this additional information separately at `severe`, and then throw an exception with a normally written message (that should be clearer than simply "PUT failed").

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 94 at r3](https://reviewable.io/reviews/google/nomulus/2038#-NW8mXRs58IeygFmZQ4u:-NW8pCtE2kTY5w3IsQ_Y:b-896fix) ([raw file](https://github.com/google/nomulus/blob/884f23a60c647e43913887a458f802624e25e238/core/src/main/java/google/registry/rde/RdeReporter.java#L94)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is a strange thing to put into the exception message (it's not really how it's intended to be used).  I would log this additional information separately at `severe`, and then throw an exception with a normally written message (that should be clearer than simply "PUT failed").
</blockquote></details>

Done.

**Review by jianglai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 93 at r4](https://reviewable.io/reviews/google/nomulus/2038#-NW8tH668E8BZwuwcfF3:-NW8tXjz6UTz_h-tjzAq:b-kkfjn3) ([raw file](https://github.com/google/nomulus/blob/e1f473a8fe6e8a739c6ee66d77c5494a19adc0d2/core/src/main/java/google/registry/rde/RdeReporter.java#L93)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs a better error message here.
</blockquote></details>

What do you have in mind? We don't know the cause other than that the request to PUT the report to ICANN's server has failed, and the details are logged already.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 93 at r4](https://reviewable.io/reviews/google/nomulus/2038#-NW8tH668E8BZwuwcfF3:-NW9DhcoDvMSk7Sfy2fz:blqi179) ([raw file](https://github.com/google/nomulus/blob/e1f473a8fe6e8a739c6ee66d77c5494a19adc0d2/core/src/main/java/google/registry/rde/RdeReporter.java#L93)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

What do you have in mind? We don't know the cause other than that the request to PUT the report to ICANN's server has failed, and the details are logged already.
</blockquote></details>

Well, how about any details about what failed?  "PUT failed" is a terrible error message; if you see that in isolation you have no idea what it was attempting to do.  At least say something about the upload of the RDE report to ICANN failing.  Your exception message below is better.

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 93 at r4](https://reviewable.io/reviews/google/nomulus/2038#-NW8tH668E8BZwuwcfF3:-NW9FOY1CYc7mecLS36R:byjn8a9) ([raw file](https://github.com/google/nomulus/blob/e1f473a8fe6e8a739c6ee66d77c5494a19adc0d2/core/src/main/java/google/registry/rde/RdeReporter.java#L93)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Well, how about any details about what failed?  "PUT failed" is a terrible error message; if you see that in isolation you have no idea what it was attempting to do.  At least say something about the upload of the RDE report to ICANN failing.  Your exception message below is better.
</blockquote></details>

Isn't it going to be a bit redundant when we'll have essentially the same message in the log and in the exception that is thrown immediately after the log? The log will give you a stack trace so people should know where the PUT failure happened.

Changed here and below.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/rde/RdeReporter.java` line 93 at r4](https://reviewable.io/reviews/google/nomulus/2038#-NW8tH668E8BZwuwcfF3:-NW9H24c-Wp7oepxHqyD:b1m2x1b) ([raw file](https://github.com/google/nomulus/blob/e1f473a8fe6e8a739c6ee66d77c5494a19adc0d2/core/src/main/java/google/registry/rde/RdeReporter.java#L93)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Isn't it going to be a bit redundant when we'll have essentially the same message in the log and in the exception that is thrown immediately after the log? The log will give you a stack trace so people should know where the PUT failure happened.

Changed here and below.
</blockquote></details>

To the extent that it's redundant, the greater detail should be in the well-formatted log message with all of the other details.  The exception is really just needed to terminate the action and return an HTTP error response.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2038#-:-NW9HJ756E-SiRdRm1sZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

**Pull request merged**
