### PR TITLE
Add log traces to Nomulus service on GKE

### PR DESCRIPTION
**Pull request by weiminyu**
Add request-scope log traces to Nomulus on GKE which, unlike AppEngine and Cloud Run etc, does not generate traces for hosted applications. This change only affects the GKE image. It does not affect the AppEngine services.

Log traces are added to Nomulus-generated logs in request-processing threads. Forked threads are not covered yet. The single relevant use case (TimeLimiter) will be addressed in a followup PR.

The main change is in the logging configuration:

*  Use gcp-cloud-logging's LoggingHandler

*  Add gcp-cloud-logging's TraceLoggingEnhancer to the handler.

*  Set a thread-local trace id through the TraceLoggingEnhancer in ServletBase on request's entry and clear it on completion.

Also removed an unused class (`RequestLogId`).

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2427)

### CODE REVIEW

**Review by weiminyu — COMMENTED** [review]
> Reviewed 24 of 41 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2427)* status: 27 of 41 files reviewed, 1 unresolved discussion (waiting on @github-advanced-security[bot])

___
*[`core/src/main/java/google/registry/module/ServletBase.java` line 107 at r1](https://reviewable.io/reviews/google/nomulus/2427#gh-1587937456:-NwuBwcb57cSUoaXVgdE:b-896fix) ([raw file](https://github.com/google/nomulus/blob/978818f63f3fa31c678fbe5a3ac500fe3054cfcb/core/src/main/java/google/registry/module/ServletBase.java#L107)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Useless parameter

The parameter 'startTime' is never used.

[Show more details](https://github.com/google/nomulus/security/code-scanning/8355)
</blockquote></details>

Done.

**Review by jianglai — CHANGES_REQUESTED** [review]
I think there's a good opportunity here to add trace ID to the proxy (not necessary in this PR). The proxy is asycnrhous so you cannot use `ThreaLocal`, but you can save the trace id as a [channel attribute](https://cs.opensource.google/search?q=attributekey&ss=nomulus%2Fnomulus:proxy%2F) so we get the same id for the same connection.

> Reviewed 37 of 41 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2427#-:-Nx-ILpC2uJZj6TvHeEw:b-pipk6v)* status: all files reviewed, 9 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`core/src/main/java/google/registry/module/ServletBase.java` line 114 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-2eGw1caZVstDfZu2:-Nx-2eGw1caZVstDfZu3:b-glo01z) ([raw file](https://github.com/google/nomulus/blob/9c4ed60a8582728a68559392bbb7606782e4827a/core/src/main/java/google/registry/module/ServletBase.java#L114)):*
> ```Java
>     // Use `isOnJetty == True` as a stand-in for GKE check in Nomulus. Do not manually set trace_ids
>     // on platforms already doing so, like AppEngine or Cloud Run.
>     if (isOnJetty()) {
> ```

There is an easier way to do this, I think. The per-service servlets are not actually used in the GKE image. Instead, it's the [`RegistryServlet`](https://cs.opensource.google/nomulus/nomulus/+/master:jetty/src/main/webapp/WEB-INF/web.xml;l=10;drc=147cdff5550bc5e554fc37d7baf0f545b91597a2;bpv=1;bpt=0) that handles all requests. You can just add the logic there and not worry about checking if the app is running on Jetty or not.
___
*[`jetty/build.gradle` line 35 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-FvZ8Dlfxm88t2TVs:-Nx-FvZ8Dlfxm88t2TVt:b-z05yb5) ([raw file](https://github.com/google/nomulus/blob/9c4ed60a8582728a68559392bbb7606782e4827a/jetty/build.gradle#L35)):*
> ```Gradle
>         // task. If more tests are added, this class along with the system
>         // property definition below, should be moved to a dedicated task.
>         includeTestsMatching "google.registry.jetty.LoggingPropertiesTest.*"
> ```

I don't understand why it is necessary to have this filter. Shouldn't all tests under the `test` directory to be automatically included?
___
*[`jetty/build.gradle` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-3mHp553Y75VK4KiV:-Nx-3mHp553Y75VK4KiW:b-c32gvz) ([raw file](https://github.com/google/nomulus/blob/9c4ed60a8582728a68559392bbb7606782e4827a/jetty/build.gradle#L48)):*
> ```Gradle
> dependencies {
>     implementation project(':core')
> ```

Any reason to have the empty lines here and below?

Also it might look better to have the `defs` definition first.
___
*[`jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-Gf3j2X6RGHp6BnNB:-Nx-Gf3j2X6RGHp6BnNC:b-jmy7rn) ([raw file](https://github.com/google/nomulus/blob/9c4ed60a8582728a68559392bbb7606782e4827a/jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java#L48)):*
> ```Java
>   @BeforeEach
>   void setup() {
>     origStdout = System.out;
> ```

Is this going to cause contention if we have multiple tests, given that the `System.out` field is static?
___
*[`util/src/main/java/google/registry/util/StringGenerator.java` line 44 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-Fa4005st5tS1S-zV:-Nx-Fa4005st5tS1S-zW:be1zqg6) ([raw file](https://github.com/google/nomulus/blob/9c4ed60a8582728a68559392bbb7606782e4827a/util/src/main/java/google/registry/util/StringGenerator.java#L44)):*
> ```Java
> 
>     /** Hex digit-only alphabet. */
>     public static final String HEX_DIGITS_ONLY = "0123456789abcdef";
> ```

Hexadecimal
___
*[`util/src/main/java/google/registry/util/StringGenerator.java` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-FRBu2yLSdRPnG9jk:-Nx-FRBu2yLSdRPnG9jl:b-ir2ip8) ([raw file](https://github.com/google/nomulus/blob/9c4ed60a8582728a68559392bbb7606782e4827a/util/src/main/java/google/registry/util/StringGenerator.java#L48)):*
> ```Java
>     /** Full ASCII alphabet with a wide selection of punctuation characters. */
>     public static final String FULL_ASCII =
>         "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`~!@#$%^&*()_-+={}[]\\/<>,.;?':|"
> ```

Seems to be a superfluous change.
___
*[`util/src/main/java/google/registry/util/GcpJsonFormatter.java` line 89 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-9_z7DDMgl1-TkNZo:-Nx-9_z7DDMgl1-TkNZp:bjgkahi) ([raw file](https://github.com/google/nomulus/blob/9c4ed60a8582728a68559392bbb7606782e4827a/util/src/main/java/google/registry/util/GcpJsonFormatter.java#L89)):*
> ```Java
>         source += " " + record.getSourceMethodName();
>       }
>       if (record instanceof SimpleLogRecord) {
> ```

You can do `if (record instandOf SimpleLogRecord simpleLogRecord) {`, which will allow you to use `simpleLogRecord` without casting.
___
*[`util/src/main/java/google/registry/util/GcpJsonFormatter.java` line 95 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-AWtU58i_UcXpGuck:-Nx-AWtU58i_UcXpGucl:b-45fsag) ([raw file](https://github.com/google/nomulus/blob/9c4ed60a8582728a68559392bbb7606782e4827a/util/src/main/java/google/registry/util/GcpJsonFormatter.java#L95)):*
> ```Java
>                 .map(LogSite::getLineNumber);
>         if (lineNumber.isPresent()) {
>           source += " line:" + lineNumber.get();
> ```

Does this give you the line number of there a log is written?

**Review by weiminyu — COMMENTED** [review]
Yes, it will depend on different solution and is unrelated to Nomulus change.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2427#-:-NxIeJanEUa-9-rzrZyy:bjtfz1t)* status: 26 of 41 files reviewed, 9 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

___
*[`jetty/build.gradle` line 35 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-FvZ8Dlfxm88t2TVs:-NxIrs_fAo0yHsUKjdfp:b9jvx46) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/build.gradle#L35)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I don't understand why it is necessary to have this filter. Shouldn't all tests under the `test` directory to be automatically included?
</blockquote></details>

Just a document for the future. If/when this test is moved out of the `test` task, the new task will need this filter.
___
*[`jetty/build.gradle` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-3mHp553Y75VK4KiV:-NxIsJMS57AKjCvdQ8OT:b-9lfm0e) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/build.gradle#L48)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Any reason to have the empty lines here and below?

Also it might look better to have the `defs` definition first.
</blockquote></details>

One blank line to separate production and test dependencies.

Moved defs up
___
*[`jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-Gf3j2X6RGHp6BnNB:-NxIsXbq0TCz0bfaO6BR:bx21f15) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java#L48)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is this going to cause contention if we have multiple tests, given that the `System.out` field is static?
</blockquote></details>


In general:

* As the only test in the only class of the task, it's never a problem.

* If another test is added to this class, it would be a problem if intra-class parallel execution is enabled, and we have not done.

* If another test class is added to the same task that also mess with stdout, there may be conflict.

In this particular case: no, since the test greps for its own logs, ignoring irrelevant stuff.
___
*[`util/src/main/java/google/registry/util/StringGenerator.java` line 44 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-Fa4005st5tS1S-zV:-NxIyKfz4DpNXA7biVHR:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/util/src/main/java/google/registry/util/StringGenerator.java#L44)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Hexadecimal
</blockquote></details>

Done.
___
*[`util/src/main/java/google/registry/util/StringGenerator.java` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-FRBu2yLSdRPnG9jk:-NxIyXm83DVTcI5GHQg0:byfutvt) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/util/src/main/java/google/registry/util/StringGenerator.java#L48)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Seems to be a superfluous change.
</blockquote></details>

Line too long. Formatter chopped the empty space off.
___
*[`core/src/main/java/google/registry/module/ServletBase.java` line 114 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-2eGw1caZVstDfZu2:-NxIrq3F1e45VGU8kZXE:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/core/src/main/java/google/registry/module/ServletBase.java#L114)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

There is an easier way to do this, I think. The per-service servlets are not actually used in the GKE image. Instead, it's the [`RegistryServlet`](https://cs.opensource.google/nomulus/nomulus/+/master:jetty/src/main/webapp/WEB-INF/web.xml;l=10;drc=147cdff5550bc5e554fc37d7baf0f545b91597a2;bpv=1;bpt=0) that handles all requests. You can just add the logic there and not worry about checking if the app is running on Jetty or not.
</blockquote></details>

Done.
___
*[`util/src/main/java/google/registry/util/GcpJsonFormatter.java` line 89 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-9_z7DDMgl1-TkNZo:-NxIy4dZDJMkPS5wVard:b-ahle5g) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/util/src/main/java/google/registry/util/GcpJsonFormatter.java#L89)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

You can do `if (record instandOf SimpleLogRecord simpleLogRecord) {`, which will allow you to use `simpleLogRecord` without casting.
</blockquote></details>

Good to know.
___
*[`util/src/main/java/google/registry/util/GcpJsonFormatter.java` line 95 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-AWtU58i_UcXpGuck:-NxIy8SV7gvXiv_v2rtu:bb77ufg) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/util/src/main/java/google/registry/util/GcpJsonFormatter.java#L95)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Does this give you the line number of there a log is written?
</blockquote></details>

Yes.

**Review by weiminyu — COMMENTED** [review]
Yes, it will depend on different solution and is unrelated to Nomulus change.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2427#-:-NxIeJanEUa-9-rzrZyy:bjtfz1t)* status: 26 of 41 files reviewed, 9 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

___
*[`jetty/build.gradle` line 35 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-FvZ8Dlfxm88t2TVs:-NxIrs_fAo0yHsUKjdfp:b9jvx46) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/build.gradle#L35)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I don't understand why it is necessary to have this filter. Shouldn't all tests under the `test` directory to be automatically included?
</blockquote></details>

Just a document for the future. If/when this test is moved out of the `test` task, the new task will need this filter.
___
*[`jetty/build.gradle` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-3mHp553Y75VK4KiV:-NxIsJMS57AKjCvdQ8OT:b-9lfm0e) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/build.gradle#L48)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Any reason to have the empty lines here and below?

Also it might look better to have the `defs` definition first.
</blockquote></details>

One blank line to separate production and test dependencies.

Moved defs up
___
*[`jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-Gf3j2X6RGHp6BnNB:-NxIsXbq0TCz0bfaO6BR:bx21f15) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java#L48)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Is this going to cause contention if we have multiple tests, given that the `System.out` field is static?
</blockquote></details>


In general:

* As the only test in the only class of the task, it's never a problem.

* If another test is added to this class, it would be a problem if intra-class parallel execution is enabled, and we have not done.

* If another test class is added to the same task that also mess with stdout, there may be conflict.

In this particular case: no, since the test greps for its own logs, ignoring irrelevant stuff.
___
*[`util/src/main/java/google/registry/util/StringGenerator.java` line 44 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-Fa4005st5tS1S-zV:-NxIyKfz4DpNXA7biVHR:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/util/src/main/java/google/registry/util/StringGenerator.java#L44)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Hexadecimal
</blockquote></details>

Done.
___
*[`util/src/main/java/google/registry/util/StringGenerator.java` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-FRBu2yLSdRPnG9jk:-NxIyXm83DVTcI5GHQg0:byfutvt) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/util/src/main/java/google/registry/util/StringGenerator.java#L48)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Seems to be a superfluous change.
</blockquote></details>

Line too long. Formatter chopped the empty space off.
___
*[`core/src/main/java/google/registry/module/ServletBase.java` line 114 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-2eGw1caZVstDfZu2:-NxIrq3F1e45VGU8kZXE:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/core/src/main/java/google/registry/module/ServletBase.java#L114)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

There is an easier way to do this, I think. The per-service servlets are not actually used in the GKE image. Instead, it's the [`RegistryServlet`](https://cs.opensource.google/nomulus/nomulus/+/master:jetty/src/main/webapp/WEB-INF/web.xml;l=10;drc=147cdff5550bc5e554fc37d7baf0f545b91597a2;bpv=1;bpt=0) that handles all requests. You can just add the logic there and not worry about checking if the app is running on Jetty or not.
</blockquote></details>

Done.
___
*[`util/src/main/java/google/registry/util/GcpJsonFormatter.java` line 89 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-9_z7DDMgl1-TkNZo:-NxIy4dZDJMkPS5wVard:b-ahle5g) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/util/src/main/java/google/registry/util/GcpJsonFormatter.java#L89)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

You can do `if (record instandOf SimpleLogRecord simpleLogRecord) {`, which will allow you to use `simpleLogRecord` without casting.
</blockquote></details>

Good to know.
___
*[`util/src/main/java/google/registry/util/GcpJsonFormatter.java` line 95 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-AWtU58i_UcXpGuck:-NxIy8SV7gvXiv_v2rtu:bb77ufg) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/util/src/main/java/google/registry/util/GcpJsonFormatter.java#L95)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Does this give you the line number of there a log is written?
</blockquote></details>

Yes.

**Review by jianglai — APPROVED** [review]
> Reviewed 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2427)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @weiminyu)

___
*[`jetty/build.gradle` line 35 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-FvZ8Dlfxm88t2TVs:-NxJ38PRD2ilY-2Y2PA5:bed6yk8) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/build.gradle#L35)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Just a document for the future. If/when this test is moved out of the `test` task, the new task will need this filter.
</blockquote></details>

Why would this test be moved out of the `test` task?
___
*[`jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-Gf3j2X6RGHp6BnNB:-NxJ3Mgb5nNMYFSiiRRb:b-o5waix) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java#L48)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

In general:

* As the only test in the only class of the task, it's never a problem.

* If another test is added to this class, it would be a problem if intra-class parallel execution is enabled, and we have not done.

* If another test class is added to the same task that also mess with stdout, there may be conflict.

In this particular case: no, since the test greps for its own logs, ignoring irrelevant stuff.
</blockquote></details>

Might be wise to note the potential pitfalls in javadoc.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2427)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot] and @jianglai)

___
*[`jetty/build.gradle` line 35 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-FvZ8Dlfxm88t2TVs:-NxJATnu15g0zBtSf1eW:b3wj43h) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/build.gradle#L35)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Why would this test be moved out of the `test` task?
</blockquote></details>

It needs the logging system property that other tests do not need. See line below.
___
*[`jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java` line 48 at r3](https://reviewable.io/reviews/google/nomulus/2427#-Nx-Gf3j2X6RGHp6BnNB:-NxJHFTaEQaOw40cEMF_:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1d337ce3a6367a7b7ef2ae51b7a1146aa7232534/jetty/src/test/java/google/registry/jetty/LoggingPropertiesTest.java#L48)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Might be wise to note the potential pitfalls in javadoc.
</blockquote></details>

Done.

**Pull request merged**
