### PR TITLE
Make cloud scheduler deployment part of gradle deploy (alpha, qa and crash)

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1969)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1969)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`appengine_war.gradle` line 106 at r1](https://reviewable.io/reviews/google/nomulus/1969#-NQg9jPK1Kzt_Q9Vr_hB:-NQg9jPK1Kzt_Q9Vr_hC:b364sg7) ([raw file](https://github.com/google/nomulus/blob/d796cdf94c2b8030eb4636ef020d114357dd4f23/appengine_war.gradle#L106)):*
> ```Gradle
> }
> 
> appengineDeployAll.finalizedBy ':core:cloudSchedulerDeployer'
> ```

what's the reason behind having the task be in the core build.gradle file and not the root build.gradle file? 
___
*[`core/build.gradle` line 1035 at r1](https://reviewable.io/reviews/google/nomulus/1969#-NQg9TffDqjyElROCymj:-NQg9TffDqjyElROCymk:b-sf4i91) ([raw file](https://github.com/google/nomulus/blob/d796cdf94c2b8030eb4636ef020d114357dd4f23/core/build.gradle#L1035)):*
> ```Gradle
>   doLast {
>     def env = rootProject.environment
>     if (env == 'alpha' || env == "qa") {
> ```

couple notes actually 

1. can we add `crash` to this too? 
2. if the environment is something else maybe we should throw an exception

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1969)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`appengine_war.gradle` line 106 at r1](https://reviewable.io/reviews/google/nomulus/1969#-NQg9jPK1Kzt_Q9Vr_hB:-NQgBdo5CzCLjxMTvWGo:b-7k2a53) ([raw file](https://github.com/google/nomulus/blob/d796cdf94c2b8030eb4636ef020d114357dd4f23/appengine_war.gradle#L106)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what's the reason behind having the task be in the core build.gradle file and not the root build.gradle file? 
</blockquote></details>

Because that's where the configs are, but I don't feel strongly about it
___
*[`core/build.gradle` line 1035 at r1](https://reviewable.io/reviews/google/nomulus/1969#-NQg9TffDqjyElROCymj:-NQgB4dq6sd0nao9WSF5:buybcqf) ([raw file](https://github.com/google/nomulus/blob/d796cdf94c2b8030eb4636ef020d114357dd4f23/core/build.gradle#L1035)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

couple notes actually 

1. can we add `crash` to this too? 
2. if the environment is something else maybe we should throw an exception 

</blockquote></details>

1 - Added crash
2 - I don't want to add an exception, as exception interrupts the deployment and I'm not  sure if the deployAll from appengine plugin is used anywhere under the hood in prod or sandbox. What I want is do nothing related to cloud scheduler if it's not one of the selected envs

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1969)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`appengine_war.gradle` line 106 at r1](https://reviewable.io/reviews/google/nomulus/1969#-NQg9jPK1Kzt_Q9Vr_hB:-NQkyH2FBRbba8Uar0bK:bb6un1j) ([raw file](https://github.com/google/nomulus/blob/d796cdf94c2b8030eb4636ef020d114357dd4f23/appengine_war.gradle#L106)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

yeah i think the (giant, and becoming larger) root file is probably best since it isn't particular to core (it includes the release folder too) 
</blockquote></details>

Done
___
*[`core/build.gradle` line 1035 at r1](https://reviewable.io/reviews/google/nomulus/1969#-NQg9TffDqjyElROCymj:-NQkyI3LA91Ht7yWAoLL:b-wzdti8) ([raw file](https://github.com/google/nomulus/blob/d796cdf94c2b8030eb4636ef020d114357dd4f23/core/build.gradle#L1035)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

actually if we put this in the root build.gradle file then we can use the `prodOrSandboxEnv` param like `verifyDeploymentParams()` does (which we use in all the AppEngine deploy tasks). So I think this should be fine and we can use that? 
</blockquote></details>

Yeah, makes sense, updated

**Review by gbrodman — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1969)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
