### PR TITLE
Fix front-end unit tests

### PR DESCRIPTION
**Pull request by gbrodman**
This doesn't really add any tests, and we'll require many more additions if we actually want to have full unit testing, but this at least makes the tests pass when running `npm test`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2529)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2529)* status: all files reviewed, 3 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/settings/security/security.component.spec.ts` line 132 at r1](https://reviewable.io/reviews/google/nomulus/2529#-O4QUl2X95bN6LeQey03:-O4QUl2Y81dhu986ZdIo:b-x2lcce) ([raw file](https://github.com/google/nomulus/blob/06be66b569e2315a0f6a09143746d1dd3628b269/console-webapp/src/app/settings/security/security.component.spec.ts#L132)):*
> ```XML
>     fixture.detectChanges();
>     const el = fixture.nativeElement.querySelector(
>       '#console-app__clientCertificateValue'
> ```

Any reason this has to be an id instead of a class?
___
*[`console-webapp/src/app/settings/security/securityEdit.component.html` line 36 at r1](https://reviewable.io/reviews/google/nomulus/2529#-O4QUrV5-pnmT8_RrC-q:-O4QUrV5-pnmT8_RrC-r:byr4ffv) ([raw file](https://github.com/google/nomulus/blob/06be66b569e2315a0f6a09143746d1dd3628b269/console-webapp/src/app/settings/security/securityEdit.component.html#L36)):*
> ```HTML
>     <mat-form-field appearance="outline">
>       <textarea
>         id="console-app__clientCertificateValue"
> ```

see above
___
*[`console-webapp/src/app/settings/whois/whois.component.spec.ts` line 38 at r1](https://reviewable.io/reviews/google/nomulus/2529#-O4QUw_pCrZ4Z3Feh0Sg:-O4QUw_pCrZ4Z3Feh0Sh:b-dvns47) ([raw file](https://github.com/google/nomulus/blob/06be66b569e2315a0f6a09143746d1dd3628b269/console-webapp/src/app/settings/whois/whois.component.spec.ts#L38)):*
> ```XML
>           provide: RegistrarService,
>           useValue: {
>             registrar: function () {
> ```

I think we might have to deal with it a lot. Would be worth making some mock service instance maybe?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2529)* status: all files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/security/security.component.spec.ts` line 132 at r1](https://reviewable.io/reviews/google/nomulus/2529#-O4QUl2X95bN6LeQey03:-O4QxrK9ADHPHVp0Pf3L:bfbs7x6) ([raw file](https://github.com/google/nomulus/blob/06be66b569e2315a0f6a09143746d1dd3628b269/console-webapp/src/app/settings/security/security.component.spec.ts#L132)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Any reason this has to be an id instead of a class?
</blockquote></details>

nope! changed
___
*[`console-webapp/src/app/settings/security/securityEdit.component.html` line 36 at r1](https://reviewable.io/reviews/google/nomulus/2529#-O4QUrV5-pnmT8_RrC-q:-O4R-EKC34-dANn2tJTj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/06be66b569e2315a0f6a09143746d1dd3628b269/console-webapp/src/app/settings/security/securityEdit.component.html#L36)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`console-webapp/src/app/settings/whois/whois.component.spec.ts` line 38 at r1](https://reviewable.io/reviews/google/nomulus/2529#-O4QUw_pCrZ4Z3Feh0Sg:-O4RSlg_4Eamznd8l4rz:bmdelyh) ([raw file](https://github.com/google/nomulus/blob/06be66b569e2315a0f6a09143746d1dd3628b269/console-webapp/src/app/settings/whois/whois.component.spec.ts#L38)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I think we might have to deal with it a lot. Would be worth making some mock service instance maybe?
</blockquote></details>

Probably! Do you know of any good resources online on that subject (or really, something that I can just google for and go from there)? 

I don't know that such a thing would need to be in this PR but we'll definitely want it for the future.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2529)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/whois/whois.component.spec.ts` line 38 at r1](https://reviewable.io/reviews/google/nomulus/2529#-O4QUw_pCrZ4Z3Feh0Sg:-O4gBOYd6APtG4e5-Dr7:b1shenj) ([raw file](https://github.com/google/nomulus/blob/06be66b569e2315a0f6a09143746d1dd3628b269/console-webapp/src/app/settings/whois/whois.component.spec.ts#L38)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Probably! Do you know of any good resources online on that subject (or really, something that I can just google for and go from there)? 

I don't know that such a thing would need to be in this PR but we'll definitely want it for the future.
</blockquote></details>

Maybe something like this? Obviously we'll probably want to add more in the future, but this is all we need for this PR / for the tests as they currently exist

**Review by ptkach — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2529)* status: all files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/settings/whois/whois.component.spec.ts` line 38 at r1](https://reviewable.io/reviews/google/nomulus/2529#-O4QUw_pCrZ4Z3Feh0Sg:-O4pIhPVBG0EZGhf0kqe:b3hvx5d) ([raw file](https://github.com/google/nomulus/blob/06be66b569e2315a0f6a09143746d1dd3628b269/console-webapp/src/app/settings/whois/whois.component.spec.ts#L38)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Maybe something like this? Obviously we'll probably want to add more in the future, but this is all we need for this PR / for the tests as they currently exist
</blockquote></details>

Yep, that should do it nicely

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2529)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/whois/whois.component.spec.ts` line 38 at r1](https://reviewable.io/reviews/google/nomulus/2529#-O4QUw_pCrZ4Z3Feh0Sg:-O4pncKj972B2-SUWLy6:b-896fix) ([raw file](https://github.com/google/nomulus/blob/06be66b569e2315a0f6a09143746d1dd3628b269/console-webapp/src/app/settings/whois/whois.component.spec.ts#L38)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Yep, that should do it nicely
</blockquote></details>

Done.

**Pull request merged**
