### PR TITLE
Fix a BSA bug and refactor some unit tests

### PR DESCRIPTION
**Pull request by weiminyu**
Added a few helpers for managing reserved list in tests and updated the tests to use them.

Also fixed a bug: when quering for newly created domains, the query
should be restricted to bsa-enrolled tlds.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2291)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2291)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/bsa/ReservedDomainsUtils.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2291#-NoKf6A48P5ldvptaNsq:-NoKf6A48P5ldvptaNsr:b-hnc1xt) ([raw file](https://github.com/google/nomulus/blob/4608bd54cb0c3f60c79ca857a5d95912fcabd430/core/src/main/java/google/registry/bsa/ReservedDomainsUtils.java#L55)):*
> ```Java
> 
>   /** Returns all reserved domains in a given {@code tld} as of {@code now}. */
>   static ImmutableSet<String> getAllReservedDomainsInTld(Tld tld, DateTime now) {
> ```

You might consider handling this in the same way I do in the upload BSA file:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomainsAction.java;l=207-216;drc=036d35c11a03654cf51e330c4d0978e6ce2facfe

Namely, that way takes advantage of the reserved list cache, so in most circumstances it shouldn't need to hit the DB at all (or at least, won't do so repeatedly, if this is being called more than once within the cache interval).

Crucially it all comes down to leveraging this method:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/tld/label/ReservedList.java;l=269-276;drc=1dcf34ccc20e8bfcf1ed0500d7488fc3500be37c
___
*[`core/src/main/java/google/registry/bsa/ReservedDomainsUtils.java` line 60 at r1](https://reviewable.io/reviews/google/nomulus/2291#-NoKebysB1ty42F-tjxy:-NoKebysB1ty42F-tjxz:blbrg1h) ([raw file](https://github.com/google/nomulus/blob/4608bd54cb0c3f60c79ca857a5d95912fcabd430/core/src/main/java/google/registry/bsa/ReservedDomainsUtils.java#L60)):*
> ```Java
>         .filter(Optional::isPresent)
>         .map(Optional::get)
>         .filter(ReservedList::getShouldPublish)
> ```

This needs clarification in the Javadoc that it's getting only reserved names that should be published for a given TLD, and that it's not in fact the set of all labels that are actually reserved.
___
*[`core/src/main/java/google/registry/bsa/persistence/Queries.java` line 103 at r1](https://reviewable.io/reviews/google/nomulus/2291#-NoKfWwM1ClF44b4vYyX:-NoKfWwM1ClF44b4vYyY:b-6aavyy) ([raw file](https://github.com/google/nomulus/blob/4608bd54cb0c3f60c79ca857a5d95912fcabd430/core/src/main/java/google/registry/bsa/persistence/Queries.java#L103)):*
> ```Java
>       ImmutableCollection<String> tlds, DateTime minCreationTime, DateTime now) {
>     return ImmutableSet.copyOf(
>         tm().getEntityManager()
> ```

Should these be on `replicaTm()`?  It shouldn't hit a timeout with that right?

So long as the queries aren't for which domains are actually blocked at time of attempted domain creation, I think we should be good to use the possibly-slightly-stale replica data for all of the BSA stuff in exchange for not affecting the primary DB performance.

(And there would need to be concomitant changes to the `transact()` calls to have them use `replicaTm()` as well.)

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2291)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/bsa/ReservedDomainsUtils.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2291#-NoKf6A48P5ldvptaNsq:-NoNNvN5EVjS-1IB18ZP:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4608bd54cb0c3f60c79ca857a5d95912fcabd430/core/src/main/java/google/registry/bsa/ReservedDomainsUtils.java#L55)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

You might consider handling this in the same way I do in the upload BSA file:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/bsa/UploadBsaUnavailableDomainsAction.java;l=207-216;drc=036d35c11a03654cf51e330c4d0978e6ce2facfe

Namely, that way takes advantage of the reserved list cache, so in most circumstances it shouldn't need to hit the DB at all (or at least, won't do so repeatedly, if this is being called more than once within the cache interval).

Crucially it all comes down to leveraging this method:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/model/tld/label/ReservedList.java;l=269-276;drc=1dcf34ccc20e8bfcf1ed0500d7488fc3500be37c
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/bsa/ReservedDomainsUtils.java` line 60 at r1](https://reviewable.io/reviews/google/nomulus/2291#-NoKebysB1ty42F-tjxy:-NoNMY7N2xMAFBrzhgvq:bh1o5re) ([raw file](https://github.com/google/nomulus/blob/4608bd54cb0c3f60c79ca857a5d95912fcabd430/core/src/main/java/google/registry/bsa/ReservedDomainsUtils.java#L60)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This needs clarification in the Javadoc that it's getting only reserved names that should be published for a given TLD, and that it's not in fact the set of all labels that are actually reserved.
</blockquote></details>

Removed the `should-publish` check after offline discussion.

Also removed it from `UploadBsaUnavailableDomainsAction`.
___
*[`core/src/main/java/google/registry/bsa/persistence/Queries.java` line 103 at r1](https://reviewable.io/reviews/google/nomulus/2291#-NoKfWwM1ClF44b4vYyX:-NoONTWB4lThyvA-DHW_:b-w62iso) ([raw file](https://github.com/google/nomulus/blob/4608bd54cb0c3f60c79ca857a5d95912fcabd430/core/src/main/java/google/registry/bsa/persistence/Queries.java#L103)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Should these be on `replicaTm()`?  It shouldn't hit a timeout with that right?

So long as the queries aren't for which domains are actually blocked at time of attempted domain creation, I think we should be good to use the possibly-slightly-stale replica data for all of the BSA stuff in exchange for not affecting the primary DB performance.

(And there would need to be concomitant changes to the `transact()` calls to have them use `replicaTm()` as well.)
</blockquote></details>

Done.

I wanted to defer it for later, but we may as well changing it now.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2291)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/bsa/persistence/Queries.java` line 45 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDylM9YZg0VrTxVZN:-NoPDylM9YZg0VrTxVZO:b-5spjcy) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/bsa/persistence/Queries.java#L45)):*
> ```Java
>       ImmutableCollection<String> labels) {
>     return ((Stream<?>)
>             getJpaEntityManager()
> ```

`getJpaEntityManager()` is kind of long and clunky to see everywhere if it's going to be as commonly used as something like `tm()`.  Would `em()` be suitable?
___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 134 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDSYP-D0Jx4G-Dm6x:-NoPDSYP-D0Jx4G-Dm6y:b-87qtlm) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L134)):*
> ```Java
>   }
> 
>   @Deprecated // This method is misleading. Use the static `getJpaEntityManager` method.
> ```

Wait why is this misleading?
___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 161 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDWsQ3HwRSdRMjSm8:-NoPDWsQ3HwRSdRMjSm9:b-rwcovu) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L161)):*
> ```Java
>   }
> 
>   @Deprecated // This method is misleading. Use the static `isInTransaction` method.
> ```

Not sure I understand why it's misleading or what the difference between the two is.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2291)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/bsa/persistence/Queries.java` line 45 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDylM9YZg0VrTxVZN:-NoSOr9P8uPQH23OH1aC:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/bsa/persistence/Queries.java#L45)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`getJpaEntityManager()` is kind of long and clunky to see everywhere if it's going to be as commonly used as something like `tm()`.  Would `em()` be suitable?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 134 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDSYP-D0Jx4G-Dm6x:-NoSMcT-Bx9_OK0gwgO7:bjdat94) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L134)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Wait why is this misleading?
</blockquote></details>

It's used as `tm().getEntityManager()` or `replicaTm().inTransaction()`and gives the illusion that the specific db instance is used,  while in reality it uses the static `ThreadLocal` which is established by the outermost `transact` call.

I think we should switch to static methods when we mix primary and replica in the same `application` such as BSA.

This doesn't prevent us from designing a new transaction model that better addresses the issue. 

I'll document this later, once we get some more experience with the BSA code base.
___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 161 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDWsQ3HwRSdRMjSm8:-NoSO29hCtrEHVlTyR69:b-q64pkt) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L161)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Not sure I understand why it's misleading or what the difference between the two is.
</blockquote></details>

See above.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2291)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @weiminyu)

___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 134 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDSYP-D0Jx4G-Dm6x:-NoSmf-Y1mbVpTS838Be:bsuxw59) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L134)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

It's used as `tm().getEntityManager()` or `replicaTm().inTransaction()`and gives the illusion that the specific db instance is used,  while in reality it uses the static `ThreadLocal` which is established by the outermost `transact` call.

I think we should switch to static methods when we mix primary and replica in the same `application` such as BSA.

This doesn't prevent us from designing a new transaction model that better addresses the issue. 

I'll document this later, once we get some more experience with the BSA code base.
</blockquote></details>

Please add this explanation here as a Javadoc (or on the interface, whichever is relevant) so that people don't use it incorrectly.  As it currently is, it's quite rare that people are going to see the code comment when they're figure out what to use from a callsite.

Also maybe this method should be marked deprecated at the interface level?
___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 161 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDWsQ3HwRSdRMjSm8:-NoSmupP9114kJ9E8Leo:b-o03o70) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L161)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Ditto as above.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2291)* status: 0 of 21 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 134 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDSYP-D0Jx4G-Dm6x:-NoSpeBo1EmDiO6P44K8:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L134)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Please add this explanation here as a Javadoc (or on the interface, whichever is relevant) so that people don't use it incorrectly.  As it currently is, it's quite rare that people are going to see the code comment when they're figure out what to use from a callsite.

Also maybe this method should be marked deprecated at the interface level?
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java` line 161 at r2](https://reviewable.io/reviews/google/nomulus/2291#-NoPDWsQ3HwRSdRMjSm8:-NoSpeW35pnnThtnK_Rg:b-896fix) ([raw file](https://github.com/google/nomulus/blob/4f328ff3b2ae94dafaccbf0cc750a5bc5ea0b3ea/core/src/main/java/google/registry/persistence/transaction/JpaTransactionManagerImpl.java#L161)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto as above.
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2291)* status: 0 of 23 files reviewed, all discussions resolved

**Pull request merged**
