### PR TITLE
Convert to tm() some low-hanging ofy fruit

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1029)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/DeleteTldCommand.java, line 82 at r1](https://reviewable.io/reviews/google/nomulus/1029#-MWZnBrQDchoXuLvQdlG:-MWZnBrR5IbJT8i0_Rg-:b-5qtuc8) ([raw file](https://github.com/google/nomulus/blob/68cb36388e368c0c81532bfadd08fe49dc88be1c/core/src/main/java/google/registry/tools/DeleteTldCommand.java#L82)):*
> ```Java
>   }
> 
>   private boolean isDomainPresent(String tld) {
> ```

Needs a better method name.  Something does `isTldEmpty()` or `doesTldContainDomains()`.

You would logically expect that a method named `isDomainPresent()` would be passed a (second-level) domain as argument, but that's not happening here.
___
*[core/src/main/java/google/registry/tools/DeleteTldCommand.java, line 83 at r1](https://reviewable.io/reviews/google/nomulus/1029#-MWZna8i8oAxB2WRIMHk:-MWZna8i8oAxB2WRIMHl:b-wfxyyx) ([raw file](https://github.com/google/nomulus/blob/68cb36388e368c0c81532bfadd08fe49dc88be1c/core/src/main/java/google/registry/tools/DeleteTldCommand.java#L83)):*
> ```Java
> 
>   private boolean isDomainPresent(String tld) {
>     if (tm().isOfy()) {
> ```

We need to standardize on how we're making this determination across the entire codebase (not in this PR).  I don't think this is 100% right.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029#-:-MWZoGYg1al0-5etk8U1:bnfp4nl)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/DeleteTldCommand.java, line 82 at r1](https://reviewable.io/reviews/google/nomulus/1029#-MWZnBrQDchoXuLvQdlG:-MWZoKNI6pTCXHVXuGKr:b-bj3el) ([raw file](https://github.com/google/nomulus/blob/68cb36388e368c0c81532bfadd08fe49dc88be1c/core/src/main/java/google/registry/tools/DeleteTldCommand.java#L82)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Needs a better method name.  Something does `isTldEmpty()` or `doesTldContainDomains()`.

You would logically expect that a method named `isDomainPresent()` would be passed a (second-level) domain as argument, but that's not happening here.
</blockquote></details>

s/does/like/

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/DeleteTldCommand.java, line 82 at r1](https://reviewable.io/reviews/google/nomulus/1029#-MWZnBrQDchoXuLvQdlG:-MW_IeKODZR6pCXafUVj:b-896fix) ([raw file](https://github.com/google/nomulus/blob/68cb36388e368c0c81532bfadd08fe49dc88be1c/core/src/main/java/google/registry/tools/DeleteTldCommand.java#L82)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

s/does/like/
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/DeleteTldCommand.java, line 83 at r1](https://reviewable.io/reviews/google/nomulus/1029#-MWZna8i8oAxB2WRIMHk:-MW_JUlS0XJp6_B3m4Zt:bwz8yzp) ([raw file](https://github.com/google/nomulus/blob/68cb36388e368c0c81532bfadd08fe49dc88be1c/core/src/main/java/google/registry/tools/DeleteTldCommand.java#L83)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

We need to standardize on how we're making this determination across the entire codebase (not in this PR).  I don't think this is 100% right.
</blockquote></details>

Ugh yeah you're right, I keep forgetting. We should use the `isDatastore` method everywhere, not `TM::isOfy` .

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/DeleteTldCommand.java, line 83 at r1](https://reviewable.io/reviews/google/nomulus/1029#-MWZna8i8oAxB2WRIMHk:-MWakIGs6DR8G_u3zghs:b-zf1pux) ([raw file](https://github.com/google/nomulus/blob/68cb36388e368c0c81532bfadd08fe49dc88be1c/core/src/main/java/google/registry/tools/DeleteTldCommand.java#L83)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Ugh yeah you're right, I keep forgetting. We should use the `isDatastore` method everywhere, not `TM::isOfy` . 
</blockquote></details>

Actually after thinking about it more, I've reversed my position. For replayed entities, we should generally use `isOfy` because that means that we will get the same behavior as all of the raw `tm()` calls. 

That is, we won't be able to shift the general `tm()` calls at runtime so it would just create ambiguity to have the runtime switch for these entity types.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/server/ListReservedListsAction.java, line 53 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWez76PEt8N-nYKfwQD:-MWez76PEt8N-nYKfwQE:b-4c6dqv) ([raw file](https://github.com/google/nomulus/blob/2988e79bc2fff295757a143e065e8abe231f2eeb/core/src/main/java/google/registry/tools/server/ListReservedListsAction.java#L53)):*
> ```Java
>     return transactIfJpaTm(
>         () ->
>             tm().loadAllOf(ReservedList.class).stream()
> ```

This isn't the same as the Datastore version.  The Datastore version uses an ancestor query, whereas this is a non-ancestor query.  I think you'll have to branch it.  The key distinction is that an ancestor query has strong consistency, whereas a non-ancestor query has eventual consistency.  We don't want to downgrade from the former to the latter in our current serving path.  This concern applies fairly generally across different callsites in this PR (I won't comment on them all individually).

Alternatively, you can make a different version of `loadAllOf()` that should be called only for queries in the cross-TLD entity group (e.g. this one) that will automatically apply the cross-tld ancestor query on the Datastore branch (and just delegate to `loadAllOf` on the JPA branch, because this concern isn't relevant there).

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/server/ListReservedListsAction.java, line 53 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWez76PEt8N-nYKfwQD:-MWf0UAf0jCo9Afco-kV:b-2o9sbv) ([raw file](https://github.com/google/nomulus/blob/2988e79bc2fff295757a143e065e8abe231f2eeb/core/src/main/java/google/registry/tools/server/ListReservedListsAction.java#L53)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This isn't the same as the Datastore version.  The Datastore version uses an ancestor query, whereas this is a non-ancestor query.  I think you'll have to branch it.  The key distinction is that an ancestor query has strong consistency, whereas a non-ancestor query has eventual consistency.  We don't want to downgrade from the former to the latter in our current serving path.  This concern applies fairly generally across different callsites in this PR (I won't comment on them all individually).

Alternatively, you can make a different version of `loadAllOf()` that should be called only for queries in the cross-TLD entity group (e.g. this one) that will automatically apply the cross-tld ancestor query on the Datastore branch (and just delegate to `loadAllOf` on the JPA branch, because this concern isn't relevant there).
</blockquote></details>

Another alternative could be to add a `list` method to the ReservedList (and others) DAO object(s), which is essentially branching.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/server/ListReservedListsAction.java, line 53 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWez76PEt8N-nYKfwQD:-MWf2KqD2P2-bL-DoxPL:bon34r0) ([raw file](https://github.com/google/nomulus/blob/2988e79bc2fff295757a143e065e8abe231f2eeb/core/src/main/java/google/registry/tools/server/ListReservedListsAction.java#L53)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Another alternative could be to add a `list` method to the ReservedList (and others) DAO object(s), which is essentially branching. 
</blockquote></details>

See PR #1040. Unfortunately the DAO approach doesn't work because not all of these entities have DAOs.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/server/ListReservedListsAction.java, line 53 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWez76PEt8N-nYKfwQD:-MWfABHP1_rxcljkhZ1_:b-2ihr81) ([raw file](https://github.com/google/nomulus/blob/2988e79bc2fff295757a143e065e8abe231f2eeb/core/src/main/java/google/registry/tools/server/ListReservedListsAction.java#L53)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

See PR #1040. Unfortunately the DAO approach doesn't work because not all of these entities have DAOs.
</blockquote></details>

gotcha -- the DAO method would work but it would require coding it up separately for each and every class

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/server/ListReservedListsAction.java, line 53 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWez76PEt8N-nYKfwQD:-MWfAXCt9QMF7OGdIzqn:b-ahx19l) ([raw file](https://github.com/google/nomulus/blob/2988e79bc2fff295757a143e065e8abe231f2eeb/core/src/main/java/google/registry/tools/server/ListReservedListsAction.java#L53)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

gotcha -- the DAO method would work but it would require coding it up separately for each and every class 
</blockquote></details>

We don't have DAOs for every relevant class and not all interactions go through DAOs.  That approach wouldn't work.

Anyway, we shouldn't submit this PR until #1040 goes in, as it's not safe until then.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[core/src/main/java/google/registry/tools/server/ListReservedListsAction.java, line 53 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWez76PEt8N-nYKfwQD:-MWfaO6aEvf4zUJbsZoi:bqug82z) ([raw file](https://github.com/google/nomulus/blob/2988e79bc2fff295757a143e065e8abe231f2eeb/core/src/main/java/google/registry/tools/server/ListReservedListsAction.java#L53)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

We don't have DAOs for every relevant class and not all interactions go through DAOs.  That approach wouldn't work.

Anyway, we shouldn't submit this PR until #1040 goes in, as it's not safe until then.
</blockquote></details>

OK, PR #1040 is merged, resolving this.  Sync to HEAD and this should work fine.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/server/ListReservedListsAction.java, line 53 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWez76PEt8N-nYKfwQD:-MWfaV5q6cUfkOc-TSFj:b-fzwysl) ([raw file](https://github.com/google/nomulus/blob/2988e79bc2fff295757a143e065e8abe231f2eeb/core/src/main/java/google/registry/tools/server/ListReservedListsAction.java#L53)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

OK, PR #1040 is merged, resolving this.  Sync to HEAD and this should work fine.
</blockquote></details>

Sweet, should be all set then.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/tools/server/ListReservedListsAction.java, line 55 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWfaaOf9IB9bsnIrBud:-MWfaaOgB8rPs5dMc2Vm:bfvqsha) ([raw file](https://github.com/google/nomulus/blob/2c8529d3654c8ad82c864b4bd9427fb0ccdcb310/core/src/main/java/google/registry/tools/server/ListReservedListsAction.java#L55)):*
> ```Java
>             tm().loadAllOf(ReservedList.class).stream()
>                 .map(ReservedList::getName)
>                 .distinct()
> ```

`distinct()` isn't necessary; the reserved list name is its primary key so there can't be duplicates.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/tools/server/ListPremiumListsAction.java, line 58 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWfarnVCGA7qjpcmCeS:-MWfarnW11vXkOriCLpR:b-h6a2k6) ([raw file](https://github.com/google/nomulus/blob/2c8529d3654c8ad82c864b4bd9427fb0ccdcb310/core/src/main/java/google/registry/tools/server/ListPremiumListsAction.java#L58)):*
> ```Java
>             tm().loadAllOf(PremiumList.class).stream()
>                 .map(PremiumList::getName)
>                 .distinct()
> ```

Same comment as below; not necessary.

**Review by CydeWeys — APPROVED** [review]
:lgtm: pending addressing the 2 small comments below.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029#-:-MWfb7nH33YEHRchphgf:b2tn54p)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @gbrodman)

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1029)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/tools/server/ListPremiumListsAction.java, line 58 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWfarnVCGA7qjpcmCeS:-MWfpXdLDaDslc5Snrs6:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2c8529d3654c8ad82c864b4bd9427fb0ccdcb310/core/src/main/java/google/registry/tools/server/ListPremiumListsAction.java#L58)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Same comment as below; not necessary.
</blockquote></details>

Done.
___
*[core/src/main/java/google/registry/tools/server/ListReservedListsAction.java, line 55 at r2](https://reviewable.io/reviews/google/nomulus/1029#-MWfaaOf9IB9bsnIrBud:-MWfpY4m0pO-E_OTsA2g:b-896fix) ([raw file](https://github.com/google/nomulus/blob/2c8529d3654c8ad82c864b4bd9427fb0ccdcb310/core/src/main/java/google/registry/tools/server/ListReservedListsAction.java#L55)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`distinct()` isn't necessary; the reserved list name is its primary key so there can't be duplicates.
</blockquote></details>

Done.

**Pull request merged**
