### PR TITLE
Add deprecation message to old console

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2516)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2516)* status: 0 of 50 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/javascript/google/registry/ui/css/registry.css` line 300 at r2](https://reviewable.io/reviews/google/nomulus/2516#-O3ET5fH6a08rRkn_XHS:-O3ET5fH6a08rRkn_XHT:b1ukqq) ([raw file](https://github.com/google/nomulus/blob/9b74d430a9ee2a0808f428641062f1cd8351761d/core/src/main/javascript/google/registry/ui/css/registry.css#L300)):*
> ```CSS
> }
> 
> div#reg-deprecation-warning {
> ```

Media query that I sent you is missing. Without it - it fails on a different screen dimensions

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2516)* status: 0 of 50 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`core/src/main/javascript/google/registry/ui/css/registry.css` line 300 at r2](https://reviewable.io/reviews/google/nomulus/2516#-O3ET5fH6a08rRkn_XHS:-O3EWcD8C1krsbn6-Ken:b-52p0bv) ([raw file](https://github.com/google/nomulus/blob/9b74d430a9ee2a0808f428641062f1cd8351761d/core/src/main/javascript/google/registry/ui/css/registry.css#L300)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Media query that I sent you is missing. Without it - it fails on a different screen dimensions
</blockquote></details>

yeah, i wasn't incredibly happy about the font sizing but it's fine either way. Changed.

**Review by ptkach — COMMENTED** [review]
> Reviewed 4 of 49 files at r1, 1 of 2 files at r2, 2 of 39 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2516)* status: 7 of 50 files reviewed, all discussions resolved

**Review by ptkach — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2516)* status: 7 of 50 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/resources/google/registry/ui/soy/registrar/Console.soy` line 0 at r3](https://reviewable.io/reviews/google/nomulus/2516#-O3IWQpmB0jUdQAHzKVH:-O3IWQpmB0jUdQAHzKVI:b-qmqdag) ([raw file](https://github.com/google/nomulus/blob/f30c34e99a0c0b1ba9da3975108515436346a88c/core/src/main/resources/google/registry/ui/soy/registrar/Console.soy#L0)):*
I just realized that it's not in sync with the NEW_CONSOLE feature flag, which means it's out of sync with the release.

**Review by ptkach — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2516)* status: 4 of 52 files reviewed, 1 unresolved discussion

**Pull request merged**
