### PR TITLE
Refactor / rename Billing object classes

### PR DESCRIPTION
**Pull request by gbrodman**
This includes renaming the billing classes to match the SQL table names,
as well as splitting them out into their own separate top-level classes.
The rest of the changes are mostly renaming variables and comments etc.

We now use `BillingBase` as the name of the common billing superclass,
because one-time events are called BillingEvents

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1993)

### CODE REVIEW

**Review by CydeWeys — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1993)* status: 0 of 66 files reviewed, 9 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml` line 84 at r2](https://reviewable.io/reviews/google/nomulus/1993#-NTUGJNc7RhO_deaNLoB:-NTUGJNc7RhO_deaNLoC:b-89a4l7) ([raw file](https://github.com/google/nomulus/blob/b6f2af5052c0294647c917bdcd56826909e9ce8e/core/src/main/java/google/registry/env/alpha/default/WEB-INF/cloud-scheduler-tasks.xml#L84)):*
> ```XML
>   <task>
>     <url><![CDATA[/_dr/task/expandRecurrences?advanceCursor]]></url>
>     <name>expandRecurrences</name>
> ```

Ditto
___
*[`core/src/main/java/google/registry/env/common/backend/WEB-INF/web.xml` line 249 at r2](https://reviewable.io/reviews/google/nomulus/1993#-NTUGATq-GlKZFOgPncI:-NTUGATq-GlKZFOgPncJ:b-w7cvge) ([raw file](https://github.com/google/nomulus/blob/b6f2af5052c0294647c917bdcd56826909e9ce8e/core/src/main/java/google/registry/env/common/backend/WEB-INF/web.xml#L249)):*
> ```XML
>   </servlet-mapping>
> 
>   
> ```

Comment should mention billing here.  The previous comment was more explanatory.

Also "OneTime" isn't correct anymore either, but perhaps out of scope.
___
*[`core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml` line 86 at r2](https://reviewable.io/reviews/google/nomulus/1993#-NTUGMnP50XQGHWe45np:-NTUGMnP50XQGHWe45nq:b-vptywd) ([raw file](https://github.com/google/nomulus/blob/b6f2af5052c0294647c917bdcd56826909e9ce8e/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L86)):*
> ```XML
>   <task>
>     <url><![CDATA[/_dr/task/expandRecurrences?advanceCursor]]></url>
>     <name>expandRecurrences</name>
> ```

Ditto ...
___
*[`core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml` line 89 at r2](https://reviewable.io/reviews/google/nomulus/1993#-NTUGQjy0T-1DIirOBMN:-NTUGQjy0T-1DIirOBMO:bj3z3z9) ([raw file](https://github.com/google/nomulus/blob/b6f2af5052c0294647c917bdcd56826909e9ce8e/core/src/main/java/google/registry/env/sandbox/default/WEB-INF/cloud-scheduler-tasks.xml#L89)):*
> ```XML
>     <description>
>       This job runs an action that creates synthetic OneTime billing events from Recurrence billing
>       events. Events are created for all instances of Recurrence billing events that should exist
> ```

Terminology issue here.  A billing recurrence isn't a billing event, it is the set of data that yields individual instantations of `BillingEvent`s (an actual event that does have an associated event time).  So there's billing recurrences, and billing events.  Not billing recurrence events.
___
*[`core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java` line 383 at r2](https://reviewable.io/reviews/google/nomulus/1993#-NTUGo8J8xclMjGRpdyu:-NTUGo8J8xclMjGRpdyv:b-sush3c) ([raw file](https://github.com/google/nomulus/blob/b6f2af5052c0294647c917bdcd56826909e9ce8e/core/src/main/java/google/registry/flows/domain/DomainCheckFlow.java#L383)):*
> ```Java
>     return tm().transact(
>             () -> {
>               ImmutableMap<VKey<? extends Recurrence>, Recurrence> recurrences =
> ```

I dunno, I think `BillingEvent.Recurrence` is more clear than just `Recurrence`.  Also note that we'll subsequently need to rename the `BillingEvent` class, as per our schema, a `OneTime` is what should be the actual `BillingEvent`, and the existing base `BillingEvent` class should be renamed to something else, maybe `BillingObject`.
___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 363 at r2](https://reviewable.io/reviews/google/nomulus/1993#-NTUHMPI2qkJYVvPai9W:-NTUHMPI2qkJYVvPai9X:bqvv51d) ([raw file](https://github.com/google/nomulus/blob/b6f2af5052c0294647c917bdcd56826909e9ce8e/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L363)):*
> ```Java
>             now);
>     // Create a new autorenew billing event and poll message starting at the expiration time.
>     Recurrence autorenewBillingEvent =
> ```

Again, I think this would work better as `BillingEvent.Recurrence` (or `Billing.Recurrence` or `BillingObject.Recurrence` following the subsequent refactor), though maybe even better would simply be to name this class `BillingRecurrence` so it has exactly the same name as its table.  I might actually prefer that.

Anyway, it probably would have been better to nail down all of the proposed names prior to doing all the work in this PR, as you are going to have some reworking to do :(

I think I might prefer `BillingRecurrence` as the name the most, as having the exact same name as the table in the schema seems ideal.  And just seeing `Recurrence` in isolation doesn't mean that much.

Anyway I'll stop reviewing the PR here as it seems like there will be a lot more changes to everything.
___
*[`core/src/main/java/google/registry/batch/ExpandRecurrencesAction.java` line 56 at r2](https://reviewable.io/reviews/google/nomulus/1993#-NTUFQIbDcaFseyRra-T:-NTUFQIbDcaFseyRra-U:b-qjri2z) ([raw file](https://github.com/google/nomulus/blob/b6f2af5052c0294647c917bdcd56826909e9ce8e/core/src/main/java/google/registry/batch/ExpandRecurrencesAction.java#L56)):*
> ```Java
>     path = "/_dr/task/expandRecurrences",
>     auth = Auth.AUTH_INTERNAL_OR_ADMIN)
> public class ExpandRecurrencesAction implements Runnable {
> ```

A better name for this might be `ExpandBillingRecurrencesAction`.  It's not immediately clear out of context what it's referring to without putting the word `Billing` in there.
___
*[`core/src/main/java/google/registry/beam/billing/ExpandRecurrencesPipeline.java` line 121 at r2](https://reviewable.io/reviews/google/nomulus/1993#-NTUFiueAIOxr0KeXO_w:-NTUFiueAIOxr0KeXO_x:b-h15lwc) ([raw file](https://github.com/google/nomulus/blob/b6f2af5052c0294647c917bdcd56826909e9ce8e/core/src/main/java/google/registry/beam/billing/ExpandRecurrencesPipeline.java#L121)):*
> ```Java
>  *     Flex Templates</a>
>  */
> public class ExpandRecurrencesPipeline implements Serializable {
> ```

Same comment re: name of pipeline as above.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1993)* status: 0 of 66 files reviewed, 9 unresolved discussions (waiting on @CydeWeys and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java` line 363 at r2](https://reviewable.io/reviews/google/nomulus/1993#-NTUHMPI2qkJYVvPai9W:-NTUm96kAQcYdV3gsIGY:b-y1g65c) ([raw file](https://github.com/google/nomulus/blob/b6f2af5052c0294647c917bdcd56826909e9ce8e/core/src/main/java/google/registry/flows/domain/DomainCreateFlow.java#L363)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Again, I think this would work better as `BillingEvent.Recurrence` (or `Billing.Recurrence` or `BillingObject.Recurrence` following the subsequent refactor), though maybe even better would simply be to name this class `BillingRecurrence` so it has exactly the same name as its table.  I might actually prefer that.

Anyway, it probably would have been better to nail down all of the proposed names prior to doing all the work in this PR, as you are going to have some reworking to do :(

I think I might prefer `BillingRecurrence` as the name the most, as having the exact same name as the table in the schema seems ideal.  And just seeing `Recurrence` in isolation doesn't mean that much.

Anyway I'll stop reviewing the PR here as it seems like there will be a lot more changes to everything.
</blockquote></details>

yeah, maybe the way to do it is to have a BillingObject superclass with the subclass names changed to match the table names

**Comment by gbrodman** [comment]
removing as reviewer so as to not spam you

**Review by gbrodman — COMMENTED** [review]
I think this should be good to go for another round -- it's a more thorough renaming and refactoring of the billing classes 

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1993#-:-NToZ_m9Do_vv99S8FpM:bmvwbi4)* status: 0 of 98 files reviewed, 13 unresolved discussions (waiting on @CydeWeys and @github-code-scanning[bot])

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1993)* status: 0 of 98 files reviewed, 8 unresolved discussions (waiting on @gbrodman and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/model/billing/BillingCancellation.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1993#gh-1173923244:-NU35yo3BitPGGwi_fjc:b41f94r) ([raw file](https://github.com/google/nomulus/blob/b66af06f0f59acf2796050169770f71188340bdc/core/src/main/java/google/registry/model/billing/BillingCancellation.java#L39)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## No clone method

No clone method, yet implements Cloneable.

[Show more details](https://github.com/google/nomulus/security/code-scanning/788)
</blockquote></details>

Any idea why `Cloneable` is coming into play here?
___
*[`core/src/test/java/google/registry/beam/billing/InvoicingPipelineTest.java` line 92 at r5](https://reviewable.io/reviews/google/nomulus/1993#-NU36Vl2-J90EmtOyU_d:-NU36Vl2-J90EmtOyU_e:b-ojzgmm) ([raw file](https://github.com/google/nomulus/blob/6dde2f929c0ef56128b138795ed46da9ca64ee5e/core/src/test/java/google/registry/beam/billing/InvoicingPipelineTest.java#L92)):*
> ```Java
>   private static final String INVOICE_FILE_PREFIX = "REG-INV";
> 
>   private static final ImmutableList<google.registry.beam.billing.BillingEvent> INPUT_EVENTS =
> ```

Tis a shame that using the fully qualified class name here becomes necessary.
___
*[`core/src/main/java/google/registry/batch/ExpandBillingRecurrencesAction.java` line 136 at r5](https://reviewable.io/reviews/google/nomulus/1993#-NU34mmx0M84BLK94j2X:-NU34mmx0M84BLK94j2Y:b-92l1w0) ([raw file](https://github.com/google/nomulus/blob/6dde2f929c0ef56128b138795ed46da9ca64ee5e/core/src/main/java/google/registry/batch/ExpandBillingRecurrencesAction.java#L136)):*
> ```Java
>                     .build());
>     logger.atInfo().log(
>         "Launching recurrence expansion pipeline for event time range [%s, %s)%s.",
> ```

`billing recurrence`
___
*[`core/src/main/java/google/registry/batch/ExpandBillingRecurrencesAction.java` line 155 at r5](https://reviewable.io/reviews/google/nomulus/1993#-NU34ot9BizmD8xofdFx:-NU34ot9BizmD8xofdFy:b-92l1w0) ([raw file](https://github.com/google/nomulus/blob/6dde2f929c0ef56128b138795ed46da9ca64ee5e/core/src/main/java/google/registry/batch/ExpandBillingRecurrencesAction.java#L155)):*
> ```Java
>       response.setPayload(
>           String.format(
>               "Launched recurrence expansion pipeline: %s", launchResponse.getJob().getId()));
> ```

`billing recurrence`

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1993)* status: 0 of 98 files reviewed, 8 unresolved discussions (waiting on @CydeWeys and @github-code-scanning[bot])

___
*[`core/src/main/java/google/registry/model/billing/BillingCancellation.java` line 39 at r3](https://reviewable.io/reviews/google/nomulus/1993#gh-1173923244:-NU3GWns1wLjRHHcxE1N:b-ff9xxl) ([raw file](https://github.com/google/nomulus/blob/b66af06f0f59acf2796050169770f71188340bdc/core/src/main/java/google/registry/model/billing/BillingCancellation.java#L39)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Any idea why `Cloneable` is coming into play here?
</blockquote></details>

ImmutableObject implements Cloneable so I guess because I'm modifying the name of this class it flags that ImmutableObject doesn't actually implement a standard straight-up clone method? 

It's definitely not relevant to this PR at least
___
*[`core/src/test/java/google/registry/beam/billing/InvoicingPipelineTest.java` line 92 at r5](https://reviewable.io/reviews/google/nomulus/1993#-NU36Vl2-J90EmtOyU_d:-NU3IoveBoafRsFHlymJ:b-vydiud) ([raw file](https://github.com/google/nomulus/blob/6dde2f929c0ef56128b138795ed46da9ca64ee5e/core/src/test/java/google/registry/beam/billing/InvoicingPipelineTest.java#L92)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Tis a shame that using the fully qualified class name here becomes necessary.
</blockquote></details>

yaaaaaaaaaay name collisions
___
*[`core/src/main/java/google/registry/batch/ExpandBillingRecurrencesAction.java` line 136 at r5](https://reviewable.io/reviews/google/nomulus/1993#-NU34mmx0M84BLK94j2X:-NU3G8J39Sm3Qf5HGEUW:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6dde2f929c0ef56128b138795ed46da9ca64ee5e/core/src/main/java/google/registry/batch/ExpandBillingRecurrencesAction.java#L136)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`billing recurrence`
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/batch/ExpandBillingRecurrencesAction.java` line 155 at r5](https://reviewable.io/reviews/google/nomulus/1993#-NU34ot9BizmD8xofdFx:-NU3G7ufATAB-IHEojx5:b-896fix) ([raw file](https://github.com/google/nomulus/blob/6dde2f929c0ef56128b138795ed46da9ca64ee5e/core/src/main/java/google/registry/batch/ExpandBillingRecurrencesAction.java#L155)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`billing recurrence`
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1993#-:-NU7yBsC5lNjFUG4q7Ii:bnfp4nl)* status: 0 of 98 files reviewed, 6 unresolved discussions (waiting on @github-code-scanning[bot])

**Pull request merged**
