### PR TITLE
Set up a unified registry servlet for Jetty

### PR DESCRIPTION
**Pull request by jianglai**
This PR creates a unified RegistryServlet that will serve all
non-console traffic. It also creates a jetty subproject that allows one
to run Nomulus on top of a standard Jetty 12 runtime.

`./gradlew :jetty:stage` will create a jetty base folder at
`jetty/build/jetty-base` where one is able spin up a local Nomulus server
by running the following command inside the folder:

```bash
java -jar ${JETTY_HOME}/start.jar
```

`JETTY_HOME` is a folder where the [Jetty runtime](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/12.0.6/jetty-home-12.0.6.zip) is located.

This PR also adds a Gradle task to create a Nomulus image based on the
official Jetty image:

```bash
./gradlew :jetty:buildNomulusImage
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2338)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 34 of 34 files at r1, 17 of 17 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by jianglai — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2338)* status: 36 of 37 files reviewed, all discussions resolved (waiting on @ptkach)

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 15 of 34 files at r1, 1 of 17 files at r2, 2 of 2 files at r3, 1 of 1 files at r5, 5 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2338)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 55 at r8](https://reviewable.io/reviews/google/nomulus/2338#-NrpLl226rC0LBNR9cVI:-NrpLl226rC0LBNR9cVJ:b-8d7y0g) ([raw file](https://github.com/google/nomulus/blob/37fd5b7c511431f0967b802df7ab93e1cc520575/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L55)):*
> ```Java
> 
>   @Provides
>   @Parameter("consoleClientId")
> ```

What is the reason to prepend this and the rest at the bottom with the world "console"? I mean, nothing stops us from having a parameter "clientId" or "domain" in console api and registry api for example, but since it's a request scope limited anyway there's no harm to it as far as I can tell as unlikely there will be a naming conflict within one request. 



_Code quote:_
```Java
consoleClientId
```
___
*[`jetty/build.gradle` line 47 at r8](https://reviewable.io/reviews/google/nomulus/2338#-NrpTkeUDUCQhhnJDGr0:-NrpTkeUDUCQhhnJDGr1:b-6n6fbs) ([raw file](https://github.com/google/nomulus/blob/37fd5b7c511431f0967b802df7ab93e1cc520575/jetty/build.gradle#L47)):*
> ```Gradle
> }
> 
> tasks.register('buildNomulusImage', Exec) {
> ```

Works like a charm. The only thing - I'd add another task to run a container, that will run docker map ports and potentially in the future kick off a local db instance.

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2338)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java` line 55 at r8](https://reviewable.io/reviews/google/nomulus/2338#-NrpLl226rC0LBNR9cVI:-NrpV8b62G95vZMoK3nE:bc810lo) ([raw file](https://github.com/google/nomulus/blob/37fd5b7c511431f0967b802df7ab93e1cc520575/core/src/main/java/google/registry/ui/server/registrar/RegistrarConsoleModule.java#L55)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

What is the reason to prepend this and the rest at the bottom with the world "console"? I mean, nothing stops us from having a parameter "clientId" or "domain" in console api and registry api for example, but since it's a request scope limited anyway there's no harm to it as far as I can tell as unlikely there will be a naming conflict within one request.
</blockquote></details>

The problem is that there are two modules providing the same binding. Before, these two modules were installed in two different components (frontend vs backend, for example). In order to have one servlet serving all routes, I installed all modules in the new component, which resulted in the conflict. Giving the bindings different names is the easiest way to fix the conflict. Also, at this point the old console is considered abandonware so I'm not super worried about making it a bit messy.
___
*[`jetty/build.gradle` line 47 at r8](https://reviewable.io/reviews/google/nomulus/2338#-NrpTkeUDUCQhhnJDGr0:-NrpX2591Ce5EM6GW6G2:bkdohjh) ([raw file](https://github.com/google/nomulus/blob/37fd5b7c511431f0967b802df7ab93e1cc520575/jetty/build.gradle#L47)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Works like a charm. The only thing - I'd add another task to run a container, that will run docker map ports and potentially in the future kick off a local db instance.
</blockquote></details>

Yes, I have a follow up PR on this.

**Review by ptkach — APPROVED** [review]
> Reviewed 2 of 34 files at r1, 8 of 17 files at r2, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2338)* status: all files reviewed, 1 unresolved discussion (waiting on @jianglai)

**Pull request merged**
