### PR TITLE
Remove AppEngineExtnesion

### PR DESCRIPTION
**Pull request by jianglai**
Most of its usage can be replaced by JpaIntegrationTestExtension. In
places where specific GAE APIs are still needed, namely when pull queue
or the User service is used, two simplifed extensions are used, which
makes them much easier to identify when the APIs are no longer used.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1905)

### CODE REVIEW

**Review by jianglai — COMMENTED** [review]
> Reviewed 171 of 171 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1905)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1905)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Review by ptkach — COMMENTED** [review]
> Reviewed 168 of 171 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1905)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

___
*[`core/src/test/java/google/registry/testing/TaskQueueExtension.java` line 62 at r4](https://reviewable.io/reviews/google/nomulus/1905#-NLbv7Zi4kOZ6nm70koc:-NLbv7Zi4kOZ6nm70kod:b6qerqh) ([raw file](https://github.com/google/nomulus/blob/3c0a15fa59ece31be16eb9e3e187e1c2f6d810c7/core/src/test/java/google/registry/testing/TaskQueueExtension.java#L62)):*
> ```Java
>   public void afterEach(ExtensionContext context) throws Exception {
>     helper.tearDown();
>     ApiProxy.setEnvironmentForCurrentThread(null);
> ```

can you please elaborate on why do we need this? Since we no longer run it as ApEngine test instance I'm not sure it's needed. 
___
*[`core/src/test/java/google/registry/testing/UserServiceExtension.java` line 55 at r4](https://reviewable.io/reviews/google/nomulus/1905#-NLbvUFx6AKaeq0qfVTT:-NLbvUFx6AKaeq0qfVTU:b-ya81ng) ([raw file](https://github.com/google/nomulus/blob/3c0a15fa59ece31be16eb9e3e187e1c2f6d810c7/core/src/test/java/google/registry/testing/UserServiceExtension.java#L55)):*
> ```Java
>   public void afterEach(ExtensionContext context) throws Exception {
>     helper.tearDown();
>     ApiProxy.setEnvironmentForCurrentThread(null);
> ```

Same as above

**Review by jianglai — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1905)* status: all files reviewed, 2 unresolved discussions (waiting on @ptkach)

___
*[`core/src/test/java/google/registry/testing/TaskQueueExtension.java` line 62 at r4](https://reviewable.io/reviews/google/nomulus/1905#-NLbv7Zi4kOZ6nm70koc:-NLbzEAbAgirHSL5dEeA:bx9pc6d) ([raw file](https://github.com/google/nomulus/blob/3c0a15fa59ece31be16eb9e3e187e1c2f6d810c7/core/src/test/java/google/registry/testing/TaskQueueExtension.java#L62)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

can you please elaborate on why do we need this? Since we no longer run it as ApEngine test instance I'm not sure it's needed. 
</blockquote></details>

The `LocalServiceTestHelper.setUp()` call in `beforeEach` would set the environment to true, otherwise any App Engine API calls would fail before being intercepted by the local emulator.
___
*[`core/src/test/java/google/registry/testing/UserServiceExtension.java` line 55 at r4](https://reviewable.io/reviews/google/nomulus/1905#-NLbvUFx6AKaeq0qfVTT:-NLbzS5YCVVEZp3UkEL_:b-816h6l) ([raw file](https://github.com/google/nomulus/blob/3c0a15fa59ece31be16eb9e3e187e1c2f6d810c7/core/src/test/java/google/registry/testing/UserServiceExtension.java#L55)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Same.

**Review by ptkach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1905)* status: all files reviewed, 2 unresolved discussions (waiting on @jianglai)

**Pull request merged**
