### PR TITLE
Convert CountDomainsCommand to tm

### PR DESCRIPTION
**Pull request by mindhog**
As part of this, implement "select count(*)" queries in the QueryComposer.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1092)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1092)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 419 at r1](https://reviewable.io/reviews/google/nomulus/1092#-MYem13c2TBJrDJV8tHS:-MYem13c2TBJrDJV8tHT:b-2xb6pj) ([raw file](https://github.com/google/nomulus/blob/994e5bce28896bfb5af7ec644712827a9e85d29b/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L419)):*
> ```Java
>     @Override
>     public long count() {
>       return Iterables.size(buildQuery().chunkAll().keys());
> ```

This is a surprising implementation to me.  Why aren't you calling Objectify's `.count()`?
___
*[core/src/main/java/google/registry/persistence/transaction/QueryComposer.java, line 95 at r1](https://reviewable.io/reviews/google/nomulus/1092#-MYemFVeEcOm9lRs3W5w:-MYemFVeEcOm9lRs3W5x:b-d4idl7) ([raw file](https://github.com/google/nomulus/blob/994e5bce28896bfb5af7ec644712827a9e85d29b/core/src/main/java/google/registry/persistence/transaction/QueryComposer.java#L95)):*
> ```Java
>    *
>    * <p>While this is implemented optimally in JPA (by building a "count" query), note that in
>    * datastore it will actually obtain all of the keys matched by the query.
> ```

I'm not sure this is necessary if we use Datastore correctly.

**Review by CydeWeys — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1092)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 419 at r1](https://reviewable.io/reviews/google/nomulus/1092#-MYem13c2TBJrDJV8tHS:-MYjXV-vDrsqNFYrWK7b:bdk8k4v) ([raw file](https://github.com/google/nomulus/blob/994e5bce28896bfb5af7ec644712827a9e85d29b/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L419)):*
<details><summary><i>Previously, mindhog (Michael Muller) wrote…</i></summary><blockquote>

Because I stole this from the implementation in CountDomainsCommand, assuming that Query does not support count().  Fixed.

There was no comment at that callsite, I have to wonder if there was some good reason for this.  In any case, it [sounds like count() is still going to suck on Datastore](https://groups.google.com/g/objectify-appengine/c/fJ323l7lsqg)
</blockquote></details>

There probably was a good reason for it in that particular case of `CountDomainsCommand`, but I don't know if it applies anymore and regardless I don't remember what it was.  In the general case using `.count()` is gonna be better.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1092#-:-MYjXkpK-YUKSF13AWS1:bnfp4nl)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @gbrodman and @mindhog)

**Review by mindhog — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1092)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java, line 419 at r1](https://reviewable.io/reviews/google/nomulus/1092#-MYem13c2TBJrDJV8tHS:-MYjhnQbAmFzKqIZAx6c:b-3nytmq) ([raw file](https://github.com/google/nomulus/blob/994e5bce28896bfb5af7ec644712827a9e85d29b/core/src/main/java/google/registry/model/ofy/DatastoreTransactionManager.java#L419)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

There probably was a good reason for it in that particular case of `CountDomainsCommand`, but I don't know if it applies anymore and regardless I don't remember what it was.  In the general case using `.count()` is gonna be better.
</blockquote></details>

Yeah, much better to do the counting in datastore than here.

**Pull request merged**
