### PR TITLE
Add registry lock ui

### PR DESCRIPTION
**Pull request by ptkach**
This should cover it, although I'm not sure how to properly test it, please advise. I will go and make another PR with table join to get isLocked on the domain in response.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2500)

### CODE REVIEW

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2500)* status: all files reviewed, 8 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/domains/domainList.component.html` line 104 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2Vei8U9nGAC8Y8QVoh:-O2Vei8V1bcdnXpkxRNg:b-4i5jqg) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/domainList.component.html#L104)):*
> ```HTML
> 
>             <ng-container matColumnDef="registryLock">
>               <mat-header-cell *matHeaderCellDef>Registry Lock</mat-header-cell>
> ```

maybe "Registry-Locked"? Or something to indicate that this is displaying whether or not the domain in question is locked. Maybe just "Locked"? 
___
*[`console-webapp/src/app/domains/domainList.component.scss` line 35 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2Vd7rD2cfNgZ2ess6S:-O2Vd7rD2cfNgZ2ess6T:b-4ks7x) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/domainList.component.scss#L35)):*
> ```SCSS
>     .mat-column-actions {
>       max-width: 100px;
>       // mat-icon {
> ```

any point to keeping this commented-out code around?
___
*[`console-webapp/src/app/domains/domainList.component.ts` line 84 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VdFOF5cV9fLe7ri96:-O2VdFOF5cV9fLe7ri97:b-3yw6m4) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/domainList.component.ts#L84)):*
> ```XML
> 
>   openRegistryLock(domainName: string) {
>     console.log('>>> Domain Name', domainName);
> ```

nit, should remove console log
___
*[`console-webapp/src/app/domains/domainList.service.ts` line 96 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2Vg-DSBNSDT9w3FPOC:-O2Vg-DSBNSDT9w3FPOD:bk5ea8x) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/domainList.service.ts#L96)):*
> ```XML
>         complete: () => {
>           this.domainsList = this.domainsList.map((d) =>
>             d.domainName === domainName ? { ...d, isLocked } : d
> ```

what's this for? Put another way, why does the domain name need to change? 
___
*[`console-webapp/src/app/domains/registryLock.component.html` line 46 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VhlffDiGJZ1qkLfeN:-O2VhlffDiGJZ1qkLfeO:ba9f7fx) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/registryLock.component.html#L46)):*
> ```HTML
>       color="primary"
>       type="submit"
>       [disabled]="!unlockDomain.valid"
> ```

out of curiosity, when would this ever *not* be valid? 
___
*[`console-webapp/src/app/domains/registryLock.component.html` line 64 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VhQiuAOqyE9qCHKdy:-O2VhQiuAOqyE9qCHKdz:b-oqqytu) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/registryLock.component.html#L64)):*
> ```HTML
>       <mat-icon>priority_high</mat-icon>The lock will not take effect until you
>       click the confirmation link that will be emailed to you. When it takes
>       effect, you will be billed the standard server status change billing cost.
> ```

So actually we (apparently) have a separate field for this on the TLD object, called the "registryLockOrUnlockBillingCost". We should probably refer to that field instead here and when unlocking a domain 

(I recognize that this is written incorrectly in the old console) 
___
*[`console-webapp/src/app/domains/registryLock.component.ts` line 60 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VfT7f-B2XCIslcOkF:-O2VfT7f-B2XCIslcOkG:bt073q3) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/registryLock.component.ts#L60)):*
> ```XML
> 
>   save(isLock: boolean) {
>     if (!isLock) {
> ```

do we even need the if statement here? we can just always pass undefined as the relockDuration if it's a lock action 
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 180 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VdqXY6G6ab0eG7Pxw:-O2VdqXY6G6ab0eG7Pxx:bjezx4z) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/shared/services/backend.service.ts#L180)):*
> ```XML
>     isLock: boolean
>   ) {
>     return this.http.post('/console-api/registry-lock', {
> ```

Did you test this? I don't think this will work as is, `isLock` isn't used

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2500)* status: 5 of 12 files reviewed, 8 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/domains/domainList.component.html` line 104 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2Vei8U9nGAC8Y8QVoh:-O2WHCWk4SDwEUphkPdL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/domainList.component.html#L104)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

maybe "Registry-Locked"? Or something to indicate that this is displaying whether or not the domain in question is locked. Maybe just "Locked"?
</blockquote></details>

Done.
___
*[`console-webapp/src/app/domains/domainList.component.scss` line 35 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2Vd7rD2cfNgZ2ess6S:-O2WHCz3B-RT1DtVmwPp:bk9zwiz) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/domainList.component.scss#L35)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

any point to keeping this commented-out code around?
</blockquote></details>

Removed, I'm a little in rush to get this out of the door, so missed some minor clean up
___
*[`console-webapp/src/app/domains/domainList.component.ts` line 84 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VdFOF5cV9fLe7ri96:-O2WHJLUEr3uD9FV3zgH:b9y13mi) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/domainList.component.ts#L84)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

nit, should remove console log
</blockquote></details>

removed, same as above
___
*[`console-webapp/src/app/domains/domainList.service.ts` line 96 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2Vg-DSBNSDT9w3FPOC:-O2WHKlg-lM3VrrHEbVA:b4nso92) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/domainList.service.ts#L96)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what's this for? Put another way, why does the domain name need to change?
</blockquote></details>

It didn't change domain name, it changed isLocked for domains entity. 
Anyway this is now gone, I had a different plan in mind to table join Domains and RegistryLock on back-end, but eventually decided against it today. We have very limited amount of locks, so it'd be more performant to load them once per registrar upon visiting domains page and just render a column from it on ui. Back-end will remain unchanged with respect to registry-lock get endpoint.
___
*[`console-webapp/src/app/domains/registryLock.component.html` line 46 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VhlffDiGJZ1qkLfeN:-O2WHzoJ5lZ0reesCGl5:b6s7sht) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/registryLock.component.html#L46)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

out of curiosity, when would this ever *not* be valid?
</blockquote></details>

when password field is empty
___
*[`console-webapp/src/app/domains/registryLock.component.html` line 64 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VhQiuAOqyE9qCHKdy:-O2WIFcXBCqa-AdM0H85:bed13ii) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/registryLock.component.html#L64)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

So actually we (apparently) have a separate field for this on the TLD object, called the "registryLockOrUnlockBillingCost". We should probably refer to that field instead here and when unlocking a domain 

(I recognize that this is written incorrectly in the old console)
</blockquote></details>

We will make it a separate change
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 180 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VdqXY6G6ab0eG7Pxw:-O2WGcRn4qNwlamJMygo:b9ybukp) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/shared/services/backend.service.ts#L180)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Did you test this? I don't think this will work as is, `isLock` isn't used
</blockquote></details>

isLock added, but I've not tested, in fact current back-end implementation is incorrect. It should accept record instead of separate params. It will need to be updated separately

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2500)* status: all files reviewed, 5 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/domains/domainList.component.ts` line 94 at r2](https://reviewable.io/reviews/google/nomulus/2500#-O2WMAVi0RBCtU2yhZvI:-O2WMAVi0RBCtU2yhZvJ:b946qp9) ([raw file](https://github.com/google/nomulus/blob/92ceefbf03852514f023f5dafa7c506eebcb64c6/console-webapp/src/app/domains/domainList.component.ts#L94)):*
> ```XML
>     this.registryLockService
>       .retrieveLocks()
>       .subscribe({
> ```

if we have `retrieveLocks` accept as input an error handler function, I think we wouldn't have to do the subscribe / unsubscribe thing here, right? Then we could just call the passed-in error handler in the RegistryLockService?
___
*[`console-webapp/src/app/domains/domainList.component.ts` line 103 at r2](https://reviewable.io/reviews/google/nomulus/2500#-O2_wASI7rI2TZx0cc7E:-O2_wASI7rI2TZx0cc7F:b-1vu3l1) ([raw file](https://github.com/google/nomulus/blob/92ceefbf03852514f023f5dafa7c506eebcb64c6/console-webapp/src/app/domains/domainList.component.ts#L103)):*
> ```XML
> 
>   isDomainLocked(domainName: string) {
>     return this.registryLockService.domainsLocks.some(
> ```

grr i wish they'd use something like `anyMatch` like java 
___
*[`console-webapp/src/app/domains/registryLock.service.ts` line 57 at r2](https://reviewable.io/reviews/google/nomulus/2500#-O2_wWoN1qK45SDwT9Dw:-O2_wWoN1qK45SDwT9Dx:b-s6gt2f) ([raw file](https://github.com/google/nomulus/blob/92ceefbf03852514f023f5dafa7c506eebcb64c6/console-webapp/src/app/domains/registryLock.service.ts#L57)):*
> ```XML
>         relockDurationMillis,
>         this.registrarService.registrarId(),
>         isLocked
> ```

this should be `isLock`, not `isLocked` -- since it signifies the action we're trying to do
___
*[`console-webapp/src/app/domains/registryLock.service.ts` line 61 at r2](https://reviewable.io/reviews/google/nomulus/2500#-O2_wcg60-iPKXtgI5D1:-O2_wcg60-iPKXtgI5D2:b2p5bp7) ([raw file](https://github.com/google/nomulus/blob/92ceefbf03852514f023f5dafa7c506eebcb64c6/console-webapp/src/app/domains/registryLock.service.ts#L61)):*
> ```XML
>       .pipe(
>         tap(() => {
>           if (isLocked) {
> ```

I think this part may be unnecessary, since the lock/unlock isn't actually finalized until the verification? 

Am I correct in thinking that this block was meant to modify the displayed domain? 
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 180 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VdqXY6G6ab0eG7Pxw:-O2WLjpD70CT_Y_fXqk3:befbn2l) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/shared/services/backend.service.ts#L180)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

isLock added, but I've not tested, in fact current back-end implementation is incorrect. It should accept record instead of separate params. It will need to be updated separately
</blockquote></details>

what do you mean by incorrect? Do you mean just that it is not ideal, or that it is not functional? We use the individual params because the action handles both GET and POST requests.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2500)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/domains/domainList.component.ts` line 94 at r2](https://reviewable.io/reviews/google/nomulus/2500#-O2WMAVi0RBCtU2yhZvI:-O2aNtYE8fZIUygCNbUp:b3qfx0h) ([raw file](https://github.com/google/nomulus/blob/92ceefbf03852514f023f5dafa7c506eebcb64c6/console-webapp/src/app/domains/domainList.component.ts#L94)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

if we have `retrieveLocks` accept as input an error handler function, I think we wouldn't have to do the subscribe / unsubscribe thing here, right? Then we could just call the passed-in error handler in the RegistryLockService?
</blockquote></details>

Rxjs observable do not fire without a subscription, so without it the request won't happen.  I removed unsubscribe, I realized it's not needed
___
*[`console-webapp/src/app/domains/registryLock.component.ts` line 60 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VfT7f-B2XCIslcOkF:-O2aOuKi6Zw-aVl88KGI:bikep6d) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/domains/registryLock.component.ts#L60)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

do we even need the if statement here? we can just always pass undefined as the relockDuration if it's a lock action
</blockquote></details>

We can, it also uses different forms - this.lockDomains and this.unlockDomains, so that will need to be conditioned anyway. Given that it will be conditioned why not make it simple and have if/else?
___
*[`console-webapp/src/app/domains/registryLock.service.ts` line 57 at r2](https://reviewable.io/reviews/google/nomulus/2500#-O2_wWoN1qK45SDwT9Dw:-O2e8TI_9TMlBo2fTcbY:b-896fix) ([raw file](https://github.com/google/nomulus/blob/92ceefbf03852514f023f5dafa7c506eebcb64c6/console-webapp/src/app/domains/registryLock.service.ts#L57)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

this should be `isLock`, not `isLocked` -- since it signifies the action we're trying to do
</blockquote></details>

Done.
___
*[`console-webapp/src/app/domains/registryLock.service.ts` line 61 at r2](https://reviewable.io/reviews/google/nomulus/2500#-O2_wcg60-iPKXtgI5D1:-O2aPFByAPsSSLYi9a8B:ba9hctq) ([raw file](https://github.com/google/nomulus/blob/92ceefbf03852514f023f5dafa7c506eebcb64c6/console-webapp/src/app/domains/registryLock.service.ts#L61)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

I think this part may be unnecessary, since the lock/unlock isn't actually finalized until the verification? 

Am I correct in thinking that this block was meant to modify the displayed domain?
</blockquote></details>

You're right, removing this block. And yes it was meant to update ui after the request, without making another request to fetch current locks. 
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 180 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VdqXY6G6ab0eG7Pxw:-O2aPR1l2XFZCqZPRiq7:b-ajq6j6) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/shared/services/backend.service.ts#L180)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

what do you mean by incorrect? Do you mean just that it is not ideal, or that it is not functional? We use the individual params because the action handles both GET and POST requests.
</blockquote></details>

I mean that back-end doesn't extract data from the body the way you wrote it (try sending it in a body - it will fail), but from the query url. In most cases sending POST with data in a query is considered to be a bad practice, especially when part of said data is sensitive, like password - our case. That was the reason I used a record in epp password update action. In fact TS even complains about body being not present in post request

**Review by gbrodman — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2500)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 180 at r1](https://reviewable.io/reviews/google/nomulus/2500#-O2VdqXY6G6ab0eG7Pxw:-O2eifqq0XhGMyALbjWe:bajaiq5) ([raw file](https://github.com/google/nomulus/blob/b5078059df8795ae2d9257411a45a7760448f4fe/console-webapp/src/app/shared/services/backend.service.ts#L180)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I mean that back-end doesn't extract data from the body the way you wrote it (try sending it in a body - it will fail), but from the query url. In most cases sending POST with data in a query is considered to be a bad practice, especially when part of said data is sensitive, like password - our case. That was the reason I used a record in epp password update action. In fact TS even complains about body being not present in post request
</blockquote></details>

ugh yeah we should change that too. I'll do that, we can either change this in this PR after that goes in, or I can also change this code in that PR after this PR goes in

**Review by gbrodman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2500)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 182 at r3](https://reviewable.io/reviews/google/nomulus/2500#-O2etbspEEy_EV_WDpGu:-O2etbspEEy_EV_WDpGv:b-f6przj) ([raw file](https://github.com/google/nomulus/blob/910ffbc237f28a00e5a43d5172e8997ea7d40d68/console-webapp/src/app/shared/services/backend.service.ts#L182)):*
> ```XML
>     isLock: boolean
>   ) {
>     let url = `/console-api/registry-lock?registrarId=${registrarId}`;
> ```

https://github.com/google/nomulus/pull/2503 if this type of thing looks good, I can also change this `backend.service.ts` code to use it once this PR (#2500) goes through

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2500)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 182 at r3](https://reviewable.io/reviews/google/nomulus/2500#-O2etbspEEy_EV_WDpGu:-O2f6Pks8Fdj4wgDZum_:bqabgki) ([raw file](https://github.com/google/nomulus/blob/910ffbc237f28a00e5a43d5172e8997ea7d40d68/console-webapp/src/app/shared/services/backend.service.ts#L182)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

https://github.com/google/nomulus/pull/2503 if this type of thing looks good, I can also change this `backend.service.ts` code to use it once this PR (#2500) goes through
</blockquote></details>

I will wait for #2503 to merge, sync, update this one, test e2e and then merge this one

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2500)* status: all files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 182 at r3](https://reviewable.io/reviews/google/nomulus/2500#-O2etbspEEy_EV_WDpGu:-O2fND2T11zYYjM8iOTy:b-n6agl9) ([raw file](https://github.com/google/nomulus/blob/910ffbc237f28a00e5a43d5172e8997ea7d40d68/console-webapp/src/app/shared/services/backend.service.ts#L182)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I will wait for #2503 to merge, sync, update this one, test e2e and then merge this one
</blockquote></details>

sounds good, will wait for that

**Review by gbrodman — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2500)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

**Pull request merged**
