### PR TITLE
Add cc support to email service

### PR DESCRIPTION
**Pull request by rachelguan**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1230)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1230)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[util/src/main/java/google/registry/util/SendEmailService.java, line 82 at r1](https://reviewable.io/reviews/google/nomulus/1230#-MdcLhGN8fv9PyvoRcpQ:-MdcLhGN8fv9PyvoRcpR:bdzy6us) ([raw file](https://github.com/google/nomulus/blob/f07d87dbc6e828e8194f328db1b679c99f2bbc64/util/src/main/java/google/registry/util/SendEmailService.java#L82)):*
> ```Java
>           }
>           for (InternetAddress bcc : emailMessage.bccs()) {
>             msg.addRecipient(RecipientType.BCC, bcc);
> ```

Why not just change both of these to, instead of using a loop, call `msg.addRecipients(RecipientType.BCC, Iterables.toArray(emailMessage.bccs(), Address,class));`
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 90 at r1](https://reviewable.io/reviews/google/nomulus/1230#-MdcKZje8GGrLnUs3NID:-MdcKZje8GGrLnUs3NIE:b-u59uk1) ([raw file](https://github.com/google/nomulus/blob/f07d87dbc6e828e8194f328db1b679c99f2bbc64/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L90)):*
> ```Java
>   void testSuccess_emptyBcc() throws Exception {
>     EmailMessage content =
>         createBuilder().setBccs(ImmutableList.<InternetAddress>builder().build()).build();
> ```

Use `ImmutableList.<InternetAddress>of()` here.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 92 at r1](https://reviewable.io/reviews/google/nomulus/1230#-MdcL8Az-7zja9pE4WdG:-MdcL8Az-7zja9pE4WdH:b-l5j2x3) ([raw file](https://github.com/google/nomulus/blob/f07d87dbc6e828e8194f328db1b679c99f2bbc64/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L92)):*
> ```Java
>         createBuilder().setBccs(ImmutableList.<InternetAddress>builder().build()).build();
>     sendEmailService.sendEmail(content);
>     Message message = getMessage();
> ```

You can inline this as `assertThat(getMessage().....).....`

No need for the local variable unless you're referring to it multiple times, which you're not here.  (And yes I realize that this is pre-existing in other tests, but that's not a level of consistency you need to maintain.)
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 93 at r1](https://reviewable.io/reviews/google/nomulus/1230#-MdcLaXI5daCcZGjb8h2:-MdcLaXI5daCcZGjb8h3:bmuo09i) ([raw file](https://github.com/google/nomulus/blob/f07d87dbc6e828e8194f328db1b679c99f2bbc64/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L93)):*
> ```Java
>     sendEmailService.sendEmail(content);
>     Message message = getMessage();
>     assertThat(message.getRecipients(RecipientType.BCC)).isNull();
> ```

This passes?  Rather than returning an empty array as one would expect, javax's `message.getRecipients(...)` just returns `null`?  Ugh.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 115 at r1](https://reviewable.io/reviews/google/nomulus/1230#-MdcLQrqAMXOaifE37yQ:-MdcLQrqAMXOaifE37yR:bs4q9op) ([raw file](https://github.com/google/nomulus/blob/f07d87dbc6e828e8194f328db1b679c99f2bbc64/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L115)):*
> ```Java
>   void testSuccess_emptyCC() throws Exception {
>     EmailMessage content =
>         createBuilder().setCcs(ImmutableList.<InternetAddress>builder().build()).build();
> ```

Ditto.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1230)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 115 at r1](https://reviewable.io/reviews/google/nomulus/1230#-MdcLQrqAMXOaifE37yQ:-MdcT-jW0GuU4_7bDtKv:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f07d87dbc6e828e8194f328db1b679c99f2bbc64/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L115)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1230)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @CydeWeys, @gbrodman, and @rachelguan)

___
*[util/src/main/java/google/registry/util/SendEmailService.java, line 82 at r1](https://reviewable.io/reviews/google/nomulus/1230#-MdcLhGN8fv9PyvoRcpQ:-Me0pzh-AIWZNsTmwtwJ:b-94puxn) ([raw file](https://github.com/google/nomulus/blob/f07d87dbc6e828e8194f328db1b679c99f2bbc64/util/src/main/java/google/registry/util/SendEmailService.java#L82)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

did that to both bcc and cc. 
</blockquote></details>

You can also statically import `toArray()` if you want, should make this fit onto one line and be more readable.  (Easily accessible through the Alt-Enter menu in IntelliJ)
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 93 at r1](https://reviewable.io/reviews/google/nomulus/1230#-MdcLaXI5daCcZGjb8h2:-Me0qD8yAQXXd9lDVf_x:b-vhucov) ([raw file](https://github.com/google/nomulus/blob/f07d87dbc6e828e8194f328db1b679c99f2bbc64/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L93)):*
<details><summary><i>Previously, rachelguan (Rachel Guan) wrote…</i></summary><blockquote>

yep ..null point exception otherwise. 
</blockquote></details>

That's an obnoxious API.  Not your fault obviously.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 95 at r2](https://reviewable.io/reviews/google/nomulus/1230#-Me0qWlE4NIQizGz90T9:-Me0qWlE4NIQizGz90TA:bc1ehft) ([raw file](https://github.com/google/nomulus/blob/234726c0b2f5302cead35be37d88d70094865671/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L95)):*
> ```Java
> 
>   @Test
>   void testSuccess_cc() throws Exception {
> ```

Add another version of this test that uses `addCc()` (multiple times) rather than `setCcs()`.  As is you don't have complete test coverage over both methods of adding CCs.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1230)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 95 at r2](https://reviewable.io/reviews/google/nomulus/1230#-Me0qWlE4NIQizGz90T9:-Me184Ua7Z340DeDmI6a:b-896fix) ([raw file](https://github.com/google/nomulus/blob/234726c0b2f5302cead35be37d88d70094865671/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L95)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Add another version of this test that uses `addCc()` (multiple times) rather than `setCcs()`.  As is you don't have complete test coverage over both methods of adding CCs.
</blockquote></details>

Done.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1230)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @gbrodman and @rachelguan)

___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 74 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1GfRF35v4HHxVwFhm:-Me1GfRF35v4HHxVwFhn:bftsb8p) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L74)):*
> ```Java
>   @Test
>   void testSuccess_addBccs() throws Exception {
>     EmailMessage.Builder contentBuilder = EmailMessage.newBuilder();
> ```

This is a fluent API so you should combine these lines:

```
EmailMessage.Builder contentBuilder = EmailMessage.newBuilder()
    .setFrom(...)
    .setSubject(...)
    .setBody(...);
```

(formatting in that example might be off; do whatever auto-formatter does)
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 78 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1H-FN16LVtkGRASYe:-Me1H-FN16LVtkGRASYf:b6p0c28) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L78)):*
> ```Java
>         .setSubject("test subject")
>         .setBody("test body");
>     List<String> emails = Arrays.asList("bcc@example.com", "bcc1@example.com", "bcc2@example.com");
> ```

See below comment.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 83 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1H0bp7s77mmyepEho:-Me1H0bp7s77mmyepEhp:boarsog) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L83)):*
> ```Java
>     }
>     sendEmailService.sendEmail(contentBuilder.build());
>     Message message = getMessage();
> ```

Inline.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 87 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1H8xo-srYg6cpLAXB:-Me1H8xo-srYg6cpLAXC:bp7dkbl) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L87)):*
> ```Java
>         .asList()
>         .containsExactly(
>             new InternetAddress("bcc@example.com"), new InternetAddress("bcc1@example.com"),
> ```

Formatting looks off.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 121 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1FgHWDPVizyBgMhaP:-Me1FgHWDPVizyBgMhaQ:bbzt07c) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L121)):*
> ```Java
>         .setSubject("test subject")
>         .setBody("test body");
>     List<String> emails = Arrays.asList("cc@example.com", "cc1@example.com", "cc2@example.com");
> ```

These 4 lines can be expressed more simply as:

```
Stream.of("cc@example.com", "cc1@example.com", "cc2@example.com").map(InternetAddress::new).forEach(a -> contentBuilder.addCc(a));
```

or:

```
Stream.of("cc@example.com", "cc1@example.com", "cc2@example.com").forEach(a -> contentBuilder.addCc(new InternetAddress(a)));
```

Generally we shouldn't be using mutable lists unless explicitly called for, and you're not mutating the list here so it's not called for.  You could also use `ImmutableList.of()` instead of `Stream.of()` if you were going to retain the `for` loop, but no need for that.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 126 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1GVUm6ku3mWqCvgBX:-Me1GVUm6ku3mWqCvgBY:boarsog) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L126)):*
> ```Java
>     }
>     sendEmailService.sendEmail(contentBuilder.build());
>     Message message = getMessage();
> ```

Inline.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 130 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1G5856xxzDffZ5Nqv:-Me1G5856xxzDffZ5Nqw:b4cueqr) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L130)):*
> ```Java
>         .asList()
>         .containsExactly(
>             new InternetAddress("cc@example.com"), new InternetAddress("cc1@example.com"),
> ```

Formatting looks wrong.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 143 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1GXyx7yven2djeXbw:-Me1GXyx7yven2djeXbx:boarsog) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L143)):*
> ```Java
>             .build();
>     sendEmailService.sendEmail(content);
>     Message message = getMessage();
> ```

Inline.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 154 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1GZ0r2QjZOraVdbbj:-Me1GZ0r2QjZOraVdbbk:boarsog) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L154)):*
> ```Java
>     EmailMessage content = createBuilder().setCcs(ImmutableList.of()).build();
>     sendEmailService.sendEmail(content);
>     Message message = getMessage();
> ```

Inline.

**Review by rachelguan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1230)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 74 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1GfRF35v4HHxVwFhm:-Me1LkCL15JheImyikhs:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L74)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

This is a fluent API so you should combine these lines:

```
EmailMessage.Builder contentBuilder = EmailMessage.newBuilder()
    .setFrom(...)
    .setSubject(...)
    .setBody(...);
```

(formatting in that example might be off; do whatever auto-formatter does)
</blockquote></details>

Done.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 78 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1H-FN16LVtkGRASYe:-Me1aVJMD3LzZbk0KyNE:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L78)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

See below comment.
</blockquote></details>

Done.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 83 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1H0bp7s77mmyepEho:-Me1ML7y7j_a708-Za8S:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L83)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Inline.
</blockquote></details>

Done.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 87 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1H8xo-srYg6cpLAXB:-Me1OPqa3OgqJGxEqd-e:b-uftvgh) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L87)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Formatting looks off.
</blockquote></details>

will check in presubmit 
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 121 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1FgHWDPVizyBgMhaP:-Me1aUQD4P-g_k7Hdc8k:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L121)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

These 4 lines can be expressed more simply as:

```
Stream.of("cc@example.com", "cc1@example.com", "cc2@example.com").map(InternetAddress::new).forEach(a -> contentBuilder.addCc(a));
```

or:

```
Stream.of("cc@example.com", "cc1@example.com", "cc2@example.com").forEach(a -> contentBuilder.addCc(new InternetAddress(a)));
```

Generally we shouldn't be using mutable lists unless explicitly called for, and you're not mutating the list here so it's not called for.  You could also use `ImmutableList.of()` instead of `Stream.of()` if you were going to retain the `for` loop, but no need for that.
</blockquote></details>

Done.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 126 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1GVUm6ku3mWqCvgBX:-Me1NVeOCbSuFFkFF1HZ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L126)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Inline.
</blockquote></details>

Done.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 130 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1G5856xxzDffZ5Nqv:-Me1O7gM-KuqYkDUbZ2b:b6ss0fh) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L130)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Formatting looks wrong.
</blockquote></details>

ack. will check how presubmit goes. 
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 143 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1GXyx7yven2djeXbw:-Me1NcDJ-GsLP_MhxaT7:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L143)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Inline.
</blockquote></details>

Done.
___
*[util/src/test/java/google/registry/util/SendEmailServiceTest.java, line 154 at r3](https://reviewable.io/reviews/google/nomulus/1230#-Me1GZ0r2QjZOraVdbbj:-Me1NfCm2trUkjN9biNt:b-896fix) ([raw file](https://github.com/google/nomulus/blob/e61f0774a1691b5314b3100ff9321150bc0689da/util/src/test/java/google/registry/util/SendEmailServiceTest.java#L154)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Inline.
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1230#-:-Me5c5381judts5-cdfL:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
