### PR TITLE
Add activeOrDeletedSince parameter to RefreshDnsForAllDomainsAction

### PR DESCRIPTION
**Pull request by jicelhay**
This parameter will be used to enqueue refresh DNS tasks for domains with deletion time >= of its value. This to fix state of deleted domains that have failed calls in the past and are not being picked up by the system.

See b/364282239.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2548)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2548)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jicelhay)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2548#-O6RZvtg5HkN7c107lBD:-O6RZvtg5HkN7c107lBE:ba8wxgb) ([raw file](https://github.com/google/nomulus/blob/c750a376f1e7d6e353623179757aec6ce6cc6a4d/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L55)):*
> ```Java
>  * recommended to be somewhere between 200 and 500. The default value is 250.
>  *
>  * <p>If {@code deletionTime} is passed in the request, this action will enqueue DNS publish tasks
> ```

`&deletionTime=` as a parameter name doesn't quite get at the intent of what this new parameter does (and a naive reading of it would assume that it's only processing deleted domains, which is the opposite of what it's actually doing).  I might suggest instead using `&activeSince=`, as that most properly describes the intent of using this parameter, as in, "I want to refresh the DNS of all domains that were active since January 2023."
___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/2548#-O6R_NbE0njYcwuRCfV4:-O6R_NbE0njYcwuRCfV5:bceao9p) ([raw file](https://github.com/google/nomulus/blob/c750a376f1e7d6e353623179757aec6ce6cc6a4d/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L57)):*
> ```Java
>  * <p>If {@code deletionTime} is passed in the request, this action will enqueue DNS publish tasks
>  * on all domains with a deletion time equal or greater than the value provided and there's no
>  * guaranteed that they will be active. {@code deletionTime} will be set at 0:00:00 UTC zone for the
> ```

s/and there's no guaranteed that they will be active/including domains that have since been deleted/



_Code quote:_
```Java
 * on all domains with a deletion time equal or greater than the value provided and there's no
 * guaranteed that they will be active. {@code deletionTime} will be set at 0:00:00 UTC zone for the
```

**Review by jicelhay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2548)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2548#-O6RZvtg5HkN7c107lBD:-O6S7FmD-bnSpuu4EkJq:bv5no8x) ([raw file](https://github.com/google/nomulus/blob/c750a376f1e7d6e353623179757aec6ce6cc6a4d/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L55)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`&deletionTime=` as a parameter name doesn't quite get at the intent of what this new parameter does (and a naive reading of it would assume that it's only processing deleted domains, which is the opposite of what it's actually doing).  I might suggest instead using `&activeSince=`, as that most properly describes the intent of using this parameter, as in, "I want to refresh the DNS of all domains that were active since January 2023."
</blockquote></details>

Fair, but I also think that having a param named activeSince, with the caveat that "there's no guarantee that they will be active" is equally if not more confusing for readers.

What do you think of activeAt? I think that conveys that the domain was active at param value, but might have change status since.
___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 57 at r1](https://reviewable.io/reviews/google/nomulus/2548#-O6R_NbE0njYcwuRCfV4:-O6S7FC72SS0ASDct_GJ:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c750a376f1e7d6e353623179757aec6ce6cc6a4d/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L57)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

s/and there's no guaranteed that they will be active/including domains that have since been deleted/
</blockquote></details>

Done.
___
*[`core/src/main/java/google/registry/tools/server/ToolsServerModule.java` line 86 at r1](https://reviewable.io/reviews/google/nomulus/2548#-O6RYGqA5WQc9dz9GKjq:-O6S7E5LDjNPylHbS9P9:b-896fix) ([raw file](https://github.com/google/nomulus/blob/c750a376f1e7d6e353623179757aec6ce6cc6a4d/core/src/main/java/google/registry/tools/server/ToolsServerModule.java#L86)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

We use ISO 8601-formatted date strings globally throughout the codebase, definitely never `MM-dd-yyyy`.  Just use the same mechanism we use for other DateTime querystring paramters:  https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/request/RequestParameters.java;l=273-290;drc=49d2e34e12eed5ff52671a8dd747fb9c64522405  (and see usages of that method)
</blockquote></details>

Done.

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2548)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jicelhay)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2548#-O6RZvtg5HkN7c107lBD:-O6Se6YA5TnQp4gpzANZ:bd4rxhf) ([raw file](https://github.com/google/nomulus/blob/c750a376f1e7d6e353623179757aec6ce6cc6a4d/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L55)):*
<details><summary><i>Previously, jicelhay (Juan Celhay) wrote…</i></summary><blockquote>

Fair, but I also think that having a param named activeSince, with the caveat that "there's no guarantee that they will be active" is equally if not more confusing for readers.

What do you think of activeAt? I think that conveys that the domain was active at param value, but might have change status since.
</blockquote></details>

So I see where you're coming from, but `activeAt` is also not quite right, as it seems to imply that a domain was active at a given date in order to be refreshed, but this action will be refreshing domains that were created after that time (and thus were not active then).  What we really want is wording that captures the meaning of "active at any time since X".  Or alternatively, `notDeletedBefore`?  That's accurate, right?  A little strange to phrase the parameter negatively, but if that's the most accurate wording possible, then ...

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2548)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jicelhay)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2548#-O6RZvtg5HkN7c107lBD:-O6SfGDC4NJ4Kbe5SNbW:bjfywem) ([raw file](https://github.com/google/nomulus/blob/c750a376f1e7d6e353623179757aec6ce6cc6a4d/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L55)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

So I see where you're coming from, but `activeAt` is also not quite right, as it seems to imply that a domain was active at a given date in order to be refreshed, but this action will be refreshing domains that were created after that time (and thus were not active then).  What we really want is wording that captures the meaning of "active at any time since X".  Or alternatively, `notDeletedBefore`?  That's accurate, right?  A little strange to phrase the parameter negatively, but if that's the most accurate wording possible, then ...
</blockquote></details>

`activeOrDeletedSince` is accurate too, but wordier.

**Review by jicelhay — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2548)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[`core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java` line 55 at r1](https://reviewable.io/reviews/google/nomulus/2548#-O6RZvtg5HkN7c107lBD:-O6an6P_AL8grZr4ERhe:bkigrn7) ([raw file](https://github.com/google/nomulus/blob/c750a376f1e7d6e353623179757aec6ce6cc6a4d/core/src/main/java/google/registry/tools/server/RefreshDnsForAllDomainsAction.java#L55)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

`activeOrDeletedSince` is accurate too, but wordier.
</blockquote></details>

I prefer activeOrDeletedSince. notDeletedBefore might be confusing as well because readers might assume that it's deleted after that, which we know is not true.

**Review by jicelhay — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2548#-:-O6aoal78adOG8ear9EX:b-896fix)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @CydeWeys)

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2548#-:-O6bO2RH9-8lRBvy60-m:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved

**Review by CydeWeys — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jicelhay)

**Pull request closed without merging**
