### PR TITLE
Use the built-in replicaJpaTm() in RDAP

### PR DESCRIPTION
**Pull request by gbrodman**
This includes a test for the replica-simulating transaction manager and
removal of any replica-specific code in RDAP tests, because it's
unnecessary due to the existing tests.

---
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/1506)

### CODE REVIEW

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1506)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java, line 233 at r1](https://reviewable.io/reviews/google/nomulus/1506#-MuqfhL7DVtoP1kxHd1a:-MuqfhL7DVtoP1kxHd1b:b-pel7rk) ([raw file](https://github.com/google/nomulus/blob/b31fc5d9cca74ceff0abf9060655b8eb7c3f949d/core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java#L233)):*
> ```Java
>                     CriteriaBuilder criteriaBuilder =
>                         replicaJpaTm().getEntityManager().getCriteriaBuilder();
>                     CriteriaQueryBuilder<DomainBase> queryBuilder =
> ```


I think you need to take a closer look here -- `CriteriaQueryBuilder` itself contains calls to `jpaTm()`.

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1506)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java, line 233 at r1](https://reviewable.io/reviews/google/nomulus/1506#-MuqfhL7DVtoP1kxHd1a:-Muqgu5qAH2p-sMSwf3K:b-7g0701) ([raw file](https://github.com/google/nomulus/blob/b31fc5d9cca74ceff0abf9060655b8eb7c3f949d/core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java#L233)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

I think you need to take a closer look here -- `CriteriaQueryBuilder` itself contains calls to `jpaTm()`.
</blockquote></details>

yeah good point, this should be moved around a bit

**Review by CydeWeys — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1506)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @CydeWeys and @gbrodman)

___
*[core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java, line 45 at r2](https://reviewable.io/reviews/google/nomulus/1506#-MuvV_AWE5q9gTPbmbhH:-MuvV_AX44Nt_pSrqaEV:b4by3zk) ([raw file](https://github.com/google/nomulus/blob/efaa891d0696a543030df8bf99ff3395656a6504/core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java#L45)):*
> ```Java
>   private final CriteriaQuery<T> query;
>   private final Root<?> root;
>   private final EntityManager em;
> ```

Why are you doing the `EntityManager` here instead of the `TransactionManager`?  The latter seems more robust.
___
*[core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java, line 235 at r2](https://reviewable.io/reviews/google/nomulus/1506#-MuwJyTX7r666F6cVcO9:-MuwJyTX7r666F6cVcOA:b-7v49zo) ([raw file](https://github.com/google/nomulus/blob/efaa891d0696a543030df8bf99ff3395656a6504/core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java#L235)):*
> ```Java
>                     CriteriaBuilder criteriaBuilder = em.getCriteriaBuilder();
>                     CriteriaQueryBuilder<DomainBase> queryBuilder =
>                         CriteriaQueryBuilder.create(em, DomainBase.class)
> ```

Per my above suggestion, I think this looks nicer if it takes the tm rather than the em.  Then these few lines would just look like this, without the need for an inline em:

```
CriteriaBuilder criteriaBuilder = replicaJpaTm().getEntityManager().getCriteriaBuilder();
CriteriaQueryBuilder<DomainBase> queryBuilder = 
    CriteriaQueryBuilder.create(replicaJpaTm(), DomainBase.class)
    // ....
```

Seems nicer from callsites, and less to potentially get wrong.  Plus if `CriteriaQueryBuilder` does end up ever needing to use any methods off the tm instead of the em, the right one will be available, rather than either potentially using the wrong one by accident, or needing to do a refactor.
___
*[core/src/main/java/google/registry/rdap/RdapSearchActionBase.java, line 501 at r2](https://reviewable.io/reviews/google/nomulus/1506#-MuwKhLl08j1JqggkAPQ:-MuwKhLl08j1JqggkAPR:bn9w4w0) ([raw file](https://github.com/google/nomulus/blob/efaa891d0696a543030df8bf99ff3395656a6504/core/src/main/java/google/registry/rdap/RdapSearchActionBase.java#L501)):*
> ```Java
>     replicaJpaTm().assertInTransaction();
>     EntityManager em = replicaJpaTm().getEntityManager();
>     CriteriaQueryBuilder<T> builder = CriteriaQueryBuilder.create(em, clazz);
> ```

Yeah see, repeating these same three lines everywhere at all callsites just isn't nice.



_Code quote:_
```Java
    EntityManager em = replicaJpaTm().getEntityManager();
    CriteriaQueryBuilder<T> builder = CriteriaQueryBuilder.create(em, clazz);
    CriteriaBuilder criteriaBuilder = em.getCriteriaBuilder();
```

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1506)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @CydeWeys)

___
*[core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java, line 45 at r2](https://reviewable.io/reviews/google/nomulus/1506#-MuvV_AWE5q9gTPbmbhH:-MuwSA4sBrI4XFM4zSrJ:b-k5mhbp) ([raw file](https://github.com/google/nomulus/blob/efaa891d0696a543030df8bf99ff3395656a6504/core/src/main/java/google/registry/persistence/transaction/CriteriaQueryBuilder.java#L45)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Why are you doing the `EntityManager` here instead of the `TransactionManager`?  The latter seems more robust.
</blockquote></details>

Just to be more specific, since the creation of queries doesn't really seem to depend on transactional semantics. There's not really any harm in it though, I suppose. 
___
*[core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java, line 235 at r2](https://reviewable.io/reviews/google/nomulus/1506#-MuwJyTX7r666F6cVcO9:-MuwSLFh5NokpKeUHtu7:b-896fix) ([raw file](https://github.com/google/nomulus/blob/efaa891d0696a543030df8bf99ff3395656a6504/core/src/main/java/google/registry/rdap/RdapDomainSearchAction.java#L235)):*
<details><summary><i>Previously, CydeWeys (Ben McIlwain) wrote…</i></summary><blockquote>

Per my above suggestion, I think this looks nicer if it takes the tm rather than the em.  Then these few lines would just look like this, without the need for an inline em:

```
CriteriaBuilder criteriaBuilder = replicaJpaTm().getEntityManager().getCriteriaBuilder();
CriteriaQueryBuilder<DomainBase> queryBuilder = 
    CriteriaQueryBuilder.create(replicaJpaTm(), DomainBase.class)
    // ....
```

Seems nicer from callsites, and less to potentially get wrong.  Plus if `CriteriaQueryBuilder` does end up ever needing to use any methods off the tm instead of the em, the right one will be available, rather than either potentially using the wrong one by accident, or needing to do a refactor.
</blockquote></details>

Done.

**Review by CydeWeys — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/google/nomulus/1506#-:-MuwUjFv4jBL275LQDjX:bnfp4nl)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
