### PR TITLE
Fix minor alignment issue on console WHOIS page

### PR DESCRIPTION
**Pull request by gbrodman**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2166)

### CODE REVIEW

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2166)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`console-webapp/src/app/settings/whois/whois.component.scss` line 21 at r1](https://reviewable.io/reviews/google/nomulus/2166#-Nfqa1aX-Y45uXN7c3no:-Nfqa1aX-Y45uXN7c3np:b-jboa6r) ([raw file](https://github.com/google/nomulus/blob/302ebe5f86c3fd820f47bf5d3d93fb6240624beb/console-webapp/src/app/settings/whois/whois.component.scss#L21)):*
> ```SCSS
>     flex-wrap: wrap;
>     margin-bottom: 10px;
>     min-width: 460px;
> ```

I don't think that's gonna work so good on mobile, as I believe iphones still are in 376 - 410px range, so that's gonna render a pretty large scroll to accommodate. 
Can you see if just replacing `min-width` with an actual width for `.&__section-description` can do the trick? I believe it should

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2166)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/whois/whois.component.scss` line 21 at r1](https://reviewable.io/reviews/google/nomulus/2166#-Nfqa1aX-Y45uXN7c3no:-Nfqdk13ECw4TS_VyEqx:b-2vfsup) ([raw file](https://github.com/google/nomulus/blob/302ebe5f86c3fd820f47bf5d3d93fb6240624beb/console-webapp/src/app/settings/whois/whois.component.scss#L21)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I don't think that's gonna work so good on mobile, as I believe iphones still are in 376 - 410px range, so that's gonna render a pretty large scroll to accommodate. 
Can you see if just replacing `min-width` with an actual width for `.&__section-description` can do the trick? I believe it should
</blockquote></details>

it does, yeah -- I think I was probably using min-width as a cudgel to get it to go to only one column on very narrow screens

**Review by ptkach — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2166)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`console-webapp/src/app/settings/whois/whois.component.scss` line 21 at r1](https://reviewable.io/reviews/google/nomulus/2166#-Nfqa1aX-Y45uXN7c3no:-Nfqu6ZG8UlMNFENz2Hb:b-cz7lxz) ([raw file](https://github.com/google/nomulus/blob/302ebe5f86c3fd820f47bf5d3d93fb6240624beb/console-webapp/src/app/settings/whois/whois.component.scss#L21)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

it does, yeah -- I think I was probably using min-width as a cudgel to get it to go to only one column on very narrow screens
</blockquote></details>

I still see `min-width 460px` here which renders the scroll, that's why I saw a scroll previously. Would you like to fix it in this PR or in a separate one?

**Review by gbrodman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2166)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ptkach)

___
*[`console-webapp/src/app/settings/whois/whois.component.scss` line 21 at r1](https://reviewable.io/reviews/google/nomulus/2166#-Nfqa1aX-Y45uXN7c3no:-NfqvBpLA_ab076CjH48:b-7gtu1z) ([raw file](https://github.com/google/nomulus/blob/302ebe5f86c3fd820f47bf5d3d93fb6240624beb/console-webapp/src/app/settings/whois/whois.component.scss#L21)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

I still see `min-width 460px` here which renders the scroll, that's why I saw a scroll previously. Would you like to fix it in this PR or in a separate one?
</blockquote></details>

hmm yeah I get what you mean now, that phones nowadays tend to be like 410-420px

**Review by ptkach — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2166)* status: 1 of 2 files reviewed, all discussions resolved

**Review by ptkach — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gbrodman)

**Pull request merged**
