### PR TITLE
Add console users screen

### PR DESCRIPTION
**Pull request by ptkach**
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2576)

### CODE REVIEW

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2576)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @gbrodman)

___
*[`core/src/main/java/google/registry/config/files/default-config.yaml` line 376 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8bZTV41fkEGMtwBblv:-O8bZTV41fkEGMtwBblw:bqhxrol) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/core/src/main/java/google/registry/config/files/default-config.yaml#L376)):*
> ```YAML
>   - https://www.googleapis.com/auth/admin.directory.group
>   # View and manage users in Google Workspace
>   - https://www.googleapis.com/auth/admin.directory.user
> ```

My sandbox test confirmed missing scope.

**Review by gbrodman — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2576)* status: all files reviewed, 5 unresolved discussions (waiting on @ptkach)

___
*[`console-webapp/src/app/app-routing.module.ts` line 21 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8ciBwq7nDHWLigGRdu:-O8ciBwr7qunKD7hvt4o:b-lpdngp) ([raw file](https://github.com/google/nomulus/blob/bfd569ee44b2c7a1ec522e0e7c82712142720ccb/console-webapp/src/app/app-routing.module.ts#L21)):*
> ```XML
> import { HomeComponent } from './home/home.component';
> import { RegistryLockVerifyComponent } from './lock/registryLockVerify.component';
> import { NewOteComponent } from './ote/newOte.component';
> ```

why is it no longer necessary to import these?
___
*[`console-webapp/src/app/shared/directives/userLevelVisiblity.directive.ts` line 24 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cm7tj8k1lBDvI90i6:-O8cm7tj8k1lBDvI90i7:b-e2tkrz) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/shared/directives/userLevelVisiblity.directive.ts#L24)):*
> ```XML
> }
> 
> export const DISABLED_ELEMENTS_PER_ROLE = {
> ```

just double checking, this means we're only allowing access to FTEs for now? 

thoughts on how this will handle registrar PRIMARY_CONTACTs managing users for their own registrar?
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 171 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cnJid2-M_Kd7GSnbC:-O8cnJid2-M_Kd7GSnbD:bkchpcd) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/shared/services/backend.service.ts#L171)):*
> ```XML
>   createUser(registrarId: string): Observable<User> {
>     return this.http
>       .post<User>(`/console-api/users?registrarId=${registrarId}`, {})
> ```

should we be passing data? 
___
*[`console-webapp/src/app/users/users.component.ts` line 29 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cl53U1gj9yVghlEtn:-O8cl53VDBLsQ0ZZfTxF:bxtogv) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/users/users.component.ts#L29)):*
> ```XML
> export const columns = [
>   {
>     columnDef: 'email_address',
> ```

elsewhere we use camelCase for the column definitions and I think it makes sense to continue that here (especially since we return this as a map from the Java backend) 
___
*[`console-webapp/src/app/users/users.component.ts` line 78 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cnsPOBXivLXcbE3om:-O8cnsPOBXivLXcbE3on:byhnkjz) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/users/users.component.ts#L78)):*
> ```XML
> 
>   ngAfterViewInit() {
>     this.dataSource.sort = this.sort;
> ```

Does this just make it so that the sorting on the component reflects the sorting of the data source? I'm surprised that this doesn't happen inherently without us specifically mentioning it.

**Review by ptkach — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2576)* status: 12 of 16 files reviewed, 5 unresolved discussions (waiting on @gbrodman)

___
*[`console-webapp/src/app/app-routing.module.ts` line 21 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8ciBwq7nDHWLigGRdu:-O8gYl518PyyTegKFkgp:b-m7f25i) ([raw file](https://github.com/google/nomulus/blob/bfd569ee44b2c7a1ec522e0e7c82712142720ccb/console-webapp/src/app/app-routing.module.ts#L21)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

why is it no longer necessary to import these?
</blockquote></details>

It's been needed after - https://github.com/google/nomulus/pull/2539/files#diff-370748f4a9a20ba1c3e0eae2aa9c4281b2de82612433b7d15cbe0e2083c6b8e5

Wonder why it didn't failed checks though. For now we're good
___
*[`console-webapp/src/app/shared/directives/userLevelVisiblity.directive.ts` line 24 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cm7tj8k1lBDvI90i6:-O8gZIwa652eU_8_FyEF:b-jgjia9) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/shared/directives/userLevelVisiblity.directive.ts#L24)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

just double checking, this means we're only allowing access to FTEs for now? 

thoughts on how this will handle registrar PRIMARY_CONTACTs managing users for their own registrar?
</blockquote></details>

You're correct it's available only to FTEs for now, mainly because I still haven't confirmed it's working e2e as after this weeks released I only managed to find that scope is missing, which is not possible to add without another release.
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 171 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cnJid2-M_Kd7GSnbC:-O8gZYMS-8hssR-QJyVl:b57bebf) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/shared/services/backend.service.ts#L171)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

should we be passing data?
</blockquote></details>

ConsoleUsersAction gets it from query param 
___
*[`console-webapp/src/app/users/users.component.ts` line 29 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cl53U1gj9yVghlEtn:-O8gZcZIE-a4-xVtB5a2:b-896fix) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/users/users.component.ts#L29)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

elsewhere we use camelCase for the column definitions and I think it makes sense to continue that here (especially since we return this as a map from the Java backend)
</blockquote></details>

Done.
___
*[`console-webapp/src/app/users/users.component.ts` line 78 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cnsPOBXivLXcbE3om:-O8gZd3u-bE4-8fIRpxy:bsm8cg2) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/users/users.component.ts#L78)):*
<details><summary><i>Previously, gbrodman wrote…</i></summary><blockquote>

Does this just make it so that the sorting on the component reflects the sorting of the data source? I'm surprised that this doesn't happen inherently without us specifically mentioning it.
</blockquote></details>

Yeah it just hooks up `MatSort` to MatTable. Why would it happen automatically? I mean what if you don't need sorters on your table?

**Review by gbrodman — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2576)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ptkach)

___
*[`console-webapp/src/app/shared/directives/userLevelVisiblity.directive.ts` line 24 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cm7tj8k1lBDvI90i6:-O8gqn0B-nZxOzgXHdnX:b-ndashh) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/shared/directives/userLevelVisiblity.directive.ts#L24)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

You're correct it's available only to FTEs for now, mainly because I still haven't confirmed it's working e2e as after this weeks released I only managed to find that scope is missing, which is not possible to add without another release.
</blockquote></details>

Gotcha. Makes sense! 
___
*[`console-webapp/src/app/shared/services/backend.service.ts` line 171 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cnJid2-M_Kd7GSnbC:-O8gq7XuDCmJJSEteLxb:b-w2dz5d) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/shared/services/backend.service.ts#L171)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

ConsoleUsersAction gets it from query param
</blockquote></details>

derp, I forgot that (at least for now) we are hardcoding the names / email addresses of the users that we're creating. 

if we wanted to allow them to specify an email address, of course we'd need to pass more data 
___
*[`console-webapp/src/app/users/users.component.ts` line 78 at r1](https://reviewable.io/reviews/google/nomulus/2576#-O8cnsPOBXivLXcbE3om:-O8gqLmx2ckeHayyXuhv:bgguls5) ([raw file](https://github.com/google/nomulus/blob/1e7d34fa699661715dd92674c2fb42bf8a14f514/console-webapp/src/app/users/users.component.ts#L78)):*
<details><summary><i>Previously, ptkach (Pavlo Tkach) wrote…</i></summary><blockquote>

Yeah it just hooks up `MatSort` to MatTable. Why would it happen automatically? I mean what if you don't need sorters on your table?
</blockquote></details>

I guess I was assuming that the MatTableDataSource would have the sorting built in but eh, I guess not.

**Pull request merged**
