### PR TITLE
Checks flyway deadlock risk for new schema chagnes

### PR DESCRIPTION
**Pull request by weiminyu**
Verified that test works as intended whether a PR has schema change or not.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/nomulus/2078)

### CODE REVIEW

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2078)* status: all files reviewed, 7 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[`db/README.md` line 62 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_j8Ypi56HR1QetHcBT:-N_j8Ypi56HR1QetHcBU:b-vutwvb) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/README.md#L62)):*
> ```Markdown
>     or sequence), it MAY hit deadlocks when applied on sandbox/production where
>     it'll be competing against live traffic that may also be locking said
>     elements but in a different order. The `FlywayDeadlockTest` checks this risk
> ```

checks for
___
*[`db/README.md` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_jAGnU2HoGT1UvmLFA:-N_jAGnU2HoGT1UvmLFB:bi7ymhx) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/README.md#L69)):*
> ```Markdown
>     *   A schema element (table, index, or sequence) being altered.
>     *   The table on which an index is created synchronously (i.e., not with
>         with the `concurrently` modifier). Please refer to
> ```

The terminology is a bit confusing to me. Isn't "synchronous" and "concurrent" synonymous? 
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 77 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_jW1tl1BO2ZzlFBYWM:-N_jW1tl1BO2ZzlFBYWN:btvrxi2) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L77)):*
> ```Java
>   private static final String GIT_GET_ROOT_DIR_CMD = "git rev-parse --show-toplevel";
> 
>   // Returns the commit hash when the current branch branches off 'main'.
> ```

If we want to avoid the use of "master", we can just say "the main branch" here, as the actual branch name is not "main".

Also, not everyone names their remote repo "origin", even though it is the default. Maybe just using "master" here should suffice? You do need your local master to be up-to-date, but same goes for the remote master which you need to fetch from time to time anyway.
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 110 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_o7Gsb6stMRiz-m9-G:-N_o7Gsb6stMRiz-m9-H:b-9dcbeu) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L110)):*
> ```Java
>   public void validateNewFlywayScripts() {
>     ImmutableList<Path> newScriptPaths = findChangedFlywayScripts();
>     ImmutableList<String> errors =
> ```

The list does not strictly speaking contain errors. It contains locked elements. It's in this test that you assert if a file contains more than one locked elements it should be an error.

I'd just call it `lockedElements`.
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 176 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_o3UFu7a5K5rW6W-Bz:-N_o3UFu7a5K5rW6W-C-:b-c38bg) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L176)):*
> ```Java
>                       .collect(Collectors.joining()))
>               .collect(toImmutableList());
>       return sqls.stream()
> ```

Why collecting the stream to a list and then immediately convert it back to a stream?
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 177 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_o4PZZAD2Q7on6AuRS:-N_o4PZZAD2Q7on6AuRT:b-b4qtus) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L177)):*
> ```Java
>               .collect(toImmutableList());
>       return sqls.stream()
>           .map(line -> line + ";")
> ```

Are you doing this because there could be multi-line statement in the flyway script? So you have to concatenate every line, split by semi-colon, then add a semi-colon to each line? Seems a little convoluted... 
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 232 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_jlyQH1hsJNw6GfSGO:-N_jlyQH1hsJNw6GfSGP:b-glav1o) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L232)):*
> ```Java
>     String error = new String(process.getErrorStream().readAllBytes(), UTF_8);
>     try {
>       process.waitFor(1, TimeUnit.MILLISECONDS);
> ```

Isn't 1ms too short of a timeout? I feel like something like 1s is more appropriate for an external process.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2078)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[`db/README.md` line 62 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_j8Ypi56HR1QetHcBT:-N_sw2_28Qb20SR_8bav:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/README.md#L62)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

checks for
</blockquote></details>

Done.
___
*[`db/README.md` line 69 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_jAGnU2HoGT1UvmLFA:-N_sw3iA0aiWAj03pdI0:b-qj92pf) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/README.md#L69)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The terminology is a bit confusing to me. Isn't "synchronous" and "concurrent" synonymous? 
</blockquote></details>

Reworded.
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 77 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_jW1tl1BO2ZzlFBYWM:-N_swsGQ9nqE5pzV_Irn:b-hghkgo) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L77)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

If we want to avoid the use of "master", we can just say "the main branch" here, as the actual branch name is not "main".

Also, not everyone names their remote repo "origin", even though it is the default. Maybe just using "master" here should suffice? You do need your local master to be up-to-date, but same goes for the remote master which you need to fetch from time to time anyway.
</blockquote></details>

Changed `main`.

As for origin/master, the `master` part is also specific to us. The same command is used by java-format check. If someone complains, or we decide to change our naming, we can do them together.
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 110 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_o7Gsb6stMRiz-m9-G:-N_sxvs72kXjLoG1YJda:b-7v2due) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L110)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

The list does not strictly speaking contain errors. It contains locked elements. It's in this test that you assert if a file contains more than one locked elements it should be an error.

I'd just call it `lockedElements`.
</blockquote></details>

It contains error messages. Scripts with only one locked element is `filter`ed out.
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 176 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_o3UFu7a5K5rW6W-Bz:-N_t0b0a-GKH9QvUJ7BL:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L176)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Why collecting the stream to a list and then immediately convert it back to a stream?
</blockquote></details>

Done.
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 177 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_o4PZZAD2Q7on6AuRS:-N_t2gEu4yONixjiwKuk:bub7zv) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L177)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Are you doing this because there could be multi-line statement in the flyway script? So you have to concatenate every line, split by semi-colon, then add a semi-colon to each line? Seems a little convoluted... 
</blockquote></details>

Modified regex pattern to avoid this.
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 232 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_jlyQH1hsJNw6GfSGO:-N_t2wTJ92aHKPKnJjph:b1qzz91) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L232)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Isn't 1ms too short of a timeout? I feel like something like 1s is more appropriate for an external process. 
</blockquote></details>

Increased a bit. By now both output and error streams have been closed by the shell process. A simple context switch should be enough.

**Review by jianglai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2078)* status: all files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @weiminyu)

___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 92 at r1](https://reviewable.io/reviews/google/nomulus/2078#-NaHcEHTCfclWJ6ST0ON:-NaHcEHTCfclWJ6ST0OO:bgndwfo) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L92)):*
> ```Java
>                   + "(IF\\s+NOT\\s+EXISTS\\s+)*(public.)?((\\w+)|(\"\\w+\"))\\s+ON\\s+(ONLY\\s+)?"
>                   + "(public.)?((\\w+)|(\"\\w+\"))[^;]+;",
>               MULTILINE | CASE_INSENSITIVE),
> ```

I don't think it is necessary now. You removed all empty lines and concatenated the content, then split the string on ";", so each line that is being matched by the pattern is just a single line without any terminator, is that right?
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 110 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_o7Gsb6stMRiz-m9-G:-NaDFB2ZBa8MXOo-yy08:b-z7y1r7) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L110)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

It contains error messages. Scripts with only one locked element is `filter`ed out.
</blockquote></details>

Yes, I understand that they are filtered out. What I meant was that the content stored in this variable is just a list of paths that contains more then one elements, not error messages themselves. But I'll leave this to you.
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 232 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_jlyQH1hsJNw6GfSGO:-NaHdArS6MH_FSSuB-6t:b-z8ayo4) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L232)):*
<details><summary><i>Previously, weiminyu (Weimin Yu) wrote…</i></summary><blockquote>

Increased a bit. By now both output and error streams have been closed by the shell process. A simple context switch should be enough.
</blockquote></details>

Ah, good point on both streams being closed. But I'd still think a longer timeout is helpful in fighting flakes. In most cases this statement should immediately return, but in the rare instance where it takes a bit longer for the process to finish, we'd rather wait a bit longer, rather than proceed and throw when `process.exitValue()` is called.

**Review by weiminyu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2078)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @CydeWeys and @jianglai)

___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 92 at r1](https://reviewable.io/reviews/google/nomulus/2078#-NaHcEHTCfclWJ6ST0ON:-NaHr2NS2R-4j2rT6ujn:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L92)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

I don't think it is necessary now. You removed all empty lines and concatenated the content, then split the string on ";", so each line that is being matched by the pattern is just a single line without any terminator, is that right?
</blockquote></details>

Done.
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 110 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_o7Gsb6stMRiz-m9-G:-NaHfRc45LfW95ZSi1sb:bb6un1j) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L110)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Yes, I understand that they are filtered out. What I meant was that the content stored in this variable is just a list of paths that contains more then one elements, not error messages themselves. But I'll leave this to you.
</blockquote></details>

Done
___
*[`db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java` line 232 at r1](https://reviewable.io/reviews/google/nomulus/2078#-N_jlyQH1hsJNw6GfSGO:-NaHf3uZ15hSrX9b2VW_:b-896fix) ([raw file](https://github.com/google/nomulus/blob/f1098adfc411e5582561dbfa3453db5987626882/db/src/test/java/google/registry/sql/flyway/FlywayDeadlockTest.java#L232)):*
<details><summary><i>Previously, jianglai (Lai Jiang) wrote…</i></summary><blockquote>

Ah, good point on both streams being closed. But I'd still think a longer timeout is helpful in fighting flakes. In most cases this statement should immediately return, but in the rare instance where it takes a bit longer for the process to finish, we'd rather wait a bit longer, rather than proceed and throw when `process.exitValue()` is called.
</blockquote></details>

Done.

**Review by jianglai — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/nomulus/2078)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @CydeWeys)

**Pull request merged**
